### ISSUE TITLE
Peer Ranked algorithms (mind expert) aren't working according to description.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1000]
Here is the description of the peer ranking algorithm (accessible from the algorithm info link on the side bar):
https://canonizer.com/topic/53-Canonizer-Algorithms/19-Peer-Ranking-Algorithms.

item #2: “Each pirate only ever votes for his self” problem, when a popular expert votes for at least one other person, besides themselves, their vote is multiplied by 5 resulting in a significant penalty for only voting for “his self”."

Is not working.  Everyone is getting the same score, even if they vote for someone else.  If they vote for someone, besides themselves, their score should be multiplied by 5.  If they don't, they don't get that reward.

**Comment by BrentAllsop** [comment]
OH, I see what you are saying.  So the second one I opened was a duplicate of the already existing one?

**Comment by rupalichavan9860** [comment]
@karun0607gautam This is still not working .I have added comment in issue #1077

**Comment by rupalichavan9860** [comment]
@BrentAllsop Score looks okay to me .Can you please test once?

**Comment by BrentAllsop** [comment]
There are still problems with this.
See issue #1077 for a description of the remaining issues.

**Comment by karun0607gautam** [comment]
@BrentAllsop  can you please check mind expert algorithm changes

**Comment by BrentAllsop** [comment]
Yes, these are now working, so closing this issue.
