### ISSUE TITLE
Page crash on browse page when applied 'As of date' filter for Mac OS

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1001]
For logged in and non -logged in users
Steps: 

1. Click on browse
2.  apply 'As of date' filter, choose a date
3. Now click 'default'
4. Now again click on 'As of date'
Page crashed

This is due to the date format being different for 'As of date' on  Mac OS as dd/mm/yyyy
& for windows the date format on 'As of date' is mm/dd/yyy

![Screenshot 2021-12-16 at 11 19 36 AM](https://user-images.githubusercontent.com/91254708/146319349-625ecf1b-c5bb-4f12-9bb3-cdbfc6a7060a.png)

![Screenshot 2021-12-16 at 11 45 27 AM](https://user-images.githubusercontent.com/91254708/146319380-5218460e-4014-4848-a766-b3615e09c38e.png)

![image_2021_12_16T06_17_05_456Z](https://user-images.githubusercontent.com/91254708/146319481-7a81d9dc-6329-4c87-852a-6cf0ac47cd63.png)

**Comment by saniatg** [comment]
This issue is on browse page for 'As of date' for date which greater than 12 .

Go to https://staging.canonizer.com/browse
When choose date in 'As of filter' as 23/12/2022, then click on default , then again click on 'As of date' 
Page will crash

**Comment by saniatg** [comment]
@HamzaBinMansoor Still getting page crash macOS Monterey. 
![Screenshot 2022-01-07 at 1 31 52 PM](https://user-images.githubusercontent.com/91254708/148511697-cdac5f93-f1ab-4ce6-b754-b2190eaca691.png)

**Comment by sunilspr7** [comment]
@saniatg  and @rupalichavan9860  this ticket related to #1070 and ticket #1070 solved. so please test and let me know.

**Comment by saniatg** [comment]
Crash issue is resolved on mac and is working fine .

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested and verified on production and is working fine. 
Date format as discussed is yyyy/mm/dd

**Comment by rupalichavan9860** [comment]
Verified
