### ISSUE TITLE
Incorrect child camp names under supported camps

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1007]
Steps:

1. Create a new topic 
2. Create camps in the order shown in the screenshot
![Screenshot 2021-12-20 at 1 33 13 PM](https://user-images.githubusercontent.com/91254708/146733077-1fa167e8-eaf2-448b-ac93-6b58b2183988.png)
3- Support child camp 'camp4'
4-Login from another user and navigate to same topic and delegate your support to 'camp4'
5-Now come back to Canonizer Sorted Camp Tree and again click on camp4 and click 'Directly join or Support ' button 

Actual result- topic names are seen instead of child name
Expected result- child camp names must be seen

![Screenshot 2021-12-20 at 12 39 50 PM](https://user-images.githubusercontent.com/91254708/146733762-45d1d072-964b-4a81-98df-1b4ab4191331.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
