### ISSUE TITLE
Page crash on forgot password page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1009]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Click on Log in
3. Click on Forgot Password
4. Enter valid email address

Actual Result :  Getting below page crash

![image](https://user-images.githubusercontent.com/40416610/146737792-febcee68-4728-456d-8140-c683718df3fa.png)

**Comment by kshitij1326** [comment]
@rupalichavan9860  this was due to migration on staging server. Please check again.

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine now
