### ISSUE TITLE
Date format is  different for Mac OS and for Windows for 'As of Date' filter

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1011]
1. Go to https://staging.canonizer.com/browse
2. Click on 'As of Date' on Mac OS date format is shown  as dd/mm/yyyy
3. & for windows the date format on 'As of date' is mm/dd/yyyy

Date format must be same
![Screenshot 2021-12-20 at 6 53 41 PM](https://user-images.githubusercontent.com/91254708/146773907-56a09e95-a562-4bc8-866f-a2f296f42ab7.png)

**Comment by saniatg** [comment]
@HamzaBinMansoor The date format still shows dd/mm/yyyy in mac.  Should be mm/dd/yyyy
![Screenshot 2022-01-07 at 1 00 19 PM](https://user-images.githubusercontent.com/91254708/148508152-5e50be56-0073-42d2-9261-007195b5d157.png)

**Comment by sunilspr7** [comment]
@saniatg and @rupalichavan9860 this ticket related to #1070 and ticket #1070 solved. so please test and let me know.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Date format is yyyy/mm/dd now.

**Comment by rupalichavan9860** [comment]
Verified
