### ISSUE TITLE
Getting page crash on Canonizer Main Page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1012]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Go to canonizer main page 
3. Select "Mind Experts" algorithm from left panel 
4. Observe result 

Actual Result : 
It is taking more time to load the page .Also page layout is getting disturbed with page crash at bottom of the page

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/146780937-2d994fa4-d9e1-4299-9522-6f9afc2c88fd.png)

**Comment by rupalichavan9860** [comment]
As of now it is working fast than previous with no page crash

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested and is working fine on Production.
