### ISSUE TITLE
Page crash on Remove support button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1013]
Please refer below scenario : 

![image](https://user-images.githubusercontent.com/40416610/146882151-2aa2f564-3a6c-4522-9d30-595eb0f1507c.png)

Getting below page crash when user "RC" click on "Remove your support" button

![image](https://user-images.githubusercontent.com/40416610/146882233-d7b04279-88a0-4242-8383-69005ca4bcf6.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860  Tested and verified on production

**Comment by rupalichavan9860** [comment]
Verified
