### ISSUE TITLE
Validation error message missing on sign up page for password field 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1018]
1. Go to https://staging.canonizer.com/signup
2. Add all mandatory fields except Password, Confirm password & captcha
3. Now click on 'Submit' button

Issue 1-> Validation error message for 'Password' field is missing
Issue 2-> For  'Confirm Password' field error message is incorrect ->should be" ConfIrm password field is required "  NOT" The password field is required.

![Screenshot 2021-12-21 at 7 44 48 PM](https://user-images.githubusercontent.com/91254708/146945235-ddc7da0b-33b1-4aa6-84e7-6884645dbace.png)

**Comment by saniatg** [comment]
Please note :All validation messages of password fields are displaying after confirm password field.  Validation messages for the particular fields must be displayed below that fields only.
![Screenshot 2021-12-24 at 12 24 27 PM](https://user-images.githubusercontent.com/91254708/147327550-f322bc66-6b0f-4baa-86ad-42c06c47d174.png)

**Comment by anilPodi** [comment]
Validations for password and captcha are working but where as confirm password is not displaying error message.
And also displays the following in password validation field (The password confirmation does not match.) this need to be changed to confirm the password field. 

after giving the correct password and wrong confirm password, this (The password confirmation does not match.) displaying for 30 secs and vanishes.

**Comment by saniatg** [comment]
Verified and is working fine

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
