### ISSUE TITLE
Incorrect topic name is displaying in removed delegated support email and camp name is missing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1019]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/
2. Login with valid email and password(User A)
3. Create new topic and create new camp
4. Support camp
5. Login with another user(User B) and delegate support to User A
6. Remove delegate support
7. Observe emails of both users 

User A(Direct Supporter) Email : 
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/146980827-b2a401c1-4693-41e2-bc1c-36eec013dc9b.png)

User B(Delegated supporter) Email : 
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/146980962-e1e5a8ca-b2f6-4c50-8dfe-0d5d6d0c51fc.png)

**Comment by rupalichavan9860** [comment]
Also Reena addressed this issue , as User B is a Delegated supporter the content  "You are receiving this e-mail because: You are directly supporting " should be removed from mail 

@gautamv16 @BrentAllsop Can you please confirm

**Comment by anilPodi** [comment]
when  I checking (Login with another user(User B) and delegate support to User A). this is how the screening is displaying even after refresh.

![Screenshot from 2022-01-03 14-46-14](https://user-images.githubusercontent.com/96222726/147915754-82b9f53f-b414-40e5-a8e9-628d57640f06.png)

**Comment by rupalichavan9860** [comment]
@nalwa Getting this email screen while adding and removing support/delegated support

![image](https://user-images.githubusercontent.com/40416610/147916132-645207ff-7547-48d0-a0f5-43194ec10d9c.png)


![image](https://user-images.githubusercontent.com/40416610/147916175-cc9a4eba-9a4c-4dd0-a536-12eca4e152ec.png)

**Comment by rupalichavan9860** [comment]
Also getting below page crash on reloading page 

![image](https://user-images.githubusercontent.com/40416610/148178836-f41ca0be-01a4-4d53-b8ee-7b39b82163b1.png)

**Comment by anilPodi** [comment]
@rupalichavan9860 working fine for me, please check and confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
