### ISSUE TITLE
Confirmation Page or resetlinksent page contents should be proper.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#102]
Every bullet-ed sentence under "Note: If you do not receive the email in few minutes:" must start with Capital letter.
![image](https://user-images.githubusercontent.com/40416610/42026252-41bcc11a-7ae4-11e8-84e5-aeaadb927d26.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test and close all ASAP

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.still not fixed please check
![image](https://user-images.githubusercontent.com/40416610/42168000-6a47d682-7e2d-11e8-81b1-1e43b35c7c90.png)
