### ISSUE TITLE
As of date : Date format is displaying different after selecting date

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1020]
Note :  Device : Mac
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse
4. Select as of date as "1 dec 2021" 
5. Click on as of date text box again and observe date 

Expected  Result :  It should display selected date 

Actual Result : It is displaying date as "12 jan 2021". Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/147040405-4b6cda39-bcc1-4ac6-80e0-db6c4de7be39.png)

Note : Facing this issue for dates <12 as it is considering 1-12 as month instead of date
i.e When user select as of date as "1 dec 2021" , it is displaying "12 jan 2021"
When user select as of date as "2 dec 2021" , it is displaying "12 feb 2021"

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor Issue is not fixed yet

**Comment by sunilspr7** [comment]
@saniatg and @rupalichavan9860 this ticket related to #1070 and ticket #1070 solved. so please test and let me know.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Working fine on Production

**Comment by rupalichavan9860** [comment]
Verified
