### ISSUE TITLE
Page Crash when session expires on Edit thread page 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1023]
When user is on edit thread page and the application is left idle then after sometime on click 'List of All Threads Camps' link page crashes. 

User must be redirected to login after session expires.

![Screenshot 2021-12-22 at 6 18 30 PM](https://user-images.githubusercontent.com/91254708/147095242-f3ee63f5-2f9a-4be2-8325-1d347b0f9201.png)

![Screenshot 2021-12-22 at 4 09 44 PM](https://user-images.githubusercontent.com/91254708/147095290-49b9483f-604e-4f11-9564-c04e5878ed12.png)

**Comment by saniatg** [comment]
Verified and working fine

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested & verified on Production.

**Comment by rupalichavan9860** [comment]
Verified on production
