### ISSUE TITLE
Promoted to a direct supporter mail is broken

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1024]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/147098712-cc7a94b5-c3b3-42e9-bd22-87ab304d9dfe.png)

Spelling of "Promoted" is displaying incorrect in subject i.e "promted"

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production

**Comment by rupalichavan9860** [comment]
Verified on production
