### ISSUE TITLE
Delegated support is not getting removed from agreement camp when their direct supporter supports child camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1025]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create topic with User A(Support is getting added to agreement camp)
4. Login with another user "User B" and delegate support to User A in Agreement camp
5. log out and login with "User A" and create new camp under agreement camp and support it

Actual Result : 
User B is now direct supporter of agreement camp and delegated supporter of child camp

**Comment by rupalichavan9860** [comment]
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/147182630-78af6a07-ddfc-4d65-94a0-4c2b6bc65009.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested,for me it's working . You can move this ticket to " staging approved "

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
