### ISSUE TITLE
Incorrect preference number displaying when delegated supporter promoted as direct supporter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1026]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps under topic
4. Support all 3 camps by User A
5. Login with User B and delegate support to User A
6. Login with User A 
7. Go to manage support and click on Remove all and click on submit

User B is promoted as a direct supporter in one camp but preference number is displaying as "2". Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/147219600-3d6e10c7-370e-4f1e-9533-bf50cda3e6d9.png)

**Comment by anilPodi** [comment]
Working fine but getting emails screen

**Comment by rohit-talentelgia** [comment]
@anilPodi 

Kindly share the screenshot of the issue.

**Comment by anilPodi** [comment]
![Screenshot from 2022-01-03 15-36-11](https://user-images.githubusercontent.com/96222726/148051574-8a511765-8775-403a-84ff-0a72dc8391ce.png)

**Comment by rupalichavan9860** [comment]
Verified on production
