### ISSUE TITLE
Delegated supporter is not getting promoted as a direct supporter when direct supporter removes their support from all camps 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1028]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password(User A)
3. Create new topic and create new camp (Camp 1)
4. Support Camp 1(By User 1)
5. Logout and login with 4-5 different users and delegate support like below 

![image](https://user-images.githubusercontent.com/40416610/147320715-f05b7b11-5fd0-46fd-b5db-9dff6c10449b.png)

6. Now Login with User A again and create new camp (Camp 2)

Note : We can see same support tree like for Camp 1

Issue : 
When direct supporter removes support from both Camp 1 and Camp 2 at the same time(Go to manage support and click on Remove all->submit), delegated supporter promoted as direct supporter in Camp 1 but not in Camp 2  and score of Camp 2 becomes "0"

**Comment by nalwa** [comment]
@rupalichavan9860  Issue is :- delegated supporter is not getting promoted as direct supporter for all camps when direct supporter is removing support from all camps at once (same time by selecting remove all). In that case its only promoted as direct supporter for one camp. 
I am working on it.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
