### ISSUE TITLE
Validations are missing for Password fields on Reset New Password page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#103]
Expected Result:
Password must be combination of characters,numbers and special symbols.It must contains at least one special character.
Actual Result:
Password field is accepting only numbers/only characters/only alphanumeric.
Steps to reproduce:
1.Go to https://staging.canonizer.com/     
2.Click on Log in     
3.Click on "Forget Password" link     
4.Enter Email and click on "Submit" button.This will sent password reset link to entered email     
5.Open mail and click on "Click Here To Reset Password".This will redirect to https://staging.canonizer.com/resetpassword     
4.Do following scenarios for Password field:          
a.Enter only characters in   Password field or          
b.Enter only numbers in Password   field or          
c.Enter alphanumeric text in   Password field     
6.Enter mandatory fields and click on "Reset"

**Comment by gautamv16** [comment]
@rupalichavan9860 done pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Validations are working properly

**Comment by rupalichavan9860** [comment]
@gautamv16 Confirm Password on Reset New Password page should be encrypted 

Actual Result : 
Confirm Password is not displaying encrypted password.

![image](https://user-images.githubusercontent.com/40416610/45085318-02dd6880-b11e-11e8-9222-2c7741976998.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 While performing negative testing I found the following issue
Password field is accepting spaces in password(leading,trailing or anywhere in password)
e.g. "  test@12345","test@12 12","test@12345  "

**Comment by gautamv16** [comment]
Passwords can have spaces. Space is a ASacci code which can be used for
password, even it will be more secure. And when u do testing again then if
u have such doubts creates each time new issue as this is not related to
this ticket.

**Comment by gautamv16** [comment]
@rupalichavan9860  pls check this and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Confirm Password is now displaying in encrypted form.So closing this issue
