### ISSUE TITLE
Shows a blank camp statement history page for agreement page with only status labels

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1033]
URL- https://staging.canonizer.com/statement/history/276/1

Trying  to reproduce the issue.

![Screenshot 2021-12-24 at 6 22 32 PM](https://user-images.githubusercontent.com/91254708/147356122-f0315509-4e59-469c-82c0-4b2c277d7873.png)

**Comment by rupalichavan9860** [comment]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A
3. Create New topic(Support getting added for Agreement camp)
4. Log out and login with User B
5. Support Agreement camp
6. Click on "Add Camp Statement" and do not commit changes
7. Log out and Login with User A again 
8. Click on Manage/Edit Camp Statement 
9. Observe page

**Comment by saniatg** [comment]
Now the empty page is not showing , instead a message "No statement history available or it might be possible a user has added a statement but it is in review state". is showing. 
@BrentAllsop if you can kindly confirm whether the message is correct or need changes.
![Screenshot 2022-01-17 at 10 24 10 AM](https://user-images.githubusercontent.com/91254708/149712613-71438d88-1812-4d41-b5a9-51819c557f16.png)

**Comment by rohit-talentelgia** [comment]
@sunnyjindal @dakshiffort , kindly look into this ticket.

**Comment by sunnyjindal** [comment]
There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state. @rohit-talentelgia @saniatg

**Comment by saniatg** [comment]
@rupalichavan9860 The text message has been changed to "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state." and is working fine

**Comment by rupalichavan9860** [comment]
Verified
