### ISSUE TITLE
Long Text in the Camp Text field is overlapping the "Undo" button Text and remove icon 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#1034]
Steps to reproduce :

Login with User A and Create new topic
Create camp (with Lengthy name)
Support This camp 
You will notice that remove icon overlapping with camp name 
Same case when user remove any support "Undo" text overlapping with camp name
![Design Bug 2](https://user-images.githubusercontent.com/92429083/147451242-97305901-1960-40cd-9aae-14ba3913548c.png)
![Design Bug](https://user-images.githubusercontent.com/92429083/147451342-375338b1-51d8-4b92-ae8e-9469a96b148c.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified . You can move this to "staging approved "

**Comment by rupalichavan9860** [comment]
Verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production.

**Comment by rupalichavan9860** [comment]
Verified
