### ISSUE TITLE
Mobile devices : Submit button on Edit thread page is not inline with other fields 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1036]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/147467912-47898540-6b1c-4b8e-87b1-77adb56245e5.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 This is fixed .You can move this to " Staging Approved "

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
