### ISSUE TITLE
Incorrect warning while supporting sibling camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1037]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic, create new camp (camp 1) and create camp hierarchy like below

![image](https://user-images.githubusercontent.com/40416610/147479851-7b561bb2-a695-472a-aa5f-ac044db56316.png)

4. Support last sub camp(User is now supporting sub camp 3 )
5. Create Another camp under Agreement camp(camp 2)
6. Click on "Directly Join and Support"
7. Observe warning

Expected Result : It should not display any warning message 

Actual Result : It is displaying warning message "Warning! You are directly supporting one or more camps under this topic. If you continue your direct support will be removed." even if nothing is getting removed

Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/147480540-fe3c91ea-263a-4e74-8741-3c2c4233d03f.png)

**Comment by saniatg** [comment]
Also I found another issue where warning message is not showing.
Case: When a delegated user tries to support a camp directly, in this case warning message is not showing

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have tested above mentioned scenarios and they are fixed now. You can move this to " Staging Approved "

**Comment by rupalichavan9860** [comment]
This is not working in below scenario : 
![image](https://user-images.githubusercontent.com/40416610/148550232-209a4e5c-6665-4ab2-9b8d-8c26d0a2f6e8.png)

"Rupali N" is delegating support to "Rupali cano" in this 2 camps "camp 1" and "camp 3"
Now trying to support third camp "camp 2" directly (Who have no supporters see below )
![image](https://user-images.githubusercontent.com/40416610/148550523-1a7e0d9a-fb2d-43d0-bd3a-aee17f998d57.png)

Actual Result : 
Warning is missing while supporting third camp "camp 3"
"Warning! You have already delegated your support for to user Rupali cano. If you continue your delegated support will be removed." --This warning should be present

![image](https://user-images.githubusercontent.com/40416610/148550599-d8eb402f-971d-4bd0-a5db-30fda5fe13f9.png)

**Comment by rupalichavan9860** [comment]
@nalwa I found some minor issues in emails : 
1 . Need to remove camp name from delegated support email . Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/149295335-86399306-2022-4dd8-8ad0-94a197288f9f.png)

2. Link to nick names are missing in old emails 

![image](https://user-images.githubusercontent.com/40416610/149295609-776fd28c-53d0-4c76-99a8-92b22696771f.png)

3. Removed  delegated support subject is different for different users

![image](https://user-images.githubusercontent.com/40416610/149295839-d67cdaca-6ee4-4d7f-a7f8-ca7ff8ed4189.png)

![image](https://user-images.githubusercontent.com/40416610/149295916-0cf73bd0-1d68-4608-a373-25267d68b6e9.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
