### ISSUE TITLE
Getting page crash on 3 history pages when user agree to topic / camp / statement change 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#1038]
![Screenshot 2021-12-28 at 11 31 27 AM](https://user-images.githubusercontent.com/92429083/147534233-5ff2c056-0083-4273-a1f8-c03e0a9aa749.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production

**Comment by rupalichavan9860** [comment]
Verified on production
