### ISSUE TITLE
Incorrect score / "Total Support for This Camp" and incorrect choice/preference number for old records 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1045]
Please refer attached screenshot : 
1. Incorrect score / "Total Support for This Camp" 
![image](https://user-images.githubusercontent.com/40416610/147726107-b72ed81e-26bd-48d9-9478-5339ed4e46a8.png)

2. Incorrect choice/preference number 
![image](https://user-images.githubusercontent.com/40416610/147726266-c3c17df1-f5ce-46cc-841c-8e1b9b75ce9b.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 I have tested and verified for some camps and working fine now . But still total score is mismatching for below camp

Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/154661803-fa04add9-d9a4-4fe8-a285-882356109b4a.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Tested on production. 
Working fine for camp : Steven Lehar but can see incorrect total score for below camp
Screenshot of live for camp "Chirapat Ukachoke"
![image](https://user-images.githubusercontent.com/40416610/157304922-9ebdcee4-2db0-4794-b3d0-7a14e2123706.png)

On staging it is displaying correct score. Please refer below screenshot
Screenshot of staging for camp "Chirapat Ukachoke"

![image](https://user-images.githubusercontent.com/40416610/157305296-45523905-dc3c-4ae6-ac3e-65f55a9840a6.png)

**Comment by rupalichavan9860** [comment]
Also check other camps under "Mind Experts" topic, total score displaying is incorrect for most of camps

**Comment by kshitij1326** [comment]
@rupalichavan9860 As i can check it is displaying correct score for me, there would be some caching issue at that time.

**Comment by rupalichavan9860** [comment]
Yes. displaying correct score now so closing the issue
