### ISSUE TITLE
Page crash when upload pdf file of 19.9 MB

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1047]
When trying to upload a pdf file of 19.9 MB . Page crashes instead  should give validation  message

![Screenshot 2021-12-31 at 4 03 27 PM](https://user-images.githubusercontent.com/91254708/147820731-9ae46932-d390-4ec9-bd7a-088c0a8ee871.png)

**Comment by saniatg** [comment]
Verified @rupalichavan9860 please confirm.

**Comment by rupalichavan9860** [comment]
@sunilspr7 @saniatg Crash is fixed and getting error message if try to upload more than 5 mb but not  able to upload file more than 2mb and less than 5 mb

**Comment by sunilspr7** [comment]
@saniatg  now issue from server side. @akuks please increase file upload size more than 2mb.

**Comment by akuks** [comment]
Done

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now. 
Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
