### ISSUE TITLE
Page contents are overlapping when minimising window.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#105]
![image](https://user-images.githubusercontent.com/40416610/42026875-dd974dd4-7ae5-11e8-9dd5-a776285d5623.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test this on standard device sizes. Resizing only dont confirm the responsiveness.

**Comment by rupalichavan9860** [comment]
I have tested on mobile also..Please refer attachment 
![screenshot_2018-06-29-01-07-24-832_com android chrome 1](https://user-images.githubusercontent.com/40416610/42089011-42a5a7ce-7bb9-11e8-930c-2a903654d266.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 clear your browser cache before testing this.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Working fine
