### ISSUE TITLE
File Upload-> Validation message is not showing correctly for valid file formats which are greater than 5MB

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1054]
When uploading a JPEG file  greater than 5MB . The validation message shows "Error! The file failed to upload." But it should show "Error! The file may not be greater than 5120 kilobytes." 
Working fine on Production but not on Staging.

![Screenshot 2022-01-04 at 7 00 02 PM](https://user-images.githubusercontent.com/91254708/148066595-4086f6c2-7a6f-430f-a8c4-5470efb02d8f.png)

![Screenshot 2022-01-04 at 6 59 14 PM](https://user-images.githubusercontent.com/91254708/148066628-c436e9b5-8788-4bce-bdbf-e5dd7c37467a.png)

**Comment by rupalichavan9860** [comment]
Working fine on both staging and live so closing this
