### ISSUE TITLE
Admin shares page needs to be able to select all available months.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1055]
![image](https://user-images.githubusercontent.com/6559312/148091473-18241405-5d60-4e68-83ea-aa37737a08b1.png)

As you can see, there is only the latest month selectable.
We need to be able to select all available months.

**Comment by BrentAllsop** [comment]
And the nick name entries in the shares columns, should be links to those nick names.

**Comment by BrentAllsop** [comment]
Also, if there is no share data entered for the current as_of month, the canonizer share algorithm shows 0 shares.
It should, instead, show the most recent share record, even if that is many months old.
If there is no share change, for a month, we should not be required to add another record for that month.

**Comment by rupalichavan9860** [comment]
@karun0607gautam @BrentAllsop If I forgot to enter shares for dec 2021 and want to enter it now , but it is not allowing and giving error message "The as of date must be a date after or equal to 2022-01-01."

Is this fine?

**Comment by BrentAllsop** [comment]
I think it would be good to be able to enter and edit any dates at any time.

**Comment by rupalichavan9860** [comment]
Tested. I found below issue
If any months is having more than 10 entries and selected that month, I can see 2 pages  below

![image](https://user-images.githubusercontent.com/40416610/151512597-35f97413-63c6-4ea9-9221-0f5e5c9d06ed.png)

but when I click on page 2 it is not displaying records for that month 

![image](https://user-images.githubusercontent.com/40416610/151512840-a33e9ba8-4ae3-4638-b4e0-49171af183cd.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
