### ISSUE TITLE
Include the "Edit Summary" field in all emails about camp changes.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1059]
The "**Edit Summary**" field is not being include in at least the change to topics.  And it needs to be clear that this entry in the email, matches the "**Edit Summary**" field on the submitted proposed change.

And we should enumerate changes to fields in the e-mail, other than "statement" changes.
The changes (except for the statement changes) should also be included in the e-mail to the author of the proposed change.

And this text needs to be improved:
"We request that all direct supporters of a camp continue to receive notifications and take responsibility for the camp. You can avoid being notified by delegating your support to someone else."

to be:

"We request that all direct supporters of a camp continue to receive notifications and take responsibility for the camp. If you delegate your support to someone else, you will no longer receive these e-mails.  Delegating your support to someone else will also result in your support following them for all camps in this topic."

Note:  Both copy people, including @CanonizerJim need to approve this change, by either changing it, and then commenting on this topic that they agree with the above copy change.  The same change needs to be made for all types of changes to camps.

**Comment by CanonizerJim** [comment]
"We request that all direct supporters of a camp continue to receive notifications and take responsibility for the camp. If you delegate your support to someone else, you will no longer receive these e-mails. Delegating your support to someone else will also result in your support following them for all camps in this topic."

This is the language I support.

**Comment by dakshiffort** [comment]
I agree with @CanonizerJim - @BrentAllsop

**Comment by saniatg** [comment]
@rupalichavan9860 
Verified updated text ""We request that all direct supporters of a camp continue to receive notifications and take responsibility for the camp. If you delegate your support to someone else, you will no longer receive these e-mails. Delegating your support to someone else will also result in your support following them for all camps in this topic." in the following cases. Let me know if I missed any case.
1- Add /Delete support
2- Add/Delete Delegated support
3- Add /Update camp statement
4- Propose change to the Topic Record
5- Propose change to the  Camp Record

**Comment by sunnyjindal** [comment]
@saniatg @rupalichavan9860 have also corrected the "Edit Summary". Earlier edit summary description was coming from the original topic. Now we have changed it so that it comes from the latest topic revision.

**Comment by rupalichavan9860** [comment]
> @saniatg @rupalichavan9860 have also corrected the "Edit Summary". Earlier edit summary description was coming from the original topic. Now we have changed it so that it comes from the latest topic revision.

@saniatg Please check this also

**Comment by saniatg** [comment]
@rupalichavan9860 verified 'Edit Summary' in all the emails for Topic/camp/statement changes and is working fine.

**Comment by rupalichavan9860** [comment]
Verified
