### ISSUE TITLE
Whenever user creates a new topic/camp/statement , user should redirect to Topic view page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1062]
Actual Result : As of now when user creates a new topic/camp/statement , user is redirecting to respective history pages 

Expected Result : Whenever user creates a new topic/camp/statement , user should redirect to Topic view page instead of history page

**Comment by rupalichavan9860** [comment]
Tested and verified.
@BrentAllsop I have one doubt in this, as user is redirecting to view page user needs to go again to edit page for committing changes

**Comment by BrentAllsop** [comment]
@rupalichavan9860 , yes I agree, good call.
We should go to the camp page for camp and topic modifications, but for the statement, we should go to the history page, so the user can commit the review.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
