### ISSUE TITLE
Logged in with register email ID and incorrect password 

### ISSUE THREAD

**Issue by anilPodi** [the-canonizer/canonizer.2.0#1063]
Logged in with register email ID and incorrect password more than 3 times does not displaying proper error message"too many login attempts, please try after 60 seconds"

**Comment by rupalichavan9860** [comment]
This functionality is already exists on staging for 5 incorrect attempts and working fine .This is not an issue so closing this

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 This is working fine on production
