### ISSUE TITLE
Page crash on "Camp Forum" and "Add Camp Statement" button click

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1070]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/ 
2. Login with valid email and password
3. Create a new topic
4. Click on "View This Version"
5. Click on "Camp Forum" and "Add Camp Statement"

Actual Result : 
Getting below page crash

![image](https://user-images.githubusercontent.com/40416610/148946186-f2686796-5eae-41b6-b107-2b23fb4a0644.png)

**Comment by anilPodi** [comment]
@rupalichavan9860 Working for me, No page crash, 
![Screenshot from 2022-01-18 11-43-51](https://user-images.githubusercontent.com/96222726/149892272-445b70ab-ea7a-4228-ab1b-a7e57fd639d0.png)
Please verify

**Comment by anilPodi** [comment]
![Screenshot from 2022-01-18 11-44-08](https://user-images.githubusercontent.com/96222726/149892752-ea51e008-28af-444a-a998-f26dc2e131d8.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
