### ISSUE TITLE
"My topics" check box is not working on browse page .

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1071]
1. Navigate to https://staging.canonizer.com/browse
2. Check the check box" My Topics"

My topics are seen instead all are showing after checking the check box which is incorrect.
![Screen Shot 2022-01-11 at 6 19 06 PM](https://user-images.githubusercontent.com/91254708/148947153-5f0af334-4bdf-4b94-8f3d-273494fd53b9.png)

**Comment by saniatg** [comment]
Task is working fine. @rupalichavan9860  please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified on production.

**Comment by rupalichavan9860** [comment]
Verified
