### ISSUE TITLE
Page crash on Remove Support button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1073]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create a new topic
4. Click on "Manage/Edit This Camp"(Agreement Camp)
5. Click on "View This Version"
6. Click on "Remove Your Support"

Actual Result : 
Getting below page crash
![image](https://user-images.githubusercontent.com/40416610/149143315-0ae595cf-9ba7-4763-a180-2b8fae5d8a3d.png)

**Comment by anilPodi** [comment]
@rupalichavan9860 Working fine for me, No page Crash, Please Verify
![Screenshot from 2022-01-18 11-48-53](https://user-images.githubusercontent.com/96222726/149892977-ad052bab-7c7f-41f0-93d2-be5bfa7f06b5.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
