### ISSUE TITLE
User is able to support both Agreement camp and child camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1074]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create a new topic(Support get automatically added to Agreement Camp)
4. Create new camp "camp 1"
5. Click on "View This Version"
6. Click on "Directly Join and Support"
7. Click on "Submit"

Actual Result : 
Support is getting added to child camp also
![image](https://user-images.githubusercontent.com/40416610/149144421-8a3ae1f2-945f-4259-a5e4-4881b6f3e3ca.png)

**Comment by saniatg** [comment]
Also, same cam is being supported twice. Check screenshot Agreement camp is seen twice. In supported camp the number is seen 3 for agreement. 2nd  is missing .
![Screenshot 2022-01-12 at 6 24 54 PM](https://user-images.githubusercontent.com/91254708/149146258-6f5dd636-e0ae-480a-ad80-d33369415c42.png)
![Screenshot 2022-01-12 at 6 38 08 PM](https://user-images.githubusercontent.com/91254708/149146293-9f2b41de-a598-48a0-8936-8793c52c0967.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
