### ISSUE TITLE
Duplicate camp is being created when click on 'Create camp' button twice

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1075]
1. Navigate to any topic or create new one.
2. Now try to create a new camp , enter all the details.
3. Click 'Create Camp' button twice

The camp will be created twice with the same name which is incorrect.
![Screenshot 2022-01-13 at 5 48 31 PM](https://user-images.githubusercontent.com/91254708/149331668-7bbec211-1237-4575-b029-bd489efe07ae.png)

**Comment by sonalizibtek** [comment]
Tested and verified . Its working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on Production.

**Comment by rupalichavan9860** [comment]
Verified
