### ISSUE TITLE
Incorrect support score is displaying when selecting "Mind Experts" Algorithm

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1077]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/149757816-f88ced5c-91ed-403d-bc3f-f93df116c5b6.png)

Rupali C's score for above 3 camps are 0.50, 0.25 and 0.13 when selecting "One Person One Vote"
1. "Ashutosh Kukreti" Camp

![image](https://user-images.githubusercontent.com/40416610/149758087-04615b8e-cc42-4aff-84e7-226dc5db4021.png)

2. "Rupali Chavan" Camp

![image](https://user-images.githubusercontent.com/40416610/149758240-c182e08d-316e-4169-bfbb-fe9beb2a51d6.png)

3.  "Rupali c 1" Camp
![image](https://user-images.githubusercontent.com/40416610/149758327-b1aa6ac5-7f20-476b-a7ae-a6a3b2695b20.png)

When selecting "Mind Experts" , it should be 0.50* 5 =2.5 , 0.25* 5=1.25 and 0.13*5= 0.65
But Actual score is displaying as 1.25 for all 3 camps

1. "Ashutosh Kukreti" Camp

![image](https://user-images.githubusercontent.com/40416610/149758754-000f97e4-a0e2-4456-900c-00e9bf3386c5.png)

2. "Rupali Chavan" Camp

![image](https://user-images.githubusercontent.com/40416610/149758863-2a69f81e-41c3-44d8-9e3e-033b6a907fef.png)

3.  "Rupali c 1" Camp

![image](https://user-images.githubusercontent.com/40416610/149758939-ad65e7d5-28a0-41f7-b46c-f90f380ef4d1.png)

**Comment by rupalichavan9860** [comment]
@karun0607gautam Tested . Still it is not working . Please refer below scenarios and screenshots

I have created two camps under Mind Experts , "Rupali C" and "Rupali cano" and both users supporting both camps.

Screenshot of "Rupali C" camp when selected "One Person One Vote " algorithm : 
Score of user "Rupali C" is 0.5 ---Correct
Score of user "Rupali cano" is 0.25 ---Correct
Total Score is 0.75 ---Correct
![image](https://user-images.githubusercontent.com/40416610/163132233-627220ab-7ca3-41f2-81c6-05f5061d8589.png)

Screenshot of "Rupali cano" camp when selected "One Person One Vote " algorithm : 
Score of user "Rupali cano" is 0.5 ---Correct
Score of user "Rupali C" is 0.25 ---Correct
Total Score is 0.75 ---Correct
![image](https://user-images.githubusercontent.com/40416610/163132363-193af8b1-bb27-4d85-a9dc-872a78a50262.png)

Screenshot of "Rupali C" camp when selected "Mind Experts" algorithm : 
Score of user "Rupali C" should be 0.5 * 5 = 2.5 **(Actual score displaying is 3.75 which is incorrect)**
Score of user "Rupali cano" should be 0.25 * 5 = 1.25 **(Actual score displaying is 3.75 which is incorrect)**
Total score should be 2.5+1.25 = 3.75 **(Actual score displaying is 5 which is incorrect)**

![image](https://user-images.githubusercontent.com/40416610/163134500-34de1851-4489-4452-8285-1a11c1cb0d5d.png)


Screenshot of "Rupali cano" when selected "Mind Experts" algorithm : 
Score of user "Rupali cano" should be 0.5 * 5 = 2.5 **(Actual score displaying is 3.75 which is incorrect)**
Score of user "Rupali C" should be 0.25 * 5 = 1.25 **(Actual score displaying is 3.75 which is incorrect)**
Total score should be 2.5+1.25 = 3.75 **(Actual score displaying is 5 which is incorrect)**


![image](https://user-images.githubusercontent.com/40416610/163133955-d8ccd9b5-d2ff-4e02-aba3-91036362688e.png)

**Comment by rupalichavan9860** [comment]
@karun0607gautam This is not fixed yet

![image](https://user-images.githubusercontent.com/40416610/165525608-e6f17863-2a1d-4d24-b7a5-deffd801b1e6.png)

**Comment by rupalichavan9860** [comment]
@karun0607gautam Please check below scenario : 
"Rupali C " is mind experts and supporting camp "Brent Allsop" only

![image](https://user-images.githubusercontent.com/40416610/174239643-f6647b2d-a23e-4b2c-977d-88dfafdf8889.png)


![image](https://user-images.githubusercontent.com/40416610/174239507-34f748f5-7499-412d-9d9d-bf7bbec6d3bf.png)

So if I select "Mind Experts" , score should display - 1* 5 = 5 
As of now score is displaying as 0

One Person One Vote : 
![image](https://user-images.githubusercontent.com/40416610/174240178-76501db1-5c61-4aed-af45-0c9329d6e31b.png)


Mind Experts : 
![image](https://user-images.githubusercontent.com/40416610/174240041-9e4445b8-17cb-42e6-b097-fd1345a85cb2.png)

**Comment by karun0607gautam** [comment]
@rupalichavan9860 this is correct as the score in case of mind expert will come from the camp in which Rupali C is an expert. Since score in that camp is 0, so it is coming 0 in case of mind expert

@BrentAllsop Can you please confirm this

**Comment by rupalichavan9860** [comment]
@BrentAllsop Score looks okay to me .Can you please test once?

**Comment by BrentAllsop** [comment]
There are still problems with this.
Leon is getting the *5 reward in his [mind expert camp](https://staging.canonizer.com/topic/81-Mind-Experts/19-Leon-Maurer). even though [he is only supporting himself](http://staging.canonizer.com/user/supports/38?topicnum=81&campnum=19&namespace=13#camp_81_19).

Also, leon meur's delegate JohnDe1941 is not a mind expert.  While JohnDe1941's vote is counted in the first, one person one vote pass.  His vote should not be counted in the mind expert part, and this is the only part of the algorithm that gives the *5 reward.  The one person one vote scores are just stored in a variable, and never displayed when the 1 person one vote is set, either in the "special" case (this topic only), or the general case (in all other topics).

You can see how this all should be programmed in the [1.0 mind expert algorithms](https://github.com/the-canonizer/canonizer.1.0/blob/master/webtools/canonizers.pm).  The algorithm should be the same as that 1.0 version.

**Comment by BrentAllsop** [comment]
This is very bad to have so many repeated close, then reopen failures like this.
We need to have automated tests for all these cases, so  nobody can even check in the code, till all of these failure cases pass the automated tests.

**Comment by karun0607gautam** [comment]
@BrentAllsop Please test mind expert algorithm fixes

**Comment by BrentAllsop** [comment]
There are 3 supporters of this '[Mind Expert](https://staging.canonizer.com/topic/81-Mind-Experts/19-Leon-Maurer)' camp.  Only one of them is an expert (has a mind expert camp).  Mike Gashler, correctly  has no "mind expert" score, but, similarly, JohnDe1941, should not have a score, since he is also not a mind expert.

**Comment by BrentAllsop** [comment]
Yes, everything is working now, so closing this issue.
