### ISSUE TITLE
Page crash when deleting the  news

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1078]
1. Log in with USER A and USER B on different browsers.
2. User A  created a topic and a camp and added news and is on canoniser sorted camp tree page and can see the news added.
3. Now login User B on different browser and navigate to the topic created by User A and delete the news .
4. Now since the page is not refreshed for USER A click on delete news , page crashes

Firstly the page must not crash. Secondly, why is User B able to delete the news. Only the submitter must delete the news.
![Screenshot 2022-01-17 at 5 21 06 PM](https://user-images.githubusercontent.com/91254708/149767170-17a20aee-8bd3-45aa-a21e-badbd725535d.png)

**Comment by rupalichavan9860** [comment]
"Delete News" should be visible only to the logged in users

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop 
There are two parts of the Ticket:

1. Firstly the page must not crash. **(Done)**
2. Secondly, why is User B able to delete the news. Only the submitter must delete the news. **(Need Discussion)**

For point two, should the person who has created the News Feed be the only one who is able to delete it or any logged-in user can delete it? Currently, anyone logged-in user is able to delete the newsfeed.

This item was also discussed in yesterday's scrum, and it was decided that your input is required. Can you enlighten us @BrentAllsop?  :)

**Comment by BrentAllsop** [comment]
Yes, my feeling is we want a wiki system, where anyone can change anything, so allow logged in users to delete news items.

**Comment by BrentAllsop** [comment]
But I do like the idea of only people logged in can delete news items, so we can know who has deleted it.  This should be recorded in the db, and it'd be nice if we had a news history page (when there are deleted news items), where we could see deleted news items, and who deleted them, and also have an option to un delete them, again, only if you are logged in.

But let's only do this additional history page for Canonizer 3.0.

**Comment by saniatg** [comment]
@rupalichavan9860 Crash issue is resolved. Task is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on Production and is working fine

**Comment by rupalichavan9860** [comment]
Verified
