### ISSUE TITLE
If user hits the same URL in two tabs of same browser,Logout from any one tab should logged out the user from both application.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#108]
Steps to Reproduce:
1. Go to https://staging.canonizer.com/     
2. Login with valid email and password     
3.Open new tab within the same browser hit the application with URL  https://staging.canonizer.com/     4.Click on log out from one tab

Expected Result:
User should be logged out after clicking on any operation from the application

**Comment by gautamv16** [comment]
@rupalichavan9860 its happening, you have to referesh page to see effect or when you will do any action on other tab you will see user is logged out. So this is invalid issue.
