### ISSUE TITLE
 "nick names" in emails should be a link showing the supports for that nick name.

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1081]
Mentioning the emails  subject for which nick name  links are missing :

1. [Nick name] has added their support to the [camp_name]
![Screenshot 2022-01-17 at 5 17 11 PM](https://user-images.githubusercontent.com/91254708/149779516-0e6498a8-d9d9-4d71-a570-e1cd5c639c6d.png)
2. [Nick name] has removed their support from [camp_name]
![Screenshot 2022-01-17 at 7 13 59 PM](https://user-images.githubusercontent.com/91254708/149779729-0ebd62bc-a830-43c3-935b-e3aba02f745c.png)
3. Proposed change to statement for camp[camp_name]
![Screenshot 2022-01-17 at 7 15 27 PM](https://user-images.githubusercontent.com/91254708/149779900-0861c407-5520-48a5-ae1a-0deec5125cd7.png)
4. Proposed change to topic[topic-name] submitted
![Screenshot 2022-01-17 at 7 16 15 PM](https://user-images.githubusercontent.com/91254708/149780011-f01308dc-a315-4916-971f-1db558a28310.png)
5. Proposed change to [camp_name/Agreement submitted
![Screenshot 2022-01-17 at 7 17 18 PM](https://user-images.githubusercontent.com/91254708/149780201-734c44ec-a50c-4897-ab9a-d7ec56a7651e.png)
6.(When creating thread)[Topic_name]/Agreement Thread[Thread_name] 
![Screenshot 2022-01-17 at 7 20 18 PM](https://user-images.githubusercontent.com/91254708/149780707-6456c9e9-9560-4bb9-92c1-8eddec71d471.png)
7.[Topic_name]/Agreement/[Thread_name] new post submitted
![Screenshot 2022-01-17 at 7 22 38 PM](https://user-images.githubusercontent.com/91254708/149781279-8a154307-6f09-4d58-af82-39341672e23c.png)
8.[Nick_name] has removed their delegated from [nick_name] in [topic_name]
![Screenshot 2022-01-18 at 1 46 44 PM](https://user-images.githubusercontent.com/91254708/149897710-9306aa38-c3ff-4a1f-8208-cfcbc1a645ea.png)
9.For subscribers->[Nick_name] has removed their delegated from [nick_name] in [topic_name]
![Screenshot 2022-01-19 at 11 34 39 AM](https://user-images.githubusercontent.com/91254708/150073575-9ad676c0-c240-4376-8eed-4a25296e994e.png)
s

Testing in progress

**Comment by saniatg** [comment]
@sunilspr7 Points 8 & 9 are not done. When delegating and removing support.
[Nick_name] has removed their delegated from [nick_name2] in [topic_name]
Nick_name2 must also be  a link 
![Screenshot 2022-02-16 at 3 27 47 PM](https://user-images.githubusercontent.com/91254708/154245760-7f8b6d57-b0e9-4186-b405-e61e6fbd2fd1.png)

![Screenshot 2022-02-16 at 4 01 21 PM](https://user-images.githubusercontent.com/91254708/154246158-0bc8a645-2236-4c99-beb2-ebe6a042baea.png)

**Comment by sunilspr7** [comment]
@saniatg  okay, I will check

**Comment by sunilspr7** [comment]
@saniatg  fixed it and code PR created

**Comment by saniatg** [comment]
@rupalichavan9860 Tested for following cases:
1- Add /remove support
2- Add/remove delegated support
3-Create thread
4- Create /update post
5- Proposed change in camp/topic/statement
6- Objection email
7- Promotion email
Points 8 & 9 are also fixed. Let me know if I missed any email.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on  production working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
