### ISSUE TITLE
'To' in the mail is empty for a thread created /post add emails

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1084]
Created a thread. In the mail for the submitter 'To' field is empty .
Same case when post is added.
![Screenshot 2022-01-18 at 11 09 17 AM](https://user-images.githubusercontent.com/91254708/149877882-19f51039-e1d1-438b-b947-45ab046088b1.png)

**Comment by saniatg** [comment]
@HamzaBinMansoor Working fine when 'Add thread' but when a post is created, in that case it is not fixed. 'To' in the email is empty.
![Screenshot 2022-02-04 at 4 02 12 PM](https://user-images.githubusercontent.com/91254708/152514054-3bf9a92d-f41d-4d97-aa3f-6e52aa5c9c3c.png)

**Comment by saniatg** [comment]
Tested and is Working fine @rupalichavan9860 Please confirm and close

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production and is working fine.

**Comment by rupalichavan9860** [comment]
Verified on production
