### ISSUE TITLE
Delegated support is getting removed when supporting parent/child camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1085]
Case 1 : 
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create new camp "Camp 1" and support it By "User A"
4. Login with "User B" and delegate support to "User A"
5. Login with "User C" and delegate support to "User B"
6. Login with "User A" and support "Agreement" camp

Actual Result : 
"User C"s support is getting removed

Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and support "Agreement" camp By "User A"
4. Login with "User B" and delegate support to "User A"
5. Login with "User C" and delegate support to "User B"
6. Login with "User A" and Create new camp "Camp 1" and support "Camp 1" camp

Actual Result : 
"User C"s support is getting removed

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified and working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
