### ISSUE TITLE
Camp name must be same . If used first alphabet as small then it should be in small .

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1086]
Created camp with name 'camp1' small letter 'c', but in header shows' Camp1' . 'C' is shown as capital which is incorrect, should be 'camp1' as added by the user.

![Screenshot 2022-01-19 at 12 38 45 PM](https://user-images.githubusercontent.com/91254708/150083799-3bf5508c-f6f5-4257-b14b-1492db003315.png)

**Comment by saniatg** [comment]
@rupalichavan9860  Tested and  is working fine. Kindly confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified on Production.

**Comment by rupalichavan9860** [comment]
Verified
