### ISSUE TITLE
Getting 2 different emails for adding delegate support

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#1087]
Getting 2 emails ,one with delegated their support to WAJEEHA KHAN in this topic
![screenshot-mail google com-2022 01 19-11_31_44](https://user-images.githubusercontent.com/92429083/150085497-deed0796-325b-4a45-9ea0-ea1effedce45.png)
and other with delegated their support to you in this topic
![Image 2](https://user-images.githubusercontent.com/92429083/150085516-eac0756c-9150-4208-9f93-0350cf2f2fc3.png)

**Comment by saniatg** [comment]
The same issue is also when remove the delegated support.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production

**Comment by rupalichavan9860** [comment]
Verified
