### ISSUE TITLE
Crash when remove support 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1088]
Log in with 3 users in 3 different browsers
User A -Create a topic and a camp 
User B- Directly supports a camp
User C- Delegates support to User B for the camp

Now User B delegates support  to User A in Agreement Camp
Refresh all the URL's for all users 
User B removes delegate support given to User A in Agreement camp
Log in with User C, click  on Agreement Camp and click on button'Remove Support'. Page will crash.

![Screenshot 2022-01-19 at 11 14 55 AM](https://user-images.githubusercontent.com/91254708/150090925-ca22e094-f2d2-43b5-a894-bcb1da715239.png)

**Comment by rupalichavan9860** [comment]
Getting same page crash in below scenario : 

Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps "Camp 1" ,"Camp 2" and "Camp 3"
4. Support all 3 camps by "User A"
5. Log out and login with another user "User B" and delegate support to "User A" in any camp
6. Again login with user "User A" and change parent camp of "Camp 1" to "Camp 2" from "Agreement"
7. Observe tree  "Camp 3"
8. Login with delegated user "User B"
9. First click on "Remove your support" as direct supporter 
It will look like below ,
![image](https://user-images.githubusercontent.com/40416610/151752654-81b3f908-4519-49a6-8eca-2cfee871ebcf.png)

10. Click on "Remove your support" as delegated supporter
Getting below page crash 

![image](https://user-images.githubusercontent.com/40416610/151752701-736caf4f-c493-4e3e-8178-929133ff1ed4.png)

**Comment by nalwa** [comment]
@rupalichavan9860  @saniatg  i have resolved first part of this ticket. And as per discussion today, second part will go in another ticket.

**Comment by rupalichavan9860** [comment]
@nalwa As per discussed I have created separate ticket for second part #1131

**Comment by saniatg** [comment]
@nalwa not able to test 1st part issue as I got a page crash after these steps.

User A -Create a topic and a camp
User B- Directly supports a camp
User C- Delegates support to User B for the camp

User B delegates support to User A in Agreement Camp
Now, when User B  tries to removes delegate support given to User A in Agreement camp, on click button 'Remove Support' Page crashes
![Screenshot 2022-02-09 at 3 03 37 PM](https://user-images.githubusercontent.com/91254708/153170063-7062a55f-cb42-4980-ba17-53ef0baca66f.png)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
Verified on production
