### ISSUE TITLE
Incorrect Total support count is displaying

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1089]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/150098207-0a5b085e-0abf-4db8-ae40-132174798548.png)

**Comment by rupalichavan9860** [comment]
Found one more scenario where incorrect score count

Steps to reproduce : 
1. Create topic with "User A" , create 3 camps and support all
2. Login with "User B" and delegate support to "User A" 
3. Login with "User C" and delegate support to "User B"
4. Login with "User D" and delegate support to "User C"
5. Login with "User B" and create and directly support 4th camp 
6. Observe Score
Actual Result : 
Score is displaying correct for first 3 camps but 4th camp score is incorrect. Please refer below screenshot
![image](https://user-images.githubusercontent.com/40416610/152148790-8f11ed65-5b13-465a-a772-af821be13079.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested on production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
