### ISSUE TITLE
Search functionality is not working for some links. It is displaying error message "Not Found The requested URL /browse was not found on this server."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#109]
![image](https://user-images.githubusercontent.com/40416610/42050363-50472a12-7b26-11e8-90d0-6c3ddf1872a8.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 mention step how you came to this page...

**Comment by gautamv16** [comment]
@rupalichavan9860 please provide steps...

**Comment by rupalichavan9860** [comment]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Check Canonizer.com radio button and enter "Testing" keyword in "Search For..."text box.
3.Click on "Google Search"
4.Click on first link "Browse - Canonizer"(http://canonizer.com/browse)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is not an issue. Our main canonizer.com is not live yet , so its very understandable live domain url will not work untill we go live. So ignore such live url issues. Thanks
