### ISSUE TITLE
Newly created camp is not listing under "Canonizer Sorted Camp Tree"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1092]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/150725049-f1bb29b6-d430-47c1-baf6-c820ee2d5f10.png)

Camp is visible after reloading page

**Comment by rupalichavan9860** [comment]
Found similar issue when changing parent camp name page is not reloading , Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/150761935-695ba81f-7097-4b0b-ac85-2eae1444954a.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860  it is working fine.

**Comment by sonalizibtek** [comment]
Tested and Verified, it is working fine . @rupalichavan9860  Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
@sunilspr7 Getting same issue again. Please check
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/155274056-ea4541b9-fbda-40f4-934a-5226c581e6d3.png)

![image](https://user-images.githubusercontent.com/40416610/155274110-8a314b39-4871-4369-b0d2-bc8a369f10dd.png)

**Comment by sunilspr7** [comment]
@gautamv16 @aliahmad45    We need to discuss this, the issue because of the caching system we are using. so the process is like when you create a new camp, it generates a event which get stores in queue, now if that queue takes time to process, until that time the camp will not get updated in the tree on topic view page. so we need to figure out a way either to show a message or to show loader until that event does not get completed.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Still facing same issue
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/156738534-f02c0b12-1ce2-482f-8d7c-4246a004243c.png)

**Comment by rupalichavan9860** [comment]
We are unable to reproduce the issue , so for now closing this issue

**Comment by sonalizibtek** [comment]
Tested and verified. In production its not  working . Please confirm @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@ahmed130544 Can you please check this. Issue exists on live

![image](https://user-images.githubusercontent.com/40416610/157398520-6690ce3c-0e3d-46f9-8f6c-46c031a0757f.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging
