### ISSUE TITLE
Incorrect nickname is displaying in removed delegated support email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1094]
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/150729224-4b8a25ec-b482-4052-8e5e-ff462a9f0b85.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production and is working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
