### ISSUE TITLE
Choice numbers are getting changed when user click on "Remove All" button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1095]
Screenshot before clicking on "Remove All"
![image](https://user-images.githubusercontent.com/40416610/150735253-da0e46f1-274b-474b-a448-06f5e2837815.png)

Screenshot after clicking on "Remove All"

![image](https://user-images.githubusercontent.com/40416610/150735324-1f77bba1-dad0-4ddb-84e1-dfd170530147.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Verified.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
