### ISSUE TITLE
Do we need Topic name label on Bread crumb of support page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1096]
According to second point in https://github.com/the-canonizer/canonizer.2.0/issues/790#issuecomment-963658816  "There needs to be a breadcrumbs like line at the top, similar to other pages, with a link to the "Agreement" camp of the topic, with the topic name as the label."

Actual Result : 
Topic name label is missing on Bread crumb but available on page 

![image](https://user-images.githubusercontent.com/40416610/150764424-f5c0ed58-d6c3-4157-bdb8-098cedabc332.png)

**Comment by BrentAllsop** [comment]
My opinion:
Yes, we should have "Supported camps of "<name of topic>" topic in the header, which should also be a link to the agreement.
And yes, just "agreement" in the breadcrumbs, also a link to the agreement statement.

**Comment by rupalichavan9860** [comment]
Thanks for confirming @BrentAllsop . I am removing "question" label

**Comment by rupalichavan9860** [comment]
@BrentAllsop As of now Topic name with link is added in bread crumb like other pages for uniformity . Is this fine or do we want topic name in header instead of bread crumb?
Please confirm
![image](https://user-images.githubusercontent.com/40416610/152524073-41385196-f937-4945-a1ba-c6ac65a418c3.png)

**Comment by BrentAllsop** [comment]
I added this to the agenda for the Thursday Feb 10, 2022  Meeting so we can find out what everyone thinks about the best standard  breadcrumbs format.

We need to do this for forum posts, also, how do we include the thread name info and stuff.

**Comment by rupalichavan9860** [comment]
@sunilspr7 As discussed in meeting current format is fine only need to remove link of Topic name . Topic name should be label only like on other pages

**Comment by sunilspr7** [comment]
@rupalichavan9860 okay

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on Production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified on Production

**Comment by rupalichavan9860** [comment]
@sunilspr7 This is not working fine for existing topics. Some times it is displaying incorrect topic name (Not even old names) and sometimes displaying old names
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/153809172-d58d39cf-304d-412c-90a9-d81ca9810287.png)


![image](https://user-images.githubusercontent.com/40416610/153809304-b026df25-d625-495b-a20d-f6730791bf91.png)

**Comment by sunilspr7** [comment]
updated support breadcrumb. Issue fixed some time support breadcrumb show blank title.

**Comment by rupalichavan9860** [comment]
Tested and verified on both staging and live also. Working fine now so closing

**Comment by BrentAllsop** [comment]
In the comment I made on Jan 26, 2022, It sounds like I'm saying that the topic name shouldn't be included in the bread crumbs, but I now think it should not say that.  There should be a: "Camp: Agreement", at the start of all "Camp:" lines of a breadcrumbs block, which should be a link to the agreement statement.
There should also be a "Topic: Suggestion Box" line on all bread crumbs blocks on any page that has anything to do with a camp (like all forum pages.)

The topic/camp navigation "bread crumbs block" should use the same code and look and feel on all pages about a camp or topic.  There should be something showing to everyone what, on the web page, is and isn't part of the "bread crumbs block"  Perhaps a border arround all parts of it.

The "Topic Name: <topic name>" line should always be included, so we know what topic we are on.  And the <topic name> should also be a link to the same agreement page of that topic, the same link as the "Camp: Agreement / ..." link.

![image](https://user-images.githubusercontent.com/6559312/170867298-8cc5c00a-9c18-4012-92a2-d197436036be.png)

On Forum pages we need additional forum navigation information  included in the bread crumbs block.

> Thread: All Camp Threads / <Thread Name>

The current "<< List of All Camp Threads" should be moved to be after the "Camp:" line and should look like:

Thread: <thread name> / << List of All Camp Threads

The "<thread name>" part should be like the "green link" for the current camp in the Camp Tree section of camps, showing that it is a link to the currently page we are on, and the "<< List of All Camp Threads" should of course be the same link it is now.

**Comment by BrentAllsop** [comment]
Let's not close this issue till these have been fixed in 2.0 and implemented in 3.0?

**Comment by rupalichavan9860** [comment]
@sunilspr7 Missing on Create thread page 
![image](https://user-images.githubusercontent.com/40416610/173354805-227a5b60-4b08-4e34-8d81-80887af4c60d.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 As per discussed in meeting, need to remove highlighted points. 

![image](https://user-images.githubusercontent.com/40416610/174607010-86f08f5e-6860-4de9-bc5c-3de57ccca4e4.png)

**Comment by sonalizibtek** [comment]
Tested and Verified . @rupalichavan9860 , Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production .It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
