### ISSUE TITLE
Camp page is not displaying when click on This camp was first created on link "Jan 25, 2022, 12:16:22 PM"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1099]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to any topic and click on any camp
4. Apply as of filter as any previous date 
5. Click on "This topic was first created on Jan 25, 2022, 10:33:18 AM" link
6. It will show "This camp was first created on Jan 25, 2022, 12:16:22 PM" 
7. Click on camp created date link 

Expected Result : 
It should display camp page

Actual Result :  
It is again displaying this "This topic was first created on Jan 25, 2022, 10:33:18 AM" link

**Comment by anilPodi** [comment]
@rupalichavan9860 please verify

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
