### ISSUE TITLE
Canonizer 2.0 Auto Delegation 

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#11]

**Comment by akuks** [comment]
This feature will be available in the next release of Canonizer.

**Comment by BrentAllsop** [comment]
@akuks  Not sure what this issue is.  Could you provide more detail?

**Comment by akuks** [comment]
Hi Brent, 
This is created to add the feature of Auto Delegation. 

It is in one of the old versions of the Canonizer Plan Sheet

_User’s settings management page.
Eventual control of auto delegation abilities (but not for first release)

If it is not required, then we can close this ticket.
