### ISSUE TITLE
Create a "Subscribe to entire topic" button on camp pages.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1101]
Current we have a "Subscribe" checkbox.

We should enhance the label to be "Subscribe to this camp (same as directly supporting)"

Additionally add a "Subscribe to entire topic (receive all notifications)", and the checkbox value will have the same value in all camps, for this user, unlike the subscribe to camp button which can be different for each camp.

@CanonizerJim  and @dakshiffort review the text for this, and report on what they agree will be good English.

**Comment by CanonizerJim** [comment]
Can we have a static label that says "Subscribe" and then two buttons beneath it, one that says "Single Camp Only" and one that says "Entire Topic?"

**Comment by sunnyjindal** [comment]
@BrentAllsop @CanonizerJim Can we have “This Camp” and “Entire Topic” as two options?

**Comment by ashish76** [comment]
@sunnyjindal Need some clarification on below points :

	1. What action will be performed by clicking on the Subscribe Entire Topic?
	2. If I click on a Subscribe Entire Topic, will only the topic be subscribe or all its camps also?  
	3. If a camp is already subscribed, then what will happen to that camp?  

Please brief all the logic behind this task.

**Comment by sunnyjindal** [comment]
@ashish76 let's discuss with @BrentAllsop in tomorrow's call.

**Comment by sunnyjindal** [comment]
@kshitij1326 @ashish76 in case this is done, can we raise the PR?

**Comment by rupalichavan9860** [comment]
@kshitij1326 I have subscribed the entire topic but Topic/camp name is missing in email in section "You are receiving this e-mail because:"
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/157810892-954e4d68-2828-43c6-8390-d3b47a039131.png)

**Comment by saniatg** [comment]
@kshitij1326 issues in the following cases:
Case1: When userA is a supporter of camp1 and has subscribed to the entire topic and UserB submits change in camp1 text "You are subscribed to the entire topic" is missing in the mail received to UserA 
- **Fixed**

![Screenshot 2022-03-24 at 11 21 34 AM](https://user-images.githubusercontent.com/91254708/159851233-23d90d05-f9c2-4ce8-82a3-4c9ddcf7308c.png)

Case 2: When userA is not  a supporter of  camp1 but  has subscribed to the entire topic and UserB submits change in camp1  text "You are subscribed to the camp1" is seen which is incorrect as UserA is not subscribed to only camp1, UserA has subscribed to the entire topic. - **Fixed**
![Screenshot 2022-03-24 at 11 18 25 AM](https://user-images.githubusercontent.com/91254708/159851489-49106f16-f2eb-4cbd-99d2-0b919cc79e58.png)

**Comment by sonalizibtek** [comment]
case 1 : User A created topic and clicked on entire topic subscribe 
- logout and login , in browse open the topic which you had subscribed 
Actual result : The entire topic subscribe check box is shown unchecked 
Expected : It should show checked

**Comment by sonalizibtek** [comment]
Case 1: User B clicked on manage edit topic  which user A created and  user A subscribed entire topic  and edited the topic and committed the changes 
Actual Result :  user A dint receive subscribe email
-Expected : user A should receive subscribe email because he had subscribed  entire topic  - **Fixed** 

Case 2: Both user A and User B subscribe to the same topic 
Expected :both User A and User B should receive emails  - **Fixed**

**Comment by sonalizibtek** [comment]
Caes1 : user A created topic and subscribed entire topic subscribe option
-User B created camp under the user A created topic
-Actual Result: user A dint receive subscribe email
-Expected : user A should receive subscribe email - **Not Fixed**

Case 2: User B created camp under user A subscribed entire topic and clicked on manage edit camp and edited the camp by changing the parent camp and submitted
Actual Result : user A dint receive subscribe email
-Expected : user A should receive subscribe email because he had subscribed entire topic - **Not Fixed**

@rupalichavan9860  the above mentioned cases are not yet fixed

**Comment by rupalichavan9860** [comment]
@kshitij1326 also incorrect nick name is displaying in proposed changed to topic email . 
In below case "R-C" is direct supporter of "camp 1" and subscribe to entire topic , "RC12345" proposed  changed to topic 
Please refer below screenshots

![image](https://user-images.githubusercontent.com/40416610/160827085-2d598b9e-c22b-46c9-b950-f7cd144070db.png)


![image](https://user-images.githubusercontent.com/40416610/160827252-751c6df5-6815-4e85-ad43-4b03835bd850.png)

**Comment by rupalichavan9860** [comment]
As discussed in meeting entire topic subscriber should receive all notifications

**Comment by rupalichavan9860** [comment]
@kshitij1326 Getting incorrect content "You are subscribed to `topic name` " for user in below scenario

Scenario : 
User A is supporter of "Agreement" camp and subscribed to entire topic
User B is supporter of "camp 1"
User C created thread and post for "Agreement" camp 
Actual Result : 
User B is getting incorrect content "You are subscribed to `topic name` " even if User B is only supporter in "camp 1" and not a topic subscriber

**Comment by sonalizibtek** [comment]
@kshitij1326  case 1:
User  A and User C - subscriber of same topic
User B created a new camp - both User A and User C received an subscribed  email 
User C will unsubscribe 
Then User B created a camp , - User C is receiving the subscribed email 
**Expected** : User C should not receive the email , only User A should receive email

**Comment by sonalizibtek** [comment]
@kshitij1326 
**Steps**
1. created topic , checked the entire topic subscribe option ,
2. then unchecked it.
3. clicked on start new supporting camp here
4. again in that page clicked on agreement camp 

**Actual Result:** Entire Topic subscribe check box is  shown checked
**Expected** : If the User Unsubscribes the Entire Topic , then it should not show subscribed [ tick mark ]. The subscribed tick mark  should be removed from tree

**Comment by rupalichavan9860** [comment]
Tested and verified. We will log related issues separately if any

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
