### ISSUE TITLE
Support remains added for both child and parent camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1105]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create new camp "camp 1"
4. Support "camp 1"
5. Create second camp "camp 2" and support "camp 2"
6. Create subcamp under "camp 2" i.e "sub camp 2"
7. Update "camp 1" : Change parent of "camp 1" to "sub camp 2" from "Agreement"
8. Observe score for "camp 1" and "camp 2"

Actual Result : User is now supporter of "camp 1" and "camp 2" even if "camp 1" is sub child of "camp 2"
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/151528499-b3b4b982-ca97-448d-9008-3f0b9d1ef3bc.png)

![image](https://user-images.githubusercontent.com/40416610/151528573-3bfb3d55-08e0-4ed7-9237-b8eab7600ab3.png)

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine now

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified. Working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
