### ISSUE TITLE
Incorrect "Total Support for This Camp tree" score and tree displaying

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1108]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps "Camp 1" ,"Camp 2" and "Camp 3"
4. Support all 3 camps by "User A"
5. Log out and login with another user "User B" and delegate support to "User A" in any camp
6. Again login with user "User A" and change parent camp of "Camp 1" to "Camp 2" from "Agreement"
7. Observe score count for "Camp 1" and  "Camp 3"
"Camp 1" : 

![image](https://user-images.githubusercontent.com/40416610/151743208-24b5328d-2784-4f23-a39c-992f0d3fb881.png)

"Camp 3" : 

![image](https://user-images.githubusercontent.com/40416610/151743293-27d99372-ddc2-4dcf-9b24-0957223b22ba.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production . @rupalichavan9860  Please verify once

**Comment by rupalichavan9860** [comment]
Verified
