### ISSUE TITLE
Showing unwanted arrow in the objection email

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1109]
When a supporter objects any proposed change to topic/camp or statement an email is sent, in the email there is unwanted arrow. This must be removed.
Refer screenshot below.
![Screenshot 2022-01-31 at 4 35 06 PM](https://user-images.githubusercontent.com/91254708/151786285-4fb16333-9724-4084-a2fe-c22ab57e8d02.png)

**Comment by saniatg** [comment]
@sunilspr7 Getting unwanted text on mail which is not related when direct supporter objects the proposed change for any camp/topic.
![Screenshot 2022-02-04 at 4 52 46 PM](https://user-images.githubusercontent.com/91254708/152531559-235d9a1f-9c76-4bd0-9c70-1153b777924d.png)

**Comment by saniatg** [comment]
Tested and is working fine

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on production and is working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
