### ISSUE TITLE
Issues when changing parent camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1110]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps "Camp 1" ,"Camp 2" and "Camp 3"
4. Support all 3 camps by "User A"
5. Log out and login with another user "User B" and delegate support to "User A" in any camp
6. Again login with user "User A" and change parent camp of "Camp 2" to "Camp 1"from "Agreement"

Actual Result : 
1. Record is displaying in "In review" 
2. Support from "Camp 1" is getting removed but "Camp 2" is not displaying under "Camp 1"
3. Delegated support of "User B" is removed and "User B " is now direct supporter of "Camp 2" and "Camp 3"

Expected Result : 
1. As there is only one direct supporter(who is change submitter) , camp should go live immediately
2. "Camp 2" should display under "Camp 1" as a child camp
3. Delegated support of "User B" should not be removed

**Comment by rupalichavan9860** [comment]
@nalwa Please refer link for "Camp heirarchy change scenarios" document
https://docs.google.com/document/d/16AHr6ewRJz_qTdi7Ie3Fz2UdXCOp4X60z2JZG7k6CvY/edit?usp=sharing

**Comment by saniatg** [comment]
@rupalichavan9860 Verified and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
@saniatg @sunilspr7 Support remains added for both "Camp 1" and "Camp 2" also even if "Camp 2" is parent of "Camp 1"

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested. Now delegated supporter becoming direct supporter after changing parent

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested and Verified in production . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
