### ISSUE TITLE
Submitter nick Name is showing incorrect when proposed change to the topic

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1111]
In the mail nick name shows as 'Sania ' has proposed a change......
which is incorrect. 
Submitter nick name is not 'Sania'.

![Screenshot 2022-02-01 at 11 31 10 AM](https://user-images.githubusercontent.com/91254708/151921348-7a6c14f6-90f1-469c-a9a6-6ed38c147062.png)

When another user submits a change to the topic.

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine now. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
