### ISSUE TITLE
"I agree with this statement change" checkbox is missing on statement history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1113]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with "User A"
3. Create New topic and create new camp and support that camp
4. Logout and login with another user "User B"
5. Go to topic and camp
6. Click on "Add Camp Statement"
7. Enter all details and click on "Submit Statement" and commit changes
Note :  Now "User A" can see "I agree with this statement change" checkbox
8. Again submit one more camp statement change(By User B) 
9. Login with "User A" and observe camp statement history page

Expected Result : 
User A should see "I agree with this statement change"  checkbox on both records

Actual Result : 
"I agree with this statement change"  checkbox is missing on both records

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
