### ISSUE TITLE
Page Crash - When user try to link other user social media account  to his canonizer account.

### ISSUE THREAD

**Issue by anilPodi** [the-canonizer/canonizer.2.0#1114]
Steps to Produce:
1.Click on Account setting 
2.Click on Social Oauth Verification ,it will display to link the social media account
3.Click on google account link 
4.It will navigate to screen where the list of google account current user is having , where user can choose the account which he want to link.
5.there are two users,  using canonizer - 1.abc@gmail.com,2. bcd@gmail.com. using these email they registered.
- now i m abc@gmail.com
-when i try to link the other canonizer user email .
-Since its already registered, it will show warning popup to choose the particular user account. 
6.The popup will be displayed where user is is already a member of other account and your trying to link that email to this account.
7.The user names with radio button to select will be present 
8.dont choose any username just click on submit

**Actual Result:**
![Screenshot (33)](https://user-images.githubusercontent.com/96222726/152105857-27b9f2eb-ef48-4981-9f01-de704317b6c4.png)
![Screenshot (32)](https://user-images.githubusercontent.com/96222726/152105882-b0d91f9d-4d1f-4dd8-9293-d3fecc9f55cf.png)

9.without choosing clicked on submit - Page crash 
**Expected Result :**
10. It should throw error message as per requirement.

**Comment by sonalizibtek** [comment]
@rupalichavan9860 , Tested and verified . Its working fine . Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified. Please confirm @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
