### ISSUE TITLE
Incorrect Error Message in Phone number Field

### ISSUE THREAD

**Issue by anilPodi** [the-canonizer/canonizer.2.0#1115]
Steps to reproduce:
1. login with credentials.
2. click on Account Settings.
3. In Profile Info.
4. try to enter the Alphabets in phone number field and click on verify.

**Actual result** 
It is displaying incorrect error message.
![Screenshot (31)](https://user-images.githubusercontent.com/96222726/152106354-95723d16-d5af-4c2a-bd20-997634a9e54f.png)

**Expected Result**
It should show "enter the valid phone number" error message.

**Comment by rupalichavan9860** [comment]
@karun0607gautam Working fine when user enters alphabets but if user enters less than 10 digits error message should be "The phone number must be 10 digits." instead of "Enter the valid phone number."

**Comment by rupalichavan9860** [comment]
> @karun0607gautam Working fine when user enters alphabets but if user enters less than 10 digits error message should be "The phone number must be 10 digits." instead of "Enter the valid phone number."

This is not fixed yet

**Comment by subhancd** [comment]
this issue has been resolved and is displaying the correct error message. 
[error message image](https://gyazo.com/26a023272c4b2c05fc24b1163b18ac7b)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified on Production. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
