### ISSUE TITLE
Add camp statement - In statement field its taking invalid data 

### ISSUE THREAD

**Issue by anilPodi** [the-canonizer/canonizer.2.0#1118]
**Steps to Reproduce:**

1.] Click on any topic 
2.] Click on Add camp Statement - It will navigate to add camp statement
3.] In the Statement field , enter the invalid data 
![Screenshot (37)](https://user-images.githubusercontent.com/96222726/152330853-08de2334-9da8-424a-8f63-3a8338dcfabd.png)
4.] Click on Submit Update
**Actual Result ;**
It is allowing the user to enter the invalid data. and some times data which is updated is showing blank 
![Screenshot (36)](https://user-images.githubusercontent.com/96222726/152331192-67e731f1-563f-49c2-ad62-ee45c72db588.png)
**Expected Result:**
It should throw an error message

**Comment by ahmed130544** [comment]
@anilPodi please mention which characters are invalid for statement, by checking screenshot, i guess just special characters are wrong input.

**Comment by kshitij1326** [comment]
@anilPodi @rupalichavan9860  @gautamv16 @karun0607gautam @akuks @sunnyjindal @rohit-talentelgia @cd-ali-ehsan  As per wiki markup * denotes unordered list and also other special characters have their own meaning, so i think we should not have to validate based on special character since we are supporting wiki markup. Here we can do one thing if the statement is not having any alphabet we can throw error. Please suggest.

**Comment by rupalichavan9860** [comment]
@kshitij1326 New note "Note: We support wiki markup. To get reference [click here](https://staging.canonizer.com/topic/132-Help/5-Canonizer-wiki-text-formatting)." is missing on statement update page
Add Camp Statement : 
![image](https://user-images.githubusercontent.com/40416610/166630088-e698e8ae-0a1a-4c3a-8eff-da00d24690ea.png)

Statement Update : 
![image](https://user-images.githubusercontent.com/40416610/166630284-173583f3-03f1-46f9-b8fa-c7f4072705d4.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please Confirm Once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified
