### ISSUE TITLE
Link to "support@canonizer.com" is missing on "https://canonizer.com/videos/consciousness/" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1119]
Link to  "support@canonizer.com" is missing on https://canonizer.com/videos/consciousness/ page. Please refer below screenshot 

![image](https://user-images.githubusercontent.com/40416610/152483389-8a12e0e3-c895-4fec-952a-9fe07065673e.png)

**Comment by ahmed130544** [comment]
@rupalichavan9860 please mention, steps to go to videos page, unable to find it.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Please refer below steps : 
1. Go to https://staging.canonizer.com/ or https://canonizer.com/
2. Go to "What's New at Canonizer" block on right bottom of canonizer home page
3. Click on "Check it out" link or "It's Not a Hard Problem; It's a Color Problem" link or image
4. Observe footer

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Verified and is working fine on production. @rupalichavan9860 can you confirm

**Comment by rupalichavan9860** [comment]
Verified
