### ISSUE TITLE
Irrelevant data is displayed instead of support link in the Blog Footer in both live and staging.

### ISSUE THREAD

**Issue by anilPodi** [the-canonizer/canonizer.2.0#1121]
**Steps to Reproduce:**
1. Click on Blog 
2. Check the footer 

**Actual Result:**
![image_2022_02_04T06_26_19_527Z](https://user-images.githubusercontent.com/96222726/152483549-9311f1e1-f317-48cd-bb62-3791e4c60b46.png)
this irrelevant data should be removed

**Expected Result:**
support@canonizer.com - this should be displayed

**Comment by rupalichavan9860** [comment]
Tested and Verified. Working fine on both staging and live

**Comment by saniatg** [comment]
Tested and is working fine on Production. @rupalichavan9860 can you confirm

**Comment by rupalichavan9860** [comment]
Verified
