### ISSUE TITLE
Page crash on "Delegate Your Support" ,"Remove Your Support" buttons and Account Settings page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1123]
Getting below page crash on  "Delegate Your Support" ,"Delegate Your Support" ,"Remove Your Support" and Account Settings page

![image](https://user-images.githubusercontent.com/40416610/152528678-ae410cc7-0cb3-47e2-a87a-54245abc85a0.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
