### ISSUE TITLE
Crash when remove support after changing parent camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1131]
Getting same page crash in below scenario : 

Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps "Camp 1" ,"Camp 2" and "Camp 3"
4. Support all 3 camps by "User A"
5. Log out and login with another user "User B" and delegate support to "User A" in any camp
6. Again login with user "User A" and change parent camp of "Camp 1" to "Camp 2" from "Agreement"
7. Observe tree  "Camp 3"
![image](https://user-images.githubusercontent.com/40416610/152992061-37d77837-bb1f-4b6b-93f9-2fce1de43dec.png)

Note : Delegated supporter is direct supporter also (Which is incorrect)
8. Login with delegated user "User B"
9. First click on "Remove your support" as direct supporter 
It will look like below ,

![image](https://user-images.githubusercontent.com/40416610/152992154-c1e78b5c-0e9f-436b-8e0c-2bc324e65fbd.png)

Note : Choice number of delegated user is incorrect

10. Click on "Remove your support" as delegated supporter
Getting below page crash 
 
![image](https://user-images.githubusercontent.com/40416610/152992230-84b7d712-96b0-4b25-ad50-51f056974005.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified in production . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
