### ISSUE TITLE
Page crash on Remove Your Support button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1138]
Steps to reproduce : 
1. Create new topic (Support will get added to Agreement camp)
2. Create new camp and support (Support will remove from Agreement camp)
3. Click on Agreement camp and apply as of date as previous date 
4. Click on Topic creation date link
5. Click on "Remove Your Support"

Actual Result : 
Getting below page crash
![image](https://user-images.githubusercontent.com/40416610/153377332-361adea7-a167-48a2-8a6b-bd7dc4481028.png)

**Comment by nalwa** [comment]
@rupalichavan9860   i test this and i  have one question here

Should we  have "Remove Support button" when  going back in past date (selecting as of date filter)?

**Comment by rupalichavan9860** [comment]
As per discussed in meeting we will disable the "Remove Support button" .
@BrentAllsop Can you please confirm on this?

**Comment by BrentAllsop** [comment]
Yes, history can never be modified.  We can only submit new versions of things, that replace old things, as of the date submitted.

**Comment by rupalichavan9860** [comment]
@nalwa As per discussed in meeting we need to disable the "Remove Support button" with tooltip.
@sunnyjindal @dakshiffort Can you please provide the content for tooltip?

**Comment by sunnyjindal** [comment]
@rupalichavan9860 @BrentAllsop Should we not hide the button in this case instead of showing it with a tooltip?

**Comment by dakshiffort** [comment]
Option 1: You can only remove your support from the latest camp statement. 
Option 2: You can only remove your support from the latest camp statement. To view the latest statement, select "default" option under “as of”.

Please see above options. @BrentAllsop please confirm.
@rupalichavan9860 @sunnyjindal

**Comment by rupalichavan9860** [comment]
> Option 1: You can only remove your support from the latest camp statement. Option 2: You can only remove your support from the latest camp statement. To view the latest statement, select "default" option under “as of”.
> 
> Please see above options. @BrentAllsop please confirm. @rupalichavan9860 @sunnyjindal

@dakshiffort I would like to do little correction here. It should be "latest camp" instead of "latest camp statement"

Also it will be good if we hide the button instead of showing it with a tooltip
@BrentAllsop Can you please confirm

**Comment by nalwa** [comment]
@rupalichavan9860  as per discussion with you i have hide the button  "Remove you support" AND "Delegate your support" whenever user go back in past dates.

**Comment by rupalichavan9860** [comment]
@sunnyjindal Can you please provide revised content as per discussed in meeting

**Comment by sunnyjindal** [comment]
@rupalichavan9860 @nalwa 
You cannot remove your support from an archived camp. For LIVE camp, select "default" option under “as of”.

**Comment by nalwa** [comment]
@rupalichavan9860  @BrentAllsop  I have disabled / greyed out  link for past dates with tooltip displaying message provided by @sunnyjindal  which is:  "You cannot remove your support from an archived camp. For LIVE camp, select "default" option under “as of”."

**Comment by BrentAllsop** [comment]
I think it would be better to talk about history.  As in: 'History cannot be modified.  In order to modify your current support select the default option in the as-of box."

**Comment by CanonizerJim** [comment]
I approve

**Comment by nalwa** [comment]
@rupalichavan9860  i have update the message.

**Comment by rupalichavan9860** [comment]
@nalwa Okay. I will check and update once deployed on staging

**Comment by rupalichavan9860** [comment]
@nalwa Page crash issue is resolved and I can see disabled button with tooltip but I have one doubt .
If another user logged in and select as of date ,then "delegate your support" button is also disabled (User cannot delegate in case of history), but user can directly support with button "Directly join and support" even if as of date selected
Is this correct behavior?

As per discussed in meeting we need to confirm the same with @BrentAllsop so adding this to the agenda for the Monday Feb 28, 2022 Meeting

**Comment by BrentAllsop** [comment]
Yes, I believe everything should be the same.  One should never be able to change things from history pages, as history is immutable.

**Comment by rupalichavan9860** [comment]
As discussed I am closing this ticket as page crash issue is resolved and created new ticket for new requirement #1204

**Comment by rupalichavan9860** [comment]
Verified on production
