### ISSUE TITLE
Delegated user is not showing under 'Support tree for Agreement Camp' when applied 'As of Filter'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1140]
1. User A created a topic and a camp. Support directly given to agreement camp.
2. Now login with User B and navigate to the topic created by User A
3. Click on 'As of date' filter
4. Delegate support to User A by clicking on button 'Delegate support'

Support Count is seen changed to 2 which is correct , but in the support tree delegated supporter (User B)  is not seen .
![Screenshot 2022-02-10 at 6 17 13 PM](https://user-images.githubusercontent.com/91254708/153413298-70518b3c-7d88-416d-8d6f-f0ac7233ad6f.png)

If changed filter to 'Default' then the delegated supporter is seen.
![Screenshot 2022-02-10 at 6 17 50 PM](https://user-images.githubusercontent.com/91254708/153413588-c9aad8e0-1187-477d-8079-46c1d68d2b85.png)

**Comment by ahmed130544** [comment]
Unable to reproduce the issue, working fine, @saniatg  please close this ticket.

**Comment by saniatg** [comment]
@ahmed130544 this issue is not coming now as the buttons are greyed out . @rupalichavan9860 Can you confirm and close this issue.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine Production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
