### ISSUE TITLE
Show order of new camp at order of existing supported camp being replaced.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1145]
![image](https://user-images.githubusercontent.com/6559312/153774848-7ad47fd3-e6e8-42fb-a9d1-4944981e7be9.png)

Rather than show the camp you are replacing, separate from the ordered list of supported camps, and rather than putting the new camp at the bottom of the list (# 12 in this case) of supported camps, combine these two graphically, somehow, and put the newly supported camp at the same order as the camp being replaced (# 5 in the case of this screen shot) and allow the dragging of the new camp, with the old one being replaced, before you submit the new replacement camp.

**Comment by rupalichavan9860** [comment]
@ahmed130544 tested. not fixed yet .Please refer below screenshot
![image](https://user-images.githubusercontent.com/40416610/163382544-bc5fd0af-8b13-4e2f-ac9a-1ca780b761ea.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested. Newly created camp is not listing and support is not getting added

![image](https://user-images.githubusercontent.com/40416610/163388494-390c56a1-fe92-41fe-8cfd-bde4a6d4d469.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 User is able to support only one camp for fresh topic . Please check this

![image](https://user-images.githubusercontent.com/40416610/163389005-0f3b1a5d-48d0-41d1-9291-1e2d781aacb1.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, working nicely.
so closing.
