### ISSUE TITLE
Remove extra space before URL links.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1146]
Currently, if you add some wiki markup like this:

"Our current top choice is what is being offered by the "[https://followmyvote.com/ followmyvote]" people."

There is an extra space after the first '"' and the followmyvote text.
You should be able to put the quote next to the text, both before and after the text.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested but issue is not fixed yet

**Comment by ahmed130544** [comment]
> @ahmed130544 Tested but issue is not fixed yet

@rupalichavan9860 Yes, code gets reverted by reviewer.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, looks great so closing this one.
