### ISSUE TITLE
Make it easier to find parent camps on the camp edit form page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1147]
Currently the choices in the parent camp drop down for the edit camp form:
https://canonizer.com/manage/camp/1873
are very hard to find, when the list is long.
There should be some way to show the current tree structure, possibly with indentation of camps, under parent camps, according to the current canonized tree/one person one vote.  If that doesn't fit on a page, then at least sort the list, alphabetically.

**Comment by sonalizibtek** [comment]
Current implementation in the design looks like this. But the box high light color is not looking good .Please find the attached screenshot below :
![Screenshot (706)](https://user-images.githubusercontent.com/99309948/172320648-52c7a704-4ea5-48ba-a6f9-c0068ceb3e69.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 I can see 2 borders when I click on Parent camp fields, Can you please check this 

![image](https://user-images.githubusercontent.com/40416610/173271089-4074dd81-07fd-42b1-b7d5-74a37a2aa2de.png)

**Comment by rupalichavan9860** [comment]
Verified.
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, I guess alphabetically is good enough, so closing this issue.

**Comment by rupalichavan9860** [comment]
Verified on production
