### ISSUE TITLE
Sometimes the page buttons under the Canonized List for block on the home page don't work.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1148]
You can mouse over them sometimes, and it doesn't change from a cursor, to a finger.
When this happens, the buttons don't work.

**Comment by saniatg** [comment]
@kshitij1326 Sometimes when try to click  the highlighted area  mentioned in the screenshot attached , it is not being clickable ,page 1 should be highlighted so that user can click it. It is still  not smooth.

![Screenshot 2022-05-27 at 12 05 11 PM](https://user-images.githubusercontent.com/91254708/170650690-1e2fae31-aefd-4111-9e65-d9191b47cd02.png)

**Comment by saniatg** [comment]
@rupalichavan9860 works fine now. Can you confirm.

**Comment by rupalichavan9860** [comment]
Page numbers are getting highlighted when selecting general namespace but not for other namespaces. Please refer attached screenshot 
General : 
![image](https://user-images.githubusercontent.com/40416610/171178418-0d5d889a-2541-4c5a-b757-a19ab56468ad.png)

Sandbox testing : 
Page numbers 1 to 7 are not getting highlighted 
![image](https://user-images.githubusercontent.com/40416610/171178707-5ab5c336-544d-4e0f-99a3-ff0f9ea8f625.png)

**Comment by saniatg** [comment]
@kshitij1326  also pagination on every namespace must show after 20 records only not before that.

![Screenshot 2022-05-31 at 6 33 42 PM](https://user-images.githubusercontent.com/91254708/171180348-eaf46001-27b3-4240-a6e7-1a6b45309ffc.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now. Please confirm.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested on Production . It is working fine . @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
