### ISSUE TITLE
Don't send e-mail to the person, if he is overwriting his support with the support of a child camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1149]
If you are already supporting a camp X, then if you take an action to support a sub camp of X, it will give the message that your support of X will be removed.  In that case, you should not send any e-mail to the supporters of camp X.  Currently the supporters get:

"Brent Allsop has just removed their support from this camp: : [Platform of the People / Sex Education](https://u6507102.ct.sendgrid.net/ls/click?upn=xJnxDo6LDHvU2dC-2FWOo-2BA7d6yyRJ070c9RfIkGKToTrolXPBHcbjoIFQp-2F2ygXahszXkLOChgH6gb-2B2ESWdE8Hu-2FabqMCfWUtZXa7cMtQVc-3D8oxj_4L9rlx8T0V8eG4q6DdZ-2BcE1AC0VtMxm8dgXrVhxxaSgtosGYk5DHCoyfHLSRKcgYhEZkKR0eOEq8kHodEeO6HAF-2FXLDdM7vrgKsPppQX2kti3uoiiYH7iWd6RYkjarD5lIJAukkd3HVs-2Fu8-2B0V35hgb2c8gy2nbxkmJdcthKZeOYdg5K-2FGZFyZtGqOLbIC3ZbOibtIku7hgND922nrORQd1voItfqk0wTWSkyyNXoR4-3D)

But this isn't correct, because you do implicitly support all parent camps to any camp you do support.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I have one question
If user is delegated user of parent camp and supports child camp directly then, user should received removed support email or not?

**Comment by BrentAllsop** [comment]
I'd think the type of support, explicit or implicit, or delegated..., or switching between any of these cases, should not change the functionality.  The user is still supporting the camp, even if the type of support has changed, so no e-mail is necessary.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested. This is still not working for below scenario : 
If user currently supporting "Agreement" camp and trying to support sub level child camp (child of camp 1 ) , then user is receiving removed email

**Comment by rupalichavan9860** [comment]
Verified
@BrentAllsop Can you please check and close?

**Comment by BrentAllsop** [comment]
Yes, I verified this is working, so closing this issue.

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on staging
