### ISSUE TITLE
Create a test app of the social service providers for Canonizer3.0

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer.2.0#1150]
Create a test app of the following social login service provider for Canonizer. Also, share the API access credentials for the same. 
1. Google +
2. Facebook
3. Twitter
4. Github
5. Linked 

The staging server URL of the new version of canonizer is:  
https://canonizer3.canonizer.com/

**Comment by gautamv16** [comment]
@ashish76 can u test facebook login working for domain https://canonizer3.canonizer.com/

@BrentAllsop make me admin for all other platforms to whitelist canonizer 3 domain.

**Comment by ashish76** [comment]
@gautamv16 Sure Varun, I will check. I hope the Facebook credentials have been set on the server [canonizer3.canonizer.com/](https://canonizer3.canonizer.com/).
