### ISSUE TITLE
The arrow is not properly aligned with the user name on top right corner

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1153]
Highlighted is the UI issue below.
![Screenshot 2022-02-14 at 1 08 23 PM](https://user-images.githubusercontent.com/91254708/153820918-0cc3c58e-1500-4281-a940-234e25ae9389.png)

**Comment by sonalizibtek** [comment]
Tested and verified. It is working fine .@rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on Production.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@aliahmad45 This issue is coming again on Canonizer main page so reopening the issue .
![Screenshot 2022-05-11 at 4 01 21 PM](https://user-images.githubusercontent.com/91254708/167829865-09ba0f07-27a1-4935-8e1d-aca4a2cca363.png)

**Comment by sonalizibtek** [comment]
not yet fixed. @aliahmad45 
case: Logout and login to the application
- Arrow is aligned up. In the home screen

**Comment by ahmed130544** [comment]
@sonalizibtek changes are not showing in code, let me ask Ashutosh please, will update once deployed.

**Comment by ahmed130544** [comment]
@sonalizibtek changes are deployed, you can test

**Comment by saniatg** [comment]
Working fine on staging . @rupalichavan9860 Please confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Verified on production and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
