### ISSUE TITLE
Scroller is missing plus last column is overlapping against the border

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#1156]
![Screenshot_5](https://user-images.githubusercontent.com/92429083/153851245-bd4cf0c7-f8f5-4797-985e-5cca670a2c8c.png)

Issue produced on: Galaxy Fold

**Comment by sonalizibtek** [comment]
Tested and Verified in Nord.  @rupalichavan9860 , Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and Verified on Production. @rupalichavan9860 Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
