### ISSUE TITLE
UI issue on Canonizer Main Page - Canonized list for pagination

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1157]
As of now pagination is displaying as below : 

![image](https://user-images.githubusercontent.com/40416610/153871785-ec51c095-232a-4c36-a037-eaf681ac56f2.png)

It doesn't looks good when there are more pages

It will be good if we can have pagination like below : 

![image](https://user-images.githubusercontent.com/40416610/153871717-a23c16bf-6203-43f1-a39f-7a4fc2799742.png)

**Comment by sonalizibtek** [comment]
this is not yet fixed @rupalichavan9860 
 
![Screenshot (58)](https://user-images.githubusercontent.com/99309948/154208018-5f3adffe-f076-4029-aba4-d06d410589cc.png)

**Comment by aliahmad45** [comment]
@sonalizibtek  can you reload the page and check again?
this is how it's look like
![Screenshot from 2022-02-16 11-53-22](https://user-images.githubusercontent.com/90698926/154211759-e717e1d3-ecec-4e28-ac9b-3a6296684ad2.png)

**Comment by sonalizibtek** [comment]
> @sonalizibtek can you reload the page and check again? this is how it's look like ![Screenshot from 2022-02-16 11-53-22](https://user-images.githubusercontent.com/90698926/154211759-e717e1d3-ecec-4e28-ac9b-3a6296684ad2.png)

@aliahmad45 
- The developed design is not matching according to the requirement 
-the number icon (ex 1,2.. ) is in blue color 
-It should be transparent 
-Please find the attached requirement design below for the reference
![153871717-a23c16bf-6203-43f1-a39f-7a4fc2799742](https://user-images.githubusercontent.com/99309948/154214722-fbd6333d-1bdf-402d-bfa8-875cb6491f52.png)

**Comment by rupalichavan9860** [comment]
@aliahmad45 We are fine with the current format.

**Comment by rupalichavan9860** [comment]
Verified on production
