### ISSUE TITLE
Need selected namespace Id in URL on Browse page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1158]
We are facing issues while automating test cases for Browse page as for all namespaces URL is same "http://staging.canonizer.com/browse"

Can we have URL like "https://staging.canonizer.com/browse?namespace=1" and "https://staging.canonizer.com/browse?namespace=1&my=1" for selected namespace and only my topics(Namespace : General)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine . Checked for Safari, Chrome and Firefox browsers . Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on Production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
