### ISSUE TITLE
Camp names are not displayed  when you select a particular Algorithm 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1160]
Steps to Reproduce:
1. Create topic and create camp
2. Apply  as of date filter and it will display the camp created date link format
3.Click the link , It will display the Topic Page
4.Now select Algorithm one person one vote and mind experts - camp name is displayed 
**Actual Result:**
5. Select algorithm :
computer science expert to canonizer canonizer  - the camp name is not showing 
- Only for two algorithm its displaying
![Screenshot (56)](https://user-images.githubusercontent.com/99309948/154037380-6ca4c8bd-497f-400d-9b7b-b6ff20f461b0.png)

**Comment by rupalichavan9860** [comment]
According to me it should not show camps as topic/agreement camp is selected. Once we select sub camp then only it should display camp

@BrentAllsop Can you please confirm?

**Comment by BrentAllsop** [comment]
Yes, the name of the root camp is always "Agreement".  Sometimes, we can consider it to be the name of the topic.
All other camps have their own name.

**Comment by rupalichavan9860** [comment]
Not an issue
