### ISSUE TITLE
Supported camps are not listing when user click on manage support in Firefox

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1161]
Chrome screenshot : 
![image](https://user-images.githubusercontent.com/40416610/154037469-2c490de2-8ba4-49f6-b15c-c43d12662284.png)

Firefox screenshot : 
![image](https://user-images.githubusercontent.com/40416610/154037594-08ae8c94-1e9e-4280-b374-fdd329e61f8f.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 This is working fine. Now same camps are showing on chrome and firefox browser.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
