### ISSUE TITLE
Spaces are getting trimmed when create or update  camp/topic but not in the URL

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1163]
![Screenshot 2022-02-15 at 9 18 09 PM](https://user-images.githubusercontent.com/91254708/154097574-9cd990f4-1416-403f-8a3e-377d66632e58.png)

**Comment by saniatg** [comment]
@sunilspr7 issue not fixed.
![Screenshot 2022-04-06 at 10 44 06 AM](https://user-images.githubusercontent.com/91254708/161900738-8893c25b-2778-4226-9fdf-ff35c26de12e.png)

**Comment by sunilspr7** [comment]
@saniatg  PR did not on Deployed  on Staging 
@karun0607gautam please deployed this PR  in staging

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production. @rupalichavan9860  Please confirm Once

**Comment by rupalichavan9860** [comment]
verified
