### ISSUE TITLE
Minor UI issue : Alignment of search functionality radio buttons is getting disturbed 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1166]
Please refer attached screenshot of staging : 
![image](https://user-images.githubusercontent.com/40416610/154219143-0e479f21-1243-4c0c-9eda-460c156af32e.png)

Expected Result : 
It should be like below
Live site Screenshot : 
![image](https://user-images.githubusercontent.com/40416610/154219237-ad94aff1-89aa-4921-ae1c-8ea095b94158.png)

**Comment by sonalizibtek** [comment]
Tested and verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested and verified on production. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
