### ISSUE TITLE
Firefox Browser issue : Remove All check box is not getting cleared when click on "Clear All Changes" on supported camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1168]
Pre-condition : Use Firefox browser
Steps to reproduce  : 
1. Open topic where user supported more than 2 camps 
2. Click on any camp and click on "Manage Support"
3. Click on "Remove All"
4. Now click on "Clear All Changes"

Actual Result : 
"Remove All" checkbox is not getting cleared in Firefox. (Note :  It is getting cleared in Chrome and Safari)

![image](https://user-images.githubusercontent.com/40416610/154222814-f8dbbad3-fa31-483f-ac39-de3848c162d9.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production @rupalichavan9860  Please confirm Once

**Comment by rupalichavan9860** [comment]
Verified
