### ISSUE TITLE
Safari Browser- Drag /drop is not working for supported camp list

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1169]
Precondition: Supported camps list for topic "topic_name" must be more than 1

When trying to change order, drag and drop does not work.
![Screenshot 2022-02-16 at 1 40 07 PM](https://user-images.githubusercontent.com/91254708/154223494-e9b89f6a-cdf3-4df1-8861-1e9061d8f1b7.png)

**Comment by saniatg** [comment]
Drag and drop is now working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
