### ISSUE TITLE
Labels are missing for all drop downs on "Manage Profile Info"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#117]
How user will know what is the meaning of drop down values "Public" and "Private".
All drop downs on "Manage Profile info" should have label "Visibility Status" like on "Add & Manage Nick Names".
![image](https://user-images.githubusercontent.com/40416610/42052797-66c3807c-7b2d-11e8-8d40-52a66cec8023.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its very clear from the field that itsfor visibility. It will look messy on this page if we give label to this field.
