### ISSUE TITLE
Error while accessing Facebook login

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1171]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/ or https://canonizer.com/
2. Click on Log in
3. Click on Facebook 

Getting below error 

![image](https://user-images.githubusercontent.com/40416610/154399902-e37cda9e-9a4b-4c53-bd92-b8c0f8e74db2.png)

**Comment by ashish76** [comment]
@rupalichavan9860 I am not able to replicate this issue. It is working as expected. Could you please verify at your end once?

**Comment by rupalichavan9860** [comment]
@ashish76 This is working fine now on both staging and live. So closing this
