### ISSUE TITLE
Score is not getting updated in the tree  for agreement camp and sub camps when removed support from 'Account Settings' page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1179]
Create a new topic
By default support gets added to agreement camp 
Now Click on account settings page and click 'supported camps'
Click on cross icon to remove support form agreement camp 
Come back to the topic 

Actual result : Support count will be seen 1 . The support is not removed from: Canonizer Sorted Camp Tree and Support Tree for "Agreement" Camp
Expected Result: Count must be seen 0, as there is no support
![Screenshot 2022-02-17 at 7 39 22 PM](https://user-images.githubusercontent.com/91254708/154500025-926c16d3-42d5-49e1-ac90-f9c9c22a5a44.png)
![Screenshot 2022-02-17 at 7 29 14 PM](https://user-images.githubusercontent.com/91254708/154500069-0340d7b6-6deb-4869-8fdd-73ea13e717e0.png)

**Comment by saniatg** [comment]
Verified and is working fine. @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
@aliahmad45 We are again facing the same issue . Can you please check

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
@ahmed130544 Again facing the same .

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
