### ISSUE TITLE
Minor grammatical mistakes on Multiple User Warning pop up

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1182]
I found some grammatical mistakes on Multiple User Warning pop up
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/154678027-fd655937-1221-495c-b429-9615923a3daf.png)

**Comment by sunnyjindal** [comment]
Could you please tag Daksh in this?

**Comment by ahmed130544** [comment]
@dakshiffort Can you please share correct grammar and English?

**Comment by dakshiffort** [comment]
It seems that there is already a user linked with this email in Canonizer. If that user belongs to you then it is a violation of Canonizer’s agreement. So we suggest you deactivate your other account and keep only a single master account active. If you do not want to deactivate then click on cancel and try linking with another email for this social account. If you wish to deactivate then select the account below and click submit. @ahmed130544 check this.

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 , Please confirm once.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified on Production. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
