### ISSUE TITLE
Commit button is missing when submitting statement update for the 2nd time

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1183]
Login with User A 
Create a topic and by default agreement camp is supported
Login with User B and add a statement .
User B is adding statement   , commit button will show first time and will be in  review.
Now again from User B  click on button 'Submit statement  update'  and submit update. 
On click 'Submit Update' immediately the statement is in review without showing the commit button.

Commit button must be seen .

**Comment by rupalichavan9860** [comment]
I found this issue in one more scenario : 
Steps to reproduce : 
1. Submit a proposed change to camp statement by different user (Do not commit changes)
2. Click on "Edit Change" and make some changes 
3. Click on "Submit" 

Expected Result : 
User should see "Edit Change" and "Commit Change" buttons and user should able to edit change during grace period

Actual Result : 
Statement is getting committed automatically  and user can't see countdown time with "Edit Change" and "Commit Change" buttons

**Comment by saniatg** [comment]
@kshitij1326 @rupalichavan9860 
Issue is not fixed.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on Production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
