### ISSUE TITLE
User is able to create multiple camps with name "Agreement" 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1184]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/154922594-a50ddee6-af66-4e70-a7a6-c916ed6512b1.png)

![image](https://user-images.githubusercontent.com/40416610/154922714-072fc38a-c38b-4417-aedb-478668394e51.png)

![image](https://user-images.githubusercontent.com/40416610/154924960-4be63e53-b8ad-4ca6-93af-f31439242cda.png)

Expected Result : 
Camp name "Agreement" is grant parent camp ,so user should not be allowed to create camp with name "Agreement"

**Comment by rupalichavan9860** [comment]
Also as of now user is able to create duplicate camp name with change in case. Please refer below screenshot 

![image](https://user-images.githubusercontent.com/40416610/165471300-3e31f346-0cc1-4db7-80af-1871f620612a.png)

@BrentAllsop Can you please confirm. Is this fine or do we need to restrict this?

**Comment by rupalichavan9860** [comment]
@kshitij1326 As discussed in meeting this is an issue . We should restrict user from creating/updating duplicate camp names with change case

**Comment by subhancd** [comment]
working fine. kindly verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
