### ISSUE TITLE
Topic submitter/direct supporter is unable to add camp statement

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1185]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A and create new topic(User A is supporter of Agreement camp)
3. Log out and login with User B
4. Add camp statement to agreement camp

Note : It will be in "In review" if user committed immediately and User A can either agree or object to change and 
If  User B not committed changes immediately ,it will take 1 hour grace period to be in "In review" state

Issue : 
User A is not able to add camp statement and can see below message "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state."

Screenshot of User A : 
![image](https://user-images.githubusercontent.com/40416610/154968896-3790554f-e8f0-40c0-bb7d-8c786fa0efa8.png)

Screenshot of User B : 
![image](https://user-images.githubusercontent.com/40416610/154968987-e80acd40-a448-4c5e-986f-40bcd021d488.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on Production
