### ISSUE TITLE
Incorrect choice number and incorrect score is displaying under support tree

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1191]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create topic with User A and create 3 camps(Camp 1, Camp 2 and Camp 3)
4. Support all 3 camps
5. Login with User B and delegate support to User A in any camp
6. Login with User A and create sub camp under Camp 2 and support new sub camp
7. Again got to Camp 2 and support 
8. Observe Score and choice numbers of Camp 3

Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/155290474-21d7fe8a-5b74-4793-a3f9-2a16d93c6284.png)

**Comment by rupalichavan9860** [comment]
Please refer one more scenario : 
1. Create topic By "User A" and create "Camp 1" and support "Camp 1"
2. Login with "User B" and delegate support to "User A"
3. Login with "User C" and delegate support to "User B"
4. Login with "User D" and delegate support to "User C"
5. Login with "User A" and create second camp "Camp 2" and support "Camp 2"
6. Observe total score of "Camp 1" and total score of topic

![image](https://user-images.githubusercontent.com/40416610/155319265-4e0127e2-3700-48b6-9892-ea8c4e88a2c2.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please verify Once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production.Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
