### ISSUE TITLE
User is not able to create and edit camp with valid Camp About URL 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1197]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Browse and select any topic 
4. Create new camp or update any existing camp with "https://www.example.com?post=1234" as Camp About URL 

Expected Result : 
It should allow user to save the data

Actual Result : 
It is displaying error message "The camp about url format is invalid. (Example: https://www.example.com?post=1234)" even if URL used is provided as example 

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/155930073-b32bfd29-d80c-4241-a0a4-ad3e6a11250e.png)

**Comment by saniatg** [comment]
Verified and is working fine. @rupalichavan9860 Please confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
