### ISSUE TITLE
Add News Module - Unable to add the valid URL in the Link field 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1199]
**Steps To Produce:**
1.Select any topics
2.Click on Add News
3.In the Link field try to enter the valid url 
**Actual Result:**  user entered the url as per mentioned in the error message  Example: https://www.example.com?post=1234 -but still  its throwing an error message to enter the valid url with example .
**Expected :** It should allow user to enter the valid url in the field 

**case2:**
1.Click on edit news 
2.enter the url - https://www.example.com?post=1234
Actual Result: It is throwing an error message to enter the valid url - 
![Screenshot (91)](https://user-images.githubusercontent.com/99309948/155932154-341db6a0-42ed-47c6-b0c4-c1f88f2b65e9.png)

**Comment by kshitij1326** [comment]
Fixed in another issue #1323

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
