### ISSUE TITLE
Implicit supporter of the agreement camp (by being a direct supporter of one of the sub camps) is unable to agree and object camp change

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1202]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A and create topic
3. Create new camp and support camp(Now User A is supporter of sub camp)
4. Login with User B and submit change to Agreement camp -add camp statement /Agreement camp /topic 

Expected Result : 
1. Camp statement should be in "in review" and Implicit supporter of the agreement camp(User A) should able to see object button and agree checkbox
2. Camp change should be in "in review" and Implicit supporter of the agreement camp(User A) should able to see object button and agree checkbox
3. Topic statement should be in "in review" and Implicit supporter of the agreement camp(User A) should able to see object button and agree checkbox

Actual Result : 
1. Camp statement is going live **(This is an issue)**
2. Camp change is in "in review" but Implicit supporter of the agreement camp(User A) is not able to see object button and agree checkbox**(This is an issue)**
3. Topic statement is in "in review" and Implicit supporter of the agreement camp(User A) is able to see object button and agree checkbox(**Working fine**)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine now. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
