### ISSUE TITLE
Delegated supporter is able to object topic/camp/statement change

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1203]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/
2. Login with User A and create topic
3. Create new camp and support camp "Camp 1"(Now User A is supporter of sub camp "Camp 1")
4. Login with User B and delegate support to User A
5. Login with User C and submit change to sub camp "Camp 1" - add camp statement /Change camp /Change topic 
6. Login with User B and observe History pages

Actual Result : 
Delegated supporter(User B) is able to object topic/camp/statement change 

Expected Result : 
Only direct supporter should able to object

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
verified on production
