### ISSUE TITLE
User can directly support with button "Directly join and support" even if as of date selected

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1204]
As per discussion user should never be able to change things from history pages, as history is immutable.
We need to disable the button "Directly join and support" with tooltip "History cannot be modified. In order to modify your current support select the default option in the as-of box."

**Comment by sonalizibtek** [comment]
1.We need to disable the button "Directly join and support" with tooltip "History cannot be modified. In order to modify your current support select the default option in the as-of box."
2. Tooltip background should be in black color 

Please confirm @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@kshitij1326 I can see tooltip and button is no clickable but not disabled. Can you please check

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on Production. Working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
