### ISSUE TITLE
Page crashes when internet is turned off and user try to Add/edit button 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1205]
1. Go to profile settings
2. Edit any field 
3. Now disconnect the wifi
4. Click Update button
5. You will see" Internet not working"
6. Not connect wifi, and refresh the URL

Page crashes

The same issue is for the following cases mentioned below:

- When adding nick name
- Creating  Camp 
- Creating Topic
- Creating/updating camp statement
- Create/edit /delete news
- Submit Support

![Screenshot 2022-02-28 at 5 54 03 PM](https://user-images.githubusercontent.com/91254708/155990780-6defc145-3d19-4507-888a-99fe258376da.png)

**Comment by saniatg** [comment]
@kshitij1326 this issue is not fixed . Still getting crash for all the cases mentioned above

**Comment by kshitij1326** [comment]
@saniatg could you please retest this as it was not deployed earlier

**Comment by saniatg** [comment]
Working fine now. @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 @kshitij1326 crash is coming in staging and production for
Add camp
add nickname 
add news
![Screenshot 2022-09-12 at 11 23 16 AM](https://user-images.githubusercontent.com/91254708/189583707-d06a98cf-3e5c-4560-8a49-7941a92cb0c2.png)

**Comment by cd-ali-ehsan** [comment]
It was decided in the call that we will add this to 35 release since it is not a critical issue. We also need to check it in Canonizer 3.0.

**Comment by saniatg** [comment]
@kshitij1326 The crash issue is resolved but if I click on browser refresh icon after internet is switched on , then whatever action user was performing is completed when inter was turned off , but If I click enter from keyboard, the page redirects to main page instead of completing the action

**Comment by kshitij1326** [comment]
@saniatg Could you please test again, now it will redirect back to edit page.

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now.

**Comment by rupalichavan9860** [comment]
verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production
