### ISSUE TITLE
User is  unable to see latest live record on camp statement history

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1209]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A and Create topic and camp and support camp "camp 1"
3. Login with User B and add camp statement for "camp 1" (It will be in "in review")
4. Login with User A and agree to the change submitted by User B
5. Submit one more change by User A(It will be live)

Expected Result : 
User A and User B both should see live record on history page

Actual Result : 
User A and User B both can see live camp statement on agreement page but User B is unable to see latest live record on camp statement history
Please refer attached screenshot with User B login : 

![image](https://user-images.githubusercontent.com/40416610/156317857-67f8b035-62c1-4062-9cda-01785cb04161.png)

![image](https://user-images.githubusercontent.com/40416610/156317954-f6d2886e-34df-4756-a439-98ab92d49180.png)

User A  login : 
![image](https://user-images.githubusercontent.com/40416610/156318039-b5aeb2f8-904e-4f43-8d5d-4c7b06f53997.png)

**Comment by saniatg** [comment]
@rupalichavan9860 working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on Production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
