### ISSUE TITLE
When user select “include review “ filter, user is not able to see Topic and camp names under Canonizer Sorted Camp Tree

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1210]
**Steps to Produce:**
1.Login with the credential 
2.Click on browse and select any topic 
3.Apply include review filter 

**Actual Result:** Include review : When user select “include review “ filter, user should able to see “In Review” topic names in Canonized list for - I m not able to see the Canonizer list of topic names 
![Screenshot (105)](https://user-images.githubusercontent.com/99309948/156363562-39a2d6f7-cf46-47fa-86a8-779cc005abd5.png)

**Expected Result:** When user select “include review “ filter, user should  able to see  “In Review” topic names in Canonized list for 
Also Canonizer Sorted Camp Tree should not be blank. It should display topic and camp names

**Comment by BrentAllsop** [comment]
I'm not able to reproduce this?

**Comment by sunnyjindal** [comment]
I am not sure but I think this is related to caching.

**Comment by rupalichavan9860** [comment]
Still getting issue for some topics

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production

**Comment by rupalichavan9860** [comment]
Again facing same issue 

![image](https://user-images.githubusercontent.com/40416610/159681081-ef265644-8332-4374-a2ff-3806430e0854.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Still this is not working for some topics when selecting "One Person One Vote" and "Mind Experts" and selected filter as "include review"

![image](https://user-images.githubusercontent.com/40416610/160057162-301c6841-2af8-44cf-9b50-5a166ab2d057.png)


please refer same topic when selected different algorithm than  "One Person One Vote" and "Mind Experts" and selected filter as "include review"

![image](https://user-images.githubusercontent.com/40416610/160057309-820c7719-aedd-45ee-b2b5-a2ba092bb361.png)

**Comment by rupalichavan9860** [comment]
Even tree is missing when selected filter as "default" for "One Person One Vote" and "Mind Experts" algorithm

![image](https://user-images.githubusercontent.com/40416610/160057536-1a771f12-5a1c-4b85-9bff-b0716396f21f.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
@ahmed130544 Again facing same so reopening this issue

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine now
