### ISSUE TITLE
"View This Version" is always displaying live records for topic/camp/camp statement records

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1219]
Submit change to topic/camp/camp statement - it will be in "in review" and click on "View This Version"
Observe page - 
Expected Result : It should display selected record changes
Actual Result : It is displaying live data only

Object change to topic/camp/camp statement - it will be in "objected" and click on "View This Version"
Observe page - 
Expected Result : It should display selected record changes
Actual Result : It is displaying live data only

**Comment by sonalizibtek** [comment]
**Case 1:**
Submit change to topic/camp/camp statement - It will be in live" and click on "View This Version"

-  Created a topic  with name [ Test Reg 31] 
-Click on Manage/Edit this topic , then edited the topic name into [ Test 31 Reg ] 
- then click on view version , 
**Actual Result** : In Topic Page , filter is in as of date  - this new topic name is showing [ Test 31 Reg  ] and newly edited  statement is shown
**Expected Result**: When filter is in as of date , it should display old topic name i.e [ Test Reg 31]
<img width="960" alt="Screenshot (254)" src="https://user-images.githubusercontent.com/99309948/160992501-a8018fa1-a568-4c44-bc85-b302340d8582.png">
<img width="960" alt="Screenshot (255)" src="https://user-images.githubusercontent.com/99309948/160992594-0370d52d-cc43-43ed-9584-c49ed998327e.png">

**Comment by sonalizibtek** [comment]
**CASE 2:** Submit change to topic/camp name - it will be in "in review" and click on "View This Version"
**Observe page -
**Expected Result** : It should display old  record when filter is in as of date  
**Actual Result** : It is displaying data which  is in review for "as of date filter"
<img width="960" alt="Screenshot (262)" src="https://user-images.githubusercontent.com/99309948/160996692-e68a556d-a8f3-4ead-a04e-1c375ad32764.png">
<img width="960" alt="Screenshot (265)" src="https://user-images.githubusercontent.com/99309948/160996731-3b0e2d38-33f4-4fed-8aaf-6b948b6f2587.png">
<img width="960" alt="Screenshot (266)" src="https://user-images.githubusercontent.com/99309948/160996775-b0ccb781-0b4a-4ac2-91e0-824d6ce498b1.png">

**Comment by sonalizibtek** [comment]
**CASE 3:**  Submit change to Manage/Edit this  statement  for Agreement camp  - it will be in "in review" and click on object , then click on  "View This Version"
Observe page -
**Expected Result** : It should display selected record changes(On selecting “ View This Version “, the user should navigate to the “Agreement Camp” page and should able to see specific contents of that selected record only)
**Actual Result** : It is displaying live data  when you are in "default filter ". 
<img width="960" alt="Screenshot (267)" src="https://user-images.githubusercontent.com/99309948/161007880-00d4c9a9-f230-4c68-88ed-5e833c98fc5a.png">

**Comment by rupalichavan9860** [comment]
@ahmed130544 This is not working for camps . Please refer below link

https://staging.canonizer.com/topic/507-retesting-1219-updated-1/2-camp-1?asof=bydate&asofdate=2022/05/10%2010:53:25

**Comment by rupalichavan9860** [comment]
@ahmed130544 Still not working for objected camp view this version and also "include review" is not working 

Objected : 
![image](https://user-images.githubusercontent.com/40416610/167418139-fceacd66-0836-4684-a2ae-f5a0c4595740.png)

Include Review : 
![image](https://user-images.githubusercontent.com/40416610/167417994-8d53bfbe-757f-4699-b21a-20fddd009713.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Got below  page crash on camp history page "View This version" 
![image](https://user-images.githubusercontent.com/40416610/167564815-9030481b-2324-4744-96e3-52069d503670.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 On filter "Default" , live camp name is not displaying in tree . Please refer below screenshot

![image](https://user-images.githubusercontent.com/40416610/167771519-d9c13c37-42b8-4414-a17d-13c8f382d700.png)

**Comment by saniatg** [comment]
@ahmed130544 found one case in which topic name is not visible when click 'View this Version'

1. User A created a topic and a camp and supported the camp
2. Login with User B and add statement in camp. It will be in review.
3. Now click on 'View this version'
![Screenshot 2022-05-12 at 10 43 17 AM](https://user-images.githubusercontent.com/91254708/167997425-6a8a2c73-9254-4091-9b20-84e618396938.png)

On click 'View this Version' the topic in the tree is not seen.

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 , Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified on production
