### ISSUE TITLE
Getting a pop up with message " error occurred" on click 'View this version' button

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1224]
Steps:

1. User A Created a topic and a camp 'camp1'
2. User A Supported Camp1
3. Login with User B and support Camp1
4. Now User B will try to add statement
5. Do not click 'commit' button instead 
6. Click on view this version, now come back again click on "manage/edit statement"
7. Now click commit button and click "view this version"

On click 'View this version' you will get a pop up for a sec " An error occurred" and then disappears.
![Screenshot 2022-03-10 at 10 00 03 AM](https://user-images.githubusercontent.com/91254708/157591828-3b663f45-ec50-4c0f-8e6d-086b5dd8af1e.png)

**Comment by rupalichavan9860** [comment]
Same exists on "Submit Camp Update Based On This"/"Submit Topic Update Based On This" and "Submit Statement Update Based On This" buttons

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 , please verify once

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
