### ISSUE TITLE
Page crash on "Remove Your Support" button when user click multiple times

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1225]
Select any supported topic/camp and click on "Remove Your Support" button multiple times, getting below page crash
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/157621994-0f430f70-caef-47ab-b10f-2b37963e0e2f.png)

**Comment by saniatg** [comment]
@sunilspr7 Still getting crash.Not fixed.
![Screenshot 2022-03-23 at 1 32 04 PM](https://user-images.githubusercontent.com/91254708/159651033-a0e7bbfb-9974-4adf-8724-396b831b5c3d.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine now. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Verified and is working fine on production. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
