### ISSUE TITLE
server-side template injection

### ISSUE THREAD

**Issue by shivvarman** [the-canonizer/canonizer.2.0#1226]
**Issue found in https://www.canonizer.com/topic/46-Abortion-Rights/1-Agreement?currentTime=**

1. (server-side template injection) - Due to this, attacker can use server-side template injection as the basis for numerous other attacks, potentially gaining read access to sensitive data and arbitrary files on the server.

The best way to prevent server-side template injection is to not allow any users to modify or submit new templates. 

One of the simplest ways to avoid introducing server-side template injection vulnerabilities is to always use a "logic-less" template engine.

**Comment by mark-shamy** [comment]
Vulnerability does not exist. Thank you for your feedback.
