### ISSUE TITLE
Incorrect namespace is showing when user is logged out and then logged in

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1227]
Steps:

1. Login and navigate to Browse page.
2. Select any namespace from the dropdown. e.g user selects 2nd namespace as 'corporations URL is https://staging.canonizer.com/browse?namespace=2 which is correct 
3. Now copy the URL and log out
4. Paste the URL in a new tab , the list will be seen correct
5. Click on Login link and log in the application
6. Now observe the URL, namespace selected and the records all are different.

Actual result: In the URL the selected namespace ID is seen and in the namespace field'General' is seen and the records are of the selected namespace.
Expected result: 'general' namespace showing selected is incorrect , should be the one that was copied .
![Screenshot 2022-03-10 at 4 42 34 PM](https://user-images.githubusercontent.com/91254708/157651594-6f009beb-5400-4860-8255-eb6d666c2bfb.png)

**Comment by sonalizibtek** [comment]
Tested and verified. Please confirm @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production. Working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
verified
