### ISSUE TITLE
Crash when removing delegated support

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1229]
Steps:

1. User A creates a topic and a  camp 'camp 1 'and supports camp1
2. User B delegates support to User A for camp 1
3. Now User A creates camp 2 and supports it, and then create camp 3 and support it too
4. Login as User B and remove support from Camp 1 on click 'Remove support ' button it will crash

Actual Result: On click " Remove your support"  user B gets crash
Expected Result:  Support must get removed .
![Screenshot 2022-03-10 at 6 10 52 PM](https://user-images.githubusercontent.com/91254708/157664158-c8ff9682-96a5-4735-833a-9f8f84e2d8ad.png)

![Screenshot 2022-03-10 at 6 06 07 PM](https://user-images.githubusercontent.com/91254708/157664205-e7e1f356-d600-4ce1-b4a8-d48927c5506e.png)

**Comment by saniatg** [comment]
@rupalichavan9860 This is fixed. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested on production and is working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
verified
