### ISSUE TITLE
Incorrect choice number and score is displaying and all supported camps are not listing under delegated supporter's lists

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1230]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A and create new topic
3. Create New camp "Camp 1" and support "Camp 1"
4. Login with User B and delegate support to User A in "Camp 1"
5. Login with User A and Create "Camp 2" and support "Camp 2" 
Note :  Observe score of "Camp 1" after supporting "Camp 2". Please refer below screenshot 

![image](https://user-images.githubusercontent.com/40416610/157665346-d9595491-636d-4686-938e-733350d392eb.png)

Also observe User B's supported camp page 

![image](https://user-images.githubusercontent.com/40416610/157665508-59678be8-c334-4128-913f-7fd34efa40f7.png)

6. Create "Camp 3" by User A and support "Camp 3" and 
Observe score and choice numbers for "Camp 2" after supporting "Camp 3". Please refer below screenshot 
![image](https://user-images.githubusercontent.com/40416610/157666063-84f5b759-b299-4e17-baa4-b332e68ec98e.png)

Also observe User B's supported camp page 

![image](https://user-images.githubusercontent.com/40416610/157666147-993bc155-47c1-4f23-90a7-b23b6346a042.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified in production . @rupalichavan9860  Please verify once

**Comment by rupalichavan9860** [comment]
Verified
