### ISSUE TITLE
Mobile- Drag and drop is not working for supported camp list 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1235]
Precondition: Supported camps list for topic "topic_name" must be more than 1

When trying to change order of the supported camps in the list , drag and drop does not work.
![Skype_Picture_2022_03_14T13_21_30_086Z](https://user-images.githubusercontent.com/91254708/158182238-8f89ed21-7880-4072-b882-ccfaeb87f25c.jpeg)

**Comment by rupalichavan9860** [comment]
Working fine now so closing this issue
