### ISSUE TITLE
'To' in the create /post thread is seen empty when Email ID is set to private

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1239]
Steps:

1. In the account profile settings, set email ID as 'Private'
2. Create a new Topic
3. Click on button 'Add forum' and create a thread

Actual Result: 'To'  in the email is seen empty
Expected Result: 'To'  in the email  must not be  empty irrespective of email Id been set as 'Private' or 'Public'
![Screenshot 2022-03-21 at 12 47 55 PM](https://user-images.githubusercontent.com/91254708/159218840-a8e151fe-1c8f-4b72-bacd-25a1da241685.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
