### ISSUE TITLE
Error message for "Add Nick Name" field is not proper on "Add New Nick Name" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#124]
Error message for "Add Nick Name" field should be "Nick Name is required." instead of "The nick name field is required."

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed, test and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 Error message should be "Nick Name is required."

**Comment by gautamv16** [comment]
@rupalichavan9860 as per standard error message is ok, please focus on other issue except these error messages.
