### ISSUE TITLE
When set 'As of' filter  to future, 'Manage Support' button is see disabled

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1240]
Steps:

1. Create a topic 
2. In the 'As if ' date filter choose any date that is of future.

Actual result: Remove your support button is seen enabled, which is correct but "Manage Support' button is seen disabled.
Expected result:  "Manage Support' button must also be enabled as the date selected is of future, only in case of past dates history cannot be modified.
![Screenshot 2022-03-21 at 12 20 33 PM](https://user-images.githubusercontent.com/91254708/159219394-280e819b-4e0b-4908-8ea4-6fa36069396d.png)

**Comment by sunnyjindal** [comment]
@kshitij1326 instead of disabling and enabling the buttons, we need to disable the selection of future date.

**Comment by sonalizibtek** [comment]
Tested and Verified , working fine. @rupalichavan9860 Please confirm once.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Verified on production and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
