### ISSUE TITLE
Incorrect Total Support score displaying for topic

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1246]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with User A
3. Create new topic and create 3 camps
4. Support all 3 camps
5. Login with User B and delegate support to User A in any camp
6. Again Login with User A and support "Agreement" camp
7. Again support all 3 camps
8. Now go to any camp - Manage support 
9. Click on "Remove All"
10. Click on "Submit"
11. Observe total score

![image](https://user-images.githubusercontent.com/40416610/159471886-16a0b6c8-66ea-47e9-9792-cb49a801938b.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm Once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
