### ISSUE TITLE
Validation is missing on "Add New Nick Name" page.It is accepting duplicate data

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#125]
Steps to Reproduce :

1. Go   to https://staging.canonizer.com/     
2. Click on Log in     
3. Login with valid Email and password    
4.Click on logged in user name and Go to Account Settings     
5.Go to Add & Manage Nick Names  
6.Enter existing data/record in "Add Nick Name" text box   
6.Click on "Create" button

Expected result:
Error message should be displayed for duplication.

Actual Result:
It is accepting duplicate data
![image](https://user-images.githubusercontent.com/40416610/42075657-8c3e8b78-7b8f-11e8-9685-640c18c22fec.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close. Its fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.But error message should be "Nick Name has already been taken." instead of "The nick name has already been taken."

**Comment by gautamv16** [comment]
@rupalichavan9860  will check these message thing with brent and JIM, please focus on funtional testing. According to me, all validation messages are correct and in standard format. The word is used as per validation message standard. So focus on other things. I can see most of the bugs are only for these validation messages.
