### ISSUE TITLE
Operating system Compatibility issue - "support@canonizer.com " link in footer is not working in Ubuntu system .

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1252]
**Steps to Produce:**
1. In ubuntu system , click on any page , check the footer and click support@canonizer.com link .
**Actual Result:** Please view this attached video link below 
https://www.loom.com/share/88e07999b3c640bf84631065224a2cc8
Expected Result: it should show an popup 
![Screenshot (225)](https://user-images.githubusercontent.com/99309948/159864616-ebc9d85b-cdcb-4542-8e7d-ad9e32cc96cb.png)

**Comment by kshitij1326** [comment]
This is a user specific setting on his/her system and it cannot be changed through the code. 
We discussed the issue on daily scrum and decided to ignore the issue and close the ticket.
