### ISSUE TITLE
"Remove Your Support" and "Delegate Your Support" buttons are grayed out even if selected filter is "default" 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1253]
Some times "Remove Your Support" and "Delegate Your Support" buttons are grayed out even if selected filter is "default" 
There is no specific scenario for this. Sometimes we are getting this issue after creating new camp or updating camp/statement

![image](https://user-images.githubusercontent.com/40416610/159884203-d96270a0-3f49-4b96-935b-dbe67d4a97d5.png)

**Comment by sonalizibtek** [comment]
<img width="960" alt="Screenshot (420)" src="https://user-images.githubusercontent.com/99309948/166857239-187d0a78-e10c-45da-af56-4a5824646de3.png">
Case 1:  User A and User B  are supporting “camp 1” and “camp 2”. Now when any user change parent of “camp 2” to “camp 1” but don't commit .
- go to user A and click on camp1 , click on view version,
-in topic view page click on , camp2.
