### ISSUE TITLE
Incorrect supported camp lists displaying and also page crash on "Remove Your Support" button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1258]
Steps to reproduce : 

Steps to reproduce : 
1. Create topic with "User A" , create 3 camps and support all
2. Login with "User B" and delegate support to "User A" 
3. Login with "User C" and delegate support to "User B"
4. Login with "User B" and create and directly support 4th camp 
6. Observe supported camp list of "User C"

Expected Result : 
User C is now delegated supporter of User B in 4th camp and should see 4th camp only under supported camps lists

Actual Result : 
It is displaying previously supported 3 camps  under supported camps lists. Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/160089189-d8304a4d-72f3-4f5f-aec1-2bfa34304228.png)

![image](https://user-images.githubusercontent.com/40416610/160089269-aabf4a75-b87d-466f-8629-7ccadb5268f3.png)

**Comment by rupalichavan9860** [comment]
Also getting crash when User C click on "Remove Your Support" from 4th camp 

![image](https://user-images.githubusercontent.com/40416610/160089629-37f50274-fe55-4992-9a2b-76197c7b098d.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and Verified in Production. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
