### ISSUE TITLE
Selected drop down value is not getting saved properly on "Add Nick Name" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#126]
1. Go to https://staging.canonizer.com/    
 2. Click on Log in     
3. Login with valid Email and password     
4.Click on logged in user name and Go to Account Settings     
5.Go to Add & Manage Nick Names  
6.Enter any text in "Add Nick Name" text box and select Visibility status as "Private"  
7.Click on "Create" button

Expected result:
It should save record with Visibility Status as "Private"

Actual Result:
Even after selecting "Private" from drop down it is saving record with "Public" as Visibility Status

![image](https://user-images.githubusercontent.com/40416610/42081536-4c6443c6-7ba3-11e8-865e-d5c47ac69f9a.png)

![image](https://user-images.githubusercontent.com/40416610/42081559-61261316-7ba3-11e8-8a43-af82a683f70d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed test and close.
