### ISSUE TITLE
Supports remains added for both parent and child camps

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1262]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 3 camps "Camp 1" ,"Camp 2" and "Camp 3"
4. Support all 3 camps by "User A"
5. Log out and login with another user "User B" and delegate support to "User A" in any camp
6. Again login with user "User A" and change parent camp of "Camp 1" to "Camp 2" from "Agreement"
8. Change parent camp of "Camp 2" to "Camp 3" from "Agreement"

Expected Result : 
Support should get removed from "Camp 3"

Actual Result : 
Support remains added for  "Camp 3" even if  "Camp 3" is parent camp of "Camp 1"
![image](https://user-images.githubusercontent.com/40416610/160823122-3204cf52-b238-42c6-ac4e-52ef2299398b.png)

**Comment by rupalichavan9860** [comment]
Please refer one more scenario : 
User A login only
1. Create new topic and create 4 camps "Camp 1" ,"Camp 2" , "Camp 3" and "Camp 4"
2. Support all 4 camps
3. Change parent camp of  "Camp 2" to "Camp 1" from agreement
4. Change parent camp of  "Camp 4" to "Camp 3" from agreement
5. Change parent camp of  "Camp 3" to "Camp 2" from agreement

Expected Result : 
Support should get added to only one camp according to parent child functionality and score should be "1"

Actual Result : 
Support remains added for "Camp 2" and "Camp 4"and score is "0.50" and "0.25" i.e. total score is 0.75

![image](https://user-images.githubusercontent.com/40416610/161004355-5c95c601-49c5-4740-907c-06fca7bf365f.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested and verified in Production @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
