### ISSUE TITLE
Page stops loading and white screen is seen  on click button 'View this version' for a proposed change

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1266]
Steps:

1. Login with User A and create a new topic
2. Create New camps "Camp 1 &camp2 " and support both camps 
3. Login with User B try to submit camp change by changing parent of camp1 to camp2 from 'Manage /edit this camp'
4 Commit changes and it will be in review .
5. Again commit camp change on click  button" Submit camp update based on this " This time do it reverse by changing parent of camp2 to camp1.
6. DO NOT click "commit' button instead click on  button 'View this version" 

Actual result: On click  'View this version" button page is taking time to load after sometime page stops loading and white screen is seen.
Expected result: Canonizer Sorted Camp Tree page must be seen according to the proposed change  click 'View this version' button
![Screenshot 2022-03-31 at 1 13 45 PM](https://user-images.githubusercontent.com/91254708/161011926-b92e01b9-41f8-4d51-8726-6ce72574bf24.png)

**Comment by rupalichavan9860** [comment]
This is working fine now as we have restricted child camp to be displayed in parent camp list so closing this
