### ISSUE TITLE
drag & drop the camp box on your choice position is only changing choice numbers, but score is not getting changed

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1268]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Account Settings ->Supported Camps
4. drag and drop camps 
5. Observe score

Expected Result : 
Score should get changed according to choice number

Actual Result : 
Only choice numbers are getting changed
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/161222940-6d81daad-da36-402c-a555-8296539d084e.png)

![image](https://user-images.githubusercontent.com/40416610/161222985-5d98c4df-370e-43c5-aab5-50c9c9cff44a.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 verified on production and is working fine.

**Comment by rupalichavan9860** [comment]
Verified
