### ISSUE TITLE
"Cancel" button is not working properly on "Add New Nick Name" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#127]
Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Click on Log in
3.Login with valid Email and password
4.Click on logged in user name and Go to Account Settings
5.Go to Add & Manage Nick Names
6.Enter data in fields
7.Click on "Cancel" button

Expected result:
It should clear out entered fields and should not save data

Actual result:
Data is getting saved to database

**Comment by gautamv16** [comment]
@rupalichavan9860 cancel button is removed as it has no use there. Please check and close issue

**Comment by rupalichavan9860** [comment]
Tested

**Comment by rupalichavan9860** [comment]
Tested.Working fine
