### ISSUE TITLE
Displaying old topic names under Canonizer Sorted Camp Tree for some specific topics

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1272]
Please refer below topics and screenshots : 
https://staging.canonizer.com/topic/37-Canonizer-Services/1-Agreement

![image](https://user-images.githubusercontent.com/40416610/161487920-c813bde4-dafa-4879-beb6-aa51aad7955e.png)

https://staging.canonizer.com/topic/6-Canonizer-Jobs/1-Agreement

![image](https://user-images.githubusercontent.com/40416610/161488016-86eb2b23-2aaf-4b6f-bdec-073af9d8daa9.png)

**Comment by saideekshith8** [comment]
Tested and Verified . @rupalichavan9860 Please confirm once

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
