### ISSUE TITLE
Creating new camp doesn't refresh original topic page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1275]
Go to any camp on any topic.
create a new camp.
Complete the creation of a new camp.

Once completed, you are sent to the new camp page.
However, the tree is not updated, so you can't see the new camp in the tree, until you refresh the page.

This also happens when you do things like add support for a camp.
You are returned to the camp, but the tree is not updated to include the new support you just added, until you refresh the page.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this again? Earlier there was mongo DB issue which is resolved now and this scenario is working fine as of now

**Comment by rupalichavan9860** [comment]
@BrentAllsop  I checked this on live and yes this is exists on live but working fine on staging. May be this will get fixed with 30th release

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this and close if working fine for you

**Comment by BrentAllsop** [comment]
Yup, working great now, so closing this.
