### ISSUE TITLE
Spaces should be trimmed after creating Topic / ManageEdit Topic name and when the topic name is saved

### ISSUE THREAD

**Issue by saideekshith8** [the-canonizer/canonizer.2.0#1277]
**Steps To produce:**
1. Create a Topic Name with more then one spaces 
2. And click on create topic button
3. Click on ManageEdit/this topic 
**Actual Result :** 
<img width="960" alt="Screenshot (300)" src="https://user-images.githubusercontent.com/102719279/161903269-6e751d32-f1e9-4106-9e25-9344ee9f5ade.png">
**Expected Result :** The spaces should be trimmed while saving  Topic name

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and Verified in Production @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
