### ISSUE TITLE
Incomplete text message when Subscribe and unsubscribe after use session expires

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1279]
Navigate to any topic 
Click on the check boxes "Subscribe to entire topic "or "Subscribe". 
Complete message is seen" You have successfully subscribed.
![Screenshot 2022-04-11 at 5 09 08 PM](https://user-images.githubusercontent.com/91254708/162889112-522c5566-0f8a-4993-a9a6-9ad04bc9977a.png)

Now leave the page idle and d not perform any action for few hours. After sometime when the session expires click on the check box  "Subscribe to entire topic "or "Subscribe". Only success message is seen instead complete message must be seen. 

![Screenshot 2022-04-11 at 5 08 22 PM](https://user-images.githubusercontent.com/91254708/162889246-fde511ef-7909-4590-9f98-eba04a216e4a.png)

**Comment by sonalizibtek** [comment]
Tested and Verified . It is working fine . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production
