### ISSUE TITLE
"Default Algorithm" sub tabs on "Account Settings" is displaying incorrect title

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#128]
Both sub tabs "My Supports" and " Default Algorithm" displaying same tittle name as "Supported Camps".
"Default Algorithm" should display respective title.

**Comment by gautamv16** [comment]
@rupalichavan9860 test and close this one

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified
