### ISSUE TITLE
Add options to camp records to prevent sub camps.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1287]
Add two independent checkbox options to the camp record edit form (display these values on the camp record):
Disable additional sub camps.    (mouse over msg: Disable the ability to add additional sub camps.)
Single level sub camps only.      (mouse over msg: "Disable the ability to add additional sub camps beyond direct sub camps."

This will also prevent changing a camp's parent to a camp that violates either of these check boxes if they are selected.

If currently on a sub camp where sub camps are not allowed, remove the "<Start new supporting camp here>".

Have Jim or Daksh Sharma review this English.

**Comment by rupalichavan9860** [comment]
This is not working properly

**Comment by kshitij1326** [comment]
@rupalichavan9860 
Could you please test this again, since the latest canonizer service for staging was not deployed on server

**Comment by rupalichavan9860** [comment]
Found below issue : 
Steps to reproduce : 
1. Create New topic and update Agreement camp - select  "Single level sub camps only" 
2. Create 2 sub camps "camp 1" and "camp 2"
3. Again update  Agreement camp - select  "Disable additional sub camps"
4. Go to "camp 1" update page  and  select  "Single level sub camps only" 
5. Observe update page and canonizer sorted camp tree

Actual Result : 
"camp 1" is not listing under "Agreement" camp 

![image](https://user-images.githubusercontent.com/40416610/189048472-a15fbbac-36b6-42e3-b22c-0800822eb3b9.png)

![image](https://user-images.githubusercontent.com/40416610/189048577-7e545bea-b41c-490e-8a2a-46a0f3ca0fa8.png)

**Comment by rupalichavan9860** [comment]
Tested and verified . I tested with all possible cases and looks okay to me

**Comment by rupalichavan9860** [comment]
Verified on production 
@BrentAllsop Can you please verify this ticket?
