### ISSUE TITLE
"Choose default algorithm preferences" drop down values on "Default Algorithm" page are not displaying in alphabetically sorted order

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#129]
![image](https://user-images.githubusercontent.com/40416610/42083241-f2243218-7ba7-11e8-9b7f-8ce695c45858.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its not required as it a  standard from 1.0 system...
