### ISSUE TITLE
Issues in Subscribe to the Camp functionality

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1291]
**case** 1: User should not receive notification once he is unsubscribed
User  A and User C - subscriber of  camp1
User B added a support for camp1 - both User A and User C received an subscribed  email 
User C will unsubscribe 
Then User B delegated the support , - User C is receiving the subscribed email 
**Expected** : User C should not receive the email , only User A should receive email  - **Working fine**

**case 2:**
User A subscribed the camp1
User B created a sub camp for camp1
But User A dint receive the Subscribed email 
**Expected :** User A should receive an email - **Working fine**

**Comment by sonalizibtek** [comment]
**Case 3:**
1.User A created topic and created camp1 and subscribed only camp1
2. User B added a statement to camp1
**Actual Result** : User A dint receive a subscribe email notification
**Expected** : User A should receive the email notification -**Working fine**

**Case 4:**
1.User A created topic and created camp1 and subscribed only camp1
2. User B created a sub camp for camp1
**Actual Result :** User A dint receive a subscribe email notification
**Expected** : User A should receive the email notification - **Working fine**

**Comment by sonalizibtek** [comment]
case1 : 
1.Create a topic , create camp1 and subscribe only camp1 by user A
2. Create a camp2 by user B 
3. Support a Camp2 by user A 
Actual result : User A received a subscribe email for removing a support from agreement 
Expected : Only if there is any change for camp1 , user A should receive an email  - **Invalid*
<img width="960" alt="Screenshot (413)" src="https://user-images.githubusercontent.com/99309948/165943369-bfc5ded1-68a1-4403-9b01-c2a30b0ad1cf.png">

case2:
"User A created topic and camp ,
and subscribed the camp 
User B edited the topic and committed it "
Expected : Only if there is any change for camp1 , user A should receive an email  -**Invalid**
<img width="960" alt="Screenshot (414)" src="https://user-images.githubusercontent.com/99309948/165944618-76683c57-aa42-4d46-bb07-6a939c80c0b6.png">

case3:
"User A created topic and camp ,
and subscribed the camp 
User B add statement to topic and commit it "
Expected : Only if there is any change for camp1 , user A should receive an email -**Invalid**

**Comment by sonalizibtek** [comment]
**case4:**
"1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
5.Add a support  by user A
6. Observe the email
 **Actual Result :**
1.User A  received the subscribe notification for removing a support of agreement camp
**Expected :**
2.2.User A should not receive the subscribe notification for removing a support of agreement camp - **Invalid**

**case5:**
1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
6.create a sub camp under camp1  and add support to sub camp by user B
6. Observe the email
 **Actual** :"User A dint receive the subscribe notification for supporting the sub camp"
**Expected** : "User A should receive the subscribe notification for supporting the sub camp" -** Fixed**

**case6**:
"1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
5.Create a sub camp under camp1 by user B
6.User A directly supported the sub camp1
7.User B delegated a support to sub camp1
6. Observe the email
 **Actual** :"User A dint receive the subscribe notification for supporting the sub camp"
**Expected**: "User A should receive the subscribe notification for supporting the sub camp" - "**Fixed**

**Comment by sonalizibtek** [comment]
**case7:**
"1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
5.Create a sub camp under camp1 by user B
6.User B added a statement to sub camp
7. Observe the email
 **Actual** :"User A dint receive the subscribe notification for adding a statement to the sub camp"
**Expected** :"User A should receive the subscribe notification for adding a statement to the sub camp" - **Fixed**
"
**case8**:
"1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
5.Create a sub camp under camp1 by user B
6.User B changed the parent of  sub camp to agreement from camp1
7. Observe the email
 "
**Actual** :"User A dint receive the subscribe notification for changing the parent of  sub camp"
**Expected** :"User A should receive the subscribe notification for changing the parent of  sub camp" - **Fixed**

**Comment by sonalizibtek** [comment]
**case9**:
"1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Click on Create New Topic
4. Create the topic  and camp1 , subscribe the camp1 by user A
5.Create a sub camp under camp1 by user B
6.User A added a support for sub camp, User B delegated to sub camp, User C delegated to User B for sub camp
7. Observe the email
 "
**Actual** :"User A dint receive the subscribe notification "
**Expected** :"User A should receive the subscribe notification " - **Fixed**

**Comment by sonalizibtek** [comment]
Four cases have not yet fixed, @kshitij1326 .

**Comment by rupalichavan9860** [comment]
Tested and Verified

**Comment by sonalizibtek** [comment]
Tested and Verified on Production. @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified on production
