### ISSUE TITLE
Direct user is unable to delegate their support to another immediate direct supporters(downwards)

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1294]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/163945142-9e6da153-276e-41aa-b242-b2793ab1af31.png)

![image](https://user-images.githubusercontent.com/40416610/163945234-8f32d938-4d7b-4477-8d5a-635397abc060.png)

**Comment by saniatg** [comment]
Tested and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested on production and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
