### ISSUE TITLE
Delegated support is getting removed and displaying incorrect score 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1295]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic By User A
4. User A is supporter of Agreement camp
5. Login with User B and delegate support to User A in Agreement camp
6. Login with User C and delegate support to User B in Agreement camp
7. Login with User D and support Agreement camp directly 
8. Login with User E and support Agreement camp directly 
9. Login with User A and create new camp "Camp 1"  and support "Camp 1"

Expected Result : 
1. User A should be direct support of "Camp 1" , User B should be delegated supporter of User A in "Camp 1" and User C  should be delegated supporter of User B in "Camp 1" and total score should be "3"
2. User D and User E should be direct supporter of Agreement camp and total score should be "5"

Actual Result : 
1. User C is not displaying as a delegated supporter under User B and total score of "Camp 1" is displaying as "2" instead of "3"
2. Total score of Agreement camp is displaying as "4"

screenshots : 

Before creating new camp : 
![image](https://user-images.githubusercontent.com/40416610/163950014-f7142b92-f5b6-484f-8496-33d0a59a700b.png)

After User A creating new camp and supporting new camp : 
![image](https://user-images.githubusercontent.com/40416610/163950178-12a17252-0f65-46d2-8964-89e4612a790c.png)

**Comment by rupalichavan9860** [comment]
Scenario 2 : 
1. Login with User A and create new topic
2. Create new camp and support
3. Login with User B and delegate to User A
4. Login with User C and delegate to User B
5. Login with User D and delegate to User C
6. Login with User A and create another camp and support camp
7. Now try to support "Agreement" camp

It is displaying "Agreement" camp twice like below
![image](https://user-images.githubusercontent.com/40416610/163989695-8d28df55-b05f-4cce-bead-9c5939603be8.png)
 
And when submitting support, support of delegated users- "User C" and "User D" is getting removed

![image](https://user-images.githubusercontent.com/40416610/163989835-e2d95cfc-755d-49cb-97d0-987f1c631761.png)

**Comment by sonalizibtek** [comment]
Tested and verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
