### ISSUE TITLE
Topic name is displaying instead of camp name in Proposed change to topic email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1298]
When user A directly supporting Agreement camp and also subscribed to entire topic and another user(User B) proposed change to topic, User A is receiving email, but in listing it is displaying "You are directly supporting `Link to topic name`" instead of "You are directly supporting `Link to Agreement camp `"
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/164156081-2a6036b4-ce78-4ded-8b28-b001e59842dd.png)

**Comment by rupalichavan9860** [comment]
Fixed in another ticket of 31st release so closing this issue

**Comment by rupalichavan9860** [comment]
This is still exists for below scenario : 
1. Create topic By User A in one namespace 
2. Login with User B and submit proposed change to topic (update namespace)
3. Observe email 

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/170544067-cccca9ac-49bb-4cfe-923c-89a4ac6656b6.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. Its working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
