### ISSUE TITLE
Button name is displaying as "Remove Your Support 1" 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1300]
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/164213554-4768e91d-b61e-4c6b-ac88-92e87275995b.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Verified and is working fine. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Verified and is working fine  on production. @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
verified
