### ISSUE TITLE
"Agreement" camp is displaying twice while supporting

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1301]
Scenario: 
1. Create new topic by User A
2. Create 2 camps and support both
3. Try to support agreement camp

getting below on supported camps page : 
![image](https://user-images.githubusercontent.com/40416610/164216580-70ccfd8b-4197-4c01-9733-c73ff41e6b1d.png)

And after supporting choice number is displaying as "2" 

![image](https://user-images.githubusercontent.com/40416610/164216747-9579add7-782d-4b6e-873c-a358002b7975.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Verified and is working fine on production. @rupalichavan9860 please confirm.

**Comment by rupalichavan9860** [comment]
Verified
