### ISSUE TITLE
Supports getting added multiple times and getting incorrect warning while submitting support

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1304]
Create scenario like below : 

![image](https://user-images.githubusercontent.com/40416610/164261110-0e3376b4-9041-49ed-b6bf-dccb6cbe16cd.png)

Login with User B i.e. "RC" in above scenario and try to support "camp 1" directly and click on submit, getting below warning,

![image](https://user-images.githubusercontent.com/40416610/164261887-f657a2f1-0e1e-4348-bdf8-0445b3a6d82d.png)

also observe support tree of "camp 1" : 
![image](https://user-images.githubusercontent.com/40416610/164262177-62d461c2-8603-4786-acb9-a758327cef01.png)

Supports are getting added multiple times

**Comment by sonalizibtek** [comment]
Tested and verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and working fine on production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
