### ISSUE TITLE
Wrong name used in e-mail about change to supported.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1307]
![image](https://user-images.githubusercontent.com/6559312/164558008-0232e228-f293-4380-933a-5632430f3398.png)
As you can see in the above screen shot, Brannock proposed a change to a topic.
However, this is the e -mail that was sent to a supporter:
![image](https://user-images.githubusercontent.com/6559312/164558099-5f8286cb-1992-498f-99af-350931f6a29b.png)
It should say "brannock" has proposed a change with a link to his id not Brent Allsop, who was the submitter of the record before this change record.

**Comment by rupalichavan9860** [comment]
@BrentAllsop This is known issue and fixed on staging . It will get fix on live in 30th release. Please refer #1111

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this again

**Comment by BrentAllsop** [comment]
Yup, tested it and appears to be working.
