### ISSUE TITLE
Page Crash on accepting the parent change camp  for User B 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1308]
**Steps to Reproduce:**

1.Create new topic and create 2 camps (By User A) and support both camps
2.Login with User B and support both camps(In other browser)
Case 1 : Change Parent camp of "camp 1" to "camp 2" from "Agreement"
Case 2 : Change Parent camp of "camp 2" to "camp 1" from "Agreement" 
Click on Submit and Click on Commit changes(It will be "In Review")
3. Click on view this version in camp2 parent change (User B , the page keeps loading and got 500 error )
4. In User A side , click on camp2 and click on accepted changes , 
5. Then go to User B browser . 
**Actual Result** : Page Crash for 
![Screenshot (360)](https://user-images.githubusercontent.com/99309948/164608791-17bf1d71-f2fd-4dd6-8805-2ac7316aacef.png)
User B

**Comment by rupalichavan9860** [comment]
This is working fine now so closing this
