### ISSUE TITLE
UI of grid is getting disturbed in case of long Nick Name on "Add & Manage Nick Names" .

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#131]
"Add Nick Name" field should have some max limit.Because of long nick name UI of grid is getting disturbed(Not able to see Visibility Status column)Please refer attachment

![image](https://user-images.githubusercontent.com/40416610/42084093-63fb483e-7baa-11e8-926b-995e54203c03.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
