### ISSUE TITLE
Camp name is not displaying as a parent camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1310]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password (User A)
3. Create new topic and create 2 camps and support both camps - User A Login
4. Login with User B and support both camps
5. Login with User B and change parent camp of "camp 1" to "camp 2" from "Agreement"
6. Login with User A and object change proposed by User B
7. try to change parent of "camp 2" to "camp 1" by any user

Actual result : 
"camp 1" is not listing in parent camp drop down

Expected Result  : 
"camp 1" should display under parent camp drop down

**Comment by ahmed130544** [comment]
@rupalichavan9860 issue also exists if we do not object change, in review state, "camp 1" is not listing in parent camp drop down when wants to add change in camp 2.

**Comment by sonalizibtek** [comment]
Tested and verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
As per discussed in meeting we have reverted this changes ,as because of this parent camp and child camp are going in a loop and getting page crash on View this version refer #1378.  
Tested with reverted changes and working

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified
