### ISSUE TITLE
Score Count is seen wrong when changing parent camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1311]
Steps:

1. User A creates a topic and camps and is supporting “camp 1” and “camp 2”
2. User A changes parent of 'camp2' to 'camp1'. Score of camp 2(child ) is 1 which is correct
3. Now change parent of camp 2 to 'agreement' score of camp2 is '1' and camp1 is '0' which is correct
4. Change parent of 'camp1' to 'camp2' and observe score of camp2
This time score of camp2 becomes '0' which is wrong . The score should have remained same.

**Comment by subhancd** [comment]
working fine. @saniatg kindly, verify

**Comment by saniatg** [comment]
Working fine. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
