### ISSUE TITLE
Mail content is seen wrong in case support is removed from agreement 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1315]
steps:

1. User A creates a topic and camp 1 , camp2. Supports agreement camp
2. Also is subscribed to agreement and 'Entire topic subscription'
3. User B submits change for topic and is in review. Mail content is seen correct
4. Now User A unchecks 'subscribe' button  and gives support to camp 1. Now support is removed from agreement and given to camp 1 .
5. User B again submits change in the topic.

This time In mail sent to User A still shows that "You  are directly supporting 'Topic_name' ". But the support was removed in step 4
![Screenshot 2022-04-25 at 4 26 57 PM](https://user-images.githubusercontent.com/91254708/165076504-f8ad8b58-3070-4486-af05-b993ec9e8f4d.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Issue seems to be fixed and  is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on Production

**Comment by rupalichavan9860** [comment]
Verified
