### ISSUE TITLE
"My topics" check box is not working for a specific case

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1318]
Steps:

1. Login and navigate to Browse page.
2. Select any namespace from the dropdown. e.g user selects 2nd namespace as 'corporations URL is https://staging.canonizer.com/browse?namespace=2 which is correct
3. Now copy the URL and log out
4. Paste the URL in a new BROWSER , the list will be seen correct
5. Click on Login link and log in the application
6. User will see the namespace correctly, click on "My topics" check box

Actual result : On click "My topics" check box page is not refreshing, it gets stuck there.
Expected result: "My topics" check box only my topics related to that namespace must be seen
![Screenshot 2022-04-26 at 12 21 13 PM](https://user-images.githubusercontent.com/91254708/165239248-a10b57a7-2e1b-4697-8a80-6cfd49069087.png)

**Comment by subhancd** [comment]
fixed @rupalichavan9860

**Comment by saniatg** [comment]
@ahmed130544 mentioned case above works fine but the same issue is seen when select'My topic'
Steps:

1. Login and navigate to Browse page.
2. Select any namespace from the dropdown. e.g user selects 2nd namespace as 'corporations' and check the box' My topics created' is URL https://staging.canonizer.com/browse?namespace=2&my=2 which is correct
3. Now copy the URL and log out
4. Paste the URL in a new BROWSER , the list will be seen correct
5. Click on Login link and log in the application

Actual result : URL https://staging.canonizer.com/browse?namespace=2&my=2  is seen but the check box is not checked 
Expected result: "My topics" check box must be checked.
![Screenshot 2022-05-31 at 11 40 35 AM](https://user-images.githubusercontent.com/91254708/171104147-08a34f0d-20d9-4e60-aafd-12abeceefb78.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 This is not fixed

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now . Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested in Production. It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
