### ISSUE TITLE
User is not able to delete uploaded file on "Upload File" grid.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#132]
"Upload File" should have delete functionality so that user can delete if he/she by mistakenly uploaded wrong file.

**Comment by BrentAllsop** [comment]
For the time being, we don't want to be able to delete files.
If the user must delete something, they will need to contact support, for the foreseeable future.
But, to resolve this issue, let's add a warning near the submit button, which will let the user know there will be no way to delete this operation.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
