### ISSUE TITLE
Issues on Subscribe Entire Topic 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1320]
Issue 1 : Incorrect content is displaying in email when any user creates a new camp
Steps to reproduce : 
1. User A create new topic and subscribed to entire topic 
2. User A or User B creates new camp (User A should receive email as User A is Subscribed to Entire Topic)

Actual Result : 
User A receives email but content is not proper 
![image](https://user-images.githubusercontent.com/40416610/165460568-b2e47228-2d41-4207-929d-a83af984da21.png)

@BrentAllsop @sunnyjindal Can you please check and provide proper content

**Comment by rupalichavan9860** [comment]
@kshitij1326 As discussed in meeting remove content from mail body
"which you currently subscribed. If no supporters of this camp [Regression 30th release / camp 1 ](https://egfggag.r.af.d.sendibt2.com/tr/cl/Z5BEwBDiGmTMELza9IQAvazUv6lzAAXKLORZCh3dgyrka_k2pvO7BWX1EZklNKokdR_ZN27hiVJd5n1jbMEKEM_zMnBKgDbLCGilXbrXS6ZPTlvBOP7FICIravCLjYEUdrI-UkBedkc2wHa9oToClxfYl7bEOofVd5OAOvNiNh2nR35Clx7uIdCaw3WwAGliSLNeIxPMFkAthJXA9eHuDjoGmKzDoyJJ6tPbQWnI9AnbeMTrlMGMS-SMv9q9BLCcKQ)object to this change, it will go live in one day / 24 hours."

**Comment by kshitij1326** [comment]
As mentioned i have to remove the specified content when a new camp has been created. But what happen when a camp has been updated and it go live immediately (when no supporter are there). Are we removing the content or keep as it is ?

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and Verified on Production. @rupalichavan9860 Please confirm

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and working fine on Production.

**Comment by rupalichavan9860** [comment]
Verified on production
