### ISSUE TITLE
User is not able to subscribe camps 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1321]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password (User A)
3. Create new topic and create 2 camps and support both camps - User A Login
4. Login with User B and support both camps
5. Login with User B and change parent camp of "camp 1" to "camp 2" from "Agreement"
6. Login with User A and object change proposed by User B
7. Try to subscribe both camps  "camp 1"  and "camp 2"

Actual result : 
As it is considering "camp 1" and "camp 2" as a parent child even if it is objected ,it is not allowing to subscribe to both camps

Expected Result  : 
User should able to subscribe both camps

**Comment by rupalichavan9860** [comment]
ref issue #1310

**Comment by subhancd** [comment]
working fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production . It is working fine. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified on production
