### ISSUE TITLE
User is not able to open the news link 

### ISSUE THREAD

**Issue by shahab-ramzan** [the-canonizer/canonizer.2.0#1323]
If I add a news link without any protocol (http or https) and the protocol for that link is http, in that case I’m unable to to open the link from news feed since the actual URL runs on http.  For example if I add link: [app.tetongps.com/login](http://app.tetongps.com/login)

After appending protocol from newsfeed it becomes: https://app.tetongps.com/login

A correct solution would be to add a validation that would prevent user from adding the news link until they have added the protocol (http or https)

**Comment by rupalichavan9860** [comment]
We need to implement same for camp statement as I have tested and above validation is missing for URL's on statement page.

**Comment by rupalichavan9860** [comment]
@kshitij1326 Working fine for news but still not working for statement

**Comment by subhancd** [comment]
working fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
