### ISSUE TITLE
nick name field behaves differently in create new topic page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1324]
Steps to reproduce :

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. click on "create new topic"
4. select a nick name which is not showing at the top of the nick name list
5. enter a special character in "topic name" field
6. click on create topic button

Expected Result:
All the fields shall behave in the same way after click the page refreshes upon clicking create topic button

Actual Result:
All the fields have the data user has entered except the "nick name" field. Nick name fields set to the first nick name in the list.

[screenshot](https://gyazo.com/94ba8ba45cbbca9b257deb5953e04a55)

**Comment by subhancd** [comment]
fixed

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production

**Comment by sonalizibtek** [comment]
Tested on Production. its working fine @rupalichavan9860 Please confirm
