### ISSUE TITLE
nick name field resets in the drop down on manage/edit this topic page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1325]
Steps to reproduce

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. click on browser
4. select a topic from sandbox testing
5. navigate to current topic record
6. click on manage/edit this topic
7. click on submit topic update based on this
8. select a nick name which is not at the top of the drop down
9. add a special character in topic name field
11. click on submit topic based on this

Actual Result:
nick name is reset to the first name in the drop down

Expected Result:
nick name field shall not reset

**Comment by subhancd** [comment]
fixed.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production .It is working fine . @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
