### ISSUE TITLE
nick name field resets in manage/edit this camp

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1326]
Steps to reproduce

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. click on browser
4. select a topic from sandbox testing
5. navigate to current camp record
6. click on manage/edit this camp
7. click on submit camp update based on this
8. select a nick that is not at the first position in the 
9. enter invalid data in the url field
10. click on submit update button

Actual Result:
nick name field resets to the first nick name in the drop down

Expected Result:
nick name field shall not reset as other fields are not resetting

**Comment by subhancd** [comment]
parent camp field resets. all fields shall behave in the same way.

**Comment by subhancd** [comment]
fixed.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
