### ISSUE TITLE
camp about nick name and nick name field resets in create new camp page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1327]
Steps to reproduce

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. click on browser
4. select a topic from sandbox testing
5. click on create new camp
6. select a nick name which is not at the top in the drop down
7. enter invalid data in the url field
8. select a user from the camp about nick name field
9. click on create camp

Actual Result:
camp about nick name field and nick name field resets while the rest of the fields are not reset

Expected Result:
all the fields shall behave in the same way

**Comment by subhancd** [comment]
"Camp about nick name" field is reset. "Parent Camp" field also resets. all fields should have same behavior.

**Comment by subhancd** [comment]
fixed.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
