### ISSUE TITLE
nick name field is reset in create a thread page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1328]
Steps to reproduce

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. click on browser
4. select a topic from sandbox testing
5. navigate to camp statement
6. click on camp forum
7. select a nick name
8. click on create thread

Actual Result:
nick name resets to the first nick name in the list
Expected Result:
nick name field shall not reset

**Comment by subhancd** [comment]
fixed. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
