### ISSUE TITLE
check box on browse page remains checked on returning back to the browse page

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1329]
Steps to reproduce:

1. navigate to https://staging.canonizer.com/
2. login with valid username and password
3. click on browse
4. check the checkbox, "only my topics"
5. click on a topic 
6. click on the back button in the browser

Actual Result: 
Check box is still ticked and it is showing all the namespaces

Expected Result:
check box shall be unchecked once user moves to other page from browse

**Comment by subhancd** [comment]
fixed @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified
