### ISSUE TITLE
Proper error message should display when File Name is too long on "Upload File" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#133]
Error message should display like "File Name may not be greater than 255 characters"

![image](https://user-images.githubusercontent.com/40416610/42085297-a88cfc2e-7bad-11e8-95a8-3392dc340fff.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test it. It will have customer predefined messages of the tool.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
