### ISSUE TITLE
Error"Statement field is required " is still seen even if data is added in the field .

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1330]
Steps:
1-Add statement by any user , add all the data in the fields and it will be live if it has no supporters
2- Now click on Manage/Edit statement
3-Click on  button "Submit update based of this"
4- You will see the data pre-filled, now clear data in statement field
5- Click on submit button
6- You will see the error but the cleared data in the statement field is seen back
Refer screenshot
![Screenshot 2022-04-29 at 12 07 14 PM](https://user-images.githubusercontent.com/91254708/165945842-adcd071d-7352-46f8-91d9-21d5bc95e125.png)

**Comment by sonalizibtek** [comment]
Tested and Verified, its working fine @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
