### ISSUE TITLE
Support is getting removed from both child and parent camp while changing parent 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1334]
Steps to reproduce : 
1. Create topic and 2 camps by "User A" and support both camps
2. Login with "User B" and delegate support to "User A" in any camp
3. Login with User A and Create new camp "Test camp 1" and support camp "Test camp 1"
4. Update "Test camp 1" and change parent camp to "Camp 1" from "Agreement"

Expected Result : 
Support should get removed from parent camp 

Actual Result : 
Support is getting removed from both camps(parent and child)

**Comment by rupalichavan9860** [comment]
Steps to reproduce : 
1. Create topic and 2 camps by "User A" and support both camps
2. Create new camp "Test camp 1"
3. Update "Test camp 1" and change parent camp to "Camp 1" from "Agreement"

Expected Result : 
Support should get removed from parent camp and added to child camp

Actual Result : 
Support is getting removed from parent but not added to child

**Comment by subhancd** [comment]
working fine. @rupalichavan9860 kindly, verify

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
