### ISSUE TITLE
Explain why greyed out buttons can't be executed.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1336]
![image](https://user-images.githubusercontent.com/6559312/167271888-2760acfe-e320-46c4-95c7-6c9ad6f71682.png)

If you mouse over this greyed out "object" button with the (i), it just says:
"You cannot object" which is already obvious, that is why it is greyed out and does not work.

It should say why, or describe what is required to object.  Something like: "**Only direct supporters at the time this change was submitted can object.**"

**Comment by rupalichavan9860** [comment]
@BrentAllsop On "Object" button click we already have pop up which describes what is required to object

![image](https://user-images.githubusercontent.com/40416610/167300875-6294c3f1-95cb-4193-9166-ced91272210a.png)

Can you please confirm, do we still need the same in tooltip?

**Comment by BrentAllsop** [comment]
good point, that looks great, I didn't realize this popped up if you clicked on it.
Would this be an improvement on that?  "**Only direct supporters at the time this change was submitted can object.**"
keep the "For more information...." stuff.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
