### ISSUE TITLE
Support is getting removed ,when user B edits the camp name

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1338]
**Steps to Produce:**
1.User A created topic  and subscribed ,by default support got added to agreement camp
2.User A created a camp
3.User B edited the camp name from camp to camp1

**Actual Result** :.In User A side score changed to [0]. score is getting removed
**Expected** : Support should not be removed from parent camp
<img width="960" alt="Screenshot (437)" src="https://user-images.githubusercontent.com/99309948/167382630-0ecc1679-e41d-475a-983f-b771fcd73fb5.png">

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
