### ISSUE TITLE
Footer contents of Blog page are different than other pages of Canonizer

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#134]
I think footer contents for all pages should be same.Please confirm?
![image](https://user-images.githubusercontent.com/40416610/42089384-7d280d5a-7bba-11e8-99dd-4de724f9081b.png)

![image](https://user-images.githubusercontent.com/40416610/42089402-932a02d4-7bba-11e8-8c42-660f1215685e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please check and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and vefified
