### ISSUE TITLE
Page crash on selecting Mind Experts algorithm

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1344]
Steps to reproduce : 
1. https://staging.canonizer.com/
2. Login with valid email and password
3. Select any topic and go to any camp history page
4. Click on "View This Version"
5. Select "Mind Experts" algorithm 

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/167811581-1e90e13b-d407-4271-993f-135c5f4ea43f.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by sonalizibtek** [comment]
Tested and Verified on Production. @rupalichavan9860 , Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
