### ISSUE TITLE
Supports are not getting removed when removing supports from Manage support -Remove All

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1346]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 2 camps
4. Support both camps
5. Go to any camp and click on "Manage Support"
6. Click on "Remove All" checkbox and Click on Submit

Expected Result : 
Supports  should get removed from both camps

Actual Result : 
Supports are not getting removed

**Comment by saniatg** [comment]
@sunilspr7 there is a case where support must be removed.
Steps to reproduce :

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic and create 2 camps
4. Support any one camp eg 'Camp1'
5. Login with User B , delegate support to 'Camp1'
6. Now click on button'Directly join/support' 2nd camp 'camp2' by User B
7. Message'Warning! You have delegated your support to user sani under this topic. If you continue your delegated support will be removed.' is seen and Camp1 and camp2 is seen, now click on"Remove All' button

Actual Result: Support is removed from camp 1 which was delegated, but not from camp2
Expected result: Support must get removed from camp 1 and camp2 from both
![Screenshot 2022-05-26 at 6 22 37 PM](https://user-images.githubusercontent.com/91254708/170490985-15566ed0-0152-403d-b11a-5b056115e6fb.png)

**Comment by subhancd** [comment]
working fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@sunilspr7 Supports are getting removed now .But I am facing below issue,
Scenario : 
User A supports camp 1, camp 2 and camp 3, Now click on Manage Support -Remove All and Click on cross icon of camp 3 and then Submit

Expected Result : 
Supports should get removed from camp 1 and camp 2 but choice number of camp 3 should be 1

Actual Result : 
Choice number for camp 3 is displaying as "3"
![image](https://user-images.githubusercontent.com/40416610/177316113-e3c1f3e3-cac8-465c-939f-6d9d77a1fcbc.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
