### ISSUE TITLE
Canonizer Main Page :  "Canonized list for"  Issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1347]
Issue 1  : "Canonized list for"  listing topics which are not present on Browse page 

Browse page screenshot : 

![image](https://user-images.githubusercontent.com/40416610/167846035-3b6dc459-6a24-4c83-9188-cc22c17c0721.png)

"Canonized list for"  Screenshot : 

![image](https://user-images.githubusercontent.com/40416610/167846146-09f1d06b-3876-4775-86b2-665f931f28e9.png)

Issue 2 : 
Getting blank pages when click on topics from "Canonized list for" which are not present on Browse page 

![image](https://user-images.githubusercontent.com/40416610/167846279-06382583-90f8-47cb-b846-3ff5cd4aaaf7.png)

Issue 3  : 
Steps : 
1. Create new topic (support getting added automatically)
2. Check newly created topic on Browse page and under "Canonized list for" drop down (Note : Topic is present)
3. Now Go to that topic and remove support from "Agreement" camp
4. Check same topic on Browse page and under "Canonized list for" drop down

Expected Result : 
Topic should present at both places

Actual Result :  Topic is present on Browse page but not under "Canonized list for" drop down

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested and verified on Production. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
