### ISSUE TITLE
"Canonizer Algorithm" drop down values are not displaying in alphabetically sorted order

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#135]
Drop down values should displayed in alphabetically sorted order.

![image](https://user-images.githubusercontent.com/40416610/42089653-dad96010-7bbb-11e8-9891-5ffb5d6ab189.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is as per priority and not an issue.
