### ISSUE TITLE
 Namespace General on Canonizer Main page is displaying topics from sandbox testing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1350]
Steps to reproduce : 
1. Go to https://canonizer.com/ or https://staging.canonizer.com/
2. Create New topic under General Namespace and move to sandbox testing 
3. Observe "Canonized list for" - General Namespace topics 

Actual Result : 
Namespace General on Canonizer Main page is displaying moved topics from sandbox testing

Note : There are some test topics created by testers under general namespace and I told them to move in sandbox testing . They are moved but still displaying under General Namespace
Please refer screenshots

![image](https://user-images.githubusercontent.com/40416610/167983769-5521f3ad-1495-4f69-8738-5283277679a9.png)

![image](https://user-images.githubusercontent.com/40416610/167983814-e5cd9f5b-c748-40ae-b2da-a22c07cbf37d.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested on live and I am still facing issue for one topic. Please refer https://canonizer.com/topic-history/389-Testing-Topic-1

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/170032767-2c3bd157-d982-47db-b27f-7a46635aa214.png)


![image](https://user-images.githubusercontent.com/40416610/170032791-577bb384-0aa1-4a0a-9c8c-cb258b1518d6.png)


Case : User Pooja created topic under "general" namespace and User RC moved to "sandbox testing" and went live after 24 hrs but still listed under "general" namespace on canonizer main page

**Comment by rupalichavan9860** [comment]
@ahmed130544 Checked for mentioned topic and it is working fine. I am  checking for one more topic - I will check after 24 hour and update accordingly

**Comment by subhancd** [comment]
@ahmed130544 this is not fixed. I've checked this with topic "test topic 20may". it is displaying in general namespace in the canonized list. in browse, it shows in the sandbox testing namespace.

**Comment by rupalichavan9860** [comment]
@ahmed130544 This is not fixed yet

**Comment by ahmed130544** [comment]
Yes, @rupalichavan9860 , still working on following ticket, there were a pull request regarding it, so Ashutosh, moved it to deployed on staging. Moving to "in progress" section.

**Comment by subhancd** [comment]
create a topic in /general/ namespace
remove support, the score becomes 0
search the topic in the canonized list the /general/ namespace, the topic doesn't show in the list

**Comment by rupalichavan9860** [comment]
@ahmed130544 I checked this with below scenarios : 
1. Topic in one namespace and moved to other - change submitted by same user(Working fine)
2. Topic in one namespace and moved to other -  change submitted by another user and agreed by direct supporter(Working fine)
3. Topic in one namespace and moved to other -  change submitted by another user and it should get move to new namespace after 24 hours ( I will check this after 24 hours)

**Comment by rupalichavan9860** [comment]
@ahmed130544 checked 3rd case and not working. I can see topic under earlier namespace. Please refer https://staging.canonizer.com/topic/728-Topic-1-JUN-2022/1-Agreement

**Comment by ahmed130544** [comment]
Ok @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@ahmed130544 Third case is still not working .Moved topic is listing under both namespaces
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/174270620-bdffe300-6617-4c08-adb0-265cf087ed21.png)


![image](https://user-images.githubusercontent.com/40416610/174270676-73887ccd-8192-4fc9-b580-7812603c7065.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Again I need to wait for 24 hours for 3rd case. I will check and close after 24 hours

**Comment by saniatg** [comment]
@ahmed130544 Not working for the 3rd case. After the record went live after 24 hours.
The live record is in "sandbox testing" namespace
But when check in the list it shows in 'General' list , not in 'Sandbox Testing' list.
![Screenshot 2022-06-21 at 5 54 45 PM](https://user-images.githubusercontent.com/91254708/174802393-e0e93085-4910-47c5-b6a5-c759bf935587.png)
![Screenshot 2022-06-21 at 5 54 28 PM](https://user-images.githubusercontent.com/91254708/174802432-d96141a9-d556-4e85-950c-7af44bd2d45a.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Working fine all cases on live also but need to wait  24 hours for below case : 
Topic in one namespace and moved to other - change submitted by another user and it should get move to new namespace after 24 hours ( I will check this after 24 hours)

SO will check tomorrow and then close

**Comment by rupalichavan9860** [comment]
Verified on production
