### ISSUE TITLE
 It should display under my topics of A or B?

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1354]
Steps :
1.user A created a topic 
2.user B edited the topic changed the topic namespace from  general to sandbox testing and committed the changes 
3.user A agreed the changes 
4.Click on browser , select only my topic check box[user A]
The topic created by user A is not shown under only my topic section and uncheck the box , the topic is displayed 
5.Click on browser , select only my topic check box[user B]
The topic was not created by user B but still it shows the topic when user selected only my topic check box.
@BrentAllsop

**Comment by rupalichavan9860** [comment]
As per discussed topic should get listed under My topics of User A

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
