### ISSUE TITLE
Page is crashing when removing delegate support in case page is not refreshed

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1357]
Steps:

1. Create topic and 2 camps by "User A" and support both camps
2. Login with "User B" in different browser and delegate support to "User A" in any camp
3. User A creates  new camp "camp 3" and supports it
4. Update camp 3 and change parent camp to "Camp 1" from "Agreement"
5. Now again change parent to "agreement" from "camp1"
6. Go to the browser where User B is logged in , do not refresh the page. 
7. Click on " Remove your support" 

Page crashes on click button' Remove your support"
![Screenshot 2022-05-16 at 4 17 17 PM](https://user-images.githubusercontent.com/91254708/168580898-06987fa7-6aa5-43c8-9273-3e6e8d9b7da9.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested on Production . It is working fine . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified on production
