### ISSUE TITLE
Old and objected camp name is displaying on "Default" filter on topic view page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1364]
Please refer topic : 
https://staging.canonizer.com/topic/543-Change-namespace-5/2-camp-4#statement

Please refer attached screenshots : 
![image](https://user-images.githubusercontent.com/40416610/168747492-b09af919-bbba-4c74-b195-a480a0aa4dc6.png)

![image](https://user-images.githubusercontent.com/40416610/168747620-fd9e697c-d238-451b-b716-18b459070a3f.png)

**Comment by rupalichavan9860** [comment]
Same for topic name : 
https://staging.canonizer.com/topic/81-Mind-Experts/1-Agreement?filter=0.000&_token=amyqaG5ekUheApzMXSUX2LTppBjZ3Bhvjdw99jfk&asof=default&topic_history=0

![image](https://user-images.githubusercontent.com/40416610/168754287-9a75c7a9-5e5b-4172-b86e-e8d385be377f.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested. Still facing same issue

![image](https://user-images.githubusercontent.com/40416610/169026211-c8784a5e-c856-48f2-8962-9f66a5c71cc7.png)

**Comment by saniatg** [comment]
Tested and is working fine. @rupalichavan9860 Can you confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
