### ISSUE TITLE
Create Thread , Post- subscribe email  content should be aligned properly 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1365]
1. Instead of displaying the title name below , it can be displayed next to the  thread title
2. Same for post . the post name can be displayed next to the post title
<img width="960" alt="Screenshot (510)" src="https://user-images.githubusercontent.com/99309948/168749475-036d2f13-c112-422b-aa1e-c457d45b4739.png">
3. Gap should be reduced
<img width="960" alt="Screenshot (511)" src="https://user-images.githubusercontent.com/99309948/168750043-53cb4c5e-c703-40a9-a2b3-6550658ac057.png">

**Comment by saniatg** [comment]
Also, remove an unnecessary dot below the post title.
![Screenshot 2022-05-23 at 4 20 23 PM](https://user-images.githubusercontent.com/91254708/169803150-1212d10d-0dd4-4ed8-b475-7da021367f8e.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 Thread title  and post should be normal text, as of now it is displaying as bold .Also getting layout issue. Please refer below screenshot 

![image](https://user-images.githubusercontent.com/40416610/173533649-321498a0-fa9a-4f1d-ae2e-502c838acf1a.png)



![image](https://user-images.githubusercontent.com/40416610/173533934-0e7660da-05d4-4d02-aab1-45b5b3845b83.png)

**Comment by sonalizibtek** [comment]
Tested and Verified, its working fine . @rupalichavan9860  Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
