### ISSUE TITLE
"nick names" should be a link showing the supports for that nick name on Canonizer Forum Details page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1367]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/168968921-fe271834-8013-4470-8577-f2f93455711b.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and working fine

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
