### ISSUE TITLE
Error messages should be proper on "Create Topic" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#137]
1.Error message for field "Topic Name" should be "Topic Name is required." instead of "The topic name field is required."
2."Additional Note" field is mandatory/required but error message is not displaying for required field.
It should display error message "Additional Note is required."
3.Enter Topic Name more than 30 characters,error message should be "Topic Name may not be greater than 30 characters." instead of "The topic name may not be greater than 30 characters."

**Comment by gautamv16** [comment]
@rupalichavan9860 retest it. Note : The will remain in the message sentence.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified.The is okay but I think label name in every error messages should be standard (It should be as it is like label name i.e Topic Name,Additional Note).Please check with Brent
