### ISSUE TITLE
Add name space to subject of e-mail for /sandbox/ and /sandbox testing/ name space proposals.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1370]
Currently e-mails that go out have [canonizer] prepended to the subject of the e-mail.

If the namespace of the topic is /sandbox/ or /sandbox testing/ add this like this:
[canon/sandbox testing/] or [canon/sandbox/]
So we can separate testing e-mail from real use e-mail with filters.

**Comment by saniatg** [comment]
@rupalichavan9860 tested on staging and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
