### ISSUE TITLE
Delegation check should be done first.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1377]
If you delegate your support to someone supporting a parent camp of some camps you already directly support, you get this message:
![image](https://user-images.githubusercontent.com/6559312/169371852-d9f18d86-f991-45d7-946d-8ffc41112eca.png)
Which is incorrect.  The delegation check should be done first, and the delegation warning should be given, not this incorrect warning.

**Comment by sunilspr7** [comment]
@BrentAllsop and @rupalichavan9860  this issue is already solved against the ticket id #1432

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check and confirm?

**Comment by sonalizibtek** [comment]
Tested on Production, its working fine @rupalichavan9860 Please confirm once

**Comment by sonalizibtek** [comment]
Tested in Production. It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
