### ISSUE TITLE
On clicking on view this version page crash appears 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1378]
steps to produce :
case 1:
1. Login with valid email and password (User A)
2. Create new topic and create 2 camps and support both camps - User A Login
3. Login with User B and support both camps
4. Login with User B and change parent camp of "camp 1" to "camp 2" from "Agreement"
5. Login with User A and object change proposed by User B
6. User A change parent of "camp 2" to "camp 1" - and commit ,  click on view this version 
Actual result : Page doesn't work
![Screenshot (545)](https://user-images.githubusercontent.com/99309948/169474448-b6ea6010-cc86-48a9-a565-180b61c0d8cf.png)

case 2:
1. Login with valid email and password (User A)
2. Create new topic and create 2 camps and support both camps - User A Login
3. Login with User B and support both camps
4. Login with User B and change parent camp of "camp 1" to "camp 2" from "Agreement"
5. Login with User A and object change proposed by User B
6. User A change parent of "camp 2" to "camp 1" - and don't click on commit ,  click on view this version 
Actual result : Page crash 
Expected : It should redirect to topic view page 
![Screenshot (546)](https://user-images.githubusercontent.com/99309948/169475199-fcf1be43-2c87-4e65-be35-39ad0aa43c04.png)

**Comment by rupalichavan9860** [comment]
This is not fixed yet

**Comment by rupalichavan9860** [comment]
This is working fine now as #1310 changes are reverted

**Comment by rupalichavan9860** [comment]
Verified
