### ISSUE TITLE
Error message is displaying after successful topic creation

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#138]
Steps to reproduce:
1.Go To https://staging.canonizer.com/
2.Login with valid email and password
3.Go to Create New Topic
4.Enter data in all mandatory fields
5.Click on Create Topic button
6.Click on back button of browser

Expected Result:
Topic should get created and user should redirect to Create New Topic page with it should clear fields
Actual Result:
Topic is getting created and user is redirecting to Create New Topic page but it page is not getting refreshed and  error is displaying "Error!Topic does not exist."

![image](https://user-images.githubusercontent.com/40416610/42103404-9778047c-7be6-11e8-8d08-78531923380d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested .Error message is not displaying now but text boxes should get cleared because if user again click on "Create Topic" button,it is creating another topic with same name.

**Comment by gautamv16** [comment]
@rupalichavan9860 why text boxes should be cleared ? and on back button previous data never removed as browser state will remane there. So its not an issue..

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.But while refreshing the same page text boxes are getting cleared so I thought it is an issue

**Comment by gautamv16** [comment]
Yes, thats why i said on browser back button previous history never cleared.
