### ISSUE TITLE
Camp filter is being applied on history pages

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1381]
User A is a direct supporter , and when user B proposes  change to any camp and do  not commit the changes and submit update on that change and commits the latest change after that  User A accepts the change and then user B applies as of date filter .
User A sees live record as old
![Screenshot 2022-05-23 at 3 27 28 PM](https://user-images.githubusercontent.com/91254708/169795846-ff6fcff0-432d-4e74-b76b-0450656ef139.png)

User B sees correct live record in history pages
![Screenshot 2022-05-23 at 3 27 47 PM](https://user-images.githubusercontent.com/91254708/169795867-bafd51c0-97ce-4dd3-bad9-0cc369055161.png)

Therefore, Camp filters must not be  applied on history pages.

[https://github.com/the-canonizer/canonizer.2.0/issues/1264]

**Comment by saniatg** [comment]
@rupalichavan9860 @ahmed130544 not able to reproduce this issue again. Closing for now.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Still facing issue on staging so reopening this

Please refer attached screenshot : 
Default Filter : 
![image](https://user-images.githubusercontent.com/40416610/172828457-df0f6b83-d855-4ab7-a923-2afb6e176af0.png)


Include Review Filter :  
![image](https://user-images.githubusercontent.com/40416610/172828367-65e5872d-14de-4d3e-890b-ddab742a42e3.png)

**Comment by sonalizibtek** [comment]
Tested and Verified , its working fine . @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. Its working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified on production
