### ISSUE TITLE
Message "There is no statement history available right now. It may also be possible that a statement has been added, but it is in a review state." is displaying even if objected statement is available

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1382]
Steps to reproduce : 
1. Create Camp "camp1" and support by User A and User B
2. Add camp statement By User A
3. Object By User B
4. Now observe User A and User B camp statement history page
Please refer attached screenshot : 
User A  login : 

![image](https://user-images.githubusercontent.com/40416610/169963488-8637d683-66c8-43f1-8484-8a382dc3ba0e.png)

User B Login : 

![image](https://user-images.githubusercontent.com/40416610/169963522-0de23223-4a2d-4dfa-a2f8-528dc29f3c90.png)

**Comment by rupalichavan9860** [comment]
![image](https://user-images.githubusercontent.com/40416610/169969968-2ad88228-f82e-4d2f-b126-198dbd4172c6.png)

**Comment by ahmed130544** [comment]
Issue exists for both topic (Agreement camp) and child camp.

**Comment by ahmed130544** [comment]
@rupalichavan9860  have a scenario,
User A login and creates a camp , and add support to it.
User B login and also support that camp.
User A added new statement, it will be in review, now User A object change request by himself. Rejected statement change is showing to User A which is fine, but not showing to User B.

AFAIK only review changes in grace period should not be visible to other direct supporters of the camp until grace period time gets completed, please confirm that do we need to handle that case.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Yes. We need to handle the case you mentioned

**Comment by saniatg** [comment]
@ahmed130544 not working for the case mentioned below:

When user is not logged in this is what is seen:
 The Statement  is still incorrect that the record is in review.
![Screenshot 2022-06-21 at 11 51 16 AM](https://user-images.githubusercontent.com/91254708/174730596-ef70eaa1-f3b8-47e3-833e-f85d71ac2cf1.png)

Now log the app, the record will show. Need to fix this case
![Screenshot 2022-06-21 at 11 51 26 AM](https://user-images.githubusercontent.com/91254708/174730697-7a22b2b3-6569-4b5f-8151-cd506296da32.png)

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@ahmed130544 last commented issue, is not fixed.

**Comment by ahmed130544** [comment]
> @ahmed130544 last commented issue, is not fixed.

@rupalichavan9860, updated logic (all statuses including rejected and in-review) for each case topic, camp and statement, please test all these cases.

**Comment by saniatg** [comment]
@rupalichavan9860 working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production .It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified on production
