### ISSUE TITLE
Default nick name is not getting created when user logged in using social logins 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1385]
When user logged in using social logins (which is not having email address) ,default nick name is not getting created

**Comment by sonalizibtek** [comment]
Tested and verified on staging. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Working social accounts fine on production except Facebook(created different ticket) so closing this issue
