### ISSUE TITLE
Don't send email when adding support to sub camp of supported camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1388]
Currently, if you add your support to a sub camp of a camp you already support, you generate two e-mails, one for removing your support to the parent camp, and one for adding your support to the sub camp.

Don't send the e-mail about removing your support from the parent, as you are still supporting the parent camp, just implicity instead of explicitly.  Only send the email about joining the sub camp.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I guess this is duplicate of issue #1149 . Can you please confirm?

**Comment by BrentAllsop** [comment]
Yes, this is a duplicate, so I will close this?
