### ISSUE TITLE
"Nick Name" drop down values on "Create New Topic" page are not displaying in alphabetically sorted order

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#139]
"Nick Name" drop down items/values should get listed in alphabetically sorted order.

![image](https://user-images.githubusercontent.com/40416610/42103878-2608d0f8-7be8-11e8-8b70-1d7fa34f42a4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
