### ISSUE TITLE
Delegated supporters are getting removed when changing parent 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1392]
Steps:

1. User A created a topic and created 2 camps: 'camp1' & 'camp2'. Support will be added to Agreement by default
2. Now create a subcamp under camp1
3. Now login with User B , delegate support to User A in agreement camp
4. Login with user C and delegate support to User B 
Support tree will look like
![Screenshot 2022-05-26 at 7 49 08 PM](https://user-images.githubusercontent.com/91254708/170506837-3875a9ec-c7a7-4c68-a0b9-bbdb5c2900e9.png)
6. Now Login as User A and camp parent of 'subcamp' from camp 1 to 'agreement'

Actual result:  Delegated supporters are not seen under the camp
![Screenshot 2022-05-26 at 7 49 08 PM](https://user-images.githubusercontent.com/91254708/170507075-a51846fc-4593-4a58-ab48-68975134c49c.png)

**Comment by subhancd** [comment]
working fine @rupalichavan9860 . kindly, verify

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 tested and working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
