### ISSUE TITLE
Page crash when removing support

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1393]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Create new topic (Support added to Agreement)
3. Open Account Settings->Supported camps in one tab
4. Open Topic Detail page in another tab
5. Remove support from Account Settings->Supported camps 
6. Remove support from Topic Detail page

Getting below page crash 
![image](https://user-images.githubusercontent.com/40416610/170546725-bc7bbbe4-418c-44f0-a4ef-0bb58bd3771e.png)

Expected Result : 
It should show message like Support removed already or any specific message

**Comment by subhancd** [comment]
fixed. @rupalichavan9860 kindly, verify.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
