### ISSUE TITLE
Direct support is getting removed , when changing parent camp in a specific case mention below.

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1398]
Steps:

1. User A will create a topic and 2 camps : "camp1 " & "camp2"
2. Support "camp1"
3. Now create a subcamp "subcamp"under camp 2 
4. Login with User B and directly support camp 1 ( Total support of camp 1 is 2)
![Screenshot 2022-05-27 at 2 09 35 PM](https://user-images.githubusercontent.com/91254708/170677693-f8038174-24aa-49f1-b776-08475f79e90e.png)
5. Login with User A and change parent of "subcamp" from camp2 to "camp1"
![Screenshot 2022-05-27 at 2 10 06 PM](https://user-images.githubusercontent.com/91254708/170677759-a2fd3dbb-9812-4881-a828-58b843bef012.png)

6. Observe score 
Actual result: Support of User B is not seen
Expected Result: Score count must be 2 not 1

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested on Production . Not working
1.Score is showing one 
2.User B support is removed . Please find the attached screenshot below
 . @rupalichavan9860 Please confirm once
![Screenshot (1017)](https://user-images.githubusercontent.com/99309948/179211234-2dfaf792-5442-4521-9db5-378fb5c467ff.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
@sunilspr7 This is still not working in below case : 
Steps:
1. User A creates a topic and 2 camps : "camp 1 " & "camp 2"
2. Support "camp 1"
3. Now create a subcamp "subcamp" under camp 2
4. Login with User B and directly support camp 1 ( Total support of camp 1 is 2)
5. Login with User A and change parent of "subcamp" from camp 2 to "camp 1"(score for camp 1 will be 2) - this is correct
6. Login with User C and support Agreement camp
7. Login with User A and create new camp "camp 3"
8. Login with User A and change parent of "camp 3" to "subcamp"

Expected Result : 
Score of "camp 1" should be 2 and supporters should be User A and User B- Working fine
Total Score of "Agreement" camp should be 3 and Supporter of Agreement camp should be  "User C"- User C's support is getting removed

**Comment by saniatg** [comment]
@rupalichavan9860 above mentioned case is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by mark-shamy** [comment]
Please update the status of this issue.

**Comment by rupalichavan9860** [comment]
Verified on production
