### ISSUE TITLE
Provide Entire canonized score on all supported camps option in the Canonizer block

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1399]
Add a check mark to the "[Canonizer Block](https://github.com/the-canonizer/canonizer.2.0/issues/1096)" with the label: "%100 of canonized score on all supported camps".

Whenever this is checked, add 100% of the supporters canonized score to all camps supported, instead of splitting this up and allocating ever decreasing portions of their canonized score to all the camps they support in this topic.

We should probably only do this in 3.0, unless we get most of the other 2.0 issues completed before this.

**Comment by sunnyjindal** [comment]
I have added this in Canonizer 3 Jira board. Closing the ticket here.
