### ISSUE TITLE
[Canonizer Forum] User must be able to update his/her own posts

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#14]
The user must update the post (owned by the user) to threads.

**Comment by akuks** [comment]
This feature will be added in the next release of Canonizer.

**Comment by rupalichavan9860** [comment]
@akuks I can't see this feature. Please check and update on this

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested. User is now able to update their own posts but when user updates post , I can see "RC replied 1 second ago (Oct 29, 2021, 10:30:51 AM)"
It should be  "RC updated 1 second ago (Oct 29, 2021, 10:30:51 AM)"

Before update : 
![image](https://user-images.githubusercontent.com/40416610/139378508-51890a7b-8080-4d42-abdc-e534f9f8e951.png)

After Update : 
![image](https://user-images.githubusercontent.com/40416610/139378562-503a1d2b-cb77-445b-8c04-d3aacf984216.png)

**Comment by rupalichavan9860** [comment]
Also user is getting "post submitted" email , It should be "post updated"

**Comment by rupalichavan9860** [comment]
@sunilspr7 Getting page crash when user click on Thread name link

![image](https://user-images.githubusercontent.com/40416610/139442028-52b38f71-d361-4f4a-a6bd-9f1dac2ee537.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Page crash issue is resolved and tested update functionality. 
Need one minor change in updated email. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/139644150-e3b33857-6ce7-46ee-88b0-05de46c6828c.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
