### ISSUE TITLE
On Live : Objected camp name is displaying on "Default" filter on topic view page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1408]
Please refer link : 
https://canonizer.com/topic/420-test-spaces-include-review/4-camp-1-objected#statement

**Comment by rupalichavan9860** [comment]
@ahmed130544 Still can see objected camp name on supports page 
![image](https://user-images.githubusercontent.com/40416610/172153747-8bbf1fbd-3720-4ef1-bbb6-d6298df748c0.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
