### ISSUE TITLE
Topic Name is missing when applying as of date filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1416]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/172120681-5555c83c-3e3c-4537-ac5f-ce6a79a42f62.png)

**Comment by ahmed130544** [comment]
Yes, @rupalichavan9860 
For now to test new changes regarding score calculation for "mind experts" and "one person one vote", we have commented out the code that pull the data from Canonizer service in Canonizer 2.0 code.
@karun0607gautam commented in team group.
Will revert this commented change, when testing will be completed.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
