### ISSUE TITLE
"In Review" camp name is displaying on supported camps and user supports page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1425]
Please refer attached screenshot : 
Default Filter : 
Topic View Page : 
![image](https://user-images.githubusercontent.com/40416610/172819085-4ccd09f3-8153-41b7-8606-eb5d00001a72.png)

Supported Camps Page :  
![image](https://user-images.githubusercontent.com/40416610/172819150-c013aa6e-b03c-4b5d-a548-eac90719b502.png)

Include Review Filter : 
Topic View Page : 
![image](https://user-images.githubusercontent.com/40416610/172819268-8d00b428-2a9b-4b19-b522-c11fb08f6651.png)

Supported Camps Page :  
![image](https://user-images.githubusercontent.com/40416610/172819361-ef1802a1-2b3f-4622-9413-7c0bb44dc9f0.png)

User supports page : 
![image](https://user-images.githubusercontent.com/40416610/172819915-a9469904-1df0-4b6d-a477-77d1904a2d9c.png)

Expected Result : 
Filter should not get applied on supported camps and user supports page(It should always show live names) 

Actual Result : 
"in review" camp name is displaying on supported camps and user supports page

**Comment by rupalichavan9860** [comment]
![image](https://user-images.githubusercontent.com/40416610/172827576-7f97d9f3-12af-4a44-a38b-50e8e49fcb56.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested . This is not fixed yet. Please refer attached screenshot : 
Live camp names : 
![image](https://user-images.githubusercontent.com/40416610/179446967-8b4979a9-7c09-4cf5-8394-5ffacd17a7e9.png)


Supported Camps : 
![image](https://user-images.githubusercontent.com/40416610/179446819-4a9759ed-1274-4901-8d5a-b816160f1594.png)


![image](https://user-images.githubusercontent.com/40416610/179446863-0e108866-ffd1-412e-907b-24c3bf8977cf.png)


![image](https://user-images.githubusercontent.com/40416610/179446926-fa1e0be8-b295-4e10-a440-43aa591011cd.png)

**Comment by sonalizibtek** [comment]
Tested and verified .It is working fine. @rupalichavan9860  please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
