### ISSUE TITLE
"In Review" camp name is displaying on Camp forum pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1426]
Please refer attached screenshot : 
Live camp name : 
![image](https://user-images.githubusercontent.com/40416610/172821565-8c0a5002-1639-4415-bab4-574c7b11f33c.png)

Camp Forum Screenshots : 
![image](https://user-images.githubusercontent.com/40416610/172821707-7f0da987-8c14-43c9-8e67-8c9438dc8d57.png)

![image](https://user-images.githubusercontent.com/40416610/172821780-76b89b8e-9e60-4115-91db-bd2671057e77.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on production
