### ISSUE TITLE
"In Review" camp name and topic name is displaying on Camp History, Add Camp Statement and Camp Statement History Bread crumbs 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1427]
Apply filter "Include Review" and check history pages bread crumbs  
Please refer attached screenshot : 

Live Names : 
![image](https://user-images.githubusercontent.com/40416610/172826817-61b252b4-1383-466e-a624-b4f94252b725.png)

After applying "Include Review" filter : 
Add Camp Statement : 
![image](https://user-images.githubusercontent.com/40416610/172826960-629cd75a-04f6-4b76-88b1-450c5a108abf.png)

Camp History : 
![image](https://user-images.githubusercontent.com/40416610/172827023-40317bc7-d842-4dc6-b87e-00c0164bbcf6.png)

Camp Statement History : 
![image](https://user-images.githubusercontent.com/40416610/172827140-552ad475-14cc-4cc1-9258-415277f6d7c4.png)

**Comment by ahmed130544** [comment]
Topic history page:
1. Topic history page: showing live topic name in breadcrumb, working fine.
2. Edit topic name, not showing live topic name in breadcrumb, not working fine.
3. Object topic name change request, not showing live topic name in breadcrumb, not working fine.
4. Manage/Edit this camp (when no camp is created, show topic details in this section): Not showing live topic name, not working fine.

Camp history page: 
1. Camp history page: not showing live topic name and live camp name in breadcrumb, not working fine.
2. In case of nested sub-camp, agreement camp has a sub-camp lets say "camp_1", and this sub-camp has a child sub-camp .
3. Add new sub camp to agreement camp or a sub-camp of agreement camp, showing live topic name and live camp name, working fine.
5. Edit camp name, showing live topic name but not showing live camp name, not working fine.
6. Object camp name change request, showing live topic name but not showing live camp name, not working fine.

Statement history page:
1. Statement history page: Not showing live topic name. but showing live camp name, not working fine.
2. Add camp statement: Not showing live topic name. but showing live camp name, not working fine.
3. Edit camp statement: Not showing live topic name. but showing live camp name, not working fine.
4. Object camp statement change request: Not showing live topic name. but showing live camp name, not working fine.

Directly join or manage support page:
1. Directly join and support: Not showing live topic name. but showing live camp name, not working fine.
2. Manage support: Not showing live topic name. but showing live camp name, not working fine.

Topic details page: working fine in all cases of "As Of".
1. Default
2. Include review
3. View this version (as of date).

Supported camps page: Working fine.
Supported camps page path: Account settings -> supported camps

@rupalichavan9860 checked all pages, please let me know if we have any other page where we need to fix it.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Working fine on all pages except supported camps/user supports/manage support page, but we have different ticket for that so closing this issue

**Comment by rupalichavan9860** [comment]
Verified on live
