### ISSUE TITLE
Duplicate thread is getting created  

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1428]
Steps to reproduce : 
1. Create thread "thread 1"
2. Create another thread "thread                          1"(same name with more than 2 spaces) and click on Submit

Expected Result : 
It should display error message 

Actual Result : 
 Duplicate thread is getting created  .Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/172997964-d1dd92dc-58d8-4b4b-a333-f65d276fb53b.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Working fine for new thread but existing thread is getting updated with duplicate name . Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/180398471-d2d3e380-0d16-4e84-b808-9c7f8a3279b3.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. It is working fine . @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
@sunilspr7 I found some more issues 
1. When user tries to update thread without any changes , it is showing error message "Thread title must be unique"
2. I can see 2 different error messages "Error! Thread title must be unique!" and " Thread title must be unique" , error messages must be uniform

![image](https://user-images.githubusercontent.com/40416610/181416239-915b84a5-94d2-47ed-969b-d3519452826e.png)

![image](https://user-images.githubusercontent.com/40416610/181416294-05027d15-c4f3-4082-80a0-c9bb03e8bc8b.png)

**Comment by saniatg** [comment]
Tested and is working fine @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
