### ISSUE TITLE
Language is not getting updated on "Manage Profile info" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#143]
Select any language from "Language" drop down other than "English".
Expected Result:
Profile should be updated successfully with selected language.
Actual Result:
Profile is always getting updated with language as "English" instead of selected language.

**Comment by gautamv16** [comment]
@rupalichavan9860 restest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested .Working now
