### ISSUE TITLE
Support remains added for both child and parent camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1430]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password 
3. Create New topic 
4. Create 4 camps and support by User A
5. Update camp 2 and change parent camp to "camp 1" (By User B)
6. Commit changes and observe after 24 hours

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/173281610-18c5ccc2-6ff2-41ab-b02b-7aa5631d81d2.png)

![image](https://user-images.githubusercontent.com/40416610/173281670-f6b3df6f-8878-4c2c-b2f2-3d4c07464bc1.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Same issue exists for simple case below : 
case :  User A created camp 1 and camp 2 and supports both and then same user change parent of camp 2 to camp 1

Actual Result :  Supports remains added for both child and parent camp

![image](https://user-images.githubusercontent.com/40416610/173379830-dee0aafe-8a3d-4684-aea5-3eb81ba0b3c5.png)

![image](https://user-images.githubusercontent.com/40416610/173379933-21611054-0dad-4df7-81c7-3f15c0fd6a78.png)

**Comment by BrentAllsop** [comment]
This is as designed. Adding agenda item to discuss this for Thursday's engineering meeting.

**Comment by BrentAllsop** [comment]
I take my last comment back.  Removing the parent support is a good solution.

**Comment by BrentAllsop** [comment]
Rupali verified this is working, so closing this.

**Comment by rupalichavan9860** [comment]
Verified on production
