### ISSUE TITLE
Incorrect warning message is displaying in some cases

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1432]
Case 1 : When user is delegating support to more than one child camps , and trying to support Agreement camp directly

Expected Result : Warning should be "Warning! You have delegated your support to user “username” under this topic. If you continue your delegated support will be removed."

Actual Result : Warning is displaying as "Warning! "Agreement" is a parent camp to this list of child camps. If you commit support to "Agreement", the support of the camps in this list will be removed. "

Case 2 : When user is delegating support to Agreement camp  , and trying to support child camp directly

Expected Result : Warning should be "Warning! You have delegated your support to user “username” under this topic. If you continue your delegated support will be removed"

Actual Result : Warning is displaying as "Warning! "camp 1" is a child camp to "Agreement", so if you commit support to "camp 1", the support of the parent camp "Agreement" will be removed. "

Case 3 : When user is delegating support to parent camp  , and trying to support child camp directly

Expected Result : Warning should be "Warning! You have delegated your support to user “username” under this topic. If you continue your delegated support will be removed"

Actual Result : Warning is displaying as "Warning! "child camp" is a child camp to "parent camp", so if you commit support to "child camp", the support of the parent camp "parent camp" will be removed.  "

**Comment by sonalizibtek** [comment]
Tested and Verified. It is working fine . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested and Verified. @rupalichavan9860 Please confirm once

**Comment by sonalizibtek** [comment]
Tested on Production. It is working, @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
