### ISSUE TITLE
Duplicate topics are showing on main page

### ISSUE THREAD

**Issue by ahmed130544** [the-canonizer/canonizer.2.0#1438]
On main page, some topics was showing duplicate, for example same topic is showing on both page 1 and page 2, which is wrong.
Issue was reported by Canonizer 3.0 front-end team, found issue on canonizer 2.0 as well, now fixed it in both environments.

For canonizer 3.0, following ticket is made.
https://canonizer.atlassian.net/browse/CAN-571

**Comment by sonalizibtek** [comment]
Tested and Verified . @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine. @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
