### ISSUE TITLE
Remove/Cross icon on records of  "My Supports" page is not displaying any tool tip text on mouse over 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#144]
Remove/cross icon should display tool tip on mouse over like "Remove Support" or "Delete Support"

**Comment by gautamv16** [comment]
@rupalichavan9860 retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified

**Comment by rupalichavan9860** [comment]
@gautamv16 "Remove Support" should ask for confirmation message for deletion.Now it is directly deleting

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
