### ISSUE TITLE
Parent camp drop down value is not inline with other fields on the pages (Create New Camp and Camp Update pages)

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1449]
Please refer attached screenshot : 

Create New Camp : 
![image](https://user-images.githubusercontent.com/40416610/174989505-15a039c8-c99a-4ffe-92f9-2eaae8d97cb0.png)

Camp Update : 
![image](https://user-images.githubusercontent.com/40416610/174989305-e618dfce-2c88-4edc-89a0-60e87ea147de.png)

**Comment by rupalichavan9860** [comment]
Also "Nick Name" should be first field on the camp update page

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
