### ISSUE TITLE
Camps are displaying twice on manage support and choice number is getting changed 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1456]
Please refer attached screenshot : 
I click on manage support- User is supporting only one camp
![image](https://user-images.githubusercontent.com/40416610/175236411-89991950-50ff-423e-86aa-60be553c733e.png)

When I submit support again on above page then choice number is getting changed to -2
![image](https://user-images.githubusercontent.com/40416610/175236302-e3b18ffa-3fcc-4fb1-ac29-b4dc82ae238c.png)

**Comment by sonalizibtek** [comment]
After creating a topic and then create a new camp , the tree is displaying like this. Please refer the attached screen shot
![Screenshot (863)](https://user-images.githubusercontent.com/99309948/175236896-71fb764f-a3a1-4e3a-a47b-afeadfa2c6a5.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
