### ISSUE TITLE
Objected record is not being seen for 'Topic History' page when a user is  not logged in

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1459]
User A who is direct supporter has objected his own change for Topic and can see the objected record but not able to see when not logged in

**Comment by ahmed130544** [comment]
Found another issue, follow steps:
1. Create new topic by user A, supported will be added automatically.
2. Add support by user B.
3. Update topic name by User A, it will go in review.
4. Reject change request by User A, itself.
Now rejected change is showing to User A, which is fine, but not showing to User B. (Both users are logged in)
@saniatg @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. @rupalichavan9860 kindly verify.

**Comment by rupalichavan9860** [comment]
Verified
