### ISSUE TITLE
Link name and error messages are not displaying properly on "System Update" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#146]
1.Link name below Nick Name drop down should be "Add New Nick Name" instead of "Add new nickname"
2.Error message for "Camp Name" should be "Camp Name is required." instead of "The camp name field is required."
3.Error message for "Additional Note" should be "Additional Note is required." instead of "The note field is required."
4.Enter more than 30 characters in "Camp Name" text box,error message should be "Camp Name may not be greater than 30 characters." instead of "The camp name may not be greater than 30 characters."

**Comment by gautamv16** [comment]
@rupalichavan9860 retest
