### ISSUE TITLE
Incorrect mail content when delegated user directly supporting camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1461]
Steps to reproduce : 
1. Create new topic By User A and create 5 camps 
2. Support all 5 camps By User A
3. Login with User B and delegate support to User A in any camp
4. Try to support any camp directly

Actual Result : 
User A and User B receives 5 emails each(for all camps) - removed support from `<camp name>`
and subject of email is - `<nickname>` has removed their support from `<topic name>/<camp name>` which is incorrect

Expected Result : 
User should receive below email : 
 User A : 
`<nick name>` has just removed their delegated support from `<nick name>`in this topic:`<topic name>`
User B : 
You `<nick name>` have just removed your delegated support from`<nick name>`in this topic:`<topic name>`

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Working fine on production @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified
