### ISSUE TITLE
Wrong parent camp name is showing in case of nested child camp

### ISSUE THREAD

**Issue by ahmed130544** [the-canonizer/canonizer.2.0#1463]
Steps:
1. Create a topic.
2. Create a camp, let's say "camp 1".
3. Create a sub-camp of "camp 1", lets say "camp 1 child"
Now on edit this camp, showing wrong parent camp (Agreement) instead it should show "camp 1".

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested on Production. It is working fine.@rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
verified
