### ISSUE TITLE
Default algorithm is not selected on Main page and topic view 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1467]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Account Settings ->Profile Info
4. Select any algorithm from "Choose default algorithm preferences " other than "One Person One Vote"
5. Log out and again login 

Expected Result : 
When user logged in , by default selected algorithm should be-  selected algorithm from account settings 

Actual Result : 
Default Algorithm is selected as "One Person One Vote" on canonizer main page and on topic view

**Comment by sunilspr7** [comment]
sorry wrong ticket mentioned

**Comment by rupalichavan9860** [comment]
@kshitij1326 This is not working in below case : 
If user is logged out then default algorithm selected is "One person one vote"  then if user copied any topic URL and then log in -  User can see algorithm selected is "one person one vote" instead of selected algorithm from default algorithm preferences

**Comment by sonalizibtek** [comment]
Tested and Verified, its working fine . @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
