### ISSUE TITLE
"In review" topic name is displaying on Camp forum pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1468]
Apply "include review" filter on topic view page/select View this version(in review record)  and click on "Camp Forum" and observe bread crumb topic name camp forum -post page 

Please refer attached screenshot : 

Live topic Name : 
![image](https://user-images.githubusercontent.com/40416610/176131045-d5b3cce5-dbcf-46b6-9113-e7255be02c15.png)

Issue : 

![image](https://user-images.githubusercontent.com/40416610/176130918-70eac5c5-ba22-411f-91b5-f6b11e079c49.png)

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
