### ISSUE TITLE
Camp update success message should be uniform.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#147]
Success message should be "Success! Camp update submitted successfully. It's live now." instead of "Success! Camp update submitted Successfully. It's live now."

![image](https://user-images.githubusercontent.com/40416610/42111933-b4cb31c6-7c03-11e8-8abb-8f3a57c45038.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 restest.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified
