### ISSUE TITLE
Old Topic name is displaying under "Canonizer Sorted Camp Tree" on default filter  

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1477]
Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/177323749-0f18ce3a-e4de-43e1-8172-249c3bd5c85a.png)

![image](https://user-images.githubusercontent.com/40416610/177323656-0fa84ea7-2859-4bf6-9810-dc376f024ea1.png)

**Comment by rupalichavan9860** [comment]
Same on Browse page  and Canonizer Main Page : 
![image](https://user-images.githubusercontent.com/40416610/180261871-23ba7dc0-cb22-41e6-9323-a32889449318.png)


![image](https://user-images.githubusercontent.com/40416610/180262192-997aadb9-239d-42a1-9210-bcb5c05e4845.png)

**Comment by ahmed130544** [comment]
@rupalichavan9860 

Please check following pages list where we need to change logic, please have a look and let me know if some other page need to be checked.

1. Topic history
2. Manage topic
3. Camp history
4. Manage camp
5. Statement history
6. Manage statement 
7. Browse page
8. Main page
9. Topic details page.
10. Topic support page.
11. Logged in user supported camps page
12. Supporter supported camps page. 
13. Camp forum details, create thread.
14. Create post

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on live
