### ISSUE TITLE
bad limit on birthday year in profile info page

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1479]
The birthday field in the profile info page is too limited.
It should go back to 1900.

Don't close this issue till we are sure it is fixed, or at least not an issue in 3.0.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check on staging and confirm if fine for you

**Comment by rupalichavan9860** [comment]
Verified on production
