### ISSUE TITLE
Required/mandatory fields should be marked with asterisk mark (*) against the field and "*" should be in red colour on "Submit Statement" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#148]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Go to Browse(From left panel)
4.Select any topic and click on "Add Camp Statement"

**Comment by gautamv16** [comment]
@rupalichavan9860 its done

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified
