### ISSUE TITLE
Error messages on Edit news should not be clickable

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1483]
Error messages on edit news page are clickable

Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/178922349-8a108f73-14a7-4b99-b171-3fc3423cd431.png)

Expected Result :  Error messages on Edit news should not be clickable

**Comment by sonalizibtek** [comment]
Tested and Verified. It is working fine @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
