### ISSUE TITLE
On Live : Count of topics on browse and count of topics on Canonizer Main page is mismatching

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1485]
Select General namespace on browse page and count number of topics and for same namespace check on canonizer main page 

Expected Result : 
Count should match

Actual Result :  
Count of topics on browse and count of topics on Canonizer Main page is mismatching

**Comment by sonalizibtek** [comment]
@ahmed130544 , this issue is not fixed.
Count of topics in main page is - 45 [general namespace]
Count of topics in browse is - 247 [ general namespace ]

**Comment by sonalizibtek** [comment]
@ahmed130544 . this issue is not fixed.
case1 :Canonizer main page for sandbox testing namespace -  239
Browse for sandbox testing  - 237 

case 2 : Canonizer main page for general namespace -  269
Browse for general - 265

**Comment by ahmed130544** [comment]
Ok @sonalizibtek will work on it.

**Comment by rupalichavan9860** [comment]
@ahmed130544 Facing this issue for "One Person One Vote" and "Mind Experts" algorithms
Working fine for other algorithms

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
