### ISSUE TITLE
When you copy paste the url of browse page after checking the my created topic check box in new tab , and when user is not logged In ,  the complete topic list should be displayed

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1487]
Steps to Produce:
1.Login and navigate to Browse page.
2.Select any namespace from the dropdown. e.g user selects 2nd namespace as 'corporations' and check the box' My topics created' is URL https://staging.canonizer.com/browse?namespace=2&my=2 which is correct
3.Now copy the URL and log out
4.Paste the URL in a new BROWSER , 
the list will be seen Incorrect
5.Click on Login link and log in the application
Actual Result : The list is showing incorrect , 
Expected : All the topics under that namespace should be displayed 
![Screenshot (1008)](https://user-images.githubusercontent.com/99309948/179219089-79b2cacb-7211-4455-bc8c-09a1e1740ed5.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 This is not working when user is not logged in 

![image](https://user-images.githubusercontent.com/40416610/189387216-74b03bf4-43bb-4afc-8c56-641139530646.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
