### ISSUE TITLE
Not able to login using Face book  in both live and staging

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1488]
![Screenshot (1021)](https://user-images.githubusercontent.com/99309948/179264641-bf50b356-8a4d-4c01-a50b-e92fa54a62cc.png)

**Comment by ashish76** [comment]
@gautamv16 @akuks: Based on the error prompt on the screen it seems that the Facebook app is still in test mode. Could you please make it live.

**Comment by gautamv16** [comment]
@ashish76 new app credentials are provided so lets test and close this.
