### ISSUE TITLE
Link name and error messages are not displaying properly on "Submit Statement" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#149]
1.Link name below Nick Name drop down should be "Add New Nick Name" instead of "Add new nickname"
2.Error message for "Statement Value" should be "Statement Value is required." instead of "The statement field is required."
3.Error message for "Note" should be "Note is required." instead of "The note field is required."

**Comment by gautamv16** [comment]
@rupalichavan9860  #1 is done, all other is ok no need to change.
