### ISSUE TITLE
New whitelist id canonizer algorithm system.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1494]
We need to have the ability to create named canonizer algorithms, where we make a list of nick_name_ids of the only ids that get how much vote.  For example, we want to have a "sandy city council" canonizer algorithm people can select to find out how the 7 people on the current sandy city council voted on topics like [this one](https://canonizer.com/topic/532-Sandy-City-Building-Needs/1-Agreement).

In other words, maybe on an admin page, we will have the ability to create new named algorithms, with the following data specifying how much vote each nick name id gets:

Algorithm Name: "Sandy City Council"
Brent Allsop (1): 1
Jim Bennett (346): 1

Temporarily add the above two nick name id's, then once we get the true city council members below, signed up, we will replace these two with the correct ones below.

Ryan Mecham:1
Alison Stround:1
Zach Robinson:1
Scott Earl:1
Marci Houseman:1
Brook D'Sousa:1
Cyndi Sharkey:1

For the sandy city council algorithm, each council member will only have one vote.
But we want to have the ability to offer certain people 2, 3, or more votes.  Like maybe the Mayer will get 5 votes or something.

**Comment by rupalichavan9860** [comment]
Tested and verified . I have checked for Algorithm Name: "Sandy City Council" with below users 
Brent Allsop (1): 1
Jim Bennett (346): 1

and working fine for me
@BrentAllsop Can you please test and close if fine for you

**Comment by rupalichavan9860** [comment]
Verified on production
