### ISSUE TITLE
Page crash on agreeing the other user changes 

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1495]
steps to Produce :
case :

1. User A will create a topic and 2 camps : "camp1 " & "camp2"
2. Support "camp1"
3. Now create a subcamp "subcamp"under camp 2
4. Login with User B and directly support camp 1 ( Total support of camp 1 is 2)
5. Login with User A and change parent of "subcamp" from camp2 to "camp1"
6. and again change the parent of subcamp from camp1 to camp2  and commit the changes
7. Login with User B click on subcamp and click on manage /edit this camp 
8. click on I agree check box 
Actual Result : The page crash 
![Screenshot (1070)](https://user-images.githubusercontent.com/99309948/180146951-c66ff409-b2c9-4309-8c47-ba2811fb39bc.png)

**Comment by sonalizibtek** [comment]
Tested and Verified. It is working fine @rupalichavan9860 Please confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
