### ISSUE TITLE
Statement update success message should be uniform.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#150]
Success message should be "Success! Statement update submitted successfully**. It's live now." instead of "Success! Statement update submitted Successfully. It's live now."
![image](https://user-images.githubusercontent.com/40416610/42112718-66ad01e2-7c06-11e8-81d1-4999c1118502.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  changed message to as per our actual requirement.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified
