### ISSUE TITLE
Support is being removed when a delegated user is trying to support the camp directly

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1500]
Steps:

1. User A creates topic and support is automatically added
2. User B delegates support to User A in agreement camp
3. Now User B tries to support agreement camp directly . Warning "Warning! You have already delegated your support for this camp to user User A. If you continue your delegated support will be removed. " which is correct
4. Click on submit

Actual Result: User B support is removed
Expected Result: User B now should be direct supporter

**Comment by saniatg** [comment]
@sunilspr7 This issue is not fixed

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine now.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
