### ISSUE TITLE
Getting page crash when click  on "delegate page" on an page which is not refreshed

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1501]
Precondition: User A and User B must be logged in two different browsers

Steps:

1. User A Create a topic , create a camp(Camp1) and a sub-camp (sub camp1)
2. Support sub camp1
3. Login with B in different browser and directly support sub camp1
4. Now navigate to User A browser and  create a new camp(camp2) and a sub camp(sub camp 2)
5. Click on sub camp 1, support will be seen 2 and in support tree 2 direct supporters are seen. Leave that page 
6. Now navigate to User B in sub camp1 delegate the support to user A , and then click on button Manage/edit camp
7. Change parent from (camp1) to sub camp2 
8. Commit changes and click on view this version
9. Now navigate to User A browser page  which is not refreshed and still 2 direct supporters are seen ,click on delegate button warning is seen. Click on Submit button

 Page crashed on submit button
![Screenshot 2022-07-25 at 12 25 55 PM](https://user-images.githubusercontent.com/91254708/180717466-1f8aa461-e68b-4cab-aea8-8183f47e0c76.png)

**Comment by subhancd** [comment]
not working. @rupalichavan9860 kindly, verify this.

**Comment by saniatg** [comment]
@sunilspr7 Not working
On 9th step when click  on delegate button warning is seen. Click on Submit button.
On click submit button , page is just loading nothing is happening

**Comment by rupalichavan9860** [comment]
@sunilspr7 After 9th step User A and User B became delegated supporter of each other
![image](https://user-images.githubusercontent.com/40416610/181775739-fc54dc67-90d9-4b0f-bb15-de5bb4784d18.png)

![image](https://user-images.githubusercontent.com/40416610/181775753-c31f8f62-99f9-4b50-a93a-bf5ceff3e0b3.png)

And topic score is displaying as 0

![image](https://user-images.githubusercontent.com/40416610/181775871-eef6bee3-bffc-4eba-84ec-5a9e75366bc0.png)

**Comment by ahmed130544** [comment]
Please provide content of the message, currently we are showing following message
**Error! You already have delegate support, you cannot delegate your support to this user**

Another scenario:
1. User A created a topic (support will be added automatically). 
2. User B (logged in from different browser) directly support topic.
3. Now move to User A browser and refresh topic details page, now it will be showing User B in topic support tree with delegate support button..
4. Shift to User B browser, delegate support to User A.
5. Shift to User A browser, now when User A tries to delegate his support to User B, page was getting crashed (User A must not refresh his page only then delegate support button will be shown against user B nickname in support tree).

**Fixed issue on staging, just need to confirm the message content.**

@BrentAllsop @sunnyjindal

**Comment by saniatg** [comment]
@rupalichavan9860 and @ahmed130544 The crash is fixed now  and is working fine.
Warning "Error! You already have delegate support, you cannot delegate your support to this user" is showing.

This is grammatically incorrect

It should be  something like"  "Error! [user_id name] is already delegating support to you , you cannot delegate your support to this user"

**Comment by ahmed130544** [comment]
@saniatg @rupalichavan9860 
Updated content message, raised pull request so move it back to review in progress from deployed on staging, we can test once the reviewer will merge pull request.

**Comment by saniatg** [comment]
Working fine now with the error message. @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Verified on production and is working fine

**Comment by rupalichavan9860** [comment]
Verified
