### ISSUE TITLE
Getting crash while adding support and support is getting added to every camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1502]
Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/180718048-0adff083-e593-4a47-8a1c-1aeb31be70c5.png)

Support getting added to parent and child with same choice number 

![image](https://user-images.githubusercontent.com/40416610/180718451-fba5eb6d-ae51-4958-ada2-b9f8c715df15.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
