### ISSUE TITLE
Include Review is Not working on Staging 2.0

### ISSUE THREAD

**Issue by sonalizibtek** [the-canonizer/canonizer.2.0#1508]
![Screenshot (1126)](https://user-images.githubusercontent.com/99309948/181426336-af5314f5-30ee-4446-bddd-bfd0e5b2aeb1.png)

**Comment by subhancd** [comment]
working fine. @rupalichavan9860 kindly verify

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly,verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
