### ISSUE TITLE
User's support should not removed from parent camp in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1509]
Steps to reproduce : 
1. "camp 1" and "camp 2" are sibling camps 
2. User A supports  "camp 1" and User B supports "camp 2"
3. Now Login with User B and change parent of "camp 2" to "camp 1" from Agreement

Expected Result : 
User A should be supporter of "camp 1" and User B should be supporter of "camp 2"

Actual Result : 
Support of User A is removed from "camp 1" and User A is now supporter of "camp 2"

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please confirm

**Comment by BrentAllsop** [comment]
Yes, this is an issue.
The only support records that should be removed are stacked (individual supports parent of a child) parent records, leaving only the child support record in the stack.
There are none of those in this case.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine on production

**Comment by rupalichavan9860** [comment]
Verified
