### ISSUE TITLE
"Collapse this branch" and "Expand this branch"  arrow are not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#151]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Click on "Algorithm Information" link on left side bar
4.Do following scenarios:
  1.Mouse over on first arrow (Canonizer Algorithms)
   Clicking on arrow is working fine but tooltip should display "Collapse this branch" instead of 
   "Collapse",because "Collapse" tool tip is displaying for first time only
  2.Mouse over on arrow of any algorithms under Canonizer Algorithms
                    1.Clicking on arrow is not working and tool tip should display "Collapse this branch" instead 
                    of "Collapse",because "Collapse" tool tip is displaying for first time only
                    2.We need to first click on algorithm name then only collapse and expand functionality is 
                      working by clicking on "Collapse this branch" and "Expand this branch"

**Comment by gautamv16** [comment]
@rupalichavan9860  Not any bug at all. Its working properly as per requirement. If there is no child it will not show anything, test it with different topics who have child too, dont test only one case for this, test different cases and check collaps functionality.

**Comment by BrentAllsop** [comment]
It looks like there is one case where this remains an issue.
This is on the main http://canonizer.com page.
If you expand any of the 10 topics on the main page, by clicking on the arrows, the sub structure arrows start out in the wrong direction.

**Comment by sunilspr7** [comment]
@rupalichavan9860  and @gautamv16   
I found this new issue while reviewing ticket id #151 
Here is option to expand but when click on it it doesn't show any subcamps. For reference I am attaching screenshot.


![Ticket151](https://user-images.githubusercontent.com/6298462/137306549-eed7ff58-d7ae-4cda-ba7c-a212505fe813.png)

**Comment by sunilspr7** [comment]
![Ticket151 - 1](https://user-images.githubusercontent.com/6298462/137306729-b6002a16-e87e-4ab8-97d0-495114e5ae71.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified. But if topic doesn't have any camps then it is looking like see below

![image](https://user-images.githubusercontent.com/40416610/139376873-c6b0b7c5-a2d3-42d0-883e-f26235c0f7f7.png)

I think this topics also should have blue color rounded box without arrows
@BrentAllsop Can you please confirm on this

**Comment by rupalichavan9860** [comment]
@sunilspr7 As arrows are working fine so closing this issue and creating new issue for above

**Comment by rupalichavan9860** [comment]
Verified on production
