### ISSUE TITLE
Namespace resets on changing the as of to "include review" from 'default'

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1510]
**Steps to reproduce**

1. navigate to https://staging.canonizer.com/
2. navigate to browse and select any namespace other than 'all'
3. change as of filter to 'include review'
**Actual Result**
namespace field resets 
**Expected result**
namespace field shouldn't reset

**Comment by saniatg** [comment]
@kshitij1326 this issue is not fixed

**Comment by kshitij1326** [comment]
@saniatg could you please retest it as it was not deployed earlier

**Comment by saniatg** [comment]
Yes working fine now. @rupalichavan9860 can you confirm

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
