### ISSUE TITLE
"Include Review" filter is not working on Browse page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1512]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Apply "include review" filter on home page or any topic detail page
4. Click on Browse page (Include review filter is persist on Browse page)
5. Observe topic names

Expected Result : 
It should show in review topic names if any

Actual Result : 
It is displaying live topic names and to see in review topic names again we need to change filter to default and then include review

**Comment by saniatg** [comment]
@ahmed130544 When applied filter include review , changes must only be seen after committing not before that. Currently when I apply filter include review, and navigate to browse, if changes are not committed that changes are also seen which is incorrect.

**Comment by saniatg** [comment]
@rupalichavan9860 Verified and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
