### ISSUE TITLE
Not able to propose a change for the agreement camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1514]
1. Create a topic
2. Click on manage/edit this camp button at the bottom
3. Propose a change , click on button 'submit camp update based on this'
4. Add changes 
5. Click on submit

Actual result : Gives error "Camp name is taken" which is incorrect 
![Screenshot 2022-08-02 at 10 05 41 AM](https://user-images.githubusercontent.com/91254708/182292596-4e86e852-e911-4a53-96c3-7cbb7a93cfa6.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine now.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on production.

**Comment by rupalichavan9860** [comment]
Verified
