### ISSUE TITLE
Support is getting removed when changing parent 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1516]
Steps to reproduce : 
1. Login with User A and create topic
2. Create 2 camps "camp 1" and "camp 2" and support both camps
3. Login with User B and support only "camp 1"
4. Login with User A and change parent of "camp 2" to "camp 1"

Expected Result : 
User A should be supporter of "camp 2"  and User B should be supporter of "camp 1"  only

Actual Result : 
User B's support is getting removed

**Comment by saniatg** [comment]
@rupalichavan9860 mentioned issue is working fine now. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
verified on production
