### ISSUE TITLE
nick name is getting created with 200 chars and under nick name tab limit is 50

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/canonizer.2.0#1517]
**Steps to reproduce**
1. create an account with 100 first name characters and 100 last name characters
2. the default nick name is created with 200 characters
**Actual Result**
[https://gyazo.com/dc94b68584c2b50704b88d1dd60980b7](image)
**Expected Result**
the nick name should not have more than 50 characters

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860
