### ISSUE TITLE
Drop down "Browse Topic" on Browse page and "Canonized list for" on Canonizer Main Page are not having "Other" item/values in drop down list.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#152]
"Browse Topic" and "Canonized list for" drop downs should have "Other" in drop down item lists because at Create Topic page user is able to select "Other" Namespace from drop down and can put his/her topic under "Other"Namespace.

**Comment by gautamv16** [comment]
@rupalichavan9860 this is next release feature. Where admin approved Namespaces will show. So its not an bug.

**Comment by gautamv16** [comment]
@rupalichavan9860 this feature is redeveloped as per requirement. There will be no "Other" option there but the namespace added in other will come in the drop down. So dont look for "Other" word in drop down check what is added in other option should come in the drop down list.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
