### ISSUE TITLE
Created topic is not being seen in the respective namespace in the 'Canonizer Main Page': Canonized list for 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1520]
Steps

1. Create a Topic in any namespace e.g. general
2. Navigate to Canonizer Main Page
3. In the tree below Canonized list for search for the topic in the namespace created

Actual Result: The topic is not seen under Canonized list for
Expected : Topic must be seen under the respective namespaces

**Comment by rupalichavan9860** [comment]
@ahmed130544 Facing this issue for "One Person One Vote" and "Mind Experts" algorithms
Working fine for other algorithms

**Comment by ahmed130544** [comment]
@rupalichavan9860 unable to reproduce issue
Working fine for all algorithms on both environments staging and live.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
