### ISSUE TITLE
Newly created camp is not listing and Expand the branch icon is not seen in Canonizer Sorted Camp Tree for the first time 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1521]
Steps to reproduce :

1. Hard reload and clear cache for https://staging.canonizer.com/ 
2. Login with valid email and password
3. Create a new topic
4. Create a new camp

Actual result: Newly created camp is not listing under tree and Expand the branch icon is not seen next to topic
Expected result: Newly created camp should show under tree and Expand the branch icon must be seen

Note : After reload it is working fine

![Screenshot 2022-08-03 at 10 34 13 AM 1](https://user-images.githubusercontent.com/91254708/182529877-3a3cb334-1b5a-49f3-95d5-d51e4600f8f6.png)

**Comment by saniatg** [comment]
@rupalichavan9860 not able to reproduce now. Can you also check and confirm

**Comment by rupalichavan9860** [comment]
Yes . working fine now

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
not working on live. @rupalichavan9860

**Comment by saniatg** [comment]
Working fine now @rupalichavan9860  verified on production

**Comment by rupalichavan9860** [comment]
Verified
