### ISSUE TITLE
Support remains added for both parent and child in below scenario

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1522]
Consider scenario like “camp 1”->”sub camp”->”1”  , User A is supporting “sub camp” and “camp 2” which is sibling of “camp 1” and after supporting ,change parent of “camp 1” to “camp 2” then 
Expected Behavior :
Support should get removed from “camp 2”, User A must be supporter of “sub camp” only  and total score should be “1”

Current Behavior : 
Support remains added for  “camp 2” even if “camp 2” is parent of “sub camp” and total score is “1”(but score is divided into “camp 2” and “sub camp which is incorrect)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on production
