### ISSUE TITLE
Page crash while adding support to child camp(when already supported parent camp) and parent camp(when already supported child camp) 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1526]
Steps to reproduce : 
1. Create topic and create "camp 1"
2. Support "camp 1"
3. Create "sub camp" under "camp 1"
4. Support "sub camp"

Getting below crash : 
![image](https://user-images.githubusercontent.com/40416610/183080214-70278c5e-9ce1-4e39-984f-0b6d61368431.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified
