### ISSUE TITLE
Both camp 1 and camp 2 score is displaying as 0.50 in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1529]
Steps to reproduce : 
1. Create new topic and create two camps "camp 1" and "camp 2"
2. Support both camps(score is camp 1: 0.75 and camp 2: 0.25)
3. Create third camp "camp 3" under "Agreement"
4. Change parent of "camp 3" to "camp 2"
5. Now observe score : 
camp 1: 0.75 ----correct
camp 2: 0.25 ----correct
camp 3: 0 ----correct
7. Change parent of "camp 3" to "camp 1"

Expected Result : 
Score should be 
camp 1: 0.75 
camp 2: 0.25 
camp 3: 0

Actual Result : 
camp 1: 0.50 
camp 2: 0.50
camp 3: 0

![image](https://user-images.githubusercontent.com/40416610/183720288-ab5b274e-da03-4f68-8023-adb632aeab19.png)

**Comment by rupalichavan9860** [comment]
Also choice numbers are incorrect in above case : 
![image](https://user-images.githubusercontent.com/40416610/183827271-da8ee5f5-e5be-4af8-855e-687fb3ec227f.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and is working fine

**Comment by rupalichavan9860** [comment]
Verified

**Comment by subhancd** [comment]
working fine on live. kindly, verify @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on production
