### ISSUE TITLE
File upload- Browse button must show hand pointer as it is clickable 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1534]
Steps:

1. Login the application
2. Click on upload file
3. Hover on browse button

Actual result:  it shows pointer arrow
Expected Result: Hand pointer must be seen as the browse button is clickable
![Screenshot 2022-08-16 at 11 00 10 AM](https://user-images.githubusercontent.com/91254708/184804325-d68140c9-1cdc-4f8a-a0d5-696968340fb1.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
