### ISSUE TITLE
Camp created success message should be uniform.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#154]
Success message should be "Success! Camp created successfully. It's live now." instead of "Success! Camp Created Successfully."

**Comment by gautamv16** [comment]
@rupalichavan9860 there will be no live message in camp as it has a different flow for live.

**Comment by gautamv16** [comment]
@rupalichavan9860 just updated for small caps.... test for that...

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
