### ISSUE TITLE
Incorrect score is displaying for delegated user when selected "Sand City" Algorithm

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1541]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/185842927-c659aa86-8bdd-4d20-8035-4e3997823c41.png)

**Comment by rupalichavan9860** [comment]
@karun0607gautam Please check .
#1286 Related ticket

**Comment by karun0607gautam** [comment]
@rupalichavan9860 this is fixed . please test

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
