### ISSUE TITLE
Create a "Forward Party" Canonizer Algorithm.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#1546]
This will be an identical copy of the [Republican](https://canonizer.com/topic/53-Canonizer-Algorithms/15-Republican-Party) or [Democrat](https://canonizer.com/topic/53-Canonizer-Algorithms/16-Democratic-Party) algorithm, except use the [Forward Party camp id 231](https://canonizer.com/topic/231-Preferred-Political-Party/6-Forward-Party).

**Comment by rupalichavan9860** [comment]
Tested and verified on staging
@BrentAllsop Can you please check and close if fine for you

**Comment by rupalichavan9860** [comment]
Algorithm is implemented but there are some issues which are logged under ticket #1568 
So closing this ticket

**Comment by rupalichavan9860** [comment]
Verified on production
