### ISSUE TITLE
Error message should be proper on "Blog" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#155]
Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Go to Blog
3.Select any blog and click on "CONTINUE READING" button
4.Go to "LEAVE A REPLY" part
5.Without entering in any field click on "POST COMMENT" button

Expected Result:
Error message should be "ERROR: Please fill the required fields (Name, Email)." and should be in red colour. Fields name in error message must match with fields name on the form

Actual Result:
Error message is displaying "ERROR: please fill the required fields (name, email)."
![image](https://user-images.githubusercontent.com/40416610/42128224-084f4af6-7cc4-11e8-8618-5b7660ba154e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this comment feature or reply feature will not be in blog as discussed yesterday and for this already created another ticket so its not an issue of feature required.
