### ISSUE TITLE
Camp is not listing in parent camp list drop down in below scenario

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1550]
Steps to reproduce : 
1. Login with User A and create a new topic
2. Create New camps "Camp 1" & "Camp 2" and support both camps
3. Login with User B and submit camp change by changing parent of Camp 1 to Camp 2 
4. Commit changes and it will be in review 
5. Login with User A and object change proposed by User B
6. Try to change parent of "Camp 2" to "Camp 1" from "Agreement"

Expected Result : 
"Camp 1" should display in parent camp list

Actual Result : 
"Camp 1" is not listing in parent camp list drop down

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 working fine on production

**Comment by rupalichavan9860** [comment]
Verified
