### ISSUE TITLE
Wikitext Parser Has No Sanitization

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer.2.0#1558]
Wikitext by design allows users to include HTML tags to their text body. If this user input is not sanitized, it allows for an attacker to include JavaScript elements.

Example of camp with JavaScript in the Camp Statement
https://canonizer.com/topic/561-Marketing-Strategies/2-Big-Tech-Censorship

For reference
https://doc.wikimedia.org/mediawiki-core/master/php/Sanitizer_8php_source.html

**Comment by mark-shamy** [comment]
Script injection is also possible on Edit Summary text fields, Keywords text fields, and URL text field when user enters a malicious string like ` http://example.com/"><script>window.alert("Hello")</script> `

**Comment by gautamv16** [comment]
@ashish76 can you please work on this urgently.

**Comment by ashish76** [comment]
Noted

**Comment by rupalichavan9860** [comment]
@mark-shamy 
Can you please verify this on staging ?

**Comment by mark-shamy** [comment]
@rupalichavan9860 Tested and verified, script tags are not being stored or served.

**Comment by mark-shamy** [comment]
@rupalichavan9860  Tested and verified, script tags are not being stored or served.

**Comment by rupalichavan9860** [comment]
@mark-shamy Thank you for verifying . I am moving this ticket to "staging approved" as changes are not on live environment so we will close once verified on live

**Comment by rupalichavan9860** [comment]
Verified By Ashutosh
