### ISSUE TITLE
"POST COMMENT" button on blog page is not validating all required fields in one click.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#156]
Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Go to Blog page
3.Select any blog and Click on "CONTINUE READING"
4.Go to "LEAVE  A REPLY" part
5.Enter data only in Name & Email fields and click on "POST COMMENT" button

Expected Result:
1.Error message should be in red colour
2.Error message should be "ERROR: Please type a comment."
3.If Comment is mandatory field it should marked with "*" symbol and "POST COMMENT" button should validate at the time of validating Name and Email fields.By doing this,it will saves users time also.

Actual Result:
1.Error message is displaying in black colour
2.Error message is displaying "ERROR: please type a comment."
3.Write your comment... is not marked with "*" symbol  and "POST COMMENT" is not validating this for first time

**Comment by gautamv16** [comment]
@rupalichavan9860 this comment feature or reply feature will not be in blog as discussed yesterday and for this already created another ticket so its not an issue of feature required.
