### ISSUE TITLE
Getting page crash on as of date

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1566]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Open any topic and apply as of date filter less than or equal to topic created date 

Actual Result : 
Getting below  page crash 
![image](https://user-images.githubusercontent.com/40416610/187368742-120b650c-fc06-4eaa-bc1e-90df9e74309b.png)

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine now

**Comment by subhancd** [comment]
working fine on live. @rupalichavan9860 kindly, verify

**Comment by rupalichavan9860** [comment]
Verified
