### ISSUE TITLE
Total Support for This Camp (including sub-camps) under section Support Tree for "camp name" Camp is displaying score as 0

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1569]
Please refer attached screenshot : 
![image](https://user-images.githubusercontent.com/40416610/187410524-b0cf9b49-e860-4508-a6ca-0c0bcaeba0e6.png)

![image](https://user-images.githubusercontent.com/40416610/187410623-466a949e-283e-49db-8947-0da0fc4cc846.png)

**Comment by sunilspr7** [comment]
@sunnyjindal This issue appeared  when #1287 ticket was solved. @kshitij1326 worked on #1287 task. So I'll re-assign this ticket to him

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
