### ISSUE TITLE
Error message should be proper on "Blog" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#157]
Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Go to Blog
3.Select any blog and click on "CONTINUE READING" button
4.Go to "LEAVE A REPLY" part
5.Do following scenarios:
            a. Enter comment,email ,Enter more than 255 characters in Name field and Enter more than 255 
               characters in Website field  and click on "POST COMMENT" button
            b.Enter invalid email in Email text box

Expected Result:
            a.It should display error message with maximum character length limit and error message should 
              be in red colour.
            b.Error message should be "ERROR: Please enter a valid Email." and error should be in red color

Actual Result:
           a.Error message for Name field is displaying "ERROR: your name is too long." and for Website it is 
             displaying "ERROR: your url is too long."
           b.Error message is displaying "ERROR: please enter a valid email address."

![image](https://user-images.githubusercontent.com/40416610/42128383-aaac1fc4-7cc7-11e8-94c1-628c0f292f56.png)

![image](https://user-images.githubusercontent.com/40416610/42128449-8d5b4754-7cc9-11e8-8c8c-8e8d5693a373.png)

![image](https://user-images.githubusercontent.com/40416610/42132793-5306d8de-7d3c-11e8-87f4-4c8fa4849959.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this comment feature or reply feature will not be in blog as discussed yesterday and for this already created another ticket so its not an issue of feature required.
