### ISSUE TITLE
Changes are getting auto committed on camp history page  

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1589]
Whenever user submitting new changes , old changes( not committed) are automatically gets committed on camp history page

![image](https://user-images.githubusercontent.com/40416610/189051287-0bea821f-596d-4845-808d-f86f50fefa32.png)

**Comment by mark-shamy** [comment]
@BrentAllsop This functionally has no recorded specifications. What behavior should the system follow?

- Prevent user from submitting new changes?
- Warn user of uncommitted changes?
- Delete uncommitted changes?

**Comment by mark-shamy** [comment]
Expected behavior.
