### ISSUE TITLE
Calendar search on Blog page is not more effective

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#159]
Calendar search should be more effective.
Now user is able to search blogs month wise only.User should able to select year so that user can easily search blogs.

Consider following scenario:
By default calendar is displaying for current month.But if user wants blogs from July 2015,he needs to click on previous month name several times until July 2015.

**Comment by gautamv16** [comment]
This issue is solved by jim and brent, its not an issue, calender is working properly adn showing only those dates which have blog post only.
