### ISSUE TITLE
Implement check in Canonizer2.0 based on Jira ticket CAN-1111

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer.2.0#1593]

**Comment by sunilspr7** [comment]
@rohit-talentelgia  sir issue is solve in this PR - https://github.com/the-canonizer/canonizer.2.0/pull/1580

**Comment by sunilspr7** [comment]
@rupalichavan9860   I have implement this following cases 
1) Topic add / edit case 
2)  Camp create / Edit 
3)  add direct support and delegate support
4)  Statement Add / Edit 

5) Add threads / add replies and edit replies case

**Comment by rupalichavan9860** [comment]
@sunilspr7 Verified but I found minor issue in this . Warning message on supported camps is different in color than other places 

Expected Result : It should be uniform at all places
Supported Camps : 
![image](https://user-images.githubusercontent.com/40416610/190392726-e31af64f-a478-4e39-9a46-38388de36f46.png)


Other places : 
![image](https://user-images.githubusercontent.com/40416610/190392592-8baadd28-1253-45a3-b1bf-964ab1524788.png)

**Comment by rupalichavan9860** [comment]
Tested and Verified

**Comment by rupalichavan9860** [comment]
Verified on production
