### ISSUE TITLE
Account creation mail with activation link 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#160]
When a user registers to an application for the first time, he/she needs to activate the account by clicking on the activation link sent in Email. This also verifies the user’s given Email address is valid and accessible.

**Comment by BrentAllsop** [comment]
Varun suggested sending a code to the user's e-mail...

**Comment by gautamv16** [comment]
@rupalichavan9860  and @BrentAllsop please check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and it is working good.
@BrentAllsop Please check this functionality and One Time Verification Code email.If it is fine for you I will close this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 Working good so closing this issue.
