### ISSUE TITLE
When  "Disable additional sub camps" is selected and then trying to select"Single level camps only" is not happening

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#1604]
When  "Disable additional sub camps" is selected and then trying to select"Single level camps only" , it must get selected. Currently I have to deselect"Disable additional sub camps" and then select other option, which is not a good user experience.
This issue is on staging & live
![Screenshot 2022-09-09 at 12 30 33 PM](https://user-images.githubusercontent.com/91254708/189290793-0af779ef-ea99-450b-9cf5-9bd2299865af.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
