### ISSUE TITLE
Page crashed when registering new user.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#161]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Click on Register
3. Enter all mandatory fields
4. Click on "Create your account" button

![image](https://user-images.githubusercontent.com/40416610/42227835-0582a8d4-7f00-11e8-9a73-16eb0fc6b0ff.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is working now
