### ISSUE TITLE
Newly created camp is not listing under tree and score is also not getting updated 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#1617]
Please refer attached screenshots

![image](https://user-images.githubusercontent.com/40416610/191429094-f87890c7-7c4b-49cb-9465-6845cec29c93.png)

![image](https://user-images.githubusercontent.com/40416610/191429082-5dfb6327-c4d0-465c-8fa6-e4c272e4865a.png)

**Comment by sajid315** [comment]
Working fine now on staging.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on live
