### ISSUE TITLE
"Canonizer Sorted Camp Tree" panel is displaying incorrect count for supports count on page load

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#162]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create New topic and Login with another user to support this newly added camp
4. Now again login with submitter account
5. Go to Browse and click on added topic
6. Observe page 

Expected result:

"Canonizer Sorted Camp Tree" panel and "Support Tree for "Agreement" Camps" panel should display camp count as 2

Actual result:
"Canonizer Sorted Camp Tree" panel and "Support Tree for "Agreement" Camps" panel is displaying camp count as 1 and after clicking on topic name it is displaying camp count as 2

Before clicking on topic name:
![image](https://user-images.githubusercontent.com/40416610/42229495-38008ce6-7f04-11e8-92b3-4d5669639cb6.png)

After clicking on topic name:
![image](https://user-images.githubusercontent.com/40416610/42229531-508cd738-7f04-11e8-95d5-a2d5043d7f8e.png)

**Is this as per business requirement or issue?Please clarify...**

**Comment by gautamv16** [comment]
@rupalichavan9860 this is not an issue. In first screenshot you have selected a topic for a particular date and time and that time it has only 1 support and overall it has 2. So i think you need to understand complete flow first before testing these. So lets have a meeting for this. Dont test such issue untill you dont know the flow.

**Comment by rupalichavan9860** [comment]
@gautamv16  Okay.Sure
