### ISSUE TITLE
"Canonizer Sorted Camp Tree" is not displaying for some submitters

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#164]
Steps to reproduce:
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic
4. Go to browse and select newly added topic

Expected result:

It should display Topic name in "Canonizer Sorted Camp Tree" panel for submitter.

Actual result:

It is not displaying Topic name in "Canonizer Sorted Camp Tree" panel for submitter.Now login with another user ,and go to browse and select same topic,he/she is able to see topic name in "Canonizer Sorted Camp Tree" panel .

![image](https://user-images.githubusercontent.com/40416610/42237278-f948916c-7f1a-11e8-8eb8-1c1a01562ffb.png)
![image](https://user-images.githubusercontent.com/40416610/42237295-036ca426-7f1b-11e8-9407-114c0bec4272.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 again after investigation, its not an issue. This is algorithm selection effect. In one account you have One person one vote and in other you have Computer science Expert, so both will have different value.

Please understand alogithm first before testing else it will waste your time. Every algorithm have their own score value.
