### ISSUE TITLE
"Browse" page should have functionality for "Topics By Me" which will list topics created by logged in user.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#165]
As Browse page is listing all topics together,it is difficult for user to search and open topics created by him/her.
I think it should have functionality who will list out topics created by logged in user.So it will be more user friendly

**Comment by BrentAllsop** [comment]
Something close to this already exists in the user support page.
We may want to design and enhance more functionality in this entire area.

**Comment by gautamv16** [comment]
@rupalichavan9860 check browse page, you will have option to select own topics.....

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Option is available to select own topics.
But I found following issue in vase of user is new(Who don't have any topics)

Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Create a new user account and log in using new user 
3. Go to Browse
4. Click on "Only My Topics" checkbox

Expected result : 
It should display "No records found" or any other respective message

Actual result : 
As of now it is displaying "No records found for selected as of date." even if I have not selected date filter(Selected filter is "Default")

Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/46245166-35217380-c407-11e8-867c-a83e1fbdb0d2.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  pls restest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It looks fine now so closing this
