### ISSUE TITLE
"Canonizer Sorted Camp Tree" panel is not displaying any data if user updated his/her default algorithm preference 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#166]
Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Login with valid email and password
3.Create new topic
4.Go to Account Settings and update default algorithm preference
5.Go to browse and select added topic--("Canonizer Sorted Camp Tree" panel is not displaying any data)
6.Again Go to Account Settings and update default algorithm preference(Previous one)--("Canonizer Sorted Camp Tree" panel is displaying data properly)
Is this issue?

**Comment by gautamv16** [comment]
@rupalichavan9860 these are not issues, you have to understand algorithm to test these. Each algorithm selection will show topic according to algorihtm. Algorithm is filter for topics to display.
