### ISSUE TITLE
Design of the drop-down is not proper on Internet Explorer and Mozilla Firefox

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#167]
Design of drop down should be uniform on all browsers.
Please check this for all canonizer pages drop downs  

![image](https://user-images.githubusercontent.com/40416610/42265076-15ec0ef0-7f90-11e8-9402-c582a312a318.png)

![image](https://user-images.githubusercontent.com/40416610/42265101-2e3f3a4a-7f90-11e8-8c2a-5d4be86c5b6e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 dont waste time on such things.  Each browser have their own compilers and this design will be different for different browser.

Please post some bugs which are genuine.......

**Comment by rupalichavan9860** [comment]
@gautamv16 I put this issue because I understood that it can be customize to same look & feel
