### ISSUE TITLE
Total Support for This Camp (including sub-camps) count is displaying incorrect when opening any topic from Browse page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#169]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Choose default algorithm as "One Person One Vote"
3.Create any topic
4.Go to Browse and select recently added topic(reference topic:OPNV-RC-Topic1)

Expected result:

It should display as count 1 for all algorithms when you are selecting from Landing page or from Browse page.

Actual Result:

If selecting from Browse it is displaying count as 41.93 for "Mind Experts" filter and count as 1 if selecting from Canonizer landing page

Browse:
![image](https://user-images.githubusercontent.com/40416610/42373235-ef3b82ba-8131-11e8-81ba-67485ce235da.png)

Landing Page:
![image](https://user-images.githubusercontent.com/40416610/42373326-35e28862-8132-11e8-87df-35fe98a4582b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test it again after clearing cache

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Working fine now.

**Comment by BrentAllsop** [comment]
There is still a scoring issue.
I'm supporting [Deepak Loomba's camp](https://canonizer.com/topic/81-Deepak-Loomba/29) as my 10th choice.  My score is incorrectly showing 1 (should be close to a fraction of zero, need to show more decimal places in these cases.)
While the total score is showing zero.

Also, it currently shows:
10:Brent Allsop  1
Let's move the order number to the end, in parenthesis like this:
Brent Allsop(10) 1

**Comment by rupalichavan9860** [comment]
I am also facing scoring issues
1. Created fresh topic and sub camp and I am the only supporter of single sub camp , my score is displaying as 0.5 and total score for the camp is displaying as 1

![image](https://user-images.githubusercontent.com/40416610/97286259-4993fc80-1869-11eb-954e-78e292f81943.png)

2. Now I am trying to support sub camp with another user .And now score for user1 is displaying as 0 and for user2 score is displaying as 0.5 and total score for camp is displaying as 2

![image](https://user-images.githubusercontent.com/40416610/97286626-b14a4780-1869-11eb-9bfc-12cdb872a5e3.png)

**Comment by rupalichavan9860** [comment]
Also checked it for other topics(both old and new),check any camp from any topic.
Scenario :  When camp is having only one supporter score is displaying as 0.5 and when camp is having multiple supporters , score for first is displaying as 0.5 and 0 for rest users

for reference ,
![image](https://user-images.githubusercontent.com/40416610/97809683-65960480-1c94-11eb-85a0-058e9ea51836.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still I am facing issues .Please refer following topic 
https://staging.canonizer.com/topic/273-test-by-Rupali-Auto-2-nov/2-test-camp-1#statement
sub camp "test camp 1 " is having 3 supporters 1.Rupali auto 2. Rupali N is delegating support to Rupali auto and 3. Rupali C
sub camp "test" is having 1 supporter "Rupali C"
So the score for "test camp 1" is 2.5 and for "test" is 0.25--- looks correct

But I can't see user nickname under support tree of sub camp "test" and can see only score
Also score for sub camp "test camp 1" for "Rupali C" should display 0.5 instead of 1
@BrentAllsop Please check and correct if I am missing something

reference screenshot

![image](https://user-images.githubusercontent.com/40416610/97895594-000c4b80-1d5a-11eb-88c1-269ab58627a8.png)


![image](https://user-images.githubusercontent.com/40416610/97895651-14e8df00-1d5a-11eb-81e9-f67017f2f488.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I am facing one more issue while supporting new camp. Please refer following scenario

Reference topic : https://staging.canonizer.com/topic/275-Test-topic-22-nov-2020/1-Agreement

This topic is having 3 sub camps "test camp 1", "test camp 2" and "1test".
I am already supporting "test camp 1", "test camp 2" and when I supported camp "1test" I am getting support removal emails for both camps "test camp 1" and "test camp 2(In actual support is not getting removed)

**Comment by rupalichavan9860** [comment]
@gautamv16 Not able to test as I am getting page crash while supporting camp

**Comment by rupalichavan9860** [comment]
@gautamv16 User can see same camp name multiple times as supported camp so I am not able to calculate score properly.I have already logged this issue in other issue please refer screenshot for more details.

![image](https://user-images.githubusercontent.com/40416610/109298835-31091280-785a-11eb-8cdd-176367a290ed.png)

SO I will check the once the above issue is fix.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Choice number is always displaying as 1 for all camps .Also for nick names like "1rupali1" choice number is missing .please refer attached screenshot

"sub camp under test camp2" Camp: 
![image](https://user-images.githubusercontent.com/40416610/111916517-5972de00-8aa1-11eb-91be-8ea3478a4d9a.png)

"Test camp 1" Camp : 
![image](https://user-images.githubusercontent.com/40416610/111916536-75767f80-8aa1-11eb-82c4-11c9d3b84f57.png)

missing choice number : 
![image](https://user-images.githubusercontent.com/40416610/111916608-c38b8300-8aa1-11eb-9fbf-ecca47592de0.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Also please check choice number sequence on supports pages. Please refer below screenshots

![image](https://user-images.githubusercontent.com/40416610/111993824-149c8500-8b3d-11eb-8d5d-0aa06f1d1301.png)

![image](https://user-images.githubusercontent.com/40416610/111993914-2aaa4580-8b3d-11eb-8e1f-9ccd25badca2.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Its fixed. Please test. and the choice number you have mentioned is coming according to the support order for that user for selected camp

**Comment by rupalichavan9860** [comment]
@gautamv16 count is displaying same for both camps as both camps are displaying at position 1
![image](https://user-images.githubusercontent.com/40416610/112964747-3a8ddf00-9166-11eb-83d8-349f9f3eca05.png)

![image](https://user-images.githubusercontent.com/40416610/112964861-53969000-9166-11eb-9951-815d4b63caeb.png)

![image](https://user-images.githubusercontent.com/40416610/112964948-6a3ce700-9166-11eb-8d82-2987c389f9d2.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this should be fixed now because ordering issue is fixed.Please retest it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine now so closing this issue
