### ISSUE TITLE
Profile is getting updated with "Date Of Birth" as future date on "Manage Profile Info"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#170]
![image](https://user-images.githubusercontent.com/40416610/42396972-acfca96a-8181-11e8-992b-5d2d613cd4ce.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.It is working fine but as user can edit Date Of Birth ,But it should be like other editable fields(Colour should be White instead of Gray)

**Comment by gautamv16** [comment]
@rupali again this issue is not relevant. This field is readonly user can
only select the value from calender and and cant edit manually and it will
greyed out. Please close issue if ticket problem is fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay .No issues.I m closing this
