### ISSUE TITLE
"Manage Profile Info" is accepting any data in City,State and Zip Code

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#171]
I think State and City should have drop down.And it should depends on Country drop down.
State drop down should populate/lists only states in selected Country
City drop down should populate/lists only cities in selected State

Or 
 City,State should auto populate on Zip Code

![image](https://user-images.githubusercontent.com/40416610/42397379-5e7a879c-8183-11e8-9bb4-fae13b22decd.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  right now this is flexible and not restricted. Do you think without this we have any issue ? If brent want this to be done then it will be in next release and its not an bug.

**Comment by rupalichavan9860** [comment]
@gautamv16 Validation should be there.We can say its an enhancement.

**Comment by BrentAllsop** [comment]
Let's spend a bit of time, now, checking for options to do an actual canonical address selector that does more than just country and state drop downs.  Takes you to the exact canonical address.
If we find a free, and easy one, let's do it now.
If not, let's list the options we find and
Let's change this to a future feature, then we can do that when we get to it.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 As per discussed in meeting "Country " drop down should display all countries , so removing the fixed and ready to test label

**Comment by gautamv16** [comment]
@rupalichavan9860 added countries to dropdown. please check

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see the the countries now but can you please keep first letter of countries as capital letter and rest small.
Something like below,

![image](https://user-images.githubusercontent.com/40416610/96020644-f6cf4380-0e6b-11eb-97fb-0113c1102ed8.png)

**Comment by rupalichavan9860** [comment]
Also I am not able to update profile with selected address.

**Comment by gautamv16** [comment]
@rupalichavan9860 its done also added non_usa option in mobile carrier as discussed in meeting

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Can see the CamelCase country drop down now and able to update profile with selected address also but still  have 1 issue

After selecting address from "Address Line 1" other fields are getting populated and grayed out (along with Country drop down) but I can change the country(Can select any country even if selected address from USA) and update profile. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/96564108-5c925400-12e0-11eb-8b22-3f569e3ff4e3.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Above issue is working now but still have some doubts like 
1. For the new user initially all the fields are blank.
Now try to update profile ,profile will not get update.
Country is mandatory but new user is not able to select only Country(Needs to select Address line 1) and profile will get update.

![image](https://user-images.githubusercontent.com/40416610/97115403-8b635c80-171c-11eb-8946-4f9115c1a402.png)

2. After selecting address line 1 from suggested addresses update the profile and again put any text in address line 1 or make it blank and update profile, profile is getting saved .Is it fine ? @BrentAllsop Please confirm

![image](https://user-images.githubusercontent.com/40416610/97115581-7d620b80-171d-11eb-9c91-a7cbd8139680.png)

**Comment by BrentAllsop** [comment]
I already have "Sandy" in my city field, and it won't let me change it.

**Comment by BrentAllsop** [comment]
The country should not be mandatory.
All address fields are not mandatory.
If the user clears the address 1 field, all other address fields should be cleared, on the client side.

**Comment by BrentAllsop** [comment]
If the user does not select a value for address line 1.
This will result in none of the other address fields being selected, so
Clear the address line 1, so the user will be forced to pick a value.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I am still facing issue for some cases .Please refer following scenario
1. Select address from Address Line 1 suggestions
2. Update profile
3. Now type any text in Address Line 1 like "test test", "any text"
4. Update profile

Expected Result : 

It should clear the address line

Actual Result : 

Profile is getting updated

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/98471438-35111600-2212-11eb-8b18-1cb08f5a05c6.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Latest issue is fixed but now user is able to update the profile with blank address line 1 .Please refer following scenario
1. Select address from Address Line 1 suggestions. It will auto populate all other address fields
2. Make Address Line 1 blank
3. Without clicking anywhere click on Update button

Expected Result : 

It should clear the address line and all other address fields

Actual Result : 

Profile is getting updated with blank address line and filled all other address fields
![image](https://user-images.githubusercontent.com/40416610/98496575-f1e19200-2267-11eb-83da-848c6181d488.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Everything is working fine now but I found one minor doubt in this 
As of now country is getting auto populated on Address Line 1 selection so can we remove "--Select--" from country dropdown?

![image](https://user-images.githubusercontent.com/40416610/99896515-587a9d00-2cb7-11eb-9233-5f8399f6ae2c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 According to me i think we dont need to remove this as there is nothing wrong in this. Because since it is autopopulating , it will get populated on google address selection

**Comment by gautamv16** [comment]
@rupalichavan9860 removed the text from country dropdown

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Everything is working fine now so closing this issue
