### ISSUE TITLE
"List of supported camps" is not displaying properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#172]
Some items are displaying as blank.
![image](https://user-images.githubusercontent.com/40416610/42409127-523e574a-81f3-11e8-861c-348a47850299.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is not displaying any blank data in list but according to my understanding it should lists all supported camps which are present in Account Settings->My Supports
Please clarify

**Comment by gautamv16** [comment]
@rupalichavan9860 your aaccount have support issue as you have changed Agreement Camp name which cant be changed as that is the base for all topics. Root camp name cant be changed from Agreement and that validation is there now. So if you want to test. Check all other camps supports except that topic camps and Agreement Me. or do fresh topic and fresh account testing.

**Comment by rupalichavan9860** [comment]
@gautamv16 Validation is there now but user can change Keywords,Additional Note,Camp About URL and Camp About Nick Name.As of now Camp Name field is disabled but user can change other fields and not able to save changes. 

Check following scenario:
Enter data in editable fields and click on "System Update" button.It is displaying error message "The camp name field is required." even if camp name is present

![image](https://user-images.githubusercontent.com/40416610/42561207-37da3ede-8516-11e8-9493-fe2278c56423.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.it is working now
