### ISSUE TITLE
"Add new nickname" Link name should be proper on Supported Camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#173]
Link name should be "Add New Nick Name" instead of "Add new nickname"

![image](https://user-images.githubusercontent.com/40416610/42409463-58ad2ade-81f8-11e8-9e99-27f338802742.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 retest it

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.verfied
