### ISSUE TITLE
"<Start new supporting camp here>" is displaying "Error!Topic does not exist." on "Create New Camp" for first time

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#174]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Select "Mind Experts" from Canonizer Algorithm drop down from left panel
4.Click on Algorithm Information
5.Select "Mind Experts" from Canonizer Sorted Camp Tree
6.Click on "Mind Experts Topic" in Camp Statement
7.Click on "Start new supporting camp here"

![image](https://user-images.githubusercontent.com/40416610/42409592-3af6cd2c-81fa-11e8-87ba-1a8e34f17bca.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 cant reproduce this.

**Comment by rupalichavan9860** [comment]
@gautamv16 Please follow steps.
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Select "Mind Experts" from Canonizer Algorithm drop down from left panel
4.Click on Algorithm Information
5.Select "Mind Experts" from Canonizer Sorted Camp Tree
6.Click on "Mind Experts Topic" in Camp Statement
7.Click on "Start new supporting camp here"
![image](https://user-images.githubusercontent.com/40416610/42442570-a5da3a72-8388-11e8-81ea-342ab58b5204.png)

**Comment by gautamv16** [comment]
Followed these steps, thats why i replied that i cant reproduce this.

**Comment by rupalichavan9860** [comment]
@gautamv16  Sometimes this error is displaying on "Topic: Mind Experts" page also.Please find attached screenshot

![image](https://user-images.githubusercontent.com/40416610/42443052-0f188eca-838a-11e8-9744-afbf6b88348d.png)

**Comment by gautamv16** [comment]
It will come if you type wrong topic id or trying to access wrong topic.
Then it will redirect to your last visited page and show this message.

**Comment by gautamv16** [comment]
@rupalichavan9860 retest it. Its not on my machines even tested on Karun system..

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Working fine now
