### ISSUE TITLE
Validation is missing on "Create Topic" page.It is accepting duplicate topic name

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#175]
Steps to Reproduce :

1.Go to https://staging.canonizer.com/
2.Click on Log in
3.Login with valid Email and password
4.Go to "Create New Topic"
5.Enter existing topic name in "Topic Name" text box
6.Click on "Create Topic" button
Expected result:
Topic name should be unique.Error message should be displayed for duplication.

Actual Result:
It is accepting duplicate data

![image](https://user-images.githubusercontent.com/40416610/42443992-a3a6f264-838c-11e8-8193-a9e5bece9ba6.png)

**Comment by gautamv16** [comment]
There is no such validation required. Will check later with brent for such
things.

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by gautamv16** [comment]
@rupalichavan9860 its not a bug. Will check this later if required.

**Comment by rupalichavan9860** [comment]
@gautamv16 I think its a bug.How user will identify his/her topic from browse list if list have 100 topics with same name.But if you think its not a bug,will check with Brent.

**Comment by gautamv16** [comment]
@rupalichavan9860 yes its not a bug, it can be a new feature which we didnt disussed yet, required or not. Different topic can have same name, 2 people can think similar and can create their own topic of same name. Topic is not a unique indentity. will discuss with the brent and jim then decide its workability. Thanks

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and it is working fine when user is trying to create new topic with existing topic name.But while editing the topic it is not allowing to submit update with same name.Please consider following scenario
1. Select existing topic for example : "ComputerSE-A-By-RN"
2. Click on "Manage/Edit This Topic"
3. Click on "Submit Topic Update Based On This"
4. Enter "Additional Note" and click on "Submit Update" button
5. It is displaying error message "The topic name has already been taken."
![image](https://user-images.githubusercontent.com/40416610/43892414-78accdca-9be9-11e8-9640-fe7659d5f13b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
