### ISSUE TITLE
"Change Password" functionality is missing in Account Settings

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#176]
"Account Settings" must have one more sub tab for "Change Password" functionality.So that user can change their password according to their needs.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested Change Password functionality and I have added new issues for this.Please check

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see the Change Password functionality in Account Settings now,So I am closing this issue.Please check issues related to this functionality
