### ISSUE TITLE
"Confirm Support" button is not working properly.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#177]
If user is already supporting camp and again he/she tries to support the camp warning is displaying as "Warning! You are already supporting this camp. You cant submit support again.",but it is allowing to do confirm support again(User is able to click on "Confirm Support" button again and success message is displaying "Success! Your support has been submitted successfully.")

Same for Delegate your support.
It is okay?

and when join or supporting camp or delegating support on Agreement page error is displaying "Error! You have already supported this camp, you cant submit your support again."User needs to refresh/reload page every time for normal page.
It should refresh/reload automatically.
![image](https://user-images.githubusercontent.com/40416610/42468754-6301fece-83d3-11e8-867f-d55d0d92e363.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this must not happen. Please restest.

**Comment by rupalichavan9860** [comment]
@gautamv16 If user is already supporting parent camp and tries to support child camp,user should able to support child camp and then it will remove parent camp support.
But now "Support" button  is not working on Supported Camps page(User is not able to click on "Submit" button)

![image](https://user-images.githubusercontent.com/40416610/42509241-eed4eca0-8468-11e8-8680-b98c5b6ccd24.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 it wont come, dont you see Submit button for confirmation ? This is used to submit the support.

**Comment by rupalichavan9860** [comment]
@gautamv16 But after clicking on "Support" nothing is happening

**Comment by gautamv16** [comment]
@rupalichavan9860 there is no support button there its submit button.  Can you please check your browser, i have tested on different browser, also i have listed nickname there too to view supported nickname.

**Comment by rupalichavan9860** [comment]
@gautamv16 Its working now.Thanks
