### ISSUE TITLE
Modification in "When you get a new delegated supporter" email format

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#180]
Please check body of email.
It should be "{nick_id} has just delegated **his/her(Gender specific)** support to you in this topic: <link to first choice camp>" instead of "{nick_id} has just delegated his support to you in this topic: <link to first choice camp>"
Ideally this should be decided by logged in users Gender.
![image](https://user-images.githubusercontent.com/40416610/42526736-4d0998ea-8494-11e8-8d8d-ce1f75be06fa.png)

**Comment by BrentAllsop** [comment]
We will change this to "their" instead of "his" or "her".

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Please do it for subject line also.

![image](https://user-images.githubusercontent.com/40416610/42697123-d8b58774-86d7-11e8-940d-2c188cafc275.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
