### ISSUE TITLE
Page crash 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#181]
Steps to reproduce:
1.Go to https://staging.canonizer.com
2.Login with valid email and password
3.Create new topic or open already added topic 
4.Click on "Start new supporting camp here"
5.Enter valid data and Click on "Create Camp" button,this will send mail for camp submittal
6.Open mail and click on "Click Here To View History"

![image](https://user-images.githubusercontent.com/40416610/42532403-6effb5f0-84a4-11e8-89bb-f22e8deb4b27.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  retest it

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working fine now.
