### ISSUE TITLE
File upload issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#182]
1. Symbol in File Name column should have tool tip text on mouse over.

2. Image file without extension is getting uploaded. Ideally upload should validate the file extensions.

![file upload 1](https://user-images.githubusercontent.com/40416610/42532931-f0b27190-84a5-11e8-9856-22d0bbd111bf.PNG)
![file upload 2](https://user-images.githubusercontent.com/40416610/42532932-f0daaf8e-84a5-11e8-8dc5-1ca87a462967.PNG)

3. File extensions should be mentioned ,as of now it is accepting png,jpg ,jpeg,bmp,gif and none

4. Upload file size message should be displayed while uploading file. As of now it is accepting more than 25 MB size.

5. Uploaded File name should have some standard naming conventions. As of now it is accepting any combination of letter, numbers and special characters

**Comment by gautamv16** [comment]
@rupalichavan9860 all done. Point 5th is not required as it can contain anything in name of the file.

**Comment by BrentAllsop** [comment]
@rupalichavan9860 @gautamv16 
When I specified the name to be epist2.gif, it gave it this name: epist2.gif.gif, can't do this.
I got an error: "Error! There is already a file with name epist2, Please use different name."
should use the real name "epist2.gif" not just epist2.  What about jpg...?
Need to discuss all this in a meeting.

**Comment by rupalichavan9860** [comment]
@gautamv16 Incorrect error message is displaying when I am trying to upload image with size greater than 25 Mb.
When I am trying to upload image file with size 25.1 MB it is not allowing me to upload file  and I got an error : "Error! The file may not be greater than 2000 kilobytes."

**But 2000 Kilobytes = 1.9531 Megabytes and 25 Megabytes = 25600 Kilobytes**

Even I am trying to upload image file with 20.6 MB  it is not allowing me to upload file  and I got an error : "Error! The file may not be greater than 2000 kilobytes."

What is the exact file size limit for image upload?2000 kilobytes or 25 MB?Please confirm

**Comment by rupalichavan9860** [comment]
Refer this screenshot 
![image](https://user-images.githubusercontent.com/40416610/43914305-22410956-9c25-11e8-928c-35f5bc6e7ef3.png)

**Comment by gautamv16** [comment]
Its is 2000 KB, need to change 25 MB to 2000 KB

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by BrentAllsop** [comment]
Change the file size limit to 5 MB.
Change the pre filled out value from just "File Name" to "File Name (with no extension)"
There is an issue, when you first upload a file with a 1.0 file name that already exists, the first time it says it succeeded, but in reality, the file URL still points to the old 1.0 image file.

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check Issue Id-228.This is also file upload issue

**Comment by rupalichavan9860** [comment]
@gautamv16 When I am trying to upload bmp image file with 0 bytes in size, it is displaying error "Error! The file must be a file of type: jpeg, bmp, png, jpg, gif."
It should display error message for minimum file size instead of type of file.
Please confirm..

**Comment by gautamv16** [comment]
0 byte file size systen recognize as invalid file and it seems it can be
tempered. So there is no minimum size in file systems.

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by gautamv16** [comment]
@rupalichavan9860 solved  as per discussion. @BrentAllsop  please check existing file issue.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested for file size issue .It is working fine now
