### ISSUE TITLE
Incorrect Submitter Nickname is displaying on "Camp History" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#184]
Incorrect Submitter Nickname is displaying for old version of camp on "Camp History" page.And this nickname is not present in Account Settings->Add & Manage Nick Names

![image](https://user-images.githubusercontent.com/40416610/42587524-9b96c4c8-8558-11e8-9b12-9280ec253263.png)

**Comment by BrentAllsop** [comment]
Varun is going to verify this.
If it is a problem, it is a show stopper, so we will set show stopper now.
If it is found to be not a show stopper, varun will resolve the issue.

**Comment by gautamv16** [comment]
@rupalichavan9860 as i have checked it in detail. This is not an issue. You are missing your nickname, "bb" is your nickname i have verified in database and its status is private so you have used bb nickname for this. Please check properly your nicknames and you will see it there.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.still different name is displaying.
I have submitted "NickNameDisplay" topic with RCanonizer nick name but when I am updating camp with same nick name,for live version this is displaying correct nick name and incorrect for old version
![image](https://user-images.githubusercontent.com/40416610/42687226-ddb894cc-86b5-11e8-8c4d-5fec6a95daa0.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 On topic history it is displaying correct nick name but on Camp history it is displaying incorrect nick name.I have created another topic with "RCanonizer" nick name ,please see attached screenshot
![image](https://user-images.githubusercontent.com/40416610/42687577-df926f56-86b6-11e8-80d4-ed5551609e0e.png)


And "Btest" is not present in my nick name list
![image](https://user-images.githubusercontent.com/40416610/42687900-f5b4bdd8-86b7-11e8-8665-d4e7dec62a66.png)
