### ISSUE TITLE
Related URL is not displaying in "Current Camp Record" panel

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#185]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on Manage/Edit This Camp and Click on "Submit Camp Update Based On This
5. Enter data in all fields and click on "System Update"
6. Click on "View This Version" of live Camp

Expected Result:

It should display Related URL

Actual Result:

URL is displaying on Camp History page but not in "Current Camp Record" panel on agreement page.

![image](https://user-images.githubusercontent.com/40416610/42588737-47e87e8a-855c-11e8-8d9a-e587191ad56c.png)

Click on "View This Version" 

![image](https://user-images.githubusercontent.com/40416610/42588765-5d1d1a36-855c-11e8-991f-9236803d2c08.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 not an issue again this is system flow of browsing history or camp by date and it will show what ever is submitted in that time range. So its not an issue. Such issues must be in question if not clear.

**Comment by rupalichavan9860** [comment]
@gautamv16 after removing date filter also it is not displaying Related URL

![image](https://user-images.githubusercontent.com/40416610/42612911-9734b97c-85bb-11e8-81fe-444324d1889b.png)

**Comment by rupalichavan9860** [comment]
Issue is still reproducible so I am reopening this issue.
And as per discussion we need to do following changes : 
Rename "Related URL" to "Camp About URL" and "Related Nicknames" to "Camp About Nick Name" on Camp History, Agreement page and preview page

**Comment by gautamv16** [comment]
@rupalichavan9860 done

**Comment by rupalichavan9860** [comment]
@gautamv16 Label names are looking good to me now but still "Camp About URL" is displaying blank instead of entered value

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
