### ISSUE TITLE
Incorrect Topic Name is displaying on "Canonizer Forum Details" page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#186]
Steps to reproduce:

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel

Expected Result:

It should display topic name of selected topic

Actual Result:

It is displaying incorrect topic name.
See URL for correct topic name 

![image](https://user-images.githubusercontent.com/40416610/42589759-b653c714-855f-11e8-98a0-e898845a22bf.png)

**Comment by akuks** [comment]
This issue is fixed. It was taking the old name of the Topic. Now it displays the correct Topic name on Forums thread.

**Comment by rupalichavan9860** [comment]
@akuks Retested.Now it is displaying correct topic name but it is not displaying properly if topic name contains special symbols.
![image](https://user-images.githubusercontent.com/40416610/42808177-4adca4cc-89d0-11e8-9e1f-273f093fc4fa.png)

**Comment by akuks** [comment]
@rupalichavan9860, if you are referring to '-', then it wouldn't show it. Because in the Database, '-' is not there. The symbol is added to make SEO friendly URL's.

**Comment by rupalichavan9860** [comment]
@akuks If I have added topic with "-" symbol,then it should display.Right?
Please clarify
Please refer screenshot
![image](https://user-images.githubusercontent.com/40416610/42837350-7dafb330-8a1b-11e8-9877-ce4d074caf5e.png)

**Comment by rupalichavan9860** [comment]
@akuks check for "!@#$%%^^&&&*****" topic.I have created topic whose topic name contains only symbols. And for this topic Camp Forum page is displaying topic name as blank 
![image](https://user-images.githubusercontent.com/40416610/42837586-2051c15a-8a1c-11e8-9caa-0194c74e57eb.png)

**Comment by akuks** [comment]
![image](https://user-images.githubusercontent.com/12954663/42837969-34ef3bfa-8a1d-11e8-950e-9361829ca711.png)
It is showing. Please see the image

**Comment by akuks** [comment]
!@#$%%^^&&&*****, Whats the URL for this topic?

**Comment by rupalichavan9860** [comment]
https://staging.canonizer.com/topic/218-----------------/1

**Comment by rupalichavan9860** [comment]
Name is not displaying properly in URL also for topic name which contains only symbols

**Comment by akuks** [comment]
Ok, got it, if you check the URL, it is coming as blank. I mean it is only getting "----------" in the URL i.e. why it showing as blank.

**Comment by rupalichavan9860** [comment]
Yes

**Comment by akuks** [comment]
if you view source" the page from where it is called. Href is showing as "https://staging.canonizer.com/forum/218-----------------/1/threads". Needs to check with Varun on this Issue. I will ping him tomorrow as he is the owner of this page.

**Comment by rupalichavan9860** [comment]
See for the camp name for same topic,even if camp name contains only symbols it is displaying properly on camp forum but not in URL
![image](https://user-images.githubusercontent.com/40416610/42838627-ef7b43d2-8a1e-11e8-9578-cf98a4f8a651.png)

**Comment by akuks** [comment]
![image](https://user-images.githubusercontent.com/12954663/42839001-ea884266-8a1f-11e8-8e73-4472feb21287.png)
To prevent another hit on Database, we took the topic name from the URL.  See the View Source of the page. There is a blank topic name in the URL. When this page was created somehow it is not showing the correct topic name. I will ping Varun on this as he created this page.

**Comment by rupalichavan9860** [comment]
Okay.sure

**Comment by akuks** [comment]
@rupalichavan9860, 
Hi Rupali,
I have a word with Varun and found out, In the URL,  the topic name is not accurate, as there is some concatenation of camp name to somewhere in the URL for SEO purpose. Topic Name from the URL and from the CAMP Forum Details would not match always.

**Comment by rupalichavan9860** [comment]
@akuks Okay.I am closing this.
