### ISSUE TITLE
Required/mandatory fields should be marked with asterisk mark (*) against the field and "*" should be in red colour on "Create New Thread" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#187]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel

**Comment by akuks** [comment]
Fixed.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
