### ISSUE TITLE
Link name on "Create New Thread" page should be proper.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#188]
Steps to reproduce:

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel

Expected Result:

Link name should be "Add New Nick Name"

Actual Result:

Link name is displaying as "Add new nickname"

**Comment by akuks** [comment]
![image](https://user-images.githubusercontent.com/12954663/42704063-1e6f4458-86ec-11e8-956f-f52f6178d1e2.png)
Done.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
