### ISSUE TITLE
Success message is not displaying after creating new thread.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#189]
Steps to reproduce:

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel
6. Enter Title and select Nick Name from drop down
7. Click on "Submit" button

Expected Result:

It should display success message for thread creation.

Actual Result:

It is not displaying success message and user needs to click 2 times on browsers back button to see "List of all the Threads" and needs to check here whether thread has been added or not.

**Comment by akuks** [comment]
Fixed.
--> Now the Success message is also displayed 
--> When a new thread is created, the application will directly go to the list of all the threads.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified. But success message should be "Thread Created Successfully!" instead of "Thread Posted Successfully!"

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
