### ISSUE TITLE
"Title of Thread": Title text box is accepting unlimited characters

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#190]
It should have some limit on character length.
UI is also getting disturbed.

![image](https://user-images.githubusercontent.com/40416610/42591626-d83ee08e-8564-11e8-92db-7b97f693be41.png)

**Comment by akuks** [comment]
Title of the thread is limited to 100 characters.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
