### ISSUE TITLE
"Create New Thread" page is displaying page title as topic name along with ID.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#191]
Steps to reproduce:

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel

As of now it is displaying "Create a new thread for ID-TopicName"(e.g. "Create a new thread for 221-NewTopicfornickname"). Is it included in functionality to display title as topic name along with ID?or it is an issue?

**Comment by akuks** [comment]
@rupalichavan9860, yes this is the functionality. To make the URL SEO friendly, it is decided to use this format. You can close this ticket.

**Comment by rupalichavan9860** [comment]
@akuks Okay.Thank you for clarification.
