### ISSUE TITLE
User is not able be identify his/her owned thread on "List of all the Threads"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#192]
I think "List of all the Threads" page should have Thread Owner Name along with Thread Name(As of now Thread Name is present).So that user can easily identify his/her own thread and see posts in that thread.
Please let me know your thoughts.

**Comment by akuks** [comment]
@rupalichavan9860, this functionality will be available in next release. This is already in pipeline. I will keep this issue until our next release.

**Comment by rupalichavan9860** [comment]
@akuks This functionality is available and I have verified so closing this
