### ISSUE TITLE
User is able to create duplicate threads several times.Is it functionality or an issue?Please Clarify.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#193]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel
6. Enter title which is already present in "List of all the Threads"
7. Click on "Submit" button

Actual Result:

User is able to create duplicate threads several times.

![image](https://user-images.githubusercontent.com/40416610/42619249-207c97a4-85d5-11e8-8949-353229ed59b8.png)

Is it functionality or an issue?Please Clarify.

**Comment by akuks** [comment]
Title of the thread is not a unique Property. There can be multiple threads with the same title. Most probably will discuss in the next meeting and if required, then fix in next release.

**Comment by rupalichavan9860** [comment]
@akuks It is working fine.But I think it should be at topic level. Because for the topic don't have any threads user is not able to create threads with same name.I will  discuss  this in tomorrows meeting

**Comment by rupalichavan9860** [comment]
@akuks User is able to create threads with same name and according to new feature ,it is camp centric so closing this issue
