### ISSUE TITLE
"Thread Posts" page should be user friendly.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#195]
If user adds 5 posts to same thread at the same time,he/she needs to click on back button of browser several times to go back to the "List of all the Threads".
Posts page should have some functionality to directly go back to the "List of all the Threads" page. 
Is it possible or this is designed as per business requirement?
Please let me know your thoughts.

**Comment by akuks** [comment]
This is a good functionality to add on forums. I will include this :)

**Comment by akuks** [comment]
Functionality Added. A new hyperlink added to the page, on click it will go to the list of all threads under the topic.

**Comment by akuks** [comment]
@rupalichavan9860, Please test this issue.

**Comment by rupalichavan9860** [comment]
@akuks Retested.It is working good now.
But I think newly added link name should be "List of all the Threads" instead of  "List of All Threads" as it is redirecting to "List of all the Threads" page. Just for uniformity..
Please clarify

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
