### ISSUE TITLE
Incorrect camp outline for old page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#196]
https://staging.canonizer.com/topic/88/6?filter=1&asof=bydate&asofdate=2010%2F07%2F01

The bread crumbs for the above page says:
Camp: Agreement / Approachable Via Science / Representational Qualia

But there is no camp tree displayed.

There should always be at least the root camp displayed on every topic.

**Comment by gautamv16** [comment]
@BrentAllsop i can view the camps in the link you sent and every topic has root camp always in tree.  Please check and let me know

**Comment by BrentAllsop** [comment]
@gautamv16 
![image](https://user-images.githubusercontent.com/6559312/42739122-1a4fcd3a-884e-11e8-84fd-9cda492cff68.png)
This is what it looks like to me.  There is nothing in the "Canonizer Sorted Camp Tree" section.
I'm using Chrome.

**Comment by gautamv16** [comment]
@BrentAllsop what algorithm you have selected, if you dont have selected One Person One Vote and you have filter 1 then it will not have any score and it will not display in the tree....

Please clarify...

**Comment by BrentAllsop** [comment]
Ooops, Varun was right - user error.
I had the filter set to filter the entire tree.
