### ISSUE TITLE
"Canonizer Forum Details" page UI is not proper.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#197]
Steps to reproduce:
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel

"Canonizer Forum Details" page
Alignment of all fields on the page must be uniform
1. Should have space between "Canonizer Forum Details" and ":" for uniformity
2. Should have space between "Camp" and ":" for uniformity

![image](https://user-images.githubusercontent.com/40416610/42678452-871ef34a-869c-11e8-8f38-c2d8181c3264.png)

**Comment by akuks** [comment]
UI Changes Updated.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified
