### ISSUE TITLE
Is is necessary to have a "Title" placeholder on "Create New Thread" page if text box is already having label named "Title of Thread:".

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#198]
Steps to reproduce:

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create new topic or open existing topic
4. Click on "Camp Forum" in Camp Statement panel
5. Click on "Create New Thread" from left panel

I think text box placeholder is not required if text box is already having label named "Title of Thread:"
And Label names must be uniform.
Labels name should be
1. "Title of Thread :" and "Nick Name :"
OR
2. "Title of Thread" and "Nick Name"

And if "Title" placeholder is not necessary then please modify error message also.
Error message then should be "The Title of Thread field is required." instead of "The title field is required."

**Comment by akuks** [comment]
@rupalichavan9860, Yes, I think so, I have seen on other websites also where the forums have 'Title' as heading and in Placeholder also. If you are ok with the response, then we can close this Issue.

**Comment by rupalichavan9860** [comment]
@akuks Sure.Closing this issue
