### ISSUE TITLE
Validations are missing for text fields 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#199]
Validations are missing for text fields.

Depending on the text field requirement in the form the inputs needs to processed accordingly :

1. Name field needs to only accept alphabet values.Name field should not accept the numeric content or the special symbols
2. Zip Code field should accept only the alphanumeric input.
3. Address field should allow characters,numeric and symbols input

As of now in our system:

1. First Name,Middle Name,Last Name,Nick Name,Topic Name,Camp Name,Thread Name are accepting all combinations(characters,numbers and special symbols)
2. Zip Code field is accepting special symbols also.

![image](https://user-images.githubusercontent.com/40416610/42681767-3f65bf20-86a6-11e8-827e-b1361bb0e7aa.png)

![image](https://user-images.githubusercontent.com/40416610/42682022-f9a1a570-86a6-11e8-9bd5-1814d45c5481.png)

**Comment by BrentAllsop** [comment]
We may want to restrict some of this, at some time in the future.  But for now, if someone wants to enter these values, in these fields, we may want to just let them.  For example, someone may want to add some third party system interface, that uses special characters in various fields.
Also, some countries do allow alphanumeric in their zip codes.
See canada:  https://en.wikipedia.org/wiki/Postal_codes_in_Canada.
@rupalichavan9860, if you are good with this, at least for now, could you close this?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Yes sure.I will close this one.

For Zip codes:
Zip codes should be alphanumeric,but should not accept special symbols.

**Comment by BrentAllsop** [comment]
We also need to validate and clean the names of topics.
Can't allow "/" and ":" and such (same as camp names).

**Comment by BrentAllsop** [comment]
We also need to make a list of all current topic names with bad characters, to figure out, case by case, the fix for those.  We'll need to do db patching for each, by hand.

**Comment by gautamv16** [comment]
@BrentAllsop I have found the topic names and camp names which have special characters which we do not allow while creating the topics as per current rules on its name. Please find below
[topic_special_character_data.xlsx](https://github.com/the-canonizer/canonizer.2.0/files/4908905/topic_special_character_data.xlsx)

**Comment by BrentAllsop** [comment]
I see the list of all the names with problem characters, so this is progress.
but not seeing the value we will fix them to.
Also, we may want to allow a few, like space and question mark..??
Anyway, let's do some more work on this, with this new list, some day.
So I'm going to remove the 18th release tag.

**Comment by BrentAllsop** [comment]
We need to specify, here, what is an disn't legal.
Then we need to decide to increase the set of what is and isn't legal.

Finally, when the user gets an error, because of an illegal character, he needs to be told why, and which characters are legal/illegal.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Now text fields are not accepting special symbols but we need to do minor change in error messages .
For First Name, Middle Name and Last Name on profile page error messages are "The first name format is invalid.", "The middle name format is invalid.", "The last name format is invalid."

![image](https://user-images.githubusercontent.com/40416610/107219024-7e9e1680-6a36-11eb-9658-4ab1cf469525.png)

It should display specific error message like register page so that user will get idea of what is valid format.
@BrentAllsop Please confirm

![image](https://user-images.githubusercontent.com/40416610/107219257-d472be80-6a36-11eb-9b82-e80d2559d2c6.png)

Same for the camp name(On create camp and camp update page) and thread title
![image](https://user-images.githubusercontent.com/40416610/107219509-36cbbf00-6a37-11eb-9676-ce2f18ee782a.png)

![image](https://user-images.githubusercontent.com/40416610/107219690-709cc580-6a37-11eb-99ca-365e1d4ec1d1.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
