### ISSUE TITLE
Canonizer 2.0 - Develop UMS (User Management System)

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#2]
The Canonizer application must have:

1. **Guest Mode**
2. **Registered User**
3. **Logged In**

**Registered User** can be determined via cookie, but the user is not yet logged in. 
The user can browse, and use default settings, but the user wouldn't set or modify the user setting or contribute in any way in the Canonizer Application.

**Comment by gautamv16** [comment]
Done
