### ISSUE TITLE
Any user has access to edit Help page and Canonizer Algorithm Information page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#200]
As of now any user can edit Camp,Topic and Camp Statement on Help page and Canonizer Algorithm Information page.
I think it must be restricted for normal users.Only selected Users/Roles should have access to add/update Help and Canonizer Algorithm Information page 
Please clarify..

**Comment by BrentAllsop** [comment]
@rupalichavan9860,
Currently, this is as designed.  This is the way all wikipedia pages work.
I anyone, possibly me or JIm adds support for these, it will force any changes to be reviewed, and we will be able to object to any changes made in that case.
In the production system, we don't want anyone supporting these, so both Jim, or I, can make changes, without having to go through the 1 week review period.
Once we go live, if we have problems, and people attempt to make undesirable changes, someone can at that time, can add there support.  But until then, let's try the wikipedia model, hopping that only good changes are submitted, and they will go live instantly.
