### ISSUE TITLE
Page crash on Objection Mail->Camp Forum link 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#201]
Steps to reproduce:
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Open any existing topic 
4. Object any camp
5. Open Objection mail and click on Camp Forum link in Objection mail

![image](https://user-images.githubusercontent.com/40416610/42704377-3105424c-86ed-11e8-92b5-a3b3f874193e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is working now.
