### ISSUE TITLE
Incorrect language is displaying on "Topic History","Camp Statement History" and "Camp History"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#202]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Account Settings->Select any language other than English
4. Click on "Create New Topic" 
5. Check for language on "Topic History","Camp Statement History" and "Camp History" page

Expected Result:
It should display language selected on "Manage Profile Info"

Actual Result:
It is displaying language as "English" even if user has selected other language on "Manage Profile Info"

![image](https://user-images.githubusercontent.com/40416610/42722864-435aad54-8771-11e8-92ab-bffbe9875e6e.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860
Currently, we have "language" values in the DB.
But we don't want to turn any different language ability on, now.
We will do this in the future.
So for the time being, the "Language:" value in the display of topic values should not be displayed.
So, to fix this, all references to a Language field, should be removed in the UI.
But it is OK, for users to specify their language, in their personal data.  It just won't be used, anywhere, yet.

**Comment by gautamv16** [comment]
@rupalichavan9860  please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
