### ISSUE TITLE
Error message for Nick Name field is displaying on two places on Create New Thread page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#203]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password(Who don't have any Nick Name)
3. Go to Browse and select any topic
4. Click on "Camp Forum" on Agreement page
5. Click on "Create New Thread"
6. Without entering in any field click on "Submit" button.

Expected Result : 

It should display error messages for mandatory field at particular place and one error message for one field.

Actual Result : 
Error message for Nick Name field is displaying on two places on the page .

![image](https://user-images.githubusercontent.com/40416610/42727247-bf6021d2-87c0-11e8-99dd-2e5f902c8a34.png)

**Comment by akuks** [comment]
This issue is fixed. Removed the additional message from the page.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
