### ISSUE TITLE
Required/mandatory fields should be marked with asterisk mark (*) against the field and "*" should be in red colour on "Add & Manage Nick Names" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#204]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/    
2. Login with valid Email and password     
3. Click on logged in user name and Go to Account Settings     
4. Go to Add & Manage Nick Names  

Expected Result : 
Required/mandatory fields should be marked with asterisk mark (*) against the field and "*" should be in red colour on "Add & Manage Nick Names" page.

Actual Result : 
"Nick Name" is not marked with asterisk mark (*)

![image](https://user-images.githubusercontent.com/40416610/42727315-106cbaee-87c2-11e8-9d47-d34c09028e6b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
