### ISSUE TITLE
Page Crash/Error Exception on "Supported Camps" page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#205]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password(**Who don't have any Nick Name**)
3. Go to Browse and select any topic
4. Click on "Join or Directly Support This Camp" Or "Delegate Your Support"
5. Nick Name drop down is blank. Without adding any Nick Name directly click on "Confirm Support" button.

Expected Result : 
It should display error message "The Nick Name field is required"

Actual Result : 
Please find attached screenshot.

![image](https://user-images.githubusercontent.com/40416610/42727442-511cd2ac-87c4-11e8-84b5-efe2a142c8c0.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Working now.
