### ISSUE TITLE
Page crash/Error Exception on "List of all the Threads page"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#206]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Without login into system click on "Browse"
3. Select any topic (who have threads) and click on "Camp Forum" on Agreement page
4. Click on any thread from "List of all the Threads"

![image](https://user-images.githubusercontent.com/40416610/42728146-6ed8f732-87d1-11e8-878f-b28eb2bdea6b.png)

**Comment by akuks** [comment]
@rupalichavan9860, I am unable to replicate this issue. Can you retest it again?

**Comment by rupalichavan9860** [comment]
@akuks Retested.Page crash is still exists.Please check it again
Note : Browse as guest( Don't Log in ) and select topic who have threads(refer topic : "ComputerSE-A-By-RN")

**Comment by akuks** [comment]
Unable to retest this issue locally.

**Comment by BrentAllsop** [comment]
@gautamv16, @akuks,
How is the work going on this one remaining show stopper?

**Comment by akuks** [comment]
@BrentAllsop, Still unable to reproduce this issue. I even tried by replicating the staging database locally on all the flavors of OS(I.e. windows, Ubuntu and Windows), but no success. I will try a few more combinations to reproduce it and let you know.

**Comment by gautamv16** [comment]
@rupalichavan9860  please check it and confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks Retested and verified.It is working now

**Comment by gautamv16** [comment]
@rupalichavan9860 please inform everyone on email that Show Stoppers are fixed.. so that i can move ahead with production deployment

@BrentAllsop @CanonizerJim
