### ISSUE TITLE
Email field is accepting invalid email addresses on register page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#207]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Click on Register 
 
Email field is accepting following combinations : 
1. test@yahoo.co.in.in.in
2. test@testtesttest.testtesttesttest

Please verify are they valid email addresses?
![image](https://user-images.githubusercontent.com/40416610/42731764-bdfe316e-8831-11e8-95df-be710be405a7.png)

![image](https://user-images.githubusercontent.com/40416610/42731771-df3d184a-8831-11e8-9782-f5800b7c11f0.png)

**Comment by BrentAllsop** [comment]
Yes, it would probably be good to verify the after @ hostname via dns lookup.
Other than this, we will expect users to be able to verify their e-mail, once we send and e-mail to them for verification purposes.

**Comment by gautamv16** [comment]
@BrentAllsop  after review this i found, there is no validation check for email like this. For this there needs to be seperate DNS check API for domain verification which we dont require here. We just need to verify the email address of user and activate the account. So this feature is already mentioned in other ticket. So close this ticket after reviewing what i said.  @rupalichavan9860

**Comment by BrentAllsop** [comment]
Looks OK to me, so closing.
