### ISSUE TITLE
Incorrect {nick_id} is displaying in "When you get a new delegated supporter" email body and subject line

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#208]
Scenario : 
Login Details : test@yahoo.co.in.in.in
First name : TestUser1
Last Name : TestUser1
Nick Name : Test User

I have selected "Topic for language test"  who have One supporter "Rupali C".If I click on "Delegate Your Support" mail will go to "Rupali C".

Expected Result : 
I think body should be  : 
Hi Rupali Chavan,
Test User has just delegated their support to you in this topic: <link to first choice camp>

Sincerely,

The Canonizer Team

Actual Result  : 
Hi Rupali Chavan,
Rupali C has just delegated their support to you in this topic: <link to first choice camp>

Sincerely,

The Canonizer Team

Please Clarify?

**Comment by gautamv16** [comment]
@rupalichavan9860 one topic can have only one nickname so default nickname will be used everywhere for which that topic is created

**Comment by rupalichavan9860** [comment]
![image](https://user-images.githubusercontent.com/40416610/44274574-19e81380-a260-11e8-89b3-34205c950c89.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working fine now
