### ISSUE TITLE
Browse topic page is not displaying any message when no record found for particular date range

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#211]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Go to Browse
4. Select "as of (yy/mm/dd)" from As Of panel
5. Select "2006/07/01" from calendar control
Records are not present for this date range.

Expected result : 
It should display "No record found for this date range " or any other  respective message instead of blank lists

Actual Result : 

![image](https://user-images.githubusercontent.com/40416610/42806390-fd85574a-89cb-11e8-9c25-42fcd9750bea.png)

**Comment by rupalichavan9860** [comment]
Message should display "No records found for selected as of date."

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested. 
As per discussion message should display "No records found for selected as of date." but it is displaying message "No Record Found!"
Please confirm

![image](https://user-images.githubusercontent.com/40416610/45024167-0d342f80-b056-11e8-8edc-c89dacf280e3.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 done changed

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
