### ISSUE TITLE
Canonizer Forum Details page is not displaying any message when respective topic don't have any threads. 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#212]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Go to Browse
4. Select any topic who don't have any threads
5. Click on "Camp Forum" on agreement page

Threads are not present for this topic

Expected result : 
It should display "No threads present for this topic " or any other respective message instead of blank lists

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/42818492-aa181e3a-89ee-11e8-88ba-3fff98dc0509.png)

**Comment by akuks** [comment]
When the topic doesn't have any new threads, it shows "No threads available for this topic. Start New Threads."

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified.
