### ISSUE TITLE
Incorrect validations for First Name and Last Name on Register page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#213]
Validations for First Name on Manage Profile Info is "The first name may not be greater than 50 characters." and for Last Name is "The last name may not be greater than 50 characters."
But on Register page validations are different

Expected Result : 

As we discussed earlier validations should be 
1. For First Name it should be  "The first name may not be greater than 50 characters."  
2. And for Last Name it should be "The last name may not be greater than 50 characters."

Actual Result : 

Validations on Register page
1. For First Name "The first name may not be greater than 255 characters."
2. For Last Name "The last name may not be greater than 255 characters."

![image](https://user-images.githubusercontent.com/40416610/42832597-5440628a-8a0f-11e8-84e7-e28726be946d.png)

**Comment by rupalichavan9860** [comment]
We have decided to limit the character length of 100 for First Name,Last Name,Middle Name

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is working fine on Register page but it is not working for Middle Name on Manage Profile Info page 
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Account Settings
4. Enter more than 100 characters in Middle Name text box 
5. Click on Update button

Expected Result : 
It should display error message "The middle name may not be greater than 100 characters."

Actual Result : 
It is not displaying any error message
![image](https://user-images.githubusercontent.com/40416610/45049763-3cba5a80-b09d-11e8-867c-b1942aa11587.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 before testing please clear you system cache once. Its working for me. Please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Yes working.
