### ISSUE TITLE
Check validation for Add New Nick Name on "Create New Camp","Submit Statement","Supported Camps","Camp Forum","Manage Topic","Camp Update" Page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#214]
As per "**Once you pick a nick name, for any contribution to a topic, you must always use the same nick name for any other contribution or forum post to this topic.**" validation user must use same nick name for any other contribution or forum post for submitted topic.
According to this validation "Add New Nick Name" should be disabled once user picked a nick name.
It should not display "Add New Nick Name" for following users:  
1. For Topic first submitter
2. Once another user(who is not a topic first submitter) contributed to any one of this

**Comment by rupalichavan9860** [comment]
Need to fix this on Camp forum page also

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed, i did a one change i.e  Add new nickname only will come if there is no Nickname added in account yet. In that way it will solve all problems. Please check and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is working on "Camp Update","Manage Topic" and "Statement Update" pages
But "Add New Nick Name" link is still available on following pages where user is not able to select another Nick Name(because according to functionality User must use same nick name which he/she have selected at the time of Topic submission)

Please refer screenshot for more details

1.Create New Camp
![image](https://user-images.githubusercontent.com/40416610/46199477-c96ad800-c32c-11e8-808b-405a341cc4c0.png)

2.Supported Camps
![image](https://user-images.githubusercontent.com/40416610/46199543-f28b6880-c32c-11e8-9605-c47520070778.png)

3.Camp Forum
![image](https://user-images.githubusercontent.com/40416610/46199580-0a62ec80-c32d-11e8-990c-c93a3f725e50.png)

4.Add Camp Statement
![image](https://user-images.githubusercontent.com/40416610/46199725-5dd53a80-c32d-11e8-8ec2-d422b3895045.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 retest..

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
Please remove the link form Forum Posts page also,refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/46244686-4fa41e80-c400-11e8-8aec-29f9e71345f7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its fixed. Retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks After thread post editor changes deployment user can see the  "Add New Nick Name"  link on thread posts page even if nick name is selected already.
Please refer attached screenshot for details
Please do the needful
![image](https://user-images.githubusercontent.com/40416610/46487173-064b3900-c81d-11e8-9878-29a1b32393b7.png)

**Comment by gautamv16** [comment]
@ash please check this. Remove Add New Nickname if user have added at least
one nickname in his account.

**Comment by akuks** [comment]
Done. Changes pushed to Development branch.

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks Retested and verified.
