### ISSUE TITLE
Incorrect escaped special characters in forum data.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#217]
@gautamv16, @akuks, @rupalichavan9860,

As can be seen on this forum page:

http://production.canonizer.com/forum/88-Theories-of-Mind-and-Consciousness/6/threads/77

There are still some incorrect escaped special characters in the old forum data.

i.e.: ...does something like prove â€œproperty dualismâ€ is epiphenomenal.

Can we get this fixed, ASAP?

Thanks,

Brent

**Comment by akuks** [comment]
@BrentAllsop, We will check this and let you know

**Comment by gautamv16** [comment]
@BrentAllsop  @akuks i have fixed this. Please test

**Comment by BrentAllsop** [comment]
Yup, looks nice.
Thanks.
