### ISSUE TITLE
Incorrect page title on Forgot Password Page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#218]
Steps to reproduce : 

1. Go to https://staging.canonizer.com or http://production.canonizer.com
2. Click on Log in
3. Click on "Forgot Password" link

Expected Result : 

Page title should be "Forgot Password" instead of "Forget Password"

Actual Result : 

![image](https://user-images.githubusercontent.com/40416610/43043109-638eb4ec-8da9-11e8-8c8b-1e63880d3186.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified.
