### ISSUE TITLE
"Sign In" link on Thread posts is redirecting to incorrect page after log in

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#219]
Steps to reproduce : 
1. Go to http://production.canonizer.com/ or https://staging.canonizer.com/
2. Without login click on Browse
3. Select any topic who have threads
4. Click on "Camp Forum"
5. Click on any thread form List of all threads
6. Click on "Sign In" link 
7. Login with valid email and password

Expected Result : 

After login it should redirect to thread posts page where use can reply to the thread

Actual Result :  

It is redirecting to "Canonizer Main Page"

**Comment by akuks** [comment]
@rupalichavan9860 Please test this issue in staging environment

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.It is redirecting to respective page now
