### ISSUE TITLE
Page crash/Query Exception on production Browse page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#225]
Steps to reproduce : 
1. Go to http://production.canonizer.com/
2. Go to Browse
3. Select "as of (yy/mm/dd)" from As Of filter
4. Put date "28/07/2010" in text box
5. Press Enter key on keyboard

Actual Result : 
Page crash/Error Exception
![image](https://user-images.githubusercontent.com/40416610/43062942-0393008c-8e78-11e8-9412-3234e96605c3.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check this.This issue is exists on staging also

**Comment by gautamv16** [comment]
@rupalichavan9860 please check and verify ASAP

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
