### ISSUE TITLE
Page Crash/Error Exception on Canonizer Forum Details page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#226]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/ or http://production.canonizer.com/
2. Login with valid Email and Password
3. Go to Browse
4. Select any topic 
5. Click on "Camp Forum"
6. Select "as of (yy/mm/dd)" from As Of filter
7. Select old date like "2008/07/01" in text box 
Actual Result : 
Page crash.

![image](https://user-images.githubusercontent.com/40416610/43066044-3ac3725e-8e81-11e8-8c41-8f59315c4036.png)

**Comment by akuks** [comment]
@rupalichavan9860, The exception is correct on this. Because "As of Filter" is not for the forums. Keep this issue open, we will discuss this in the meeting.

**Comment by rupalichavan9860** [comment]
@akuks Okay.Sure

**Comment by gautamv16** [comment]
@rupalichavan9860 @akuks please check this solved. Yes this feature is not for forum . But error is coming because there are empty camp data forwarded, solved it, please check.

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks Retested and verified.Working fine now
