### ISSUE TITLE
"under review" messages need to be fixed.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#232]
@gautamv16, @rupalichavan9860, @CanonizerJim 
When I submitted a change to a topic record, I got this message:

"Success! Topic update submitted successfully. Its under review, once approved it will be live."

All messages like this (for topics, camps, statements...) should be changed to be this:

"Topic change submitted successfully.  If no direct supporters object to this change, it will go live on <go live date/time>"

Jim, is this the best way to say this?

**Comment by CanonizerJim** [comment]
Yes. At least, it’s better than the existing language you received, which has some grammar problems.

**Comment by gautamv16** [comment]
@rupalichavan9860  please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested. Success message is displaying **"Success! Topic change submitted successfully."** But according to previous discussions All messages like this (for topics, camps, statements...) should be changed to be this:**"Topic change submitted successfully. If no direct supporters object to this change, it will go live on <go live date/time>"**

@BrentAllsop Please confirm

**Comment by gautamv16** [comment]
Here, if topic is going be live in future then date will come, if its
already live then only change message will come as we dont have any future
live data in that case. So its not an issue.

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested for topic which will be live in future.Working fine but there is mismatch in dates.Please find screenshot and confirm
![image](https://user-images.githubusercontent.com/40416610/43893577-0e687c44-9bed-11e8-87bd-dd367d6851b4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test and close issue

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified. It is working fine for Topic.
Please fix this for camp also
Please refer attached screenshot for details
![image](https://user-images.githubusercontent.com/40416610/43990685-68bf95fc-9d7c-11e8-8e17-3976eb32e1b4.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Please fix this time issue in respective mails also.
Please refer screenshot
![image](https://user-images.githubusercontent.com/40416610/43990853-2782c886-9d7f-11e8-8e3f-53b3c208be7c.png)
![image](https://user-images.githubusercontent.com/40416610/43990864-3c58c756-9d7f-11e8-959a-6aa91ab48d67.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  camp and statement history page time fixed. And for email timing i have removed time as its not possible to pass local time zone which we are using on browser based i.e client side as its rendering it dynamically. So there is only a message that it will go live in 1 week. On the email we cant use the unix time based on browser timezone as email is not rendering from browser.

So if those camp and statement fixed please close the issue for release.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified.
