### ISSUE TITLE
Edit camp parent.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#233]
We must be able to edit the parent of a camp.
Needs to be a drop down selector of all available camps for a topic.
Default to current value.

**Comment by gautamv16** [comment]
@BrentAllsop need discusion on this. Its not clear to me.

**Comment by BrentAllsop** [comment]
@gautamv16,

When you edit a camp, you can currently change or set the following fields in a camp record:
Camp Name
Keywords
Additional Note
Camp About URL
Camp About Nick Name

You also need to be able to edit or change the Parent camp field in this record.
It should default to the current camp, but have all other camps in the topic as selectable parent camps.
In other words, this is how you change the camp outline structure in a topic.

**Comment by gautamv16** [comment]
@rupalichavan9860  @BrentAllsop  please test

**Comment by BrentAllsop** [comment]
@rupalichavan9860, @gautamv16 
Nice, verified it is working in development.canonizer.com
I was able to change a camp's parent camp.
Looking forward to seeing this in production.

**Comment by BrentAllsop** [comment]
Ah, missed an additional issue related to this.
The parent camp needs to be indicated in the record history.
Notice the parent camp field isn't indicated in any of these historical records:

https://canonizer.com/camp/history/88/63

**Comment by BrentAllsop** [comment]
I see this is ready in staging.
But there is one additional feature i think would be nice.
You should be able to change the parent camp, when creating a new camp.
The default value should be the camp from which you pressed the create new camp button, but you should be able to change it, if you want to.

**Comment by gautamv16** [comment]
@BrentAllsop this feature done.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and this feature is available now.
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
Looks great, so closing this issue.
