### ISSUE TITLE
UI is not proper on Camp Statement History page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#235]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Select any topic and click on "Manage/Edit Camp Statement"
4. Observe page

Expected Result  : 

1.Gap between "Statement" and "Note" should be uniform like other fields on the page.
2."Go live Time" should display like "Go live Time : 09/08/2018, 14:35:42" .Remove ";" 

Actual Result :  
1. Extra gap is displaying between "Statement" and "Note" 
2. As of now it is displaying  Go live Time" as "Go live Time : 09/08/2018, 14:35:42;"

![image](https://user-images.githubusercontent.com/40416610/43889805-bf514d0c-9be2-11e8-9b35-6c4d01e01611.png)

**Comment by gautamv16** [comment]
2. Time is not any issues its 24 Hrs format over all. So its not an issue
here.

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check this on "Topic History". It looks good
![image](https://user-images.githubusercontent.com/40416610/43893711-85db01d4-9bed-11e8-82b8-34c44e1ba212.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Even on Camp History. This issue is exists only on Camp Statement History and only for "Go live Time"

**Comment by gautamv16** [comment]
Dont know what issue you are talking. Its date format and its showing
correctly as per the camp timings and topic. There is flow of go live time
after 1 week qnd its showing date and time according to local timezone.

**Comment by rupalichavan9860** [comment]
It's just UI issue.I just want to say remove extra semicolon which is present at the end of the date .Please check screenshot

**Comment by gautamv16** [comment]
@rupalichavan9860 test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
