### ISSUE TITLE
Regarding page title for statement update

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#236]
Steps to reproduce : 
 1. Go to https://staging.canonizer.com/
 2. Login with valid Email and Password
 3. Go to Browse
 4. Select any topic and click on "Manage/Edit Camp Statement" on Agreement page
 5.Click on "Submit Statement Update Based On This"

Expected Result : 
Page title should be "Statement update"

Actual Result : 
As of now page title is displaying as "Submit update"

 Please confirm?

![image](https://user-images.githubusercontent.com/40416610/44000009-96932a02-9e35-11e8-842e-a0657767f5f7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.But I think 'u' from 'update' should be in capital letter for uniformity.
I just checked title for other pages and observed title names are like "Create New Topic","Create New Camp","Manage Topic","Topic History" etc
So this also should be uniform
1.It should be "Statement Update" instead of "Statement update"
2.And for camp update also title should be "Camp Update" instead of "Camp update"
Please clarify.
And if current title is fine I will close this issue
![image](https://user-images.githubusercontent.com/40416610/45023413-086e7c00-b054-11e8-9bf3-4cd1a748c58f.png)
![image](https://user-images.githubusercontent.com/40416610/45023450-1f14d300-b054-11e8-8f57-472c5e46321f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 done pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
