### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#237]
https://staging.canonizer.com/statement/history/211-ComputerSE-A-By-RN/1

**Comment by gautamv16** [comment]
@rupalichavan9860 please check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Issue is still exists but now it is displaying "HTTP ERROR 500" when you click on "ComputerSE-A-By-RN" topic on Browse page

![image](https://user-images.githubusercontent.com/40416610/44298486-8bc46980-a301-11e8-886a-111203515bf5.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Same issue is exists when I am opening topic from "Proposed change to Agreement submitted" email
Even exists when I am clicking on link in 
"Proposed change to camp statement #1370 submitted" email

Steps to reproduce : 
1.Go to https://staging.canonizer.com
2. Login with valid email and password.
3.Click on any topic
4.Click on "Manage/Edit This Topic"
5.Click on "Submit Camp Update Based On This"
6.Do some changes and click on "Submit Update" button
7.Open mail  "Proposed change to Agreement submitted" and click on link


![image](https://user-images.githubusercontent.com/40416610/44298633-27ef7000-a304-11e8-8e26-cc9b49d5d6ce.png)
![image](https://user-images.githubusercontent.com/40416610/44298661-b106a700-a304-11e8-8615-f081926c4aeb.png)

![image](https://user-images.githubusercontent.com/40416610/44298721-b4e6f900-a305-11e8-8745-5512cce6ed7e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please check this. This issue arises due to parent camp drop down newly built. As per flow we cant change Root camp parent any how, buts system allowing it to change and then complete structure got messed.

Please test same scanario too and these camp issue too. If any of othe test camp have this same issue then its parent association issue. You cant change root camp parent.

Now system will not allow you to change parent camp of Agreement root camp. test this same case too.

This one is good catch and it takes good time to find out the cause......

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested
1.Root Camp parent : this issue is working fine for root camp parent as we can't change root camp parent 
2.Child Camp : Create a child camp using <Start new supporting camp here>under root camp and try to update this camp by selecting different values from "Parent Camp" drop down.Now it is displaying "HTTP ERROR 500" on Submit update/View this version and when opening link from respective mail(proposed a change to this camp)

**Comment by rupalichavan9860** [comment]
@gautamv16 This issue is exists for Child camp.Please refer following steps to reproduce this
Steps to reproduce : 
1.Go to https://staging.canonizer.com
2.Login with valid Email and Password
3.Select any topic or create new topic
4.Go to Agreement page and Click on Start new supporting camp here
5.Enter in all fields and click on "Create Camp" button
6.Click on "View This Version" and support this new camp
7.Click on "Submit camp update based on this" 
8.Select any parent camp from "Parent Camp" drop down except "Agreement" and change other mandatory fields on camp update page
9.Click on "Submit Update" button
10.Click on "View This Version" 

Refer this link : https://staging.canonizer.com/topic/246/3?asof=bydate&asofdate=2018/08/27%2004:58:01

Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/44321141-dcec6e80-a463-11e8-9751-eb02022df6d0.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please check and test. Dont use above url as it has wrong dates and time selection. Test it from the flow.

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested for fresh topic with the flow,but if I am trying to update any camp and if I am trying to select same camp from Parent Camp drop down as a Parent Camp this issue is occurring.

Need to discuss this

**Comment by gautamv16** [comment]
@rupalichavan9860 check it for same camp solution, made some changes.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working now
