### ISSUE TITLE
Fatal Error Exception

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#238]
I am getting fatal error exception when click on link from "proposed a change to this camp" mail.
Steps to reproduce : 
1.Go to https://staging.canonizer.com/
2.Login with valid Email and Password
3.Open any topic who have child camps
4.Click on child camp from "Canonizer Sorted Camp Tree"
5.Click on "Manage/Edit This Camp"
6.Click on "Submit Camp Update Based On This" and do some changes in fields
7.Click on "Submit Update" button
8.Open link from respective mail

Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/44302699-23e74080-a34c-11e8-8066-019a58157e61.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test again with the flow. Dont use old email and tested data.

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested for fresh topic with the flow,but if I am trying to update any camp and if I am trying to select same camp from Parent Camp drop down as a Parent Camp this issue is occurring.

Needs to discuss this

**Comment by gautamv16** [comment]
@rupalichavan9860  can you please check it for that solution now. I made some changes.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working fine now
