### ISSUE TITLE
Add new topic name_space system.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#24]
Create a new table containing records of hierarchical name spaces.
Each topic should belong to a namespace (in 1.0 system null name space represents "general")
Add administrator abilities to create new name spaces.
pre populate the table with the values from the name_space fields, ad update topics to reference these namespace records.

**Comment by gautamv16** [comment]
Admin panel dashboard is left from where admin can approve namespaces or can add new namespace.

**Comment by gautamv16** [comment]
Done
