### ISSUE TITLE
Upload File issue on production environment 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#241]
Steps to reproduce : 
1. Go to https://production.canonizer.com
2. Login with valid Email and Password
3. Go to Upload File
4. Try following scenarios
               1.Try to upload file greater than 2 MB 
               2.Try to upload file greater than 5 MB

Expected Result : 
1.File should get uploaded successfully
2.It should display error message "Error! The file may not be greater than 5 MB. "

Actual Result : 
It is displaying error message "Error! The file failed to upload." for both scenarios
![image](https://user-images.githubusercontent.com/40416610/44480080-fa862780-a65f-11e8-897d-ed4dd11295cd.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 .txt file is getting uploaded on both staging and production.
Steps to reproduce : 
1.Rename any .jpg file to .txt and upload 
2.Upload the .txt file
Please refer following screenshot
![image](https://user-images.githubusercontent.com/40416610/44521584-2c939a00-a6f1-11e8-9551-59bf0d05c441.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.As per discussion it is a production server issue so I am closing this

**Comment by saniatg** [comment]
@gautamv1 Not able to upload 5mb file on Production . The same file works on staging.

Attaching the sample file as well

![Screenshot 2021-10-22 at 2 27 26 PM](https://user-images.githubusercontent.com/91254708/138426563-93f10007-8af0-45b7-a60c-4748ead51c93.png)
![Sample-Image-file-Download](https://user-images.githubusercontent.com/91254708/138426648-d2faed28-40e2-4b06-91b3-1b5c3526d7bb.jpg)

**Comment by rupalichavan9860** [comment]
Tested and verified
