### ISSUE TITLE
When user clicks on any camp of Canonizer Sorted Camp Tree on blog page it is redirecting to https://canonizer.com

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#242]
Steps to reproduce : 
1.Go to https://production.canonizer.com
2. Login with valid Email and Password
3.Go to Blog
4.Open any blog and go to bottom part(Canonizer Sorted Camp Tree)
5.Click on any camp from Camp tree

Expected Result : 
It should redirect to respective production site agreement page 

Actual Result : 
As of now it is redirecting to agreement page of https://canonizer.com

![image](https://user-images.githubusercontent.com/40416610/44513509-2db9cc80-a6db-11e8-90a8-2650b494906c.png)
Click on "Education-Is-Important" camp
![image](https://user-images.githubusercontent.com/40416610/44513553-432ef680-a6db-11e8-8c1b-4088538101f5.png)

**Is it an issue?Please confirm..**

**Comment by gautamv16** [comment]
Its not an isssue
