### ISSUE TITLE
UI got disrupted when the URL https://canonizer.com/index.php is called

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#243]
UI got disrupted while calling the URL https://canonizer.com/index.php.
Tested on Chrome. 

![image](https://user-images.githubusercontent.com/12954663/44726547-99de6b00-aaf5-11e8-8751-e47a9e2e7fa5.png)

**Comment by gautamv16** [comment]
@akuks please check and close.

**Comment by akuks** [comment]
Working fine. Closing the issue.
