### ISSUE TITLE
Posts to forums must send e-mail to all direct supporters of that camp, and all sub camps.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#246]
I've added the description of the content of this e-mail to the Canonizer Email google docs:

To Direct supporters when a post is made to a camp forum.

https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit?usp=sharing

**Comment by akuks** [comment]
Email functionality is added and deployed on staging. @BrentAllsop @rupalichavan9860 Please test it.

**Comment by rupalichavan9860** [comment]
@akuks Functionality is working so closing this
