### ISSUE TITLE
Incorrect validation on Register page for Middle Name

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#247]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Click on Register
3. Enter valid data in all mandatory fields and keep Middle Name as blank as it is non mandatory
4. Click on "Create your account" button

Expected Result : 
User should get registered and user should see canonizer main page 

Actual Result : 
User is not getting registered and It is displaying error message "The middle name must be a string."
Please refer following screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/45085503-767f7580-b11e-11e8-8e85-5c39538aab89.png)

**Comment by rupalichavan9860** [comment]
This error message is also displaying when trying to click on "Create Your account" without entering into any field
Scenario :  
Without entering into any field directly click on "Create your account" button on register page
refer screenshot for details

![image](https://user-images.githubusercontent.com/40416610/45110924-3f7e8380-b161-11e8-92d2-67ff230e6d5d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please check this..

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
