### ISSUE TITLE
Regarding page title when user click on Add Camp Statement button

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#248]
Steps to reproduce :

1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Go to Browse
4. Select any topic and click on "Add Camp Statement" on Agreement page

Expected Result :
Page title should be "Add Camp Statement" or "Create Camp Statement"

Actual Result :
As of now page title is displaying as "Submit Statement".Button name is also "Submit Statement"

Please confirm?
![image](https://user-images.githubusercontent.com/40416610/45350241-eaaf9280-b5d0-11e8-82da-eeb0d44a332f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
