### ISSUE TITLE
UI issues on Change Password page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#253]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Account Settings
4. Click on Change Password
5. Observe Change Password page

Expected Result : 
1. Change Password page title name should be "Change Password"
2. Label names should be uniform like "Enter Old Password","Enter New Password" and "Confirm Password"

Actual Result : 
1. Page title is displaying as "Nick Names"
2. Label names are displaying as "Enter old password","Enter New password","Confirm password"

Please make every first letter of all label capital or only First letter capital.
For uniformity Please make it like expected result like labels on "Manage Profile Info" page
Please refer screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/45467610-1e5bfb00-b73e-11e8-8282-aa15b3bf514d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
Please change error message for "Enter current password" field to "The current password field is required." instead of "The old password field is required."
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/45527725-c636fe80-b7fa-11e8-8b9e-f009c9666c9f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 solved fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
