### ISSUE TITLE
Incorrect error message on Change Password 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#254]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on "Change Password"
5. Enter incorrect password in "Enter old password" text box and enter valid data in "Enter New password" and "Confirm password" text boxes

Expected Result : 

Error message should be "Error! Incorrect Old Password." 
Or Change label name to "Enter Current Password" instead of "Enter old password"

Actual Result : 
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/45467813-28322e00-b73f-11e8-9972-8fa9d0fd056e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.Closing this
