### ISSUE TITLE
Page is redirecting to change password page when user logged in after successful password change

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#255]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on Change Password
5. Enter valid data in all fields and click on Save button
6. Now this will redirect to Login page
7. Login with email and changed password

Expected Result : 
User should redirect to Canonizer home page 

Actual Result :  
User is redirecting to Change Password page instead of Canonizer home page

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check this issue.

**Comment by gautamv16** [comment]
@rupalichavan9860 test it

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
