### ISSUE TITLE
Old style URLs bad and not working.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#256]
There are two issues contained in this report.

#1 old URLs, of the format: http://canonizer.com/topic.asp/88/6 do not work.
There are lots of these on the internet, like on this quora page:
https://www.quora.com/What-exactly-are-qualia
so it would be nice to get them working, redirect or something.

#2 There are a bunch of topics in the old data that had these old style links in them.
It looks like they've been changed  (an attempt to fix them?), but they are really broken, and they don't work.
For example the links on this important camp page:
https://canonizer.com/index.php/topic/105-Consciousness-Srvy-Prjct/1

**Comment by BrentAllsop** [comment]
We should find and fix all of these.

**Comment by gautamv16** [comment]
@BrentAllsop this link is working. 

For example the links on this important camp page:
https://canonizer.com/index.php/topic/105-Consciousness-Srvy-Prjct/1

And we must have to find old url which have topic.asp because if there is .asp extension in url it will not work.

**Comment by BrentAllsop** [comment]
@gautamv16,
Yes.  There are many links arround the internet that use the .asp format I was hopping we could make work.
Can we not make old format .asp links work?

Also, some of the links on this page:
https://canonizer.com/index.php/topic/105-Consciousness-Srvy-Prjct/1
in particular this one:
Theories of Mind and Consciousness:  https://canonizer.com/index.php/index.php/topic/88
which are not formatted correctly in either the 1.0 or 2.0 system.
But these links were working in the 1.0 system, so something must have changed them?

**Comment by BrentAllsop** [comment]
Hmm, it looks like the canonizer.com URLs in most camps are bad?
For example, the URLs in this camp.
https://canonizer.com/index.php/topic/132-Help/1

https://canonizer.com/index.php/index.php/topic/73-wiki-text/1

**Comment by gautamv16** [comment]
@BrentAllsop  please test and close. Developed a new way for all old style url to work according to newer one.

**Comment by BrentAllsop** [comment]
Looks great.

**Comment by BrentAllsop** [comment]
Re opening this, as it appears there are still issues with URLs like this:
http://canonizer.com/index.php
Sometimes these are showing up in google searches.
If you have index.php in the URL, some of the links, like the blog link, and the link to the white paper don't work.
We should redirect all such URLs to the same, without the index.php:
http://canonizer.com/

**Comment by gautamv16** [comment]
@BrentAllsop its solved now again. We dont need to touch our server htaccess.

**Comment by BrentAllsop** [comment]
Lookin good, so closing this issue.
