### ISSUE TITLE
Incorrect error message on Change Password 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#258]
Steps to reproduce :

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on "Change Password"
5. Enter valid password in "Enter current password" text box and enter same password in "Enter new password" and "Confirm password" text boxes
6. Click on "Save" button

Expected Result : 
Error message should be "The new password and current password must be different."

Actual Result :
Error message is displaying as "The new password and old password must be different."
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/45743784-7bfab680-bc1a-11e8-9a84-7a750ce6e2cc.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 test it

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
