### ISSUE TITLE
special characters in the statement text are all messed up. 

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#26]
Here is just one example of a snippet of text in this camp:

https://canonizer.com/canonizer2.0/public/topic/88-Macro-Material-Property-Dualism/36

" In the idealized theory world, this would be â€˜â€™â€™glutamateâ€™â€™â€™. For grenness, weâ€™ll say itâ€™s another random neurotransmitter like say â€˜â€™â€™glycineâ€™â€™â€™."

These values were just fine in the 1.0 version, so we need to figure out if the data has been corrupted, from the original, or why it worked in the 1.0 version, and find some way to find and clean all these up in all versions of all camp statements.

**Comment by gautamv16** [comment]
@BrentAllsop after investigating the issue, i found that data of latest version statement is in this format in our database which you sent us earlier. So these camps data is corrupted and need add such content again. So lets discuss what will be the process for it and who will do it.
