### ISSUE TITLE
Add Markup for Forum Posts

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#260]
Add Markup for forum posts to make posts more elegant.

**Comment by BrentAllsop** [comment]
I'm thinking we should decide exactly what we are going to do here, before we spend time actually doing it.  For example, Do we want to use different markup than what the camps use...?

**Comment by akuks** [comment]
We will discuss this on Tuesday's (25th Sep 2018)  meeting and decide what needs to be done there.

**Comment by akuks** [comment]
Updated the Editor to the Fourm Posts.

**Comment by rupalichavan9860** [comment]
@akuks Functionality present and tested.
