### ISSUE TITLE
Object Button operation is indistinguishable from new version button.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#261]
@gautamv16, @rupalichavan9860 

When you press the object button, the resulting page looks almost identical to the "submit update based on this" button.

The object page should change in these ways:
* there should be no section for editing the statement.
* There should be no note section.
* The "submit update" button should read "Submit Objection"

When you press the "Submit Objection" it should not create a new record, it should just mark the object flag for that version, changing the color of that record from yellow to red.  It should also add the object reason field to the record being objected, not a new record.

**Comment by BrentAllsop** [comment]
The way it currently works, the record being objected to would still go live after one week right?  Only the new record would not go live?

**Comment by gautamv16** [comment]
@BrentAllsop please check this one, re-developed accordingly.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working accordingly,But the page title should be different

It should be "Statement Object" or any other respective title instead of "Statement Update".
And I think "Your Objection Reason" should be mandatory.As of now "Your Objection Reason" field is non-mandatory.Is it fine?please confirm

**Comment by gautamv16** [comment]
Title is update because we are updating it. It must not be object as its
already mention on button. And object reason is not mandatory as per record.

**Comment by rupalichavan9860** [comment]
Okay

**Comment by rupalichavan9860** [comment]
@BrentAllsop I have tested this and looks good to me . Please check this and close if fine for you

**Comment by BrentAllsop** [comment]
@rupalichavan9860 @gautamv16 
I'm in Rupali's camp on these.
I think an update operation in canonizer.com, is something that creates new version of the record, containing the update.  Objecting to an update, is very different than an update.

I think the object reason should be required, when objecting.

The current label is: "<camp/topic/statement> update" but I think it should instead say:
"Object to this proposed update"

**Comment by gautamv16** [comment]
@BrentAllsop  and @rupalichavan9860 please retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
Expected Result : 

1. "Object to this proposed update" should display only one button i.e "Submit Objection"
2. Error message for "Your Objection Reason " should be "The objection reason field is required."

Actual Result : 

Please refer attached screenshot for more details : 
1. "Object to this proposed update" is displaying 3 buttons "Submit Objection","Submit Update" and "Cancel"
![image](https://user-images.githubusercontent.com/40416610/46244467-d22adf00-c3fc-11e8-8447-6abea4ef8029.png)

2. "Submit Objection" and "Submit Update" are working as one button.Error message is displaying as "The object reason field is required."
![image](https://user-images.githubusercontent.com/40416610/46244525-b7a53580-c3fd-11e8-87e4-ba879174794f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  its fixed. Retest...

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
Error message for "Your Objection Reason " should be "The objection reason field is required."

**Comment by gautamv16** [comment]
@rupalichavan9860  please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
