### ISSUE TITLE
Camp outline arrow default setting is wrong when there is sub structure.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#262]
@gautamv16 @rupalichavan9860 

When you first open a page with lots of structure, like this one:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1
All the arrows point the right, indicating the sub structure is not open, when it is open.
The first time you click it, it changes the arrow, but does not close the structure.
Only on the second click, does the arrow go back to the right, and the substructure close.

As a feature, it would be nice if we could remove the arrows when there is no sub structure - no use having button clutter, when it does nothing.  (will also better indicate no structure).
An exception should be when you are on a camp, with  no sub structure.  You do have the <Start new supporting camp here> sub structure, so in that case, there should be an arrow so you can hide that, as it does now.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I already added this issue but as per Varun it was not an issue and it was closed.
Please refer closed issue 151

**Comment by BrentAllsop** [comment]
Oh, yea, I seem to vaguely recall something like that.  Sorry I missed it.
I added the duplicate flag to this one.
Is there are better way to link this to issue 151, than just set the duplicate flag, and reference 151 here?

**Comment by rupalichavan9860** [comment]
Okay.No issues.Just setting the duplicate flag is fine :)

**Comment by rupalichavan9860** [comment]
Let keep this open because issue 151 was marked as invalid and closed.

**Comment by BrentAllsop** [comment]
Not fixed yet.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test this

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working now.
@BrentAllsop Can you please verify and close this issue if fine for you?

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Arrow are working fine now but I have one doubt.Because of this fix if I click on leaf node of any camp I can see slight change in line layout.Layout should be proper.Please let me know your thoughts.
Please refer following screenshots for more details
Staging : 
![image](https://user-images.githubusercontent.com/40416610/50109452-ddecab80-025d-11e9-8ab0-ff7afc150156.png)

live : 
![image](https://user-images.githubusercontent.com/40416610/50109517-11c7d100-025e-11e9-8c8f-49677363e10b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 solved please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
