### ISSUE TITLE
Footer contents on canonizer emails are different than other pages of Canonizer

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#263]
I think footer contents at all places should be same.Please confirm?
Canonizer footer contents : 
![image](https://user-images.githubusercontent.com/40416610/46225356-93524600-c376-11e8-86b5-edf98744f29b.png)

Canonizer email footer contents  : 
![image](https://user-images.githubusercontent.com/40416610/46225390-aa913380-c376-11e8-80d7-6c7320592ce9.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed and changed all templates of emails..

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
