### ISSUE TITLE
"Submit Statement" button is not working properly on Add Camp Statement page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#264]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Open any topic  or create new topic
4. Create new camp
5. Click on "Add Camp Statement"
6. Enter valid data in "Statement" field
7. Without entering into "Note" field click on "Submit Statement"

Expected Result : 
It should display error message "The note field is required." without clearing data entered in "Statement" field

Actual Result : 
 As of now data entered in "Statement" field is getting clear.User again needs to write the same data again and this will be time consuming if user wants to enter long statement
This functionality is working fine on "Statement Update" page

**Comment by gautamv16** [comment]
@rupalichavan9860 please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine now.
