### ISSUE TITLE
Validations are missing for Your Objection Reason field on Object to this proposed update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#266]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid username and password
3. Go to browse
4. Select any topic
5. Click on Manage/Edit Camp Statement
6. Click on "Object"
7. Enter more than 300 characters in "Your Objection Reason" field
8. Click on "Submit Objection" button
9. Observe recently objected record on "Camp Statement History"

Expected Result : 
Your Objection Reason field should have some limit on character length.
"Submit Objection" button should display error message for max character limit

Actual Result : 
Your Objection Reason is accepting large number of data and UI is getting disturbed on "Camp Statement History"

Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/46256336-efc47b00-c4c6-11e8-8011-951e2e3d39d1.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please check.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
