### ISSUE TITLE
Camp Statement History page is displaying mismatch in Go Live Time

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#267]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Browse
4. Select any topic and go to "Manage/Edit Camp Statement"
5. Click on "Object"
6. Enter in all mandatory fields and click on "Submit Objection" button

Expected Result : 
Go Live Time in success message and objected record should be match

Actual Result : 
As of now success message go live time and objected record go live time on "Camp Statement History"  is displaying different
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/46276854-09c19480-c57f-11e8-8721-06b06cf2b4e4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its working please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
