### ISSUE TITLE
"Statement preview" pop up and Camp Statement History page UI is not proper when user enters long statement and note

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#269]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Add Statement" or "Manage/Edit Camp Statement"
5. Click on "Submit Statement Update Based On This"
6. Enter long data in Statement and Note field(refer attached screenshot for data)
7. Click on "Preview" button and Observe page
8. Click on "Submit Update" button
9. Observe "Camp Statement History page"
 
Please refer attached screenshot for more details
Actual Result : 

![image](https://user-images.githubusercontent.com/40416610/46366687-644f1380-c699-11e8-8a18-2e0e6132eeaf.png)

![image](https://user-images.githubusercontent.com/40416610/46366724-7b8e0100-c699-11e8-97bd-9e2557568cb7.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Check this issue for very long statement without any space or break and observe Camp Statement on  Canonizer Sorted Camp Tree page
Refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/46625611-4595c480-cb52-11e8-84dd-c5974414abf8.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
