### ISSUE TITLE
People should be able to browse, everything, without logging in.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#27]
People (and especially search robots) should be able to browse, everything, without having to log in.
They should only be required to log in, any time they want to make a contribution of any kind.
If we don't know who they are, they should be operating as a "guest", and still be able to save session state (like their currently selected canonizer).

Once they log in, we should save a cookie indicating who they are.  Once their session times out, and if they return, they should still be able to have their preferences (such as default canonizer) operational, and be able to browse as themselves (rather than just a guest).  But, if they want to make any contributions, they will be required to provide their credentials, and change state to fully logged in, before they can submit anything.

**Comment by gautamv16** [comment]
Solved
