### ISSUE TITLE
"Updated camp record preview" pop up and Camp History page UI is not proper when user enters long Keyword, URL and note

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#270]
Steps to reproduce :
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Manage/Edit This Camp"
5. Click on "Submit Camp Update Based On This"
6. Enter long data in keywords, Additional Note and Camp About URL fields
7. Click on "Preview" button and observe UI
8. Click on "Submit Update" button 
9. Observe "Camp History" page
Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/46367826-47680f80-c69c-11e8-82a2-90b526f1ad8e.png)

![image](https://user-images.githubusercontent.com/40416610/46367864-623a8400-c69c-11e8-8281-45541d84bff6.png)

**Comment by rupalichavan9860** [comment]
Please check this issue on "Create New Camp" page also

**Comment by rupalichavan9860** [comment]
@gautamv16  Check this issue on "Current Camp Record:" section of Agreement page
![image](https://user-images.githubusercontent.com/40416610/46809469-28e4d100-cd8c-11e8-92ca-c7ca85a2c2b4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
