### ISSUE TITLE
UI is not proper on Topic History page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#271]

**Comment by rupalichavan9860** [comment]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Click on "Create New Topic" and Enter long data in "Additional Note" field
4. Click on "Create Topic" button and Observe Topic History page UI
5. Open any topic and click on "Manage/Edit This Topic"
6. Click on "Submit Topic Update Based On This"
7. Enter in all mandatory fields and enter long data in "Additional Note" field
8. Click on "Submit Update" and observe Topic History page UI

Refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/46368709-8303d900-c69e-11e8-8e98-c370546ffbeb.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
