### ISSUE TITLE
"Paste", "Paste as plain text", "Paste from word" are not working on CKEditor while posting reply to the thread

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#273]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Open any thread and type some text in "reply" field
6. Copy this text using editor "Copy" control
7. Now try to paste the copied text using editor "Paste", "Paste as plain text" or "Paste from word" 
icons

Expected Result : 
Copied text should get paste on the required location
Actual Result : 
For "Paste" icon
It is displaying error message "Your browser doesn't allow you to paste this way. Press Ctrl+V to paste."
For "Paste as plain text" icon
It is displaying error message "Your browser does not allow you to paste plain text this way. Press Ctrl+Shift+V to paste."
For "Paste from word" icon
It is displaying error message "Your browser doesn't allow you to paste this way. Press Ctrl+V to paste."
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/46403796-1da4fc00-c721-11e8-8ede-6c5ad9b781df.png)

![image](https://user-images.githubusercontent.com/40416610/46403833-33b2bc80-c721-11e8-8c42-df105e24b12f.png)

![image](https://user-images.githubusercontent.com/40416610/46403875-50e78b00-c721-11e8-91aa-67e6be3aa4e6.png)

**Comment by akuks** [comment]
Fixed and pushed to development branch
