### ISSUE TITLE
When user is trying to add image to the thread posts ,Image Preview is not getting loaded on Image Properties of CKEditor and image is not getting added

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#274]
Steps to reproduce :

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Open any thread and click on image icon on editor
6. Copy image URL from canonizer file upload page(short code) or try to load image from local machine(local machine URL)
7. Observe Image Properties page for preview
8. Click on "Ok" button

Expected Result : 
Image should get added 

Actual Result : 
Image preview is not getting loaded in preview section of "Image Properties" and image is not getting added in CKEditor
![image](https://user-images.githubusercontent.com/40416610/46404825-f26fdc00-c723-11e8-8ffe-9ae22abaadf5.png)

![image](https://user-images.githubusercontent.com/40416610/46405178-05cf7700-c725-11e8-8f61-acbd4d0d5e8f.png)

**Comment by akuks** [comment]
Fixed. And Pushed to dev Branch
