### ISSUE TITLE
Post is not getting displayed properly on thread posts in case of long data

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#276]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Click on any listed thread
6. Type long reply like below in reply field
"Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910Test12345678910"
7. Click on "Submit" button
8. Observe Thread posts page

refer attached screenshot for more details 

![image](https://user-images.githubusercontent.com/40416610/46415013-00ccf080-c742-11e8-9bc4-dcc3e2c2fb71.png)

**Comment by akuks** [comment]
Pushed to dev Repository.

**Comment by rupalichavan9860** [comment]
@akuks Retested and working fine now.Closing this issue

**Comment by rupalichavan9860** [comment]
@akuks Please check this issue in live environment
Please refer attachments for more details
![image](https://user-images.githubusercontent.com/40416610/46573765-7c83a300-c9b7-11e8-8569-f1f1638440c0.png)

**Comment by rupalichavan9860** [comment]
@akuks Check this issue for Summernote  "Paragraph Align Right " . UI is not displaying properly when you write any text with right alignment.
Please refer following screenshot
![image](https://user-images.githubusercontent.com/40416610/46574497-f28d0780-c9c1-11e8-8e93-ea7659a4f267.png)

After saving posts it display 
![image](https://user-images.githubusercontent.com/40416610/46574510-0c2e4f00-c9c2-11e8-9d43-6fd3d848e494.png)

**Comment by akuks** [comment]
@rupalichavan9860 It is working fine. Please check the following URL
https://staging.canonizer.com/forum/276-Topic-16/1/threads/413

**Comment by rupalichavan9860** [comment]
@akuks Please check this issue for following URL
https://www.canonizer.com/forum/192-Testing-1/1/threads/323

**Comment by rupalichavan9860** [comment]
@akuks I have retested this issue on live environment after 5th release deployment but still not fixed.Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/47777649-32be7c00-dd1b-11e8-8b71-f598d5101ed4.png)

**Comment by akuks** [comment]
Sorry, I missed out on this. Fixed.

**Comment by akuks** [comment]
This is for the old post that w already made but It will not appear in the our upcoming posts. Fixed

**Comment by rupalichavan9860** [comment]
@akuks I have tested this and still post is not displaying properly in case of long data.

**Comment by akuks** [comment]
Can you post the URL?

**Comment by rupalichavan9860** [comment]
https://staging.canonizer.com/forum/210-Testing---20-3-2019/1/threads/353

**Comment by rupalichavan9860** [comment]
@akuks This is working fine now.So closing this issue
