### ISSUE TITLE
Issues on Summernote editor

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#279]
Steps to reproduce :

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Click on any listed thread
6. Select "Style" from editor and compare it with summernote editor

Expected Result : 

"Blockquote" and "Code" in canonizer thread posts editor should display like summernote and when user wants to write text using this styles it should save with "Blockquote" and "Code"

Actual Result : 
"Blockquote" and "Code" in canonizer thread posts editor is displaying different than summernote and when user write text using this styles, "Blockquote" and "Code" styles are not getting applied  for text.

Please refer attached screenshot

 1. "Blockquote" and "Code" in canonizer thread posts editor
![image](https://user-images.githubusercontent.com/40416610/46463249-1d6c3580-c7e1-11e8-8054-d8a21e03ab64.png)

2. "Blockquote" and "Code" in summernote 
![image](https://user-images.githubusercontent.com/40416610/46463455-8e135200-c7e1-11e8-9327-209812cbd7b8.png)

3. Text with "Code" style in canonizer thread posts editor
![image](https://user-images.githubusercontent.com/40416610/46463543-bac76980-c7e1-11e8-9bc2-3d845460be41.png)

4.  Text with "Code" style in summernote 
![image](https://user-images.githubusercontent.com/40416610/46463605-e5192700-c7e1-11e8-92cf-01aaa9a2f1d9.png)

5. Text with "Blockquote" style in canonizer thread posts editor
![image](https://user-images.githubusercontent.com/40416610/46463638-fb26e780-c7e1-11e8-92c6-df7cef3cfd46.png)

5. Text with "Blockquote" style in summernote 
![image](https://user-images.githubusercontent.com/40416610/46463666-0da12100-c7e2-11e8-8b39-f37f26b74874.png)

**Comment by akuks** [comment]
@rupalichavan9860 This is because you are checking the summernote on earlier version of bootstrap and in our application newer version of bootstrap (4) is used. It wouldn't match with the older version.
https://summernote.org/getting-started/ and go to For bootstrap 4. You will find our toolbar is similar to this one.

**Comment by rupalichavan9860** [comment]
@akuks Okay.Yes our toolbar is similar to this so I am closing this issue
