### ISSUE TITLE
Image is not getting displayed in thread posts email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#282]
Steps to reproduce :

1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on "Camp Forum" on "Canonizer Sorted Camp Tree"
5. Click on any listed thread
6. Add image and add some text reply field
7. Save post
8. Observe thread post email

Expected Result :
Added image should get displayed properly in thread post mail

Actual Result :
Irrelevant data is getting displayed in place of image in thread post mail but when user clicks on "view entire message" link image is not getting displayed(not even irrelevant data) but entered text is getting displayed properly.

Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/46488405-30eac100-c820-11e8-8a79-d289078aacfe.png)

![image](https://user-images.githubusercontent.com/40416610/46488421-3b0cbf80-c820-11e8-9834-c6e1ae7e0e39.png)

**Comment by rupalichavan9860** [comment]
@akuks As per discussed in meeting we are not going to use images on forum posts so image is turned off form toolbar.So I am closing this issue

**Comment by rupalichavan9860** [comment]
@akuks We have turned off image from toolbar but still user can directly drag image or paste screenshot in "Post Your Message Here" and submit post.
Need to fix this for thread posts emails

**Comment by akuks** [comment]
Fixed.

**Comment by rupalichavan9860** [comment]
@akuks Retested but still not working

**Comment by akuks** [comment]
Images are not valid to forums hence it it is invalid request

**Comment by rupalichavan9860** [comment]
@akuks Okay .I am closing this issue then
