### ISSUE TITLE
Preview for camp record missing "parent camp" field.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#283]
If you want to modify a camp record,
you can now do a preview on the record edit page, before submitting the change.

When you do a preview on any camp record, we need to show the "parent camp" field.

Also, when there is no "camp about" value, it previews with the "-- Select Camp About Nick Name --" value.  It should just be blank when there is no value.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
User can change the parent camp also on camp update page.I am trying to change parent camp and other things but on preview selected Parent Camp is not displaying(as of now it is displaying saved parent camp)
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/46942337-ba08c000-d08a-11e8-8f6f-54a686bf32f8.png)

**Comment by rupalichavan9860** [comment]
And " Related Nicknames :" in preview should display blank if no nick name selected.It should not display drop down.It is just a preview of what user has selected so user can't select or write anything on preview page
Actual Result:
It is displaying drop down
![image](https://user-images.githubusercontent.com/40416610/46942618-5a5ee480-d08b-11e8-8afd-e02378d07539.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 clear cache and test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
