### ISSUE TITLE
Need new page describing supporters of camps.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#285]
When you click on supporters of camp, it attempts to go to a URL like this:

https://canonizer.com/user/supports/1

But this fails, and just goes to the main canonizer page?

If this is an anonymous ID, it should only show what other camps this anonymous ID supports.

If it is a public ID, it should show all information for that user, the user has marked public, and all supported camps of all publick nick IDs for that user.

**Comment by gautamv16** [comment]
@rupalichavan9860 please create automated test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
