### ISSUE TITLE
Objection is not getting submitted when user is objecting to proposed changed for topic

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#288]
Steps to reproduce :

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on Manage/Edit this topic
5. Go to Not Live record on Topic History page
6. Click on Object
7. Enter valid data in all fields and click on "Submit Objection" button

Expected Result :
Objection should get saved and it should display objected record on Topic History page

Actual Result :
As of now it is not submitting objection and only page is getting refreshed

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
