### ISSUE TITLE
UI issues on page when user click on nick name link from Support Tree for "Agreement" Camp on agreement page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#289]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings and enter max length data in all the fields 
4. Go to Browse and select any topic
5. Click on Join or Directly support this camp
6. Click on nick name link
7. Observe page 

Expected Result : 
UI should be displayed properly.Data is not getting displayed fully

Actual Result : 
UI is getting disturbed for Address, City, State, Postal Code fields
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/46659277-3f472d00-cbd2-11e8-8d0b-facad8b47c85.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
