### ISSUE TITLE
"Once you pick a nick name, for any contribution to a topic, you must always use the same nick name for any other contribution or forum post to this topic" this functionality is not working for one scenario

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#291]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Create any topic (Refer topic- "Demo-10/10/2018" and submitter nick name is "Rupali C")
4. Now log out and login with another valid Email and Password
(Precondition : User should have at least two nick names)(Suppose nick names are "demousercanonizer1" and "demousercanonizer2"
5. Now open  "Demo-10/10/2018" topic created by nick name "Rupali C"
refer screenshot
![image](https://user-images.githubusercontent.com/40416610/46755439-b10e9c00-cce2-11e8-96e6-b75f1811b229.png)
6. Without supporting the agreement camp,directly create a new camp,here I can select any nick name from "demousercanonizer1" and "demousercanonizer2"(I have created " Test camp demo cano user" using nick name "demousercanonizer1")
![image](https://user-images.githubusercontent.com/40416610/46755622-25493f80-cce3-11e8-933f-6b8fac4c8d72.png)
7. Now without supporting this new camp try to create another camp or any other contribution,I must use "demousercanonizer1" because I am not able to see other nick name in drop down
![image](https://user-images.githubusercontent.com/40416610/46755846-bcae9280-cce3-11e8-8bc2-436186f21d5e.png)
8. But If I go to parent camp and click on Join or Directly support this camp,here I can select any nick name from "demousercanonizer1" and "demousercanonizer2"
![image](https://user-images.githubusercontent.com/40416610/46755975-08613c00-cce4-11e8-8ec4-a65158f8e120.png)
9. Here if I have selected "demousercanonizer2" and click on confirm
![image](https://user-images.githubusercontent.com/40416610/46756137-5d04b700-cce4-11e8-8342-e52be600386f.png)
10. Now again try to do other contribution to the topic,now I must use "demousercanonizer2" if I want to do any contribution to the topic
![image](https://user-images.githubusercontent.com/40416610/46756224-90474600-cce4-11e8-98ef-12947343d93b.png)

Expected Result : 
According to "Once you pick a nick name, for any contribution to a topic, you must always use the same nick name for any other contribution or forum post to this topic" this functionality once user picked a nick name for any contribution and If user click on " Join or Directly support this camp" ,user must use same nick name to confirm support also.

Please Confirm?

**Comment by rupalichavan9860** [comment]
Any updates on this?

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .This issue is not fixed yet. Please refer below screenshot
https://staging.canonizer.com/camp/history/293-Test-Topic-issue-291-retest/2-Test-camp-1 this camp is created by user "RC" but "RC" is not supporting yet.

![image](https://user-images.githubusercontent.com/40416610/111896443-a6be6380-8a3f-11eb-9381-6aa56b282334.png)

When user trying to support this camp user can see both nick names in drop down .It should display only "RC" as Once you pick a nick name, you must always use the same nick name for any contribution

![image](https://user-images.githubusercontent.com/40416610/111896456-bf2e7e00-8a3f-11eb-97f3-6ceee8c82815.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . This is working fine now for sub camp .But still I can see all nick names while supporting agreement camp.
 
When user trying to support the agreement camp , user can see both nick names in drop down .It should display only "RC" as Once you pick a nick name, you must always use the same nick name for any contribution
For all other contribution , I can see only "RC" 
![image](https://user-images.githubusercontent.com/40416610/111990325-35fb7200-8b39-11eb-89fd-b6dcb8308163.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 lets discuss this as i see its working fine. in the above camp mentioned by you The user having nickname  RC or Rupali C has not contributed yet thats why its showing all nicknames. the topic mentioned above is created by user having nickname "1rupali1".

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working now so closing this issue
