### ISSUE TITLE
Success message when submitting objection on camp statement should be  "Success! Objection submitted successfully."

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#292]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on Manage/Edit Camp Statement
5. Click on Object button on Live or Objected record on Camp Statement History page
6. Enter valid data in mandatory fields and click on "Submit Objection"

Expected Result : 
Success message should be "Success! Objection submitted successfully." like for topic objection having

Actual Result : 
Success message is displaying as "Success! Statement change submitted successfully."
![image](https://user-images.githubusercontent.com/40416610/46939865-0224e400-d085-11e8-81e2-ec3d3b5ba234.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
