### ISSUE TITLE
Page crash when user click on camp name link in thread post email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#294]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on "Camp Forum" on agreement page
5. Create a new thread or open any thread
6. Click on thread title
7. Submit post to the thread
8. Open Email 
9. Click on "demousercanonizer1 has made the following post to the Camp <Camp_name> forum:" camp name
10. Observe Page

Expected result : 
It should open respective page

Actual Result : 
Page crash
![image](https://user-images.githubusercontent.com/40416610/47017988-4a213500-d171-11e8-9aef-ccc121bd3748.png)

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16 Same issue I am getting in Thread creation mail->Camp name link

**Comment by akuks** [comment]
@rupalichavan9860 , Page is not crashing for all of the thread link. It crashes only where the topic Topic Name has "forward Slash".

**Comment by akuks** [comment]
@rupalichavan9860  It is not true for all the links, it is where the forward slash in included in the Topic Name. 
Url is encoded and pushed on the dev branch

**Comment by rupalichavan9860** [comment]
@akuks Yes. For other topics it is working fine.

**Comment by rupalichavan9860** [comment]
@akuks Retested and it is working now.Closing this issue
