### ISSUE TITLE
View This Version not working for Not yet live Versions.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#296]
I created a new version of the "eff the ineffable" camp on the live system:

https://canonizer.com/statement/history/102-Best-word-to-mean-communicating-that-which-is-ineffable/2

Notice that the live version will not go live till next week.

You should be able to press the "see this version" and view this version, as if it was live, or with an as of time for which it would go live, before it goes live.  Currently it looks like the version hasn't changed from what is currently live when you select "view this version".

**Comment by rupalichavan9860** [comment]
@gautamv16 I have also tested and not able to see the versions of Not yet live records

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 its fixed.

**Comment by BrentAllsop** [comment]
Yea, tested, and working so closing this.
