### ISSUE TITLE
Old format URLs, not working on live system.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#297]
This staging URL works:

https://staging.canonizer.com/topic.asp/53/11

But the live version:

https://canonizer.com/topic.asp/53/11

doesn't currently work.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 please create automated test. Its fixed.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Working for me. @BrentAllsop Please check and close if working

**Comment by BrentAllsop** [comment]
@rupalichavan9860, @gautamv16,

Yes, this is working now, so closing this issue.

**Comment by BrentAllsop** [comment]
This still isn't working completely.
This should work:
https://canonizer.com/topic.asp/105

This is the top result when you go to canoniazer.com, and do a google search on canoniazer.com for "Consciousness Survey Project"

Also, can we turn of robots.txt searches for production.canonizer.com and www.canonizer.com?

**Comment by gautamv16** [comment]
@BrentAllsop the issue of old url solved as per these search results. 
Please test such urls.

@BrentAllsop why we need to take off www.canonizer.com google indexing ?

**Comment by BrentAllsop** [comment]
Yes, this issue is fixed.
Will talk about indexing and robots.txt with issue #317,
so closing this issue.
