### ISSUE TITLE
Position of error message "Error! Incorrect Current Password." must be at field level 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#298]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on Change Password sub tab
5. Enter Invalid password in Current password field and enter valid and same passwords in New and Confirm password fields
6. Click on Save button

Expected result : 
Error message "Error! Incorrect Current Password." must be display at field level like other error messages
Actual Result : 
As of now error message "Error! Incorrect Current Password." is displaying at top of sub tab

**Because of this I am not able to pass automated test case for this scenario**

![image](https://user-images.githubusercontent.com/40416610/47932457-c351b380-def7-11e8-9491-6f9dced7a1e5.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its not an issue but still i changed it. According to me this error message must come at top as its a logical error not a field or requirement error. Please put it into automate test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.Automated test case is also working now.Thanks and closing this now
