### ISSUE TITLE
Current Password, New Password and Confirm Password must have Unique ID .

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#299]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on Change Password sub tab
5. Open Developer tool(Press F12 key)
6. Observe Console error

Actual Result : 
Current Password, New Password and Confirm Password are displaying as non-unique ID
Found this issue while  performing automated testing .Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/47932715-6a364f80-def8-11e8-93e5-8405fc25c23b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please do automate test for the same. Its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
