### ISSUE TITLE
Add date next to "Camp Statement" heading.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#300]
There is the "Camp Statement" block heading on camp pages.

It would be nice to have the go live date of the camp statement indicated after the "Camp Statement" block heading.

Brent

**Comment by gautamv16** [comment]
@BrentAllsop this feature has been added. @rupalichavan9860 pls test this one

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and Verified
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
Yes, this looks great, closing.
