### ISSUE TITLE
Error exception 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#302]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse
4. Select any topic 

Expected Result : 
It should open respective agreement page of topic

Actual Result : 
Getting Error exception

![image](https://user-images.githubusercontent.com/40416610/48388711-5a044880-e720-11e8-97f2-5701df9a875c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 solved

**Comment by rupalichavan9860** [comment]
@gautamv16 Working good so closing this issue
