### ISSUE TITLE
User is not able to select any namespace from namespace drop down except "Other"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#303]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Click on Create New Topic
4. Enter data in all mandatory fields and select any namespace from namespace drop down

Expected Result : 
User should able to select any namespace from namespace drop down value

Actual Result : 
User is not able to select any namespace from namespace drop down except "Other"

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check this issue on "Create New Topic" and "Topic Update" page

**Comment by gautamv16** [comment]
@rupalichavan9860 please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Working now
