### ISSUE TITLE
Error message for  Other Namespace Name should be proper on Topic Update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#304]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Browse
4. Select any topic
5. Click on Manage/Edit This Topic and click on "Submit Topic Update Based On This"
6. Select "Other" namespace from Namespace drop down
7. Click on Submit Update button

Expected Result : 
Error message should be "The Other Namespace Name field is required when namespace is other."

Actual Result : 
Error message is displaying as "The create namespace field is required when namespace is other."
refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/48431996-2dd8de00-e799-11e8-8dcd-12342960e97a.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Check this on Create New Topic page also and when user selects Other namespace from drop down field "Other Namespace Name" should marked with asterisk

![image](https://user-images.githubusercontent.com/40416610/48432333-16e6bb80-e79a-11e8-96b9-322691f25ce0.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Working now
