### ISSUE TITLE
Border is missing for Change Password tab 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#306]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on Change Password tab
5. Observe UI

Expected Result : 
When user clicks on Change Password tab user should see border like other tabs

Actual Result : 
Border is missing for Change Password tab 
![image](https://user-images.githubusercontent.com/40416610/48573311-d3bf5080-e931-11e8-90bd-7498a2362de6.png)

It should be like other tabs like following
![image](https://user-images.githubusercontent.com/40416610/48573351-f6ea0000-e931-11e8-9d60-87fc25aac769.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.Closing this issue
