### ISSUE TITLE
Error message is incorrect on Create New Topic page while creating new Namespace

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#307]
Steps to reproduce : 
1. Go to https://www.canonizer.com/
2. Login with valid email and password
3. Go to Create New Topic
4. Enter data in all mandatory fields
5. Select Other namespace from Namespace drop down
6. Enter existing name in Other Namespace Name field
7. Click on "Create Topic" button

Expected Result : 
Error message should be "Error: Namespace already exists"

Actual Result : 
Error message is displaying as "Error: Namespace already exsist"
![image](https://user-images.githubusercontent.com/40416610/48664251-c0db8600-eac1-11e8-93b5-6c6721e8ff4e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
