### ISSUE TITLE
Validation is missing for Other Namespace Name on Topic Update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#308]
Steps to reproduce : 
1. Go to https://www.canonizer.com/
2. Login with valid Email and Password
3. Open any topic
4. Click on Manage/Edit This Topic
5. Click on "Submit Topic Update Based On This"
6. Select Other Namespace from Namespace drop down
7. Enter existing namespace name in Other Namespace Name field
8. Click on "Submit Update" button
9. Go to Browse
10. Observe Drop down

Expected Result : 
It should display error message "Error: Namespace already exists"

Actual Result : 
System is not displaying any error message and allowing to create duplicate namespace 
On Browse page drop down is displaying duplicate namespace also
![image](https://user-images.githubusercontent.com/40416610/48664331-0b113700-eac3-11e8-912a-6751e8362505.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.

**Comment by rupalichavan9860** [comment]
@gautamv16 Issue is still exists for following scenario : 
if same namespace name with leading and trailing spaces is entered in "Other Namespace Name" field 
 then it should display error message "Namespace already exists"
As of now it is accepting duplicate names

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested this scenario and working fine on Manage Topic but issue is still exists on "Create New Topic" page.
And issue is exists for one more scenario
 Enter namespace like "sandbox/" or "/sandbox".It should display error message "Namespace already exists",but as of now it is creating new namespace every time

**Comment by rupalichavan9860** [comment]
@gautamv16 Please check this issue for different case combination also.
As of now it is accepting following names also like "SANDBOX","Sandbox", "sandboX" or any other combination

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
