### ISSUE TITLE
Other Namespace Name should have some limit on character length

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#309]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Create New Topic/Topic Update
4. Enter valid data in all mandatory fields
5. Select "Other" namespace from drop down
6. Enter long data in Other Namespace Name field
7. Click on "Create New Topic"/"Submit Update" button

Expected Result : 
Other Namespace Name field should have some limit on character length

Actual Result : 
Other Namespace Name is accepting long name and UI is getting disturbed on Browse page
![image](https://user-images.githubusercontent.com/40416610/48699576-c941d700-ec0f-11e8-9fc0-bb223066b64c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested .It is displaying error message if user enters more than 100 characters in "Other Namespace Name"
But need little correction in error message,It should be "The Other Namespace Name may not be greater than 100 characters." instead of "The Other Namespace may not be greater than 100 characters."

![image](https://user-images.githubusercontent.com/40416610/48967652-e3155c80-f009-11e8-8e4b-2d043977a8c6.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  its done, please test when all deployed to staging.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
