### ISSUE TITLE
Set up canonizer.com e-mail aliases.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#31]
set up the following e-mail addresses:

karl.kjer@canonizer.com  -> karl.kjer@gmail.com

support@canonizer.com   ->  assuredservices.28@gmail.com
help@canonizer.com
kinari@kanonizer.com

**Comment by gautamv16** [comment]
Its taking time as on new server whole email server setup system needs to install and configure. Due to some misconfigurations, its creating problem, still working on it. Will figure out soon.

**Comment by gautamv16** [comment]
@BrentAllsop please check test and close the issue.

**Comment by gautamv16** [comment]
@BrentAllsop please close this issue if its tested and working.
