### ISSUE TITLE
Changes to non supported camps should go live instantly.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#310]
A user submitted a change to a new non supported camp:

https://canonizer.com/topic/88/62
https://canonizer.com/camp/history/88/62

But it went into the 1 week review.
All unsorped camps should work like wikipedia.  All changes go live instantly.

**Comment by gautamv16** [comment]
@BrentAllsop Please test it. @rupalichavan9860 please do test on this. Its working as per explaination. Please test on fresh camps and topics.

**Comment by BrentAllsop** [comment]
Looking great to me.
I tested topics, camps, and camps statements on staging.
All go live instantly, when I am the only supporter.
@rupalichavan9860    if this looks OK to you, go ahead and close this.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested and looks Okay to me also.So closing this
