### ISSUE TITLE
Make it so production.canonizer.com, www.canoniaer.com... have a turn off search robots.txt

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#317]
Anything but canonizer.com URLs, should not allow robots to search/index.

**Comment by akuks** [comment]
@BrentAllsop Can you please check now. 
**production.canonizer.com** and **canonizer.com** pointing to the same production folder. Hence it is not possible to disallow the domain from the same robots.txt file.

A Separate robots-disallow.txt is created for all the other subdomains.

**Comment by BrentAllsop** [comment]
@akuks,
Right.  I just know apache has access to the host name being referenced (i.e. production.canonizer.com vs canonizer.com when an http request is made) so I was imagining you could put a conditional definition of robots.txt for various different incoming host names being referenced.  I seem to recall configuring  different document roots, for different domain names, in apache listening on the same port, before.  Now that I think about it, I can look up the old canonizer 1.0 apache config files where I did this, if you need them.

But maybe we're going about this all wrong?
Maybe we should just always redirect *.canonizer.com to canonizer.com?
I believe there is a way to configure apache to do this, also.

**Comment by akuks** [comment]
@BrentAllsop,
I have already modified the .htaccess file and add the contents to disallow for production.canonizer.com.  Search is not showing production.canonizer.com.

I am just wondering do we need "production.canonizer.com" subdomain. If don't then we can delete it from cpanel.

**Comment by BrentAllsop** [comment]
We resolved this issue by redirecting all www.canonizer.com URLs to https://canonizer.com
So this no longer a problem.

**Comment by BrentAllsop** [comment]
This showed up in a google search:
https://mail.canonizer.com/topic/63-Worlds-Without-Ends/3

Except for the ones we know of, like staging.canonizer.com and developement.canonizer.com

everything else should redirect to https://canonizer.com/topic/63-Worlds-Without-Ends/3

**Comment by BrentAllsop** [comment]
We think this is fixed, so if we are ready to close and release, just close this.
Otherwise make sure mail.canonizer.com and production.canonizer.com don't serve any pages.

**Comment by BrentAllsop** [comment]
No evidence of this being a problem so closing this.
