### ISSUE TITLE
Can't get the rest of the topics on the main page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#32]
It seems like on windows chrome and IE, I can't get the home page to list any more than the first 10 topics.
But it does seem to work on Chrome, on my android phone.

**Comment by gautamv16** [comment]
@BrentAllsop  your browser have issue due to ads. Please tryt to re-install chrome and test it. Once tested please close this issue

**Comment by BrentAllsop** [comment]
@gautamv16 
I cleared cache and everything, but still can't seem to get more than 10 topics.
The same is true in IE and Chrome.

**Comment by gautamv16** [comment]
@BrentAllsop please test this once again after clearing cache. Made some changes, lets see if that works on your system.

**Comment by BrentAllsop** [comment]
@gautamv16,
Dang still doesn't seem to be working.
Cleared cash, tried both chrome and IE. just doesn't work for me.

**Comment by gautamv16** [comment]
@BrentAllsop working on this issue still not figuring out your system issue. I changed last time the library for scroll but still not work on your system. So i think we can give button of load more topic instead of automatic scroll ? Think on it and let me know.

**Comment by BrentAllsop** [comment]
@gautamv16 
Yea, I like the button idea.  Seems to give the user more control.

**Comment by gautamv16** [comment]
@BrentAllsop please check new feature added with a button now. By pressing this button all remaining topic will load in background..... It means all topic will load in 2 phases now. No need to click more and more to get all topics. I think this looks ok and also speed of loading is ok too.. Let me know on this.

**Comment by BrentAllsop** [comment]
That works.
closing this issue.
