### ISSUE TITLE
UI is not proper on Camp Update page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#320]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid Email and Password
3. Go to Browse
4. Open any topic
5. Click on "Start new supporting camp here"
6. Enter data in Mandatory fields and click on "Create Camp" button
7. Click on "Submit Camp Update Based On This"
8. Observe Camp Update Page 

Expected Result : 
UI should be proper
 Actual Result : 
UI is not proper for Additional Note field

![image](https://user-images.githubusercontent.com/40416610/49360532-77b14600-f6ff-11e8-9687-418f1999b346.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
