### ISSUE TITLE
Error Exception on topic objection page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#322]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password(New user who don't have any Nick Name)
3. Go to Browse
4. Select any topic and Click on Manage/Edit This Topic
5. Click on Object
6. Without entering in any field click on "Submit Objection" button
7. It will ask for "The objection reason field is required."
8. Enter objection reason and click on "Submit Objection" button

Expected Result : 
It should display error message "The nick name field is required."

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/49511889-62304d80-f8b2-11e8-8af7-db69e601cdc8.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed solved

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
