### ISSUE TITLE
Supporter Agreement to change

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#323]
The first is adding a feature that would allow supporters of a camp to indicate agreement to changes prior to the one-week review period. Each supporter would have a checkbox on the history block for the record that would allow them to say they agree to the change. The change then would go live at the moment that everyone has checked the box. This will require a new database table to temporarily store these values. Once the change goes live, all these temporary values will be cleaned out of the database.

**Comment by gautamv16** [comment]
@rupalichavan9860 this feature has been done please test this.

**Comment by rupalichavan9860** [comment]
@gautamv16 This feature is available but I am getting page crash .Please refer #337

**Comment by rupalichavan9860** [comment]
@gautamv16 This is working fine for me.
@BrentAllsop @CanonizerJim Please test this feature and close if it working as per requirement

**Comment by gautamv16** [comment]
@BrentAllsop please update on this so that we can deploy release 8th

**Comment by BrentAllsop** [comment]
@rupalichavan9860 and @gautamv16 .  Yea, since #337 is fixed.  From what I"ve seen, this looks fine.  So closing this issue.
