### ISSUE TITLE
News feeds on camp.

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#324]
Design of camp news records:
Each camp can have a list of news records which can be re-ordered.
Each news record can have a “Use for sub camps” flag indicating if it should be carried to sub camps (with no records of their own).
If a camp doesn’t have any news records, it searches parents for first parent with active news records.
If there are any news records to display for a camp, a “News” section is created on the camp page, above the Camp Tree section.
If the most immediate parent camp with news records, if none of those records have the “Use for sub camps” flag set, the camp will not inherit any other parent news records.
Each camp record has the following fields:
Unique ID key field (can not be null)
News record order (starting with 1)
Display Text (256 Characters)
URL link (2000 Characters)
Flag indicating child camps can use this if they have no news of their own.
Submit time. (can not be null) record not used if asof value before this date.
End time.  (If null infinity is assumed.)
Editing and ordering of these records will work like editing of support records.
When you go to the camp news record edit page, it will show latest active camp news list for that camp in an ordered list.
You will be able to edit the state of all the records for that camp, including their order, on the client side before any submit takes place.
When you do a submit, all currently active records will have their end time set to the submit time.
The new submitted records will receive the submit time and become active, immediately.
On the edit page, If a parent camp has a parent camp with active news records, these will be displayed on the edit page in a news section similar to what would be displayed on the camp page, if there were no news records for this camp.
There will be both a submit and a cancel button on the camp news record edit page.
When submitted all currently active news records will have their end time set to the submit time and become inactive as of that time.
All new records will receive this same submit time and become active, immediately.
There will be a note that if there are any active news records for this camp the parent news section will not be displayed.  Determine this verbiage in meeting.
The parent news section, if it exists, will be greyed out, or something when there are active news records on the edit page ready to be submitted.  While all news records on the edit page are deleted, the parent news record section will show it as active, identical to the way it would show up on the camp page.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by gautamv16** [comment]
@rupalichavan9860  please close this one

**Comment by rupalichavan9860** [comment]
News feeds feature is available so closing this
