### ISSUE TITLE
Countdown timer note should go away immediately like timer,Update Statement and Stop when user manually stops timer

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#328]
Steps to reproduce : 
1. Go to https://development.canonizer.com
2. Login with valid Email and Password
3. Go to browse and select any topic
4. Click on Manage/Edit Camp Statement
5. Click on Submit Statement Update Based On This
6. Do some changes and click on Submit update button
7. Click on Stop button on updated version of camp statement
8. Observe behavior

Expected Result : 
When user manually stops the timer,the timer,Update Statement and Stop button and Timer note should go away immediately

Actual Result : 
Timer note is remains even after click on "Stop" timer button.And after reloading page only timer note is getting away 

![image](https://user-images.githubusercontent.com/40416610/49629576-28755900-fa10-11e8-80a8-600d4b94327c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 done pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
