### ISSUE TITLE
Countdown timer is displaying incorrect time when user click on browser's go back and again go forward arrows

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#329]
Steps to reproduce : 
1. Go to https://development.canonizer.com
2. Login with valid Email and Password
3. Go to browse and select any topic
4. Click on Manage/Edit Camp Statement
5. Click on Submit Statement Update Based On This
6. Do some changes and click on Submit update button
7. We can see the one hour grace period countdown timer on the updated version
8. After some seconds click on browser's go back arrow and again click on browser's go forward arrow
9. Observe behavior of countdown timer 

Expected Result : 
Countdown timer should display correct time 
Actual Result : 
Countdown timer is again restarting from 1 hour instead of exact time

**Comment by gautamv16** [comment]
@rupalichavan9860 after all investigation this is concluded that its not a bug and its browser behaviour to show last data as discussed so please close this issue.

**Comment by BrentAllsop** [comment]
@rupalichavan9860   I'm thinking we can close this, but only if Rupali is OK with it.

**Comment by rupalichavan9860** [comment]
@gautamv16 As its a browser behavior I am closing this issue.
