### ISSUE TITLE
Error message for other namespace name should be display at field level

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#330]
Error message "Error: The Other Namespace Name field is required when namespace is other." should be present at field level instead of pop up.(On Create New Topic and Topic Update page)
I am facing problem while creating automated test case for this field(Not able to copy XPATH of error message)
![image](https://user-images.githubusercontent.com/40416610/49788808-3c77ce00-fd22-11e8-8eec-1401d2497195.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working on Topic Update page.Please do the same change on Create New Topic page also

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
