### ISSUE TITLE
Spelling for field Language is incorrect on "Manage Profile Info" page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#332]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Username->Account Settings
4. Observe Manage Profile Info for field Language

Expected Result : 
Spelling should be "Language"

Actual Result : 
Spelling is incorrect.It is displaying as "Languauge" instead of "Language"
![image](https://user-images.githubusercontent.com/40416610/50003703-9f8b8e00-ffca-11e8-9591-985fdb5ce604.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
