### ISSUE TITLE
Incorrect validation and error message on Topic Update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#333]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Browse and select any topic
4. Click on Manage/Edit This Topic
5. Click on Submit Topic Update Based On This
6. Enter more than 50 characters in Topic name field
7. Click on "Submit Update" button

Expected Result : 
As per given limit Topic Name should accept only 30 characters and if user enters more than 30 characters it should display error message "The topic name may not be greater than 30 characters."

Actual Result : 
Topic Name is accepting more than 30 characters(accepting 50 characters) and if user enters more than 50 characters it is displaying error message "The topic name may not be greater than 50 characters."
Please find attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/50056722-46685980-0186-11e9-80a1-1b33a1873e6d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
