### ISSUE TITLE
Page Crashed Error on Statement when "I agree with this statement change" check box is checked

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#337]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Browse and Select any topic
4. Click on Add Camp Statement or Manage/Edit Camp Statement
5. Click on "Submit Statement Update Based On This"
6. Do some changes and click on "Submit Update" button
7. Click on "I agree with this statement change" check box
8. Observe Results

Actual Result : 
It is displaying Query Exception.
![image](https://user-images.githubusercontent.com/40416610/50080934-38144f00-0213-11e9-9ef3-5aaa0c0d2a5a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
