### ISSUE TITLE
Page Crashed Error on Topic History page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#338]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Click on Create New Topic
4. Enter data in mandatory fields and click on "Create Topic" button

Expected Result : 
Topic should get created and it should display Topic History page

Actual Result : 
Topic is getting created but it is displaying error exception on topic history page
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/50082907-2aad9380-0218-11e9-87b5-b2fdcb4602eb.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
