### ISSUE TITLE
missing favicon.ico in production. (and redirect all www. URLs)

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#339]
This files seems to be missing:
http://canonizer.com/favicon.ico

Also, we decided to redirect all www.canonizer.com URLs to just https://canonizer.com

This will greatly simplify all google search results.

**Comment by gautamv16** [comment]
@BrentAllsop   here is the fev icon on server https://canonizer.com/img/favicon.ico and its showing properly there.

Also the DNS issue solved for www and production please check.

**Comment by BrentAllsop** [comment]
@gautamv16 
Right, but all browsers check this location for an icon to put on the browser tab:
http://canonizer.com/favicon.ico
So we need to copy into this location.

**Comment by gautamv16** [comment]
@BrentAllsop pls test

**Comment by BrentAllsop** [comment]
Yea, looking good, so closing this issue.
