### ISSUE TITLE
Page Crashed Error on camp forum page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#340]
Steps to reproduce : 
1.Go to https://staging.canonizer.com
2. Login with valid email and password(login with new user who don't have nick name yet)
3. Go to Browse and select any topic
4. Click on Camp Forum
5. Click on "My Threads" or "My Participation"
6. Observe results

Expected Result : 
It should display respective page/message

Actual Result : 
As of now it is displaying error exception
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/50143363-660c9880-02d2-11e9-86b3-4f47c3613af2.png)

**Comment by akuks** [comment]
@rupalichavan9860 Please test on staging.

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified.
