### ISSUE TITLE
Page Crashed on Camp Forum

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#341]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Without logging into canonizer go to Browse
3. Select any topic
4. Click on "Camp Forum" on agreement page

Expected Result : 
It should display respective camp forum page

Actual result : 
It is displaying Error Exception
![image](https://user-images.githubusercontent.com/40416610/50143703-56418400-02d3-11e9-9214-4ead3b0caa31.png)

**Comment by akuks** [comment]
@rupalichavan9860 Please check

**Comment by rupalichavan9860** [comment]
@akuks Retested and verified. Closing this issue
