### ISSUE TITLE
Camp Name Size Issue

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#355]
It says in the camp record edit form, that a name is limited to 30 chars.
But when you submit, it clips to 25 chars.
I suspect this is because the DB schema is 25, but should allow 30?

**Comment by gautamv16** [comment]
@BrentAllsop please test

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop I have tested and working for me.
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
@rupalichavan9860 @gautamv16 Yea, it is now working, and accepts 30 character names.
The name field on the camp record edit field allows more than 30 characters.
You don't get the error message that 31 characters is too long, till you submit the form.
It would be nicer if all text fields simply prevented you from typing in more than 30 characters.
This is fairly easy to do on text fields, right?
So how about we get that fixed before we close this.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
