### ISSUE TITLE
The "As of" box doesn't work on the main page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#356]
If you select anything other than "default" as of value, no topics show up.

You should be able to see the top 10 topics at any time, and be able to also select "include review".

**Comment by BrentAllsop** [comment]
Also, the as of date selector doesn't seem to be working at all.
For example, look at the state of the Theories of Consciousness topic in Archive.org, on Dec 5, 21014:

http://web.archive.org/web/20141215081907/http://canonizer.com:80/

Notice there are 30 or 40 camps, with more than 40 supporters on that date.

But, when you set the asof value to the same Dec 5, 2015 on that topic, currently, there is only about 10 camps and very few supporters.  It looks the same as it did back in about 2012, yet lots of camps and supporters were added between 2012 and 2014:

https://canonizer.com/topic/88-Representational-Qualia/6?filter=0.001&asof=bydate&asofdate=2014%2F12%2F05

**Comment by gautamv16** [comment]
This one is already tested and matched with history. Dont know why still not updated. Now closing this issue.
