### ISSUE TITLE
Page Crash error when selecting as of filter-as of (yy/dd/mm) as past date

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#357]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic who have threads
4. Click on Camp Forum
5. Select as of filter ->as of (yy/dd/mm) and select past date than thread created date
6. Observe behavior

Actual Result : 
It is displaying error exception.Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/50385505-addd5680-06fc-11e9-82a6-d7b2d25e56fa.png)

**Comment by rupalichavan9860** [comment]
Same issue exists on Camp History ,Create Camp , Add Camp Statement page

**Comment by rupalichavan9860** [comment]
This issue exists on all pages of camp forum ->All Threads,My Threads,My Participation,Top 10

**Comment by rupalichavan9860** [comment]
@akuks Now it is displaying Error: 404 Page not found on camp pages
![image](https://user-images.githubusercontent.com/40416610/50395491-69000100-078a-11e9-9c7f-4fb69f88644f.png)

and HTTP ERROR 500 page isn't working on forum pages
![image](https://user-images.githubusercontent.com/40416610/50395528-b3817d80-078a-11e9-997f-ae70fec974d6.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Issue is still exists

**Comment by gautamv16** [comment]
@akuks please check this one where it is in forum. I have no issue on my machine. Please check and verify with @rupalichavan9860

**Comment by gautamv16** [comment]
@rupalichavan9860 you have to show this issue, when, where its coming for you. It doesnt came for past date selection. If you are facing it then its something related you sepcific account. Because its not discoverable for me...

**Comment by rupalichavan9860** [comment]
@gautamv16  Yes sure..I have 3-4 accounts on staging and I have checked this issue using all accounts and able to reproduce.SO I will show you in tomorrows meeting

**Comment by gautamv16** [comment]
@rupalichavan9860 done as per discussion in last meeting please check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Still canonizer and as of filter blocks are available on Camp Statement History,Topic History,Camp History and forum pages
Please do the same for above pages also

**Comment by gautamv16** [comment]
Thats is required on history pages. thats why its there.

**Comment by rupalichavan9860** [comment]
Okay but when I am applying as of date as past date on camp history page it is displaying Data could not be found .It is Ok?

**Comment by gautamv16** [comment]
Yes if there is no data in that range it should display that message.

**Comment by rupalichavan9860** [comment]
Okay.But need to remove for forum pages because filters are not required for forums.

**Comment by gautamv16** [comment]
check now @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@gautamv16 retested and verified..Need to remove when user is on profile page(Manage Profile Info).
@BrentAllsop Canonizer and As of filters are removed from unnecessary places. Please check and let me know if fine for you.

**Comment by BrentAllsop** [comment]
Yea, looks nice.  Except for as Rupali said, it's still there on the Manage Profile Info tab page.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.So closing this issue
