### ISSUE TITLE
View this version doesn't work for Camp Record history.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#358]
When you submit a new version of a camp record, with a new name, for example, and then when you click on "View This Version", the camp and the entire sub structure is missing from the camp tree.

You can see this by clicking on the "View This Version" button on the yellow record scheduled to go live on Dec 30.

**Comment by BrentAllsop** [comment]
Also, when you click on "view this version" for other, older, versions, lots more of the camp tree is lost.

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed with history fixes please check

**Comment by gautamv16** [comment]
@rupalichavan9860 its history fix, you have toverify and close this

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
@BrentAllsop Please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, looking good so closing.
