### ISSUE TITLE
Arrow structure is missing for topics who don't have sub camps

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#369]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Select "/general/" from Canonized list for drop down
3. Click on "Load All Topics" button
4. Observe
Please refer following screenshot
![image](https://user-images.githubusercontent.com/40416610/50417098-4503f480-084a-11e9-98c7-d3aa250abbbb.png)

**Comment by BrentAllsop** [comment]
Hmm, not seeing this?

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@rupalichavan9860 Retested and verified.
