### ISSUE TITLE
User should able to create camp from "Canonized List For" also.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#370]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Select any from Canonized list for drop down
3. Click on "Load All Topics" button
4. Click on First topic and click on other topics also
Expected Result : 
User should able to see <Start new supporting camp here> for each topic 
Actual Result : 
User is able to see <Start new supporting camp here> this link only for first topic
![image](https://user-images.githubusercontent.com/40416610/50418647-9a440400-0852-11e9-9238-4de4f1c01878.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 as discussed removed from landing page.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.Closing this issue
