### ISSUE TITLE
Arrows are not clickable on blog posts camp structure 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#371]
Steps to reproduce : 
1. Go to https://staging.canonizer.com or https://www.canonizer.com
2. Login with valid email and password
3. Go to Blog and select any blog
4. Go to bottom of the blog post
5. Click on any arrow

Expected Result : 
Arrow should be clickable

Actual Result : 
Arrows are not clickable

**Comment by gautamv16** [comment]
@rupalichavan9860 @BrentAllsop these are not clickable as these are third party and only for display and linkup with related topic. These cant be clickable.

**Comment by BrentAllsop** [comment]
@rupalichavan9860 @gautamv16 It would be nice to be able to click them, but being a third party tool would make it far to difficult to do, at this time.  There are more important things to focus on, so I'm OK with closing this one.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Okay .Closing this issue
