### ISSUE TITLE
When user is on Create New Thread page "Create New Topic" link is getting highlighted instead of "Create New Thread"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#372]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Browse and select any topic
4. Click on "Camp Forum" 
5. Click on "Create New Thread" link from left panel
6. Observe left panel

Expected Result : 
It should highlight "Create New Thread" link."Create New Thread" link must be in green color

Actual Result : 
As of now it is highlighting "Create New Topic" instead  of  "Create New Thread"
Please refer attached attached screenshot
![image](https://user-images.githubusercontent.com/40416610/50571064-e6002b80-0dc5-11e9-981d-d8c244df5f8f.png)

**Comment by rupalichavan9860** [comment]
Same happens when user clicks on "Algorithm Information" link "Help" is getting highlighted.
![image](https://user-images.githubusercontent.com/40416610/50571076-2c558a80-0dc6-11e9-8c1a-be07d8f1f074.png)

**Comment by akuks** [comment]
@rupalichavan9860 Please test. I am not sure of Help, we need to discuss on Friday Meeting. For Forums it working well.

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16 Yes.It is working fine for forums now and as per discussion "Algorithm Information" is part of Help so I am closing this issue
