### ISSUE TITLE
UI is getting disturbed on list of supported camps page if Nick Name is 50 character long

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#373]
Pre-condition : 
User must have Nick Name 50 character long
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Go to Browse and select any topic
4. Click on supporter nick name under "Support Tree for "Agreement" Camp"
5. Observe namespace drop down on page

Expected Result : 
Drop down alignment should be proper place

Actual Result : 
Drop down is not displaying at proper place.Refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/50571188-c3701180-0dc9-11e9-9f1a-ea03d0604552.png)

**Comment by rupalichavan9860** [comment]
Please refer following screenshot for proper position of namespace drop down
![image](https://user-images.githubusercontent.com/40416610/50571212-3f6a5980-0dca-11e9-8a99-3826704a892a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please check after clearing cache

**Comment by rupalichavan9860** [comment]
@gautamv16 Checked this after clearing cache ,still issue exists.Please refer screenshot
![image](https://user-images.githubusercontent.com/40416610/50629632-627c4100-0f63-11e9-97fa-36ef696ea683.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested but still I am facing this issue.I have already discussed in last meeting but I guess you missed this because of your poor internet connection.I will show you in tomorrows meeting
