### ISSUE TITLE
Incorrect Submitter Nickname is displaying on Camp History page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#374]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Create fresh topic
4. Go to Manage/Edit This Camp
5. Observe Camp History page for Submitter Nickname field
6. Click on "Submit Camp Update Based On This"
7. Observe Nick Name drop down

Expected Result : 
Correct Submitter Nickname should display

Actual Result  : 
It is displaying incorrect Submitter Nickname
Refer attached screenshots for more details
On Camp History : 
![image](https://user-images.githubusercontent.com/40416610/50571252-67a68800-0dcb-11e9-9e77-ecbd0619de7b.png)

On Camp Update : 
![image](https://user-images.githubusercontent.com/40416610/50571245-5198c780-0dcb-11e9-8e21-3805df3906e5.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test it for new camp and new record now. Old you have submitted is recorded with wrong data due to some issue. Please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
