### ISSUE TITLE
Two error messages are displaying at a time for "Other Namespace Name" field for one scenario

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#385]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Click on "Create New Topic"
4. Select Other namespace from Namespace drop down
5. Enter more than 100 characters in "Other Namespace Name" field
6. Click on "Create Topic" button. This will display error message "The Other Namespace Name may not be greater than 100 characters."
7. Now Clear entered data in "Other Namespace Name" (make it blank) and again click on "Create Topic" button

Expected Result : 
It should refresh the page and should display only one error message "The Other Namespace Name field is required when namespace is other."

Actual Result : 
As of now it is displaying two error messages.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/50631772-99565500-0f6b-11e9-9c49-743612516b99.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Issue is still exists

**Comment by gautamv16** [comment]
Please clear your system cache

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
