### ISSUE TITLE
Camp name is accepting duplicate names

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#386]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid Email and Password
3. Create new topic or open any existing topic
4. Go to Agreement page and create 2 or 3 camp with same camp name
5. Go to Manage/Edit this camp
6. Observe Parent camp drop down

Expected Result : 
Camp name must be unique at topic level

Actual Result : 
As of now Camp Name is accepting duplicate names and Parent Camp drop down is displaying all camps under that topic and this is creating confusion at the time of selecting parent camp.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/50648917-7b581700-0fa2-11e9-9de9-0fb8b80a25ef.png)

**Comment by gautamv16** [comment]
I made it uniuqe for overall topic level.. But if it reuire unique at topic level then need to check.. Lets discuss this...

**Comment by rupalichavan9860** [comment]
I have tested this but still camp name is accepting duplicate names at topic level and overall also.Need to discuss on this

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. It is displaying error message "The camp name has already been taken" when trying to update same camp.
Refer issue #509

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash on Camp Update page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/58198637-4dbf0080-7cec-11e9-9a83-5f755826bec7.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 On Create New Camp it is working fine but on camp update still it is accepting duplicate name.
I have updated camp name "test camp 1 " to "test camp 2" and record is getting updated even if "test camp 2" is already available under same topic
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/58199690-b0b19700-7cee-11e9-8006-0caa0b582521.png)

![image](https://user-images.githubusercontent.com/40416610/58199914-2c134880-7cef-11e9-96f8-dc657b8a6e84.png)

**Comment by gautamv16** [comment]
can you please check it now..

**Comment by rupalichavan9860** [comment]
@gautamv16 Now again it is displaying error message "The camp name has already been taken" when trying to update same camp.
![image](https://user-images.githubusercontent.com/40416610/58201592-1142d300-7cf3-11e9-9ff0-cd15c4de0cca.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I just checked this is working now.
But this is not checking not live camp names .Please refer following scenario
I have created camp "Camp5 " and renamed "Camp5 " to "Camp6" which is not live yet (Submitted on : 5/23/2019, 3:59:32 PM  )
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/58246482-ce294400-7d74-11e9-86bf-78bb6376289a.png)


And now I am able to create duplicate camp with name "Camp6"
Please refer attached screenshot with submitted on time
![image](https://user-images.githubusercontent.com/40416610/58246389-8c989900-7d74-11e9-9f7a-5535a096c002.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 can u pls recheck

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
