### ISSUE TITLE
Success message on Camp History page after update statement is not proper and it is displaying different Go live time in message than on updated record

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#387]
1.Go to camp update and do some changes in camp and click on"Submit Update" button.
2.Now this will display one hour countdown timer with Update Statement button
3.Click on "Update Statement" button
4.Make some changes and Click on "Submit Update"
5.Observe Success message and Go live time

Expected Result : 
Success message should be "Success! Updation in your changed camp made successfully. It will go live live on 1/10/2019, 10:04:42 PM"

Actual result : 
As of now it is displaying "Success! Updation in your changed camp made successfully. 1/10/2019, 10:04:42 PM"
Go live time is not getting updated in updated record
![image](https://user-images.githubusercontent.com/40416610/50650095-8791a380-0fa5-11e9-9761-92f6611e36e7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 go live time is removed from success message as it coming in updated records where user can view the go live time. Only message is shown there now. As i can see it was removed from all success message. So not required here.

**Comment by rupalichavan9860** [comment]
@gautamv16 Any change in camp is going live instantly ,So I am not able to test this issue.
I think if other supporters are present it should go into review mode.Please check and verify

**Comment by gautamv16** [comment]
@rupalichavan9860 message is similar in all cases now. There is difference to test in any case. For golive its working as it was working

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
