### ISSUE TITLE
Topic name is accepting duplicate name on topic update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#388]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Open any existing topic 
4. Click on Manage/Edit This Topic->Submit Topic Update Based On This
5. Enter any existing topic name in "Topic Name" field
6. Click on "Submit Update" button

Expected Result : 
It should display error message "The topic name has already been taken."

Actual Result : 
As of now user is able to update topic with existing topic name.

**Comment by gautamv16** [comment]
@rupalichavan9860 in update case we have to check uniqueness even in existing name of the topic. Please check its developed accordingly.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified..

**Comment by rupalichavan9860** [comment]
@gautamv16  This is creating problem when user is trying to update other fields of the topic .
When user tries to update other fields on the page then also it is displaying error message "The topic name has already been taken.".Need to work on this

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Not working.Please try to update any topic with/without any change in any field(Don't change topic name)

**Comment by gautamv16** [comment]
Rupali, this can only work in this way. If you dont update anyfield then it
will give you validtaion error that topic already exist if you change
anything then only it allow you to update

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by rupalichavan9860** [comment]
@gautamv16 According to me it should allows user to change any single field on the page.
As of now If user wants to change only namespace then it is displaying error message "The topic name has already been taken."
Need to discuss this in meeting

**Comment by rupalichavan9860** [comment]
According to Varun this is working fine on local server but not getting reflected on staging and requires more time to work on this.So I will keep this open for 10th release

**Comment by BrentAllsop** [comment]
We need to be able to abandon a name on one topic, then use it on another, with no possibility that two topics will have the same live name.

* When you add a new name, check all the default (live now) and in review topic names of all topics to make sure no duplicates, anywhere.  Ignore all objected to records.

I guess if we do that, it will be sufficient.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 i forget to update this. This is also done.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. it is not working ,Even if I am not changing anything or changing any single field it is always displaying error message "The topic name has already been taken".

**Comment by rupalichavan9860** [comment]
On Create Topic page also it is displaying error message "The topic name has already been taken" even if topic is not present in topic lists
![image](https://user-images.githubusercontent.com/40416610/57446773-1de71600-7273-11e9-86f0-68f4a11038d1.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 can you please clear cache and try now.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
