### ISSUE TITLE
Remove no multi parent / child camp support requirements.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#389]
Users can now support any set of camps they want to in a topic, including if they are parent or children camps to camps they already support.

Remove the old code that enforced these restrictions.

**Comment by BrentAllsop** [comment]
Never mind.
We changed our  minds on this one.
When someone is adding explicity support for a camp,
we will not allow any other explicit support in any implicitly supported camp.

However, since it is so hard to insure this, when changing camp parent's, we will allow multiple support of parent and children camps.  So we must handle this case, but this is only possible via moving camps.

In other words, put the code back to the way it was, when this issue was first submitted.

**Comment by gautamv16** [comment]
@BrentAllsop done by karun

**Comment by BrentAllsop** [comment]
@rupalichavan9860  This looks fine to me, so go ahead and close it, if you think it is OK.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop This looks fine to me too, so closing this
