### ISSUE TITLE
When there is no support, go live instantly (submit time = go live time)

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#39]
If there is no support, we don't need approval of anyone, so go live instantly.

**Comment by BrentAllsop** [comment]
When you create a new topic set the go_live time to be the same as submit time.
Also create a new support record for the topic with the same nic_id.

Currently, if you try to add support to a camp, with a conflicting (parent or child) support record, it disallows it.  You must manually remove the conflicting support, then come back to add the desired support.

We want to change this, so that instead we display this message first:

"You are already supporting this <parent|child> camp <link to camp with camp name as label>.
If you commit this support, support for that camp will be removed."

This message will have the following two options:

[Cancel]    [Submit]

**Comment by gautamv16** [comment]
@BrentAllsop this task has been completed and deployed on production, staging. Please test the flow properly.

Thanks

**Comment by BrentAllsop** [comment]
I verified that this was resolved.

**Comment by BrentAllsop** [comment]
Ooops, another related issue, so reopened this, rather than create a new one.

If you submit a modification to a topic, camp, statement, and you are the only supporter, it should go live instantly, the same as if there was no support.

**Comment by gautamv16** [comment]
@BrentAllsop please test all cases. Modified the flow.

Please test for following cases.

1. If there is 0 support

2. If you are the only supporter

3. If there are other supporters.

In all 3 cases results needs to be tested and confirmed to close this ticket.

**Comment by BrentAllsop** [comment]
@gautamv16 
This is all working and tested.
But I noticed one minor issue, so could we include that here, before we close this?

You can add the key words to a topic record, when you edit it.
You also need to be able to add key words when you create a new topic.

**Comment by gautamv16** [comment]
@BrentAllsop we dont have keyword feature for topic. There is no keyword field for topic. Do you want a new field to be added in topic table for keyword?

**Comment by BrentAllsop** [comment]
@gautamv16 
Oh, my bad.  Sorry.  We only have, and only want, key words on camps.
Closing this.
