### ISSUE TITLE
Current camp can't be filtered.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#390]
When a camp (including the agreement camp) is filtered, as when the camp isn't supported, the "Start new supporting camp here" is also filtered, making it impossible to add supporting sub camps without turning off the filter.

The bread crumbs at the top of the page are never filtered.  Similarly, the current (and parent) camps should never be filtered in the camp structure section.

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed..

**Comment by rupalichavan9860** [comment]
@gautamv16 I think this issue is still exists.
@BrentAllsop Please test

**Comment by BrentAllsop** [comment]
Right, this camp doesn't show up in the default support tree, since it isn't supported:
https://staging.canonizer.com/topic/29-Test-Camp-/7
The current camp should never be filtered in the support tree.

**Comment by gautamv16** [comment]
@BrentAllsop pls test

**Comment by BrentAllsop** [comment]
Yea, this looks great.
@rupalichavan9860  and @gautamv16  we should have automated tests for everything, especially things like this, before we close them.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls take care of above comment and close issue

**Comment by rupalichavan9860** [comment]
I have tested this but I have one doubt.
When I hit  " https://staging.canonizer.com/topic/29-The-Sky-is-Blue/", I am not able to see "Test Camp" even it is child of agreement camp.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/58382618-04bbc480-7fea-11e9-8ac3-ffe95fd1ebcf.png)

And when I click on any of the camp available then I can see the not supported camps("Test Camp").Refer screenshot
![image](https://user-images.githubusercontent.com/40416610/58382651-611ee400-7fea-11e9-8b1b-c4d1b9c21d15.png)

In my understanding not supported camps like "Test Camp" should be displayed as per the hierarchy
@BrentAllsop Please confirm

**Comment by gautamv16** [comment]
@rupalichavan9860 please read issue once again. This is related to only current camp selection. If current camp have 0 support then it must not be filtered else it will filtered. This is what this ticket is all about. And its working as expected.

**Comment by rupalichavan9860** [comment]
Yes.It is working as expected for current camp, but I have doubt that I have mentioned in last comment.
And if @BrentAllsop also confirms that it is an issue, then I will create a new issue for this

**Comment by BrentAllsop** [comment]
Yes, that is an issue, but it now looks fixed on staging?
But it is still possible to have the filter value on the side bar inconsistent with what is filtered.
i.e. Filter < 0.001 still shows non supported camps, in some cases.

**Comment by gautamv16** [comment]
@BrentAllsop please test now. There are so many cases which require testing. But now i have retested and checked various cases and implemented the same based on single source of truth. @rupalichavan9860 pls test the same

**Comment by BrentAllsop** [comment]
@rupalichavan9860, I tested this, and it looks OK.
So close this if you think it is OK.
Thanks.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop I have tested this and looks OK to me so I am closing this
