### ISSUE TITLE
Incorrect button name is displaying on Statement Preview pop up when user is adding new camp statement

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#391]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. go to browse and select any topic
4. Go to Agreement page and click on "Add Camp Statement" button
5. Enter data in mandatory fields and click on Preview button
6. Observe Statement Preview pop up

Expected Result : 
Button name should be same as name on Add Camp Statement page

Actual Result : 
Button name is displaying as "Submit Update" instead of "Submit Statement"
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/50817382-a3040200-1349-11e9-8535-f142158213f1.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed...

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
