### ISSUE TITLE
Incorrect link name on Statement update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#392]
Pre-condition : 
Login with user who don't have nick name

Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic
4. Go to Manage/Edit Camp Statement->Submit Statement Update Based On This
5. Observe Add new nick name link name

Expected Result : 
Link name should be "Add New Nick Name"

Actual Result : 
Link name is displaying as "Add New Nickname"
![image](https://user-images.githubusercontent.com/40416610/50825929-54159700-1360-11e9-958c-8a2146f80ad8.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Need to do same changes on objection page .Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/52176722-a5d50400-27dc-11e9-969f-99d7cac23329.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 ready for test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
