### ISSUE TITLE
Camp records are not going live, instantly, when there is no support.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#393]
I submitted a change to this camp record:
https://staging.canonizer.com/camp/history/81/27
It has no support.
The change went into review for one week.
It should have gone live, instantly.
This occured both in production, and on staging (where I canceled the grace period)

**Comment by BrentAllsop** [comment]
Hmm, I just submitted a statement for the same camp.
And it, too, went into review mode for one week.

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed have to test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Camp records are going live instantly when there is no support.But it should go to review mode for one week when camp having two or more supporters.
As of now each and every statement change is going live instantly.
@BrentAllsop Please check and verify

**Comment by BrentAllsop** [comment]
Yup, this appears to be working in staging.
so I'm going to close this.
