### ISSUE TITLE
Issues on News Feeds feature

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#395]
Issue 1 : 
Label name is displaying different than name given in requirement and name in error message
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on "Add News Feed" link
5. Without entering into any mandatory field click on "Create News" button
6. Observe error message

Expected result : 
Label name should be "Display Text" 

Actual Result : 
Add News page :
As of now Label name is "Topic Name" and error message is "The display text field is required."
![image](https://user-images.githubusercontent.com/40416610/51235627-05867f00-1996-11e9-8ec9-d24e2e5d61ee.png)

Edit News Feed Page : 
![image](https://user-images.githubusercontent.com/40416610/51236158-7c704780-1997-11e9-9123-d96ff6c7a254.png)

Issue 2 : 
Error messages should be proper on Edit news feed page
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on "Add News Feed" link
5. Add 4-5 news and go to "Edit News Feed" page
6. Enter more than 256 characters in 2 or 3 news text area and click on "Submit" button
7. Observe error messages

Expected Result : 
Error message should be "The display text may not be greater than 256 characters"

Actual Result : 
As of now it is displaying error messages like 
"The display_text.0 may not be greater than 256 characters" for first news record
"The display_text.1 may not be greater than 256 characters" for second news record 
and 
"The display_text.2 may not be greater than 256 characters" for third news record
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/51236626-a4ac7600-1998-11e9-8475-c85cdc85bf9a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 done pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Both issues are fixed but need correction for issue 2 in following error message
Error message should be "Display text may not be greater than 256 characters" instead of "Display text may not be greater **then** 256 characters"
![image](https://user-images.githubusercontent.com/40416610/51439867-3ba16700-1ce6-11e9-8822-4a210dcc2635.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
