### ISSUE TITLE
Link and page title names are not proper for News feed feature

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#396]
Link name should be "Edit News Feed" instead of "Edit News" like "Add News Feed"
![image](https://user-images.githubusercontent.com/40416610/51241185-4a64e280-19a3-11e9-8463-558504c9766d.png)

Page Title should be "Edit News" instead of "Edit News Feed"
![image](https://user-images.githubusercontent.com/40416610/51241230-5f417600-19a3-11e9-93c9-0b2b0106d6a8.png)

![image](https://user-images.githubusercontent.com/40416610/51241265-741e0980-19a3-11e9-88e5-9c96ef6859a9.png)

Please confirm?

**Comment by gautamv16** [comment]
@rupalichavan9860 done pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
