### ISSUE TITLE
Canonizer 2.0 UMS Management

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#4]
UMS (User Management System) must have a management settings page. Following are the features that 
should be the part of the management page:

1. Manage nicknames (both private and public) used to identify contributions.
2. Ability to change things like e-mail, password, and other settings/preferences, like default canonizer algorithm.

**Comment by gautamv16** [comment]
#1 and #2 partially done. Default canonizer algorithm setting needs to be implement @karun you need to get it done. Then i will implement the algorithm based on default setting.
