### ISSUE TITLE
<nowiki> </nowiki> tags are having problems.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#40]
In order to create the help pages for wiki markup, we need to use the <nowiki> tag to turn of wiki parsing, and just display text as is.

When you add a <nowiki> tag, it does turn of wiki parsing, but it also displays the <nowiki> tag.  It should not display the <nowiki> tag.

You should be able to turn wiki parsing back on, with the close xml tag: </nowiki>.  But this is not working, it just continues to the end of the statement, with no wiki parsing.

**Comment by gautamv16** [comment]
@brent can you send me link for that topic statement where this happens..

*With Highest Regards*

*Varun Gautam*

*Software Developer*

*+91-9888-207706*

*gautamv16@gmail.com <gautamv16@gmail.com>*

*Great Minds Think Alike*

**Comment by BrentAllsop** [comment]
@gautamv16 
The current live statement of this topic uses the <nowiki> and </nowiki> tags, and they don't currently work:
http://staging.canonizer.com/topic/73-purple-wiki-text/1

**Comment by BrentAllsop** [comment]
Also, if you have a list with a single # line, it converts to a * (or bullet, not number).

**Comment by gautamv16** [comment]
@BrentAllsop  please check the issue and check the format i sent you on email for wiki samples. All those are standard wikimedia supported tags. So please create help docs based on that.

**Comment by gautamv16** [comment]
@brent please test this.

**Comment by BrentAllsop** [comment]
@gautamv16, @CanonizerJim,
This is great, the <nowiki> markup is now working, closing this github issue.
Jim, we can now work on a set of new wiki text for this help page:
http://production.canonizer.com/topic/73-wiki-text/1
