### ISSUE TITLE
News Feeds - Link size issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#409]
According to requirement - URL link (2000 Characters), link field should accept 2000 characters but as of now it clips to 555 chars.
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on Add News link
5. Enter more than 1000 characters in "Link" field and click on "Create News" button
6. Go to Edit News and observe link field

it s clips to 555 chars 
Please confirm?

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.Now it clips to 2000 characters when user enters more than 2000 characters but I think we should display error message when user enters more than 2000 characters.
May be user will loose some part of URL  in case of long link name(User should get notified about link max limit)
Please let me know your thoughts

**Comment by gautamv16** [comment]
Please check now @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
