### ISSUE TITLE
Fixes to the history page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#41]
* Change the label of the submit button to include: "Submit Statement Update Based On This".
* When there is no history, there is no way to "Submit Statement Update Based On This".  There should be a "Create New Camp Statement", not associated with any history object.
* Add a 3rd button for each history object that will take the user to that object, with an "as_of" value = "go live time" of that version, so the user can see what it looks like at that time.

**Comment by gautamv16** [comment]
@BrentAllsop  please test these new features...

**Comment by gautamv16** [comment]
@BrentAllsop  tested then close this.

**Comment by gautamv16** [comment]
@BrentAllsop please test this one

**Comment by BrentAllsop** [comment]
@gautamv16,
Hmmm, when I go to this history page, trying to test this, nothing is showing up?

https://staging.canonizer.com/statement/history/88-Theories-of-Mind-and-Consciousness/1

**Comment by gautamv16** [comment]
@BrentAllsop solved.

**Comment by BrentAllsop** [comment]
Verified fixed on developement.canonizer.com and closed.
