### ISSUE TITLE
Name and Title issues.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#42]
Names need to be limited to 30 characters.
Make the label on the edit page be: "Name (Limit 30)"
Make this change to the DB schema.

**Comment by gautamv16** [comment]
@BrentAllsop this is solved

**Comment by BrentAllsop** [comment]
@gautamv16  This is working good for camps.
I think we should also make this same limit on topic names.

**Comment by gautamv16** [comment]
@BrentAllsop its done.

**Comment by BrentAllsop** [comment]
@gautamv16 
I can't test this yet, when I try to create a new topic, it says:
"Error!This topic is not live yet, you dont have access to view the detail. Please try after sometime."

Unrelated, but rather than create issues for these minor issues, could you fix them before clossing this issue?
there should be a space between "Error!This"
And could you set the default namespace to be General, so you don't have to specifically set one.  Also indicate this is recommended, unless you know otherwise that you want a specific special namespace.
And in the history page for the topic records, when the database namespace has no value, indicating general, the user should see General (exactly as it should appear everywhere to the user),  not blank.

**Comment by gautamv16** [comment]
@BrentAllsop  please test all these issues and flow according to various conditions or test cases to make sure everything is covered.

**Comment by BrentAllsop** [comment]
@varun
Yea, everything checks out fine.
Except I wonder if you could change this label for the Namespace, when working on a new topic:

Namespace (General is recommended, unless you know otherwise):

**Comment by gautamv16** [comment]
@BrentAllsop done. Please confirm and close the ticket if done.

**Comment by BrentAllsop** [comment]
All fixed and tested.
