### ISSUE TITLE
as of history is broken

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#423]
We should be able to set history, for each day, after each version of this camp record:

https://canonizer.com/topic/88-Representational-Qualia/6?

Currently, there is even a problem trying to set the as of value, on that camp page.
It attempts to go, then resets back to default.

**Comment by gautamv16** [comment]
@rupalichavan9860 its fixed with history fixes.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I have tested this.Looks good to me
If there is no data for selected date then it is displaying message "Topic does not have any record for selected date."
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, looking good so closing this.
