### ISSUE TITLE
Topic 81 not reachable in MS Edge browser.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#424]
If you try to go to this topic with an MS edge browser:
https://canonizer.com/topic/81
It just redirects to the login page.

We were using an apple system at the sovrin demo.
The apple browser had this and other problems.
Oftentimes the support tree was completely blank.

**Comment by gautamv16** [comment]
@BrentAllsop pls check this.

**Comment by BrentAllsop** [comment]
Yea, seems fixed, even in production.
Looking forward to hearing how you fixed this in an engineering meeting.
