### ISSUE TITLE
Staging and live environment is not working 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#425]
Steps to reproduce : 

1. Go to https://staging.canonizer.com or https://canonizer.com/
2. Click on Log in
3. Enter valid Email and Password
4. Click on Log in button

Expected Result :
User should redirect to canonizer main page

Actual Result :
It is displaying Token Mismatch Exception on staging and Oops! Data Could Not Be Found on live 
Please refer attached screenshot or more details
1. Live
![image](https://user-images.githubusercontent.com/40416610/52713658-e93e2800-2fbd-11e9-9432-0ef4cccc4b00.png)

2. Staging 
![image](https://user-images.githubusercontent.com/40416610/52713743-1e4a7a80-2fbe-11e9-9867-b8228f1ade5e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 i am able to access both. Not found these issue. Please cross check

**Comment by rupalichavan9860** [comment]
@gautamv16 it's working now so closing this
