### ISSUE TITLE
Camp structure is missing when viewing in review camp record.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#427]
I submitted a new version for this camp record:
https://canonizer.com/camp/history/88/18
It is not yet live but when you click on the "view this version" it disappears form the camp hierarchy.
https://canonizer.com/topic/88/18?asof=bydate&asofdate=2019/02/14%2021:37:34
It should be in the hierarchy, with children, with the new name.
The bread crumb camp name should also have the correct new as of value.  It currently does not when you try to view this version.

**Comment by BrentAllsop** [comment]
Even the value shown in the record section at the bottom is still the old value, not the correct as of value.

**Comment by BrentAllsop** [comment]
This is important, as it is almost impossible to get a new camp created, if you can't immediately see it in the camp structure before it is supported.
So I'm adding the 10th Release label to this.

**Comment by gautamv16** [comment]
@BrentAllsop pls test

**Comment by gautamv16** [comment]
@rupalichavan9860 you can also test

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test this one and lets close if ok

**Comment by rupalichavan9860** [comment]
@gautamv16 I just tested this.When I am updating any camp and click on view this version ,updated camp name is not getting updated on Canonizer Sorted Camp Tree.
Please refer attached screenshot
I have changed camp name from "test camp 1" to "test camp 1-v1.1"
![image](https://user-images.githubusercontent.com/40416610/56097316-118bc980-5f10-11e9-8556-9f720df9360b.png)

**Comment by rupalichavan9860** [comment]
Even when updated camp is live then click on View this version->It is displaying old camp name on canonizer sorted camp tree

**Comment by gautamv16** [comment]
@rupalichavan9860 can u check now

**Comment by rupalichavan9860** [comment]
@gautamv16  Retested and View this version is working fine for child camp but if the camp is child of another camp then in bread crumb parent camp name is displaying old camp name .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/56122457-12fcd680-5f90-11e9-8118-e02b4baacd5a.png)

I have created another issue related to bread crumb camp name.Please refer issue #458

**Comment by gautamv16** [comment]
@rupalichavan9860 are you mixing the tickets with new issues of new test cases ? If this ticket related fix is done then let me know and close it and when ever you find new test case issue please dont merge with existing one.

**Comment by rupalichavan9860** [comment]
@gautamv16 I am not merging tickets.When I clicked on View this version I saw difference in camp name on the agreement page.  
But if you think like this is not related to current issue then I will close this.No issues
