### ISSUE TITLE
Incorrect error message is displaying while uploading image file of 0 bytes size

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#434]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Upload File
4. Select any image file(jpeg,bmp,png,jpg,gif ) of 0 bytes size
5. Click on "Upload" button

Expected Result : 
It should display respective error message.

Actual Result : 
As of now it is displaying error message "Error! The file must be a file of type: jpeg, bmp, png, jpg, gif." even if trying to upload .bmp or .png file
![image](https://user-images.githubusercontent.com/40416610/52930354-1b5cda80-336e-11e9-8981-5f90981ea1e6.png)

![image](https://user-images.githubusercontent.com/40416610/52930383-362f4f00-336e-11e9-8e59-f1bee1b1389a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this need to investigate, still i have reserached and implemented something for 0 byte size but still if cant measure exact file size to display in validation but file size must have 1kb please test it.

**Comment by rupalichavan9860** [comment]
@gautamv16 Not able to test this because "Upload File" is displaying FatalThrowableError error .
Please refer Issue #441

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Still I can see the same error message "Error! The file must be a file of type: jpeg, bmp, png, jpg, gif." even if trying to upload .bmp or .png file of size 0 bytes

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16  Still I can see the same error message "Error! The file must be a file of type: jpeg, bmp, png, jpg, gif." even if trying to upload .bmp or .png file of size 0 bytes
![image](https://user-images.githubusercontent.com/40416610/58079709-3f2ef700-7bcf-11e9-9049-2237f6e7523a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 the issue u are asking is not valid as per me. For 0 file size system will not reconize the file type i first check and it will always show this message as for any 0 or invalid file file system always check for valid file first and 0 size file never have any file extension so it will always display error message for file type and that is ok according to me.

**Comment by rupalichavan9860** [comment]
@gautamv16 I am not agree with statement "0 size file never have any file extension"
![image](https://user-images.githubusercontent.com/40416610/58248587-257de300-7d7a-11e9-8474-a06c3539460a.png)
 
@BrentAllsop according to Varun this is not a valid issue and he is OK with current message,Please check and close if you are also OK with this

**Comment by gautamv16** [comment]
@rupalichavan9860 yes i am ok and it depends on file to file. You are intentionaly making a file size 0 and nay file will not have file size 0. And if default any file have 0 size file system will not reconize its file type and always give erro please uplaod valid file not message file size is 0, please test other sites and see the result and share with us if they are able to show the same.
