### ISSUE TITLE
Phone Number Verification questions and doubts

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#435]
Steps to reproduce : 
1. Go to  https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Observe Manage Profile Info

Questions and doubts : 
1. "Phone Number" should have input length limit/minimum and maximum range.As of now "Phone Number" fields is accepting only single digit also
2. Do we need arrows in "Phone Number" and "Verify Code" text fields. Remove arrows from "Phone Number" and "Verify Code" fields if not required
3. "Verify Code " field should mark as a mandatory field and when user clicks on "Confirm" button without entering any code user should see error message "Verify Code field is required." instead of "Verification : A 6 digit code has been sent on your phone number for verification."

Please refer attached screenshot for more details:
Issue 1 : 
![image](https://user-images.githubusercontent.com/40416610/53489615-a305c000-3ab7-11e9-9a28-cb2f61b50af2.png)

Issue 2 : 
![image](https://user-images.githubusercontent.com/40416610/53489671-c597d900-3ab7-11e9-9860-316708e1bd1b.png)

Issue 2 : 
![image](https://user-images.githubusercontent.com/40416610/53489880-41922100-3ab8-11e9-91a1-27be5479d159.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Only issue 2 is working fine.1 and 3rd are still exists

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
But need some minor changes
1. Remove ":" from label Verify Code* : for uniformity
2. Need space between Code and "*"
3. User can type 10 digits in "Verify Code" field but in error message it is saying "Verification : The verify code must be 6 digits."
Expected Result : User should able to type 6 digits only
![image](https://user-images.githubusercontent.com/40416610/72496322-2c002400-384f-11ea-8a53-a195e8c17555.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
