### ISSUE TITLE
selected canonizer algorithm and "as of" value should remain persistent.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#436]
User selections need to be made persistent, and saved in the user session.
Once a person selects a canonizer algorithm, or an "as of" value, these selections should remain, until the session expires.

Also, it would be nice to save the last "nick_name" used, as the default, when making any contribution.
But this is very minor, so don't spend much time on this.
In the future there will likely be more of these types of session values we will want to save.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and looks okay to me.
@BrentAllsop Please test and close if fine for you

**Comment by rupalichavan9860** [comment]
As of date is getting persisted but I have one doubt.
If I click on any topic/camp/statement history record and click on view this version then selected as of date is getting changed as selected record Go live time.This is fine .
But my doubt is, it is displaying different time(date is correct but timestamp is incorrect).Please refer attached screenshot.
![image](https://user-images.githubusercontent.com/40416610/56517967-e16da780-655b-11e9-8c07-715a8daee8db.png)

Now click on View this version
![image](https://user-images.githubusercontent.com/40416610/56518027-03672a00-655c-11e9-8d46-fe5a778ea57b.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860   Are you saying the "go live time" is changing?  I don't think the go live time on any record version should ever change, right?

**Comment by BrentAllsop** [comment]
Unless all supporters of the camp indicate they agree.  Then it should change to when the last remaining supporter indicated they support it.

**Comment by rupalichavan9860** [comment]
@BrentAllsop No."Go live time" is not changing..But it is displaying different go live time in as of date filter text box

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by BrentAllsop** [comment]
The values indicated on the side bar are being saved, but they are often not active on the page.

I'm having troubles reproducing it.  But I will often see the "include review" selected on the side bar, as saved in my session, but the  statement in review is not being displayed on the page, just the older live version.

**Comment by rupalichavan9860** [comment]
I have one more doubt on this.Do we want same as of date filter in URL also?
Because as of now I can see different filter in URL than selected date and time.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57094182-8000c200-6d2d-11e9-9a24-a6dfd3033006.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its conversion of time so url can have diferent then whats displaying. Its not an issue.

@BrentAllsop please create new issue for the bug you are reporting. That one is different. This one is related to dates.

**Comment by BrentAllsop** [comment]
1. Create a new version of a statement, on a supported record, so it will go into review.
2. Go to that camp page.
3. Select "include review" in the as of box, verify the the change is visible.
5. Go to canonizer main page.
6. Go back to camp page.
7 Notice that the "include review" is still correctly selected, but the change is not shown in the statement.

**Comment by BrentAllsop** [comment]
The best fix would be to use "Single source of truth" (see wikipedia).

**Comment by gautamv16** [comment]
@BrentAllsop pls test, its done.

**Comment by BrentAllsop** [comment]
@gautamv16   Were you able to change this, so that it is using a "single source of truth" or did you just  find a way to make sure the two sources of truth were not in disagreement in this case?

**Comment by gautamv16** [comment]
@BrentAllsop this is using single source of truth.

**Comment by BrentAllsop** [comment]
Great.  This is working great, so closing this issue.
