### ISSUE TITLE
 FatalThrowableError on Upload File page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#441]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Click on "Upload File" link
4. Observe 

Expected Result : 
It should display Upload File page

Actual Result : 
It is displaying FatalThrowableError  when user click on "Upload File" page
Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/54668853-ed59ea00-4b15-11e9-8af3-278e600ebd37.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
