### ISSUE TITLE
Success message is not displaying properly after topic change submittion

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#442]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Click on Manage/Edit This Topic->Submit Topic Update Based On This
5. Do some changes and Click on "Submit Update"
6. Observe success message

Expected Result : 
Either it should display success message like "Success! Topic change submitted successfully." or "Success! Topic change submitted successfully. If no direct supporters object to this change, it will go live on `Date and Time"` 

Actual Result : 
As of now success message is not displaying Date and Time .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/54813642-03051600-4cb4-11e9-9327-37d3a180ac8f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
