### ISSUE TITLE
Error Exception while applying as of date filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#443]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password 
3. Go to Browse and select any topic 
4. Click on Manage/Edit This Camp
5. Select as of (yy/mm/dd) date as past date
6.Observe 

Actual Result : 
It is displaying error exception.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/54868723-a12cd500-4db5-11e9-8245-3b26e4d3c149.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by BrentAllsop** [comment]
@gautamv16  and @akuks 
It looks like this no longer crashes.
But I think the real fix is that there should be no Canonizer algorithm or as of box on any history page.
It doesn't make sense on these pages.  We shouldn't need to have automated tests for this...

**Comment by rupalichavan9860** [comment]
Yes.There is no longer crashes.
But when as of date is past date some things are getting disturbed like Camp name is displaying as "n/a" instead of correct camp name
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55672898-2b009600-58be-11e9-9fa4-830ce0b8ce9f.png)

**Comment by BrentAllsop** [comment]
Yes, all these types of problems would go away, if there was no canonizer or as of box on the side bar of history pages.  I think this is the best solution.

**Comment by gautamv16** [comment]
Brent, but if i am in a state where there is data for current selection and
there is no data on past record then side bar will have all options. Now in
this case camp not avaialble so its coming as n/a

**Comment by BrentAllsop** [comment]
Oh, I see.
I forgot that we had a bread crumbs camp chain at the top of the history page, which does require an as-of box.  Thanks for pointing that out.

Possibilities given that.
1.	Remove the bread crumbs bar, and only have a link to the camp
        a.	This would be the same camp for both the camp record and statement record history pages.  
                1.     For the topic history page, it would be the agreement camp for the topic.
                2.	Currently, the topic page has no link at all.  It should at least have a link back to the 
                       agreement camp page.
        b.	Remove both the as of and the canonizer box on the side bar.
2.	Keep the as of box and the breadcrumbs bar.
        a.	Only remove the canonizer algorithm box, since this does nothing on this page.

Any other possibilities?

I’m leaning towards #1, since “as of” doesn’t make much sense, when you are looking at the entire history of the topic/camp/statement records.  Also, each camp record has a “view this version” button which is a more direct and meaningful way to do any kind of specific date viewing on history pages.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 this is done as per #1 please cross check on staging.

**Comment by BrentAllsop** [comment]
@rupalichavan9860  I see the as of and canonizer selector box are now gone from all 3 edit pages.
But we still have the entire breadcrumbs bar, which is probably OK.  I guess it will still use whatever as-of state is saved in session?  So I guess we just need to make sure this can't crash, if they have an odd as of date set.  Go ahead and close this, if you think it is OK.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop canonizer selector box are now gone but yes we can manually add filter to the camp history URL page like 
If I add following to camp history URL then again things are getting disturbed
"?filter=0.001&_token=JmaeVkoXkgWOEPtlU8Bk6Dxn5WUrjtpthi546usO&asof=bydate&asofdate=1999%2F04%2F01"

Still I am fine with this so closing this issue.
