### ISSUE TITLE
Incorrect topic name is displaying on Create New Camp page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#444]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to browse and select any topic
4. Change the topic name (Go to Manage/Edit This Topic->Submit Topic Update Based On This->Change topic name)(for reference topic name : Testing 1)
I have changed the name of topic to "Testing 1: change on 27 mar"
5. Go to Topic History page and click on View this version(latest record)
6. Click on Create New Camp 

Expected Result : 
It should display updated topic name

Actual Result : 
It is displaying old topic name.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55075298-9b3a3b00-50b8-11e9-8506-a41c02de380e.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Incorrect topic name is displaying on Camp Statement History,Camp Statement Objection,Statement Update,Camp History,Camp Update,Camp Objection and Add Camp Statement page also

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.
I have changed topic name again from "Testing 1: change on 27 mar" to "Testing 1: change on 27 mar 11" and it's not live yet, but I can see not live updated name in bread crumb.Bread Crumb should display updated name only if it is live.
@BrentAllsop Please confirm
![image](https://user-images.githubusercontent.com/40416610/56497042-992d9580-6519-11e9-9a92-b4474bd5c18b.png)

Current Topic record also should display updated topic name only when it is live but as of not it is displaying not live topic name
![image](https://user-images.githubusercontent.com/40416610/56497111-dbef6d80-6519-11e9-9bd1-8c6ff8a9acd0.png)

**Comment by rupalichavan9860** [comment]
And still it is displaying old topic name on camp history,camp update,statement update and camp statement history page
![image](https://user-images.githubusercontent.com/40416610/56497178-2375f980-651a-11e9-84e0-92e9a1bb9b83.png)

![image](https://user-images.githubusercontent.com/40416610/56497329-b747c580-651a-11e9-9ccb-b44df5b3a217.png)



![image](https://user-images.githubusercontent.com/40416610/56497273-7d76bf00-651a-11e9-8408-2712ae9204ae.png)


![image](https://user-images.githubusercontent.com/40416610/56497222-4c968a00-651a-11e9-8b9b-96964a66e043.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.It is displaying correct topic name on other pages now but Camp forum page is displaying not live updated topic name in bread crumb.
I missed to list camp forum page in previous comment

**Comment by gautamv16** [comment]
@rupalichavan9860 please chare comparision and screenshots. I dont understand for forum pages. Please mark this issue to Ashutosh, he will check where it is in forums, as i am not able to find anywhere in forum issue you are talking. Its ok from my end. Please mark issue to Ashutosh and close this for 11th release if not replicated.

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks Please refer attached screenshot more details
I have updated topic name from "Test Topic : By Test name " to "Test Topic : By Test name.."
Now go to live version of topic history and click on Camp forum
Observe Topic name

![image](https://user-images.githubusercontent.com/40416610/57220079-a49fb700-7017-11e9-9c5c-566a856ca20f.png)

![image](https://user-images.githubusercontent.com/40416610/57220124-c7ca6680-7017-11e9-8266-a36f49b82549.png)

**Comment by gautamv16** [comment]
@akuks can u please check from where this is coming.

**Comment by akuks** [comment]
I will check that

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16 Tested and verified.
