### ISSUE TITLE
Current camp records is displaying incorrect data for not live records on agreement page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#445]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with email and password 
3. Go to Browse and select any topic
4. Update camp record and enter in all available fields
5. Go to Not Live camp record and click on "View This Version"
6. Observe Current Camp Record block on agreement page

Expected Result : 
It should display updated Keywords,Camp About URL,Camp About Nick Name 

Actual Result : 
As of now it is displaying data from Live record

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working good
