### ISSUE TITLE
View This Version on Topic History is not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#446]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Click on "Create New Topic"
4. Enter data in  all mandatory fields and click on "Create Topic" button
5. Click on "View This Version"

Actual Result : 
1. as of (yy/mm/dd) filter is getting added automatically
2. As of now Support Tree for "Agreement" Camp is displaying only count and after selecting "Default" filter it is displaying supporter name
3. Name Space  field in Current Topic Record is displaying value "N/A" and after selecting "Default" filter it is displaying namespace name

Expected Result : 
1. I think "Default" should get selected by default.Please confirm
2. It should display supporter nick name also.
3. It should display saved namespace name.

![image](https://user-images.githubusercontent.com/40416610/55085958-903dd580-50cd-11e9-94bc-521a39f2f277.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 for this when ever you came from view this version it will show the date not default selected. Please check rest of thi things as working perfectly for me

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working perfectly now,so closing this one.
