### ISSUE TITLE
Page crash error on Create New Camp page when user is on Thread posts page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#447]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and click on any topic
4. Click on Camp Forum
5. Click on any thread and click on "Create New Camp"
6. Observe page

Expected Result : 
It should display Create New Camp page

Actual Result : 
It is displaying NotFoundHttpException
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55138217-f459ab80-5158-11e9-9327-6ed46d3cde38.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks while performing 9th release testing on live I found that "Create New Camp" link is redirecting to home page but the URL is https://canonizer.com/camp/create
Please fix this

![image](https://user-images.githubusercontent.com/40416610/55306667-95ef3e80-5472-11e9-809a-67177035aa97.png)

**Comment by akuks** [comment]
@rupalichavan9860 can you please share the screenshot on Forums where you see the create new camp link?

**Comment by rupalichavan9860** [comment]
@akuks please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55326459-70c7f380-54a5-11e9-9199-528376fe3a6e.png)

**Comment by akuks** [comment]
Thats strange. I can't see it on
https://staging.canonizer.com/forum/88-Theories-of-Mind-and-Consciousness/1/threads

I will look into it.

**Comment by rupalichavan9860** [comment]
@akuks click on any thread .You will see the link on posts page
for your reference
https://staging.canonizer.com/forum/88-Theories-of-Mind-and-Consciousness/1/threads/347

**Comment by akuks** [comment]
Fixed.

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified.
