### ISSUE TITLE
Things to cleaned up from live database

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#448]
As per discussion in meeting we need to cleaned up following things from live database
Namespace : 
1. /sandbox testing/ : https://canonizer.com/browse?namespace=19
2. /sandbox/ : https://canonizer.com/browse?namespace=20
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55143501-deea7e80-5164-11e9-8b74-9de692604973.png)

Topics : 
1. /general/ How to control Anger : https://canonizer.com/topic/166-How-to-control-Anger/62
2. /general/ test : https://canonizer.com/topic/167-test/63
3. /general/ Test2 : https://canonizer.com/topic/168-Test2/64
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55143724-54eee580-5165-11e9-92e6-7ac267de1b2c.png)

I found 3 more topics which I think need to cleaned up from live database.Please refer attached screenshot
@gautamv16 @BrentAllsop Please confirm
1./general/ Test Topic - armvy : https://canonizer.com/topic/171-Test-Topic---armvy/1
2./general/ Test Topic - fmule : https://canonizer.com/topic/170-Test-Topic---fmule/1
3./general/ Test Topic - njwlv :  https://canonizer.com/topic/169-Test-Topic---njwlv/1

![image](https://user-images.githubusercontent.com/40416610/55144009-eeb69280-5165-11e9-9b3a-ae4aa5c478ae.png)

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860   its fixed on live db

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.But still I can see /sandbox testing/ namespace and topics also.
Please refer screenshot
![image](https://user-images.githubusercontent.com/40416610/57230640-6bc30a80-7036-11e9-89ba-622cfe4a54c5.png)

![image](https://user-images.githubusercontent.com/40416610/57230673-85fce880-7036-11e9-807d-83a6b25feb30.png)

![image](https://user-images.githubusercontent.com/40416610/57230714-9e6d0300-7036-11e9-87b3-41102996afc7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 as per discussion in meeting it @BrentAllsop told to keep snadbox testing for you to put all test topics in it. I think you missed that conversation

**Comment by BrentAllsop** [comment]
Move any of topics in the following, as specified:
"/general/ Te3st Topic - armvy" => "/sandbox/"
"/general/ Test Topic - fmule" => "/sandbox/"
"/general/ Test Topic - njwlv" => "/sandbox/"
"/general/ How to control Anger"  => "/General/"
"/general/ test" => "/sandbox/"
"/general/ Test2" => "/sandbox".
Then remove these 6 name spaces.

**Comment by rupalichavan9860** [comment]
I have moved all test topics to /sandbox/ namespace except "/general/ test"  : https://canonizer.com/topic/167-test/63 
because today I saw the topic name changed to "Tree of Knowledge (ToK)" and I observed that now there are two entries for topic "Tree of Knowledge (ToK)".
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57443451-b7122e80-726b-11e9-8c5d-e1642967b9c1.png)

Both topics are different.Should I move topic https://canonizer.com/topic/167-Tree-of-Knowledge--ToK-/63 to /sandbox/ namespace?
@BrentAllsop Please confirm

**Comment by BrentAllsop** [comment]
Topic 306 has two spaces "  (" before the "(".  It needs to be changed to 1 space.
But it can't, because 167 has that name.
I changed the name of 167, so the one space ToK name is no longer used,
But it still won't let me use that one space name for 306?
Let's discuss this next meeting.
