### ISSUE TITLE
Incorrect button name is displaying after countdown timer on topic history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#449]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Update any thing and observe not live records on topic history page

Expected Result : 
1.Button name display after countdown timer must be "Update Topic" instead of "Update Statement"

2.Note must be "This countdown timer is the grace period in which you can make minor changes to your **topic** before other direct supporters are notified." instead of "This countdown timer is the grace period in which you can make minor changes to your **statement** before other direct supporters are notified."

Please refer attached screenshot.

![image](https://user-images.githubusercontent.com/40416610/55220987-8bdcfe00-522e-11e9-9d46-d915aa8c0ea1.png)

**Comment by rupalichavan9860** [comment]
Same for camp change
Expected Result :
1.Button name display after countdown timer must be "Update Camp" instead of "Update Statement"

2.Note must be "This countdown timer is the grace period in which you can make minor changes to your **camp** before other direct supporters are notified." instead of "This countdown timer is the grace period in which you can make minor changes to your **statement** before other direct supporters are notified."
![image](https://user-images.githubusercontent.com/40416610/55221469-89c76f00-522f-11e9-8268-d03b97ddd7d6.png)

**Comment by akuks** [comment]
Fixed. Pushed to staging is pending.
<img width="686" alt="Screenshot 2019-04-04 at 11 43 46 AM" src="https://user-images.githubusercontent.com/12954663/55533479-098d8780-56cf-11e9-9f72-805ce0924403.png">

**Comment by akuks** [comment]
Screenshot from my local machine

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test this as @akuks already fixed this.

**Comment by rupalichavan9860** [comment]
@akuks I am not able to see the changes on staging.Please refer attached screenshot
for topic change
![image](https://user-images.githubusercontent.com/40416610/57237169-43420d00-7044-11e9-96cb-df3ee3f41146.png)

same for camp change
![image](https://user-images.githubusercontent.com/40416610/57237251-74224200-7044-11e9-9809-898a66f1bb51.png)

**Comment by rupalichavan9860** [comment]
@akuks  @gautamv16  Tested and verified
