### ISSUE TITLE
Canonizer  - Email system flow

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#45]
Develop a email communication system for each event.

**Comment by gautamv16** [comment]
https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit?usp=sharing

**Comment by gautamv16** [comment]
@BrentAllsop  Please test the email flow.

**Comment by BrentAllsop** [comment]
@gautamv16,
I need to log into here to do this, right?:
https://development.canonizer.com/admin/login

I couldn't seem to get in, with the same credentials I use on canonizesr.com.
Do I have different ones for this?

Also, after multiple tries, I got this exception:

TokenMismatchException
--
in VerifyCsrfToken.php (line 68)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)

**Comment by gautamv16** [comment]
Hey @BrentAllsop no you dont need admin access to test emails. You have to do just various action on staging where your email address is in env file and you have to test each email.

Like on new account signup, 1.0 account claim, support email, anyone object, new change submit. Do these action and test the content of email. You will receive those emails in your email on staging. Also please buy email plan on sendgrid.
