### ISSUE TITLE
Change the label on the browse page to "Select Namespace"

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#450]
Currently, on the header of the browse page it has "Browse Topic" on the left, and everything else justified to the right.

"Browse Topic" should be changed to "Select Namespace:", and the selector and stuff next to that.

**Comment by BrentAllsop** [comment]
Also, we need to disable the ability to create new namespaces.
We will likely be able to charge for this, in the future.
There is a bunch of garbage namespaces, now.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
