### ISSUE TITLE
Creating new camp statements is broken.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#451]
If you are the only supporter, they don't go live.
When you attempt to submit a new version, when the first version is in review, you don't see the history page, so you can chose the in review version to modify.

**Comment by BrentAllsop** [comment]
If there is a version, even if it isn’t live, you should go to the history page, not directly to the new statement page.

**Comment by gautamv16** [comment]
@BrentAllsop i am not getting this. Please explain little bit with example or screenshots.

**Comment by BrentAllsop** [comment]
@gautamv16  
Create a new camp.
Make sure you support that camp.
Then if you create a new statement, it does not go live, immediately.
Once this first version is in review, the "Add camp statement" should change to ?Manager/Edit camp Statement", but it doesn't.
If you try to "add" a new statement, it doesn't show you the history page.
Does that help?

**Comment by gautamv16** [comment]
@BrentAllsop yes this helps. Let me debug and solve the issue.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 pls test

**Comment by BrentAllsop** [comment]
@gautamv16   still many issues.
If there is already a camp, even if only in review, the button should say "manage camp statement"
For example, this camp is supported by me, and has two yellow "in review" statements, but the button still says add camp statement.

Also, if you are the only supporter of a camp, a new statement should go live instantly.
The to statements in the above camp should have both gone live, instantly.

**Comment by gautamv16** [comment]
@BrentAllsop i have tested all cases. Found only one issue as per your explaination i.e If there are statements in review and not live then there must be button which says " Manage camp statement " which is solved and working as per requirment.  But another issue you have mentioned about goign live is working perfectly on staging for all cases i have tested.  Please check once on staging and let me know.

This is finished now as per me.

**Comment by BrentAllsop** [comment]
@gautamv16, yea everything looks good.
Except there is still one minor use case that should change.
If you are not the only supporter, and if there is not yet a camp statement, even the first camp statement should go into review, to be sure all current supporters are OK with that new statement.

It should only go livek, instantly, if you are the only supporter.

**Comment by gautamv16** [comment]
@BrentAllsop pls test.

**Comment by gautamv16** [comment]
@rupalichavan9860 u can also test flow

**Comment by BrentAllsop** [comment]
This look fine.  @rupalichavan9860 go ahead and close this if it looks OK to you.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop This looks Okay to me too so closing this
