### ISSUE TITLE
Editing support for already supported camp

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#452]

**Comment by gautamv16** [comment]
@BrentAllsop this is for ?

**Comment by BrentAllsop** [comment]
@gautamv16 ,Oh, sorry.  This one got created, accidentally.
I'll close it.

**Comment by BrentAllsop** [comment]
Ah, I discovered what this one should have been.  I thought I submitted it somewhere else, but not seeing it.
Currently, if you already support a camp, it says you can't support it again, and removes the commit button.  It should not do this.
If you already support a camp, the "Join or Directly support" button should change to manage support.
All the current supported camps should have an X on them, so you can easily delete support.
If you submit, with no changes made, no DB changes should be submitted.

**Comment by BrentAllsop** [comment]
@gautamv16 Without this, users will think it is impossible to delete support (or change support order) for a statement.
The only way to do it currently, is to leave the camp, go to the user attributes, then find the topic, then find the camp, only then can you delete it.  The user will never figure this out, but still must be able to delete support.

So it is also important that if someone is already suporting a camp, the button be changed to "manage support", so users can still to to the support page, for this topic, and re-order or delete the support for this or any other topic camp support.

So I'm putting this back to Release 10.

**Comment by gautamv16** [comment]
@BrentAllsop facing issue for its implementation as topic page is visible publicly and anyone can view that page until any action need to be taken on the topic/camp. So we dont have browsing user detail to check if i am supporting this camp or not and another case making it slow down that is first find out which nickname i am using for this topic then check against that nickname that i am supporting this camp or not so we are making it complex here. We have to change text which can be used in either cases and based on the login status it will work. And then we will remove condition that you cant support camp again and give delete and rearrange option instead. Please think and let me know

**Comment by BrentAllsop** [comment]
@gautamv16  OK, how about we just change the button text from always being: "Join or Directly Support This Camp" to "Directly Join or manage support".  Then allow the user to delete or re-order any support for any camps for this topic, including the current one, even if he is already supporting it?

@CanonizerJim   Is that the best thing to do, from an ease of use POV?

**Comment by gautamv16** [comment]
@BrentAllsop this is done as per following flow.

Now there is text as per your instruction and now user can rearrange support for a topic from this link and confirm rearrange. But to delete any support user have to go in my support to delete any support from any camp for any topic. Delete is not possible here as we are assigning numbers to the arrangements. So i hope this flow will work.

**Comment by BrentAllsop** [comment]
@gautamv16 This doesn’t make sense to me.  If the number changes, a termination value for the record with the old number must be added.  Then a new record, with a new start date, and the new number added.  A delete should just do the same, without creating the new record for that camp?

**Comment by gautamv16** [comment]
@BrentAllsop i am not getting what you said. We need to discuss this in meeting. Meanwhile i am leaving this as it is untill not clear.

**Comment by BrentAllsop** [comment]
I'll add this to the agenda for next Thursday.
We just need to have the X on the supported camps, so people can delete any of them, including the camp we are looking at.

**Comment by gautamv16** [comment]
@rupalichavan9860 and @BrentAllsop pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 The X on the supported camps is there but I can see my name in support tree even if I click on X icon on the supported camps 
And click on X  and then click on Confirm Support, then I am getting page crash(Please refer #465)  but now support is getting removed.

It means if we want to remove support we need to click on X  icon and click on Confirm Support also?
@BrentAllsop Please test

**Comment by BrentAllsop** [comment]
@gautamv16 and @rupalichavan9860,
Looking nice.
But it looks like when you hit submit, it is going back to a different camp than the one you started from.
It would be nice if we could save the starting camp, in session, or something, so we could return to the same camp.  And if session times out, and we don't know what camp we started from, do what is being done now.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 pls check it now

**Comment by BrentAllsop** [comment]
@gautamv16  The "confirm support" button needs to change to "submit"
And we need a "cancel" button that goes back to the same camp, but not changing anything in the DB.

**Comment by gautamv16** [comment]
@BrentAllsop please check the above changes.

**Comment by BrentAllsop** [comment]
Nice.
Closing this issue.
