### ISSUE TITLE
Error Exception on Topic Update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#457]
Pre-condition : 
User is logged in

Steps to reproduce : 
1. Go to Browse and select any topic
2. Go to Manage/Edit This Topic
3. Click on Submit Topic Update Based On This
4. Change Topic name field
5. Click on "Submit Update" button

Actual Result : 
I am getting Error Exception .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/55944459-4543c680-5c66-11e9-9be5-d375fd99559c.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting same error exception on topic object page when I am changing topic name field

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
