### ISSUE TITLE
Incorrect bread crumb camp name on multiple places

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#458]
Incorrect bread crumb camp name is displaying on following places
1. Agreement page
![image](https://user-images.githubusercontent.com/40416610/56097743-18b5d600-5f16-11e9-9e47-3c1828ad21a9.png)

2. Create New Camp
![image](https://user-images.githubusercontent.com/40416610/56097739-03d94280-5f16-11e9-9bd8-5b6980928779.png)

3. Add Camp Statement
![image](https://user-images.githubusercontent.com/40416610/56097726-f2903600-5f15-11e9-8987-84ec7c1f4614.png)

4. Camp History
![image](https://user-images.githubusercontent.com/40416610/56097720-dc827580-5f15-11e9-9daf-9b76672e4a7a.png)

5. Camp update
![image](https://user-images.githubusercontent.com/40416610/56097713-c8d70f00-5f15-11e9-97f1-2f7f176a3d35.png)

6. Camp Statement History
![image](https://user-images.githubusercontent.com/40416610/56097776-6599ac80-5f16-11e9-9b8b-fa1129582b8b.png)

7. Statement Update 
![image](https://user-images.githubusercontent.com/40416610/56097764-51ee4600-5f16-11e9-9ac7-19514b85b17a.png)

**Comment by BrentAllsop** [comment]
Let's also fix the bread crumbs URL issue in this one, while we are at it.
Bread crumb URLs should include the optional camp name.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
