### ISSUE TITLE
Supported Camps page is displaying updated camp name even if camp record is not live

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#459]
I have changed camp name from "Camp 2" to "Camp 2-v1.1" and it is not live but supported camps page is displaying updated camp name instead of current camp name.
I think for not live camp records it should not display updated name. Please confirm
Please refer attached screenshot.
![image](https://user-images.githubusercontent.com/40416610/56125918-9e2d9a80-5f97-11e9-831e-820c0a6b9b7a.png)

![image](https://user-images.githubusercontent.com/40416610/56125992-bdc4c300-5f97-11e9-87bf-a752980693a8.png)

**Comment by BrentAllsop** [comment]
It would work the way it is, but I'm thinking it would be better if the camp name was the current default live value.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
