### ISSUE TITLE
System crashes if you submit without a nickname selected.

### ISSUE THREAD

**Issue by KKjer** [the-canonizer/canonizer.2.0#46]
We submitted a new statement (edit) without having selected a "nickname" (field was blank for nickname). The system crashed. To test, we did the same thing, but this time, selecting a nickname, and it was fine.

**Comment by gautamv16** [comment]
@KKjer its solved. Please test with same test case again and confirm the fix. If done please close the ticket.

**Comment by BrentAllsop** [comment]
@KKjer, @gautamv16 
I verified this is fixed, and closed it.
Thanks.
Brent
