### ISSUE TITLE
Add location tag for statement on camp pages

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#462]
Add this tag to all URLs in the tree outline so when you click on camp URLs in the outline, it scrolls down to the camp statement on the page.

**Comment by BrentAllsop** [comment]
In other words, all links in the camp tree should be of this form:
https://canonizer.com/topic/88-Representational-Qualia/6#statement

So that the page will scroll down to display the statement section of the page when you click on them.

**Comment by gautamv16** [comment]
@BrentAllsop  and @rupalichavan9860   its fixed and deployed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and looks okay to me.
@BrentAllsop @CanonizerJim Please test and close if fine for you

**Comment by BrentAllsop** [comment]
We need to discuss this,
I think this type of URL, should not scroll down:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1

Only this type of URL (which should be used in the camp tree) should scroll:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1#statement

Does everyone agree with me?

**Comment by BrentAllsop** [comment]
We need to discuss this.
We should be able to have scrolling and non scrolling camp URLs:


https://canonizer.com/topic/88-Theories-of-Consciousness/1#statement
https://canonizer.com/topic/88-Theories-of-Consciousness/1

**Comment by gautamv16** [comment]
@rupalichavan9860 and @BrentAllsop please check this. Now i have changed it to dynamic # url based on html dom element. Please test url flow as required. Then lets deploy 11th release

**Comment by BrentAllsop** [comment]
Yes, that is nice.
