### ISSUE TITLE
Need to manage laravel sessions.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#463]
We need to find a way to scale laravel sessions.

Short Term, we should probably let them time out, after 20 minutes.

The system should only fail gracefully.

**Comment by gautamv16** [comment]
@BrentAllsop  We need to create a script also which delete session data periodicaly. Every week script run once and delete all cache and sessions.

**Comment by akuks** [comment]
I think 20 minutes is on the lower side. What about an hour?

**Comment by akuks** [comment]
And also I will create this script. that runs Once a week.

**Comment by BrentAllsop** [comment]
Doing it via script will not work.  It will kill live sessions.

Yes, we can start with one hour.
We can adjust later, if needed.

**Comment by BrentAllsop** [comment]
Do robot visits create sessions?  They should not.

**Comment by BrentAllsop** [comment]
And we should focus on getting release 10 out before we work these.

**Comment by akuks** [comment]
Sure, we will fix it after release 10.

**Comment by gautamv16** [comment]
@akuks is it done for 12th release or you need to move it for 13th release as except this all of 12th release tickets are done, waiting for this one to deploy 12th release. Please let @rupalichavan9860 know if need to deploy 12th without this and remove 12th tag from this and then we are ready for 12th deployment.

**Comment by akuks** [comment]
Will create a script in the 13th Release for this issue.

**Comment by akuks** [comment]
Script is developed and deployed in production.
