### ISSUE TITLE
Error exception on Supported Camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#465]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Create any new camp ->View This Version->Directly Join or Manage Support
5. Click confirm support button
6. Click on cross icon on camp name and again click on confirm support button

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/56497886-05f65f00-651d-11e9-9151-41c0e2d34f63.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting Error exception when there is only one record present in camps list.
Click on cross icon on camp name and click on confirm support button

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
