### ISSUE TITLE
history records are messed up.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#466]
The history records at least on this page are bad:
https://canonizer.com/camp/history/88/17

Here is an archive.org snapshot of that camp on Aug 29, 2014.
Notice that the record showing live, above, is different than the one shown here.

I suspect that this problem is pervasive across all history pages>

Once this is fixed, Kinarri needs to do some thorough spot checking of more history pages (topic, camp, statement) to be sure everything is working and agrees with actual history.

**Comment by rupalichavan9860** [comment]
@BrentAllsop This is working fine on staging after yesterday's deployment. Please check

**Comment by BrentAllsop** [comment]
@gautamv16, This seems to be a problem on many, if not all camps.
Here is another very bad history camp for the critically important camp #18:
https://staging.canonizer.com/camp/history/88/18

I think we should get this fixed, and into release 10, before it goes out.

**Comment by BrentAllsop** [comment]
It seems like it is randomly taking camp records from other camp histories.
You can tell by the camp names, being names for other random camps.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I am not getting,can you please elaborate with expected result

**Comment by BrentAllsop** [comment]
Oh, I see the problem.  I was thinking that the first item in the history record was the name, but it is the parent.  I need to pay more attention.  Sorry.

But how about we change the order.  I think the camp name should aLways be first, then the camp parent.

**Comment by rupalichavan9860** [comment]
Okay.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test

**Comment by BrentAllsop** [comment]
this looks fine.  OK with me to close this one.

**Comment by rupalichavan9860** [comment]
This looks fine to me too.
@BrentAllsop Do we want same changes(change order) on Create New Camp,Camp Update and Camp preview pop up for uniformity or is it fine?
If fine please close this one

**Comment by BrentAllsop** [comment]
Not sure I'm fully understanding.  Let's talk about this next Thursday.
I'll close this, for now, so we can get release 10 out.
