### ISSUE TITLE
Turn filter off in their session, when someone creates a new camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#467]
When someone creates a new camp, set the filter value, in their session, to 0.00. (turn it off)

That way, they will be able to see the new, not yet supported camp they just created, and not think it failed to be created.

**Comment by gautamv16** [comment]
@BrentAllsop pls test as created a new way for filter. Lets close if it works

**Comment by BrentAllsop** [comment]
Functionally, camps with no support are showing up, after you create a new camp.
But the filter indicator, on the side bar, still says: "Filter < 0.001", indicating it is on.
This is another dual source of truth issue that needs to be fixed (made back to a single source)

**Comment by gautamv16** [comment]
@BrentAllsop its done.

**Comment by BrentAllsop** [comment]
It seems that when you change something on the side bar, it doesn't change the session value, it just reloads the page with filter and as values in the URLs.  So if you change the URL, it goes back to the old session you thought you changed.

In my opinion, the side bar should only change the session, and not add arguments to the URL.
Also, I'm thinking values specified in the URL, should not change session.

Let's talk about this in the next meeting.

**Comment by BrentAllsop** [comment]
Also, when you change the "filter" value this should be saved in sessions, to be consistent with all other side bar actions.

**Comment by gautamv16** [comment]
@BrentAllsop pls check i have finished this.

**Comment by BrentAllsop** [comment]
it is still not quite right, in the following case:

Set all side bar setting to default (not by URL)
Go to a topic with camps with zero support.
Create a new camp.
Notice that the Filters is set to 0.00 (turned off) which is good.
Now turn the filter on:
set Filter < 0.001
Notice that the side bar and URL indicate the filter is on
However, there are not supported camps that are not filtered.  They are showing up in the camp tree.

The filtering seems completely broken, and out of sync with what is indicated on the side bar.

**Comment by gautamv16** [comment]
@BrentAllsop pls test it now as it requires all algorithm modification too. So its done now from my end for every case. Please check various cases you can expect. if all ok pls close this one.

**Comment by BrentAllsop** [comment]
Yea, everythings looks great to me, so closing this one.
