### ISSUE TITLE
Incorrect camp name and topic name on supported camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#469]
Reference topic/camp
https://staging.canonizer.com/topic/220-Camp-2--sub-camp-1/7?

Please refer attached screenshot.

![image](https://user-images.githubusercontent.com/40416610/56644448-4b3f9b80-6699-11e9-9d8c-29b16dd82f8c.png)

![image](https://user-images.githubusercontent.com/40416610/56644637-b1c4b980-6699-11e9-8259-b84aea093139.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 incorrect camp name is displaying because I have changes the parent from "camp 2" to "Camp 1 : v1.1" for camp "Camp 2: sub camp 1 " and record is not live yet.
Need to discuss on this

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test properly as in above screenshot your points are conflicting on one point as you changed rhe parent of camp on one page then you are matching that on second page which will be different. So please test it properly.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I have changed topic name today from ""Test 6" to "Test 6: change on 19 may" which is not live yet
I can see the live topic name in URL but not on Supported camps page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57980876-6ca06700-7a4e-11e9-81bb-237e3c23806e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
