### ISSUE TITLE
Main Page "Include Review" is broken

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#471]
If you set the "include review" option on the main page, it only displays the topics with the largest topic numbers.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls close this as tested in 11th release same issue. Pls test once

**Comment by rupalichavan9860** [comment]
@gautamv16 after logged in when I click on "Include Review" it is displaying "No topic available." for /general/ namespace but after selecting any other namespace and again /general/ then it is displaying 
some topics
![image](https://user-images.githubusercontent.com/40416610/58380448-c95fcc80-7fce-11e9-8ff6-f79e6601a691.png)

![image](https://user-images.githubusercontent.com/40416610/58380458-e8f6f500-7fce-11e9-9ea3-ec611b9c1db1.png)

Is this an issue?Or it is fine.
@BrentAllsop Please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yes, these are all issues which need to be fixed.
There should be no change in the list of items, when changing to "include review"
as no camp support changes.  The only thing that should change would be a topic or camp name change that hasn't gone live yet.

**Comment by gautamv16** [comment]
@BrentAllsop i am moving this from 12th release. Still debugging the queries and problems seems very complicated in different cases which require more time so i think we should push 12th release without this if Brent you are ok with it as we are finished with all 12th issues only few of @akuks tickets needs to be closed or tested if done.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested..Not fixed yet

It is topic name multiple times and listing topics from other namespaces also
![image](https://user-images.githubusercontent.com/40416610/72247644-57023200-361b-11ea-8d2f-2e065cc31bb4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I think I am facing same behavior for both default and include review filters.I am not able to verify this issue.Can you please check and verify?

**Comment by BrentAllsop** [comment]
@rupalichavan9860 Could you describe what you are seeing?
I'm not seeing any problems, now.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested and verified.I am not facing any issue so closing this
