### ISSUE TITLE
turn off settings pages in robots.txt

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#472]
We should update the robots.txt file to tell robots they should not index all
https://canonizer.com/settings
pages.

And we need to be sure all logs.canonizer.com pages are also turned off.

After second consideration, I think we should tell google to search history pages.
so don't turn off history page indexing.

**Comment by gautamv16** [comment]
@akuks can you please check this one

**Comment by akuks** [comment]
/settings disallowed in the robots.txt and there is no robots for logs hence it will not indexed by google.

**Comment by gautamv16** [comment]
@akuks please help @rupalichavan9860 to close this issue so that we can deploy 12th release.

**Comment by akuks** [comment]
@rupalichavan9860 can you please check and close this issue. robots.txt disallowed /settings in the canonizer. Please check this https://canonizer.com/robots.txt

**Comment by rupalichavan9860** [comment]
@gautamv16 @akuks Checked and verified.
@BrentAllsop Please check and close if fine for you.

**Comment by BrentAllsop** [comment]
With visual inspection, this looks OK.
But visual inspection can fail.
We need an automatic tool to check all of our "properties" reliably.
For example, here is some info on a google robots.txt testing tool
https://support.google.com/webmasters/answer/6062598?hl=en
I don't want to close this now.  We need to automate the test, before closing.
But I will remove the "12 release" tag, so we can put out release #12, and get this automated in the future.
Once we have a design for this, let's talk about this in a meeting.

**Comment by rupalichavan9860** [comment]
Implemented automated test case for this, so closing this issue.
