### ISSUE TITLE
Incorrect success message is displaying after camp statement creation

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#473]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Create new camp and click on "Add Camp Statement"
5. Click on "Submit Statement"
6. Observe success message

Expected Result : 
It should display success message "Success! Statement submitted successfully."

Actual Result : 
It is displaying success message "Success! Statement update submitted successfully."
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/56867241-bfaf6d00-6a00-11e9-8174-e161c4344e35.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I have created fresh topic and adding camp statement first time but still it is displaying success message as "Success! Statement change submitted successfully." 
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57980748-ad977c00-7a4c-11e9-8216-5cbd73adcc48.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
