### ISSUE TITLE
Topic history page needs default link to topic page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#474]
This should be similar to the bread crumb rows at the top of other history pages.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 its fixed and deployed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and looking nice.
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
@gautamv16 and @rupalichavan9860,
I'm seeing what looks like a link to the topic on the topic history page, but it is just blue bold text, not a link to the agreement camp of the topic?  Am I missing something?

**Comment by BrentAllsop** [comment]
Ignore my previous comment.
Rupalli pointed out this is a cashing issue on my end.
