### ISSUE TITLE
Do we need "Create New Camp" link on Help topics also?

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#475]
We have added Create New Camp link on left side menu and because of this any user is able to add camp under help page topics also.
I think only Admin should have access to add or edit topics/camps of any Help topic.Please confirm
As of now I can add camps under any help topics.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57134737-b2113300-6dc4-11e9-82b3-240300871a2e.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
Let's discuss this, but in my opinion, like wikipedia, anyone can edit anything, including help pages.
If someone has a better idea of how to say things, or if they need some help we don't see, we want them to add it....  So it is OK with me to close this as question answered.
