### ISSUE TITLE
clarification of "Note" field.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#476]
Currently, the labels for the "Note" field are as follows:

Topic: “Additional Note”
Camp: “Additional Note”
Statement: Note

All of them should be the same:
“Edit summary (Briefly describe your changes)”

**Comment by gautamv16** [comment]
@rupalichavan9860 @BrentAllsop check this

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested this.I can see the changed name on add and edit pages,but we need to do same changes on topic/camp/statement history pages and preview page also.
I have attached some screenshot for reference

![image](https://user-images.githubusercontent.com/40416610/57427759-05f79e00-7243-11e9-94d2-d798eec7e903.png)


![image](https://user-images.githubusercontent.com/40416610/57427784-2162a900-7243-11e9-9381-392dc090b051.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 As we have added note field recently in proposed change emails.We need to do same changes in those emails also.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check its done

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
