### ISSUE TITLE
User is not able to create nick name which is used by another user

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#477]
As of now nick name uniqueness is present at overall users level.
My thinking is it should be unique at specific user level.
I am trying to add nick name "Rupali N" for user "rupali.chavan9860@gmail.com" which is not present in nick name list but this name is associated with another user "rupali.nimbalkar22@gmail.com".
User will get confused name is not in a list and still it is displaying error message "The nick name has already been taken."
Please confirm
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57175930-7c755400-6e6f-11e9-81d6-b323084cc9b9.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860,
Yes, nick names must be unique, canonizer wide.
Otherwise two different people, with the same nick name, could support the same camp.
This would make it look like they were cheating.
So I think this is as designed, not a bug.

**Comment by rupalichavan9860** [comment]
Ohh, Yes.Thanks for clarification @BrentAllsop .I am closing this one
