### ISSUE TITLE
Submitting a new camp currently crashes.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#48]
I tried to create a new camp, with no statement value
and it crashed.

Also, creation of a statement should not be part of a camp creation.
The creation and editing of a camp record should be different than creation/editing of a camp statement.  The history is also different.

Also, when you "join or directly support" a camp, if you don't support one yet it says:

"You didn't supported any camp yet for this topic."

This should say:

You currently don't support any camps in this topic.

**Comment by gautamv16** [comment]
@BrentAllsop solved. Please test as per flow.

**Comment by BrentAllsop** [comment]
@gautamv16,
Everything looks good, closing this issue.
