### ISSUE TITLE
Password validations are not working properly on change password,register and reset password pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#480]
Try to add password like "TEST@12345",It is displaying error message "Password must be atleast 8 characters, including atleast one digit and one special character(@,# !,$..)" even if password is matching all required criteria.

We need to add one more criteria in list like password must include at least one lower case letter because as of now it is accepting password like "tEST@12345"

**Comment by rupalichavan9860** [comment]
We have already discussed this issue but not able to track as it was not in a issue list

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I can see the changes in error message for Password field on register page but not in Password guidelines, error message for enter new password on change password page and in Password guidelines on forgot password page. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57981029-31069c80-7a50-11e9-913c-b918794f3607.png)

![image](https://user-images.githubusercontent.com/40416610/57981035-4380d600-7a50-11e9-9166-9c2c844d2075.png)

![image](https://user-images.githubusercontent.com/40416610/57981070-8e025280-7a50-11e9-9ddf-022a0b169d46.png)

![image](https://user-images.githubusercontent.com/40416610/57981102-dcafec80-7a50-11e9-8b0f-954c6881c34f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check it now

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
