### ISSUE TITLE
Remove ":" symbol from create new thread form

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#482]
Need to remove ":" symbol after label "Title of Thread" on create new thread formfor uniformity.

![image](https://user-images.githubusercontent.com/40416610/57177578-b9971180-6e82-11e9-8eec-03f5716dde59.png)

**Comment by akuks** [comment]
Fixed and changes pushed to staging but there are some conflict issues hence the changes are not pushed to the staging Server.

**Comment by akuks** [comment]
@rupalichavan9860 Please test this

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified
