### ISSUE TITLE
Text fields size issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#483]
The text fields in an overall canonizer applications have some limit on character length.
You don't get the error message that text fields characters is too long, till you submit the form.
It would be nice if all text fields simply prevented you from typing in more than given text field size characters.

Following are text fields where we need to implement this functionality.
1. Create Topic page :  Topic Name ( Limit 30 char )
2. Topic Update page : Topic Name ( Limit 30 char )
3. Create New Camp page : Camp Name ( Limit 30 Char ) - Already implemented
4. Camp Update page : Camp Name ( Limit 30 Char ) - Already implemented
5. Topic Object page : Your Objection Reason (Limit 100 char)
6. Camp Object page : Your Objection Reason (Limit 100 char)
7. Statement Object page : Your Objection Reason (Limit 100 char)
8. File Upload page : File Name(with no extension) (Limit 200 char)
9. Add News Page : Display Text ( Limit 256 Characters )
10 .Add News Page : Link ( Limit 2000 Characters ) - Already Implemented
11. Edit News Page : Display Text ( Limit 256 Characters )
12 .Edit News Page : Link ( Limit 2000 Characters ) - Already Implemented
13. Create New Thread Page : Title of thread (Limit 100 characters)
14. Account Settings->Add & Manage Nick Names : Nick Name (Limit 50 characters)
15. Create Account page : First Name(Limit 100 characters), Middle Name(Limit 100 characters), Last Name(Limit 100 characters)
16. Account Setting->Manage Profile Info page : First Name(Limit 100 characters), Middle Name(Limit 100 characters), Last Name(Limit 100 characters)
17. Account Setting->Manage Profile Info page : Phone Number(Limit 10 characters)
18. Account Setting->Manage Profile Info page :Address Line 1(Limit 255 characters), Address Line 2(Limit 255 characters) , City(Limit 255 characters), State(Limit 255 characters), Zip Code(Limit 255 characters)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working everywhere except on Create Account page.
Create Account page : First Name(Limit 100 Chars), Middle Name(Limit 100 Chars), Last Name(Limit 100 Chars)
Need to prevent typing in more than 100 characters.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
