### ISSUE TITLE
Labels names must be uniform  throughout application 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#484]
Actual Result : Some text fields labels names have characters limit information in brackets and some text fields don't have .
Expected Result : (Limit ... characters ) must available for all or none.

Actual Result : Some text fields labels name having characters limit information like ( Limit 30 **char** ) and some having like ( Limit 256 **Characters** )
Expected Result : This must be uniform.It must say either "chars" or "characters"

Please refer attached screenshot.

![image](https://user-images.githubusercontent.com/40416610/57223302-34972e00-7023-11e9-97ab-b5237d4d834d.png)

![image](https://user-images.githubusercontent.com/40416610/57223603-39101680-7024-11e9-85f2-544fc2a24f5a.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 "(" is missing for label "City" on "Manage Profile Info" page
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57915280-0a106500-78ae-11e9-88c9-9d868d9e09af.png)

**Comment by rupalichavan9860** [comment]
"( Limit 100 chars )" is missing on Register page for fields First Name, Last Name and Middle Name
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57981356-f56dd180-7a53-11e9-85f2-10dd94293d35.png)

**Comment by rupalichavan9860** [comment]
Limit 100 chars : c in Chars must be capital(Chars) like other places for First Name,Middle Name and Last Name.
Same for Topic Name on Create New Topic and Topic Update page
Please refer attached screenshot
![Capture](https://user-images.githubusercontent.com/40416610/58121131-48967e80-7c24-11e9-83b2-a41eec312a88.PNG)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 First two commented issues are fixed but third commented issues are still exists.Please check latest comment with screenshot

**Comment by gautamv16** [comment]
@rupalichavan9860 can u pls after clearing cache now..

**Comment by rupalichavan9860** [comment]
@gautamv16 working on profile page and create new topic but still pending on topic update page 
![image](https://user-images.githubusercontent.com/40416610/58201784-94642900-7cf3-11e9-81c4-72a7a7b35bdd.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
