### ISSUE TITLE
Word wrapping in forums needs to be fixed.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#485]
Go to any forum thread post, and change the window size.
You will see words wrap on characters, instead of on words.
Making it very hard to re
ad.

**Comment by akuks** [comment]
Fixed and changes pushed to staging but there are some conflict issues hence the changes are not pushed to the Server.

**Comment by akuks** [comment]
@BrentAllsop @rupalichavan9860 Please test this bug and let me know if any modifications are required.

**Comment by rupalichavan9860** [comment]
@akuks Tested and looks good to me 
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
Yup, looking great so closing.
Thx
