### ISSUE TITLE
Fix Delegated Support.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#488]
When you delegate to anyone, in any camp, all direct support should be terminated (and not show in "supports" list).

After delegation, you should see all your supports, as being the same as the supports for who you are delegated to.  You should be able to see these supports are delegated, and should not have the option to delete individual supports.

If your supports are delegated, you should be able to remove all delegated supports, or convert all delegated supports to direct supports.

**Comment by gautamv16** [comment]
@BrentAllsop pls check flow once. Now in my support if user have delgated a support to any camp of a topic then individual support will be ignored and will not be shown in my support. There will be delegated nickname to whom user is supporting for that topic. Pls check and lets discuss in tomorrow meeting

**Comment by BrentAllsop** [comment]
There needs to be 2 distinct modes of support for a topic:
Direct support.  (can support any number of camps, in any order)
Delegated support.  (if you delegate to anyone, you abandon all direct support of any camps, and from now on, support exactly the camps of your delegate, in their order.
There can be no way to do both delegated and direct support of camps, on one topic.

**Comment by BrentAllsop** [comment]
If you have delegated your support to someone who has supported multiple camps.
Then, if you try to directly support camp ABC:

The new camp showed up with "Nick Name to Support (then bread crumbs.)
Instead of bread crumbs, it should say:
Nick Name to Support Above Camps.

In the my supports page, when it says: "Support delegated to Mike Gashler" it would be nice to show a non editable list of the camps on this topic Mike Gashler supports. in this form:
1: Revised Preface - 2019; 2: camp 2 name.
And make these the links to that camp.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 I am not able to see non editable list of the camps 
![image](https://user-images.githubusercontent.com/40416610/72683390-f7b18f80-3afc-11ea-8e37-a842c13e7068.png)

Please refer following comment
https://github.com/the-canonizer/canonizer.2.0/issues/488#issuecomment-495061466

**Comment by gautamv16** [comment]
@rupalichavan9860  This is not coming because may be RC has no camp supported under "Test Topic:issue562"

**Comment by gautamv16** [comment]
@rupalichavan9860 Yes it is coming blank because RC is not supporting any camp under this topic

**Comment by rupalichavan9860** [comment]
@gautamv16 RC is supporting "Test camp 1" Camp under topic "Test topic : issue 562"
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/72916287-cdafd580-3d67-11ea-975b-c3d1f30bbf92.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I have fixed this issue, pls test it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. This is not working for root camp(Agreement).Please refer attached screenshot
Rupali N has delegated their support to RC for topic: Testing : 11 dec 2019 / Agreement

![image](https://user-images.githubusercontent.com/40416610/72999640-a61f4280-3e25-11ea-86e8-d4f55c323164.png)

![image](https://user-images.githubusercontent.com/40416610/72999698-bd5e3000-3e25-11ea-88db-8978f04a7f23.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Everything is working for me now
@BrentAllsop I have checked this for multiple camps.Please refer attached screenshot 
Can you please check functionality and layout also and close if fine for you?
![image](https://user-images.githubusercontent.com/40416610/73047890-52e8d680-3e9d-11ea-8b75-33f2f2f87a24.png)

**Comment by BrentAllsop** [comment]
Yea, this looks good, so closing this.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop  I just found that choice number order is different for delegated one.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73149400-2922f000-40e7-11ea-953b-f00222840bf1.png)

![image](https://user-images.githubusercontent.com/40416610/73149417-4061dd80-40e7-11ea-8b02-23b82ffcc3d4.png)

Choice number order should display same for both direct supporter and delegated supporter.

**Comment by gautamv16** [comment]
@rupalichavan9860 these are not the choice number as it was not asked to show choice number. 
(In the my supports page, when it says: "Support delegated to Mike Gashler" it would be nice to show a non editable list of the camps on this topic Mike Gashler supports. in this form:
1: Revised Preface - 2019; 2: camp 2 name.
And make these the links to that camp.)
 These are just serial number to show the camps
@BrentAllsop Can you please confirm that if we need to show the choice number here also

**Comment by BrentAllsop** [comment]
@gautamv16, it looks to me like Rupali's first screen shot shows the list of camp, in order the person she is delegating to supports them.  The second screen shot is the actual support list for that person, in the order they have chosen. which is different.  These two lists should be the same, right?
Sorry about the serial number comment that was wrong, don't know where that came from, so my fault.
@rupalichavan9860 , can you provide links to the pages where you took those screenshots, so we can know for sure?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Karun already fixed the issue and asked me to test . I just tested and now I can see similar lists order for both the supporters.
This screenshots are from My Supports page so links will not work.I need to share my credentials,then only you can verify.Please let me know if required

**Comment by BrentAllsop** [comment]
OH.  OK, great.  Then if you are good with it, I'm OK with closing this.

**Comment by rupalichavan9860** [comment]
Yeah I am OK with this so closing the issue
