### ISSUE TITLE
Update blog footer : copyright year

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#489]
Expected Result : 
It should display copyright year as (2006 - 2019)

Actual Result : 
Blog footer copyright year is displaying as (2006 - 2018) 
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57461387-898dab00-7294-11e9-8c42-ec59c5d26611.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
I'm not seeing this.
Also, this should never be a problem.
All these types of issues should be automatically calculated, and should never be wrong, forever.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still I can see Blog footer copyright year as (2006 - 2018)
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/60484818-67bf0c00-9cb8-11e9-9747-b7168a46f66f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 Issue not fixed on live.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/62227156-0aae9700-b3d9-11e9-9d81-663bbbfa4ae5.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 This is not fixed yet.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop This issue is fixed on staging but as per discussion in yesterday's meeting we also need to include Privacy Policy and Terms & Services links on blog footer also.Please do the needful

**Comment by gautamv16** [comment]
@rupalichavan9860  I have added the Privacy Policy and terms & service link in blog footer on staging. Please check. if verified i will update it on live then.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I will close the issue after implementing automated test case for the same

**Comment by rupalichavan9860** [comment]
Done with automation test case so closing this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 I am facing the same issue(Blog footer copyright year is displaying as (2006 - 2018)) again after copying database and files from production to staging
And I can see Privacy Policy and Terms & Services at two places on blog footer.
Please refer attachment for details
![image](https://user-images.githubusercontent.com/40416610/68653214-40732800-0551-11ea-9c51-101720556839.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Privacy Policy and Terms & Services looks good.
But Still I can see Blog footer copyright year as (2006 - 2018).This may be due to copying database from production to staging 

![image](https://user-images.githubusercontent.com/40416610/68788087-c209a980-0668-11ea-9e5d-d06ebcb667e6.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.

**Comment by rupalichavan9860** [comment]
@gautamv16 Again copyright year is not getting updated automatically on blog footer.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/71707666-4f6bad80-2e11-11ea-8e08-0d70fe04f429.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  I have fixed it to 2020 year on production. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.It is working now but "All these types of issues should be automatically calculated, and should never be wrong, forever." 
It is developed like this?

**Comment by gautamv16** [comment]
@rupalichavan9860  I have changed this to get automatically updated for the current year
