### ISSUE TITLE
History pages should have bread crumbs at top of page, like camps.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#49]
Also, each object should have a link to the version of the object (with an as_of value in the URL.)

**Comment by gautamv16** [comment]
@BrentAllsop link to camp detail page added as per go live time as_of value.

**Comment by CanonizerJim** [comment]
Also remove the title line from the camp history block.

**Comment by BrentAllsop** [comment]
@gautamv16 ,
Yes, we've been using this feature, works great.
closing this issue.
