### ISSUE TITLE
Error Exception on "I agree with this change" check

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#493]
Click on "I agree with this change" checkbox on camp history page.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/57521504-1771a080-733e-11e9-911c-6306e3b1a232.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check this

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
