### ISSUE TITLE
Edit summary is not getting persisted on topic update page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#496]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Go to Manage/Edit This Topic
5. Click on "Submit Topic Update Based On This"
6. Observe Topic Update page

Actual Result : 
Edit Summary field is blank even if edit summary is present previously.

Expected Result : 
Saved Edit summary should get displayed on topic update page
Refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/57572452-23da2400-7438-11e9-9103-617f69c0f3c5.png)

![image](https://user-images.githubusercontent.com/40416610/57572464-39e7e480-7438-11e9-935a-7e405e082830.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 edit summary is only for ref and it must be displayed only on history. Submit new change have no use of it. In that case it must be blank so that user can provide their own edit summary.

**Comment by rupalichavan9860** [comment]
I was thinking like if some user wants to add his/her own edit summary along with original one.
@BrentAllsop Please confirm

**Comment by gautamv16** [comment]
edit summary is always for new change brief description.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
