### ISSUE TITLE
Acceleration of "go live."

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#50]
There are two parts to this idea. 

1. The first is adding a feature that would allow supporters of a camp to indicate agreement to changes prior to the one-week review period. Each supporter would have a checkbox on the history block for the record that would allow them to say they agree to the change. The change then would go live at the moment that everyone has checked the box.  This will require a new database table to temporarily store these values. Once the change goes live, all these temporary values will be cleaned out of the database. 

2. We want to give the submitter of a change a one-hour grace period where they can fix minor grammatical or spelling errors in their submission before the email notification of a change goes out to subscribers. This would also require adding a one-hour countdown timer to the history block indicating when the e-mail will be sent. The submitter would also have the option to manually end the countdown and send the email.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test 2nd point on development server only as it is not on staging as its a completly seperatly feature and i want it to test for first phase on development from your end then i will merge it with staging for final testing.

And then close this ticket as i am creating a new ticket for feature 1st. as that is a separate feature as well so both will be released seperatly one by one. @BrentAllsop is it ok to create seperate ticket for 1st part which is under development and we can release both seperatly.

**Comment by BrentAllsop** [comment]
Sure, creating seperate ticket for 1st part sounds great.

**Comment by gautamv16** [comment]
@rupalichavan9860 please close this one if 2nd point is ok as we have created seperate ticket for 1st part.

**Comment by rupalichavan9860** [comment]
@gautamv16 I am closing this as the 2nd feature is available now on staging and I have tested this.If I found any issue related to this feature I will create a separate issue for this.
