### ISSUE TITLE
Sort browse topics

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#502]
The list of topics on the browse page would be nice if it was sorted, first by the namespace (if all is selected) then sorted by topic name.

**Comment by BrentAllsop** [comment]
Before we create a namespace, we should verify there are no spaces (only "_"),
that it always begins and ends with "/"
And that it is unique.

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed it. please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Sorting is working fine.I can see topics list  displayed in sorted order first by the namespace (if all is selected) then sorted by topic name.
Namespace :
I just created the new namespace and found that following validations are missing 
1. I can create duplicate namespaces
2. I can create namespaces with spaces(spaces are then replaced by "-" in label name)
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/68270355-069eaf00-0083-11ea-98d6-26e1ccf4625c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and issue is still exists.Still I can create duplicate namespaces.Please refer attached screenshot.
![image](https://user-images.githubusercontent.com/40416610/69932709-314d1d80-14f2-11ea-838d-815c93a637dc.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Working when creating new namespace but not working when updating existing namespace.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
