### ISSUE TITLE
There is no way to go the Topic or Camp URL from the account setting page.

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#503]
After login when user goes to the "Account Settings"  and then go the "My Support" tab. There is no way to go to the Topic and Camp URL. User needs to search and then go the Topics and URL they support.

App must have a way where User directly visits the Camp and Topics they support.

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16  Tested and verified
