### ISSUE TITLE
Button Id's must be unique on Manage Profile Info page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#506]
Button Id's are not unique on Manage Profile Info page.
Verify,Confirm and Update button all are having same ID "submit" and because of this I am facing issues while creating automated test cases
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/58008123-586d7000-7b09-11e9-9c06-d0be87d3ba37.png)

![image](https://user-images.githubusercontent.com/40416610/58008181-763ad500-7b09-11e9-9785-75248c8712be.png)

![image](https://user-images.githubusercontent.com/40416610/58008247-966a9400-7b09-11e9-92d4-3f15b35b9129.png)

**Comment by BrentAllsop** [comment]
Good catch.  All IDs should remain unique, and consistent as pages change and improve, so as not to break tests.  The id values should also be very descriptive, describing how the various "submit" buttons are different, not just meaningless submit1, submit2, and so on.

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested this.But still "Verify" and "Confirm" buttons are having same ID "verify_phone_email".Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/60482177-190c7480-9cae-11e9-8e18-742b015e5297.png)

![image](https://user-images.githubusercontent.com/40416610/60482211-37727000-9cae-11e9-9b2f-64b2bdcc4884.png)

Is it possible to change the ID's otherwise I can face issue while automating test case..

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified
