### ISSUE TITLE
Video Podcast Block

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#512]
Create a video podcast section on the front page
![Screen Shot 2019-05-22 at 8 29 10 PM](https://user-images.githubusercontent.com/36485203/58226404-bd7cbd80-7ce3-11e9-9b09-e1f53dc9a929.jpg)

**Comment by BrentAllsop** [comment]
Create a fixed size div box.
Have a server side include, sourced within that fixed size div box.
File name  "video_podcast_block.html"
Provide a way for Jim to update that server side include file, from the admin page.

**Comment by rupalichavan9860** [comment]
I have checked this ,Canonizer Main Page layout is getting disturbed 
Advertisement block shifted to the end of the page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/60533228-b3a39c80-9d1c-11e9-8be3-d278c3ecbdcd.png)
@BrentAllsop @CanonizerJim Please check

**Comment by BrentAllsop** [comment]
Yes, this is a problem.  The add should be on the right bar, at least for desktop.
Can we put a div that forces a size that will not allow any div content to go outside of that block?

**Comment by rupalichavan9860** [comment]
@gautamv16 Layout issue is still exists when minimized the window. Advertisement block shifted to the end of the page.Please refer attached screenshot.
![image](https://user-images.githubusercontent.com/40416610/60874423-9eb39580-a255-11e9-9be7-df3f18856e4b.png)

@BrentAllsop @CanonizerJim Is it fine?Or it is an issue?

**Comment by BrentAllsop** [comment]
@rupalichavan9860, I'm not able to see any issues.
Do you still see anything that is questionable on staging.canonizer.com?

**Comment by rupalichavan9860** [comment]
@BrentAllsop According to Varun that need to be design from back end,So what ever design is setup-ed from back end it will work like that.
So please close the issue if it is fine.

**Comment by rupalichavan9860** [comment]
Only we need to change the video title before releasing to live site.
![image](https://user-images.githubusercontent.com/40416610/61187992-69180d80-a696-11e9-9e71-de992949c728.png)

**Comment by CanonizerJim** [comment]
Need to create a scrolling function so that the div box is square with the box on the left side of the page.
