### ISSUE TITLE
Some old URLs are still broken.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#513]
Some old URLs are still broken.  For example:

http://staging.canonizer.com/topic.asp/88/21

Contained in an old letter from Daniel Dennett I am now trying to reply to.

On staging, this non https url redirects to this broken URL missing one of the required "?"s:
https://staging.canonizer.comtopic.asp/88/21

On the live site, it just redirects to:

https://canonizer.com

Can we get this fixed for release 12?

**Comment by gautamv16** [comment]
@akuks please check staging server .htaccess file. I am not able to read it there. What changes you did last in htaccess ? This change is related to htaccess. But i cant find any htaccess file on staging.

Can you please check this.

**Comment by akuks** [comment]
There is a swap file created in staging for .htaccess. I didn't modified .htaccess file. File is there and intact and Swap file has been deleted.

**Comment by akuks** [comment]
http://staging.canonizer.com/topic.asp/88/21 redirect's to 
 **https://staging.canonizer.comtopic.asp/88/21** and this URL misses '/'. I think thats why we have an issue

**Comment by gautamv16** [comment]
@rupalichavan9860 and @BrentAllsop please check this issue. Solved on both server issue is related to ssl misconfigurations. Please close and let me know when to deploy 12th release

**Comment by BrentAllsop** [comment]
This looks great, so closing.  Thanks.

**Comment by BrentAllsop** [comment]
Oh, yes.  I forgot, we should be sure we have automated tests for all issues, before they are closed.
So I'm re-opening this one.  An automated test should be fairly easy?
@rupalichavan9860, close this if/once we have an automated test.

**Comment by rupalichavan9860** [comment]
Automated test case has been implemented successfully so I am closing this.
