### ISSUE TITLE
Multiple issues with approving new modifications.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#517]
The only person that can “object” is someone who was both:
•	A supporter of the camp, when modification submitted.
•	Currently a supporter of the camp.
•	Everyone else should not be able to object and not have an object button.

The approve check box should appear for any current supporter.
If someone checks the approve check box, it should approve for all delegators to them.

The definition of a “supporter” is anyone who supports (either directly or delegated) of this camp and any child camp.

So you should be able to “approve” a modification to go live for any parent camp of a camp you support.  Currently, the approval check box doesn’t show up for parent camps of camps you support.

Also, a modification should not go live, before the "go live" time, unless all supporters, and all sub camp supporters have indicated agreement.
Jim and I did this test:
1. Brent proposed a modification to an agreement camp statement.
2. Jim Bennett was an explicit supporter of the agreement camp.
3. Andrew fullen was an implicit supporter of that agreement camp (by being a supporter of one of the sub camps)
4. Jim Bennett clicked the "approval" check box on the pending change.
Expected behavior:  The change should not have gone live, because Andrew Fullen (sub camp supporter) hadn't approved the change yet.
Actual behavior.  The change went live, despite sub camp supporters not indicating their approval.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by BrentAllsop** [comment]
@rupalichavan9860 @gautamv16 @gautam
There are still issues not working correctly so I removed the fixed flag
Evidently anyone can object to any change in review.
Only people that supported that camp, when the change was first submitted for review, and who are currently supporting it, can object to a change.
This is true for all 3 types of changes.  Statement, Camp, and topic.
**We need to handle and test for this border case:**
Even if they left the camp, shortly after someone submitted a change, as long as they were a supporter, when it was submitted, they can rejoin, then object, till it does go live.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. According to first comment the change should not go live until sub camp supporter approval
As of now I am not able to see approval checkbox for sub camp supporters.
@BrentAllsop Can you please check and confirm if I am missing something ?

**Comment by BrentAllsop** [comment]
@rupalichavan9860 , that is correct.  When you explicitly join a camp, you implicitly support all parent camps up to and including the agreement camp.   A "Supporter" of a camp includes both  explicit and implicit supporters.  Both types of supporters have the same editorial control of that camp.

**Comment by gautamv16** [comment]
@rupalichavan9860 , I have fixed it. Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Now I can see approval checkbox for sub camp supporters , but changes are not going live even after all the approvals

**Comment by gautamv16** [comment]
@rupalichavan9860 I have also tested it and it is working fine. I have used below case.

I have created a topic with user A and from same user created a new camp( say camp1) under this topic. Now i logged in with user B and created new camp with user B ( say campB). Now with User A i have created a subcamp for  camp1 named camp3. 
I have supported this camp with user B. and with a new user C ( user also supporting agreement camp). Now If user A change any statement in Camp1 then it is going in review and when i checked it with User B and C i saw the checkbox to approve. now when i have approved from B and then C , changes goes live . I have repeated same for topic change and camp name change.
Let me know if i am missing something in this test case

**Comment by rupalichavan9860** [comment]
@gautamv16 Can you please check following scenario
Please refer https://staging.canonizer.com/statement/history/245-Test-topic---issue-517/1
In this RC and Rupali N are supporting Agreement camp
Rupali Auto is supporting 2 sub camps :  Camp 1 and Camp 2
Now when RC has proposed a change to Agreement camp statement It should go live when Rupali N and Rupali Auto click on "I agree with this statement change"

As of now both users agrees with the statement change but changes are not going live

@BrentAllsop Can you please check this once as me and Karun have some confusion

**Comment by gautamv16** [comment]
@rupalichavan9860 yes in your scenario there is issue, i have fixed that also . Can you test it again and verify

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified..Above scenario is working fine now.But I have one more doubt
Rupali N have submitted change for topic ,camp and statement, but can Rupali N object to self  modified changes?
Because as of now Rupali N is able to see Object button for statement change but not for Topic and camp.Is this an issue?
Please refer attached screenshot
Camp Statement
![image](https://user-images.githubusercontent.com/40416610/73612534-9b796000-4612-11ea-9563-2b3ca8b50577.png)

Topic
![image](https://user-images.githubusercontent.com/40416610/73612560-cbc0fe80-4612-11ea-8245-1fd393e6e788.png)

Camp
![image](https://user-images.githubusercontent.com/40416610/73612514-7c7ace00-4612-11ea-8bc5-78a1b3511f9b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I guess its an issue so i have implemented the same condition as for camp name changes on it also, the object button should not appear for user who is making a change. Pls test it 

@BrentAllsop Please correct me if i am wrong

**Comment by BrentAllsop** [comment]
Whether someone submitted a modification or not has no effect on whether they can object or not.
Non supporters can submit a change, but they can't object to it, unless they meet the same support requirements of everyone else.
Only requirements for anyone to be able to object (whether they are the submitter or not):
1. Supported the camp (or sub camp) when the change was submitted.
2. Currently supporting the camp (or a sub camp).

General idea: Anyone can submit any change, only camp supporters (including sub camp supporters) can object.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . I have submitted 2 changes for each topic, camp and statement.But I can see object button only for the latest changed record(for statement and camp) and I can see Object button for both topic change records

**Comment by gautamv16** [comment]
@rupalichavan9860 Object button should be there for each change until they are in review. i have changes it. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now.
@BrentAllsop Can you please test this issue with your scenarios (If I missed some scenarios)and close if fine for you?

**Comment by BrentAllsop** [comment]
The case where someone joins a camp, after a change has been submitted, solely to object, only to leave the camp, once they object is still a problem.  They can still "game the system" by doing this.
The "object" button, and the "I agree with this change" check box on yellow (in review) changes, should only exist for people that are currently supporting that camp AND were supporting the camp when the change was submitted.  And their OK, shouldn't be required for it to go live, even if they are a supporter, but they weren't supporting it when it was submitted.

**Comment by gautamv16** [comment]
@rupalichavan9860 , @BrentAllsop . I have fixed it. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested by Brent and me.Working fine for both so closing this issue
