### ISSUE TITLE
Error Exception when user click on some topic name/camp name on My Supports page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#518]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Account Settings->My Supports
4. Click on " Testing 1: change on 12/5/19" or on camps for the same topic

Or
Click on "https://staging.canonizer.com/topic/192-Testing%201:%20change%20on%2012/5/19"

Actual Result : 
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59007377-c7ee9980-8843-11e9-8b17-bc286cab7d4b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please test and close then i will deploy 12th release. These are some fix soon issue to deploy 12th release

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
