### ISSUE TITLE
Irrelevant data on agreement page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#519]
I found some irrelevant data on agreement page while testing .
It  is getting cleared after clearing cache but it is appearing again after sometime.
Please refer attached screenshot.
![image](https://user-images.githubusercontent.com/40416610/59019123-0ba5cb00-8865-11e9-8bff-1c0112f00437.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  please test and close then i will deploy 12th release. These are some fix soon issue to deploy 12th release

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
