### ISSUE TITLE
Old record values used on main page topic list.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#52]
In the topic lists, on the main canonizer.com page, the topic names are names from old versions of the camp record.

**Comment by BrentAllsop** [comment]
Also, in the camp page it displays the current values for the topic and camp records.
It is not showing the right version of the name space value.:
http://canonizer.com/canonizer/public/topic/131-Create-Topic-Steps/1

This is the one I noticed.  I suspect other values may be incorrect, also, possibly on camp record also?

Found another one:
In the browse page, it is showing old values, also.  Look for the above topic on that page.  Indicates there is no name space for that topic, when the current live version has a namespace for it.

Found another (thought this one was fixed?):
http://canonizer.com/canonizer/public/topic/105-How-to-mesure-the-consciousness--/1
In the camp outline, the name of the topic is "elkhyari", a very old version of the name.
The current version name is: "Consciousness Srvy Prjct"

**Comment by gautamv16** [comment]
@BrentAllsop please test these Karun fixed all these today cleaned and tested.

**Comment by BrentAllsop** [comment]
@gautamv16,
It looks like the browse page is still using old topic names.
Especially see the browse topics /organizations/mta/
Many of those have been recycled to general topics with different names.

**Comment by gautamv16** [comment]
@BrentAllsop those topic which are recycled to general will not come under /organizations/mta those will come under General and for browse topic now i have developed it in wa with asofdate value so that version of topic will come. Please test and lets discuss in meeting.

**Comment by BrentAllsop** [comment]
@gautamv16 
Correct, when we recycled them, we changed them from MTA topics to general topics, as they were no longer needed for the MTA.

When I set the main canonizer.com page to /organizations/mta/, many of the ones that are no longer mta topics are still showing up.

For example, this topic is now general namespace:
https://staging.canonizer.com/topic/11-New-ExpertNet-Name/1
But it is still showing up on the main page, when /organizations/mta/ is selected?

Also, this topic is still showing up in the brows list for the /organizations/mta/:
https://staging.canonizer.com/topic/11-Should-we-pray-at-Monthly-MTA-Board-Meetings-/1
even though it is now in the general name space.

**Comment by gautamv16** [comment]
@BrentAllsop this is not feasible in this way as both are now seperate entities. Both records have unique values based on different condition. Either we have to set some status for those records which are recycled.

Think like this, if you select general those are coming, now there is record in database for /organization/mta/ namespace and when a where clause do namespace='/organization/mta/' then old will show as you have no parameter to satisfy the false condition as where always check first.

**Comment by gautamv16** [comment]
@BrentAllsop please test this now. @karun done with this.

**Comment by gautamv16** [comment]
@BrentAllsop  please test this..

**Comment by BrentAllsop** [comment]
Verified this is fixed, closing.
