### ISSUE TITLE
objected to records are being used when "include review" is selected.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#520]
If you go to this URL to an agreement statement:
https://staging.canonizer.com/topic/81
and the select "include review"
it is using the topic name "daniel dennett" which is the value in an objected to record, that should not be used.  Objected to records should never be used.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 please check and close so that i can deploy 12th release now.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Please test and close if fine for you

**Comment by rupalichavan9860** [comment]
@gautamv16 Supported Camps page, Canonizer Forum Details page, My Supports page are still displaying objected topic name .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59338913-deec2a80-8d20-11e9-8e2b-7b175b49c79e.png)

![image](https://user-images.githubusercontent.com/40416610/59339190-55892800-8d21-11e9-894e-a440369c2638.png)

![image](https://user-images.githubusercontent.com/40416610/59339308-8f5a2e80-8d21-11e9-99d2-a7525dbcd50f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 please check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. For topic it is working fine now.
But still objected records are displaying for camp name on My Supports and Supported Camps page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59509335-64610d80-8ece-11e9-8092-22b1b82cacdc.png)

![image](https://user-images.githubusercontent.com/40416610/59509461-b73ac500-8ece-11e9-97fa-a9fbbce31606.png)

![image](https://user-images.githubusercontent.com/40416610/59509387-8195dc00-8ece-11e9-8a0d-31b515270f3b.png)

**Comment by rupalichavan9860** [comment]
I have tested for topic and camp objected mail also.In objected mail topic name and objected camp name is displaying as objected topic name and objected camp name .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59510855-6f1da180-8ed2-11e9-804b-81360bfff359.png)

![image](https://user-images.githubusercontent.com/40416610/59510976-b9068780-8ed2-11e9-979b-0883e4aba142.png)

![image](https://user-images.githubusercontent.com/40416610/59511559-3a124e80-8ed4-11e9-9645-b2cf93e62882.png)


![image](https://user-images.githubusercontent.com/40416610/59511518-1e0ead00-8ed4-11e9-841b-8627485e0c78.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is done. But what i have observed that testing or test cases for single bug or feature is not created properly or you dont have test cases related to single issue. Like this issue related to objected topic and camp name there must be test case for both manual and automated where you must have all places where topic name and camp name is effecting must be tested once so that we can solve all once. Otherwise its taking lots of time to work on single issue several times. Our test cases must have possible location where single source is effecting the feature. @BrentAllsop your feedback on this.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and working fine now.
@BrentAllsop Please test and close if fine for you

**Comment by BrentAllsop** [comment]
Yes, it's working, so closing.
