### ISSUE TITLE
Camp forum email issues and doubts

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#521]
1. ',' is missing after username in thread created email.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59253786-95caa680-8c4c-11e9-8325-79b3fc26870d.png)

2. Do we want supporters name(like Hi Rupali Chavan,) or Hi Canonizer User is fine in thread created and post submitted mails?Please confirm

![image](https://user-images.githubusercontent.com/40416610/59253893-cd395300-8c4c-11e9-8d9d-0b791682d5fe.png)

![image](https://user-images.githubusercontent.com/40416610/59253935-e3471380-8c4c-11e9-983a-0e3fe96d129e.png)

3. Is 'Note' necessary in post submitted mail? Because this is not present in thread created mail. Please refer attached screenshot
 
![image](https://user-images.githubusercontent.com/40416610/59254159-4cc72200-8c4d-11e9-8705-af85906a1f00.png)

**Comment by BrentAllsop** [comment]
Let's talk about this in a meeting.
I think more information is better, so person's name is better than "canonizer user" in all cases.
I Don't think we need to send out a notification, if someone creates a new thread.
But all direct supporters of a camp (always includes direct supporters of all sub camps) should be notified for all posts.  So we do need the "Note:" for all thread posts, and all camp modification proposals, in case people no longer want to receive these.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Note is always blank even if I have added note while creating/updating camp.
Which note do we want in forum mails?
Want to discuss on this

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
