### ISSUE TITLE
Page crash on "Create New Camp" link 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#522]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings->My Supports
4. Click on any topic name
5. Now Click on "Create New Camp" link from left menu

Expected Result : 
It should display respective page

Actual Result : 
It is displaying "NotFoundHttpException".Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59427991-acfac700-8df9-11e9-8dc7-c98a687c1180.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash again on "Create New Camp" link when I am opened topic from camp statement and clicked on "Create New Camp" link.
Steps to reproduce : 
1. Go to "Algorithm Information"
2. Click on "Mind Experts"
3. Click on link " Theories of Conscoiusness. " or "Mind Experts topic " link
4. Click on "Create New Camp" link

Expected Result : 
Respective page should get open

Actual Result : 
It is displaying "NotFoundHttpException".
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59578136-70261d00-90e4-11e9-92b6-783c388b17f9.png)

**Comment by rupalichavan9860** [comment]
Same for following scenario : 
1. Go to "Algorithm Information"
2. Click on "Mind Experts"
3. Click on "Manage/Edit Camp Statement"
3. Click on link " Theories of Conscoiusness. " or "Mind Experts topic " from camp statement history page
Click on "Create New Camp" link

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified.
