### ISSUE TITLE
Page crash - ErrorException while submitting topic objection

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#523]
Steps to reproduce :  
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to any topic
4. Go to topic history and Click on Object
5. Enter data in mandatory fields and click on Submit Objection

Actual Result : 
I am getting ErrorException .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59689339-1f561780-91fd-11e9-951c-bef5dac688bf.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 can u pls check just cleared server cache.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
