### ISSUE TITLE
Page crash on "Create New Camp" on live

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#524]
Steps to reproduce : 
1.Go to https://canonizer.com
2.Go to Topic https://canonizer.com/topic/168-Test2/1
3.Click on "Create New Camp"

Actual Result : 
I am facing the issue for this topic only as it is displaying "No camp data available." even if data is available.When I click on "Test2" it is displaying camp data 

![image](https://user-images.githubusercontent.com/40416610/59896638-f5704100-9406-11e9-9cf1-df1d9f0b6469.png)

But When I click on "Create New Camp" link directly(Without clicking on "Test2") I am getting page crashed.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/59896728-497b2580-9407-11e9-819d-237f472e3747.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is not page crash. After debugging lot i found there is no such url exist and there is no such topic with such camp id exist. How you can go directly to a invalid camp ? From where you are trying to access this url ? You cant access this url from anywhere. So this is invalid.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
