### ISSUE TITLE
Name with Special characters "AntÃ³nio DamÃ¡sio" at mind experts Agreement Camp Page.

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#526]
https://canonizer.com/topic/81-Mind-Experts/1 has name ("AntÃ³nio DamÃ¡sio") with Special characters. I think we need to fix it as per our previous discussions.

Happy to discuss it in next meeting.

**Comment by akuks** [comment]
Fixed on staging.

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified
