### ISSUE TITLE
Add/Edit News-Link invalid issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#527]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Browse and select any topic
4. Go to Add News/Edit News
5. Enter "https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1" in Link field
6. Click on "Create News" on Add News or "Submit" on Edit News

Actual Result : 
1. It is displaying error message "The link format is invalid." on Add News and "Link is invalid" on Edit News.
2. "https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1" is considering as a invalid link

Actual Result : 
1.Error message must be uniform for Add and Edit News
2.I think "https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1" should be valid **Please confirm**
![image](https://user-images.githubusercontent.com/40416610/60354624-42957980-99ea-11e9-8d31-0a003d733979.png)

**Comment by rupalichavan9860** [comment]
Error messages must be uniform when user doesn't put data in mandatory fields.As of now error messages on Add News and Edit news are not uniform
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/60355516-39a5a780-99ec-11e9-93c4-739d4c00aee6.png)

![image](https://user-images.githubusercontent.com/40416610/60355558-4f1ad180-99ec-11e9-881f-08dc11fd9f80.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
