### ISSUE TITLE
Better handle non existent topics and camps.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#53]
If you specify a topic number in a topic URL that doesn’t exist, the error message currently states:

Error! Selected camp is not available in the selected parameters, Please check the filters for more accurate results.

It should handle this case better, and state:

“Topic <number> does not exist.”

Or for camps that do not exist, should similarely say:

“Camp <number> does not exist.”

**Comment by gautamv16** [comment]
@BrentAllsop done

**Comment by BrentAllsop** [comment]
@gautamv16 Could we add the topic or camp number that does not exist, to the error message?

**Comment by BrentAllsop** [comment]
Looks Good.
