### ISSUE TITLE
Don't pre populate "Edit Summary" or note field when making modification.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#530]
Currently, when someone selects
Submit <topic | camp | statement> update based on this version
it goes to an edit page.
The  "Edit summary (Briefly describe your changes)" field should not be pre populated.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Previously it was working like this way only but I only submitted issue for edit summary pre populate and asked for your confirmation in issue #496.
My thinking was "Edit Summary" should be persisted for reason "if some user wants to add his/her own edit summary along with original one "
We need to revert the changes if you don't want pre poulate. Please confirm

**Comment by BrentAllsop** [comment]
I guess I forgot about this.
Let's discuss this in the next meeting.

**Comment by gautamv16** [comment]
@rupalichavan9860 changed back as per brent. Pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
