### ISSUE TITLE
Don't use "Agreement" in URL.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#531]
If you click on the "agreement" link in the camp tree, or in the bread crumbs, the URL uses agreement, instead of the topic name.  It should use the topic name instead.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Issue is not fixed yet.Please refer following steps
1. Go to Browse->Theories of Consciousness
2. Click on Create New Camp link or `<Start new supporting camp here>`

3. Click on Agreement link in the bread crumbs
Please refer following screenshot
![image](https://user-images.githubusercontent.com/40416610/63190170-4c02a000-c083-11e9-92b7-4fcaecf40cff.png)

**Comment by rupalichavan9860** [comment]
It is not working for Camp forum,Add Camp Statement,Supported Camps,Camp History pages bread crumbs also.

It is not working for following scenario also :
1. Go to Browse->Theories of Consciousness
2. Select any child camp and click on Agreement link in the bread crumbs ,the URL uses agreement, instead of the topic name

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still I can see "Agreement" in URL when I click on agreement link from following places
1. Camp Forum->Click on Agreement link
2. Supported Camps(Directly Join or Manage Support)->Click on Agreement link
![image](https://user-images.githubusercontent.com/40416610/63840224-520b5180-c99e-11e9-9d8a-4c9d2a40071f.png)

**Comment by rupalichavan9860** [comment]
Tested .This is working fine now but I need to update the respective automated test case.I will update the same and close the ticket

**Comment by BrentAllsop** [comment]
Great, thanks for being sure we don't close things till we have working test cases.

**Comment by rupalichavan9860** [comment]
Done with automation testing so closing this issue
