### ISSUE TITLE
Page crash on My Supports page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#533]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Login with valid email and password
3. Go to Account Settings
4. Click on My Supports sub tab

Expected Result : 
Respective page should get open

Actual Result : 
It is displaying ErrorException.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/60943369-708c8f00-a303-11e9-9dd1-de90b9facdc7.png)

Note : 
I am facing this issue for following user accounts
rupali.chavan9860@gmail.com and rupali.nimbalkar22@gmail.com

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
