### ISSUE TITLE
BCC all canonizer email to brent.allsop@canonizer.com

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#534]
I would like to get a blind copy of any e-mail sent to users, other than personal information like login credentials.

I need to know when new activity occurs.

**Comment by BrentAllsop** [comment]
The number of e-mails / day or week, would be a valuable metrick of Canonizer traction.

**Comment by gautamv16** [comment]
@BrentAllsop its done now there is setting in env file to setup bcc email from where now i have developed a way which will send all bcc email to that email address.

**Comment by BrentAllsop** [comment]
I see this working great.
