### ISSUE TITLE
Create New Camp page URL issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#535]
Create New Camp page is displaying different URL when user click on Create New Camp link from different places
For Example for topic https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1
1. Go to Browse and select topic Theories of Consciousness->Click on <Start new supporting camp here> URL is
    https://staging.canonizer.com/camp/create/88/1
2. Go to Browse and select topic Theories of Consciousness->Click on Create New Camp link from left menu URL is
    https://staging.canonizer.com/camp/create/88-Theories-of-Consciousness/1
3. Go to Browse and select topic Theories of Consciousness->Click on Agreement ->Click on Create New Camp link from left menu URL is
   https://staging.canonizer.com/camp/create/88-Agreement/1

In second case URL is displaying topic name also.
I think this should be uniform.Please confirm

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16  This issue is not fixed yet.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
Click on "Start new supporting camp here" URL is displaying as https://staging.canonizer.com/camp/create/88/1

**Comment by rupalichavan9860** [comment]
Tested .This is working fine now but I need to update the respective automated test case.I will update the same and close the ticket

**Comment by rupalichavan9860** [comment]
Done with automation testing so closing this issue
