### ISSUE TITLE
Need a fast way to snapshot and restore system state (DB and files)

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#537]
This should go into the next release, and be prioritized over any other issues, except fatal crashes.

We need to design and implement a fast and easy way to take a snapshot of the DB and canoniazer.com/files directory.
We need to have an easy way to transfer such a dated snapshot to a backup, or a dev system like staging, and be able to easily restore the entire state to exactly what is live.

For example, the data on staging is way old and out of date.
It should be easy to push a button (or something) on production to make a snapshot.  We should be able to make easy dated copies of this for backup.  Also, we need to have an easy way to restore this into any dev (or maybe live, if needed), or between any set of systems for testing purposes.

This should include restoring everything but the blog data.

**Comment by BrentAllsop** [comment]
If anyone notices staging more than a week out of date from live, we should do a restore.
In other words, we should copy state to staging once a week or something.

**Comment by BrentAllsop** [comment]
It should be easy to have test scripts that add new data, starting from a clean live copy state for testing purposes.
The tester should be able to easily restore to live state, overriding test data, so test of data creation can be repeated, automatically.

**Comment by BrentAllsop** [comment]
We want to avoid putting junk test data in live data, as much as possible.

**Comment by gautamv16** [comment]
@rupalichavan9860 please test it from admin panel

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Please test and close if fine for you

**Comment by rupalichavan9860** [comment]
Tested and verified.So closing this issue
