### ISSUE TITLE
not found pages result in exception error.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#539]
If you go to anything that does not exist
https://canonizer.com/garbage
It gives a non existing page http exception error.

We should have a more graceful, "Sorry, the page you are looking for could not be found." error, without the exception.

**Comment by BrentAllsop** [comment]
The page should have a link back to https://canonizer.com, as the logo.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I will close this once the automated test case implemented

**Comment by rupalichavan9860** [comment]
Done with automated test case so closing this
