### ISSUE TITLE
Need to add adds.txt to canonizer.com document root.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#541]
Google now requires an adds.txt file to be in Canonizer.com document root.
It must contain this 1 line:

google.com, pub-6646446076038181, DIRECT, f08c47fec0942fa0

**Comment by gautamv16** [comment]
@rupalichavan9860 please check and confirm

**Comment by BrentAllsop** [comment]
This is working.
I'm going to close this for now.
But it may be that we need to turn this off on staging, to prevent google adds from thinking our tests are trying to scam them.
