### ISSUE TITLE
Need Canonizer "Terms of service" and "Privacy Policy" urls

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#542]
There is probably a standard location to put this, on a website.

Twitter API, required by tennagraph.com, needs to supply these to work.

**Comment by BrentAllsop** [comment]
Jim created the "terms of service" and "privacy policy" text to the end of the google doc Canonizer plans (at the end of the document):
https://docs.google.com/document/d/1UsQ_fpKM89eJUI85fDMWzA_7TNvEXDbodJ3V-AWVhQ8/edit?usp=sharing

**Comment by BrentAllsop** [comment]
Replace the canonizer version line on the footer to a link to these two documents.

**Comment by rupalichavan9860** [comment]
Do we need this on the footer of blog and canonizer emails also?

**Comment by BrentAllsop** [comment]
Good idea to add links to these in the footer of all e-mails.
Also, I think it would be better if both the terms of service link and the privacy link were on the same line, with some space (like a tab) between them.

**Comment by rupalichavan9860** [comment]
Yeah..else we can use separator also e.g "." or "|"

**Comment by BrentAllsop** [comment]
How about we put the privacy policy on the same line as, and to the left of the patent, and the terms of service to the right of the patent?  Takes up less space that way.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test and close

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Looks good now.
@BrentAllsop Please check and Do we need this on the footer of blog and canonizer emails also?Please confirm

**Comment by BrentAllsop** [comment]
Yes, let's add these to the footers of all outgoing e-mails before we close this one.
But this additional work is probably a low priority.

**Comment by gautamv16** [comment]
@rupalichavan9860 as on email footer links are designed and added. On blog Jim need to add links if required. But i dont think we need on blog as blog is seprate entity and blog then must have its own privacy and policies, we cant use canonizer.com policies there in blog. So as per me its not required same url on blog.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified for email footer also.
"Version - Canonizer 2.0" is available on email footer but missing on all canonizer pages.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/64100973-65496300-cd8a-11e9-86e2-c0eb56e5ae8d.png)

![image](https://user-images.githubusercontent.com/40416610/64101018-801bd780-cd8a-11e9-9b4a-455d9fecea99.png)

**Comment by rupalichavan9860** [comment]
As per discussion this is not an issue so closing this
