### ISSUE TITLE
Email Format issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#543]
As per discussion(Topic name and camp name should be separated by "/" instead of ":" and after keyword topic/camp/statement ":" should present )  we need to change the format for some emails.Please refer following screenshots
1. Objected to proposed change for camp
It should be "Rupali N has objected to your proposed change submitted for camp : 123456789012345678901234567890 / test camp 1" 
instead of "Rupali N has objected to your proposed change submitted for camp 123456789012345678901234567890 : test camp 1"

![image](https://user-images.githubusercontent.com/40416610/62117411-832e2e80-b2d9-11e9-869e-bba1ccff04d5.png)

2. Objected to proposed change for camp
![image](https://user-images.githubusercontent.com/40416610/62117869-621a0d80-b2da-11e9-9656-3e65f249ee28.png)

3.Objected to proposed change for statement
![image](https://user-images.githubusercontent.com/40416610/62118136-cb018580-b2da-11e9-9863-c469053b6416.png)
 and All places that use a number like this, should be changed to a more informative value, like the camp name.For more details please refer https://github.com/the-canonizer/canonizer.2.0/issues/437#issuecomment-477845843

4. Delegated support
![image](https://user-images.githubusercontent.com/40416610/62118670-bb367100-b2db-11e9-84bc-b6820dde7c93.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Objected to proposed change for statement mail format is not proper yet.
All places that use a number like this, should be changed to a more informative value, like the camp name.For more details please refer #437 (comment)
![image](https://user-images.githubusercontent.com/40416610/65484335-ac73d100-debc-11e9-93c3-986ff6212834.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and it is displaying blank after "statement : "  .Is it fine?Please confirm
Please refer attachment for more details
![image](https://user-images.githubusercontent.com/40416610/66285809-0c6e6c80-e8ec-11e9-9ef3-c92150720357.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested and looks fine.Closing this issue
