### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#544]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/ or https://canonizer.com/
2. Go to bottom of the canonizer home page and click on "^" icon
3. Now go to Chrome->More tools->Developer tools
 
Actual Result : 
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/62871560-521e1700-bd39-11e9-9153-356b4e8be984.png)

And when I click multiple times on "^" icon it is increasing the number of errors in console.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/62871685-914c6800-bd39-11e9-9e56-f28bf1c3a0a1.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
