### ISSUE TITLE
Label name is not proper for camp change agreement checkbox

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#545]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Go to Browse and select any topic
3. Go to any topic and update the camp
4. Login with other supporter and see the camp history page for agreement checkbox

Expected Result : 
It should be specific.
Label name for checkbox should be "I agree with this camp change" like on statement history 

Actual Result : 
Label name is displaying as "I agree with this change"
Please refer following screenshots

![image](https://user-images.githubusercontent.com/40416610/63648195-b4b7df80-c749-11e9-9412-6dd4c7b03f3e.png)

![image](https://user-images.githubusercontent.com/40416610/63648211-f3e63080-c749-11e9-94d6-3a4f2c3c4af5.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
