### ISSUE TITLE
robots.txt. Needs to disallow all history pages.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#546]
Only live content should show up in Google searches.  No history.

**Comment by BrentAllsop** [comment]
Robots.txt should specify that search engines only scan these pages:
https://canonizer.com
https://canonizer.com/topic/*
https://canonizer.com/forum/*
https://canonizer.com/blog/*
https://canonizer.com/video/*
This is for only the live production server.
The default robots.txt checked into git should disallow all searches for anything but production.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this ?

**Comment by BrentAllsop** [comment]
@gautamv16, how can we test this?
The robots.txt needs to be different in production than it is on all other machines.
Can you list the two different robots.txt here, for both production and non production.
And describe the way these are managed in both production and all other machines?

**Comment by BrentAllsop** [comment]
Let's have the default robots.txt checked into get be one that turns of all search spidering.
Then create a robots.production.txt that turns on search engines for the above listed pages.
Then let's add a step to the READ.me file that describes this install step required if searching of the system by search engines is desired.

**Comment by gautamv16** [comment]
@BrentAllsop I have added robots-production.txt file and also updated README.md file for installation

**Comment by BrentAllsop** [comment]
The current robots.txt is still only:
    User-agent: *
    Disallow: /settings
    Allow: /

And I'm not seeing:
https://canonizer.com/robots-production.txt

**Comment by gautamv16** [comment]
@BrentAllsop I have updated the robots.txt on production and added it to .gitignore so it will not get updated

**Comment by BrentAllsop** [comment]
We need to fix robots-production.txt
so that it is for all robots, not just googlebot.

And also, once this is fixed, it needs to be deployed on production.

**Comment by gautamv16** [comment]
@BrentAllsop  I have fixed it for all robots and deployed it on production

**Comment by rupalichavan9860** [comment]
@gautamv16 Can you please add the steps for how to test this issue?

**Comment by gautamv16** [comment]
@rupalichavan9860 go to below site

https://en.ryte.com/free-tools/robots-txt/

and check the urls above if those are allowed and all other url than above in the side should be disallowed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I have tested all the above urls and they are allowed and others (history urls) are disallowed.So closing this issue
