### ISSUE TITLE
Hide other namespace in Manage Topic page, when not selected.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#55]
In the "Manage Topic" page, the other namespace edit box should only show up when selected.

The note for that edit box says:
"Note: Name space is categorization of your topic, it can be something like: General,crypto_currency etc."

This should also only show up, when "other" is selected, and it should say:
"Note: Name space for hierarchical categorization of topics.  It can be something like: /crypto_currency/, /organizations/<your org name>/ etc... It must start and end with "/"

When this is submitted, it should be checked before creating it.
Can't be blank, can't be General, can't be any existing namespace, must begin and end with "/"

doing these checks on client side (along with server side checks) would be even better.

**Comment by gautamv16** [comment]
@BrentAllsop and @rupalichavan9860 this feature is done. Here please note onething, the validation of "/" in start and end of the namespace is not there as it will automatically inserted by system if user didnt added it so we dont need to show there as system to automatic work for this. 

You can create automated test and start testing. Please check and let me know.

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested this and working fine for me for when user selects "Other" namespace .But user is not able to select any other namespace except "Other" and even previously selected namespace is also not displaying on Manage Topic page.Please refer issue #303 
@BrentAllsop Please check and close if fine for you

**Comment by gautamv16** [comment]
@rupalichavan9860 its already solved with 303 please cross check
