### ISSUE TITLE
My Supports page layout issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#550]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Click on logged in username and Go to Account Settings->My Supports

Expected Result : 
Camp name layout should be inline with topic name layout

Actual Result : 
Layouts are not inline
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/63742886-f23a7b00-c8b7-11e9-91d5-ba078c53b198.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 This issue is still exists for case : delegated support
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69600910-6102ae00-1038-11ea-91ae-9a97da073ab0.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Layout looks good now but I can see following extra contents on page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/72243248-6e3c2200-3611-11ea-9ff8-d153bcbcb587.png)


![image](https://user-images.githubusercontent.com/40416610/72243716-a55f0300-3612-11ea-89a0-a14e45142434.png)

**Comment by rupalichavan9860** [comment]
Ohh.I just gone through this https://github.com/the-canonizer/canonizer.2.0/issues/488#issuecomment-495061466

but supported camp list is blank
![image](https://user-images.githubusercontent.com/40416610/72245239-1a800780-3616-11ea-8a19-fbbfa0e51c64.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 another issue is present for the supported camp list feature so closing this
