### ISSUE TITLE
Instant go live error

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#551]
Create a new topic.
Have user A support the agreement camp.
Create a camp, with statement.
Have only user B support the camp.
User B adds a modification to the camp statement

Expected Behavior:
Since user B is the only supporter of the camp, his change should go live instantly

Error:
It goes into review mode for one week, as if user A supports more than the agreement statement.

**Comment by BrentAllsop** [comment]
This also occurs in other cases than just this.
Another case is when someone is supporting a competing camp, not just a parent camp.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can you please check and close if fine for you.

**Comment by BrentAllsop** [comment]
Yes, looks great, so closing this.

**Comment by BrentAllsop** [comment]
There is another issue along these lines.
A change should go live as long as all direct supporters agree.
Delegated supporters should not prevent something from going live.
If you have one direct supporter, and one supporter delegating to that one direct supporter, a change submitted by the one direct supporter does not go live, instantly, as it should.
Only direct supporters should have the option to click on "agree" and help it to go live, and only the agreement of direct supporters is necessary for the change to go live.

**Comment by BrentAllsop** [comment]
Have a camp with one direct supporter (name: dir) and one delegated suporter to dir (name: del)
Have dir propose a change.
Expected behavior:
Dir should have the "agree" option to make it live.
Del should not have the "agree" option to make it live.
Actual behavior is just the reverse.  Del has the option, and not Dir.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine for me.
@BrentAllsop Can you please check and close if fine for you?

**Comment by BrentAllsop** [comment]
Tested, and working great, so closing this one.
