### ISSUE TITLE
TokenMismatchException error on multiple click on login page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#553]
Steps to reproduce : 
1. Go to https://staging.canonizer.com
2. Click on Login
3. Enter Email and Password
4. Click on Login button multiple times

Expected Result : 
User should get logged in
Actual Result : 
It is displaying TokenMismatchException .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/64837836-00a1ca00-d60e-11e9-97b4-c0bccaad6376.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
