### ISSUE TITLE
Canonizer Admin Issues -1

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#554]
Following are the list of issues : 
Login Page : 
1. All mandatory fields should be marked with * sign
2. All error messages should be in red color
![image](https://user-images.githubusercontent.com/40416610/64934234-faf2f100-d866-11e9-937c-1b626cfbad1c.png)

Namespace Page : 
Add Namespace : 
1. Click on Add Namespace link -> Page name should be Add Namespace or link name should be Create Namespace
![image](https://user-images.githubusercontent.com/40416610/64934288-76ed3900-d867-11e9-8016-ced42a6d360c.png)

![image](https://user-images.githubusercontent.com/40416610/64934307-8e2c2680-d867-11e9-99e0-4f7a50cff034.png)

2. All mandatory fields should be marked with * sign
3. Error messages should be present for mandatory fields and All error messages should be in red color
4. When user doesn't enter in any field and directly click on "Submit" button it is displaying page crash
![image](https://user-images.githubusercontent.com/40416610/64934359-e531fb80-d867-11e9-8382-6a74705d5d5c.png)
4. After creating new namespace page is redirecting to Dashboard page instead of Namespace list page

Edit Namespace : 
1. User is able to edit Namespaces with blank spaces
![image](https://user-images.githubusercontent.com/40416610/64934425-570a4500-d868-11e9-96bc-e67de4d02d95.png)
2. All mandatory fields should be marked with * sign
3. Error messages should be present for mandatory fields and All error messages should be in red color
4. After editing namespace page is redirecting to Dashboard page instead of Namespace list page

Namespace Request : 
Add Namespace : 
1. Click on Add Namespace link -> Page name should be Add Namespace or link name should be Create Namespace
2. All mandatory fields should be marked with * sign
3. Error messages should be present for mandatory fields and All error messages should be in red color
4. When user doesn't enter in any field and directly click on "Submit" button it is displaying page crash
5. After creating new namespace page is redirecting to Dashboard page instead of Namespace list page
6. After creating new namespace ,namespace is getting added in Namespace List instead of Namespace Request list.Is Namespace and Namespace Request are same?

Templates : 
1. Link name and page title name must match
![image](https://user-images.githubusercontent.com/40416610/64934689-13183f80-d86a-11e9-877d-4a88c377df4c.png)

2. Edit and Delete template are not working.It is displaying blank page 
![image](https://user-images.githubusercontent.com/40416610/64934749-92a60e80-d86a-11e9-9cce-ea21e4cc0084.png)

![image](https://user-images.githubusercontent.com/40416610/64934764-af424680-d86a-11e9-9ccf-a2423443ecb3.png)

Create Template : 
1. All mandatory fields should be marked with * sign
2. Error messages should be present for mandatory fields and All error messages should be in red color
3. When user doesn't enter in any field and directly click on "Create" button it is displaying page crash
![image](https://user-images.githubusercontent.com/40416610/64934717-51adfa00-d86a-11e9-9651-0a4f1831e7c7.png)

Send Emails : 
1. Link name and page title name must match
![image](https://user-images.githubusercontent.com/40416610/64934831-0c3dfc80-d86b-11e9-9c34-65a6d5f6679f.png)

2. All mandatory fields should be marked with * sign

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Still I am facing following issues.
Namespace Page :
1. Now the link name changed to "Create Namespace" and page title changed to "Add Namespace".
This should be uniform.Please make it "Add Namespace" at all places because I can see link name and page title on Namespace Requests page as "Add Namespace"

![image](https://user-images.githubusercontent.com/40416610/69844109-b2a57580-1290-11ea-8743-7f4214c76b9c.png)

![image](https://user-images.githubusercontent.com/40416610/69844126-c8b33600-1290-11ea-9b77-bb6b611de06c.png)

2. Without entering in Namespace Name field directly click on "Submit" button is displaying page crash on both Add Namespace and Edit Namespace

![image](https://user-images.githubusercontent.com/40416610/69844239-5131d680-1291-11ea-8428-39f603677193.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . fixed pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Now there is no page crash on while creating new spaces but there is a page crash while editing namespace
Steps : 
1. Go to Namespace lists page 
2. Click on Edit
3. Make "Namespace Name" as blank
4. Click on Submit button

Actual Result :
![image](https://user-images.githubusercontent.com/40416610/70113708-eeb94b80-167f-11ea-8a4f-13878ba6ea32.png)
 

Other issues : 
1. On Namespace page link name and page name is still mismatch.
![image](https://user-images.githubusercontent.com/40416610/70113380-f1677100-167e-11ea-892c-8992d81ee262.png)
![image](https://user-images.githubusercontent.com/40416610/70113401-0cd27c00-167f-11ea-88d0-1d55ecdcc379.png)

2. Edit and Delete template are not working.It is displaying blank page
![image](https://user-images.githubusercontent.com/40416610/70113326-caa93a80-167e-11ea-9100-4b159e871a28.png)
![image](https://user-images.githubusercontent.com/40416610/70113348-dc8add80-167e-11ea-8e5d-992de320f57f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16  Tested. Edit namespace page crash issue is still exists. Previously it was UnexpectedValueException but now Exception is "Uninitialized string offset: -1" .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/70645467-12295b00-1c6b-11ea-888c-0aed4a7001ec.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
