### ISSUE TITLE
Canonizer Admin Issues -2

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#555]
1. Canonizer admin footer should be display at the bottom of page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/65268565-0d09b380-db35-11e9-9e31-e23614595c4f.png)

![image](https://user-images.githubusercontent.com/40416610/65268713-5d811100-db35-11e9-8391-782ac3a2ae3a.png)

2. Selected menu item is not getting highlighted.Dashboard and Namespace menus are always bold .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/65269087-16dfe680-db36-11e9-91a6-c166cc0fce6d.png)

3. After logout user should redirect to canonizer admin login page 
Actual Result : 
As of now user is redirecting to "https://staging.canonizer.com/" /canonizer main page
Expected Result : 
User should redirect to "https://staging.canonizer.com/admin/login"

4. After successful login, logged in username should display at right top corner
Actual Result : 
As of now after successful login, it is not displaying logged in username anywhere

5. Left menu name and page title must match for menu Namespace
![image](https://user-images.githubusercontent.com/40416610/65269928-c1a4d480-db37-11e9-8a73-b46fe8b37d49.png)

6. User is able to create duplicate namespaces from both add namespace and edit namespace.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/65270116-23653e80-db38-11e9-9d57-8554b23e98b8.png)

7. Email Templates list column names and Create Template labels names are not matching
Actual Result : 
Email Templates list column names are **Name  , Subject , Body , Status** and Create Template labels names are **Template Name , Template Subject , Template Body , Status** 
Expected Result : 
Names must match

8. User is getting updated with all blank data.
Expected Result : 
It should display error messages for mandatory fields while updating any user
![image](https://user-images.githubusercontent.com/40416610/65270898-b94d9900-db39-11e9-8b85-c224933ad1de.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Still facing following issues
1. Admin Panel layout is not proper : Please refer issue #570 
2. Error messages should match label names on Create Template page .Please refer attached screenshot
Error message for Template Name  should be "Template Name field is required." 
Error message for Template Subject should be "Template Subject field is required." 
Error message for Template Body should be "Template Body field is required." 
![image](https://user-images.githubusercontent.com/40416610/69933375-7d00c680-14f4-11ea-9e04-498e366e39fd.png)

3. User is able to create duplicate namespaces .Please refer issue #502 comment https://github.com/the-canonizer/canonizer.2.0/issues/502#issuecomment-560236931

4.Validations for first name,last name,middle name to accept letters only are missing Edit User page.Please refer issue #572

**Comment by gautamv16** [comment]
@rupalichavan9860  Pls test issues from 1 to 3. #572 is not fixed yet

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Issue 1 and 2 are fixed.3rd issue is still exists. For 3rd and 4th issues we already have separate issues so I am closing this one
