### ISSUE TITLE
Increase the size of the front page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#558]
I think we should grow the number of items on the front page to at least 30, instead of 10.
And also expand the space for Jim, next to this, so his stuff doesn't wrap.

If this is easy, let's do it for release 15, before we do ether canonizer.
If not, let's wait till latter.

The bottom line, it would be nice to control this number of items to display, with a constant, so we could easily change the size any time we want.

**Comment by gautamv16** [comment]
@rupalichavan9860 pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 tested and verified.
@BrentAllsop please check and close if fine for you

**Comment by BrentAllsop** [comment]
The change in the size of the page looks great on staging.  Except for the advertisements that should be on the right hand side are currently wrapping down to the bottom, and extending the page even larger.  This is true even when I go to full screen on a very large display.  This is a problem.  Last week this was only occurring on live, not on staging.  But now it seems to be happening everywhere.  I'm seeing this problem in both Chrome and Microsoft's browser.  I would rather not close this till this issue is resolved.

**Comment by rupalichavan9860** [comment]
@BrentAllsop @gautamv16 I just checked and this is working fine now.
@BrentAllsop Can you please check at your end and close .

**Comment by BrentAllsop** [comment]
Yup, looks great to me.
