### ISSUE TITLE
Multiple issues with supports page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#559]
Click on a supporter of any camp that supports more than one camp on that topic.
This will take you to their supports page.
There are the following issues with this page:
1. There should be a #label added to the HTML, so when they click on this, it scrolls down to that particular topic/camp, if there are lots that they support.  And there should be some indicator that that is the one they clicked on, maybe make that camp large font and bold or something.  Perhaps include the camp topic and camp number as arguments in the supports URL, in addition to the #target option.
2. Instead of "agreement", it should be the topic name for the agreement camp.
3. Clicking on camps on this supports page should go to the camp page, not a history page.
4. The order of the listed camps for each person, should be in their chosen order, currently they are not displayed in this order.

**Comment by BrentAllsop** [comment]
An additional thing we need is on regular camp pages, when there is a direct supporter, we need to indicate whether that support is the first, second, third.... choice for that topic.  In other words, if it is the supporters 12th choice, make a direct supporter look like this:

"12: Brent_Allsop (0.001)"

delegated supporters will be the same as their direct supporter, so won't need this.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .The order of the listed camps for each person, should be in their chosen order.As of now last camp supported is displaying as first.It should display camp like on my supports page.Please confirm
refer screenshots for more details
![image](https://user-images.githubusercontent.com/40416610/71553309-ad744b80-2a33-11ea-96f5-ddc92c98dc38.png)

![image](https://user-images.githubusercontent.com/40416610/71553316-c3820c00-2a33-11ea-88b6-23073bc66950.png)

@BrentAllsop Please check

**Comment by gautamv16** [comment]
@rupalichavan9860  Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and still facing issue

**Comment by rupalichavan9860** [comment]
@gautamv16 order is working fine now but as per Brent's comment I am not able to see following thing

An additional thing we need is on regular camp pages, when there is a direct supporter, we need to indicate whether that support is the first, second, third.... choice for that topic. In other words, if it is the supporters 12th choice, make a direct supporter look like this:

"12: Brent_Allsop (0.001)"

delegated supporters will be the same as their direct supporter, so won't need this.

@BrentAllsop Can you please check this?

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
Oh, yea. Let's do that.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . I can see the choice number now, but it is starting from 0 instead of 1 .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/72220085-35e60680-3573-11ea-921f-eeaed74e898a.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
I'm thinking that if you only support one camp, it should be 0.
If you support more than one camp, the top choice number should be 1.

After discussing this in our meeting, we decided it would be too confusing to use both 0 and 1, for the first camp.  So lets be consistent, and always use just 1 for the first camp, even if that is the only camp for that topic.

**Comment by BrentAllsop** [comment]
There is an error case for the numbering.
In this camp:
https://staging.canonizer.com/topic/243-Choice/3#statement
It shows my number as: 216, when I am only supporting one camp in that topic.

**Comment by gautamv16** [comment]
@BrentAllsop I have changed it to show the choice number for that camp under current topic, previously i have showcased the chioce number from all the camps supported

**Comment by BrentAllsop** [comment]
It seems like we don't have the number right, yet.
For example, my first two camps (1, and 2) are both labeled with 11.
https://staging.canonizer.com/topic/208-Sex-Education/13#statement

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working for me.
@BrentAllsop Can you please check and confirm?And close if fine for you?

**Comment by rupalichavan9860** [comment]
@gautamv16 Choice numbers are missing for agreement camp. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73000439-dc10f680-3e26-11ea-9d6a-decc1433e2f7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I can see the choice numbers for agreement camp but still numbers are missing for delegated supporter.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/73136004-ffc67d80-406e-11ea-892c-e5ff2732bdb7.png)

And also when user supporting more than one camp under same topic choice numbers should be like 1,2, 3,....
As of now I can see choice number as 1 for every camp 
Please check choice numbers for user "RC" for subcamps of  topic https://staging.canonizer.com/topic/240-Test-topic-20-dec-2019/1#statement

**Comment by BrentAllsop** [comment]
@rupalichavan9860, We don't need to show the choice numbers for delegated supporters, since they are the same as the delegate direct supporter at the top.  You are correct, the choice number for a third choice camp should be 3, not 1.

**Comment by gautamv16** [comment]
@rupalichavan9860 I have fixed the issue to display 1,2,3.. numbers according to supported camp for topic. Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working now so closing this
