### ISSUE TITLE
Search button text

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#561]
Can we have Search button text as only "Search" instead of "Google Search" because ultimately we are selecting one of the option from "web" or "canonizer.com".
So it seems we are searching canonizer.com with "Google Search" button.
@gautamv16 @BrentAllsop @akuks @CanonizerJim Please let me know your thoughts on this.

![image](https://user-images.githubusercontent.com/40416610/68323029-90ce2e00-00ea-11ea-90b7-9e91652302b3.png)

**Comment by BrentAllsop** [comment]
My initial thoughts were that people should know that pressing this button with the Canonizer option would do the same thing as going to google and doing a search, while including this: "site:canonizer.com".  I'll add this to the agenda for the next meeting so we can talk about this.

**Comment by rupalichavan9860** [comment]
As per discussion replace "Google Search" button text with "Search" and in the placeholder where "Search for..." is written should be replaced by "Google search for..."

**Comment by gautamv16** [comment]
@rupalichavan9860  pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 Need same changes on blog.So reopening the issue

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by rupalichavan9860** [comment]
@gautamv16 Changes are missing on blog page of production .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/74118487-9b183080-4be1-11ea-983b-1646980d2acc.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looks good now so closing this issue
