### ISSUE TITLE
New statement not notifying direct supporters.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#562]
When a new statement is submitted for the first time, it currently correctly goes into review, but all direct supporters are not being notified, nor do they have the chance to make it go live sooner.

**Comment by BrentAllsop** [comment]
Also, if there is only one direct supporter (who has delegators), when he submits a new version, it should go live instantly.

Also, all the direct supporters should be the only ones that give theo OK, to go live early.  And only all of the direct supporters, regardless of how many delegators don't participate) should be able to make it go live, early.

**Comment by BrentAllsop** [comment]
Also, if a parent camp has a supporter, (with or without delegators) it should not effect a sub camp.  If a sub camp has no supporters, it should always go live instantly.

**Comment by BrentAllsop** [comment]
Also, as part of this, Jim and I have decided to change the 1 week waiting period to 24 hours.  In the future we will want to extend this, probably back to one week.  So it should be a constant that is easily setable.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested this for grace period and now its changed to 24 hrs.We need to change respective emails to "it will go live in one day/24 hours" from "it will go live in one week"
![image](https://user-images.githubusercontent.com/40416610/71541639-48ace880-2982-11ea-8265-f733fad4640f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  Pls Test

**Comment by rupalichavan9860** [comment]
> Also, as part of this, Jim and I have decided to change the 1 week waiting period to 24 hours. In the future we will want to extend this, probably back to one week. So it should be a constant that is easily setable.

@BrentAllsop  This is only for camp statement or we need to change the grace period to 24 hours for camp and topic change also?

**Comment by BrentAllsop** [comment]
Yes, it should be for everything.  Topic, camp, and camp statements.

**Comment by BrentAllsop** [comment]
OH, and we need to make sure we update the messages to the users, to use this constant, so it is easy to change.  In other words, we should notify the direct supporters that it will go live after X time, where X is the constant.  And find a way to make the english work, maybe define a string, with the constant?

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can you please check and close if fine for you.

**Comment by BrentAllsop** [comment]
Yup, everything seems to be working, so closing this.
