### ISSUE TITLE
Link in email notification of change should go to history page of that change.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#563]
Currently it is just going to the camp page.

**Comment by rupalichavan9860** [comment]
Same issue I am facing for objected to your proposed change email link also

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash on Link in email notification of change(topic, statement and camp) and also I can see some extra text in email.Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/70647276-9c26f300-1c6e-11ea-97f8-2d3a1461021d.png)

![image](https://user-images.githubusercontent.com/40416610/70647443-f627b880-1c6e-11ea-9fa3-5f755ac96b26.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
