### ISSUE TITLE
Email format issue : Proposed change to statement for camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#564]
Need some space or separator between keyword "for camp" and camp name.
In following example camp name is "test camp 1"
Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/68732461-7ff54f00-05f9-11ea-872f-d7b9be43bf19.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Now I can see the space between keyword "for camp" and camp name,but do we need hyperlink for keyword "for camp"
@BrentAllsop Please confirm and close the issue if you are fine with current format.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69902749-feead580-13b6-11ea-891f-941369061d9a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 . I have removed for camp from link. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
But I found one new change in mail .Please refer attached screenshots for more details.
Old Email :
![image](https://user-images.githubusercontent.com/40416610/69931801-97d03c80-14ee-11ea-97e8-dcc3af3ea2d1.png)
New Email : 
![image](https://user-images.githubusercontent.com/40416610/69931764-72433300-14ee-11ea-95d7-274d40d8dbdc.png)

Previously it was " If no supporters of this **statement** object to this change, it will go live in one week."
Now it's changed to " If no supporters of this **statement : for camp** object to this change, it will go live in one week."
And after "for camp" ,camp name is not there.

I think we need to revert this change .Please confirm

**Comment by gautamv16** [comment]
@rupalichavan9860 . pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. It should be "If no supporters of this camp object to this change, it will go live in one week." instead of  "If no supporters of this 1 object to this change, it will go live in one week."
![image](https://user-images.githubusercontent.com/40416610/70647943-0d1ada80-1c70-11ea-8fb3-8987fa6bd41c.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
