### ISSUE TITLE
Page crash error on Metamaks Account

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#565]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Username->Account Settings
4. Click on Metamaks Account

Expected Result : 
It should display respective page

Actual Result : 
It is displaying UnexpectedValueException .
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/68734906-fd24c200-0601-11ea-823a-54ed17098549.png)

**Comment by akuks** [comment]
I also get an error but a different one.
Base table or view not found: 1146 Table 'staging.ether_address' doesn't exist (SQL: select * from `ether_address` where `user_id` = 325). 

I think it misses the migration. I am checking it

**Comment by akuks** [comment]
@rupalichavan9860 can you please check again.

**Comment by rupalichavan9860** [comment]
@akuks It's working now
