### ISSUE TITLE
"Add & Manage Nick Names" tab in the Profile screen should be "Manage Nick Names"

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#567]
Just a thought, In the Users profile, "Add & Manage Nick Names" tab should be renamed as "Manage Nick Names". 

After renaming the above,  the "MetaMask Account" also comes in line with all other tabs.

![image](https://user-images.githubusercontent.com/12954663/68736602-1714d380-0607-11ea-83a4-24301a049071.png)

We can discuss this in our next meeting.

**Comment by gautamv16** [comment]
@rupalichavan9860 . Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .I can see "Add & Manage Nick Names" tab renamed as "Manage Nick Names".But still "MetaMask Account" tab is not in line with all other tabs.
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69826665-28322700-123a-11ea-99c3-d7eb8b77535f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  Fixed. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I can see all tabs in one line but tab names text size is very small.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69931433-3d82ac00-14ed-11ea-87c7-0711016f2a8f.png)

Can we change it like @akuks posted in first comment
![image](https://user-images.githubusercontent.com/40416610/69931300-baf9ec80-14ec-11ea-9fa7-1ab830f57d55.png)

**Comment by gautamv16** [comment]
![image](https://user-images.githubusercontent.com/6199964/70122344-78741380-1696-11ea-9e8d-25b7dc34b8f0.png)

@rupalichavan9860 the one Karun did is good and not required any change as if system screen is small than again that will come down. So i just checked on different machine its ok Please refer screenshot.

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.No issues I am closing this
