### ISSUE TITLE
Camp forum mails are displaying Not live and Objected records(camp name) 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#569]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to Browse and select any topic
4. Go to camp and object
5. Now go to Camp forum and create any thread/make a post
6. Observe email

Expected Result : 
Live camp name should display in email

Actual Result : 
It is displaying Objected camp name in email
Please refer attached screenshot
E.g : In following example it should display "Camp1" instead of "Camp1.1"
![image](https://user-images.githubusercontent.com/40416610/69117898-4a4bdc80-0ab7-11ea-8bd7-c3952e4d6d06.png)

![image](https://user-images.githubusercontent.com/40416610/69117921-694a6e80-0ab7-11ea-8753-fd87e328a74b.png)

![image](https://user-images.githubusercontent.com/40416610/69117984-b4648180-0ab7-11ea-9088-1fb3f53e05ce.png)

**Comment by gautamv16** [comment]
@akuks  can u please check this one.

**Comment by rupalichavan9860** [comment]
@akuks Tested .Still I can see not live camp name in forum emails

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed, Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Still I can see not live camp name in forum emails.
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/82804570-24592780-9ea0-11ea-9801-2cfb1da8e123.png)

![image](https://user-images.githubusercontent.com/40416610/82804626-389d2480-9ea0-11ea-9436-5145cf1c0699.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed, Please Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still I can see not live camp name in forum emails.

**Comment by gautamv16** [comment]
@rupalichavan9860 I have fixed the issue for not live camps . pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing the issue
