### ISSUE TITLE
Admin panel : layout is not proper

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#570]
I am not able to see "Canonizer Admin" and username properly when screen size is 100%.
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/69827326-dfc83880-123c-11ea-974b-656aee878b78.png)

![image](https://user-images.githubusercontent.com/40416610/69827187-4e58c680-123c-11ea-9cad-082500cd9117.png)

![image](https://user-images.githubusercontent.com/40416610/69827144-1baece00-123c-11ea-92e5-134921ac5195.png)

**Comment by KarlaChen** [comment]
@rupalichavan9860 can I try it?

**Comment by BrentAllsop** [comment]
I Karla,  Certainly you may try.
And let us know if there is anything we can do to help.
Thanks for reaching out.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
