### ISSUE TITLE
Incorrect Validations for Middle Name on Register page  

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#571]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Click on Register link
3. Enter valid data in all the fields and keep Middle Name as blank
4. Click on "Create your account"

Expected Result : User should get registered

Actual Result : 
It is displaying error message "Middle name must be in letters only" 
![image](https://user-images.githubusercontent.com/40416610/69846343-b8538900-1299-11ea-989c-b85b924e7bbb.png)

**Comment by akuks** [comment]
@rupalichavan9860 Please test

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified.
