### ISSUE TITLE
Validations missing for first name,last name,middle name on manage profile info

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#572]
Validations for first name,last name,middle name to accept letters only are missing on manage profile info

![image](https://user-images.githubusercontent.com/40416610/69902928-0f03b480-13b9-11ea-881c-5186a35814d7.png)

**Comment by rupalichavan9860** [comment]
Need to same validations on Admin panel->users page

**Comment by gautamv16** [comment]
@rupalichavan9860 you are adding new issues in this. This is seperate issue than you mentioned. We have to close release ticket wise. So if you keeps adding new found issue in existing finished issue than it wont close issue on expected time as it will take time to fix your new found issues.

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.No issues.I was testing functionality wise so that's why I mentioned it here. I will create new one

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
