### ISSUE TITLE
Canonizer Admin Issues-3

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#573]
1. Login Page : 
When canonizer user who don't have admin access and trying to login into https://staging.canonizer.com/admin , page is getting refreshed
Expected Result : 
It should display error proper message 

2. Login Page : 
User is getting logged in to https://staging.canonizer.com instead of https://staging.canonizer.com/admin for following scenario
Steps : 
     1. Go to https://staging.canonizer.com/
     2. Click on Log in
     3. Go to URL and type https://staging.canonizer.com/admin
     4. Enter valid email and password 
     5. Click on Login
Expected Result : 
User should get logged in to admin
Actual Result : 
User is getting logged in to https://staging.canonizer.com

3. Dashboard Page : 
Total Live Topics,Total Live Camps,Total Active Persons are always displaying 12.I am not getting the functionality.Is this an issue?Need help on this
![image](https://user-images.githubusercontent.com/40416610/69977288-8d468f00-1550-11ea-91ad-c06d94fa0eab.png)

4. Namespace,users and Templates list page : 
Arrows alignment in pagination are not proper when user is on first and last page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69977850-866c4c00-1551-11ea-8560-eea966d1812d.png)

![image](https://user-images.githubusercontent.com/40416610/69977941-ad2a8280-1551-11ea-85c3-6d33d52d0e5b.png)

5. Templates Page : 
User is able to create duplicate templates(Please check on both create template and update template page).Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/69979458-5e321c80-1554-11ea-8bd8-b38b451c0a28.png)

6. Namespace, Namespace Requests, Templates, Users page validations
All text fields should have some limit on characters length.As of now user can enter data of any length.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/70023850-a423ca80-15be-11ea-9297-d1c4538ddfb5.png)

![image](https://user-images.githubusercontent.com/40416610/70023880-c3baf300-15be-11ea-9407-9a21f375c6b5.png)

![image](https://user-images.githubusercontent.com/40416610/70024039-34620f80-15bf-11ea-8037-95e7a4ae4b10.png)

7. Delete Template : 
  i. Delete template is directly deleting template.It should ask for delete confirmation
 ii. After deleting template it is displaying success message "Template Deleted Successfully" with cross sign.When user click on cross sign it should close the success message,As of now it is not closing success message 
iii. After updating template it is displaying success message "Template Updated Successfully" with cross sign.When user click on cross sign it should close the success message,As of now it is not closing success message

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested
1. Issue 1 and issue 2 are not fixed yet.
2. Need help to cross check count for Total Live Topics,Total Live Camps,Total Active Persons on dashboard page
3. List pages pagination is still not proper.It should have similar spaces between each page numbers.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/71552983-e52bc500-2a2c-11ea-9dbc-6323f064c3b0.png)
 4. It would be nice if all text fields simply prevented you from typing in more than given text field size characters and all text fields labels should be followed by max limit in () .e.g Namespace Name (Limit 100 chars) *

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and I am still facing last commented issues .
Can we change pagination like forum is having. It looks good .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/71830575-05165500-30cd-11ea-816c-00e263e0787d.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .
1. Issue 2 is not fixed yet.Need to discuss in meeting
2. It would be nice if all text fields simply prevented you from typing in more than given text field size characters and all text fields labels should be followed by max limit in () .e.g Namespace Name (Limit 100 chars) *

Expected result : 
It should be applicable for all text fields on create new and update pages

Actual Result : 
As of now this feature is implemented only for Namespace Name field on Create Namespace page.

**Comment by gautamv16** [comment]
@rupalichavan9860 point 2 is fixed you can test and point 1 i am not able to reproduce it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested..But this is implemented only on Namespace pages text fields.
It should be applicable for all text fields of Admin panel -> Templates(Create Template,update Template),Users(Edit User)

**Comment by gautamv16** [comment]
@rupalichavan9860 Implemented Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
