### ISSUE TITLE
Update readme.md file.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#576]
This isn't really a "show stopper" but it needs to be done ASAP so brent can make progress on making a canonizer page for the consciousness video.

We need to enhance the readme.md file.
It needs to include more detailed instructions of how to install on windows.
    Include info about where to get and how to install xampp.
It would be nice to have more detailed instructions on how to install into a production (linux) box.

**Comment by gautamv16** [comment]
@BrentAllsop I have updated the readme file and pushed it on staging. Please check and verify if all is good

**Comment by BrentAllsop** [comment]
Yes, nice to see instructions for windows/xampp.

Closing this.
