### ISSUE TITLE
Update New User Welcome help link.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#578]
The link to the "help" page in the Welcome to Canonizer e-mail is the old:
https://staging.canonizer.com/topic/38-Canonized-help-statement-text/1
It should be updated to this current version:
https://staging.canonizer.com/topic/132-Help/1

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I just registered a new user and check but still The link to the "help" page in the Welcome to Canonizer e-mail is the old:
https://staging.canonizer.com/topic/38-Canonized-help-statement-text/1

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still it is redirecting to old one 

![image](https://user-images.githubusercontent.com/40416610/76070831-33c08700-5fbb-11ea-8de9-df5c5028df30.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine so closing this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop I just reset my password and I am getting "[staging.canon] Welcome to Canonizer.com 2.0 System" mail and observed that the link to the "help" page in the Welcome to Canonizer 2.0 System e-mail is the old:

https://staging.canonizer.com/topic/38-Canonized-help-statement-text/1

It should be updated to this current version:
https://staging.canonizer.com/topic/132-Help/1

So I am reopening the issue

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed Please Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing issue
