### ISSUE TITLE
Admin ->Send Email : User is not able close the success message after sending email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#579]
After sending mail it is displaying success message "Mail sent successfully" with cross sign.When user click on cross sign it should close the success message,As of now it is not closing success message

![image](https://user-images.githubusercontent.com/40416610/72497365-50113480-3852-11ea-9394-624d0f7aec63.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working now, but I can see green layout on Send Email page which was not there previously
It is fine? @BrentAllsop please confirm
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/74625543-aa175980-5172-11ea-871d-a4f6964bae63.png)

**Comment by BrentAllsop** [comment]
@rupalichavan9860   The green looks fine to me, so no problem.
@gautamv16 I have working credentials for admin on live, but nothing works on staging.
Shouldn't these duplicate across from live to staging with everything else?

**Comment by rupalichavan9860** [comment]
@BrentAllsop I have copied production database and files to staging.Please check whether your login credenitals working on staging or not.
Please check and close issue if working fine for you

**Comment by BrentAllsop** [comment]
Yes, things are working now.  Thanks.
The green shading looks fine to me.
So I'm OK to close this if you are.

**Comment by rupalichavan9860** [comment]
@BrentAllsop But previously we don't have the green shading .You can check in first comment.
And we don't have this type of shading on any other page of admin

Also I can see it's a part of success alert message.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/75116542-7d41d580-568f-11ea-98a0-89c0b374c40a.png)


but I am OK to close if you are fine with this

**Comment by BrentAllsop** [comment]
@gautamv16, or whoever did this, do you have any comments on this?
Let's talk about this in our next meeting.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test it now. I have fixed it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified . Working now so closing this
