### ISSUE TITLE
Add "open source" link on front page comment.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#580]
This comment is on the front page:
"This is a free open source prototype being developed by volunteers.
Please be patient with what we have so far and/or be willing to help. "

Make "open source" a link to
https://github.com/the-canonizer/canonizer.2.0

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I can see the link to "open source" and it is redirecting to given URL so closing this
