### ISSUE TITLE
Can't easily select an asof date before 2010.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#581]
When you select the date field, for the first time, you cant select dates before 2010.
It needs to go back to earliest date in the database, but not earlier.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Please check and close if fine for you

**Comment by BrentAllsop** [comment]
There seems to be multiple issues with this.
When I go to this topic:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1
Then set the as-of date to before 2006,
It says:  This topic was first created on 12/1/2008, 7:23:55 AM
When I click on that, it set's the asof to: 11/30/2008, 5:00:00 PM
So it shouldn't exist at this time before the first created date?  It seems to me?
But the tree shows the current tree, not the almost no tree that existed when it was first created.
Also, we need to make sure ALL dates (including this created date) are displayed according to the browser local time.  And internally, they should all be unix time.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I also tried this link.It says : This topic was first created on 12/1/2008, 7:53:55 PM .When I click on link it set's the as of to: 12/1/2008, 5:30:00 AM

**Comment by BrentAllsop** [comment]
That is odd, it almost looks like the asof value is correcting for the browser's time zone (why it is different), as it should, but the "First created on" value is not being corrected for the browser's time zone (why it is kind of the same?), so needs to be fixed?
I wonder why you are getting a created on value of 12/1/2008, 7:53:55 PM, while I get almost the same: 12/1/2008/ 7:23:55 AM  ?
Anyway, the time should always be the same unix time, just always displayed in the local time zone.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by BrentAllsop** [comment]
We tested this.  That as of value is correct, but the topic isn't showing the state of the topic at that date.  It is showing current state of topic.

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash when I click on following date link
![image](https://user-images.githubusercontent.com/40416610/77254851-9edfae00-6c89-11ea-9fee-2272e98a0606.png)

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/77254873-b5860500-6c89-11ea-9af2-28076b5e7cb5.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine for me.
@BrentAllsop Can you please check once and close if fine for you?

**Comment by BrentAllsop** [comment]
This is nicely fixed.
Just one minor issue.
Currently, the year selector goes all the way back to 1920.
This only needs to go back to 2006, since Canonizer didn't exist before then.
Removing those years will simplify things.
Once this is fixed, we can close this.

**Comment by gautamv16** [comment]
@BrentAllsop @rupalichavan9860 I have made the changes as asked. Pls test and confirm

**Comment by BrentAllsop** [comment]
@gautamv16 @rupalichavan9860   Sorry to be nit picky, and sorry I didn't notice this before.
How about we also do a date check and calculation to find out what year it is now, and limit the last year to be that, instead of 2030?  That would clean things up a bit more.  (And not break, once we get past 2030?)

**Comment by gautamv16** [comment]
@BrentAllsop It is not fixed to 2030, the year's max limit is current year + 10 years. If you want to change it to the current year only then pls confirm

**Comment by gautamv16** [comment]
@BrentAllsop I have changed that datepicker to set the current year as last year in range

**Comment by BrentAllsop** [comment]
I'm still seeing a problem.
1. go to https://staging.canonizer.com
2. Set the as of date to: 2/28/2009, 5:00:00 PM
3. Then go to https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1
Expected:  Early tree with only a few camps.
What you see:  The as of value default tree.

**Comment by BrentAllsop** [comment]
Also it is possible to do the same on the main page.
It is possible to have the as of value different than the displayed tree.

Also, we have this string:
as of (yy/mm/dd)
This should be
as of date

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860   Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. as of date is not working on Canonizer Main Page. Please refer attached screenshot
I have selected as of date as yesterday's date and it is not displaying topics under Canonized list for

![image](https://user-images.githubusercontent.com/40416610/77849747-8cb2c200-71eb-11ea-8799-5b66b8c710ec.png)

Also When I am selecting any topic and selecting as of date equal to topic created date or any previous date I am getting following page crash

![image](https://user-images.githubusercontent.com/40416610/77849804-e1563d00-71eb-11ea-8e9d-4dfcb4732575.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by BrentAllsop** [comment]
Since the as-of value can effect the browse page.
We need to add an as-of box to the side bar of the browse page, so users can change this.

**Comment by BrentAllsop** [comment]
Save the selected date in session.
If there is a session as of value, always display that in the as of date box (even if the as of checkbox is not selected)
If the user doesn't select a different date, after the as of checkbox is selected, go back to default.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.It's working good for me now.
@BrentAllsop Can you please check once and close if fine for you?

**Comment by BrentAllsop** [comment]
This is still an issue:

Go to staging.canonizer.com.
Set an as-of date value to some time in 2009, but leave the selection on default.
This is currently correctly saved in session.
Go to the consciousness topic:
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1
As of value should still be set to default, and the date should still be the 2009 date.
When you switch between the default and asof selector boxes, nothing changes in the tree.
The page doesn't reload.
If you switch to "include review" the page correctly reloads.
But if you switch back to the "as of" setting, it does not reload with the old 2009 tree.

**Comment by gautamv16** [comment]
@BrentAllsop @rupalichavan9860  Pls test

**Comment by BrentAllsop** [comment]
Nice, everything looks ready to close to me.

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see some topics from /sandbox testing/ namespaces under /general/ namespace on Canonizer Main Page

![image](https://user-images.githubusercontent.com/40416610/78519520-4bb93f80-77e1-11ea-84f6-c39318e32f6b.png)

**Comment by BrentAllsop** [comment]
Oops, on further testing, I found another issue with this.
Go to this camp on staging:
Camp: Agreement / Approachable Via Science / Representational Qualia / Dualism / Property Dualism / Mind-Brain Identity / Functional Prprty Dualism

Then set the as-of value to some time in early 2016.

It shows the breadcrumbs on the top of the page as:
Camp: Agreement / Approachable Via Science / Representational Qualia / Dualism / Property Dualism / Mind-Brain Identity / Functional Prprty Dualism

But this camp doesn't show up in the tree.

I believe that camp existed, at that time,

**Comment by BrentAllsop** [comment]
Good catch rupali.
Also, that list on the front page should be sorted, according to the selected canonizer algorithm.
It doesn't look sorted, there.

**Comment by rupalichavan9860** [comment]
I found one more issue .Please refer following scenario
Go to any topic and select any sub camp
Select as of date filter and select any date
Result : 
Camp name is displaying as "N/A" and also it is displaying "No camp data available."Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/78677744-bcf21300-7905-11ea-972b-25120f130647.png)

**Comment by gautamv16** [comment]
@BrentAllsop  @rupalichavan9860 Fixed . pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looks fine to me so closing this issue
