### ISSUE TITLE
"Algorithm Information" links on the side bar should be to agreement camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#583]
Current, the Canonizer Algorithm link on the side bar is pointing to the 1 person 1 vote sub camp:

https://canonizer.com/topic/53-Canonized-Canonizer-Algorithms/2

It should be to the agreement camp and have the right name, like this:

https://canonizer.com/topic/53-Canonizer-Algorithms/1

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Not fixed yet.Still redirecting to https://canonizer.com/topic/53-Canonized-Canonizer-Algorithms/2

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
