### ISSUE TITLE
List of supported camps page issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#584]
1. List of supported camps is displaying Not live topic name.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73148821-40141300-40e4-11ea-8d20-896d956373f8.png)

![image](https://user-images.githubusercontent.com/40416610/73148852-60dc6880-40e4-11ea-8d48-f16398cb9e02.png)

2. List of supported camps is not listing delegated supported topic/camps
please refer attached screenshot for user "Rupali auto"
Expected  Result :  "Rupali auto" has delegated their support to RC for 14 camps under Topic "Test topic 20 dec 2019".So it should display on list of supported camps page
Actual Result : As of now I can see only directly supported topics/camps and not delegated camps
![image](https://user-images.githubusercontent.com/40416610/73148984-1dcec500-40e5-11ea-990f-eb9b4a0b4e80.png)

![image](https://user-images.githubusercontent.com/40416610/73149031-65555100-40e5-11ea-83e5-f6ef107fa778.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Second issue is still exists

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I can see the delegated supported camp list now.
@BrentAllsop Please check and close if fine for you.Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/76163836-abcfae00-616f-11ea-8602-fbf7d94b35f8.png)

**Comment by BrentAllsop** [comment]
https://staging.canonizer.com/topic/195-Agreement/1
On the supports page (where the above URL came from) the URLs have “agreement” rather than the topic name, as is correctly done everywhere else.
Let's fix this before we close this.

Other than the above, this seems to be to be ready to close.

**Comment by gautamv16** [comment]
@BrentAllsop @rupalichavan9860  I have fixed the url issue mentioned above. Pls test and confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine so closing this
