### ISSUE TITLE
Page layout issues after applying as of (yy/mm/dd) filter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#585]
I can't see Help, White Paper and Blog menus after applying as of(yy/mm/dd) filter as any past date. 
Also footer contents are displaying at the center of the page instead of bottom of the page.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73237859-ecc1c380-41bc-11ea-8755-97a8f8417f69.png)

**Comment by BrentAllsop** [comment]
Yes, go to a fairly new topic, and set the as of date before that topic was created to reproduce this.
Good catch.

**Comment by BrentAllsop** [comment]
Current message: "Topic does not have any record for selected date."
Could we easily change this to:
"This topic was first created on <date>."  And have the <date> be in the local time zone for the browser, and be a link that sets that as_of value so the first version of the topic will show up?

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I am getting page crash when I am selecting as of (yy/mm/dd) date is equal to  topic created date or past date.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/76018674-78f6a180-5f46-11ea-81a0-515c1b4b3a66.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed, Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . I am not seeing page crash now but as per Brent's comment message need to do minor changes in message 

It should display  "This topic was first created on ." And have the be in the local time zone for the browser, and be a link that sets that as_of value so the first version of the topic will show up?

Right now message is displaying as "**The** Topic was first created on 03/07/2020"
It should be display as "**This** **t**opic was first created on 03/07/2020"

![image](https://user-images.githubusercontent.com/40416610/76157852-07307a80-6135-11ea-97ee-b90dd53c7696.png)

**Comment by rupalichavan9860** [comment]
Also It is displaying date as yesterday's date for some topics(Not created by me)- This may be timezone issue.But still I would suggest First version date should match with topic's  first version on Topic history page .Please refer attached screenshot
Please refer screenshot for "Help" topic

![image](https://user-images.githubusercontent.com/40416610/76157938-224fba00-6136-11ea-9039-6d70cd4f6994.png)

![image](https://user-images.githubusercontent.com/40416610/76157952-4e6b3b00-6136-11ea-9120-9aa6b04148be.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and looks good now.But I found one UI issue on the page- I am not able to see selected as of (yy/mm/dd) date properly .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/76160150-a7929900-614d-11ea-9cae-3ac01fbd8099.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Its working fine when i checked it in chrome
![image](https://user-images.githubusercontent.com/6199964/76162465-167aec80-6164-11ea-840e-5ec6e01818ae.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Can you please tell me your browser's text size? Because for me , when my text size is 90% it looks good but if it is 100% then it is not displaying properly

**Comment by gautamv16** [comment]
@rupalichavan9860 I have checked it at 100% text size, but i have made some fixes by changing the text size . Pls test it again if it is working fine now at your end

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looking good now so closing this issue
