### ISSUE TITLE
Page crash on Manage/Edit Camp Statement

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#588]
Pre-condition : 
User should not have nick name

Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Click on Manage/Edit Camp Statement

Expected Result : 
Specific page should get open

Actual Result : 
It is displaying UnexpectedValueException. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73604118-86b8b000-45b1-11ea-85b7-6fe36d5dad32.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I have fixed it. please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working now so closing the issue
