### ISSUE TITLE
Email changes, including camp subscription.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#589]
Before spending time on implementing these changes, propose a design with brief pseudo code, so we can do a review of the design in a meeting, before it is implemented.  I would like to move towards a "canonize a topic structure" microservice.  (i.e. we shouldn't be building canonized structure with stuff like this, or when displaying html...  Just iterating on the topic structure the service provides.
And we shouldn't be checking canonized values by reading html, just testing the service.

We need to have a spec of a linked up and canonized topic structure we can serialize and deserialize to and from java script.

Camp Subscription:

We need to provide an ability to "subscribe" to a camp.
When you are subscribed, you get all e-mails a direct supporter would get.
On the topic page, to the left of the "Add News", there needs to be a "Subscribe" checkbox for that camp.  

If you are subscribed to a child camp you are implicitly subscribed to all parent camps.  So they need to be checked, greyed out, and deactivated.
If you mouse over this in this inactive Subscribed div, a message should pop up: "You are subscribed to <(current, not as of) camp name> camp” or  “You are currently supporting <(current, not as of) camp name> camp.

Camp support change notifications:

When someone changes their support of camps in a topic in any way, make a list of all camp changes (joined, deleted, moved up or down in priority.)

For each camp change in this list do the following:
1. For all direct supporters or subscribers of this camp (or sub camp) add a message for that user to indicate support was added, deleted or changed.

Only send one e-mail to an e-mail address with 1 or more collected descriptions of all changes.

[canon] tag on subject line of ALL e-mails from canonizer.

All email that comes from canonizer, the subject line should lead with: [canon].
Unless that string is already in the subject line.

If it is from a non production machine, it should include the type.
I.e staging should be [staging.canon]  or [localhost.canon] or [ip.canon]

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
Following points are not working : 
1. When you are subscribed, you get all e-mails a direct supporter would get.
2. For all direct supporters or subscribers of this camp (or sub camp) add a message for that user to indicate support was added, deleted or changed.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested some scenarios.But still facing some issues and have some doubts
1. For all direct supporters or subscribers of this camp (or sub camp) add a message for that user to indicate support was added, deleted or changed : I am not getting mails when support added or deleted,only getting mails when someone delegated their support to other
Doubt on delegated mail : 
User 1 is submitter of the agreement camp so User 1 is direct supporter 
Case : User 1 is direct supporter and subscriber also, User 2 is only subscriber of the camp.Now when User 3 delegating their support to User 1, User 1 and User 2 both should get emails
Actual Result : User 1 and User 2 are  getting mails .User 2 is getting (User 3 has just delegated their support to User 1.) User 1 is getting 2 mails (1.User 3 has just delegated their support to you and  2. User 3 has just delegated their support to User 1 ).It is fine?Or User 1 should get only one mail?

2. When you are subscribed, you get all e-mails a direct supporter would get : 
If User 2 is only subscriber and User 3 has proposed a change to the statement User 1 is currently directly support It should not say -User 3 has proposed a change to this statement : for camp Agreement which you currently directly support.(Please check User 2 email body contents)
It should say User 3 has proposed a change to this statement : for camp Agreement which you currently subscribed

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed pls test.
"support to User 1.) User 1 is getting 2 mails (1.User 3 has just delegated their support to you and 2. User 3 has just delegated their support to User 1 ).It is fine?Or User 1 should get only one mail?" For this we need to confirm with @BrentAllsop

**Comment by rupalichavan9860** [comment]
@gautamv16 I am facing following issues

- Added the support

1. Supporter name is missing in email tile and body.
2. Topic name/camp name should be link in email body
3. Email title should include topic name also
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/77460789-9b822900-6e27-11ea-9aa8-4bda39df8eec.png)

4. If User 1 is subscriber and supporter or the camp User 1 is getting 2 mails (Added the support)

- Deleted the support
1. User is not getting email when user deleting support 

- Subscription mails
1. Subscriber should receive forum emails also.
As of now only supporter of the camps are getting forum mails

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still facing following issues
1. Added Support

![image](https://user-images.githubusercontent.com/40416610/77632730-6f27f300-6f74-11ea-8825-4dddd6a8e1f2.png)

2. Deleted the support
User is getting support added email when user deleting support

3. Subscription mails
Subscriber should receive forum emails also.
As of now subscribers are getting 2 emails.They should receive only one mail when someone creating thread and post

4. Subscription mails
Minor spell mistake in note.Please refer attached screenshot(On camp change and statement change emails)
![image](https://user-images.githubusercontent.com/40416610/77633278-3d635c00-6f75-11ea-8b32-54784c493416.png)

![image](https://user-images.githubusercontent.com/40416610/77633382-6388fc00-6f75-11ea-99c4-4f1429a2df1a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.

- Getting page crash on removing support

1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to any topic and support any camp
4. Go to Directly Join or manage support->click on cross sign 
5. Click on Submit

![image](https://user-images.githubusercontent.com/40416610/77935131-ab3db980-72ce-11ea-88cf-3babc6e9cd49.png)

- Subscription Mails

- Camp Forum
1. Users are not getting thread creation mail
2. Only subscriber is getting thread post mail, the user who is supporter and subscriber also is not getting thread post mail

- Camp Statement 
1. Both Subscriber and supporters are getting 2 mails on camp statement change

- Topic Change 
Not getting topic change mail

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I tested all possible scenario's and all are working fine for me.
@BrentAllsop Can you please check emails changes once.because for supporter we have note like : 

"If you do not wish to receive these notifications, you can either delegate your support to some other camp supporter in the topic, or remove your support from the camp. We request that all direct supporters of a camp continue to receive and take some responsibility for the camp." 

for subscriber : 
"If you do not wish to receive these notifications, you can unsubscribe from the camp. We request that all subscriber of a camp continue to receive and take some responsibility for the camp."

@BrentAllsop please check and confirm

**Comment by BrentAllsop** [comment]
@CanonizerJim @rupalichavan9860 @gautamv16 
What do you think about the following changes from what rupali noted:

Since multiple supports and multiple subscribes can cause a single e-mail.

How about we change the additional part of the message to list all the reasons like this (will often only be one element in the list):

You are receiving this e-mail because:
•	You are directly supporting &lt;link&gt;camp name&lt;/link&gt;
•	You are directly supporting &lt;link&gt;different camp name&lt;/link&gt;
•	You are subscribed to &lt;link&gt;camp name&lt;/link&gt;
•	You are subscribed to &lt;link&gt;different camp name&lt;/link&gt;

(Only include this last part after the above if any of the above reasons are from a “direct support”)

Note: We request that all &lt;bold&gt;**direct**&lt;/bold&gt; supporters of a camp continue to receive notifications and take responsibility for the camp.  You can avoid being notified by &lt;bold&gt;**delegating**&lt;/bold&gt; your support to someone else."

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check other emails also.There are some new emails also like Support added and removed.Please review once and let us know if required any changes

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
Yes, all e-mails, being received for any of these reasons, should include all this at the end.

**Comment by gautamv16** [comment]
@BrentAllsop @rupalichavan9860 Implemented the email changes as discussed. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.It is working now for some mails.I found some mismatch in following scenarios

1. Support added : It is not listing supported camps,as of now it is only listing subscribed camps list
Please refer attached screenshot
Support added mail screenshot : 
![image](https://user-images.githubusercontent.com/40416610/79965207-5cd4a280-84a9-11ea-9267-d9bd1e480240.png)

Support removed mail screenshot : 
![image](https://user-images.githubusercontent.com/40416610/79965540-c5238400-84a9-11ea-800e-c19e85b66dda.png)

2. When user1 is supporting agreement camp and subscribing sub camp1 ,Now when another user made any changes to sub camp1 like camp/camp statement/support added/support deleted/camp thread created/post submitted 

User1 is getting only "You are subscribed to sub camp1"
I think it should also list "You are directly supporting Agreement"

Please confirm

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still some issues are there
Note is missing in all mails (when User is subscriber of the camp)
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/80301888-4c336d80-87c4-11ea-89a9-43818b94daad.png)

please refer another mail
![image](https://user-images.githubusercontent.com/40416610/80301917-856bdd80-87c4-11ea-9961-e29d1f003b48.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , Its not missing , it is what requested to implement
Only include this last part after the above if any of the above reasons are from a “direct support”)

Note: We request that all <bold>direct</bold> supporters of a camp continue to receive notifications and take responsibility for the camp. You can avoid being notified by <bold>delegating</bold> your support to someone else."

**Comment by rupalichavan9860** [comment]
@gautamv16 Yes.My bad.. I missed it.
@BrentAllsop I have checked and verified all the mails .Can you please check if I am missing something and close if fine for you

**Comment by BrentAllsop** [comment]
Thanks for all the great work to get all this done.
This was a hard one.
Looking great.

**Comment by BrentAllsop** [comment]
There are still multiple issues with this.

When I made a change to the "Computer Science Experts" camp (https://canonizer.com/topic/53-Computer-Science-Experts/13) , it listed all these as reasons for the person receiving this e-mail:

You are directly supporting Atheist
You are directly supporting RankingRunoff
You are directly supporting Mind Experts
You are directly supporting Computer Science Experts

But he should not be receiving e-mails for a changes to the "Computer Science Expert" if he is only supporting Atheist, or Ranking Runoff, or Mind Experts (and not Computer Science Experts).

So, these camps unrelated to the changing camp should not be listed as a reason for why he received this e-mail for a change to the "Computer Science Experts" camp.

He should only have reasons listed for changes to camps they support (including supporting sub camps)  Not just everything they support in that topic.


This is a bit unrelated, but this fix this, before we close this issue:

The e-mails from production have this leader in the subject line:
[staging.canon] which makes it appear that it is from the staging system.
All e-mail from the live system should only have [canon] as the subject leader.

**Comment by BrentAllsop** [comment]
One more minor issue on this.
We need a space between the [canon] and the actual subject line.

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860 . this is fixed and deployed on staging pls test

**Comment by BrentAllsop** [comment]
@rupalichavan9860   Looks great to me, go ahead and close this, if you're OK with it, Rupali.

**Comment by rupalichavan9860** [comment]
@BrentAllsop @gautamv16 I am OK with this so closing this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop 

The e-mails from production have this leader in the subject line:
[staging.canon] which makes it appear that it is from the staging system.
All e-mail from the live system should only have [canon] as the subject leader.

I can't see [staging.canon] in Password Reset Mail , so reopening this issue

**Comment by gautamv16** [comment]
@rupalichavan9860 Password reset mail issue is fixed. Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looking nice so closing this issue
