### ISSUE TITLE
Change the way adding direct support to camps works.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#59]
When you select the join/support camp button, it will take you to an edit page, showing all previous camps currently supported, with the new one at the end of the list.

At this point, the user can delete, reorder, camp support... with the changes only occurring on the client.
Then, once the user get's things the way they like them, they will commit this support.
This is the only operation that will effect the camps being supported on the server side, in the database.

**Comment by gautamv16** [comment]
@BrentAllsop finished it with testing. Please check all scenarios. karun will be still doing unit manual tetsing on this by this week for any issue as this is the main part. But i need you to test it for all possible test cases. So that we will have a go ahead on this feature now.

**Comment by BrentAllsop** [comment]
This is looking great.  Closing this issue.
