### ISSUE TITLE
Uncaught TypeError on User supports page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#591]
Error --> Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': parameter 1 ('options') is not an object
Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/73909309-55eaba80-48d2-11ea-88b8-ac4b285d514f.png)

**Comment by BrentAllsop** [comment]
Ah, nice catch.  We should notice and fix java script errors like this.
But I don't think this should stop the release of 16?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Yes This will not stop release of 16..I found this during exploratory testing so I created issue .May be Varun will mark it for next release

**Comment by gautamv16** [comment]
@rupalichavan9860 Its Fixed. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still not fixed please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/74593735-7219f480-5054-11ea-9ead-bb99b493aec7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test now

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
