### ISSUE TITLE
Email format changes 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#593]
1. Proposed change to statement for camp Agreement submitted

All topic and camp names should be html links to the appropriate page.

Subject line should be "Proposed change to statement for camp **Topic Name / Agreement** submitted" instead of "Proposed change to statement for camp **Agreement** submitted"
Also change the mail body contents to 
"Username has proposed a change to this statement for camp **Topic Name / Agreement** which you currently directly support. If no supporters of this statement object to this change, it will go live in one day / 24 hours." instead of 
Username has proposed a change to this statement : for camp **Agreement** which you currently directly support. If no supporters of this statement object to this change, it will go live in one day / 24 hours.

![image](https://user-images.githubusercontent.com/40416610/74176562-f425aa00-4c5d-11ea-8761-afe9c2712568.png)

2. Proposed change to Agreement submitted
As of now keyword "camp" is missing 
Subject should be "Proposed change to **camp Topic Name / Agreement** submitted" instead of "Proposed change to **Agreement** submitted"

![image](https://user-images.githubusercontent.com/40416610/74178619-e3773300-4c61-11ea-87a8-a7bd31f1b45e.png)

3. Proposed change to Topic  submitted
Subject should be "Proposed change to **topic** Topic Name submitted"

As of now keyword "topic" is missing.Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/74178982-8760de80-4c62-11ea-8185-c07c1879fc2a.png)

Also as per discussed in skype channel need to do following changes
1. If at all possible, we should include the topic name, and the path of all parent camps, with the camp name.  And all of them could be links.
Maybe if in the subject line, it is to many characters, eliminate the parent camps.  Just the topic name and camp.

**Comment by gautamv16** [comment]
@rupalichavan9860  Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .
Proposed change to Topic submitted.Subject should be "Proposed change to topic Topic Name submitted" is still exists


![image](https://user-images.githubusercontent.com/40416610/82071893-5924ec00-96f4-11ea-8525-76f0fcfca990.png)


Other issues are working fine

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
