### ISSUE TITLE
Load More Topic With Manual Pagination

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#594]
Load More Topic With Manual Pagination

**Comment by BrentAllsop** [comment]
Is this talking about bot the list of topics on the front page, and on the browse page?
Hopefully the performance will be adequate for both of these, when it is working.
If not, we'll need to try cashing/warehousing data, and updating that once a day, or something.

**Comment by BrentAllsop** [comment]
Once this is completed, we should also make sure the performance for this closed issue is adequate,  Otherwise include some possible cashing solutions for that, also.
https://github.com/the-canonizer/canonizer.2.0/issues/602

**Comment by gautamv16** [comment]
This is implemented and deployed on staging . @rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .It is not working properly when changing namespace from Canonized list for drop down(Not displaying topics even if topics are available)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed it and now if you change the namespace it will go to the 1st page

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working great now.
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
When you change the the mind expert algorithm, with the /general/ namespace, the number topics per page isn't 20, and page 8 has no topics listed at all, so should not be listed in pagination set.

We need to make the current page graphically more clear in the pagination set.

**Comment by rupalichavan9860** [comment]
> When you change the the mind expert algorithm, with the /general/ namespace, the number topics per page isn't 20, and page 8 has no topics listed at all, so should not be listed in pagination set.
> 
> We need to make the current page graphically more clear in the pagination set.

Please check the same scenario when you set Filter < any value

**Comment by gautamv16** [comment]
graphical design for pagination is fixed . need to discuss the number of records displaying on the page

**Comment by gautamv16** [comment]
As discussed in the meeting , the number of topics on a particular page is not 20 as per our page length because of the filter for score . it is not displaying the topics having score value zero. So for now we will go with it and see if it does not create any problem or confusion, if so then we will reopen it and look for a solution. 

@rupalichavan9860  Pls check the graphical design point and if fine close this.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and I am fine with graphical design
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
How about, if no topics are listed in a page of topics, when a given algorithm/filter is set, we add a message like:

"There are no topics on this page, given the current algorithm and filter setting."

**Comment by gautamv16** [comment]
@BrentAllsop pls test

**Comment by BrentAllsop** [comment]
Yes, looks wonderful.
Closing this excessively big one.
Thanks!
