### ISSUE TITLE
Staging and live are crashing

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#596]
Pre- condition : User is not logged in

Staging : 
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Go to Browse
3. Click on any topic 

Expected Result : 
It should open respective agreement page

Actual Result : 
It is displaying ErrorException.Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/76017236-48156d00-5f44-11ea-88ce-079ec6a942c1.png)

Live : 
Steps to reproduce : 
1. Go to https://www.canonizer.com/
2. Go to Browse
3. Click on any topic 
4. Click on Manage/Edit Camp Statement or Manage/Edit This Topic or Manage/Edit This Camp

Expected Result : 
It should redirect to login page 

Actual Result : 
It is displaying ErrorException.Please refer attached screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/76017636-eefa0900-5f44-11ea-9603-954abcff2eef.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Still I am getting page crash .

please refer following steps
Staging :
Pre- condition : User is not logged in
Steps to reproduce :
1.Go to https://staging.canonizer.com/
2.Go to Browse
3.Click on any topic
4.Click on Manage/Edit Camp Statement or Manage/Edit This Topic or Manage/Edit This Camp

![image](https://user-images.githubusercontent.com/40416610/76706279-45690380-670c-11ea-9226-6db2844d5d3e.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I haves fixed it Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
