### ISSUE TITLE
Design and implement O-Auth login.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#597]
We need to first design and then implement O-Auth login ability, so people can login and link their identity, using credentials from google, facebook, twitter and github.

https://developer.okta.com/blog/2017/06/21/what-the-heck-is-oauth

Does laravel have some libraries for that?

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop If possible can we design login page like below or any other  design

![sign-in-from-with-facebook-and-twitter-button](https://user-images.githubusercontent.com/40416610/80962826-6821b980-8e2b-11ea-81dd-e8da1a596ee2.png)

As of now current design is

![image](https://user-images.githubusercontent.com/40416610/80963058-dd8d8a00-8e2b-11ea-9d00-0b783ef7b76a.png)

@BrentAllsop If you are okay with current design then I am also fine with this

**Comment by rupalichavan9860** [comment]
@gautamv16 

1. I am getting page crash on GitHub login .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/80963838-68bb4f80-8e2d-11ea-9512-138e9a881b5f.png)
I got this for first time and for second time I am able to logging in successfully. 
is it an issue?

2. I am getting page crash on facebook Login page->Not Now link
Also on LinkedIn ->Cancel button

![image](https://user-images.githubusercontent.com/40416610/80964473-8fc65100-8e2e-11ea-95ae-41133321c04c.png)

![image](https://user-images.githubusercontent.com/40416610/80964969-63f79b00-8e2f-11ea-84da-d9432cab9d3d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I have fixed the page crash issues and for design let @BrentAllsop confirm it

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Page crash issues are fixed now

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash on github button

![image](https://user-images.githubusercontent.com/40416610/82075163-76a88480-96f9-11ea-9e56-d169b7a14157.png)

**Comment by BrentAllsop** [comment]
3 remaining issues:
1. Delete connection button, with a confirmation popup.
2. twitter link is broken.
3. Replace the user's login name, if available.  (i.e. "brent.allsop" from google, instead of 114378572079231599653

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860 , I have implemented the above mentioned points and deployed on staging. pls test

**Comment by BrentAllsop** [comment]
This is all looking very nice.
The delete buttons look a little funky, would it work to have a seperate column for the delete button?


@CanonizerJim   Here is the current message Varun has implemented.
We need to clean this up, and have a link to the terms where it says it is a violation of Canonizer policy for single individuals to have multiple accounts.
====================================================
Multiple User Warning

It seems that there is already a user linked with this email in canonizer. If that user belongs to you than it is a violation of canonizer's agreement. So we suggest you to deactivate your another account and keep only single master account active. If you donot want to deactivate than click on cancel and try linking with other email for this social account.If you wish to deactivate than select the account below and click submit

 TBrent Allsop
 GBrent Allsop
Note: If you select the current user then you will be logged out of the canonizer
========================================

Need to include a penalty in both the warning and terms of service.
If you are reported or caught cheating in any way, your identity/email could be flagged with a permanent “cheater” flag which users may choose to use in canonizer algorithms to avoid counting the votes of people with a history of cheating.

**Comment by gautamv16** [comment]
@BrentAllsop Fixed Delete button design

**Comment by BrentAllsop** [comment]
Better, But there is a problem with the button, when you have a narrow window, it overlaps the link graphics.  This needs to be fixed.
Also, once it is linked, the words "google, facebook... are added to the linked image.
These names should be removed.  So that it just says link (when not linked) and linked (when linked) no name, just the icon.

Also instead of just "Delete" It should be "Unlink"?

**Comment by BrentAllsop** [comment]
Let's move the default algorithm to the Profile Info page and remove that tab.
Let's remove the words "Manage" and "My".
Let's change the order of the remaining tabs to:

1. Profile Info
2. Social OAuth Verification  (Capitalize the a, so it isn't just the word oauth.)
3. Change Password
4. Nick Names
5. Supported Camps
6. Crypto Verification  (was Metamask Account)

**Comment by rupalichavan9860** [comment]
> Better, But there is a problem with the button, when you have a narrow window, it overlaps the link graphics. This needs to be fixed.
> Also, once it is linked, the words "google, facebook... are added to the linked image.
> These names should be removed. So that it just says link (when not linked) and linked (when linked) no name, just the icon.
> 
> Also instead of just "Delete" It should be "Unlink"?

Yes.I am also facing this issue .When screen is 100 % "Delete" buttons overlaps link button

![image](https://user-images.githubusercontent.com/40416610/82732277-d9b59f00-9d29-11ea-9f20-b8540a8fe348.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash on twitter login .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/82736112-bd732b80-9d44-11ea-857f-20b6a82547f2.png)

**Comment by BrentAllsop** [comment]
I'd like to add an additional requirement for release 18.
In addition to the OAuth options on the login page:
Let's add an option to login via a one time code to their e-mail (doesn't require password).
And add an option to do the same via phone.
If they don't have a phone number, grey this option out, and if they mouse over it, throw up a (phone number required) message.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still facing following issues on Twitter login
Scenario 1:
1. Go to https://staging.canonizer.com/
2. Click on Log in->Twitter
3. Click on Cancel button
4. Click on Return to the_canonizer
5. Observe behaviour

Expected Result : 
User should get redirect to canonizer home page

Actual Result : 
I am getting page crash.Please refer following screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/84927851-12f3eb80-b0eb-11ea-89b1-d487b21e7b92.png)


Scenario 2 : 
1. Go to https://staging.canonizer.com/
2. Click on Log in->Twitter
3. Sign in with valid Username and Password(User email is not available in twitter)
4. This is redirecting to User Email Confirmation page 
5. Enter any mail(like "test@test4" or any valid email and click on Submit)

Actual Result : 
I am getting page crash for first time and user is getting logged in for second time with same mail.Please refer following screenshot for more details
![image](https://user-images.githubusercontent.com/40416610/84928356-e2608180-b0eb-11ea-8c8e-9e0ab1ece9c4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed.pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 After copying production database and files to staging I checked Google login and on Google button click I am getting following page crash

![image](https://user-images.githubusercontent.com/40416610/85497264-3fcc6500-b5fb-11ea-9c50-ab04dfab865c.png)


Also on GitHub click and Account settings-> Social Oauth Verification tab click getting following page crash
 
![image](https://user-images.githubusercontent.com/40416610/85497367-6db1a980-b5fb-11ea-952a-dc775688da1a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , Yes it is coming because i have created a new table for social logins and which is not there on production since 18th release is not deployed to production yet. Because you have copied the production db to staging it has overwrite the database and now the social user tble is not there thats why it is displaying error

**Comment by gautamv16** [comment]
@rupalichavan9860 , I have added the table on staging. please test now

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I am facing page crash on verify email page.Please refer following screenshot
![image](https://user-images.githubusercontent.com/40416610/85728285-64b4fb00-b715-11ea-859e-e06834dbac4a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed , pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still getting same issue also Email validations are missing on verify email page
I just entered email e.g "aaaaaaaaaaaaaa" and I am getting page crash.Please refer screenshot

![image](https://user-images.githubusercontent.com/40416610/85954449-19108480-b995-11ea-928e-ea9b90f6e4bd.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 email validation implemented . that page crash is also due to this so its also fixed. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still I am getting page crash when user enters  email like "1@1.com"
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/86906974-f9662280-c131-11ea-9309-b029284ceb74.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Page crash issue is resolved now.
