### ISSUE TITLE
Both topic and camp name in optional URL SEO values.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#598]
Currently, we have optional SEO values in the URLs like this for the agreement camp with the topic name:
https://canonizer.com/topic/88-Theories-of-Consciousness/1

For camps, we replace the topic name with the camp name like this:
https://canonizer.com/topic/88-Representational-Qualia/6

It would be more informational and more consistent to always have the topic name, with the topic number, and the camp name with the camp number like this:

https://canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement
or since 1-Agreement is the default just
https://canonizer.com/topic/88-Theories-of-Consciousness
and
https://canonizer.com/topic/88-Theories-of-Consciousness/6-Representational-Qualia

**Comment by BrentAllsop** [comment]
It would be nice if all the code that requires these changes be moved into one unified procedure.  So part of the requirements is to refactor things so that changes like this only require changes in one function, which everyone calls to get the same URL.

Also, testing this is much easier, since only one test would be required.

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. 
We should get the same URL when we goes to any topic name/camp name link , bread crumb links.

**Comment by gautamv16** [comment]
@rupalichavan9860 it is fixed for breadcrumb links . pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Please check this from user supports page 

I have checked for camp 
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/6-Representational-Qualia

Click on any supporter nick name -> click on Representational Qualia

and it is displaying URL as 
https://staging.canonizer.com/topic/88-Representational-Qualia-Theory/6

also camp name is mismatching.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/92329998-45c5d400-f089-11ea-9354-f3f870509a8e.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.We need to change the same for following places

1. Go to Theories of Consciousness and click on `<Start new supporting camp here>`
URL should be 
https://staging.canonizer.com/camp/create/88-Theories-of-Consciousness/1-Agreement
As of now URL is 
https://staging.canonizer.com/camp/create/88-Theories-of-Consciousness/1

2.  Go to Theories of Consciousness and click on Manage/Edit Camp Statement
URL should be 
https://staging.canonizer.com/statement/history/88-Theories-of-Consciousness/1-Agreement
As of now URL is
https://staging.canonizer.com/statement/history/88-Theories-of-Consciousness/1

3.  Go to Theories of Consciousness and click on Camp Forum
URL should be 
https://staging.canonizer.com/forum/88-Theories-of-Consciousness/1-Agreement/threads
As of now URL is 
https://staging.canonizer.com/forum/88-Theories-of-Consciousness/1/threads

4. Go to Theories of Consciousness and click on Directly Join or Manage Support
URL should be 
https://staging.canonizer.com/support/88-Theories-of-Consciousness/1-Agreement
As of now URL is
https://staging.canonizer.com/support/88-Theories-of-Consciousness/1

5. Go to Theories of Consciousness and click on Manage/Edit This Topic->click on topic name Theories of Consciousness  in bread crumb
URL should be 
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement
As of now URL is
https://staging.canonizer.com/topic/88-Theories-of-Consciousness/1

6. Go to Theories of Consciousness and click on Manage/Edit This Camp
URL should be 
https://staging.canonizer.com/camp/history/88-Theories-of-Consciousness/1-Agreement
As of now URL is 
https://staging.canonizer.com/camp/history/88/1

7. Click on "Algorithm Information"
URL should be 
https://staging.canonizer.com/topic/53-Canonizer-Algorithms/1-Agreement
As of now URL is 
https://staging.canonizer.com/topic/53-Canonizer-Algorithms/1

8. Click on "Help"
URL should be 
https://staging.canonizer.com/topic/132-Help/1-Agreement
As of now URL is 
https://staging.canonizer.com/topic/132-Help/1

9. Go to Theories of Consciousness and click on Delegate your Support
URL should be 
https://staging.canonizer.com/support/88-Theories-of-Consciousness/1-Agreement-358
As of now URL is 
https://staging.canonizer.com/support/88/1-358

here 358 is user's ID to whom user wants to delegate their support.
@BrentAllsop Do we need any changes here.Please confirm?

**Comment by BrentAllsop** [comment]
Hi Rupali, thanks for finding all of these.
It seems to me this is bad coding.  All of these places in the code should be using the same code.
So one change fixes them all?
Let's code review these changes, before we close this.

**Comment by gautamv16** [comment]
deployed and fixed the changes in above mentioned places. @rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified .Working fine on all the mentioned places.
@BrentAllsop Can you please test and close if fine for you?

**Comment by BrentAllsop** [comment]
Sweet, everything checks out OK, so closing this.

**Comment by rupalichavan9860** [comment]
@gautamv16 I am facing following URL issue when adding /editing news, So reopening the issue

Scenario: 
1. Go to any topic 
2. Click on Add News link
3. Click on Cancel 
4. Repeat step 2 and 3 , 2 or 3 times
5. Observe URL value
6. Again Click on Add News or Edit News
7. Observe URL value

Actual Result : 
Every time camp name is getting added at the end of the URL. Please refer attached screenshot

After Step 5
![image](https://user-images.githubusercontent.com/40416610/94279134-53c09380-ff69-11ea-8f76-896cdfba3617.png)

After Step 6
![image](https://user-images.githubusercontent.com/40416610/94279362-9c784c80-ff69-11ea-8cca-fe300e135bad.png)

![image](https://user-images.githubusercontent.com/40416610/94279518-d8abad00-ff69-11ea-89cb-def9769b3be7.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine now so closing this issue
