### ISSUE TITLE
Page crash on support page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#600]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create a fresh topic or browse any topic
4. Create new camp using same user or use existing camp
5. Join the camp using same user
6. Now again click on Directly join or manage support
7. Click on cross sign on newly created camp name
8. Click on "Submit"

Please refer attached screenshot for error exception
![image](https://user-images.githubusercontent.com/40416610/77535446-a1781880-6ec0-11ea-8713-fb70a83fb12d.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test it is resolved

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working now so closing
