### ISSUE TITLE
Page crash on Create New Camp link

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#601]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Select filter as of date and select any date(past date) <= topic created date
5. Click on Create New Camp link

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/78675461-bdd57580-7902-11ea-8007-6569358b50cd.png)

**Comment by rupalichavan9860** [comment]
Also getting different page crash on Create New Camp link.Refer following scenario

1. Go to any topic and select any sub camp
2. Select as of date filter and select any date
3. Click on Create New Camp link

Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/78678455-9a142e80-7906-11ea-88e2-e712347f7c6a.png)

**Comment by BrentAllsop** [comment]
Good catch.
I'm thinking that if you create a new camp, it should set the as-of value to default.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working.But now I am getting another page crash on camp save.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/78807896-50007b00-79e2-11ea-83db-aee71e573ce6.png)

**Comment by gautamv16** [comment]
@BrentAllsop yes i have done this and fixed it. @rupalichavan9860 pls test and confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
