### ISSUE TITLE
Filters are not working properly on Browse page 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#603]
As per discussion, Browse page should save selected namespace name in session

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 still facing following issue 
scenario :
Select any namespace click on Only My Topics checkbox and observe Namespace drop down value

Expected Result : 
Selected namespace should display 

Actual Result : 
As of now it is always displaying selected value as /general/
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/81910631-d283e800-95e9-11ea-8e1b-aa56b5a2ea82.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. everything is working fine except namespace "All" .Please refer scenario

Select any namespace and again select "All" from namespace drop down and observe results

Expected Result : 
List should display all the topics from all namespaces

Actual Result : 
User can see previously selected list .
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/82725133-8840ec00-9cf8-11ea-9928-440071e757e4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 I am still facing the issue.Please check following scenario

Select All from Namespace drop down and click on "Only My Topics" and observe behavior

Expected Result : 
It should lists all the topics created by logged in user

Actual Result : 
When user click on "Only My Topics", it is getting deselected immediately

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this
