### ISSUE TITLE
User names are not listing properly under respective camp support Tree 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#604]
Steps to reproduce : 

Go to any topic which have sub camp and try to add support to agreement camp(If user supported to sub camp) and sub camp(if user supported to agreement camp) .

Expected Result : 
User's name should display under respective camp support tree(Agreement/sub camp)

Actual Result : 
As of now when user is supporter of agreement camp and trying to add support to sub camp,user is getting support added mail for sub camp but user name is not listing under sub camp support tree and vice versa

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working for me so closing this
