### ISSUE TITLE
Page crash on thread creation

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#605]
Error Exception on Thread creation.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/79334795-96079280-7f3e-11ea-98c9-6ae825cd2dea.png)

**Comment by rupalichavan9860** [comment]
Also not getting thread creation mail

**Comment by akuks** [comment]
@rupalichavan9860 I am not getting this error. While creating threads in local and as well as staging environment. Can you please pen down the steps to reproduce?

**Comment by akuks** [comment]
> Also not getting thread creation mail

Thread is not created, hence you will not receive any emails. Otherwise you will.

**Comment by rupalichavan9860** [comment]
@akuks Thread is getting created but not getting mail.
Steps to reproduce :

1. Go to Camp Forum
2. Click on Create Thread
3. Enter Thread title and click on Submit

![image](https://user-images.githubusercontent.com/40416610/79344394-67dd7f00-7f4d-11ea-9a34-06d729dfd9ac.png)

**Comment by rupalichavan9860** [comment]
I just observed there are two different exceptions one is "Undefined variable: dataObject" and other is "Undefined variable: userSub"

**Comment by gautamv16** [comment]
@Ashutosh I have fixed it. and  deployed it to staging, sorry I did not checked the ticket on GitHub. I found this while checking and fixed

@rupalichavan9860  Pls test

**Comment by akuks** [comment]
Oops. I didn't see this. I was working on it. I'll resync my branch.

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16 Tested .Page crash issue is resolved but I am getting 12 thread creation and post submitted mails

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting 12 mails for specific topic https://staging.canonizer.com/topic/237-Test-topic---23-feb-2020-test/1

Please check

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed it pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 I am still getting 12 mails for specific topic https://staging.canonizer.com/topic/237-Test-topic---23-feb-2020-test/1

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
