### ISSUE TITLE
Fix "Expert" canonizer algorithms.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#609]
The "expert" canonizer algorithms needs to handle the "pirate" case where all the pirates only vote for themselves to be the pirate leader.

See [this section of the "Captain Teague"](https://www.youtube.com/watch?v=nfKFHTaGzuU&t=105) scene from one of the Pirates of the Caribbean movies.

So we give the pirates a 5 times their vote reward, if they vote for anyone else.
It is OK to support themselves, they just need to provide additional information about who else they vote for, after themselves.

This way, Even if all the pirates vote for themselves as their top choice, they provide additional information which can be used to differentiate who is the most popular pirate, after themselves.

The camp_tree_count function, used in the expert canonizer algorithms currently has this clause at the end.

        if($directSupports->count() > 0 || $delegatedSupports->count() > 0){
             return $expertCampReducedTree[$expertCamp->camp_num]['score'] * 5;
        }else{
             return $expertCampReducedTree[$expertCamp->camp_num]['score'] * 1;
        }

All this does is give the pirates the 5 times reward if they have any direct or delegated supporters.
Which will not help, if all the pirates only vote for themselves.

Here is this statement from the 1.0 system:

    if ((!$expert_camp->{supporters}->{$nick_name_id}) ||        # don't support yourself or
        $#{$expert_camp->{support_hash}->{$nick_name_id}} > 0 ) {# support more than just yourself
        # give a significant reward for supporting more than yourself.
        $score = $expert_camp->{score} * 5;
    } else {
        $score = $expert_camp->{score} * 1;
    }

As the comments in this code indicate the person should only get the 5 times reward
if they don't support themself in this topic
    or
they support more than one camp in the topic.  (i.e. they support more than themselves)

**Comment by akuks** [comment]
pushed to staging

**Comment by BrentAllsop** [comment]
Hi Ash,

Sorry I’m not being clearer with all this.
You added this code:

        $only_support_himself = 
          ($directSupports->count() == 1 & $directSupports[0]->nick_name_id == $nick_name_id) 
          ? 1 
          : 0;


$nick_name_id    is the id for which we want to know their canonized score.
$expert_camp     is the camp with the camp_about_id the same as $nick_name_id.

What you have is confusing how many people support the $expert_camp vs how many camps does the $nick_name_id support in the topic.  We do not need to know how many people support the $expert_camp (directly or indirectly), we need to find out how many camps the ID supports in this topic.

We need two variables:

$does_not_support_self
    This should be true if $nick_name_id, does not support $expert_camp

$supports_more_than_one_camp
    This is true if $nick_name_id supports more than one camp in this topic.

It would be nice if we could no these kinds of things, without needing to know anything about sql data field names, filters and all that kind of stuff.  Could someone describe some code that will calculate exactly the above two values?

Then we want exactly this condition:

    if ($does_not_support_self ||
        $supports_more_than_one_camp ) {
      $score = $expert_camp->{score} * 5;
    } else {
        $score = $expert_camp->{score} * 1;
    }

**Comment by akuks** [comment]
@rupalichavan9860 @BrentAllsop Please test.

**Comment by BrentAllsop** [comment]
I attempted using the "Mind Expert" canonizer on the [mind expert topic](https://staging.canonizer.com/topic/81-Mind-Experts/1) on staging, but got this error in the place of the camp tree structure:
topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0topic-support-nickname-81Undefined offset: 0

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this and close if fine for you?

**Comment by BrentAllsop** [comment]
I'd like to look at this more, before we close this.
But marking it for ready to release so it won't hold up release 18.

**Comment by BrentAllsop** [comment]
https://github.com/the-canonizer/canonizer.2.0/issues/538 is related to this one.
That one is currently tracking the wallet linking.
