### ISSUE TITLE
Error occured on camp history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#610]
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/80301644-d4187800-87c2-11ea-9cf3-2bb6cf46cd6f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , I have fixed it. Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
