### ISSUE TITLE
My Supports : Camp names are missing and getting page crash on remove support of the blank camp name

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#611]
Steps to reproduce : 

1.  Go to https://staging.canonizer.com/
2.  Login with valid email and password
3.  Go to browse 
4. Select Namespace as "Sandbox testing" and select as of filter "as of date" = "6/18/2019, 5:30:00 AM"
5. Go to Account settings -> My Supports 

 Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/81470689-b3f8a800-9209-11ea-8653-1784b60d1ed8.png)

I think filter values are getting saved in session.User supports page also not listing all the supported camps

Please confirm..

**Comment by rupalichavan9860** [comment]
@gautamv16 This issue is exists on live also. And when I am trying to remove this null supports I am getting page crash .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/81470918-2f0e8e00-920b-11ea-916f-9edef9e06ff7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .I can see the camp names now but still getting page crash on removing support.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/81890332-642c2f00-95c3-11ea-98ef-9af2d0cc19d2.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , Fixed Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working fine now so closing this issue
