### ISSUE TITLE
Enable uploading of files of any type.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#613]
We want to be able to host files of any type.
Especially mp4 files and such.
Currently you get this error:
Error! The file must be a file of type: jpeg, bmp, png, jpg, gif.

We want to remove this restriction.

**Comment by rupalichavan9860** [comment]
@gautamv16 I am trying upload file of any type(in progress) but I found 1 minor issue.

As we can now upload file of any type we need to change the page title also.Currently page title is "Upload images only ( jpeg,bmp,png,jpg,gif ), Max size 5 MB"
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/89852223-08fede00-dbac-11ea-88f2-c664c2e94487.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine for me.
@BrentAllsop Can you please test and close if fine for you

**Comment by BrentAllsop** [comment]
Yea, I tried it and it is looking nice, so closing this one.
