### ISSUE TITLE
supports page isn't ignoring objected to records.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#615]
If you look up the supports of "Lenny":
https://canonizer.com/user/supports/38?topicnum=81&campnum=19&namespace=13#camp_81_19

you see that he supports the "Leon Maurer" camp under the "Daniel Dennett" topic.
While, "Daniel Dennett" is the name on the latest topic record, that record has been objected to (is red) so it should be ignored.  The name on the live record is: "Mind Experts" and this is what should be displayed instead of "Daniell Dennett".

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. pls test

**Comment by BrentAllsop** [comment]
nice, ok with me to close this one.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested and verified.Working fine now so closing this issue
