### ISSUE TITLE
Arrows obscure menue on mobile

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#616]
![Screenshot_20200523-073202](https://user-images.githubusercontent.com/6559312/82731982-90ccfe80-9cc7-11ea-9c9b-7847a13c3810.png)

The lines in the tree are correctly under the menu, but the arrows are not.

**Comment by rupalichavan9860** [comment]
@gautamv16 Still I can see some design issues.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/89739137-b8985b00-da9b-11ea-878d-12909594b7b6.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I am still facing some layout issues.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/90258859-c1f04180-de66-11ea-849d-e78d8fd0331b.png)


@BrentAllsop Can you please check and confirm it this is still an issue or close if fine for you

**Comment by BrentAllsop** [comment]
Yea, I can see the issue Rupali is talking about here, on my phone.
It'd be nice to get this fixed, before we close this.

**Comment by rupalichavan9860** [comment]
@gautamv16 as per discussion in meeting it is difficult to fix arrows issue on smaller size devices and everyone is okay with current layout so closing this issue
