### ISSUE TITLE
namespaces need to be able to have "_" and " " in the names.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#617]
Admin system.

It appears that when you edit or create a new name space, even if there are spaces in the existing name, already, all spaces and underbars (_) get replaced with '-'  characters.

**Comment by BrentAllsop** [comment]
Don't do any mapping of characters.
Either allow or don't allow the character.

**Comment by BrentAllsop** [comment]
Let's not allow spaces (hopefully, don't allow the user to type spaces, or any other illegal character into the form field.
But we should allow "_".
Also, if the user supplies "/", before and after, this should work correctly. so we don't end up with something like:  "//organizations//united-utah-party/"

**Comment by gautamv16** [comment]
@BrentAllsop  I have fixed it , now space is not allowed only "-" and "_" is allowed but if user put a "-" in the namespace i have changed it to "_" in the backend.

@rupalichavan9860 . Pls test

**Comment by BrentAllsop** [comment]
Let's not do any changes of characters.
If it is illegal, just say so, don't change it, let the user change it, if they want that.
Also, when I tried "/a_dashed_name/", but it gave the error: 'Namespace name must not contain any space.'
Also 'any' is plural, so should be spaces, not just space.
I'm thinking we could just have one message where we list all illegal characters?

**Comment by rupalichavan9860** [comment]
@gautamv16 

1. When user trying to create namespace with some special characters like (@,#), e.g "test@@##$%^&*()_namespace",error message is displaying as "Namespace name must not contain any space."

Expected Result : 

Error message should be specific

2. Multiple slashes in namespace label .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/85733897-35ed5380-b71a-11ea-9df0-96770d93d729.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , pls check its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Working good now.
but as per https://github.com/the-canonizer/canonizer.2.0/issues/617#issuecomment-647238633 namespace field should accept "/"

As of now namespace field is not accepting "/" character 
@gautamv16 @BrentAllsop Please clarify? We should "/" character allow or not?

**Comment by BrentAllsop** [comment]
Yes, I am thinking we should allow slashes and we should always force start and end with slash but make sure we don't end up with double slashes if the user does or does not add them.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thanks for clarification.
@gautamv16 Can you please implement above point.

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860  I have allowed the backslashes in the name space, but i did not made it compulsory to add it in namespace, if user add it in namespace it will allow him and create label with single slashes only , if user donot put slashes in namespace name then name will be without slashes but label is with slashes which we have already in place. Please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can you please check and close if fine for you?

**Comment by BrentAllsop** [comment]
This name space name already exists in the staging db.
While this won't be possible in the db on the live system, when you submit any such, "/" it should only be (optionally) allowed at the beginning and end, and no place else in the name.
Also, if you were editing a name on page 3, when you hit submit, it should go back to page 3.  (maybe save this in session(not good) or send as an argument with the submit (much better since it makes it state independent), or something?)

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860  Pls test i have removed the label column from namespaces and implement the validation to add slashes only at beginning and end

**Comment by rupalichavan9860** [comment]
@gautamv16 I can't see the namespace names on browse page .Is this because of this changes.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/88086073-6521a400-cba4-11ea-9a19-76d24db5b043.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Fixed. Please Test

**Comment by BrentAllsop** [comment]
If you submit the form, with an invalid name, the name is lost.
The invalid name should still populate the form, when returning from the submit, so you only need to fix it, rather than retype the whole thing.

Also, slash representations should be consistent and clean in the data.
So you don't need to do additional checks, everything the data is used.
the beginning and ending slashes should ether always be there, or not, including a consistent standard for parent name spaces.

**Comment by gautamv16** [comment]
@BrentAllsop  I have fixed the issues mentioned above and discussed in the meeting. Please test and verify

**Comment by BrentAllsop** [comment]
Yes, functioning nice.  So I'm going to close this.
