### ISSUE TITLE
make support@canonizer.com on bottom of all pages a link.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#618]
Like:
<a href="email://support@email.com">support@email.com</a>

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I can see a link for support@canonizer.com on bottom of all pages except on Blog page.

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed.pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.

**Comment by rupalichavan9860** [comment]
@gautamv16 link for support@canonizer.com is missing on blog bottom  on production.

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine on production now so closing this issue
