### ISSUE TITLE
Change "Browsing as: Guest_31" to just Guest.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#623]
Remove the "_31" from the "Browsing as Guest_31"

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop  Please check and close if fine for you

**Comment by BrentAllsop** [comment]
Yup, looking nice so closing this one.
