### ISSUE TITLE
Create '/organizations/united_utah_party/' namespace.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#624]
Create '/organizations/united_utah_party/' namespace.

**Comment by gautamv16** [comment]
@BrentAllsop , @rupalichavan9860  created this on staging. please check

**Comment by BrentAllsop** [comment]
Looks perfect on staging.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested.Looks good to me also so closing this
