### ISSUE TITLE
Login Feature with OTP issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#625]
1. Design 

Can we design Login Feature with OTP like Flipkart. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/85047252-2e282f00-b1af-11ea-8287-e4f164268676.png)

As of now we are having checkbox for Request OTP , user needs to check the checkbox and also need to click on Log in button then only user is redirecting to verification page

2. Error message 
Scenario : 
Without entering Email or Phone Number ,check Request OTP checkbox and click on Log in button

Expected Result : 
It should display error message "Please enter valid Email ID/Phone number" or "The email/Phone Number field is required."

3.Label name and Page Name
Checkbox label name should be "Request OTP" instead of "Request Otp"

![image](https://user-images.githubusercontent.com/40416610/85048090-6e3be180-b1b0-11ea-9d0d-952e867afc22.png)

Page name should be "Login OTP Verification" instead of "Login Otp Verification".

![image](https://user-images.githubusercontent.com/40416610/85048034-55cbc700-b1b0-11ea-8ffe-b87a6eb5be81.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 , I haved the issues mentioned, design part is not done yet.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified

**Comment by gautamv16** [comment]
@rupalichavan9860 design implamanted, pls check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looks good now
@BrentAllsop Can you please check and confirm if you are okay with design

**Comment by BrentAllsop** [comment]
Old people (like me) may not understand "Request OTP"
So, let's solve that by changing it to:   "Request One Time Password"?

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. 

Can you please change the error message to "Please enter One Time Verification Code" instead of "Please enter OTP"

![image](https://user-images.githubusercontent.com/40416610/107172452-681e9d80-69eb-11eb-87ad-069b30cee661.png)

And error message  to "Error! Incorrect One Time Verification Code Entered" instead of "Error! Incorrect OTP Entered"

![image](https://user-images.githubusercontent.com/40416610/107172496-81bfe500-69eb-11eb-9901-47739059b1fb.png)


Also at some places it is "One Time Password" and at some places I can see it as "One Time Verification Code".

It should be same at all places. Either it  should be "One Time Password" or "One Time Verification Code" and need to change the same for error messages and other places
Please check screenshots for more details


On Login Page : 
![image](https://user-images.githubusercontent.com/40416610/107172323-1249f580-69eb-11eb-8ed4-ec5026cb9985.png)

On Verification Page : 
![image](https://user-images.githubusercontent.com/40416610/107172652-e2e7b880-69eb-11eb-9de5-243543e85950.png)

Email : 
![image](https://user-images.githubusercontent.com/40416610/107172417-4fae8300-69eb-11eb-93d8-00834fbdb90f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 It is fixed i have changed one time password to one time verification code in all places.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Looking uniform at all places so closing this issue
