### ISSUE TITLE
irrelevant data on camp history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#628]
I can see some irrelevant data on camp history page.Please refer attached screenshot.

![image](https://user-images.githubusercontent.com/40416610/87245161-d3f25500-c460-11ea-98ff-1c2fc6d6ed11.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is fixed . Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Looking nice now so closing this issue
