### ISSUE TITLE
User is not getting removed support emails

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#630]
Previously when user removed support from any camp user is getting removed support mail .I am not getting removed support mails now.Please check

**Comment by BrentAllsop** [comment]
I changed my camp (left one camp (a) and joined another (b) in one step
The "I left" email said I left camp (b), when a really left camp (a)
The "I joined" email had the correct (b) name.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I am getting removed support mails now so closing this issue
