### ISSUE TITLE
User should not be able to Delegate their support to themselves

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#631]
Steps to reproduce :
1. Create any camp and support the camp
2. With the same user try to delegate the support

Actual Result : 
As of now user can delegate their support to themselves

Expected Result : 
User should not be able to delegate their support to themselves

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and it is working good now.But I found one more issue on this

Scenario: 
User A is already delegating their support to User B, But still User A can see "Delegate Your Support"/again able to delegate their support to User B for the same camp
And I can see 2 mails one is User A removed their support and another is User A has just delegated their support to you

I think user should not allow to delegate their support  if user is already delegating their support to someone .
@BrentAllsop Please confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 As per discussed in meeting user should not allow to delegate their support if user is already delegating their support to someone.
Also when delegated supporter want's to join the camp directly delegated supporter should see warning message that they are already delegating their support to someone for the same camp.

@BrentAllsop Please correct the above comment if any mistake

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working great now.
I found one minor issue in delegated email .Please refer attached screenshot.

Email body should be "Rupali N has just delegated their support to Rupali Chavan in this **camp**:Exploratory testing 2 / test camp 1" instead of "Rupali N has just delegated their support to Rupali Chavan in this **topic**:Exploratory testing 2 / test camp 1"

![image](https://user-images.githubusercontent.com/40416610/90531039-3262cf80-e193-11ea-9534-369455bf1988.png)

**Comment by BrentAllsop** [comment]
Yes, camp is more precise.  Let's get this fixed, then we can close this one.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.Looking nice so closing this issue
