### ISSUE TITLE
Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#633]
Steps to reproduce : 

1. Go to https://staging.canonizer.com/ or https://canonizer.com/
2. Login with valid email ans password 
3. Go to Account Settings->Crypto Verification (was Metamask Account)
4. Open developer tools

Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/88910047-7db34d80-d279-11ea-8d1a-78744576a898.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Right click on Enable Metamask button and click on Inspect and check for console error

**Comment by rupalichavan9860** [comment]
@gautamv16 Found more issues on the same page

![image](https://user-images.githubusercontent.com/40416610/126078585-ba6d5757-0020-4f97-b955-418f1d5c405a.png)

**Comment by rupalichavan9860** [comment]
Still getting issues 

![image](https://user-images.githubusercontent.com/40416610/139406517-93b1f76b-ec0a-434e-8336-f1b07bb52823.png)

**Comment by kshitij1326** [comment]
@rupalichavan9860 The above issue was occurred due to multiple click on Enable Metamask . So i have hide the button and show a text 'processing...' when user clicks on Enable Metamask button. Kindly check and let us know in case of any issue.

**Comment by rupalichavan9860** [comment]
@kshitij1326 Still getting below issues
![image](https://user-images.githubusercontent.com/40416610/140728809-cb455046-f382-4072-b86c-9f4c49571289.png)

**Comment by kshitij1326** [comment]
Above error will occurred when there will be any pending request from Metamask (when user clicks on enable metamask, a popup window will opened and user closes the popup without any action then the request will be stil in pending state ).

For this, I have follow the documentation of metamask (We have to disable the button when clicked).

On visiting metamask documentation site i seen the mentioned error there also 

https://docs.metamask.io/guide/getting-started.html#connecting-to-metamask

There is also an issue opened on metamask github repository for the same

https://github.com/MetaMask/metamask-extension/issues/10584

**Comment by ashish76** [comment]
@rupalichavan9860 I had a discussion regarding this issue with @gautamv16. I had explained the issue and it is a known issue from the MetaMask end which has not been resolved yet. So we can leave this for now. If you look at the Kshitij comment for this task, you will be able to know that.

**Comment by rupalichavan9860** [comment]
As this is known issue from MetaMask end , closing this
