### ISSUE TITLE
Design issues : Mobile device

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#635]
I found some design issues on mobile device.Please refer attached screenshots
1)Social Oauth Verification page
Social Name and Action columns are missing.

![image](https://user-images.githubusercontent.com/40416610/89554333-5980df00-d82c-11ea-820c-0864c5c05cf6.png)

2)Browse Page : Alignment is not proper

![image](https://user-images.githubusercontent.com/40416610/89554491-8b924100-d82c-11ea-8571-c4367bb84e69.png)

3)Agreement page : Alignment is not proper

![image](https://user-images.githubusercontent.com/40416610/89554593-b1b7e100-d82c-11ea-9467-42dc4dab9419.png)

![image](https://user-images.githubusercontent.com/40416610/89554967-24c15780-d82d-11ea-8bde-744b33bed396.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I found new layout issue on agreement page .Is this because of this fix?Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/89738759-ce585100-da98-11ea-8a33-062ca855b9d8.png)


Also following issue is still exists
1)Social Oauth Verification page
Social Name and Action columns are missing.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Following issue is still exists
1)Social Oauth Verification page
Design is still not proper when using mobile device->Social Name and Action columns are missing.

**Comment by gautamv16** [comment]
@rupalichavan9860 , i have checked this , it is fine as in mobile device it has horizontal scroll for those columns

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I can see the horizontal scrollbar and looks good so closing this issue
