### ISSUE TITLE
bad links in someone objected email.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#639]
This was contained in an e-mail I received when someone objected to one of my proposals:

"See this link for options you can take when there are objections: | See this link for options you can take when there are objections: | See this link for options you can take when there are objections:"

The link is only a link to the objection in the history page.
That link should be provided, but not here.
That link should point to the "Dealing with Disagreement" camp here: https://canonizer.com/topic/132-Dealing-with-disagreement/4

Also, you we don't need to end a hot link with ":"

**Comment by ashish76** [comment]
Changes are 
1. make the text "proposed changes" of the email body hyperlink with the history link
2. CTA "See this link for options you can take when there are objections" redirects to the "Dealing with Disagreement" camp.

**Comment by rupalichavan9860** [comment]
@ashish76 @gautamv16 I am getting page crash on Object button of camp history page.

![image](https://user-images.githubusercontent.com/40416610/134482108-ce5d07ed-62ff-4ab5-8b14-ff1261194028.png)

**Comment by ashish76** [comment]
Could you please give the proper permission to the logs folder? I have checked this issue in my development environment and it is working fine.

**Comment by ashish76** [comment]
As discussed with @gautamv16 I have updated the "Dealing with Agreement" link static inside a General Class.

**Comment by ashish76** [comment]
@rupalichavan9860 Please test this once it gets merged into the staging

**Comment by rupalichavan9860** [comment]
@ashish76 @gautamv16 page crash issue is fixed on camp history but in mail I can see "proposed change" as a link and  which is not working

![image](https://user-images.githubusercontent.com/40416610/134551891-6703947c-6f7c-4aa5-8bb2-85a59d230721.png)

![image](https://user-images.githubusercontent.com/40416610/134552023-3ce800b6-62e2-4f64-aec4-d7045307b9de.png)

**Comment by rupalichavan9860** [comment]
@ashish76 @gautamv16 Please check this also

![image](https://user-images.githubusercontent.com/40416610/134554084-224fa733-e18e-41b5-a1f9-44f417a63f8f.png)

**Comment by ashish76** [comment]
@rupalichavan9860 I am looking into this issue once again. I already resolved this issue yesterday. I am not sure whether the staging environment has the updated code. I can see that my pull request has not merged yet. 
@gautamv16 Could you please merge the pull request?

**Comment by ashish76** [comment]
@rupalichavan9860 I have tested this on staging and the HTML is rendering properly in the email template. Attached is the screenshot for your reference.
![Screenshot from 2021-09-24 15-10-05](https://user-images.githubusercontent.com/23633446/134654759-38e3caca-d017-4a46-ab3e-8c1bd9779d76.png)

**Comment by akuks** [comment]
What happens if you click on the proposed changed link? Is it working now?
I think rupali refers the link is not working

**Comment by ashish76** [comment]
On click of proposed changes, it will redirect to the topic history (https://staging.canonizer.com/topic-history/281) and it is working.

**Comment by rupalichavan9860** [comment]
@ashish76 @gautamv16 Tested and verified. Working fine now so closing this issue
