### ISSUE TITLE
All the places that don't allow certain characters need to explain what characters.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#640]
All the places that don't allow certain characters need to explain what characters.

Any place a message like "The title format is invalid."  (camp thread title) is presented

A full description of what is and isn't legal needs to be provided, so users can fix it without trial and error.

And we need to look into way of allowing more characters, possibly by escaping them or something, internally.

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop Can you give some examples with screenshots?

**Comment by BrentAllsop** [comment]
Sorry, things haven't been designed to that level of detail, yet.
We just need to find some way, so when someone get's an error, saying there is an invalid character, they need more information so they know what they can and can't do.

**Comment by BrentAllsop** [comment]
@HamzaBinMansoor, forgot to tag you in the last post.

**Comment by ashish76** [comment]
I have updated the suggested changes. Below is the list of files in which I have made the changes 

1. Registration Controller (App\Http\Controllers\Auth\RegisterController.php)
2. Topic Controller (App\Http\Controllers\TopicController.php)
3. Settings Controller (App\Http\Controllers\SettingsController.php)
4. Reply Controller (App\Http\Controllers\ReplyController.php)
5. NewsFeed Controller (App\Http\Controllers\NewsFeedController.php)
6. CThreads Controller (App\Http\Controllers\CThreadsController.php)

In the above files, the changes are 
- Correct that validation message 
- Add a few new messages of validation based on the rule

**Comment by ashish76** [comment]
@rupalichavan9860 please test this

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified. 
Just a minor change.
Just for uniformity can we have uniform error messages for First name ,last name and middle name on register page and settings page. Also some error messages are ends with '.' and some are not.

Register : 

![image](https://user-images.githubusercontent.com/40416610/134564364-3dbe2d75-a0c4-45d5-a2a7-501088ae6b70.png)


Settings : 
![image](https://user-images.githubusercontent.com/40416610/134564521-f20d5442-1285-421e-ba2e-7b0de5460201.png)

**Comment by ashish76** [comment]
@rupalichavan9860 I have made the suggested changes in the files. Please look at this once again.

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified
