### ISSUE TITLE
Bread Crumb links on forum thread page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#641]
The camp forum thread pages only have a link back to the list of all threads.
It would be nice to also have the standard breadcrumbs link back to the camp, and all parent camps.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can you please check and close?

**Comment by BrentAllsop** [comment]
Yes, looking nice so closing this.
