### ISSUE TITLE
Messaging when user has not yet created a nick name.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#642]
When a user first attempts to contribute, he may have not yet created a nick name.
They see this and might not know what to do:
![image](https://user-images.githubusercontent.com/6559312/93532329-0bb4c780-f8fe-11ea-81d9-7eb04f75f8fe.png)

If there are no nick names yet, we should add the message, before the "Add New Nick Name" link:
"You have not yet added a nick name.  A public or private nick name must be added then selected here when contributing."

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.I can see the note now.
But there are some other places also where user see "Add New Nick Name" link when there are no nick names yet.
Do we need to add this note at all those places?
@BrentAllsop  Please confirm

**Comment by BrentAllsop** [comment]
Yes, it needs to be every place, editing statement, camp, topic, and contributing to forums...
Anyplace that requires them to select a nick name.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thanks for the confirmation. I am removing the fixed and ready to test tag.
@gautamv16 Please check and update

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I can see the note now but  I found font-size mismatch on Create New Topic page/Forum page .Please refer attached screenshot 

It is fine ? @BrentAllsop Please confirm
![image](https://user-images.githubusercontent.com/40416610/94373073-7a74fa80-0120-11eb-9e19-268462e9ffc0.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I found the note on Nick Names page.I think we don't require this note here, we require on only those places where we are contributing
Please refer attached screenshot
@BrentAllsop Please confirm

![image](https://user-images.githubusercontent.com/40416610/94460606-9aff8c00-01d6-11eb-9387-70c9894a8ef1.png)

**Comment by BrentAllsop** [comment]
I'm thinking it would be nice to have something like this, here.
It just shouldn't include the "selected here" as that isn't here.
How about:
"Note: You have not yet added a nick name.  A public or private nick name must be used whenever contributing."

**Comment by rupalichavan9860** [comment]
Yes "selected here"  is somewhat confusing. 
"Note: You have not yet added a nick name. A public or private nick name must be used whenever contributing." looks good

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Looks good now
@BrentAllsop Can you please check and close if fine for you

**Comment by BrentAllsop** [comment]
Looks nice, so closing.
