### ISSUE TITLE
Wrong edit summary for proposed change.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#643]
I proposed a change to a camp record.
I only changed the parent and provided an "Edit Summary:" value.
Then e-mail was sent out, giving the wrong "Edit Summary"
The email had the edit summary from the previous, in this case also the first, record, not the new one I submitted.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine now.
@BrentAllsop Can you please check and close if fine for you?

**Comment by BrentAllsop** [comment]
Yes, working nicely, so closing.
