### ISSUE TITLE
Minor : Design issues

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#647]
I found minor design issues on topic agreement page 
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/94262505-38e22500-ff51-11ea-828e-e8704aa632bb.png)

**Comment by BrentAllsop** [comment]
Good catch.

**Comment by gautamv16** [comment]
@rupalichavan9860 its fixed pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Looks good now so closing this issue
