### ISSUE TITLE
Support removal is not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#651]
I have created new topic yesterday (10/5/2020, 4:21:16 PM) and created camp "1" and I was the only supporter .
After some time I removed my support from camp and I got support removed email and also I got following mail,

"Hi Brent Allsop,

Rupali C has just delegated their support to you in this camp: test emails links url / 1"

Even if Brent Allsop is not the supporter of the camp.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/95207694-c2251180-0805-11eb-9d5a-67e425c23615.png)

Also now I am trying to add support for the same camp so I can see following warning 
"Warning! You have already delegated your support for this camp to user Brent Allsop. If you continue your delegated support will be removed."

![image](https://user-images.githubusercontent.com/40416610/95207932-0fa17e80-0806-11eb-837e-97d739e386e2.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I just done more testing on this and found that this is happening only if the camp name is starting with number like camp names "1","123","1test"

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested .Still facing issues
When user supporting sub camp and trying to support agreement camp, user is getting 2 emails one is removed support from sub camp and added support to agreement camp 
But now the issue is in both mails it is displaying same camp name ( removed support from agreement camp and added support to agreement camp )

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Still facing issue when trying to support camp with no support and can see following warning

![image](https://user-images.githubusercontent.com/40416610/96140843-014a1580-0f1e-11eb-81af-d7f9d1ab6d0b.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. It is working for me now so closing this issue
