### ISSUE TITLE
Inappropriate "added support" email.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#652]
**Steps to reproduce:**

1. Add support to many camps (I supported 21)
2. Add support for an additional camp (Deepak Loomba), and move that camp higher in the list, before doing a submit (I moved it to something like 12)
3. Submit the new support, at the not last position in the list.
Expected behavior:
Only one e-mail should be sent out, indicating one new camp was now supported.
Actual behavior:
The expected email was sent, but also an additional email went out for the still last camp on the support list (Imants Baruss).

**Here is the list of my supporters after I experienced this:**
https://canonizer.com/user/supports/1?topicnum=81&campnum=5&namespace=13#camp_81_5

**I was adding support for Deepak Loomba.**

**I got this correct email, for that:**

Delivered-To: brent.allsop@canonizer.com
Received: by 2002:a17:906:1813:0:0:0:0 with SMTP id v19csp1410933eje;
        Thu, 8 Oct 2020 08:44:10 -0700 (PDT)
X-Google-Smtp-Source: ABdhPJxZcCjcAhyZ/kZle0OXTF9hATsxUScfW7FoMZ4kL8sJZXIFBdoCrl4Lr87/qMIV6H8+NU9s
X-Received: by 2002:a05:6402:293:: with SMTP id l19mr9814861edv.227.1602171850111;
        Thu, 08 Oct 2020 08:44:10 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1602171850; cv=none;
        d=google.com; s=arc-20160816;
        b=gW3CG1sQfiSch9oVrz0yUcFdtPtu5xo2PZexi6r7QIpH4zyUVuzlvVw/OOZldnOEC2
         D5nz4jU+mzuCz0rxnBvyzdn/VfBD5OsE91kSlvaamPy9UKqj/G+FGU+i+++kAEYF7YPF
         yIEVHTj25pnhO6LkKO6OYWdFZ+uU8/fHpuWnKHHm1UlzhA/4KbreP4hTbf5djsOg4RxQ
         XywEGSsHPWkhaf8aQ4IsGHU0Re3rk+J5fmexYKXFVn720EuWih6REeXlU66ts3YHZO+a
         i2dCJMbl4BXQ5RMC90IEriMtNPAohkGgIS+WDUcX00AXnE77RQNoNtoo5A+wfAi6Sdsj
         5m9g==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:mime-version:from:subject:date:message-id:dkim-signature;
        bh=jxVMo6e9Acsy3syBpGmC2dcleIgKde5yWXimbDJFR2U=;
        b=stZ5x8hSC3HKS3i5cXVtKUXpfGH91GA0yDVXw2CYvXjH7QCt6jv5rY++A8wejI9X6B
         RRWKY9vPXPR2os3qXzUX/347ryifDLwmgeFPDxqU7tmBsSckinGq7Ya9hgPbhZ3c1P2T
         Y/pE5wwIvytUI1fUwMLmKhIAH6FSBBF1iRgVgRpqcYeQpyIIEKiIU0LR7HKzhAYh2y3/
         SM2UvaB+tAwk/sK9V8MTvHw2Eb6XPmzl/9+LFzcUlyb6ylGlOJ74po4Nx7xqy++ToK8b
         kCrAeANPzu4XdwEbamdBJ6dm45FLuIZ3rI8zfA6T5TBH4KBAgqN541yIVf+E883CKxGF
         KrDw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@sendgrid.net header.s=smtpapi header.b=L2zpQhJR;
       spf=pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.167.116 as permitted sender) smtp.mailfrom="bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net"
Return-Path: <bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net>
Received: from wrqvxttq.outbound-mail.sendgrid.net (wrqvxttq.outbound-mail.sendgrid.net. [149.72.167.116])
        by mx.google.com with ESMTPS id bx11si4127473ejb.319.2020.10.08.08.44.09
        for <brent.allsop@canonizer.com>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Thu, 08 Oct 2020 08:44:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.167.116 as permitted sender) client-ip=149.72.167.116;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@sendgrid.net header.s=smtpapi header.b=L2zpQhJR;
       spf=pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.167.116 as permitted sender) smtp.mailfrom="bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net"
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sendgrid.net; h=subject:from:mime-version:to:content-type; s=smtpapi; bh=jxVMo6e9Acsy3syBpGmC2dcleIgKde5yWXimbDJFR2U=; b=L2zpQhJRcGv5V2UPP5yT8pDJeTxhqT3GsvErBIZn2wOzLdIJR+uVN/0PxTUL345GRSSI 0MQOowP+rPWHcV2NJ5zPzFPULcEeerFk2ZhYuewvydWDBnkbFECWcnR46TTL0b0RU0geWj UpvGt4/VgGvAkDUEDd5ikvDBSxWeTPe0c=
Received: by filterdrecv-p3las1-dcbfbb89c-hzdv9 with SMTP id filterdrecv-p3las1-dcbfbb89c-hzdv9-20-5F7F33C8-33
        2020-10-08 15:44:08.421381515 +0000 UTC m=+61683.473250215
Received: from canonizer.com (unknown) by geopod-ismtpd-4-0 (SG) with ESMTP id Bi3Zo3xlS56xFoD0dBu-8Q for <brent.allsop@canonizer.com>; Thu, 08 Oct 2020 15:44:08.252 +0000 (UTC)
Message-ID: <c049a685d4328b1c4b3e36649a94ceeb@canonizer.com>
Date: Thu, 08 Oct 2020 15:44:08 +0000 (UTC)
Subject: [canon]Brent_Allsop has added their support to Mind Experts / Deepak Loomba.
From: The Canonizer Team <canonizer@canonzier.com>
MIME-Version: 1.0
X-SG-EID: yPSDj0K8sADzb1/88WGchPYMwVfPmKsJRHMs5lWTTMy6+0IO10QlYs7EAcfu64oOfjFqlEfdoc04WRZ8ke2R1DY/+BtDob4wc6WrLYITPCScWKgkR8DiPiEgxNpYrc9Zs+X5S7TL4xDILJqX1OJ2C8ZbnXME+OiEhJEXGRmKk39vkveWjhKd/7bhQA7YlToGTAYiYXioSwS08s3VX6B/NI6a77XxjBqB+ex3ASPvDwoQ9PERZRAN3AaxHIuMBsZjPI/lxsHMO/RGoSoPZSw1JA==
To: brent.allsop@canonizer.com
X-Entity-ID: 7ibV8VhmqKctJ1aR9DLlGA==
Content-Type: multipart/alternative; boundary="_=_swift_v4_1602171848_fa54fe96dc5d275d978677f7ea2d01ec_=_"

--_=_swift_v4_1602171848_fa54fe96dc5d275d978677f7ea2d01ec_=_
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

[Canonizer](https://u6507102.ct.sendgrid.net/ls/click?upn=3DxJnxDo6LDHvU2dC=
-2FWOo-2BA5ieInWhZtblPnq8Ag3arGE-3DyITq_4L9rlx8T0V8eG4q6DdZ-2BcE1AC0VtMxm8d=
gXrVhxxaSiK97N-2FHJ1lqOGlmH35Q4Vx-2FzUkTXEgRWYxub4JwfvI5qgfV4sQBFofNSZFSvsy=
eZcveSxRZhmUN9nOrhkALEp9RpmHN4VKLR6N9QMUVtVMkMAScQ-2FtzoteGHuzv2a2Z8XK7dJ1g=
NNU7ak0-2BP9Rx6q1TudPjioCYUw-2FX2ba8XrkJiPdG7GGe-2Bcbv7Oo7ds4szI-3D

Hi Brent Allsop,
=20
  =09Brent_Allsop has just added their support to this camp: Mind Experts /=
 Deepak Loomba
=20
=20

=20
=09You are receiving this e-mail because:
=09=09
=09=09=09=09=09=09=09=09=09 =09You are directly supporting Deepak Loomba
=09=09=09 =09=09=09
=09=09=09
=09=09=09
=09=09
   Note:
=09
=09 We request that all direct supporters of a camp continue to receive not=
ifications and take responsibility for the camp. You can avoid being notifi=
ed by delegating your support to someone else.
=09

Click here to See this topic.: https://u6507102.ct.sendgrid.net/ls/click?up=
n=3DxJnxDo6LDHvU2dC-2FWOo-2BA7d6yyRJ070c9RfIkGKToTrCt-2FE30X9uZOfji-2FQNvzE=
3554L_4L9rlx8T0V8eG4q6DdZ-2BcE1AC0VtMxm8dgXrVhxxaSiK97N-2FHJ1lqOGlmH35Q4Vx-=
2FzUkTXEgRWYxub4JwfvI5q0SPTBwnfSW7osxw6mowLeOWPyAXG6up4V-2BGgk73REQdggZBA9G=
OBwYKg-2FfUKtMtev8Aaun9HAxxO-2BlaeB2Gz1H4My3znA5MudWjtFri-2Bl1DanmbKi8NgT5D=
nUUt-2BI6NRgS-2BW8j8y0izeNPUGm8ZCE-3D

Sincerely,
The Canonizer Team

=A9 2020 Canonizer. All rights reserved.

**I also got this erroneous e-mail, I should not have received this one since I was already supporting  Imants Baruss so I didn't add new support**

Delivered-To: brent.allsop@canonizer.com
Received: by 2002:a17:906:1813:0:0:0:0 with SMTP id v19csp1414027eje;
        Thu, 8 Oct 2020 08:48:50 -0700 (PDT)
X-Google-Smtp-Source: ABdhPJwcZ6VPb2wk5zErIOtd79/Qo79P29q8lJBmGUnPbzpviy222stPEUZAgsdBntFRgSpd/qKI
X-Received: by 2002:a17:906:16c6:: with SMTP id t6mr9071420ejd.453.1602172130278;
        Thu, 08 Oct 2020 08:48:50 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1602172130; cv=none;
        d=google.com; s=arc-20160816;
        b=sGbqMzlfwcvGOebN4u4jyvuZ/kIbI5IYFbX8O/YWdKQera2cZdaW4RltI5xTUPKHIB
         OsosCLB1PkBlJS2gvnEByuPBAwA6ivpEK7fg0bZPS2sUm9ieti6UuUi5sVSXcKxxUHaC
         v7ZrxRbddV+33v3sK0F1a5189WvFOmQJaTem5JVjsXXyxc8lBPU4kEQ1RhwonUnTpFZm
         FLqbZND9GxSYqGJeT3mpRzREyFUFPhPDZiS/Zg+4Y0G4Yo9qsOB0PC04Cg+LonQpN8KX
         dPcDmMeUHyQSDa3opm51QWOtz2bpgGxLqdgbxTwbYbrf5Cj0SWgCikniFoEs66GA3c0x
         h27Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:mime-version:from:subject:date:message-id:dkim-signature;
        bh=N7v2MeH8WRfYZrTuepm4T8yh1SWXhhm4Vzw164Em1Iw=;
        b=k9hT3eXszHGbg2jwWUA22Aq6PGa1v3KkQWcc7ecHMeFQsBm2hRPzWp6OYIbYOcVcGL
         OTWQjX0kd0EtioXcGp008rGSs4tM9UJMtjNqgmwz+o+ZHH1V6HUaboyZl6EgWont8FdA
         C+0z70HJ+OZcBaMd6KgckM3ZWRkejyUxNx3lrtKJQSzyARCmCUzfTYc4B01qEcpJkq0J
         ZRr6HcWEsm/XAOK8DM1OuwdLy2VDbrVDq1yP8+jgTty3obgLUwbiGBnif6OUUWsRXY85
         2Oo8ZCuAME0sCBRwjP0EnPLtl4xwNt8N9SNX0tGx4hu3sTvXWGRZPdMZe0cHY54GRUfV
         Zwmg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@sendgrid.net header.s=smtpapi header.b=or+W67+A;
       spf=pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.168.13 as permitted sender) smtp.mailfrom="bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net"
Return-Path: <bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net>
Received: from wrqvxvhd.outbound-mail.sendgrid.net (wrqvxvhd.outbound-mail.sendgrid.net. [149.72.168.13])
        by mx.google.com with ESMTPS id v10si3903639edw.363.2020.10.08.08.48.49
        for <brent.allsop@canonizer.com>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Thu, 08 Oct 2020 08:48:50 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.168.13 as permitted sender) client-ip=149.72.168.13;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@sendgrid.net header.s=smtpapi header.b=or+W67+A;
       spf=pass (google.com: domain of bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net designates 149.72.168.13 as permitted sender) smtp.mailfrom="bounces+6507102-5d45-brent.allsop=canonizer.com@sendgrid.net"
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sendgrid.net; h=subject:from:mime-version:to:content-type; s=smtpapi; bh=N7v2MeH8WRfYZrTuepm4T8yh1SWXhhm4Vzw164Em1Iw=; b=or+W67+A0o0rgPlE+DIbWEXvGYke9fnuvfLa7LX2cevHsfRx9kYy+wl128RGLYkcPXC3 EE/+D51Os2z0Ta/+PiyE3RDFrDuxhhy7zswHemWZiANWtdtL82LeS+UlF6FxN637epzw/I qu8kR5PtqpggevnuWF98qEAeladqBOBpQ=
Received: by filterdrecv-p3las1-dcbfbb89c-97wlm with SMTP id filterdrecv-p3las1-dcbfbb89c-97wlm-19-5F7F34E0-5B
        2020-10-08 15:48:48.521454106 +0000 UTC m=+61969.488187486
Received: from canonizer.com (unknown) by ismtpd0100p1mdw1.sendgrid.net (SG) with ESMTP id DhphZMTyTnGSQXFBaptZcQ for <brent.allsop@canonizer.com>; Thu, 08 Oct 2020 15:48:48.418 +0000 (UTC)
Message-ID: <b45fcea59acbdd257889a1b4974160ac@canonizer.com>
Date: Thu, 08 Oct 2020 15:48:48 +0000 (UTC)
Subject: [canon]Brent_Allsop has added their support to Mind Experts / Imants Baruss.
From: The Canonizer Team <canonizer@canonzier.com>
MIME-Version: 1.0
X-SG-EID: yPSDj0K8sADzb1/88WGchPYMwVfPmKsJRHMs5lWTTMy6+0IO10QlYs7EAcfu64oOfjFqlEfdoc04WRZ8ke2R1HETnpQhX/hos+mSfui4NrffAhCE0jXwS0NQy1/VPRl4osxnevDWyTMOATB3HH02LyQ+ti6kC1VSbI2vFHxLnCEzd8GtWMNDXFHU+ayPK/uSJjng34h5dRDQ7YghZxOrNwEuodpMudJ5SbTb/QYF2Le8czJB7tESmy/4TfhGVtDbP55nUqqj+1j3RhcBJrVIWQ==
To: brent.allsop@canonizer.com
X-Entity-ID: 7ibV8VhmqKctJ1aR9DLlGA==
Content-Type: multipart/alternative; boundary="_=_swift_v4_1602172128_c4c2e20dd651fb97274f5f754af0fd21_=_"

--_=_swift_v4_1602172128_c4c2e20dd651fb97274f5f754af0fd21_=_
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

[Canonizer](https://u6507102.ct.sendgrid.net/ls/click?upn=3DxJnxDo6LDHvU2dC=
-2FWOo-2BA5ieInWhZtblPnq8Ag3arGE-3D-jn4_4L9rlx8T0V8eG4q6DdZ-2BcE1AC0VtMxm8d=
gXrVhxxaSgGaAYpbJ-2BtAFG91-2Fb1vLyuTPh59ECaHDPbEB3U1380tnSJEzf4HrUig-2BFoZ4=
jFOCCgIO9G-2F5gLKa2ZMTklAcFC-2FvnvzHwBLMaVYSE9PZ2hnO1pkfc0BBx61-2Fzx9dCB00b=
OQ2Rxvg0KLt2Dm7RDJTrf66h6KsIuiYcrzMcA3IJ8l-2FYvRju4GpEcAn0KPvfskKA-3D

Hi Brent Allsop,
=20
  =09Brent_Allsop has just added their support to this camp: Mind Experts /=
 Imants Baruss
=20
=20

=20
=09You are receiving this e-mail because:
=09=09
=09=09=09=09=09=09=09=09=09 =09You are directly supporting Imants Baruss
=09=09=09 =09=09=09
=09=09=09
=09=09=09
=09=09
   Note:
=09
=09 We request that all direct supporters of a camp continue to receive not=
ifications and take responsibility for the camp. You can avoid being notifi=
ed by delegating your support to someone else.
=09

Click here to See this topic.: https://u6507102.ct.sendgrid.net/ls/click?up=
n=3DxJnxDo6LDHvU2dC-2FWOo-2BA7d6yyRJ070c9RfIkGKToTr0aE-2BkBkbEY2GVd6PXPUo7-=
-QO_4L9rlx8T0V8eG4q6DdZ-2BcE1AC0VtMxm8dgXrVhxxaSgGaAYpbJ-2BtAFG91-2Fb1vLyuT=
Ph59ECaHDPbEB3U1380tocGEES3SC4SSefwtVJIR5bvqSAM-2FVVqW77fEkzBwEAVU5yXTj5wXt=
WwccYwNi7AhuFdmGFZfQ9sF7w1Qr0Jojd5MQL5-2F198oTcDJCIWiWs9OqIS1XUasML7I7WpDST=
3q-2B5XoyEnq2ui5JYnFIFsZlc-3D

Sincerely,
The Canonizer Team

=A9 2020 Canonizer. All rights reserved.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop Tested .
On live I am not getting Inappropriate "added support" email but I am getting Inappropriate "removed support" emails for other camps .This will get fixed on 20th release because it is working fine on staging.
But we need to keep this open as we still have issue on live

**Comment by BrentAllsop** [comment]
Yes, I noticed getting inappropriate "removed support", even though the support for that camp didn't change, I only added another supporting camp after that camp support that didn't change.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and working fine for me on new secure server .
@BrentAllsop Can you please check and close if working for you?

**Comment by BrentAllsop** [comment]
@rupalichavan9860 
Yes, I tested this and except for the [new issue](https://github.com/the-canonizer/canonizer.2.0/issues/742) this is working fine.
So I am closing this so we can get the 20th release out.
