### ISSUE TITLE
Delegate support functionality is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#654]
Environment : Staging
When user trying to delegate their support to someone , instead of delegated supporter user become direct supporter of the camp and also user is not getting delegated support mail

**Comment by gautamv16** [comment]
@rupalichavan9860 please Test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Following topic name/camp name link  in delegated email is redirecting to wrong URL. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/96138882-dc54a300-0f1b-11eb-8cdf-ba58bd46bd1e.png)

![image](https://user-images.githubusercontent.com/40416610/96138808-c810a600-0f1b-11eb-9c0a-3e5ef6c20b4d.png)

Also facing one more issue on this
Firstly I delegated my support to someone else on agreement camp and then now trying to support sub camp directly and getting following mails
1. Removed support from agreement camp(correct mail)

**2. Getting following mail instead of added support to sub camp(Incorrect email)**

![image](https://user-images.githubusercontent.com/40416610/96139883-eb882080-0f1c-11eb-90a8-ef4e98187df1.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working now so closing this issue
