### ISSUE TITLE
Namespace structure cleanup.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#656]
There are major issues with these name spaces.

/Occupy Wall Street/canonizer/            -> /organizations/canonizer/
/organizations/help/                             -> /organizations/canonizer/help/
/Occupy Wall Street/mta/                     -> /organizations/mta/
/Occupy Wall Street/TV07/                   -> /organizations/TV07/
/Occupy Wall Street/wta/                      -> /organizations/wta/
/crypto_currency/Jesperson_Oscar_F/  -> /family/Jesperson_Oscar_F/
/crypto_currency Ethereum/                 -> /crypto_currency/Ethereum/

All records, through all time, need to be verified to have these changes.
And there may be other issues like this I haven't noticed.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified by Brent and me. So closing this issue
