### ISSUE TITLE
Page crash on staging

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#657]
I am getting page crash while supporting sub camp. Click on Submit or Cancel button on supported camps page.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/97190410-ac36bb00-17cb-11eb-8156-07a57ec90343.png)

**Comment by rupalichavan9860** [comment]
I am facing this issue for fresh topics.
1. Create 1 new topic
2. Create new camp 
3. Click on Directly Join or Manage Support
4. Click on Submit or Cancel button

Support is getting added and user is getting  support added mail also but can see above page crash on following places
1. On Submit button click
2. On Cancel button click
3. Click on links from support added mail 
4. Go back to agreement page and click on newly created sub camp

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine so closing this issue
