### ISSUE TITLE
Create a "Camp URL Format" Help Page.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#66]
Included in this issue is adding the new ability to specify a canonizer algorithm to a camp URL.

We need to document the format of the camp URL.

Create a new "Camp URL Format" topic help page for this.
Add a link to this new topic in the main help page list of other help pages:
http://production.canonizer.com/topic/132-Help/1

Things you should be able to add to a camp URL:
* Topic num
* Camp num (optional, default to 1/root camp)
* camp description (ignored, used for search engine optimization)
* As_of value. (optional, default to current or user selected session value)
* Canonizer algorithm indicator (optional, default "1 person 1 vote" or user selected session value)

**Comment by gautamv16** [comment]
@BrentAllsop  here is the sample url and values.

Url : www.production.canonizer.com/topic/{topic_num}-{topic_name}/{camp_num}?filter=0.000&asof={bydate,review,default}&asofdate={date('Y/m/d')}&canonizer={key_value_from following following algorithm array }

'blind_popularity'=>'One Person One Vote',
            'mind_experts'=>'Mind Experts',
            'computer_science_experts'=>'Computer Science Experts',
            'PhD'=>'Ph.D.',
            'christian'=>'Christian',
            'secular'=>'Secular / Non Religious',
            'mormon'=>'Mormon',
            'uu'=>'Universal Unitarian',
            'atheist'=>'Atheist',
            'transhumanist'=>'Transhumanist'

Based on this detail now you can create the Help topic.

Let me know anything else you need now. 

Canonizer algorithm value from url is now used for canonizer algorithm selection.

Please test whole flow for this.

**Comment by gautamv16** [comment]
@BrentAllsop please check this.

**Comment by CanonizerJim** [comment]
I understand this, and I'll close this as soon as I write up the help page.

**Comment by CanonizerJim** [comment]
This page is now online.
