### ISSUE TITLE
Critical must fix now privacy breach issue.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#660]
Users are reporting they cannot set their e-mail address to private.
I have been able to reproduce this problem.
This is a serious breach of privacy that must be fixed immediately.

Brent Allsop

**Comment by gautamv16** [comment]
@BrentAllsop Its deployed to production. please check and close

**Comment by BrentAllsop** [comment]
Yep, working wonderfully in production, so closing this issue.
Thanks!
