### ISSUE TITLE
don't send a "new supporter" email, if the user just changes the order of the support.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#661]
If the user only changes the order of his support  (i.e. moves it from 5th choice to 1st choice, and all the other related re-orderings) don't send email.
Only send an email, for a new supporter of a camp.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop This is working fine on staging but it is having one issue 
User can change support order of camp, drag & drop the camp box on their choice position from User->Account settings->Supported camps but user is not able to change the camp order from Directly Join or Manage support

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. User can change the camp order now but after this fix found another issue, User can drag and drop only text also anywhere on the page which looks messy on the page please refer attached screenshot


![image](https://user-images.githubusercontent.com/40416610/109614967-55663700-7b59-11eb-8ce5-548b9d42b137.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Layout issue is working fine now.
@BrentAllsop Can you please check and close if fine for you?

**Comment by rupalichavan9860** [comment]
@gautamv16 Change the order of the support is not working properly. I have create fresh topic and created 4 sub camps 
1. Test camp 1
2. Test camp 2
3. Test camp 3 
4. Test camp
and moved Test camp to first position while supporting but now I can see order of supports as below ,

![image](https://user-images.githubusercontent.com/40416610/111996978-904c0100-8b40-11eb-9639-70581246f2bd.png)

![image](https://user-images.githubusercontent.com/40416610/111997043-a48ffe00-8b40-11eb-97bc-ad9fc4cf30ce.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. still facing the issue .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/112961966-81c6a080-9163-11eb-801e-07b17493d75f.png)

after supporting newly created camp (which moved to position 1)
![image](https://user-images.githubusercontent.com/40416610/112962093-a15dc900-9163-11eb-8286-17bae1cff346.png)

![image](https://user-images.githubusercontent.com/40416610/112962187-ba667a00-9163-11eb-8e47-ace1a9ab2078.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Working fine for me so closing this issue
