### ISSUE TITLE
Social Login : Facebook page crash 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#664]
I just created new facebook account and trying to login to canonizer using facebook ,I am getting following Error
Unable to log in: There is a 60-minute delay before new accounts can log in to any applications. Please try again in an hour.

![image](https://user-images.githubusercontent.com/40416610/103002061-3f823780-4554-11eb-8fae-f8e8b9aafc53.png)

When I click on Ok I am getting page following page crash
 
![image](https://user-images.githubusercontent.com/40416610/103002042-34c7a280-4554-11eb-8249-a5428065ffc1.png)

Expected Result :
It should display some error message/warning instead of page crash

**Comment by gautamv16** [comment]
@rupalichavan9860 I think as we have discussed in the meeting this is only case if you create new FB account and it is not on our side . I Think we can close this issue
