### ISSUE TITLE
Support camp functionality is not working properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#669]
Issue 1 : 
Steps to reproduce : 
1. Login to https://staging.canonizer.com/
2. Create any new topic/select any existing topic
3. Try to support agreement camp if user is supporting sub camp 

Expected Result : User's support should be removed from the sub camp and should see their support under agreement camp

Actual Result : As of now I can see user's support for both parent camp and sub camp

Issue 2 : 
User is able to support any parent camp multiple times .Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/105848628-44c81b80-6005-11eb-8457-c7b378678f69.png)

Supported camps screenshot
![image](https://user-images.githubusercontent.com/40416610/105848694-632e1700-6005-11eb-8130-f0c6c8f83a4b.png)

**Comment by BrentAllsop** [comment]
Good catch.
Yes, here is another example of problems, where I attempted to support Qualia are Material Qualities.
The only sub camps to "Material Qualities" were "Molecular Materialism.
![image](https://user-images.githubusercontent.com/6559312/105916215-d4fa6680-5fed-11eb-92c7-2275191112b1.png)

Also the new supported camp numbering is initially backwards.  The deleted ones should have their old numbers, and the supported camps should be listed in their supporting order.  If you change their order, they get numbered correctly.

**Comment by BrentAllsop** [comment]
Good catch.
Yes, here is another example of problems, where I attempted to support Qualia are Material Qualities.
The only supported child camps to "Material Qualities" were "Molecular Materialism" and "Orch OR".  None of the others should be in the will delete list.
![image](https://user-images.githubusercontent.com/6559312/105916215-d4fa6680-5fed-11eb-92c7-2275191112b1.png)

Also the new supported camp numbering is initially backwards.  The to be deleted ones should have their old numbers, and the supported camps should be listed in their supporting order.  If you change their order, they get numbered correctly.

**Comment by BrentAllsop** [comment]
And can we find a way to go back to the camp we came from (the one newly added to the list) if we cancel, not to the support page.

**Comment by rupalichavan9860** [comment]
Delegated support functionality is also not working. User is able to delegate their support to all the other supporters of the same camp.
According to functionality delegated support should be removed from user 1 and added to user 2 .as of now I can see user is able to delegate their support to both User 1 and user 2 for the same camp
Please check following screenshot

![image](https://user-images.githubusercontent.com/40416610/105999232-73acc300-60d3-11eb-8759-a574538fac29.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I just created new topic to test this fix and created new camp using same user(user1).user 1 is now supporter of newly camp .
Now I am trying to support this new camp using another user and getting following page crash

![image](https://user-images.githubusercontent.com/40416610/107174418-27755300-69f0-11eb-8d21-75e033175a3f.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and it looks perfect now but user should not receive the warning in following scenario.

User1 is trying to support the camp in which he/she is already delegating their support to User2.And displaying following warning 
"Warning! You are already supporting this camp. You can't submit support again."
As per functionality User1 can directly support to the camp So I think it should display only second warning. Highlighted warning is not required. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/107944572-55d8cc80-6fb4-11eb-8481-c3e2fbdde419.png)

Also User1(delegated supporter) is not able to join camp directly. Can see only cancel button

**Comment by rupalichavan9860** [comment]
@gautamv16 I am facing one more issue in this. I have created fresh topic and created 3 camps "Test camp 1", "Test camp 2", "Test camp 3" and same user is supporting all 3 camps .
Now using sane user I am trying to support Agreement camp and I can see camp names multiple times in list.Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/108169693-0e228400-711f-11eb-813c-b8f38a7410f2.png)

Supported camps page screenshot : 

![image](https://user-images.githubusercontent.com/40416610/108169889-5641a680-711f-11eb-849a-636013ac5150.png)

Also getting multiple removed mails

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash on "Directly Join or Manage Support" button click when user is not a supporter of a camp. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/111317299-09071500-868a-11eb-992c-43a603e11ad5.png)

**Comment by rupalichavan9860** [comment]
Also getting page crash on Account Settings->Supported camps
Click on "Supported Camps" sub tab. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/111318453-1670cf00-868b-11eb-9ffc-f2458d3e6960.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 page crash on "Directly Join or Manage Support" button click is fixed but still getting page crash on Account Settings->Supported camps 
Also getting page crash on "Directly Join or Manage Support" >Cancel button click(which is support page only).Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/111896104-2dbe0c80-8a3d-11eb-9a4d-9785ee4558a7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Still I can't see supported camps page , can see code instead .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/111912120-3985ef00-8a8e-11eb-8582-63fdfa78822f.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test again

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Page crash issue is fixed now. Only issue remaining in this is user supports page is still displaying duplicate camp names. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/111913850-b1a3e300-8a95-11eb-8f01-8ef23a021050.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed. pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Above issue is fixed but all supported camps are not listing in email. Please refer screenshot
User "Rupali C" is supporting all the below camps but while supporting new camp ,it is listing only that camp name 
![image](https://user-images.githubusercontent.com/40416610/112962959-8cce0080-9164-11eb-999f-70c52c21a68e.png)

Please check below screenshot(Listing only current camp name)

![image](https://user-images.githubusercontent.com/40416610/112963041-9bb4b300-9164-11eb-8af9-cf05e03f6e09.png)

**Comment by rupalichavan9860** [comment]
Delegated supporter is not able to join the camp directly. Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/114151718-091dcc00-993b-11eb-930f-ce1658f7423c.png)

![image](https://user-images.githubusercontent.com/40416610/114151878-3b2f2e00-993b-11eb-80b8-f4edee82e497.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Delegated supporter can see and able to click the "Submit" button to support camp directly , but when click on "Submit" button nothing is changed.
User can see the "Warning! You have already delegated your support for this camp to user Rupali Chavan. If you continue your delegated support will be removed." this warning but still Delegated supporter remains delegated supporter for that camp instead of direct supporter

**Comment by gautamv16** [comment]
@rupalichavan9860 Pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I am getting page crash again
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Select any camp
5. Apply as of date date filter as any previous date
6. click on topic created date then camp created date
7. Click on "Directly Join or Manage Support" button
8. Observe result

Actual Result :  
I am getting following screenshot 

![image](https://user-images.githubusercontent.com/40416610/115175439-9a820080-a0e8-11eb-930e-fcedf28aff92.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . I have created fresh topic and camp. Topic submitter trying to support sub camp but support is not getting added
I am getting removed support mail from "Agreement" camp and added support mail to sub camp but can't see added support under list

**Comment by rupalichavan9860** [comment]
Checked for old topics/camps also user is getting support added and removed mails but can't see support under support tree

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine now so closing this issue
