### ISSUE TITLE
Add new "White Paper" link to the side bar on all pages.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#67]
Add this new link to the sidebar of all pages:

Canonizer Main
Browse
Create New Topic
Upload File
Help
White Paper  <-- new link to James Carroll's "Amplifying the Wisdom of the Crowd" pdf.
Blog

Also:
Change the links on the side bar, so the page you are on is green and is not a link, like the bread crumbs and camp outline links.

**Comment by gautamv16** [comment]
@BrentAllsop done please test with different test cases.

**Comment by BrentAllsop** [comment]
@gautamv16,
Not seeing any of this.
Don't see the "White Paper" link on any pages
This link to the white paper (from the current countdown page) still doesn't work:
https://canonizer.com/canonizer2.0/public/files/2012_amplifying_final.pdf

**Comment by gautamv16** [comment]
@BrentAllsop  Karun forget to push his code, i thought he did as we are using same account. So it was not updated thats why not showing.

Please test today, all this is done.

**Comment by BrentAllsop** [comment]
looking great now, closing...
