### ISSUE TITLE
ID links in the forums don't link to that identity.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#670]
![image](https://user-images.githubusercontent.com/6559312/105914958-5fda6180-5fec-11eb-8c40-73d2ae7facdd.png)

None of these "Africahead" ids, some of which are links, link to the ID.
They should all link to the same ID they would link to if this ID supported a camp.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Id's in blue color are redirecting to correct user's supported camp page but Id's in red color are redirecting to top of the same page . I checked the link on red color id's .Please check below screenshot

![image](https://user-images.githubusercontent.com/40416610/107945898-49557380-6fb6-11eb-9b79-27f554480970.png)

@BrentAllsop Red color id's should also redirect to supported camp page right? Please confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. All ID's are redirecting to their respective user supports page now so closing this issue
