### ISSUE TITLE
Add reply on individual replies in Canonizer forums

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#672]

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop Can you provide more clarification on this:

- How will the user reply to the individual replies in Canonizer?
- What will be the user interface and experience for adding a reply?
- How will the UI look like when a reply has been added?
- Can there be multiple replies to a single individual reply?
- Can that reply be deleted?

Let us know.

**Comment by BrentAllsop** [comment]
This one is a low priority.  we may not need this.  If we do decide to implement this, we'll need to specify the details, like how many nested replies will fit on screen, and answer the rest of Hamza's questions.  The UI/UX people can work on this.
