### ISSUE TITLE
Move reply textarea on thread to the top.

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#673]

**Comment by HamzaBinMansoor** [comment]
This has been completed.

**Comment by gautamv16** [comment]
Hey @HamzaBinMansoor it seems you have closed this ticket. This need to be tested by @rupalichavan9860 before closing. Please dont close any ticket from your end.

**Comment by rupalichavan9860** [comment]
@gautamv16 @HamzaBinMansoor Tested and verified
