### ISSUE TITLE
Account Settings->Profile->Address

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#674]
User is not able to update their address. It is displaying following error in console

 You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started Places API error: BillingNotEnabledMapError
https://developers.google.com/maps/documentation/javascript/error-messages#billing-not-enabled-map-error

Please refer following screenshot.

![image](https://user-images.githubusercontent.com/40416610/107147222-e428cf00-6972-11eb-9dca-5a89f61633bc.png)

**Comment by HamzaBinMansoor** [comment]
Is this a development issue? Seems like you just need to enable billing on the Google Cloud project.

**Comment by gautamv16** [comment]
@BrentAllsop we are using the apikey for address api of google for trial period which is over now, you need to enable billing in google account and share the api key , i will replace that and it will start working then

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.  Now user is able to update the address so closing this issue

**Comment by saniatg** [comment]
@rupalichavan9860 working fine now. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
