### ISSUE TITLE
javascript error on blog page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#678]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Click on Blog
4. Open developer tool
5. Scroll on blog page many times and observe console

Result : 
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/107368241-51209e00-6b06-11eb-9abb-546d7031c4b5.png)

**Comment by ashish76** [comment]
@gautamv16 I think the blog has a different code base (i.e. WordPress). To fix this issue I need access of the WordPress code.

**Comment by rupalichavan9860** [comment]
@gautamv16 @BrentAllsop This issue is exists on staging only. Do we need to fix this ?

**Comment by rupalichavan9860** [comment]
Seems like JQMIGRATE version issue 
Staging  : 
![image](https://user-images.githubusercontent.com/40416610/135411679-0638dad8-2070-431c-a744-f68d62235b64.png)

live : 
![image](https://user-images.githubusercontent.com/40416610/135411755-2b682f8a-0f3c-4fec-8b5c-d976486dd5d0.png)

**Comment by sunnyjindal** [comment]
@rupalichavan9860 @ashish76 This is not an error. This is just an information that some plugins installed may be relying on older jQuery functionality.

**Comment by rupalichavan9860** [comment]
Closing this
