### ISSUE TITLE
Yet another history issue.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#681]
The Mind Expert topic is getting the incorrect topic name in the URL:
https://canonizer.com/topic/81-Daniel-Dennett/1-Agreement

Note that in the history, the latest version of the topic has the name "Daniel Dennett" but this version has been objected to (red) so should not be live.
The correct (green) live name should be "Mind Experts"

![image](https://user-images.githubusercontent.com/6559312/107866401-b7226380-6e2d-11eb-813e-c80fb068744e.png)

There should only be one set of code that does this operation in all cases, so we don't have different versions of the code, all with different errors like this.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested now I can see live topic name in URL . Closing this
