### ISSUE TITLE
Topic and Camp name restrictions

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#683]
Can we give old camp name for new one. As of now I am getting error while creating new camp name as "The camp name has already been taken" 

Please refer following scenario

1. I have Created  camp with name "Test camp 1" on 1/26/2021, 6:21:27 PM
2. And Updated  "Test camp 1"  with new name "Test camp test updated" on  2/14/2021, 7:38:41 PM and "Test camp test updated" is live camp name
3. Now I am trying to create camp with name "Test camp 1" under same topic and I am getting error message "The camp name has already been taken" 

![image](https://user-images.githubusercontent.com/40416610/108224622-1c918f80-7161-11eb-95d2-96d13c37f241.png)

![image](https://user-images.githubusercontent.com/40416610/108224802-4e0a5b00-7161-11eb-94d9-ee22eddc539c.png)

@BrentAllsop Can you please check and confirm. Is this an issue ?

**Comment by rupalichavan9860** [comment]
As per discussion in meeting user should able to create new topic or update any existing topic , create new camp or update any existing camp with any name excluding live and not live topic/camp name throughout the application.

As of now it is restricting user for creating topic/camp name even if camp/topic names are old or objected
@BrentAllsop Please correct me if I am missing something

**Comment by sunilspr7** [comment]
I have added the conditions while creating / updating the topics or camps as mentioned in the ticket. I will be working on writing unit test cases for the same. Once unit test case is complete, I will push the code and will create the pull request.

**Comment by VikramTL** [comment]
As discussed over the call, we need to change the status "Not Live" to "In Review" under the history

![2021-09-21 19_25_02-Canonizer](https://user-images.githubusercontent.com/90752335/134184184-db2aa001-0dcd-4bed-90f4-481bf34fe8e2.png)

**Comment by BrentAllsop** [comment]
Thank you for adding that, @VikramTL

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 @BrentAllsop We have completed this ticket and below mentioned tasks are complete:
1. While creating a new topic or updating an existing topic, if a topic already exists under "Live" or "In Review" status, then it will show, "Topic already exists with this name" message.
2. While creating a new topic or updating an existing topic, if a topic does not exist under "Live" or "In Review" status but exists under "Objected" or "Old" status, then the topic will be successfully created or updated.
3. While creating a new camp or updating an existing camp, if a camp already exists under "Live" or "In Review" status, then it will show, "Camp already exists with this name" message.
4. While creating a new camp or updating an existing camp, if a camp does not exist under "Live" or "In Review" status but exists under "Objected" or "Old" status, then the camp will be successfully created or updated.
5. We have updated the text from "Not Live" to "In Review"

Pull request for this task is created.

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia Camp is getting created with not live camp name . Please refer below screenshot 
In have changed camp name "Test camp 2 v1" to "Test camp 2 v2" but able to create new camp with name "Test camp 2 v2"

![image](https://user-images.githubusercontent.com/40416610/134555115-d8672d87-fe36-4c34-ad65-4081c8c59b41.png)

![image](https://user-images.githubusercontent.com/40416610/134555176-115983b0-8973-4bd9-9959-59c6b15c6413.png)

**Comment by rupalichavan9860** [comment]
Same happening with topic also
Please refer attached screenshot 

Not live topic  : 
![image](https://user-images.githubusercontent.com/40416610/134555656-41088f1f-a6fa-4cda-af14-6ee138123ca3.png)


New topic with not live topic name : 
![image](https://user-images.githubusercontent.com/40416610/134555556-ef122a9e-1e35-4f24-8634-46f77adfeeea.png)

**Comment by nalwa** [comment]
@gautamv16  we have updated this task as per @rupalichavan9860  findings. we have also  created a PR for same please merge with staging.

**Comment by rupalichavan9860** [comment]
@nalwa Tested and verified.
