### ISSUE TITLE
Canonizer 2.0 Internal Search / Web Google Search 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#685]
Canonizer 2.0 Internal Search / Web Google Search  is missing on some mobile devices.
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Open developer tool
4. Click on Toggle Device Toolbar where we can see our site in responsive mode
5. Check for different resolutions 
6. Observe the result 

I can see Internal Search / Web Google Search  only when I select iPad Pro and not for others. Please refer attached screenshot for device iPhone 6/7/8

![image](https://user-images.githubusercontent.com/40416610/109159822-158b0280-779b-11eb-8dfa-d92aa10d36b6.png)

iPad Pro

![image](https://user-images.githubusercontent.com/40416610/109159978-410ded00-779b-11eb-80df-55b3413dbc58.png)

@BrentAllsop Is this an issue? Can you please confirm?

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test the search option for smaller devices will come under togglemenu

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. can see under toggle menu.
