### ISSUE TITLE
Multiple entries getting created on multiple click

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#687]
Multiple entries getting created while updating topic, statement and camp .
Try to update any topic, statement or camp and click on submit update button multiple times , multiple records getting created
please check below screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/109657786-e5bd6f80-7b8b-11eb-9805-563ca23e3f0f.png)

![image](https://user-images.githubusercontent.com/40416610/109657974-18676800-7b8c-11eb-851d-1e2289c7bb97.png)

![image](https://user-images.githubusercontent.com/40416610/109658262-654b3e80-7b8c-11eb-9c45-edc293948ff6.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Need to check and fix this issue on every button click throughout application

**Comment by BrentAllsop** [comment]
That will make the system much more robust, yes.

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested. Working fine for camp and statement but user is not able to update topic .

When user tries to submit update on topic the button "System Update" is getting disabled and new entry is not getting created on topic history page

**Comment by rupalichavan9860** [comment]
@gautamv16 Getting same issue on "Add News". Button "Create News" is getting disabled and New news is not getting created

**Comment by rupalichavan9860** [comment]
> @gautamv16 Retested. Working fine for camp and statement but user is not able to update topic .
> 
> When user tries to submit update on topic the button "System Update" is getting disabled and new entry is not getting created on topic history page

@gautamv16 Tested. This is not working yet

**Comment by rupalichavan9860** [comment]
@gautamv16 Getting page crash on "Manage/Edit This Topic"

![image](https://user-images.githubusercontent.com/40416610/127798407-16531dd1-d2e1-4e00-9c7b-0c2abe7b4b20.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 page crash issue is fixed . please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working now so closing this
