### ISSUE TITLE
Issues on Topic and camp change ageement

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#688]
Steps to reproduce :  
For topic change agreement : 
Topic : https://staging.canonizer.com/topic/291-Test-topic-2-march-2021-4/1-Agreement
1. I created topic name "Test topic 2 march 2021"  by user "1rupali1"
2. After that user "RC" submitted topic change  times
    1. Test topic 2 march 2021 1
    2. Test topic 2 march 2021 2
    3. Test topic 2 march 2021 3
    4. Test topic 2 march 2021 4
    5. Test topic 2 march 2021 5
    and committed changes
3. User "1rupali1" first objected 2 records then submitted agreement to one record (which became live )but still can see checkbox of "I agree with this topic  change" for remaining 2 records
4. Now when User "1ruali1" checked the "I agree with this topic change" for remaining 2 records that records becomes "old"
@BrentAllsop Is this working perfectly?

For topic change agreement : 
Topic : https://staging.canonizer.com/topic/291-Test-topic-2-march-2021-4/1-Agreement
Camp: Test camp 4 updated

1. I created camp name "Test camp 1"  by user "1rupali1"
2. After that user "RC" submitted topic change  times
    1. test camp 1 updated
    2. Test camp 2 updated
    3. Test camp 3 updated
    4. Test camp 4 updated
    and committed changes
3.User "1rupali1" first objected "Test camp 3 updated" camp then objected  "Test camp 2 updated" and submitted agreement to one camp name "Test camp 4 updated" (which became live )but still can see checkbox of "I agree with this topic  change" for camp name "test camp 1 updated"

Issue : when user click on the checkbox "I agree with this camp change" user can see success message "Success! Your agreement to camp submitted successfully" but in actual still user can see that record as not live and still see checkbox "I agree with this camp change

![image](https://user-images.githubusercontent.com/40416610/109693699-fda6ea80-7baf-11eb-9d0c-ae7a03e59d09.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Still facing issue for camp change

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. working fine now so closing this issue
