### ISSUE TITLE
Add google search to blog.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#69]
Currently, there is a word press search field on the top of the blog page that does not show up, when in the main page iframe.  We want to replace this with the same identical google search on the main page.

**Comment by BrentAllsop** [comment]
This should include changing the canonizer icon link to go to the main site (not the blog)
and remove the "back to site" link.

**Comment by gautamv16** [comment]
@BrentAllsop this is done..... added search feature.... with other chnages too.

**Comment by BrentAllsop** [comment]
oh, nice, I verified it is fixed...
closing this issue.
