### ISSUE TITLE
Camp About URL

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#695]
@BrentAllsop Can you please explain what "Camp About URL " field is? As of now "Camp About URL" field don't have any validations, I can enter unlimited characters in this field

![image](https://user-images.githubusercontent.com/40416610/110831751-903a3e80-82c0-11eb-8698-812b4784425d.png)

**Comment by BrentAllsop** [comment]
That was designed for people to add opinion to pages on the internet (the camp about url)
It should have a limit, probably something like 1024 characters.
It's not really used, anywhere, in the 2.0 system, that I know of.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thanks for the clarification. I will mark it as bug then 
@gautamv16 Please limit the character length for field "Camp About URL" to 1024 characters.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
