### ISSUE TITLE
Need to have the ability to delete news items.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#696]

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. After deleing the news, user is redirecting to incorrect topic name as we discussed in meeting. Please check

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine now so closing this issue
