### ISSUE TITLE
add things like "disallow /browse/*" to robots.txt

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#698]
It seems like the allow statements do nothing in robots.txt, as everything is allowed, like /user/supports/* whether allowed or not.
We do want to allow /user/supports/* (we should probably add that), but we don't want to allow /browse/*

It would be even better if we could disallow everything but what is in the allow section.
Everything else should be disallowed, including /browse/*

We should create a list of all pages, and review what is allowed, and what is not allowed.

**Comment by gautamv16** [comment]
@BrentAllsop Can you please provide the list of pages that we allow and which we are adding in disallow section?

**Comment by BrentAllsop** [comment]
We need to at least add "disallow /browse/*" to the robots.txt.
We should also do a review to see if there is anything else, like /browse/, which should also not be crawled by robots.

**Comment by gautamv16** [comment]
@BrentAllsop I have added /browse/ in disallow section in robots file

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
![image](https://user-images.githubusercontent.com/40416610/140921929-dd4476da-14ca-4773-8e29-7580f3713be5.png)

@BrentAllsop Can you please check and close the issue

**Comment by rupalichavan9860** [comment]
@gautamv16 Can you please do the same for staging also. robots.txt looks different on staging

![image](https://user-images.githubusercontent.com/40416610/140922196-4e32475e-8c8d-4bf5-858e-d755d0e44a8e.png)

**Comment by BrentAllsop** [comment]
Yes, this all looks correct to me.
On the live site, we specify only what we want the search engines to index for searches and disallow everything else.
All other dev, staging and testing systems need to tell all robots ("user-agent"s) to not index anything for search "Disallow: /"

**Comment by BrentAllsop** [comment]
Ooops, there are still more pages that need to be added to Disallow:

Disallow: /history/*
Disallow: /settings/*

@gautamv16   there are others, like the admin stuff, right?

**Comment by gautamv16** [comment]
@BrentAllsop admin also included.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified on staging

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested on production . I can't see below on live 
Disallow: /history/*
Disallow: /settings/*
Disallow: /admin/*

**Comment by rupalichavan9860** [comment]
Verified on production
