### ISSUE TITLE
2 Canonizer canonizer algorithms

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#699]
**Create 2 canonizer algorithms for canonizer governance.**

The two algorithms will be:
"Canonizer Shares"        the number of recognition shares held as of that date.
"Canonizer Canonizer"   the sqrt(shares)

Create a new DB record containing the following:
unique id       record key
unique id of nick name record.  (canonizer algorithm will look up record for nick name, based off this.)
*             We need to add an extra column to the user's nick name table that has the nick name unique id.
date                for as of values.
shares             Number of recognition shares held, as of date.

Create a Canonizer Admin tab so Kinnari can enter the shares held each month, starting with Jan 2021.
Have a drop down month selection box, starting with Jan 2021, to the current month.
When you select a month, it will display all record entries for that month.
There will be a delete and edit button for each row.
Each row will show the nick name, the shares, and the sqrt(shares)
There will be a button to create a new record for the selected month.  That date will be the first day of the selected month.

**Comment by BrentAllsop** [comment]
A few issues:
1. For the nick name field on the admin page add "(Enter nick name id)"
2. If you support more then one camp, the camp scores aren't showing correctly.
3. When creating new admin table entries, need an ability to specify the year.

**Comment by BrentAllsop** [comment]
There needs to be a new column in the user's "nick names" page, containing the value that must be used for the shares.
The user needs to be able to look up this number for the nick name they want the shares to be associated with, and send it to the accountant (kinnari) so she can enter the shares for that person.
The same terminology must match this column name, and the filed name on the shares management page.

**Comment by BrentAllsop** [comment]
I believe we resolved all the "need discussion" issues with a discussion in our last meeting.
So am removing these tabs, so we can get this closed.
It was indicated this is fixed, but isn't yet on staging, so could we get this on staging, then add the ready to test tag?

**Comment by rupalichavan9860** [comment]
@gautamv16 While testing Admin->shares I found some issue .  

![image](https://user-images.githubusercontent.com/40416610/120142990-f0c08400-c1fc-11eb-8439-804250f32997.png)

@BrentAllsop  can you please check and confirm

**Comment by rupalichavan9860** [comment]
@gautamv16 I am getting page crash .Please refer below scenario
Enter any alphabet in Share field and try to create/update share. Getting below page crash

![image](https://user-images.githubusercontent.com/40416610/120222529-b4714000-c25d-11eb-8556-23c2de8c12a5.png)

Due to this getting page crash on Admin>>"Shares" click

**Comment by gautamv16** [comment]
@rupalichavan9860 , it is fixed and i have implemented validations in admin side 
it will now not allow to enter dates before jan2021 and max date is current date.
Please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Incorrect date is displaying on list page please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/120935990-17158080-c723-11eb-90ff-834a3ef08c70.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 As discussed in call selected date is not getting saved/updated . Please fix and update

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test its fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 retested and validations are working fine for me. Just have one suggestion
For uniformity field names should be same

On admin side I can see field "Nick Name Id" which is "Unique Number" on Nick Names page. 
![image](https://user-images.githubusercontent.com/40416610/121798281-02654b00-cc43-11eb-9d98-79855ac165e4.png)

![image](https://user-images.githubusercontent.com/40416610/121798309-22950a00-cc43-11eb-89ba-908d5604300f.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 I found more issues on this
1. After selecting specific month from user don't have option to see all the shares . User needs to click on Shares link from left panel to see all the entries
2. After selecting specific month user is not able to delete the share(delete is not working) and also found JavaScript error on delete link click

![image](https://user-images.githubusercontent.com/40416610/121817810-32433b80-cca1-11eb-8409-1beeae336f09.png)

**Comment by gautamv16** [comment]
> @gautamv16 I found more issues on this
> 
> 1. After selecting specific month from user don't have option to see all the shares . User needs to click on Shares link from left panel to see all the entries
> 2. After selecting specific month user is not able to delete the share(delete is not working) and also found JavaScript error on delete link click
> 
> ![image](https://user-images.githubusercontent.com/40416610/121817810-32433b80-cca1-11eb-8409-1beeae336f09.png)

It is fixed and ready for test

**Comment by gautamv16** [comment]
> @gautamv16 retested and validations are working fine for me. Just have one suggestion
> For uniformity field names should be same
> 
> On admin side I can see field "Nick Name Id" which is "Unique Number" on Nick Names page.
> ![image](https://user-images.githubusercontent.com/40416610/121798281-02654b00-cc43-11eb-9d98-79855ac165e4.png)
> 
> ![image](https://user-images.githubusercontent.com/40416610/121798309-22950a00-cc43-11eb-89ba-908d5604300f.png)

It is displayed as because it was asked to show as unique number, so wont we changing it

**Comment by rupalichavan9860** [comment]
@gautamv16 retested and verified. Working good now so closing this
