### ISSUE TITLE
Canonizer 2.0 Topic, Camp and Camp Text History Pages

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#7]
1. Ability to See all the versions of topics, camps, and camp text on their history pages.
2. History pages are in a sorted manner.
3. The Version must be shown as Yellow if it is not yet live.
4. The Version must be shown as Green if it is live.
5. The Version must be shown as Red if someone objected it.
6. All remaining old version will be shown in blue.
7. It should display the **submitted** Date.
8. It should display the **Go Live** Date.
9. It should display the **Submitter** Nickname.
10. It should display the **Objector** Nickname (if any).

**Comment by gautamv16** [comment]
This is done.
