### ISSUE TITLE
Modified e-mail for modifications and objections.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#70]
I modified the text for these two standard e-mails:
To Direct supporters when change proposed.
Submitter is notified if anyone objects to his submitted change.

See the modified e-mail in this google doc:
https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit

Be sure when we have <topic | camp | statement>, the appropriate one is included in the text.

**Comment by gautamv16** [comment]
@BrentAllsop for statement what text needs to be put as we have only statement value available nothing else.

**Comment by gautamv16** [comment]
@BrentAllsop please test this... @kinari can verify this as she will receive all emails on staging.

**Comment by BrentAllsop** [comment]
@gautamv16 and @kinari,

I tried to modify this camp record:
https://staging.canonizer.com/topic/88/20
When I hit submit on the record edit page, I got a fatal error of undefined variable topic.
But it looks like the modification was submitted, as the yellow record showed up in the history page.
Kinari, could you let us know if you received an e-mail for this?  there are 3 direct supporters of this camp that should receive e-mail.

On the history page of that camp, I then pressed the object button but this just went to the camp record edit page.

**Comment by kinari** [comment]
Sorry guys i think you misspelled.. @kinnari good luck 🤞

**Comment by BrentAllsop** [comment]
Sorry, that was me, I know I sometimes do that, and am working on it.
Thanks

**Comment by gautamv16** [comment]
@BrentAllsop undefined erroe solved. 

And for objection you must have to go for edit page and when you click on object there is option comes out to provide objection reason and notes and click submit that means you are objecting the camp. This is objection flow.....

**Comment by gautamv16** [comment]
@BrentAllsop please test this. And for objection you must have to go for edit page and when you click on object there is option comes out to provide objection reason and notes and click submit that means you are objecting the camp. This is objection flow.....

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 I have tested Modified e-mail for modifications and objections.Everything is fine expect one thing. "Sincerely,
The Canonizer Team" font size is smaller in modifications mail.It should be uniform

**Comment by gautamv16** [comment]
@rupalichavan9860  don retest it. 

Note : when you restest a issue and its status is fixed and if you found isssue not fixed then change its status to Re-Opened

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and Verified.
