### ISSUE TITLE
Link is missing for `<topic name>:<camp name>` name in statement objected email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#700]
Link is missing for `<topic name>:<camp name>` when someone is objected to statement change.
Please refer below screenshot

![image](https://user-images.githubusercontent.com/40416610/113666972-be4b4c80-96cd-11eb-9d4b-49a325a57b83.png)

According to canonizer email document there should be link

![image](https://user-images.githubusercontent.com/40416610/113667114-f2bf0880-96cd-11eb-88f3-63deb58f0fcc.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Still I can't see the link . Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/118617608-6a5d7880-b7e0-11eb-9596-f053180dabd0.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
