### ISSUE TITLE
Page crash on supporting sub camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#701]
Steps to reproduce: 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Select any sub camp
5. Apply as of date as any previous date (than camp created date)
6. User see following screen 
![image](https://user-images.githubusercontent.com/40416610/114298228-fb9b4a00-9ad2-11eb-985c-7207aad03870.png)
7. Click on date link
8. User see following screen
![image](https://user-images.githubusercontent.com/40416610/114298261-1a014580-9ad3-11eb-91f5-fd17c7c52208.png)
9. Click on given camp created link
10. Click on "Directly Join or Manage Support" button

Actual Result : 
Getting page crash.
![image](https://user-images.githubusercontent.com/40416610/114298321-60ef3b00-9ad3-11eb-8f39-aad7a2dd8fd7.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Page crash issue is fixed on staging but I am getting same page crash for same scenario on live .Please refer attached screenshot
Live : 
![image](https://user-images.githubusercontent.com/40416610/114425443-b4967d00-9bd6-11eb-8b04-08d10fbf8c26.png)

Also I am getting another issue on staging on this:
After applying as of date filter "Your supporting camps list for topic " is not listing supporting camps(Note: When applied filter for sub camp)

![image](https://user-images.githubusercontent.com/40416610/114425749-017a5380-9bd7-11eb-87bf-08a1bb02ef73.png)

Same on supported camps page : 
![image](https://user-images.githubusercontent.com/40416610/114426963-363ada80-9bd8-11eb-8600-62398dde61ae.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I am getting page crash again
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic
4. Select any camp
5. Apply as of date date filter as any previous date
6. click on topic created date then camp created date
7. Click on "Directly Join or Manage Support" button
8. Observe result

Actual Result :  
I am getting following screenshot 

![image](https://user-images.githubusercontent.com/40416610/115175439-9a820080-a0e8-11eb-930e-fcedf28aff92.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Page crash issue is resolved now so closing this
