### ISSUE TITLE
Question on Delegated support functionality

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#702]
I have created topic  "Exploratory testing 5april2021" and topic having following camps
1.test camp 1 updated 
2.Test camp 2 
3.Test camp 3 
4.Test camp 4 by rc1
5.Test camp 5 
6.Test camp 6 moving to1

Question 1: 
User "yopmail1" delegated their support to user "@@@" for camp "test camp 1 updated " and "@@@" is supporting all the other camps also so I can see "yopmail1" as a delegated supporter for each camp

![image](https://user-images.githubusercontent.com/40416610/114427993-4901df00-9bd9-11eb-95b3-29dd48b236d0.png)

Now again user "yopmail1" delegated their support to user "Rc1" for camp "Test camp 3 " and as "Rc1" is supporting all the other camps also so I can see "yopmail1" as a delegated supporter for each camp

But when I go to user "yopmail1" supported camps I can see only "yopmail1"Support delegated to @@@Supported camp list : 1: test camp 1 updated;

![image](https://user-images.githubusercontent.com/40416610/114428894-63888800-9bda-11eb-9732-439f84f6176c.png)

![image](https://user-images.githubusercontent.com/40416610/114429014-85820a80-9bda-11eb-8844-502eccd617ad.png)

I think this is an issue.
@gautamv16  @BrentAllsop Can you please check and confirm?

**Comment by BrentAllsop** [comment]
Yes, that is an issue.  If you delegate to someone, in any camp, you are effectively delegating to them in all camps.
If you change your delegation to another person, in any camp, the entire old delegation is removed, and you now support all the camps, with the new person.

And the issue is, when it shows you are delegating to someone, at any point in time, it should list all the camps your delegate is supporting, and thereby you are also supporting.

Even though delegation is performed in a particular camp, the operation is topic wide.
Whichever camp the user did the delegation from, should not be stored in the DB, since the person delegated to may abandon that camp, and your support always follows your delegate.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thanks for the confirmation

**Comment by rupalichavan9860** [comment]
@gautamv16 Found 1 more issue in this
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/127965145-51b41bc6-2ac3-442e-a93e-72b86e217a22.png)

![image](https://user-images.githubusercontent.com/40416610/127965341-67780c11-8744-448b-b71c-920267d1a19d.png)

![image](https://user-images.githubusercontent.com/40416610/127965438-784e2dcf-6a1b-463b-92bd-5a5b9b791729.png)

![image](https://user-images.githubusercontent.com/40416610/127965486-2bbd19cd-4929-4a42-b715-d5f5285d35bc.png)

**Comment by BrentAllsop** [comment]
Also, someone should be able to remove their delegated support on the canonizer.com/support page, the same way than can remove their dirrect support, with a red "x".  In this attached picture, the delegated support should also have the same red "x":
![canonizerscreen (1)](https://user-images.githubusercontent.com/6559312/130285866-3d947410-0b76-4171-af17-849e1f64763a.jpg)

**Comment by BrentAllsop** [comment]
Also, if the user has delegated their support to anyone, in any camp of a topic, and then if they directly support any camp in that topic, all delegated support should be terminated at the same time.  It should not be possible to be both a direct and delegated support of any topic as you can see in this screen shot:
![image](https://user-images.githubusercontent.com/6559312/130287363-f178f195-40f2-4213-a5a6-800a00916bf5.png)

**Comment by BrentAllsop** [comment]
Also, if someone deletes their delegation, or completely deletes their support of all camps in a topic, all the people delegated to that nick name in that topic should receive a notification to find another person to delegate to, with a link to the camp of the last or number one camp they supported, when they did the delete, so they can do that, easily.

**Comment by BrentAllsop** [comment]
Also, it looks like there is no way to delete any kind of support, especially completely remove your support for a camp.

There is a cancel button, but there also should be a commit button.  Nothing should be committed to the db, till the commit button is pressed.

**Comment by supported** [comment]
Not too sure why I'm tagged here but,

Hello.

**Comment by BrentAllsop** [comment]
@supported,
Ouch, sorry about that Domonic.  I guess we had this unrelated word, above "@@@supported" which accidentally tagged you.
We'll work to avoid that, in the future.
But while you are hear, thanks for bringing this to our attention, and for saying hello!

**Comment by BrentAllsop** [comment]
Another issue for this.
As it shows in this image, delegated supporters are getting "1:" numbers showing the numbered supported, which is wrong, as it should always identically match the number of the person they support.
![image](https://user-images.githubusercontent.com/6559312/130820710-c3ea8623-9131-4f45-862d-3d9fa820a0f1.png)
If the direct supporters changes any support, or any order of any camp, all delegates should be identical.
All delegates should only point to the id they delegate to in the db, what camp they did this from should not be saved in the db.  Their supported camp order should always use data from the direct supporter.  There should not be two sources of this truth, which can be mistaken as we see in this case.
And no delegate supporters should have the camp support order number displayed, as this is redundant (second source of truth) information.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Still I can see 1 issue in this .
Please refer https://staging.canonizer.com/topic/331-Testing-share-value-RupaliC-Ne/2-Test-camp-1#statement

User "1rupali1" is directly supporting "Test camp 1" and "Rupali C" is supporting "Test camp 1" and "Test camp 2"

And When user "1rupali1" is delegating support to "Rupali C" for "Test camp 2" , "1rupali1" became both direct supporter and delegate supporter of "Test camp 1"

**Comment by rupalichavan9860** [comment]
Also "Test camp 1" is not displaying on user supports page for user "1rupali1" . It is displaying only delegated supported camp names

![image](https://user-images.githubusercontent.com/40416610/133124194-fae123e6-3eb5-4c20-90f7-8ecb9488796d.png)

**Comment by rupalichavan9860** [comment]
Also the delegated support can see the same red "x" and able to delete the support but not receiving support removed mail

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. When delated supporter removed support from camps , direct support is getting removed support email but nickname is displaying as direct supporter nickname instead of delegated supporter nickname in email

**Comment by gautamv16** [comment]
@rupalichavan9860 I have updated the text in the remove delegate support email. please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I can see the correct nickname now but found another issue in this 
Subject line is : "[staging.canon]Rupali cano has removed their delegated support **to** Rupali Chavan from Issue testing 702 / Test camp 1."

It should be : 
"[staging.canon]Rupali cano has removed their delegated support **from** Rupali Chavan **in** Issue testing 702 / Test camp 1."

Same for mail body : 
As of now it is displaying as : "Rupali cano has just removed their delegated support **to** Rupali Chavan in this camp: Issue testing 702 / Test camp 1"

It should be : "Rupali cano has just removed their delegated support **from** Rupali Chavan in this camp: Issue testing 702 / Test camp 1"

Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/134010682-f01a4cdb-a655-4adb-bd05-3ecfa4bdc1ca.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Email changes are working fine but found 1 issue.
Scenario : 
"user1" is direct supporter of "camp1" and "camp2" and "user2" delegating support to "user1", then automatically their support added to "camp2" as a delegated supporter
Issue : 
When "user2" tries to support the "camp1" directly , support is getting added for "camp2" also.

**Comment by gautamv16** [comment]
@rupalichavan9860 please check this. it is fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified
