### ISSUE TITLE
All public displays of "nick names" should be a link showing the supports for that nick name.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#704]
For example, in the history page, it lists the nick name which submitted each version.
This should be a link to the supports page for that nick name.

Any other place a nick name is publicly displayed should also be a link.

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see this changes on staging but I am getting page crash on some links and some links are redirecting to wrong URL's

Issue 1 : 
Please find attached screenshot

1. Can see below link to nick name "Rupali auto"

![image](https://user-images.githubusercontent.com/40416610/117762440-cbb4a300-b246-11eb-90c1-0db1d3f73c67.png)

2. When I click on "Rupali auto" ,I am getting below page crash

![image](https://user-images.githubusercontent.com/40416610/117762507-ef77e900-b246-11eb-9bde-5d2b088ac17c.png)

Issue 2:

1. I can see "Rupali C" nick name in one objected statement history page below

![image](https://user-images.githubusercontent.com/40416610/117762682-3fef4680-b247-11eb-9fc7-7fa08a8184a3.png)

2. When I click on "Rupali C" it is redirecting to below users support page

![image](https://user-images.githubusercontent.com/40416610/117762807-71681200-b247-11eb-9ee4-5d6b448cff40.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 Its fixed pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested and verified. Working good now so closing this issue
