### ISSUE TITLE
All public displays of "nick name" link should highlight specific topic/camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#712]
Topic/camp : https://staging.canonizer.com/topic/299-Exploratory-testing-5april2021/2-test-camp-1-updated#statement

This topic is present under Namespace : /sandbox_testing/
1. When user is on Camp Statement History page and click on nick name link "Rc1" ,  /sandbox_testing/ namespace should get selected and topic/camp name should get highlighted. 
As of now user can see selected namespace as /General/

2. When user is on Topic History page and click on nick name link  "Rc1",  /sandbox_testing/ namespace is getting Selected but topic/camp name is not getting highlighted. 

3. When user is on Camp History page and click on nick name link , "Rc1"  /sandbox_testing/ namespace should get selected and topic/camp name should get highlighted. 
As of now user can see selected namespace as /General/

Like working on thread pages

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Working fine on history pages but I found new issue on this 
Refer topic : https://staging.canonizer.com/topic/314-Retesting-issue-686-v4/1-Agreement
This topic was moved from /sandbox/ to  /sandbox_testing/ but when user click on forum pages user nick name link user can see selected namespace as /sandbox/

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working good now so closing this
