### ISSUE TITLE
Viewport not set to "device-width"

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#713]
Google notified me of this issue in Canonizer.com.

See:
https://search.google.com/search-console/mobile-usability/drilldown?resource_id=sc-domain:canonizer.com&item_key=CAc&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en

Note: You must be logged in to canonizer's Google search console to see this page.

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop Can you provide us the credentials for Google Search Console?

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop any update on this?

**Comment by HamzaBinMansoor** [comment]
@BrentAllsop This is already fixed as <meta name="viewport" content="width=device-width, initial-scale=1"> has already been added. Do you want us to work on the rest of the errors in Mobile Usability section in the Google Search Console?

**Comment by BrentAllsop** [comment]
I just checked this page:
https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Acanonizer.com&item_key=CAMYEyAE&hl=en
![image](https://user-images.githubusercontent.com/6559312/134554236-b792a55c-72bc-4148-9241-7ce7a7d84d1e.png)
But those errors are fixed, so I told google those errors are fixed, and started a validation to be sure.
I'll get back when I see the results, that it shows zero errors.

**Comment by rupalichavan9860** [comment]
@BrentAllsop @HamzaBinMansoor As per discussed in meeting I have added Ready for release label for this

**Comment by BrentAllsop** [comment]
We need to release this, then test it, before we can close this, right?

**Comment by BrentAllsop** [comment]
Hi @HamzaBinMansoor ,
It is  now live, and I'm showing one remaining issues, that looks like a validation has started on that, but it is still "pending".
I'm not seeing how to get that to complete?  Is that the issue?
What do we need to do to close this?

**Comment by BrentAllsop** [comment]
Oh, it finally resolved and the validation finally passed:
@HamzaBinMansoor, go ahead and move this so it is marked as done and closed on the project board.
![image](https://user-images.githubusercontent.com/6559312/138988108-bc8787b5-a3ed-4d09-89dd-659668fac06f.png)
So closing this issue.
