### ISSUE TITLE
http://3.12.165.249/ :Data Could Not Be Found issues on Privacy Policies and Terms & Services pages click

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#724]
Steps to reproduce : 
1. Go to http://3.12.165.249/ 
2. Click on "Check it out!" link from What's New at Canonizer block
3. Click on Privacy Policy and Terms & Services link

Expected Result : 
User should see Privacy Policy and Terms & Services respectively

Actual Result : 
It is displaying Data Could Not Be Found .Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/123677312-9699f980-d862-11eb-9ca7-70bdefd649a7.png)

![image](https://user-images.githubusercontent.com/40416610/123677363-a6194280-d862-11eb-8444-cb783bdb38fc.png)

**Note : Same issues exists on canonizer live (https://canonizer.com/) also**

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Still I can see Data Could Not Be Found . Can you please check again and confirm

**Comment by akuks** [comment]
@rupalichavan9860 can you please test this. I think it is fixed by either Varun or Karun.

**Comment by rupalichavan9860** [comment]
@akuks @gautamv16 Tested and verified. I can see Privacy Policy and Terms & Services pages now so closing this issue
