### ISSUE TITLE
JavaScript errors on new secure server 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#727]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/124548061-ce003b80-de4a-11eb-8948-557ca8ce9fef.png)

**Comment by akuks** [comment]
I only see one javascript error and that is of show_ads.js. It is because we are accessing this using the http instead of https. Once the server is migrated to the new domain, the issue will be resolved.
