### ISSUE TITLE
robots.txt is missing on new secure server

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#728]
Steps to reproduce : 
1. Go to http://3.12.165.249/
2. Add robots.txt to URL and press enter key

Actual Result : 

Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/124561667-c6955e00-de5b-11eb-9e3a-4d30aa42d2b2.png)

**Comment by akuks** [comment]
Done

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified. I can see the robots.txt file now so closing this issue

**Comment by BrentAllsop** [comment]
On Dec 5, 2021, I got a google search result pointing to:
https://canonizer.com/browse
I immediately checked robots.txt, which contained this entry:
Disallow:/browse/*

So we are assuming these google search results were stale, and will eventually be removed from the index.
If this continues, this issue should be re-opened, and further work be done, possibly contacting google, to get this issue resolved, so browse pages are not included in search results.

**Comment by BrentAllsop** [comment]
I was googling for "death" on Canonizer, which resulted in a reference to this user page:
https://canonizer.com/user/supports/55
We only want references to pages like this:
https://canonizer.com/topic/67-Death-Gives-Meaning-/1-Agreement
Not users support pages containing links to those.

Unless there is specific user information we do want searchable (I don't see any) we need to include the following line to robots.txt:

Disallow: /user/*
