### ISSUE TITLE
JavaScript errors 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#736]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Open developer Tools 
3. Observe "Canonizer Main Page " and "Login" page for JavaScript errors

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/126078150-5827a80b-d3ba-4bc2-bb90-da2fbdb24e3e.png)

**Comment by rupalichavan9860** [comment]
This issue is exists on "Terms & Services" page also

**Comment by gautamv16** [comment]
I think we need discussion for this because these console logs are coming from google ad and morever we should not be creating bugs for console logs unless they are blocking any functionality on that page. because they may come because of different plugin on user's browser or ad blockers etc.
