### ISSUE TITLE
Numbering doesn't work in forum posts.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#737]
If you make a list of items on multiple lines in a forum post, then select the button to turn that set of lines into a numbered list, there are lots of problems, like duplicate numbers for each item.

It should be possible to cut and paste numbered lists from other sources, like MS Word, and have it work, as pasted.

**Comment by akuks** [comment]
@ashish76 I am confused. Is it fixed ? I see it is mentioned in 25th release merge request

**Comment by ashish76** [comment]
@akuks No, I did not work on it. I can see this ticket in the in-progress state.

**Comment by akuks** [comment]
@ashish76 Ticket is in progress but it is mentioned in 886 ( Merge Request ). [Iffort 25th release]

**Comment by rupalichavan9860** [comment]
Not able to test as not able to create/update post mentioned in issue #921

**Comment by rupalichavan9860** [comment]
We forgot to test this issue after resolving page crash . Just tested and working fine on both staging and live so closing this issue
