### ISSUE TITLE
Incorrect camp name displaying on some pages

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#739]
Please refer attached screenshot : 

Live Camp name 

![image](https://user-images.githubusercontent.com/40416610/127838829-e16308fe-cd93-4cca-8d10-6ad5729a8e8e.png)

Issue 1 : 
Old camp name is displaying on Create New Camp page ->Parent Camp drop down. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/127839355-5f5a271d-e613-4785-ae31-40d8810def28.png)

Issue 2 : 

Not live camp name is displaying on supported camps page. Go to Agreement camp and click on "Directly Join or Manage Support" and observe already supported camp name .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/127840227-7a15d846-f97c-449c-b241-3f826310ae6b.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Still displaying not live camp names on supported camps page .Please refer below screenshots
Live Camp names : 

![image](https://user-images.githubusercontent.com/40416610/131252504-63a27780-85e1-4cd5-8a71-1f839f9d46ef.png)

Supported camps page :

![image](https://user-images.githubusercontent.com/40416610/131252547-d9aa3274-a310-41cd-9a7e-3d964f5afd07.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. Still not working , still can see not live camp names

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Now it is displaying live camp name so closing this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 Still it is displaying not live camp names on supported camps page so reopening issue

**Comment by rupalichavan9860** [comment]
![image](https://user-images.githubusercontent.com/40416610/134551370-3bb57dc2-dfbc-4c3e-92ff-0ffbc922887d.png)

![image](https://user-images.githubusercontent.com/40416610/134551435-6e045e56-856a-49ed-bc89-c16412123253.png)

**Comment by nalwa** [comment]
@rupalichavan9860  i am not able to re-produce this issue, If it appears in some certain cases do mention that.
as i have asked @saniatg  to test the same she was also not able to re-produce it.

**Comment by rupalichavan9860** [comment]
@nalwa @saniatg Let's have a quick call

**Comment by nalwa** [comment]
@rupalichavan9860  issue fixed

**Comment by rupalichavan9860** [comment]
@nalwa Tested and verified
