### ISSUE TITLE
Back to Site Link issue on blog

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer.2.0#74]
The 'Back to Site' link is not working on Blog Page. Gives an error message of "Not Found".
--

@BrentAllsop today need to discuss this how this needs to be done.

**Comment by gautamv16** [comment]
@BrentAllsop and @Kinari solved please check.......

**Comment by gautamv16** [comment]
@kinaari and @BrentAllsop  please test

**Comment by BrentAllsop** [comment]
verified.
