### ISSUE TITLE
 Login with MetaMask button is not working

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#741]
Nothing is happening when user click on  "Login with MetaMask" button on Crypto Verification page. I can see JavaScript errors on the page  
Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/128147218-4ed95c35-fae2-4942-b63f-e3666a2a60d6.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 This issue is exists on live also

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified on staging, it is working fine on staging

**Comment by rupalichavan9860** [comment]
@gautamv16 Again getting this issue so reopening this

![image](https://user-images.githubusercontent.com/40416610/136079964-458626b5-ba21-4701-911a-c2ff9e69ce9a.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 I have checked it on staging it is working for me, is your metamask plugin for chrome is installed?

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.

**Comment by saniatg** [comment]
@rupalichavan9860 ad @gautamv16 I'm getting console error and when click on button"Meta mask" nothing happens. It is not responding
![Screenshot 2021-10-21 at 7 02 43 PM](https://user-images.githubusercontent.com/91254708/138396261-2b436946-da4b-44a3-9a99-887fd94afba5.png)
.

**Comment by rupalichavan9860** [comment]
@gautamv16 This is occurring when MetaMask plugin  is not installed. I am also facing this on Firefox as MetaMask plugin is not installed. Can we have some user friendly message or link to link download plugin so that user will not face issue in future

![image](https://user-images.githubusercontent.com/40416610/138431571-3a4d4904-57c3-474d-a241-fe86e094d951.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is fixed , please test and verify

**Comment by rupalichavan9860** [comment]
@gautamv16 I can see the download option now but download metamask image is broken. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/138816478-77fe5da1-88ac-4b46-993c-e8efe853434a.png)


Also image is missing in Firefox

![image](https://user-images.githubusercontent.com/40416610/138816722-86bde7d4-c051-4ad5-b94d-9a93b05d3874.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 this is done. please check

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.

**Comment by rupalichavan9860** [comment]
Verified on production
