### ISSUE TITLE
Check for parent or child camp being supported using wrong version of record.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#742]
When you add support to a camp, it does a check, then gives a warning that any supported parent or children camps will be removed if it is committed.
The code that is doing this check is broken.  It is, not getting the right version of the record.
It uses the first version of the record, not the current version of the record.
There is two problems with this, the problem itself, second, this also shows that this is not using a single standard source of the code.  Everyone should be using the same code, so things like this can’t happen multiple times.

In the live DB:
The first version of the John Gregg camp (http://3.12.165.249/topic/81-Mind-Experts/16-John-Gregg#statement) has
as it's parent camp the Chris Firth camp (http://3.12.165.249/topic/81-Mind-Experts/15-Chris-Frith), which was fixed in a later version record.
So it should not give that warning, nor should it change the support, when you add or change support to one, or the other, since in the current version, they are not related.

**Comment by BrentAllsop** [comment]
Just found another related issue to this one.
![image](https://user-images.githubusercontent.com/6559312/131576246-c1bc6c6e-7bba-4000-aa87-cf3350ab7809.png)
Before I took the action to support the Zibtek Proposal camp, I had removed my support for the parent "15K Design Sprint or Discovery" camp. 
So, in addition to getting the wrong versions of the parent children data, it seems to also be getting the wrong timed versions of the support records, as I had terminated my support for that camp, before taking this action.

**Comment by BrentAllsop** [comment]
I found another failure case which needs to be tested for, before this is closed.
I was not supporting this camp:
![image](https://user-images.githubusercontent.com/6559312/132851114-74f0ab21-ddb2-4db4-99e9-5e002f166307.png)
And as you can see, this camp has never had any other camp, other than the "Consensus Design" camp.
Yet, when I try to support that camp, I get:
![image](https://user-images.githubusercontent.com/6559312/132851257-2e6d8ed8-a7bb-4006-bde6-399c3d900184.png)
Even though the zibtek camp was never a parent camp to this camp.

And even worse, when I try to accept that, then add the zibtec camp back, I get:
![image](https://user-images.githubusercontent.com/6559312/132851618-8684396e-7950-42ca-8e92-fecb590a4a47.png)

evidently making it impossible to support all 4 camps.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.
@BrentAllsop I tested all the possible scenarios and working fine for me . Can you please check this and close if it is working perfectly

**Comment by BrentAllsop** [comment]
Yes I tested this and can't see any problem on staging, so closing this.
Thanks all.
