### ISSUE TITLE
Delegateee supporters should be able to object.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#745]
If you delegate your suppor to someone else, you don't receive e-mail notifications, and such.

But you do still have the right to object to any changes you don't like.

So you should have an object button to any proposed changes of any camp you are a delegated supporter of, or parent camp.

Currently, the object button is missing, so a delegated supporter is not able to object.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested . Delegated supporter still not able to object. Can't see object button

**Comment by rupalichavan9860** [comment]
@gautamv16 Not able to test this for camp as I am getting page crash on Manage/Edit This Camp and Still Can't see object button for topic and statement history

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
