### ISSUE TITLE
Share value = latest record for that as-of value, not sum of all records.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#748]
![image](https://user-images.githubusercontent.com/6559312/130824251-6e4016e7-4f75-482c-a1c7-6fef23dd1cbb.png)
In this image, it is showing the sum of the shares in all brents share records, not just the latest record's value.
It should only be the value in the latest record, previous to whatever as-of date is selected.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please check this . 
I still can't see correct data .Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/131258825-6ea0ea93-10e6-4c3f-8830-63e2072eb06e.png)

**Comment by BrentAllsop** [comment]
Just noticed another issue with this one.
![image](https://user-images.githubusercontent.com/6559312/131586404-0d468cd2-db4c-4021-b90a-8c0b9cadac2d.png)
I'm supporting 3 camps, in the order the camps were created.
But I'm getting my entire vote, the same for all 3 camps.
All algorithms, including the share algorithm, should operate the same as the 1 person one vote algorithm.
If you split your vote, you only get 50% of your total canonized score for the first, 25% for the second, and so on.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. I have updated As Of Date in admin panel as today's date and I have created one more entry for today's date. Please refer screenshot 
![image](https://user-images.githubusercontent.com/40416610/133052959-e5e1daba-0872-4311-abab-c119100fab6c.png)

But I can't see correct values on agreement page when selecting algorithm Canonizer Shares

![image](https://user-images.githubusercontent.com/40416610/133053104-ce43f2d2-c02f-41c2-a859-1cab0493ad19.png)

**Comment by gautamv16** [comment]
@rupalichavan9860  as per your screenshot the latest value of shares for your user for sept month is 2 and it is showing that value. what is wrong in this

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and checked after modifying to latest date and it is displaying latest share value. Closing this
