### ISSUE TITLE
When upload of file fails, it still shows URL that is not real.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#750]
Currently the uploading of files seems to fail.
That needs to be fixed, probably a permissions problem?

But it also needs to not look like it succeeds, proving a URL that doesn't work.
It should give some failure message, instead, and only give the URL, if the file is actually there.

And we shouldn't close this till we have a way to automatically test this functionality (verify the URL works, and the same file can be downloaded via that URL, then remove the test file after it is deposited, so as to not fill up the disk.

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified on staging and working fine there .
I tested this on live also and getting page crash for files of type .exe, .tif which are more than 5120 kilobytes.

![image](https://user-images.githubusercontent.com/40416610/134567126-688f69a8-cc35-484b-ad9e-aef9890d85cc.png)

My be this will work once deployed to production

@BrentAllsop Can you please test this if I am missing something

**Comment by nalwa** [comment]
@gautamv16 Apache configuration needs to be updated for below

post_max_size
upload_max_filesize

**Comment by BrentAllsop** [comment]
Thanks @nalwa.

**Comment by BrentAllsop** [comment]
We need to decide the size limits, and what types of files we allow.
I'm thinking we only want image files, for people to include on wiki pages.
Once this is specified, we need to include automated tests to verify all these limits and types.
Before we can close this.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Previously it was accepting image files only , after that you said We want to be able to host files of any type.
Especially mp4 files and such. 

Please refer ticket https://github.com/the-canonizer/canonizer.2.0/issues/613

**Comment by BrentAllsop** [comment]
@rupalichavan9860, oh yes, I forgot about that.  thanks for remembering all this.
We are now hosting video files at [https://canonizer.com/videos/](https://canonizer.com/videos/), also, since we now have access to shared google docs, sheets, and all that the need to host things like that no longer exist.
So I'm thinking we should go back to just hosting image files.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Should I move this issue to "To Do" then?

**Comment by BrentAllsop** [comment]
@sunnyjindal,  I'm thinking we should move most everything that needs to be done into the "To Do" board, but wanted to ask you, as scrum master.

**Comment by sunnyjindal** [comment]
@BrentAllsop I would suggest that we should have 2 list - TODO and Assigned. TODO can have all points as mentioned by you. Assigned can have those tickets that have been assigned to the teams.

**Comment by nalwa** [comment]
@rupalichavan9860  what needs to be done for this ticket? 
I am not clear about it, please explain .

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please confirm on this ?
It should only allow to host image files ? or do we need all types of files?

**Comment by BrentAllsop** [comment]
@rupalichavan9860  Currently, we want to only host image files.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please confirm which types of Image Files we want to host? As of now we are able to host jpeg,jpg,png,bmp,gif files

**Comment by BrentAllsop** [comment]
This set sounds correct to me: "jpeg, jpg, png, bmp, gif".

**Comment by rupalichavan9860** [comment]
@nalwa File with size 5.2MB is getting uploaded on Mac. Can you please check

**Comment by nalwa** [comment]
@rupalichavan9860  @gautamv16 I have checked this and i found this:
5234617 Bytes = 5.234617 MB (in decimal)
5234617 Bytes = 4.992119789123535 MB (in binary)

Calculation made while upload is through binary process so file with 5234617 bytes(5.2MB) on system is actually calculated as 
4.992119789123535MB in binary which 5MB appx. not greater.

So this difference will remain for 1-2KB. And  this doesn't seems issue to me.
@gautamv16  please let me know the further action

**Comment by rupalichavan9860** [comment]
Tested on production and getting below page crash when tying to upload large files (more than 8 mb)so moving to "To Do"

**Comment by rupalichavan9860** [comment]
Working fine now so closing this
