### ISSUE TITLE
Need notification on non live systems

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#751]
We need a notification at  the header of all canonizer pages that are not the live system.
I fear some people may be using staging.canonizer.com assuming that is a live system.
So on all system that are not live, we need an indicator that anything they do there will not go into the live system.
This notification will only not show up on the live system.

**Comment by BrentAllsop** [comment]
It currently says:
"This is not the live system.So any activity you perform here will not go to live system. Please go to canonizer.com"
Change this to:
"This is not the live system.  Any data submitted here is for testing purposes only and will be lost. Please go to canonizer.com"

**Comment by BrentAllsop** [comment]
It currently says:
"This is not the live system.So any activity you perform here will not go to live system. Please go to canonizer.com"
Change this to:
"This is not the live system. So any activity you perform here will not go to live system. Please go to canonizer.com"

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.
@BrentAllsop Can I close this if fine for you?

**Comment by BrentAllsop** [comment]
Yea, this looks great to me, so closing this issue.
