### ISSUE TITLE
Agreement page is not displaying properly for some topics

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#752]
For some scenarios Agreement page is not displaying properly for some topics. Please refer attached screenshot
![image](https://user-images.githubusercontent.com/40416610/133021957-a07759bb-cfb0-47b1-aa24-0ee91d5a1a66.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860  , I have reviewed most of the topic on staging and production too, but i am not able to reproduce the error you have mentioned. The topic you have mentioned is not available on staging now. Please review all scenario and let me know.

Thanks

**Comment by rupalichavan9860** [comment]
@sunilspr7 @rohit-talentelgia Yes. This will be non-reproducible as we have copied production data to staging .
Previous Scenario : 
Previously when user was delegating their support to someone and submitting delegated support, user was able to click submit button multiple times and support was getting added multiple times.

And now multiple clicks issue is resolved, so we are unable to reproduce this
