### ISSUE TITLE
Reason for statement change is lost when re editing.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#759]
After you submit a camp statement, you get the preview, which can be re edited.
If you select edit, the camp statement is not lost, but the description of the change is lost, and needs to be re typed.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I am confused on this. Previously we decided "Don't pre populate "Edit Summary" or note field when making modification." . Please refer issue https://github.com/the-canonizer/canonizer.2.0/issues/530 

As per this fix we can see the "Edit Summary" on statement update page. Do do we need to change same for topic and camp also? or do we need to go with this ->  https://github.com/the-canonizer/canonizer.2.0/issues/530

**Comment by BrentAllsop** [comment]
@rupalichavan9860   Right, we shouldn't ever pre populate the reason field from a previous edit record.
But, if we enter a reason, then "preview" that edit with reason, then go back to the edit page, or in any other way return to continue an edit, we should attempt to preserve the reason, if it is entered for the current edit.  Does that make sense?

**Comment by HamzaBinMansoor** [comment]
![image](https://user-images.githubusercontent.com/79147323/135973241-4e979577-1c7a-43aa-a737-92293c8220e6.png)

As discussed in the scrum meeting:

If the User presses the "**Submit Camp Based on this**" the **Edit Summary** Will be Empty
If the user presses the "**Edit Change**" Button then the **Edit Summary** field will be pre-filled with previous data

**Comment by aliahmad45** [comment]
Do we need this functionality for Topic & camp as well?
there is same functionality when we edit the topic and camp.

**Comment by rupalichavan9860** [comment]
@aliahmad45 We need the same functionality for Topic & camp as well

**Comment by rupalichavan9860** [comment]
@aliahmad45 @gautamv16 As it needs to be implement , I am moving this to "To Do"

**Comment by rupalichavan9860** [comment]
@aliahmad45 @gautamv16 Tested and verified
