### ISSUE TITLE
Corruptic topic tree in  "mind expert" ranking topic (81)

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#76]
Somehow we lost the root camp of this topic, and the camp for Daniel Dennett is the root camp on the production and staging systems:
https://staging.canonizer.com/topic/81

This is a corruption from the original 1.0 topic, which can be seen in archive.org here:
https://web.archive.org/web/20140906184517/http://canonizer.com/topic.asp/81

**Comment by BrentAllsop** [comment]
We might also want to consider the root cause of this issue, and think about if there are similar problems elsewhere in the 2.0 data.

**Comment by BrentAllsop** [comment]
The theory is, that some of the objected to values, did not get carried over to the 2.0 DB.
For example, if you look for this history, of the topic record for topic 81, the first version of the record is the correct value.  We predict that all later values of this record, in the 1.0 DB, have been objected to, resulting in the topic name being "Mind Experts" instead of "Daniel Dennett" (an objected to value).

This issue also exists in the "godly topic"  (an objected to name) (topic #2)

**Comment by gautamv16** [comment]
@BrentAllsop please test it thouroughly, its correct accoridngly....

**Comment by BrentAllsop** [comment]
@gautamv16 @CanonizerJim ,
I'm seeing this fix on staging, looks OK there, but not seeing it in the production db.

**Comment by gautamv16** [comment]
@BrentAllsop code is not migrated to production yet. Today i will merge staging with production. Please check then.
