### ISSUE TITLE
Add ability for users to remove their registration, and stop e-mail.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#761]
We have users that do not want to receive any more e-mail from Canonizer.com.
We need to add an easy button people can execute to stop the e-mail and remove their account.

We should mark all their support of camps as disabled, and no longer user visible.

**Comment by BrentAllsop** [comment]
We should have a design and review of a solution for this, before it is implemented.
We don't want to completely remove users, just mark all their support as inactive, and make sure they don't' get any more e-mail, and have some way to reactivate things if they want.  Make them feel like their account has been removed, but not really.

**Comment by ashish76** [comment]
@BrentAllsop & @gautamv16 
Based on the specification given above, my understanding is as follows
- There should be a provision to deactivate or activate the user account. 
- Once the user gets deactivated he/she will not be able to receive an email notification from the canonizer.
- All the supported camps of the inactive user will no longer be visible to the user 

Based on my understanding, I have few queries 
- Can inactive users access the system?
- Activate/Deactivate a user can be done by the Admin, is it right?
- Any Topic or camp created by an inactive user will no longer be visible to the user, is it right?
- Can it be possible that a user wants to be an active user but doesn't want to receive emails from the canonizer?

It will be a great help to answer the above query, which will help to design the solution.

**Comment by ashish76** [comment]
Conclusion of the discussion had with Brent related to this feature

1. There will be a button to Activate/Deactivate an account in the user's account settings.
2. Once the account is deactivated, the user will not be able to receive email notifications from the application.
3. The nickname will not be visible to all the supported camps by the user from the date of deactivation. The nickname of the user can be replaced with Anonymous.
4. A deactivated user will access the system with limited privileges. He/She can access only the account settings. 
5. If the user reactivates the account then the system will back to the normal state, and the user will be able to access all the features of the application as before.

**Comment by BrentAllsop** [comment]
@ashish76 
There are nick name records that support camps.
They have a start time, and a termination time field which can have a not terminated (infinite?) value, for when the support is active.
When the user abandons a camp, the termination time is set to the time the support was terminated.
This is what allows the "as of" system to preserve history.
I was thinking of just iterating through all current "not terminated" records, when the user deactivates an account and marking them as terminated, as of the time the account was deactivated.
We loose the ability for a user to restore their previous state, should they decide to reactivate, but I think the simplicity of doing it this way is worth it, and will not require the significant amount of additional design to handle all that.
And the user can always get a list of what they supported, immediately before the termination date, via the as of functionality, then use that to restore their support.
Does that sound like the right way to do things?

**Comment by ashish76** [comment]
> @ashish76 There are nickname records that support camps. They have a start time and a termination time field which can have a not terminated (infinite?) value, for when the support is active. When the user abandons a camp, the termination time is set to the time the support was terminated. This is what allows the "as of" system to preserve history. I was thinking of just iterating through all current "not terminated" records, when the user deactivates an account and marking them as terminated, as of the time the account was deactivated. We loose the ability for a user to restore their previous state, should they decide to reactivate, but I think the simplicity of doing it this way is worth it, and will not require the significant amount of additional design to handle all that. And the user can always get a list of what they supported, immediately before the termination date, via the as of functionality, then use that to restore their support. Does that sound like the right way to do things?

Hi Brent, 
I have gone through with your suggestion and I somewhat agree with this but I have a query. 
**Query:**
1. What will happen a user pullout his support from a camp and then deactivate his account. After few days he activates his account once again but doesn't want to support that camp. Shall we remove the termination date from the camp or it will remain there?

I would prefer to keep these two functionalities separately and based on that below will be my approach to implement this functionality. Please find the attached document for your review.


[Canonizer-Understanding-Document.docx](https://github.com/the-canonizer/canonizer.2.0/files/7322002/Canonizer-Understanding-Document.docx)

@BrentAllsop Please let me know if we can discuss this today.

**Comment by ashish76** [comment]
@BrentAllsop & @gautamv16 
Based on yesterday's discussion, I have checked the flow and the suggested approach seems to be workable. 
Based on that I have updated the document. Please have a look and let me know if any feedback or suggestion.

[Canonizer-Understanding-Document.docx](https://github.com/the-canonizer/canonizer.2.0/files/7329391/Canonizer-Understanding-Document.docx)
