### ISSUE TITLE
User is not able to login - shows error  "User is no longer active on canonizer "

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#769]
Steps to reproduce :
1- Click on 'Register' enter the details  , DO NOT verify the  OTP instead click on 'Login' link .
2- Try to login, it will give an error: "User is no longer active on canonizer "
3- On login Page  with that same email address click on the button" Request the OTP" 
4- Enter the OTP and login
5- User will login successfully and then logout
6- Now  try to login again, it will not let you login and will show error "User is no longer active on canonizer "

Actual Result: Every-time I try to login is shows error "User is no longer active on canonizer "
 I have to request for an OTP to login  every-time, it can be cumbersome for the users to every-time request for OTP to login  
Expected Result: In such case, where the user does not verify the OTP and try to login should show a message" Your account is not verified" once they verify the OTP they should not be asked to again verify their account after sign out.

**Comment by rupalichavan9860** [comment]
@aliahmad45 @HamzaBinMansoor Tested. User is getting "Error! Your account is not verified" this error but when tried for "Request One Time Verification Code" , user is not receiving new One Time Verification Code

**Comment by aliahmad45** [comment]
Hi @rupalichavan9860 ,
I tried with my account "ali.ahmad@codedistrict.com" which is already verified account but i'm receiving one time verification code.
I've attached a picture of otp for your reference.
![image](https://user-images.githubusercontent.com/90698926/135813801-eee4f640-3261-495d-b0eb-716439cd1d97.png)

can you please let us know which process you followed?

**Comment by rupalichavan9860** [comment]
@aliahmad45 Your account is already verified. Please try to register with new account and don't verify your new account with One Time Verification Code

**Comment by aliahmad45** [comment]
@rupalichavan9860  registered with new account "techverd@gmail.com". Verified my account through verification code which we get after registration then generated a one time verification code and i got code through email.
![Image](https://user-images.githubusercontent.com/90698926/135818933-6ba1b112-6801-4b96-a4d0-d18481133dfe.jpeg)

then registered a another account, did not verify the account and generate the one time code and received a code in my email.
![image](https://user-images.githubusercontent.com/90698926/135819523-37235b88-ef25-44fb-b33a-1e1bb86c125e.png)

**Comment by rupalichavan9860** [comment]
@aliahmad45 
I was checking on different email .Tested and verified this. Working fine so closing this issue
