### ISSUE TITLE
Wiki Markup for Images

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#77]
Wiki markup for images is not working properly. 

<img src="&lt;img src=" http:="" production.canonizer.com="" files="" canonizer_logo.jpg"="">

**Comment by gautamv16** [comment]
Hey @BrentAllsop and @CanonizerJim  here is the markup for image. Please use this standard markup style.

For example, <nowiki> [[File:http://canonizer.com/files/canonizer_logo.jpg]]</nowiki> displays:

[[File:http://canonizer.com/files/canonizer_logo.jpg]]

**Comment by gautamv16** [comment]
@CanonizerJim and @BrentAllsop please check this.

**Comment by BrentAllsop** [comment]
@CanonizerJim @gautamv16,
Jim, this looks OK to me, if you agree, could you close this issue?
Thanks
Brent

**Comment by CanonizerJim** [comment]
I'll close it now.
