### ISSUE TITLE
Topic submitter is not getting "proposed changed to topic" email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#771]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create any new topic or take any existing topic
4. Login with another user and submit a change to topic

Expected Result : 
Submitter should receive "proposed changed to topic" email

Actual  Result : 
User is not receiving  "proposed changed to topic" email

**Comment by sunilspr7** [comment]
Steps to reproduce :

  1  Go to https://staging.canonizer.com/
  2 Login with valid email and password
  3 Create any new topic  
  - Topic creator User received this mail - this text in mail makes no sense. 

![-staging-canon-Thank-you-for-contributing-to-Canonizer](https://user-images.githubusercontent.com/6298462/135446992-4d776b98-0fdd-4539-b738-4d75333114cc.png)


@gautamv16  @rupalichavan9860 - Please verify if it meet to change or not?

**Comment by sunilspr7** [comment]
@rupalichavan9860 ,

I have now created a new email template for the proposed change in the topic. and now the email is implemented as per your comment.

But I have a query, will this email be sent to all the supporters of that topic as well along with the creator of the topic?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Can you please confirm, do we need to remove this "You proposed a change for topic" in email for first time topic creation

**Comment by BrentAllsop** [comment]
@rupalichavan9860 , I added an agenda item for Monday Oct 4th to discuss how we can better manage who is getting what e-mails, when, along these lines, with reference to this issue and [775](https://github.com/the-canonizer/canonizer.2.0/issues/775)

**Comment by sunilspr7** [comment]
@BrentAllsop  @CanonizerJim  @rupalichavan9860  Please provide the email content to be sent to all the supporters in case someone  updates in the supported topic

**Comment by rohit-talentelgia** [comment]
@sunilspr7 The email template is there in the document provided by Rupali.

**To Direct supporters when change is proposed.**

From: canonizer@canonizer.com
Subject: Proposed change to <topic/camp/statement id> submitted

Hello {first_name} {last_name},

{nick_id} has proposed a change to this <topic | camp | statement> <topic name>:<camp name> <link to camp with change, as_of value set to include review> which you currently directly support.  If no supporters of this <topic | camp | statement> object to this change, it will go live in one week {go_live_time}.

If you do not wish to receive these notifications, you can either delegate your support to some other camp supporter in the topic, or remove your support from the camp.  We request that all direct supporters of a camp continue to receive and take some responsibility for the camp.

Sincerely,

The Canonizer Team

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested. When "user1"  created new topic and "user2" proposed changed to topic, "user2" is receiving email but "user1" is not receiving the proposed changed email

**Comment by sunilspr7** [comment]
@rupalichavan9860 as per ticket, submitter should receive the email, and submitter is who is proposing change on topic.
So, email is being sent to submitter and direct supporters. 
And Creator is already direct supporter so he/she will receive email, if he /she has removed their support from topic in that case you want us to send email to that person?

**Comment by rupalichavan9860** [comment]
@sunilspr7 Can we have a quick call for this?

**Comment by sunilspr7** [comment]
sure

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified
