### ISSUE TITLE
Issue on Total Support score 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#772]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create any new topic 
4. Create 2 camps under that topic
5. support both camps using same user

Now score of user1 is 0.50 and user 2 is 0.25

6. Login with another user
7. Delegate support to any camp : delegated support will automatically get added for second camp
8. Observe score of each camp for each user

For 1st camp I can see score as  : 
Direct supporter : 1
Delegated supporter : 0.5

For 2st camp I can see score as  : 
Direct supporter : 0.5
Delegated supporter : 0.25

It seems like issue for me
@BrentAllsop can you please confirm

Please refer topic https://staging.canonizer.com/topic/282-Testing-bad-links-emails-issue/3-Rupali-2#statement

**Comment by BrentAllsop** [comment]
Yes, this is an issue.  with 1 person 1 vote canonizer algorithm, all delegates should have the same score as the direct supporter, for all supported camps.  And all delegated supported camps should be the nth supported camp, where n is the same number of supported camp for the direct supporter.

**Comment by rupalichavan9860** [comment]
@kshitij1326 Tested and verified. Score looks correct for me so closing this

**Comment by saniatg** [comment]
@kshitij1326 Count is showing correct for supporting tree but wrong for camp tree.
Please Refer screenshot -> Highlight are the counts which are incorrect
![Screenshot 2021-10-13 at 3 58 17 PM](https://user-images.githubusercontent.com/91254708/137116562-d6e81581-723b-49f9-968a-d26c41bc1062.png)
.

**Comment by kshitij1326** [comment]
on checking this situation, i found that when main user removed their support from camps to Agreement, delegates and sub delegates supports are not removed, and also i got an extra entry for delegates of main user.
![Screenshot from 2021-10-14 13-20-43](https://user-images.githubusercontent.com/91306850/137275015-a94fefc0-ae11-4a76-86c8-095c719f5af4.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 yes delegated support is not getting removed. We already have an issue for this #790  .Once that fixed I will check the score count and then close

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
