### ISSUE TITLE
File name validations are missing on Upload file

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#773]
As of now file name field is accepting any name including special characters. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/134723777-25acdfee-be48-48e0-ad0b-20889df2fdf2.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified.

**Comment by rupalichavan9860** [comment]
@aliahmad45 @gautamv16 As of now it is validating File name field, but it is not validating original file name
Need to discuss on this

**Comment by HamzaBinMansoor** [comment]
As discussed in the scum meeting:
1. The File Name field will be required.
2. File Name field can accept an alphanumeric string.
3. Only special characters allowed are - and _

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor @gautamv16 As it needs to be implement , I am moving this to "To Do"

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor Tested and verified
