### ISSUE TITLE
Once forum "submit" button is pressed, disable it until a change is made in the post

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#774]
We need to prevent multiple posts of the same thing.

**Comment by BrentAllsop** [comment]
We should also put a check on the DB side.  So if there is a forum thread post, identical to the last one submitted, don't add it to the db, again.

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 @BrentAllsop We have implemented a check on the submit button, once it is pressed it will be disabled so that multiple entries do not get saved in the database.

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia @nalwa @gautamv16 Tested and verified. Working fine now so closing this issue
