### ISSUE TITLE
Explain why parent or children camp support will be removed, when joining a camp.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#775]
When you join a camp, if you already support a parent or child camp, to that camp, it gives a warning that the support of those parent or children camps will be removed.

We need to provide an explanation as to why.

Check with @CanonizerJim to review the language to use for this explanation.

**Comment by sunilspr7** [comment]
@CanonizerJim and @BrentAllsop , kindly share the text to be displayed and I will add it.

**Comment by BrentAllsop** [comment]
@sunnyjindal, could you find all the current e-mail text, currently being used in the system, and post it here.
Then @CanonizerJim and I can propose modifications to that.

Does that make sense?

**Comment by sunnyjindal** [comment]
Sure Brent. I shall do that on Tuesday.On Fri, Oct 1, 2021 at 7:02 PM,             Brent Allsop ***@***.***> wrote:
@sunnyjindal, could you find all the current e-mail text, currently being used in the system, and post it here.
Then @CanonizerJim and I can propose modifications to that.
Does that make sense?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/the-canonizer/canonizer.2.0/issues/775#issuecomment-932231659",
"url": "https://github.com/the-canonizer/canonizer.2.0/issues/775#issuecomment-932231659",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BrentAllsop** [comment]
Sorry @sunnyjindal, I intended to ask @sunilspr7, who has been assigned to this issue for this, not you.
thanks all.

**Comment by sunilspr7** [comment]
@BrentAllsop I will create a document of all the emails currently going through the system.

**Comment by sunilspr7** [comment]
[Canonizer Email Templates.docx](https://github.com/the-canonizer/canonizer.2.0/files/7277786/Canonizer.Email.Templates.docx)

Hello @BrentAllsop , I have created the document of the email templates and attached is the same

**Comment by rohit-talentelgia** [comment]
Here is the link to the Email Template document that needs to be followed:

https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit

**Comment by saniatg** [comment]
@BrentAllsop @CanonizerJim 
Please check the content for the message
Case 1. User supporting a child camp and support getting removed from parent camp
Warning : The following camp is a child camp of "test" camp and your support to the parent camp will be removed if you commit this support. You can give support only to either a parent camp or a child camp. You cannot support child and parent camp together.

Case 2. Supporting a parent camp and support getting removed from child camp
Warning : The following camp is a parent camp of "test" camp and your support to the child camp will be removed if you commit this support. You can give support only to either a parent camp or a child camp. You cannot support child and parent camp together.

**Comment by BrentAllsop** [comment]
@dakshiffort and @CanonizerJim, can you review this new copy defing "parent" and "child" to be great, then once reviewe

When adding support to a new camp, if you already support a parent or child camp of the new camp, this results in stacked support.  Stacked support provides contradictory information and defeats the purpose of Canonizer.  Grand parent, great grand parent and so on camps are all considered "parent" camps.  Similarly grand child and great grand child camps are all considered "child" camps.


Case 1 already supporting parent camp:
(new camp name) is a child camp to (old parent camp name), so if you commit support to (new camp name) the support of parent camp (old parent camp name) will be removed.

Case 2(single) Already support 1 child camp:
(new camp name) is a parent camp to (old children camp name), so if you commit support to (new camp name) the support of the child camp (old child camp name) will be removed.

Case 2(list) Already support multiple child camps:
(new camp name) is a parent camp to this list of children camps.  If you commit support to (new camp name) the support of the camps in this list will be removed.

**Comment by rupalichavan9860** [comment]
@BrentAllsop What should be the warning in following scenario
Right now user is supporting " test camp 4" and created sub camp under " test camp 4"  i.e "Test camp 4 sub camp 4" and again created sub camp under "Test camp 4 sub camp 4" i.e "sub camp" and trying to support "sub camp"

![image](https://user-images.githubusercontent.com/40416610/137126336-92417c9a-04e9-4215-a568-f798dc93a240.png)

**Comment by dakshiffort** [comment]
Hello @BrentAllsop from a flow point-of-view, the statement is correct. I've made minor punctuation edits at some places. @sunnyjindal 

When adding support to a new camp, if you already support an existing parent or a child camp of the new camp, this results in stacked support. Stacked support provides contradictory information and defeats the purpose of Canonizer. Grandparent, great grandparent and similar camps are all considered "parent" camps. Similarly, grandchild and great-grandchild camps are all considered "child" camps.

Case 1: Already supporting a parent camp: (new camp name) is a child camp to (old parent camp name), so if you commit support to (new camp name), the support of the parent camp (old parent camp name) will be removed.

Case 2(single) Already supporting a child camp: (new camp name) is a parent camp to (old children camp name), so if you commit support to (new camp name), the support of the child camp (old child camp name) will be removed.

Case 2(list) Already supporting multiple child camps: (new camp name) is a parent camp to this list of child camps. If you commit support to (new camp name), the support of the camps in this list will be removed.

**Comment by sunnyjindal** [comment]
Hi @BrentAllsop @CanonizerJim Please have a look at the copies and let @dakshiffort know if this looks good.

**Comment by CanonizerJim** [comment]
Brent and I both think this looks good!

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested.
Already supporting a parent camp
Already supporting a child camp
Already supporting multiple child camps
This are just the cases for our understanding. Can you please remove the same from warning messages

![image](https://user-images.githubusercontent.com/40416610/139409836-485cea88-ecd8-477a-af9b-3e4f47e64df2.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified. Working fine now

**Comment by rupalichavan9860** [comment]
Verified on production
