### ISSUE TITLE
Nick name Visibility Status(Public and Private) feature

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#776]
We have not implemented this feature yet. As of now functionality of public and private nick names are same
@BrentAllsop Can you please provide requirement for this

**Comment by kshitij1326** [comment]
Based on the discussed approach, I have implemented the functionality. 
Desired Output: If the user's nick name is Private, then on click of nickname the user's profile details will be hidden and only the supported camp will be visible.

**Comment by rupalichavan9860** [comment]
@kshitij1326 @gautamv16 Tested and verified
