### ISSUE TITLE
Data Could Not Be Found on What's New at Canonizer links

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#777]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Go to What's New at Canonizer block 
3. Click on "Check it out!" link  and "It's Not a Hard Problem; It's a Color Problem" link or  "It's Not a Hard Problem; It's a Color Problem" image

Actual Result  : 

![image](https://user-images.githubusercontent.com/40416610/134798382-a60052fc-9c40-4084-911b-499a27b90d72.png)

**Comment by aliahmad45** [comment]
@gautamv16 , @rupalichavan9860 

"What's New at Canonizer block" section's content dynamically change from the admin portal. The person who has changed this content, he has to put correct path of video or image to see the content.


How to change the content/path:
1. Login as admin on [staging](https://staging.canonizer.com/admin/login)
2. go to video podcast option.
3. Chang the link.

I have attached the image for your reference
![What's New at Canonizer block ](https://user-images.githubusercontent.com/90698926/135253213-04120941-6e28-46c3-8dd2-ad29ab665867.png)

**Comment by rupalichavan9860** [comment]
@gautamv16 @aliahmad45 Still getting this issue as folder videos/consciousness is not available on staging

**Comment by BrentAllsop** [comment]
Thanks @rupalichavan9860, for making sure things like this get fixed.

**Comment by rupalichavan9860** [comment]
@BrentAllsop @CanonizerJim Tested and verified. Working good now so closing this
