### ISSUE TITLE
 Users are not able to reorder the camps ,when joining a camp on a phone

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#778]
Precondition : 
User must be logged in on phone
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Try to support camps by reordering them
4. Observe results

Expected Result : 
User should able to drag and drop /reorder camps of their choice

Actual Result  : 
 Users are not able to reorder the camps

**Comment by rupalichavan9860** [comment]
@aliahmad45 Tested and verified on android and iPhone device and working fine so closing this

**Comment by rupalichavan9860** [comment]
@aliahmad45 UI is getting disturbed in case of reordering and user is able to drag and drop anywhere on the page due to which sometimes all camps are getting disappears so reopening the issue

**Comment by saniatg** [comment]
Please refer attached screenshot for the UI issue
![781](https://user-images.githubusercontent.com/91254708/137129258-4b5859c1-3c8a-467d-9473-ef12e8444066.jpeg)

**Comment by saniatg** [comment]
@HamzaBinMansoor Still facing issues 
1- issue is the design gets unaligned when dragging the supported camps
2- The camps are being dragged anywhere in the screen due to which the camps disappear from the list
Video files to describe the issues  are not uploading . I have shared the same in the skype group

**Comment by saniatg** [comment]
@HamzaBinMansoor 
Issue 1 is fixed
Issue 2- is not fixed , the camps are disappearing when dragged

https://user-images.githubusercontent.com/91254708/138873238-918d2971-e12a-44fe-8e91-3e18998101fa.mp4

**Comment by saniatg** [comment]
@rupalichavan9860 Camps are not disappearing now. Looks stable . Please confirm

**Comment by rupalichavan9860** [comment]
@saniatg @gautamv16 Tested and verified. Working fine now so closing this
