### ISSUE TITLE
There is an issue with the supports page

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#78]
The "John Gregg" camp, should be second, but is showing up 3rd here:
http://production.canonizer.com/user/supports/1?namespace=13

The support order is listed, correctly, here:]
http://production.canonizer.com/support

And the algorithm (one person one vote) is being calculated correctly for topics like:
http://production.canonizer.com/topic/81-Brent-Allsop/3?
Notice the the nickid keithsharris, has 0.13, indicating it is the correct 3rd choice.

**Comment by gautamv16** [comment]
@BrentAllsop please check this. Test this as per different cases you have.

**Comment by BrentAllsop** [comment]
Briefly verified, closing this.
