### ISSUE TITLE
Add times to forum activities, with the date.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#780]
there are dates included for thread creation date and thread post date.
Let's include the times also, with these.

And as with all other times displayed in Canonizer, don't convert from Unix time till the data gets to the browser, and do it based on the browser's local time zone setting.

When we add the ability to edit forum posts, we will need to add the last edited date/time, along with the created date/time.

**Comment by nalwa** [comment]
@akuks @gautamv16  @rupalichavan9860 @BrentAllsop   i was working on this task  and my findings  On Thread creation & Post/Comment creation are:
1. Date & time format saving in DB is not UNIX its DATETIME format as - "2021-10-01 08:38:58"
2. And time saving in DB is not correct as per testing on my local system

Please check and verify this on staging database.

I have displayed time as described by @BrentAllsop  but if data in DB is wrong then it will display incorrect time.

**Comment by akuks** [comment]
Yeah, in forum, it is the MySQL timestamp (I can take the blame of it of not being consistent). And it is time saved on the server. Not in the IST. I think we need to add this functionality also. Where we change the time as per the location.

**Comment by akuks** [comment]
Time is in the UTC in the new server. I will check the old server. 
New server TZ `(Fri Oct  1 12:46:47 UTC 2021)`

**Comment by nalwa** [comment]
@akuks  have you changed the Mysql Date time into UNIX on staging and production?
I guess it needs to be done before code deployment.

I am saving time as UNIX format on thread and forum post so Date format needs to be changed in DB.

**Comment by akuks** [comment]
@nalwa No, it will done after the code is deployed to staging. Otherwise things will stop working on staging.

**Comment by rohit-talentelgia** [comment]
@akuks 

If you can write the migration for the database update it will be helpful.

**Comment by akuks** [comment]
Migrations completed and applied to staging.

**Comment by nalwa** [comment]
@akuks As i can see migration are only added for **Thread** table, it also needs to be added for **post** table.

**Comment by rupalichavan9860** [comment]
@akuks We need actual date and time instead of "n hours" ago so removing ready to test label and moving this to "To do"

**Comment by akuks** [comment]
@rupalichavan9860 a little correction. We need both. 
"Brent updated 10 years ago (Oct 30, 2011, 22:34:45)", where the time is specified in the users selected format and time zone, as specified in their browser.

**Comment by saniatg** [comment]
@akuks the format must be " replied/updated 10 years ago (Oct 30, 2011, 22:34:45) NOT
replied on 3 weeks ago at Thu, Sep 30, 2021, 11:44:54 AM

"Brent updated 10 years ago (Oct 30, 2011, 22:34:45)" this looks good

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified
