### ISSUE TITLE
Mobile Testing : Edit News link is not displaying properly on mobile devices

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#781]
Please refer attached screenshot for more details : 

Responsive mode on laptop : 
![image](https://user-images.githubusercontent.com/40416610/134810664-32762cd2-46eb-4e08-a910-3d97a126a719.png)

Mobile Device : 
![image](https://user-images.githubusercontent.com/40416610/134810776-cb1b1543-cd2a-4144-8632-d4f413ac7c15.png)

**Comment by rupalichavan9860** [comment]
@aliahmad45 Still not displaying properly for responsive devices

![image](https://user-images.githubusercontent.com/40416610/137130517-e819e58d-2afc-4069-9f61-a7b308765df0.png)

**Comment by rupalichavan9860** [comment]
@aliahmad45 Still facing issue for iPhone 5/SE and Galaxy Fold

**Comment by saniatg** [comment]
@rupalichavan9860 verified on iPhone 5s/ and galaxy fold . The issue is fixed now. Please confirm and close .

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Issue is fixed on .Checked on all mobile devices . But order is not correct for some devices like in Galaxy S5 delete news link is displaying first

**Comment by rupalichavan9860** [comment]
@aliahmad45 Tested .links are displaying in one line now but on some devices "Delete News" link is displaying first . Please refer attached screenshot 

Devices : 
Moto G4,Galaxy S5,iPhone 5/SE and Galaxy Fold
![image](https://user-images.githubusercontent.com/40416610/138871302-5ea32483-6557-427e-b858-08a444ac504f.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have again tested this issue , and links are displaying in correct order now for all devices .You can close this issue now

**Comment by rupalichavan9860** [comment]
@aliahmad45 @Wajeeha1995 Tested and verified
