### ISSUE TITLE
Crypto Verification : Minor spelling case change

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#782]
I found some non-uniform in spelling cases

Please refer attached screenshots

![image](https://user-images.githubusercontent.com/40416610/134811815-d5db7bf3-e23b-4152-965f-64123ec2c9a1.png)

![image](https://user-images.githubusercontent.com/40416610/134811907-1b46dcf0-ce45-4ca2-b909-f454f1972c3f.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860  - Correct display of "MetaMask" word in this way. Reference website -  https://metamask.io

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified
