### ISSUE TITLE
Topic Name should not come while objecting

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer.2.0#784]
I found an issue while reviewing the application as below:

![image](https://user-images.githubusercontent.com/8575740/134924023-5859df47-5bfa-4654-a8a1-b87f69375ef4.png)

When we Manage/Edit a Current Topic Record, and while objecting to any statement, we should not get the option of the Topic Name field as it does not actually update the Topic Name. 

![2021-09-27 19_35_37-Canonizer](https://user-images.githubusercontent.com/8575740/134924618-309eb871-feb9-40c9-a882-185aa4e47f2f.png)

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia Previously this topic name /camp name/ statement field was disabled/grayed out on objection page
@BrentAllsop Can you please confirm. Do we want to remove it or keep as disabled

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 I think, keeping it disabled/read only will work.

**Comment by sunilspr7** [comment]
Ticket Complete with following:
1. Topic Name /Camp Name / Statement Name field is disabled while objecting
@gautamv16  I have Completed the ticket and created PR for same, please merge and make it available for testing.

**Comment by rupalichavan9860** [comment]
@sunilspr7 @gautamv16 @BrentAllsop Can we do the same changes for parent camp field also on camp objection page. 
As of now user is able to select another parent camp on camp objection page but it's not getting changed after submission

**Comment by BrentAllsop** [comment]
Thanks @rupalichavan9860   Yes, let's include that change also, before closing this.  You should not be able to change anything like that.  Just objecting, and providing a reason for objecting.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thanks for the quick response and confirmation. As this needs to fix too, I am reopening this

**Comment by sunilspr7** [comment]
@rupalichavan9860  - Condition also applied on parent camp in camp objection page. Now user is not able to select another parent camp on camp objection page.

**Comment by rupalichavan9860** [comment]
@sunilspr7 @gautamv16 Tested and verified. Working fine now so closing this issue
