### ISSUE TITLE
Page is crashing and giving error- Refer video for steps 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#787]
Steps: 
1-Create a topic and 2 sub camps 
2- Give a support to any sub camp from another user
3- Now Edit  the camp in parents camp field add any sub camp
4-Commit the changes
5-The update will show in yellow which is 'In Review'
6- Click on button'View this version'

Actual Result- after 4-6 seconds page will crash
Expected result- Version should be viewed
[Screen Recording 2021-09-29 at 3.45.30 PM.mov.zip](https://github.com/the-canonizer/canonizer.2.0/files/7251587/Screen.Recording.2021-09-29.at.3.45.30.PM.mov.zip
![Screenshot 2021-09-29 at 12 03 52 PM](https://user-images.githubusercontent.com/91254708/135263350-7a9fa298-8cc9-4fe6-964d-865ff105485c.png)
)

**Comment by rupalichavan9860** [comment]
Adding Scenario for this as @saniatg is not able to reproduce the scenario
1. Go to any camp who is having sub camp
2. Click on Manage/Edit This Camp
3. Click on Submit Camp update based on this
4. Select "Parent camp" as sub camp/child of current camp
5. Click on Submit Update

**Scenario is " Select child camp of current camp as a Parent Camp on camp update page"**

![image](https://user-images.githubusercontent.com/40416610/135497006-85348e44-b489-484f-92e7-a37c2a154940.png)

**Comment by nalwa** [comment]
@gautamv16  @BrentAllsop  @rupalichavan9860  as per the scenario: **"Select child camp of current camp as a Parent Camp on camp update page"**

Page is crashing as already mentioned in ticket.
But, Is it logically correct to select child camp as a parent camp on Camp Update ?
According to me its not logically correct as well from coding point of view it will go in infinite recursive loop which is resulting in page crash (out of memory error).

**Solution**: To avoid this we have to restrict child camp to appear in the  "Parent Camp" dropdown list.

Please correct me if i am wrong on this
Or, explain more if it is required feature in the application.

**Comment by rupalichavan9860** [comment]
@nalwa I added steps to reproduce the issue as @saniatg was not able to reproduce
and yes as per requirements user can select any camp as a parent camp
@BrentAllsop Please confirm ?

**Comment by BrentAllsop** [comment]
@rupalichavan9860 , not sure what you want me to confirm here for the "For Brent" tag.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Need confirmation on this :  can user can select any camp as a parent camp(e. g if "camp1" is parent camp of "camp2" , can "camp2" will be selected as parent of "camp1" )

**Comment by gautamv16** [comment]
@nalwa @rupalichavan9860 lets give a message to user instead of page crash. There must be a validation message that user cant do this change.

**Comment by rohit-talentelgia** [comment]
@gautamv16 

We suggest that we should not show the child camps in the dropdown list rather than showing the validation message. Please confirm.

**Comment by rupalichavan9860** [comment]
Getting this page crash in one more scenario : 

When "camp1"  parent camp modified to  "camp2"  which is in review record
and again trying to select "camp1" as a parent camp of "camp2"
![image](https://user-images.githubusercontent.com/40416610/138318985-4bd37784-a7f6-4a8c-8d48-ef26ce48bb49.png)

**Comment by BrentAllsop** [comment]
@nalwa it looks the issue for me has been resolved, so I am going to remove the "for brent" lebal.
If there is still an issue, let me know.

**Comment by rupalichavan9860** [comment]
@sunilspr7 I am still getting page crash . Please refer below screenshot

![image](https://user-images.githubusercontent.com/40416610/142620656-3dfd28df-3da3-4710-adf8-c3b044b45d7d.png)


Steps to reproduce : 
I have created below camp levels
![image](https://user-images.githubusercontent.com/40416610/142625172-f7616fe2-dd6b-46d8-864b-ccf0d818891c.png)


And trying to change parent camp of "camp 2" from "camp 3" to "1"

**Comment by rupalichavan9860** [comment]
Scenario : 
Previously Camp 1 , Camp 2, Camp 3 are on same level (child camp of agreement camp), then
1.  I changed parent of "camp 2 " to "camp 3"
2.  changed parent of "camp 3" to "camp 1"

**Comment by saniatg** [comment]
Tested and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
