### ISSUE TITLE
Create a default nickname, while registering a user in the application.

### ISSUE THREAD

**Issue by ashish76** [the-canonizer/canonizer.2.0#788]
This feature is to provide flexibility to the user in case if she/he forgot to create a nickname before creating a topic or a camp.
A user can create a nickname anytime in case if she/he wishes to have multiple nickname.

**Requirement:**
1. The system will create a default nickname of the user during the registration process.
2. The system will take the first name and last name of the user and concatenate them with the hyphen (-) to generate a nickname.
3. The nickname will be unique. In case a nickname already exists, then the system can put some kind of intelligence to make it unique. A possible option could be 
- Append user-id
- Append running serial number
This is not yet finalized.

@BrentAllsop Please have a look at the requirement and put your feedback or suggestions if any.

**Comment by ashish76** [comment]
This feature has been implemented
Now the default nickname will be created while registering a user in the application. 
Nickname will be the combination of first name and last name, concatenated with the "-" sign.
If the nickname already exists then a random 3 digit number will be appended at the end of the nickname.

A unit test case has been created for this to verify the functionality. To run the unit test case please use the below command 
./vendor/bin/phpunit ./tests/Feature/RegisterUserTest.php

@rupalichavan9860: Please test this feature and let me know any queries.

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified.
