### ISSUE TITLE
Submitted change is getting committed by clicking on View this version

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#789]
When user submits any change to camp/topic and click on View this version, submitted change is getting committed

**Comment by aliahmad45** [comment]
@rupalichavan9860 
when user changed the statement and click on "submit update"  button then changes are committed at this point.
Changes are not committing by clicking on "view this version". "View this version" only redirect to user to statement page.

**Comment by rupalichavan9860** [comment]
@aliahmad45 Yes "View this version" only redirect to user agreement page. but when user click on "View this version" without committing changes and again go to history page , user can't see "Edit change" "commit change" buttons 

this is happening because when user click on "View this version" as of date filter is getting applied
when user change this filter to Default then only  user can see  "Edit change" "commit change" buttons

**Comment by HamzaBinMansoor** [comment]
![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/79147323/135973852-ae700b37-f7cc-4ce2-a1ec-6d2ef3f3042b.png)

As Discussed in the Scrum Meeting:
**Count Down Time** **Edit Change** and **Change Commit** should be shown whatever the filter (Include Review, Default, As of Date) is selected on Camp Screen.
Currently It only Shows in case when **As of Date Filter** is selected

**Comment by BrentAllsop** [comment]
@HamzaBinMansoor, Let me know what I can do, for the "For Brent" label.  If you understand, and you no longer need my help, could you remove that label?
thanks.

**Comment by saniatg** [comment]
@rupalichavan9860 Verified the task and is working fine . Please confirm at your end .

**Comment by rupalichavan9860** [comment]
Tested and verified. Working fine so closing this issue
