### ISSUE TITLE
Cached pages are interfering with updates in Safari

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#79]
In a Safari browser, we were looking at a atopic page with one supporter. Someone else on another browser removed that support, but it didn't show up in the Safari browser, indicating the page was cached. 

We need to find out how to tell a Safari browser not to cache dynamic pages like this one. 

Emptying the cache doesn't solve the problem. There appears to be some server-side state that is not being cleared. We also saw a similar problem when going to topic 129 with no support, yet the support for the topic was the same value as the total support for the consciousness topic.

**Comment by BrentAllsop** [comment]
Not sure if this is related, but sometimes, on the left bar navigation menu, the incorrect page will be green.  (i.e. the "Help" link will be green, when not on the help page.)

**Comment by gautamv16** [comment]
@CanonizerJim can please retest again now.

**Comment by BrentAllsop** [comment]
@CanonizerJim,
I don't know a way to reproduce this, so am going to assume this is fixed, and close it.
As I indicated in the engineering meeting, this morning, we all need to carefully watch for any evidence that this issue might still exist.
If anyone sees any evidence, whatsoever, we need to collect as much data as possible about exactly what was going on, and exactly what happened, and enter that here.
If we see any evidence, we need to re-open this issue, and spend more time trying to reproduce the problem in a reliable way.
