### ISSUE TITLE
Delegated support is not getting removed when supporter removed their support from camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#790]
Please refer attached screenshot 
refer topic : https://staging.canonizer.com/topic/290-Test-issue-749/1-Agreement

![image](https://user-images.githubusercontent.com/40416610/135332225-7796c9f0-2fc6-467a-873d-98167100e265.png)
 
![image](https://user-images.githubusercontent.com/40416610/135332125-f5778e62-9917-4fe7-98ea-1649d50c5399.png)

**Comment by nalwa** [comment]
@gautamv16  @rupalichavan9860  according this ticket my findings and fixes are as:
1. Code for "Removing Delegate supports"  on removal of "direct support" by supporter was not there.
2. So, code was added to remove the delegate support if support is removed by direct supporter.
3. Code written to re-order the "Support order/preferences" on removal of delegate support.

**Comment by rupalichavan9860** [comment]
@nalwa Tested . direct delegate support is getting removed but sub level delegate support is not getting removed
Please refer attached screenshot

For below topic "RC" is direct supporter and "Rupali Cano" is delegated supporter of "RC" and "Rupali-Chavan" is delegated supporter of "Rupali Cano"

When "RC" removed support from camp , "Rupali Cano" 's support is removed but "Rupali-Chavan" still can see below

![image](https://user-images.githubusercontent.com/40416610/137257367-78706dc5-1ef7-4b2e-bb8f-8cc3e09560c2.png)

**Comment by nalwa** [comment]
@rupalichavan9860  okay i will check it

**Comment by nalwa** [comment]
@rupalichavan9860  @gautamv16   as per findings for sub level delegate, changes needs to be implemented in three cases:

CASE 1:  ON deleting direct support all delegated support including sub-level delegate support should be removed. (AS per this ticket #790)

CASE 2: When reordering the camps while adding support to camp Choice/preference no has to be re-orders for sub-level of delegate support. **(Note: it is fixed for direct delegate support in #749** ).

CASE 3: When any direct supporter re-order the support order of camps from "Supported Camp List " menu under account settings, sub-level of delegates should be re-ordered as well  **(Note: it is fixed for direct delegate support in #749** ).**

Correct me if i am wrong about any of above. Thanks!

**Comment by akuks** [comment]
We need to discuss this ticket on Monday after the standup. I will add it in agenda.

**Comment by rupalichavan9860** [comment]
@nalwa @gautamv16 As per discussed in meeting 
When direct supporter removes their support from camp : 
1. All Immediate (level 1)delegated supporters will become direct supporters of that camp
2. It should send an email to new direct supporters that, they are now direct supporters of the camp as user they were delegating have removed their support from that camp and they can either remove or delegate their support to others

@BrentAllsop Please check and correct me if I am missing something

**Comment by nalwa** [comment]
@rupalichavan9860  @gautamv16 There is one  more thing to add in above 
3.If any delegate supporter remove its support then all its child delegates will become supporter of its removal's  parent Supporter.
Example: If A is direct supporter and B is its delegate supporter  and C is delegate supporter of B. Then if B removes its support the C will become delegate supporter of A.

@rupalichavan9860  @gautamv16  correct me if i am wrong on this.

**Comment by cd-ali-ehsan** [comment]
@dakshiffort

**Comment by nalwa** [comment]
@rupalichavan9860  please test the flow as discussed. Email part is yet not there. once i will get the content i will make email part working as well.

**Comment by dakshiffort** [comment]
@BrentAllsop - Pls consider two options

Option 1: [XYZ Name] has just removed their support from this camp [camp name]. You are now a direct supporter of this camp. To remove or delegate your support from the camp, click [here].

Option 2: You are now a direct supporter of the camp [camp name] as [XYZ Name] has just removed their support. To remove or delegate your support from this camp, click [here].

**Comment by BrentAllsop** [comment]
We need to add the following fixes to the manage “support” page as part of this issue.

1. The "Directly Join or Manage Support" button needs to change to just "Directly Join and Support" if not already a supporter or "Manage Support" if already a supporter.  In the new "Directly Join" case, the new camp is placed at the bottom of the list of supported camps as a temporary change, until the submit button is pressed.  This temporary change is not cleared when the "clear temporary changes" button (see below) is taken.
2. There needs to be a breadcrumbs like line at the top, similar to other pages, with a link to the "Agreement" camp of the topic, with the topic name as the label.
3. All actions, including deletion of support for camps, needs to be temporary on this page, only committed to the DB when the “Submit” button is pressed.  "X"ed camps should only be temporarily greyed out or something, not completely removed, so the deletion can be undone until the "Submit" action is taken.
4. This warning needs to be eliminated: "Warning! You are already supporting this camp. You can't submit support again." and the user should be able to re-order, or delete support, temporarily, until the submit button is pressed.
5. Each camp label on the page needs to be a link to that camp.  If the user follows this link, any temporary edits are “canceled” and the user goes to the selected camp.  If the person selects "open in new window" the temporary changes are not lost in the current window.
6. When the user selects “cancel” they should go back to the camp they came from with no changes to the DB.
7. There needs to be a button to temporarily delete all supported camps, the same as if each one was "X"ed, individually.
8. There needs to be a “clear temporary changes” button which put’s the page back to the way it started.  This button should be grayed out when there are no temporary changes, or the only change is the new camp being added.  This new camp temporary change should not be cleared.
9. If the user does a submit with no camps supported, all currently supported camps are marked as terminated with that same termination date.  In this case, all nick names delegated to him are promoted, and notified of such.  Once all the support is terminated, the user should return to the camp of origin, showing no support.
10. When the submit button is taken, the user should return to the camp of origin, showing the current support (or not if temporarily deleted before it was submitted)

**Comment by BrentAllsop** [comment]
Hi @dakshiffort, after reviewing this good proposal, I realized there are a bunch of things that need to be fixed, and additional information communicated.  You can see these 10 changes in the list, above.  Once all those changes are made, how about something like the following?

1. When a direct supporter removes their support of all camps (see change # 9, above) we should email to all delegates of that nick name with the following:
    a.  “You delegated your support to [xyz nick name] directly supporting [abc name of first choice camp being abandoned] in [abc topic name] topic.  They have entirely removed their support of all camps in this topic, so you have been promoted to a direct supporter in their place.  Direct supporters are expected to participate in the maintenance of camps, including receiving and where necessary, responding to emails regarding the maintenance of directly supported camps.  If you are not able to do this, you can delegate your support to any other camp supporter in the [abc name of first choice camp being abandoned] camp.  Or you can entirely remove your support of all camps here (link to the manage supports page for this topic).”


2. When a delegated supporter removes their support in any camp (either on the camp page, or on the manage support page).
    a.  This marks the delegation record with a termination date, effectively removing all support anywhere in that topic.
    b.  All the people that have delegated support to this removing support nick name, need to be emailed the following message:
    c: “You delegated your support to [xxx nick name] who delegated their support to [yyy nick name] in [abc name of first choice camp being abandoned] in [abc topic name] topic.  They have stopped delegating their support in this topic so your support has been delegated to [yyy nick name].  No other action is required.

All the above nick names and camp names should be links.
No notifications are e-mailed, if the camp support change is only in the order of the camp in the newly submitted support list.

**Comment by rupalichavan9860** [comment]
@nalwa We need to implement the changes suggested by @BrentAllsop and also needs to implement the email part so I am moving this to "To do"

Also I found one issue in this,
When any middle person(delegated) removes their support from camp, immediate delegated person and their delegates are not listing
Please refer below screenshots
User : "Rupali-Chavan" 
Before removing support :

![image](https://user-images.githubusercontent.com/40416610/140920519-0b2e7a64-96b8-49cb-82e3-43b2636a10ea.png) 

After removing support : 
![image](https://user-images.githubusercontent.com/40416610/140920642-73c8ddc0-b6e1-4e3f-bad6-b78fab3b65bb.png)

**Comment by nalwa** [comment]
@rupalichavan9860  okay i will check this.

**Comment by nalwa** [comment]
Hi @BrentAllsop @gautamv16   we have create Document for Canonizer Support System, i am sharing link below:
https://docs.google.com/document/d/1gk5Ihxax7TkEh-LliMgGaW0ma1r6HzcM/edit#

@rupalichavan9860  has also added all the emails Support system already have and should have(new ones).

Please review the DOC if any changes required. Once you will approve the DOC, i will start implementing it.

**Comment by nalwa** [comment]
> Hi @dakshiffort, after reviewing this good proposal, I realized there are a bunch of things that need to be fixed, and additional information communicated. You can see these 10 changes in the list, above. Once all those changes are made, how about something like the following?
> 
> 1. When a direct supporter removes their support of all camps (see change # 9, above) we should email to all delegates of that nick name with the following:
>    a.  “You delegated your support to [xyz nick name] directly supporting [abc name of first choice camp being abandoned] in [abc topic name] topic.  They have entirely removed their support of all camps in this topic, so you have been promoted to a direct supporter in their place.  Direct supporters are expected to participate in the maintenance of camps, including receiving and where necessary, responding to emails regarding the maintenance of directly supported camps.  If you are not able to do this, you can delegate your support to any other camp supporter in the [abc name of first choice camp being abandoned] camp.  Or you can entirely remove your support of all camps here (link to the manage supports page for this topic).”
> 2. When a delegated supporter removes their support in any camp (either on the camp page, or on the manage support page).
>    a.  This marks the delegation record with a termination date, effectively removing all support anywhere in that topic.
>    b.  All the people that have delegated support to this removing support nick name, need to be emailed the following message:
>    c: “You delegated your support to [xxx nick name] who delegated their support to [yyy nick name] in [abc name of first choice camp being abandoned] in [abc topic name] topic.  They have stopped delegating their support in this topic so your support has been delegated to [yyy nick name].  No other action is required.
> 
> All the above nick names and camp names should be links. No notifications are e-mailed, if the camp support change is only in the order of the camp in the newly submitted support list.

@sunnyjindal @BrentAllsop please provide  subject for emails in above cases. Thanks

**Comment by sunnyjindal** [comment]
Hi @nalwa @dakshiffort we will need to discuss it once. Can we discuss the ticket at 3:30pm IST?

**Comment by saniatg** [comment]
@nalwa not receiving the updated mails as discussed above .

**Comment by sunnyjindal** [comment]
Subject 1 : You have been promoted as a direct supporter for Camp - [Camp Name]
Subject 2: Your support has been delegated to [yyy nickname] for Camp - [Camp Name]

@nalwa

**Comment by nalwa** [comment]
@saniatg  please re-test for emails, broken emails are also fixed.

**Comment by nalwa** [comment]
> Subject 1 : You have been promoted as a direct supporter for Camp - [Camp Name] Subject 2: Your support has been delegated to [yyy nickname] for Camp - [Camp Name]
> 
> @nalwa

**Comment by rupalichavan9860** [comment]
We have tested and verified all the points and all are implemented .We have created related tickets separately and assigned "28th release" labels on it so moving this ticket to "Staging approved"

**Comment by rupalichavan9860** [comment]
Verified on production
