### ISSUE TITLE
Layout is getting disturbed on List of All Camp Threads and Posts page when thread name is 100 characters long 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#793]
Please refer attached screenshot:
List of All Camp Threads 

![image](https://user-images.githubusercontent.com/40416610/135510908-cc4bdde0-e136-4242-82d5-1201c592738c.png)

Thread Posts page : 
![image](https://user-images.githubusercontent.com/40416610/135511061-59fa41c8-a491-486e-a221-28c51ad04dd5.png)

**Comment by ashish76** [comment]
This issue has been resolved.
Wrap the content to the next line

@rupalichavan9860 Please have a look and let me know if any issues

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified. Looking nice so closing this issue
