### ISSUE TITLE
We need user warning re: camp edit page about Camp About nicknames and Camp About URLs

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#80]
We'd like to have text that tells users that they shouldn't change the Camp About URL and Camp About nickname edit fields unless they specifically know what they're doing. 

Above the Camp About Url edit field, we should add the following user note:

"The following fields are rarely used and are for advanced users only."

**Comment by gautamv16** [comment]
@CanonizerJim its done and deployed

**Comment by BrentAllsop** [comment]
@gautamv16 @CanonizerJim,
This is working great for the camp record edit form.
But on the create new camp form, it is after the camp url field.
Both "about" fields should be under the note.

**Comment by gautamv16** [comment]
@BrentAllsop solved

**Comment by BrentAllsop** [comment]
@gautamv16 ,
Not seeing this in production, staging, or development yet.

**Comment by gautamv16** [comment]
@BrentAllsop its on all three.

**Comment by BrentAllsop** [comment]
Yup, fixed.
Closing.
