### ISSUE TITLE
Chapter specification argument URL, not working in safari browser.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#802]
This is not a problem with the canonizer 2.0 repository code.
This is a problem with the index.html file located in this repository:
https://github.com/the-canonizer/canonizer-videos

The videos are not contained in that github repository, as they are too large, but they can be downloaded from this directory:
https://canonizer.com/videos/consciousness/  for development work.

Debugging this on a local system is difficult, Brent Allsop has some tricks to do this, like how to start a browser in a mode to allow it to load the required files on a local system.

This is an issue with this URL argument:
https://canonizer.com/videos/consciousness/?chapter=differentiate_reality_knowledge
This works in chrome, but does not work in Safari.
When you try to play the video, after going to that URL, it won't play in Safari.
Everything else works, like just going to https://canonizer.com/videos/consciousness, but some how the argument messes things up in safari.

Brent Allsop has done all the html 5 development of this index.html file, but Brent does not have a safari browser, so has no ability to fix this.

Hopefully you can reproduce the problem, with a safari browser.
If not, contact @BrentAllsop 

If you can fix this, work with @BrentAllsop to do a pull request to the repository, and get this into production.

**Comment by BrentAllsop** [comment]
@HamzaBinMansoor,  There appears to be too much space above the video:
![image](https://user-images.githubusercontent.com/6559312/137751899-02f72a66-9c63-4885-a76d-8433e7369069.png)

The space at the top should be the same as on the sides.
We only have more space on the bottom of the video, for the references.

**Comment by rupalichavan9860** [comment]
Still not working so moving this to "To do"

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor Tested. Everything is working fine but found 1 layout issue on mobile devices 

Issue : On mobile devices footer content is left aligned. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/143993347-02879087-f3aa-4b0f-8c86-6d18d8f3c2c9.png)

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor Also getting "Oops! Data Could Not Be Found" issue on privacy policy and terms & services , Created new issue #955

**Comment by HamzaBinMansoor** [comment]
I have added a comment on #955 

> @HamzaBinMansoor Also getting "Oops! Data Could Not Be Found" issue on privacy policy and terms & services , Created new issue #955

I have added a comment on #955 for that ticket

**Comment by HamzaBinMansoor** [comment]
> @HamzaBinMansoor Tested. Everything is working fine but found 1 layout issue on mobile devices
> 
> Issue : On mobile devices footer content is left aligned. Please refer attached screenshot
> 
> ![image](https://user-images.githubusercontent.com/40416610/143993347-02879087-f3aa-4b0f-8c86-6d18d8f3c2c9.png)

The structure for this codebase is made in core HTML CSS. I have consulted with our front-end developer. The current Code is not responsive. It is made with a table design pattern.  So please convert it into a separate task(and assign it to me) because this is not related to the issue of the ticket. 

Possible Solution: This should be converted into a responsive div based structure 
@rupalichavan9860

**Comment by rupalichavan9860** [comment]
@HamzaBinMansoor Okay . I will open a new ticket for this

**Comment by HamzaBinMansoor** [comment]
thankyou

**Comment by rupalichavan9860** [comment]
As per discussion I am creating new ticket for footer layout issue

**Comment by rupalichavan9860** [comment]
Verified on production
