### ISSUE TITLE
Email content to be matched with Email Template Document

### ISSUE THREAD

**Issue by rohit-talentelgia** [the-canonizer/canonizer.2.0#805]
All the emails being sent from the website needs to be audited and to be matched with the email template document given below:

https://docs.google.com/document/d/1xpdJ9XHs7FgZkJth9NE4chhTBR73p9XY_iu5S6OQLYg/edit

**Comment by saniatg** [comment]
Sharing my findings related to the email content in the doc file
[Email issues.docx](https://github.com/the-canonizer/canonizer.2.0/files/7293655/Email.issues.docx)

**Comment by rupalichavan9860** [comment]
@rohit-talentelgia @saniatg This doc is not updated one. We have changed lots of things in email format

**Comment by rohit-talentelgia** [comment]
@rupalichavan9860 so should we not work on matching the content for this document? Is there any updated document of email templates?

**Comment by rupalichavan9860** [comment]
Yes @rohit-talentelgia . Need to update the document before testing
