### ISSUE TITLE
We need to remove the camp title data from the topic page

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#81]
http://production.canonizer.com/topic/129/1

Title is still showing up in the camp record data - e.g. "Title : Is the singularity near?"

Previously, we decided to not use a root camp title field as the root camp title is the same as the topic. This field has been functionally removed everywhere except this location.

**Comment by gautamv16** [comment]
@CanonizerJim its solved. deployed to staging only.

**Comment by BrentAllsop** [comment]
@gautamv16 @CanonizerJim,
Verified and closed this issue.
