### ISSUE TITLE
User should not be able to delegate their support to their delegated supporter

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#811]
Expected Result : 
If "user2" delegated their support to "user1" , then "user1" should not be able to delegate their support back to "user2"

Actual Result : 
As of now  "user1" is able to delegate their support to "user2"(who is already delegating support to "user1")

Please refer attached screenshot for more details 

![image](https://user-images.githubusercontent.com/40416610/136568607-ea925e36-33e7-4073-b3ea-d12003ba9a34.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 its done. please test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested and verified. Working fine now so closing this

**Comment by rupalichavan9860** [comment]
@gautamv16 As per discussed in meeting user should not be able to delegate their support to  any sub level delegated supporter, So reopening this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested. This is working fine so closing this now,  but some users are not able to delegate their support to others . I have added new issue for this #893

**Comment by rupalichavan9860** [comment]
Verified on production
