### ISSUE TITLE
Page is crashing when trying giving support to the child camps for old topics

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#818]
Precondition: already supporting one child camp
Steps:
1- Navigate to old topic
2- Add 2 sub camps for that topic
3- Give support to 1 sub camp
4- Now try to give support to 2nd sub camp
5- On click submit button page crashed
![Screenshot 2021-10-13 at 1 12 44 PM](https://user-images.githubusercontent.com/91254708/137093201-d19a1b27-479a-4b59-b087-189a89bb0487.png)

**Comment by rupalichavan9860** [comment]
@nalwa @gautamv16 Tested and verified
