### ISSUE TITLE
Support added when modifying topic

### ISSUE THREAD

**Issue by CanonizerJim** [the-canonizer/canonizer.2.0#82]
When we recycled a topic that we were not supporting to turn it into a help page, I was added as a supporter to the root camp by default. This should only happen when you create a new topic, not when you modify a topic.

**Comment by gautamv16** [comment]
@CanonizerJim its solved, please test and close issue.

**Comment by BrentAllsop** [comment]
@CanonizerJim @gautamv16 
Verified and closing.
