### ISSUE TITLE
Users are only able to register through email, but when logging in, the system says that a users can enter a phone number to login as well

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#822]
Login Screen Screenshot : https://prnt.sc/1w3o82t
Register Screen Screenshot : https://prnt.sc/1w3ohlj

**Comment by BrentAllsop** [comment]
We may want to create a new issue for the fact that we need to make the OTP phone system work for anywhere in the world, not just in the US.  And we want to avoid needing to select the phone carrier, if possible.  Need to find some service to do this all over the world.

**Comment by rupalichavan9860** [comment]
I can see Label changed to "Enter Email" from "Enter Email / Phone Number", but error message is not changed 

![image](https://user-images.githubusercontent.com/40416610/139381511-02b2cd21-b942-4617-9701-d8b46596fcb0.png)

And I guess if US mobile number users requests for One Time Verification Code, they are receiving it on verified mobile number, so we should revert this
@BrentAllsop Can you please confirm

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Now error message is showing according to the  label .

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified

**Comment by rupalichavan9860** [comment]
As per Brent's comment I have created new issue for OTP phone system work for anywhere in the world #915. So closing this issue
