### ISSUE TITLE
When user is on Login/Register page ,it should highlight that page ( page active status ) is not showing

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#823]
![Screenshot](https://user-images.githubusercontent.com/92429083/137299869-0e76c75b-779b-48eb-886b-1918d969e0c1.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Its working now . when user is on login/Register page ,it is highlighting that page. You can move this to production now

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
