### ISSUE TITLE
Place holders are missing on all fields (Login /Register page) 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#824]
![Screenshot (1)](https://user-images.githubusercontent.com/92429083/137300741-c5956bb1-f5f6-441d-a297-9dba556ac70a.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have tested this ,and now placeholders are showing on all fields on registration and login page. You can move this ticket on production now

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
