### ISSUE TITLE
For better user experience , when user types passwords for both fields and they don't match , please let user know that don't match before he/she clicks Create account button

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#825]
![Screenshot (2)](https://user-images.githubusercontent.com/92429083/137301798-69fcc6c6-cc89-4102-8e8e-85a18f80058f.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 , @ashish76 
Its working for this screen ,But its not working for other screen where captcha field is not available .I think we should create another ticket for this

**Comment by rupalichavan9860** [comment]
Verified on production
