### ISSUE TITLE
Highlighted text is not readable ,Please change background color

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#826]
![Screenshot (4)](https://user-images.githubusercontent.com/92429083/137303603-44f1149f-e7ab-41bb-83f7-ac23e0de034e.png)
Steps re reproduce : 
1.Go to " https://staging.canonizer.com/create/topic "
2.Fill all mandatory fields and create topic
3.It navigates on topic history 
4.Click on " Submit topic update based on this "
5.Fill all mandatory fields and click on " Submit update " button 
6.Submitter nick name showing in old topic is not readable properly

**Comment by Wajeeha1995** [comment]
Fixed and verified 
Text on this background color is readable now 
![Screenshot (9)](https://user-images.githubusercontent.com/92429083/137724605-57ae8c4d-4c45-4e1e-8b4e-f7ba8bc30b8a.png)

**Comment by rupalichavan9860** [comment]
This is readable but not highlighted , user will only know that it is a link only when user hover mouse on nick name
@BrentAllsop Can you please check this?

**Comment by rupalichavan9860** [comment]
@gautamv16 We can either underline the text or can add external link symbol

**Comment by rupalichavan9860** [comment]
@gautamv16 Need to change this for Objector Nick Name field also on history pages

**Comment by gautamv16** [comment]
@rupalichavan9860 I have added underline to the hyperlink text  and also did same for objector name

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Text is readable and highlighted now. You can close this issue

**Comment by rupalichavan9860** [comment]
@gautamv16 @Wajeeha1995 Yes. Tested and verified .Closing this issue
