### ISSUE TITLE
Alphabet is cutting in date field  and spacing is not equal from left and right 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#827]
Steps to reproduce : 
1.Got to " https://staging.canonizer.com/browse "
2.Check date field 
![Screenshot (5)](https://user-images.githubusercontent.com/92429083/137308204-49787fc7-8fc1-4aa7-a351-8fda02d10685.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified from my end .You can move this to production

**Comment by rupalichavan9860** [comment]
Verified on production
