### ISSUE TITLE
Complete content is not showing on supported camp page

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#828]
Steps to Reproduce : 
1.Go to " https://staging.canonizer.com/topic/371-Smoke-testing/1-Agreement 
2.And click on " Directly join or manage support " button 
3.Attached content is showing on this page 
![Screenshot (6)](https://user-images.githubusercontent.com/92429083/137311098-ce87182b-1101-4cde-b836-8bd78731a8ea.png)
4.Click on " Nick names " it navigates to  https://staging.canonizer.com/settings/nickname
5.Now click on " Supported camps " ,it navigates back to https://staging.canonizer.com/support .content which is showing in step
3 is not showing here 
![Screenshot (7)](https://user-images.githubusercontent.com/92429083/137312459-c9c6f079-a5e3-42d2-bdbe-5379f6997471.png)

**Comment by gautamv16** [comment]
@Wajeeha1995 are you talking about the nickname dropdown section content?
![image](https://user-images.githubusercontent.com/6199964/137597664-103dc478-c91f-46ad-a98c-3e05d54adfb1.png)

**Comment by rupalichavan9860** [comment]
@Wajeeha1995 This is not an issue. on 1st screen user is supporting camp and 3rd screen is displaying supported camps
