### ISSUE TITLE
All nick names are not showing in nick name drop down on " Create new camp " page 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#829]
Steps to Reproduce : 
1.Go to  https://staging.canonizer.com/browse
2.Select  /sandbox testing/ Smoke testing
3.It navigates to https://staging.canonizer.com/topic/371-Smoke-testing/1-Agreement
4.Click on  " Start new supporting camp here " 
5.It navigates to https://staging.canonizer.com/camp/create/371-Smoke-testing/1-Agreement
6.Click on Nick names drop down , and observe that all nick names are not showing 
7.But if you check this  https://staging.canonizer.com/settings/nickname ,we have 3 nick names in the list
![Screenshot (8)](https://user-images.githubusercontent.com/92429083/137314669-53d7cd6d-84aa-4d41-bbf1-5a3acc14ff02.png)

**Comment by Wajeeha1995** [comment]
Fixed and verified 
Now all nick names are showing in "Nick name " drop down " on creating new camp .

**Comment by rupalichavan9860** [comment]
@gautamv16 Previously it was working according to the functionality, can you please revert the changes

**Comment by gautamv16** [comment]
@rupalichavan9860 changes reverted

**Comment by saniatg** [comment]
Working fine now, the changes are reverted . For the first time all nick names will show when supporting/creating a new camp after that only that nick name will show with which the first camp was created/supported , all will not populate. @rupalichavan9860 Please confirm and close.

**Comment by rupalichavan9860** [comment]
@gautamv16 @saniatg Tested and verified.
