### ISSUE TITLE
Add a button's to remove and delegate support on camp pages.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#831]
We should have a "Delegate Your Support" button, like this one:
![image](https://user-images.githubusercontent.com/6559312/137652895-c17879b8-ac80-41ef-8411-624a788ef3dd.png)
Even when you are already supporting a camp like here:
![image](https://user-images.githubusercontent.com/6559312/137652922-bee0d1a3-4e7b-457e-9941-77ac91557c48.png)

There should be a "remove support" button, for yourself, and a delegate support button for all other supporters (except delegated supporters to your nick name)

**Comment by saniatg** [comment]
@nalwa Button to remove and delegate support on camp pages is looking good but there is a case where buttons should not show for non logged in users.
When user directly supports a camp  : button 'Remove your support ' is seen which is correct , now copy the URL and logout the app.
Now paste the URL in other tab, non logged in user sees button as 'Delegate your support ' , which is incorrect . For non logged in users, button should not be seen. When login then condition must be checked to show 'Delegate your support' OR 'Remove your support'

**Comment by nalwa** [comment]
@saniatg  i will fix it.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
