### ISSUE TITLE
After resetting password , error occurred when user try to login with new password. 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#832]
Steps to reproduce :
1.Go to https://staging.canonizer.com/login
2.Click " Forget Password "
3.Enter valid Email and submit
4.Reset link receive on submitted email 
5.Click on " Reset Password " 
6.It will navigate user to https://staging.canonizer.com/resetpassword/d2FqZWVoYTExQG1haWxpbmF0b3IuY29t
7.Fill all mandatory fields and click on " Reset " button
8.It logins the user 
9.After logging out ,this error occurred ( error mentioned in attached screenshot )when user try to login with changed password 
![Screenshot (9)](https://user-images.githubusercontent.com/92429083/138049105-c2088dd5-5782-4d82-9fb4-1a4ce7c87096.png)

**Comment by Wajeeha1995** [comment]
If account is not verified and user trying to login with new pass, user should receive One time verification code

**Comment by ashish76** [comment]
@Wajeeha1995 I tried to replicate this issue on staging.canonizer.com and it is working as expected. 
There is no error. I have followed the exact steps that you mentioned. I am assuming that the reset password you tried for the user, is a verified user.

**Comment by Wajeeha1995** [comment]
@ashish76  Not its not for the verified user , If account is not verified and user trying to login with new pass after changing password and error display on the screen , Is it possible that we add option for One time verification code on this screen so that user  receive One time verification code ?

**Comment by ashish76** [comment]
After discussion with the above comments, it has been decided to implement a new feature to resolve this issue. A new ticket for the same has been created #865
