### ISSUE TITLE
When user is resetting passwords make sure to provide a confirmation on site page as well that clarifies user that his password is changed. Right now there is no confirmation at both sides and If I try keep logging after changing password , it lets me login w/o  any further validation Or notification

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#833]
Steps to reproduce :
1.Go to https://staging.canonizer.com/login
2.Click " Forget Password "
3.Enter valid Email and submit
4.Reset link receive on submitted email 
5.Click on " Reset Password " 
6.It will navigate user to https://staging.canonizer.com/resetpassword/d2FqZWVoYTExQG1haWxpbmF0b3IuY29t
7.Fill all mandatory fields and click on " Reset " button
8.It logins the user without giving any confirmation message that " Password has been changed successfully "

**Comment by ashish76** [comment]
@Wajeeha1995 Based on your comment above I have displayed the success message once the password has been reset successfully. 

Regarding the confirmation, before submitting the form, we need to submit the form using javascript which does not advisable. In version 3.0 we are going to implement API-based communication. We can implement it at that time. 

@gautamv16 Please suggest.

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
