### ISSUE TITLE
Session time out on forum pages causes crash.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#836]
If you are editing a new submission to a forum thread, then your session times out, you get a fatal error  (TokenMismatchException) that should be handled more gracefully.  (hopefully, recover data being submitted?)

in VerifyCsrfToken.php line 68

![image](https://user-images.githubusercontent.com/6559312/138178609-466982d6-8f1e-4f49-b5aa-0273db4a6dd4.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
