### ISSUE TITLE
Most Recent Post Date column : replied on date is missing 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#837]
When user creates a post to any thread , "replied on" date is displaying as blank. Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/138215463-60a88516-7f7c-4fac-a201-90cec6a0e7e5.png)

![image](https://user-images.githubusercontent.com/40416610/138215487-f980eaad-6dd3-441d-8938-bfe0df011832.png)

**Comment by akuks** [comment]
#780 causes this issue. I guess
Not sure, if the code of #780 is deployed on prod. Checking this

**Comment by nalwa** [comment]
@akuks  migrations need to be added for post table, as you added them for thread table.
its not because of code, i think DB fields are not updated for post table.

**Comment by akuks** [comment]
@rupalichavan9860 This is fixed. Please test it.

**Comment by rupalichavan9860** [comment]
@akuks Tested and verified.
