### ISSUE TITLE
Link text for login should be uniform at all places

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#839]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/138220126-47efe560-3355-4ad0-8542-7631cfac9143.png)

![image](https://user-images.githubusercontent.com/40416610/138220191-e3c2273f-748a-43af-b7a3-7d8753ea5a6b.png)

**Comment by aliahmad45** [comment]
@rupalichavan9860 can you mention what will be the text ? Log in or Login

**Comment by rupalichavan9860** [comment]
@aliahmad45 I think "Log in" looks good

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Text is not same , button is  showing **log in** but title is showing **login**

**Comment by rupalichavan9860** [comment]
@aliahmad45 Can you please make it uniform

**Comment by aliahmad45** [comment]
@rupalichavan9860  ok. i'll do it

**Comment by rupalichavan9860** [comment]
@aliahmad45 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
