### ISSUE TITLE
Support tree not shown when one supporter.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#84]
On topics with only one supporter, like this sandbox topic:

https://staging.canonizer.com/topic/205?asof=bydate&asofdate=2018/06/19%2023:02:49

It shows in the support section that there is a total support of 1, but doesn't list who it is.

**Comment by CanonizerJim** [comment]
Pending

**Comment by BrentAllsop** [comment]
http://staging.canonizer.com/topic/205
