### ISSUE TITLE
Invalid As Of Date is displaying By default  on Create Share and Update Share page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#842]
By default date is displaying as "010/21/2021"
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/138266390-eceb9e5f-2b4e-48ff-ab2c-c5cc046d0dcb.png)

and giving below error : 
"The as of date is not a valid date."
![image](https://user-images.githubusercontent.com/40416610/138267044-2d486cfc-9a4b-4fe8-98a2-e79d025c70c9.png)

**Comment by rupalichavan9860** [comment]
Also date is not getting updated after updating 

![image](https://user-images.githubusercontent.com/40416610/138267784-e7c23c17-5625-450a-a6b3-4ddf6eba07b6.png)

**Comment by ashish76** [comment]
Fix #842.
Wrong logic to format Day and Month.

**Comment by rupalichavan9860** [comment]
@ashish76 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
