### ISSUE TITLE
JavaScript error on forum pages on live

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#844]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/138315949-21b3787c-2f90-49aa-9ff9-6c28fdaf35c6.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified . Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
