### ISSUE TITLE
Date format should be consistent throughout the application

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#845]
Currently in 'Camp Forum' format is ->dd/mm/yyyy & when upload file it is yyyy/mm/dd

 To keep it uniform we can follow US time format mm/dd/yyyy

![Screenshot 2021-10-22 at 9 25 06 AM](https://user-images.githubusercontent.com/91254708/138456674-711f7f82-575f-4791-95ac-b736ef9ef03d.png)

![Screenshot 2021-10-22 at 6 23 22 PM](https://user-images.githubusercontent.com/91254708/138456698-fbb5755d-f8b5-43d3-9e91-a5e26f58ac1f.png)

**Comment by sunitamary** [comment]
The date format is consistent through out the application in this format  **"Nov 19, 2021"** but not  "US time format mm/dd/yyyy" as mentioned in the ticket. please confirm @rupalichavan9860

**Comment by rupalichavan9860** [comment]
As the date format is consistent through out the application , I moved this to "Staging approved"

**Comment by saniatg** [comment]
@rupalichavan9860 tested and verified on production please confirm

**Comment by rupalichavan9860** [comment]
Verified
