### ISSUE TITLE
Labels alignment issue when window is resized

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#848]
The labels ( In review, Objected ) must be aligned in the straight line with the others 
 Refer screenshot for the issue
![Screenshot 2021-10-05 at 11 51 11 AM](https://user-images.githubusercontent.com/91254708/138651678-53aa9f39-dfd3-445f-a02d-e1b453d32b04.png)

**Comment by saniatg** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
