### ISSUE TITLE
We can host image files on canonizer.com.

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#85]
@CanonizerJim,
I assigned this issue to you.
in the wiki markup help page it says:

"Canonizer does not host image files for posts on its servers, but you can still include an image file in your post if you put the file on a web server and simply insert the URL to that file."

This is incorrect.  On the side bar, there is an "upload file" option people can take to upload files which will be accessible via this url:  http://canonizer.com/files/<file name>

I'm thinking we should have an entire new help page, fully describing this process, titled uploading images for pages, or something.  And only reference that help file, where this statement is in the wiki help page.

**Comment by CanonizerJim** [comment]
Got it. Will change the help page and close the issue.

**Comment by CanonizerJim** [comment]
I won't close it until I've changed the help pages

**Comment by CanonizerJim** [comment]
I've added language to this help page, but I won't close this until I've written a new help page for images.

**Comment by CanonizerJim** [comment]
This is now included in the help page, now titled "Wiki Markup and File Uploads."
