### ISSUE TITLE
Incorrect validations for field Camp About URL 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#850]
I am trying to update camp for field Camp About URL with value "https://www.google.com/" and can see error message  "Camp's about url can not be more than 1024 characters." even if entered characters are 23 only

Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/138658742-cd4c8f90-5dc4-4da2-99c6-aaee2a64a4ec.png)

**Comment by rupalichavan9860** [comment]
@nalwa Tested. Camp About URL is non-mandatory but still I am not able to create camp as is it displaying error message "The camp about url format is invalid." when "Camp About URL " is blank

**Comment by rupalichavan9860** [comment]
@nalwa Camp About URL is accepting more than 1024 characters. can you please check once
Also as of now it is accepting any URL like "test.test". Can you please fix that also

**Comment by nalwa** [comment]
@rupalichavan9860 @gautamv16  @BrentAllsop  please clarify these points:
1. Why character limitation is required as long as we are validating URL.
2.as per @rupalichavan9860  **test.test** is being accepted because it is considered as valid URL. If you need it domain specific like.com,.net, .uk etc. Then please provide the list of domains.

**Comment by rupalichavan9860** [comment]
@BrentAllsop I want to add one more point :  As it is an URL , so we need a link on text which will redirect to that URL

**Comment by nalwa** [comment]
@rupalichavan9860  @gautamv16  @BrentAllsop  Below points are covered:
1. 1024 character limitation is added on field.
2. URL validation added on field (Not domain specific).
3. Link added on URL where is is displayed

**Comment by rupalichavan9860** [comment]
@nalwa I can see some irrelevant data on agreement page Current Camp Record : Camp About URL. Please refer screenshot 
![image](https://user-images.githubusercontent.com/40416610/142360569-364cebce-6503-4b48-a367-fcbc672aa8e7.png)

**Comment by rupalichavan9860** [comment]
@nalwa I found some issues in this : 

1. On Create Camp page field label is "Camp About URL ( Limit 1024 Chars )" and on Camp update page field label is "Camp About URL" - It should be uniform
Please refer attached screenshot : 
Create Camp : 
![image](https://user-images.githubusercontent.com/40416610/142857267-4127a08f-20b4-4451-8b42-940e4e56af42.png)

Camp Update : 
![image](https://user-images.githubusercontent.com/40416610/142857328-ca96d2ff-7b54-42d6-b3c6-25e06b35aded.png)

2. Camp About URL should display as link under "Current Camp Record" section and on "Updated camp record preview" pop up
Please refer attached screenshot 
"Updated camp record preview" pop up : 
![image](https://user-images.githubusercontent.com/40416610/142857594-dba04f65-c5cc-42ca-8073-855da4f36bcf.png)

Current Camp Record : 
![image](https://user-images.githubusercontent.com/40416610/142857716-7cefb744-ebe9-48cf-9290-da2ea574a800.png)

3. Can see "https://" added before link on Current Camp Record but not on history page 

![image](https://user-images.githubusercontent.com/40416610/142858249-3a2e6ee9-ee80-41be-9598-f7755a854c02.png)

![image](https://user-images.githubusercontent.com/40416610/142858317-071058ac-1a65-4446-81a0-ae05bc9a5bc4.png)

4. According to ticket #640 , Need to correct the validation message. As of now it is displaying "The camp about url format is invalid."
![image](https://user-images.githubusercontent.com/40416610/142865303-820d3ce8-b2b5-4ded-aad4-83ac57a0e355.png)

**Comment by sunilspr7** [comment]
Point 1 , 2 and 3rd done.
For Point 4 I will need validation message after that I will update.

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested . Found 1 issue : 
When Camp About URL is blank ,on preview it is displaying as " http://" 
Please find attached screenshot
![image](https://user-images.githubusercontent.com/40416610/143419934-d4857a47-d555-4d93-bff6-e098cc80bde4.png)

**Comment by rupalichavan9860** [comment]
@sunnyjindal Can you please validation message for this field

**Comment by sunnyjindal** [comment]
@rupalichavan9860 you will need to provide more info on what exactly is required. We'll discuss this in our call today.

**Comment by rupalichavan9860** [comment]
@sunilspr7 I discussed with @sunnyjindal  and as agreed upon , we can provide below message 

"The camp about url format is invalid. (Example: https://www.example.com?post=1234)"

**Comment by sunitamary** [comment]
Tested and working but there is an UI Bug, due to text color Blue, the url displays only after hover. Please view the video attached:
 https://share.vidyard.com/watch/mitYgU59cUfsuSAELs7c9N?  @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@sunitamary Other fields you motioned in video are working fine. If user entered those fields while creating/updating camps they are visible on that specific record
  
@sunilspr7 Can we make the text of color as black like "Submitter nick name" so that it will be highlighted on every color

**Comment by sunilspr7** [comment]
@rupalichavan9860  okay I will do it

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested. Link is visible on every color but **underline is missing** ,user need to hover mouse on it then only user got to know it is a link

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested. When user click on link, it is redirecting to that link but on history page underline is missing for that record , needs to reload page to see the underline

![image](https://user-images.githubusercontent.com/40416610/146721368-72cca1cc-b538-4896-9e6a-bab67eba3331.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
