### ISSUE TITLE
Text fields are overlapping and social media link buttons are cutting off on mobile devices

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#851]
**Profile info screen :** 
![Screenshot](https://user-images.githubusercontent.com/92429083/138676666-85654951-0b5f-4664-b339-038c732baa94.png)
**Social Oauth verification Screen :** 
![Screenshot (1)](https://user-images.githubusercontent.com/92429083/138676814-cdf0b5f0-b59f-4df5-ad7f-b7c83f84c6f4.png)
 **Profile info screen in rotate mode :** 
![Screenshot (3)](https://user-images.githubusercontent.com/92429083/138678888-4ec8601b-67e8-4356-b69e-20966c659dec.png)
Topic History screen : 
![Screenshot (4)](https://user-images.githubusercontent.com/92429083/138680279-9c9f1d40-6df1-4453-9a81-b3fecf173d29.png)
**Camp History Screen :** 
![Screenshot (5)](https://user-images.githubusercontent.com/92429083/138681528-8f36b5d3-9f4e-4833-9d96-8d64978585e4.png)

**Comment by sunitamary** [comment]
Tested and working fine. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
I found one minor issue in this . Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/142380964-c0d89b28-ea61-469a-8b81-aa7bebe5920e.png)

**Comment by sunitamary** [comment]
I have found an alignment issue.The object button is not aligned exactly with the other two button. please refer the attached screenshot.
![Screenshot from 2021-11-18 14-18-58](https://user-images.githubusercontent.com/92773405/142385717-b88bd55d-8df4-4cad-aa96-1e42b522e70a.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 .On topic screen ,Text is moving away from text box (Issue produced on Iphone 5. Please check attachment 
![Issue](https://user-images.githubusercontent.com/92429083/143016275-5cee3162-4066-4fe8-8df5-6711fd2f4c5c.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
