### ISSUE TITLE
Some menus form left panels are not getting highlighted 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#852]
When user click on any link from left panel, link colors changes but this is not working for below links

1. Create New Topic

![image](https://user-images.githubusercontent.com/40416610/138681285-009631ae-e282-4629-8610-20696aec27fd.png)

2. Jobs

![image](https://user-images.githubusercontent.com/40416610/138681396-66285fad-861a-40ea-843b-e95446a73e54.png)

3. Algorithm Information

![image](https://user-images.githubusercontent.com/40416610/138681521-fb80beb3-a2a3-4119-9f98-376fee63ee11.png)

**Comment by sunitamary** [comment]
Tested and working fine! @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sunitamary** [comment]
Tested and working fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified on  production
