### ISSUE TITLE
When creating a topic under any 'Namespace" other than General  it automatically changes to 'General' whenever there is any error on the page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#853]
Steps to reproduce:

1. Login and navigate to 'Create Topic'
2. Now add 'Topic Name' which is duplicate or invalid
3. Select any namespace except 'General'. E.g. I choose ' Organizationz' as my namespace
4. Click on 'Create topic' Button
5. Error "Name already exists" shows which is correct 
6. In the namespace field the selected namespace as"Organizationz' changes automatically to 'General ' which is incorrect

Actual Result:  selected namespace as"Organizationz' changes automatically to 'General ' which is incorrect
Expected Result: No matter what error shows while creating topic , the namespace must not change to 'General' it should show the one selected
Refer screenshots below
![Screenshot 2021-10-25 at 4 28 30 PM](https://user-images.githubusercontent.com/91254708/138683853-c34b4be2-ec32-4d9d-82d3-4831288374b0.png)

![Screenshot 2021-10-25 at 4 25 28 PM](https://user-images.githubusercontent.com/91254708/138683859-fd44be95-be93-4f91-8d39-ded3dfdce752.png)

**Comment by saniatg** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested and verified on Production
