### ISSUE TITLE
when user place  cursor on help icon on any mobile device ,it doesn't display any tooltip like showing on web

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#854]
Issue produced on Mobile devices : 
![Screenshot (6)](https://user-images.githubusercontent.com/92429083/138689195-3f89c2ec-d742-4cdb-9a4d-95bb8015af36.png)

On Web : 
![Screenshot (7)](https://user-images.githubusercontent.com/92429083/138689475-734570f0-3c13-41c2-ac73-fbe93ec960c7.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have tested this issue. Its fixed now. You can close this issue.

**Comment by sunitamary** [comment]
The tooltip appears only after clicking the icon on mobile devices. not on hover. @rupalichavan9860

**Comment by Wajeeha1995** [comment]
@rupalichavan9860  I think there is no hover option in mobile but this tooltip appears on the mobile devices when tapping" Please confirm this .

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 .Tested and verified on production .Its working
