### ISSUE TITLE
 Display Text in Add news should accept full stop(.) It is not possible to enter 256 chars without a full stop as per User perspective. 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#855]
Steps to reproduce

1. Login and navigate to any topic created by the user
2. Click on Add news
3. Enter text in 'display text' field with a full stop (.)

Actual Result: Gives error" Only spaces and alphanumeric allowed" when enter full stop(.)
Expected result: Full stop should be acceptable
![Screenshot 2021-10-25 at 5 57 49 PM](https://user-images.githubusercontent.com/91254708/138695296-434d0d16-3e2e-4e01-8dc0-660a4ec45598.png)

**Comment by rupalichavan9860** [comment]
@aliahmad45 Tested. Working fine on "add news" page but need to do same change on "edit news" page also

![image](https://user-images.githubusercontent.com/40416610/142416304-aac4ae2e-751b-4832-9c24-daa6240c1006.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Tested & verified on Production
