### ISSUE TITLE
For safari browser , Crypto verification(Meta mask Account), we should add a text with list of supported browsers.

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#857]
Meta Mask only supports Chrome and Firefox browser. We must add a text for Safari browsers mentioning the list of supported browsers .

**Comment by saniatg** [comment]
@ashish76 The spelling of 'supported' is incorrect
It is displayed as 'suported' instead should be 'supported'
![Screenshot 2021-11-18 at 12 11 06 PM](https://user-images.githubusercontent.com/91254708/142365331-e33480a6-e06b-40f6-956e-2d52aa9d9046.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Tested & verified on Production
