### ISSUE TITLE
Page crash when adding invalid URL in Link field of news

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#858]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to browse and select any topic 
4. Click on Add News 
5. Type any display text and type link like "www.testurl.in" 
6. Save
7. Open newly created news

Actual Result : 
Getting below page crash 
![image](https://user-images.githubusercontent.com/40416610/138852316-f9e4b807-58e1-4fb6-98fc-6c098f7f093d.png)

**Comment by akuks** [comment]
@rupalichavan9860 This is fixed but it is a part of 25th release so it is not in staging yet.

**Comment by akuks** [comment]
@rupalichavan9860 can you please test this

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@ rupalichavan9860 Tested and verified on production. It's working fine.

**Comment by rupalichavan9860** [comment]
Verified
