### ISSUE TITLE
Buttons are overlapping on mobile devices 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#859]
Steps to reproduce 
Go to https://canonizer.com/forum/348-Canonizer3-Topic-Page-Design/3-Topic-Page-by-Code-District/threads
![Screenshot (7)](https://user-images.githubusercontent.com/92429083/138857920-7533c9b1-7246-45e5-ba22-01b2fd2b1319.png)
Issue Produced on : Galaxy fold , iPhone 6, 7,8 plus , S5 , pixel 2 , pixel 2XL

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have tested this .This is working fine now .You can move this to " Staging Approved ".

**Comment by rupalichavan9860** [comment]
Verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 .Its looking fine on production .
