### ISSUE TITLE
Pagination is cutting out of user's view in auto rotate mode 

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#860]
**Steps to reproduce :**
https://staging.canonizer.com/login
![Screenshot (9)](https://user-images.githubusercontent.com/92429083/138861639-07ffb062-7f63-4245-a6d4-83cdb8a940f3.png)
**Issue Produced on :**  Galaxy Fold , Iphone 6,7,8 , Galaxy S5

**Comment by Wajeeha1995** [comment]
@rupalichavan9860.This is working fine. You can move this to Staging approved.

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Its looking fine on production .

**Comment by rupalichavan9860** [comment]
Verified
