### ISSUE TITLE
Need to put some custom message when user enters invalid link in camp statement 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#864]
I have added statement  [1.1.1 The Canonizer] in which 1.1.1 is invalid link. When statement is live and user click on link "The Canonizer" , it is displaying page crash 

![image](https://user-images.githubusercontent.com/40416610/139055254-96531396-6a4e-4b9e-a128-75fe2a4430de.png)

Is there any way to restrict users from entering invalid URL/message when page is redirecting to invalid URL?

**Comment by akuks** [comment]
@rupalichavan9860 can you please add the steps in details to reproduce this issue?

**Comment by rupalichavan9860** [comment]
@akuks Sure. Please find below steps : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Go to any existing topic/create new topic
4. Click on "Add Camp Statement" 
5. Add any link like "[1.1.1 The Canonizer]" in statement field
6. Click on "Submit Statement"
7. Click on added link from statement on Camp Statement History or click on link present in camp statement section from agreement (if newly added statement is live)

Actual Result : 
Getting page crash

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production. Not getting crash on clicking camp statement link

**Comment by rupalichavan9860** [comment]
Verified
