### ISSUE TITLE
Canonized list for is not looking properly for topics who doesn't have any camps under them

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#875]
If topic doesn't have any camps then it is looking like see below

![image](https://user-images.githubusercontent.com/40416610/139376873-c6b0b7c5-a2d3-42d0-883e-f26235c0f7f7.png)

I think this topics also should have blue color rounded box without arrows
@BrentAllsop Can you please confirm on this

**Comment by sunilspr7** [comment]
![Screenshot 2021-10-29 at 15-48-03 Canonizer](https://user-images.githubusercontent.com/6298462/139422680-83dfebd2-96bc-42ce-b579-50560e46efb3.png)

if any topic have no camps then add - icon.

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested . looking nice now but as discussed and agreed by everyone color of icons for topic which have no camps should be grey and tooltip should be "No Children"

@BrentAllsop Can you please confirm. Because in many warnings we have modified "Children" to "Child"

**Comment by rupalichavan9860** [comment]
@sunilspr7 Tested and verified. @saniatg observed one minor issue in this "The default grey icon is looking fine when there is no sub camps but when hover on it shows hand pointer which is wrong as it is not clickable instead show normal pointer" and created new issue for this #895 , so moving this to "staging approved"

**Comment by rupalichavan9860** [comment]
Verified on production
