### ISSUE TITLE
Login --> Tooltip: Helping text for tooltip is cutting out for login & reset passwords sections.

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#876]
Issue Produced on devices : iPhone 6,7,8,X , Galaxy S5 , Galaxy fold
Reset Password Screen:
![Screenshot (20)](https://user-images.githubusercontent.com/92429083/139414976-8915c7ba-aac2-49d4-8beb-ab92f06d90f2.png)

Register Screen : 
![Screenshot (21)](https://user-images.githubusercontent.com/92429083/139414893-158fe6ce-2cbd-41d7-9dd9-094d0cbe52a3.png)

**Comment by saniatg** [comment]
@karun0607gautam Looks fine for registration page but for  reset password page the tooltip is still truncating for screen with width 320 px
Refer screenshot for dimension
![Screenshot 2021-11-18 at 4 52 34 PM](https://user-images.githubusercontent.com/91254708/142406657-febae72b-42dd-457f-9cfa-452c2cd2e7b9.png)

**Comment by vedantvyas0** [comment]
Tested working fine 
@rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested on production. Its looking fine on login and reset password screen .

**Comment by rupalichavan9860** [comment]
Verified
