### ISSUE TITLE
Admin Panel- Incorrect spelling of 'beginning ' word

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#879]
Steps:

1. Navigate to admin panel
2. Click on namespace from left navigation 
3. Create any invalid namespace
4. 

Error will show"Namespace Name may only contain letters, numbers, underscore and backslashes at begining and end only."

Correct spelling is 'beginning' not 'begining
![Screenshot 2021-11-01 at 12 49 22 PM](https://user-images.githubusercontent.com/91254708/139635967-025d3a7b-881f-449b-907e-2fe41b9582f3.png)

**Comment by saniatg** [comment]
@nalwa 
It is fixed when adding a name space but when edit still shows incorrect spelling
![Screenshot 2021-11-11 at 3 15 36 PM](https://user-images.githubusercontent.com/91254708/141276044-c5df679e-a1f7-4de7-845b-d5bce2d7f813.png)

**Comment by saniatg** [comment]
Verified and working fine.

**Comment by rupalichavan9860** [comment]
Verified on production
