### ISSUE TITLE
Register page should have "Login" option/button for existing users

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#88]

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified
But it should be "Already have an account? Login Here" instead of "Already have have account Login Here"

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified
