### ISSUE TITLE
Admin Panel- Incorrect error message when creating a namespace with backslash

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#880]
Steps:

1. Navigate to admin panel
2. Click on namespace from left navigation
3. Create a namespace with backslash(\)

Actual result -Error will show"Namespace Name may only contain letters, numbers, underscore and backslashes at begining and end only." 

Expected result- Backslashes are not allowed , only forward slashes(/) are allowed. Need to replace the text "backslashes" "in the error message with 'forward slash'
![Screenshot 2021-11-01 at 1 01 07 PM](https://user-images.githubusercontent.com/91254708/139637689-d37f1cc6-2f68-461f-8cdc-88be2e6a60f9.png)

**Comment by saniatg** [comment]
@nalwa 
It is fixed when adding namespace but when edit the error is still incorrect
![Screenshot 2021-11-11 at 3 15 36 PM](https://user-images.githubusercontent.com/91254708/141276392-873faa94-b2e6-40b2-98e2-0f7476c440aa.png)

**Comment by saniatg** [comment]
Verified and is working fine

**Comment by rupalichavan9860** [comment]
Verified on production
