### ISSUE TITLE
Camps are listing incorrectly under delegated supporter 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#881]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/139646460-982f49ae-ee5c-4efc-8dc5-5951a45e584f.png)

![image](https://user-images.githubusercontent.com/40416610/139646407-2b2f7a5e-ef1f-4a2b-8b1e-67577dcd7bb1.png)

**Comment by rupalichavan9860** [comment]
This is because delegated support is not getting removed when direct supporter removes their support from camp

**Comment by karun0607gautam** [comment]
@rupalichavan9860 It is not reproducible now after fix in 834. also i have fixed the mentioned topic from db. Please test and if you found any scenario then mentioned that

**Comment by rupalichavan9860** [comment]
Yes. I am also not able to reproduce this now so for now moving this to staging approved
