### ISSUE TITLE
Page crashes-Token mismatch error when the user hits any action button after expiry of the session in case the page is left idle

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#883]
Navigate to Create topic or Manage support page, and leave it idle . Do not perform any action.
After sometime when click on 'Create topic or 'Submit ' button when trying to support any camp or on click any action button , the page crashed

Expected result: The page should not crash instead redirect to the login page when trying to submit any action after expiry of the session in case the page is left idle
NOTE: The same issue is in admin as well. Share module-> when click 'add share ' button after the expiry of the session in case the page is left idle.
![Screenshot 2021-11-01 at 5 35 05 PM](https://user-images.githubusercontent.com/91254708/139791759-50eac6f2-50a2-4af9-b070-9529c65db8b4.png)

**Comment by saniatg** [comment]
@HamzaBinMansoor could be please correct
 The content for the error message when token expires seems incorrect from user perspective
Currently displaying as "Your action could not performed due to mismatch token, please log in again"
Instead it should be 
"Your session has expired, please log in again
![Screenshot 2021-11-19 at 11 24 37 AM](https://user-images.githubusercontent.com/91254708/142582462-d4f4be54-2aaf-40ee-bd25-8a40892cf256.png)
"

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Tested & Verified on Production
