### ISSUE TITLE
 When user click on "Click Here To View" from camp creation email, topic name is getting highlighted

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#884]
Pre-condition :  user is logged in
Steps to reproduce : 
1. Create new camp
2. Click on  "Click Here To View" from email 
3. Observe behavior

Expected Result : 
It should highlight camp name 

Actual Result : 
Topic name is getting highlighted

![image](https://user-images.githubusercontent.com/40416610/139797161-6598c75d-6834-4a3a-9a21-91a9db6cff39.png)

![image](https://user-images.githubusercontent.com/40416610/139797254-aeb3ba19-0bc5-4f1e-9bce-1329c6d1086c.png)

**Comment by sunitamary** [comment]
Tested and Working Fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
