### ISSUE TITLE
 Submitter is not receiving email whenever new statement is submitted

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#885]
When user creates a new statement , user should receive "Thank you for contributing to Canonizer.com" email

**Comment by saniatg** [comment]
@sunilspr7 Not able to verify the ticket as when 'Adding a new statement ' for a camp on click 'Submit 'button page is crashing
![Screenshot 2021-11-18 at 11 29 44 AM](https://user-images.githubusercontent.com/91254708/142360956-6b596921-94c1-4a2d-8dd6-6e5edb5190e6.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Crash issue resolved and mail to the submitter is receiving when add new statement. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
