### ISSUE TITLE
Error messages for character length should be proper on Register page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#89]
Error messages for character length should be proper.
1.Enter more than 255 characters in "First Name" field.Error message should be "First Name may not be greater than 255 characters." instead of "The firstname may not be greater than 255 characters." 
2.Enter more than 255 characters in "Last Name" field.Error message should be "Last Name may not be greater than 255 characters." instead of "The lastname may not be greater than 255 characters."

**Comment by gautamv16** [comment]
@rupalichavan9860 fixed
