### ISSUE TITLE
Incorrect warning is displaying while supporting camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#892]
I am getting Incorrect warning while supporting camp in below scenario
"Rupali-Chavan" is delegating support to "Rupali cano" for camp "Rupali-Chavan"
![image](https://user-images.githubusercontent.com/40416610/140687377-8ea77859-a482-4b26-8458-588ec5c06370.png)

When Rupali-Chavan is trying to support "count camp1" directly , getting below warnings
![image](https://user-images.githubusercontent.com/40416610/140687422-7ff530a7-7ea0-4dc1-b296-5f566599b11f.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860 I have tested and It is working fine. Some old data had delegate support  issue so that you got  error. But now It is working fine.

**Comment by rupalichavan9860** [comment]
@sunilspr7 I am also not able to reproduce this. For now I am moving this to "Staging approved" and will reopen if found again

**Comment by rupalichavan9860** [comment]
I am able reproduce the issue .Please refer below screenshot
![image](https://user-images.githubusercontent.com/40416610/143190096-635815c2-057b-48f9-88b2-4532d80dcc7b.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860  Yes I have also got this issue. Here only second warring message will be shown.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
