### ISSUE TITLE
Issues related to pointer and color of the icons related to topic/camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#895]
Issue 1- The default grey icon is looking fine when there is no sub camps but when hover on it shows hand pointer which is wrong as it is not clickable instead show normal pointer

Issue 2- When create a new topic, icon is showing in grey , should show in blue color as it is expanding
![Screenshot 2021-11-09 at 12 57 06 PM](https://user-images.githubusercontent.com/91254708/140881971-6b8eb501-cb22-45aa-9172-10795cab9912.png)

**Comment by saniatg** [comment]
Issue 1 is  On canonizer main page :  canonized list

**Comment by vedantvyas0** [comment]
Tested and Working Fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Tested and Verified on Production
