### ISSUE TITLE
Canonizer 2.0 Wiki Text System (WTS)

### ISSUE THREAD

**Issue by akuks** [the-canonizer/canonizer.2.0#9]
1. WTS needs to implement to display the camp pages.
2. A tool or method needs to be developed to convert all versions of all camp statements from the purple wiki formatting used in the 1.0 system to the Wikimedia format.

**Comment by akuks** [comment]
**Wiki Parser**
For the time being, use one of the available PHP wiki parsers, some good ones are listed here:
https://www.mediawiki.org/wiki/Alternative_parsers

List of possibilities for initial wiki parser:
**Wiky.php**
*Link :* https://github.com/lahdekorpi/Wiky.php
*Description : * A tiny PHP library that uses only regular expressions to convert Wiki markup to HTML.
This one looks very simple, so if it is efficient, easy to understand and modify, and everything,

**Mediawiki2html_machine**
* Link: *https://github.com/JohannesBuchner/mediawiki2html_machine
*Description:* A pure-PHP Mediawiki to HTML converter

**PHP5 Wiki Parser**
*Link:* https://github.com/d2g/WikiParser
*Description:* Parser With Plugin Framework To Add Additional Syntax. Configurable for alternative markup i.e. PmWiki.

If the above two can’t be easily configured to handle canonizer.com add-ins (like canonized topic trees in statements), we will probably want to use this one.

**Comment by gautamv16** [comment]
@karun is working on this.

**Comment by gautamv16** [comment]
Need to replace img with file

**Comment by gautamv16** [comment]
Done
