### ISSUE TITLE
Live topic name is displaying when user click on topic name link name from proposed a change to topic email

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#900]
When user proposed a change to any topic and click on topic name link or click here to view, it is redirecting to agreement page and display updated topic name 

But Live topic name is displaying under Canonizer Sorted Camp Tree. Please refer attached screenshot for more details

![image](https://user-images.githubusercontent.com/40416610/141055853-0b42e157-93a5-4ef9-87ad-356ab416c7a0.png)

**Comment by ashish76** [comment]
@rupalichavan9860 This is issue has been resolved. The topic name is not getting updated in the camps tree due to the Nofilter criteria had set to true in the code. Please test this once again once deployed on staging and let me know if any issue persists.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
