### ISSUE TITLE
Upload File ---> Error  needs to be revised for file name

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#908]
Steps to reproduce :
1.Select upload file from left menu 
2.Upload file 
3.Give File Name with space 
4.And observe error 
In error its saying Name field ,it should be file name field

![File name field](https://user-images.githubusercontent.com/92429083/141424519-816604ff-dfcd-4385-a16b-e3d59a6be1b7.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified . You can move this to " Staging Approved "

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
