### ISSUE TITLE
Validations are missing for Password field on Register page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#91]
Expected Result:
Password must be combination of characters,numbers and special symbols. 
It must contains at least one special character.

Actual Result:
Password field is accepting only numbers/only characters/only alphanumeric.

Steps to reproduce:
1.Go to https://staging.canonizer.com/
2.Click on Register
3.Enter all mandatory fields
4.Do following scenarios for Password field:
     a.Enter only charachers in Password field or
     b.Enter only numbers in Password field or
     c.Enter alphanumeric text in Password field
5.Click on "Create your account" button

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.Validations are working

**Comment by rupalichavan9860** [comment]
@gautamv16 While performing negative testing I found the following issue
Password field is accepting spaces in password(leading,trailing or anywhere in password)
e.g. "  test@12345","test@12 12","test@12345  "

**Comment by gautamv16** [comment]
Saw my message on other ticket its not an issue. Close this ticket as per
the issue this ticket has been fixed.

**Comment by gautamv16** [comment]
@rupalichavan9860 its fine. pls close

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.closing this
