### ISSUE TITLE
Topic page is not getting loaded properly

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#911]
Please refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/141780149-d9766d14-4b96-40d9-9b45-254ec8504e01.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 It is coming due to circular support data in table. i have fixed it from db but i think you need to create this scenario again and note down the steps to reproduce it

**Comment by rupalichavan9860** [comment]
@gautamv16 Sure. I will try to reproduce it and provide steps

**Comment by rupalichavan9860** [comment]
As of now not able to reproduce this so closing this issue
