### ISSUE TITLE
 Page crashes  'Production env.' on click supported camp of Topic -Testing 13 oct 2021

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#914]
Click on this link
https://canonizer.com/user/supports/357?topicnum=350&campnum=5&namespace=19#camp_350_5
and
https://canonizer.com/topic/350-Testing-13-oct-2021/2-Test-camp-1

Then click on 'Camp 1 or Camp 3' under List of supporting camps for Topic -Testing 13 oct 2021
Page crashes
![Screenshot 2021-11-17 at 3 48 06 PM](https://user-images.githubusercontent.com/91254708/142182170-205c044a-550a-4d72-b40c-2749d41154cb.png)

![image_2021_11_17T10_01_03_862Z](https://user-images.githubusercontent.com/91254708/142182621-1c6c3d13-6491-4918-8c18-0ef64751478d.png)

**Comment by rupalichavan9860** [comment]
Working fine now so closing this issue
