### ISSUE TITLE
Responsive issues ( Tested in iPhone XS Max)- Camp statement ->Button design are missing and cancel does not work for the preview pop up

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#918]
Steps:

1. Go to any topic/camp
2. Click on Add Camp Statement
Issue 1- The button UI is missing for 'Preview'  next to 'Submit Statement' only text is seen

Issue 2- Click on the text 'Preview' pop up shows, now again for 'Cancel' the button design is missing and the cancel  functionality does not work 
![Skype_Picture_2021_11_18T09_28_48_964Z](https://user-images.githubusercontent.com/91254708/142389566-62c2790a-c0ad-4616-8ff4-ae37de0c7f3b.jpeg)

![Skype_Picture_2021_11_18T09_28_54_580Z](https://user-images.githubusercontent.com/91254708/142389684-d2c787d0-d830-43c3-99a5-003308781801.jpeg)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
Tested & verified on Production
