### ISSUE TITLE
Password field should have strength checker and guidelines on Register page.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#92]

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test

**Comment by rupalichavan9860** [comment]
@gautamv16 Tested.I think look & feel for Password guidelines should be more effective.
 Please let me know your thoughts

Current Look & Feel  : 
![image](https://user-images.githubusercontent.com/40416610/45050303-91120a00-b09e-11e8-9b85-3c226de77960.png)

Please refer Facebook sign up page or any other website for Password guidelines look & feel.
 
![image](https://user-images.githubusercontent.com/40416610/45050242-5ad48a80-b09e-11e8-862d-2bf897c33528.png)
![image](https://user-images.githubusercontent.com/40416610/45050265-6cb62d80-b09e-11e8-91ab-9aeb8b492603.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 looka and feel is ok. Its simpler and good. So please test functionality. If that works please close the issue. We will see in future about look and feel of complete canonizer.

**Comment by rupalichavan9860** [comment]
@gautamv16 Okay.I will focus on functionality and closing this
