### ISSUE TITLE
Camp forum : validations are missing for post/reply field 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#921]
As of now it is accepting space only and post is getting saved. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/142414018-19d71b1d-1d2a-49c2-bd93-fcd77540a1d9.png)

**Comment by akuks** [comment]
@rupalichavan9860 Can you please check this

**Comment by saniatg** [comment]
@akuks Not able to save a post. When click on thread and try to add  a post on click 'Submit' button , nothing happens.

**Comment by rupalichavan9860** [comment]
We forgot to test this issue after resolving page crash . Just tested and working fine on both staging and live so closing this issue
