### ISSUE TITLE
Incorrect Choice number/preference number displaying under Support Tree for camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#924]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create a new topic
4. Create 2 camps "Camp 1 " and "Camp 2" and support both camps
5. Update "Camp 2" : Make "Camp 1" as a parent camp of "Camp 2" 
6. Observe Choice number 

Expected Result : 
preference number/Choice number should be 1 as only one support is there

Actual Result : 
preference number/Choice number is displaying as 2. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/142594396-64992df5-5950-4595-89cb-69faf87d7efc.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by anilPodi** [comment]
@rupalichavan9860 this is working fine for me. 
![Screenshot from 2022-01-13 12-53-35](https://user-images.githubusercontent.com/96222726/149287750-7fd682ce-f2b8-4edd-9c59-dfd185c60d0d.png)

**Comment by rupalichavan9860** [comment]
Verified on production
