### ISSUE TITLE
Not able select sub camps of sibling camps as a parent camp while updating the camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#925]
Please refer below screenshots

![image](https://user-images.githubusercontent.com/40416610/142618821-6468d361-24ea-4fcd-8bda-58f9b42059a9.png)

When trying to update "Test camp 3" , can see below camps in parent camp drop down

![image](https://user-images.githubusercontent.com/40416610/142618953-f93e826f-ef7b-46ea-b806-bef5c4ebffc7.png)

Expected Result : 
It should also list "Camp 2" and "sub camp under camp2" in parent camp drop down

**Comment by saniatg** [comment]
Tested and is working fine. @rupalichavan9860 Please confirm

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
