### ISSUE TITLE
Incorrect warning displaying while supporting camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#926]
Please refer below screenshot : 
![image](https://user-images.githubusercontent.com/40416610/142633903-69b73ff1-dc15-48a0-8656-d267079ceabb.png)

![image](https://user-images.githubusercontent.com/40416610/142633938-97285222-06d1-489c-9f89-dd56f490c519.png)

when trying to support "camp 2", getting below incorrect warning

![image](https://user-images.githubusercontent.com/40416610/142634101-1d7124d4-e213-4543-9fec-5b895c12438f.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by bazeer** [comment]
Working

**Comment by sunitamary** [comment]
Tested and working @rupalichavan9860

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production

**Comment by rupalichavan9860** [comment]
Verified
