### ISSUE TITLE
Crash on forum detail post page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#933]
Steps
1. Go to camp forum and click on any thread from list of all camp threads.
2. Copy the URL->https://staging.canonizer.com/forum/276-Global-village/1-Agreement/threads/506
3. Now logout the application
4. Paste the URL on a new tab

Actual result- Page crashes
Expected result- Should redirect to login page

![Screenshot 2021-11-23 at 11 56 17 AM](https://user-images.githubusercontent.com/91254708/142979348-d57e6717-d87f-477f-ba7e-e996e39613dc.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested & verified on Production
