### ISSUE TITLE
Page crash on Registration Verification page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#935]
Precondition : 
User is not verified
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Click on  Log in
3. Click on Forgot Password
4. Enter non verified email address
5. Click on Submit
6. Click on "Request for Verification Code"
7. Enter non verified email address
8. Without entering "One Time Verification Code" click on "Submit" button

Actual Result : Getting below page crash
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/143019430-f54b85bf-fc65-470b-a796-1fb8e5fc5d2d.png)

**Comment by rupalichavan9860** [comment]
I would suggest as soon as user click on "Request for Verification Code" , user should receive verification code on email and should redirect to "Registration Verification page" to enter the code

As of now user is redirecting to "Get Verification Code" page where user again need to enter non verified email address get verification code

**Comment by rupalichavan9860** [comment]
@kshitij1326 Tested. Still getting below issues
1. Getting 2 different emails with 2 different codes when user click on "Request for Verification Code"
2. When user click on "Submit" button without entering or entering incorrect code , user is getting new email every time(on each submit click)
Expected Result :  It should only display error message 

3. User can still able to see below enter email address screen and can request for validation code on single page
![image](https://user-images.githubusercontent.com/40416610/145383987-a1feca33-5f77-45a1-9fcf-6e5cb61266a1.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Verified and is working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860  Tested on production and it's working.Please confirm

**Comment by rupalichavan9860** [comment]
Verified
