### ISSUE TITLE
Menu selection is  going away from details section .Also tree arrow button is overlapping with text.

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#939]
Steps to reproduce : 
1.Navigate to https://staging.canonizer.com/ ( Issue produced on 
![Screenshot_1](https://user-images.githubusercontent.com/92429083/143195508-0aa16ffb-2453-4949-99c6-3b343fd43229.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Above mentioned issue is fixed now .But if you check pagination  ( 9 should be exactly beneath 1).Please verify this issue.
