### ISSUE TITLE
Pagination is going out of box in all the screens except laptop screen.

### ISSUE THREAD

**Issue by sunitamary** [the-canonizer/canonizer.2.0#940]
![Screenshot from 2021-11-24 10-56-00](https://user-images.githubusercontent.com/92773405/143208882-3edd4a3b-13f0-4e11-8187-7f9d7c7b70dd.png)

**Comment by sunitamary** [comment]
Tested and working fine. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sunitamary** [comment]
Verified on production.
