### ISSUE TITLE
Social account buttons are overlapping in login page.

### ISSUE THREAD

**Issue by sunitamary** [the-canonizer/canonizer.2.0#941]
![Screenshot from 2021-11-24 14-49-01](https://user-images.githubusercontent.com/92773405/143210599-af58f241-d505-460d-a4ee-db00469dd0b7.png)

**Comment by sunitamary** [comment]
Tested and working fine. @rupalichavan9860

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sunitamary** [comment]
Verified on production.
