### ISSUE TITLE
User can use another nick name for any contribution once used for post creation

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#942]
Steps to reproduce : 
1. Create topic by user "User A"
2. Go to Camp forum and create new thread
3. Login with another user and create new post in thread(First contribution)
4. Try to add another post/any other contribution to same topic

Expected Result : 
User should see previously selected nick name only in drop down

Actual Result : 
User can see all nick names of that user

Pleas refer attached screenshot 
![image](https://user-images.githubusercontent.com/40416610/143239789-cd388d6d-e7be-4b29-8d48-f1428d3583ed.png)

**Comment by rupalichavan9860** [comment]
@akuks Tested and this is fixed on thread post page but still I can see all nick names in drop down for other contributions

**Comment by rupalichavan9860** [comment]
@ahmed130544 As per discussed, please refer below places where we need to implement this
1. Create New Camp
2. Add Camp Statement
3. Create a new thread
4. Add Direct/Delegate Support
5. Topic Update
6. Camp Update
7. Statement Update

**Comment by rupalichavan9860** [comment]
@ahmed130544 Tested and verified

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and verified on production. Please confirm.

**Comment by rupalichavan9860** [comment]
Verified
