### ISSUE TITLE
Uniformity across the website- Need to replace register label by 'Sign up' 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#949]
Issue 1 - Replace register text by 'Sign up ' on the header
Issue 2- should be 'Sign up' space between  words Sign and up NOT 'signup' . Please implement the changes across the website. 

![Screenshot 2021-11-26 at 12 38 01 PM](https://user-images.githubusercontent.com/91254708/143541209-b5fa58fb-edee-43cd-bd73-548821222e0d.png)

**Comment by sunitamary** [comment]
In all 3 places it should display as "Sign up" rather on header its "Register" and in 2 other place its "signup". Issue is not yet fixed.
![Bug](https://user-images.githubusercontent.com/92773405/143866293-8ccf3be6-476b-44f5-a8af-c056306f5968.png)
@rupalichavan9860

**Comment by rupalichavan9860** [comment]
@kshitij1326 Can you please check this 
![image](https://user-images.githubusercontent.com/40416610/143867231-da40884f-a553-4344-83b6-3cc46b879778.png)

**Comment by kshitij1326** [comment]
The code is overwritten when merging, I will re-do. 
@rupalichavan9860  Is there need to change the url also from register to signup ?

**Comment by rupalichavan9860** [comment]
@kshitij1326 Yes. I would suggest it should be signup

**Comment by saniatg** [comment]
@rupalichavan9860 Tested & verified, please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
Tested and is working fine @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified on production
