### ISSUE TITLE
Issues while getting proposed change emails 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#951]
Case 1 : proposed change to topic

When someone submits any change to topic , direct supporters are getting proposed change email immediate after submission(without committing changes)

Case 2 : proposed change to camp

When someone submits any change to camp, direct supporters are getting proposed change emails after committing changes

Case 3 : proposed change to camp statement

When someone submits any change to camp statement , direct supporters are getting proposed change emails after committing changes

Expected Result : 
It should behave same in all 3 cases

Also I have one question in this  : 
As of now direct supporters can see changes submitted by another user even if changes are not committed yet and can see "I agree with this topic/camp/statement change" checkbox

Is this a right behavior or changes should be visible after committing?
@BrentAllsop Can you please confirm?

**Comment by BrentAllsop** [comment]
All 3 of these should use the same code, so let's get that fixed before closing this issue?

**Comment by rupalichavan9860** [comment]
I just checked submitted changes are visible to direct supporters even if changes are committed yet(in all 3 scenarios - camp/topic/statement change)
As per discussion 
1. Submitted changes must be visible to direct supporters only after committing 
2. Submitted changes must be visible to direct supporters after 1 hour grace period(even if not committed yet)

**Comment by rupalichavan9860** [comment]
Tested . Still changes are visible in below scenarios : 
Pre-condition :  Submit change by User(Who is not a supporter or topic/camp submitter)
1. Submit some changes in camp statement/camp/topic and do not commit changes and Logout ->without logging in go to Topic History/Camp History/Camp Statement History pages and changes are visible (even if not committed yet)
2. Submit some changes in camp statement/camp/topic and do not commit changes and Logout ->login with user(who is not a topic/camp submitter or change submitter or direct supporter), go to Topic History/Camp History/Camp Statement History pages and changes are visible (even if not committed yet)
3. Submit some changes in topic and do not commit changes and Logout ->login with user who is only supporter of the Agreement camp 
Topic History page is displaying blank for user who is only supporter of camp. Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/147669871-168403e3-e9b6-4303-ad1d-bed3dd7213e1.png)

**Comment by saniatg** [comment]
Also, email is being send after proposing change to statement for a camp before committing changes .  User has not commit the changes for the statement yet the email is being sent.

**Comment by saniatg** [comment]
Note: 2 emails are being received when proposing statement change for the first time only .
First before committing the changes & second after committing the changes.
Only one mail should be send to the user after committing the changes.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
