### ISSUE TITLE
Need space between Parent Camp and ":" on camp history page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#952]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/143851642-edd7394f-3c45-4b39-af25-1948a68d35d6.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
