### ISSUE TITLE
Preview button is missing on create camp page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#953]
Do we need preview pop up for create camp?
As of now preview pop up is available on Camp Update, Add Camp Statement, Statement Update but missing on create camp 

![image](https://user-images.githubusercontent.com/40416610/143852555-3ee32b87-63ef-4f3d-98ab-3e008da91286.png)

**Comment by BrentAllsop** [comment]
The purpose of the preview button, is to preview the wiki markup.
Both the camp and topic records, don't need this.
Therefore, we should only remove the preview button on the camp update page.
The same is true for both create and update forms.
Only preview on camp statements, nothing else needs a preview.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
