### ISSUE TITLE
Delegate emails are not working from 2nd level 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#954]
Users are not getting delegate support added /removed emails from second level 

Scenario : 

![image](https://user-images.githubusercontent.com/40416610/143862451-b7b69bc1-b45a-4b46-ae9d-8749e89f4473.png)

In above scenario when "karun gautam" added/ removed delegate support to/from "Rupali cano" , "Rupali cano" should receive emails

Actual Result : 
"Rupali cano" is not receiving delegate support added/removed  emails

**Comment by nalwa** [comment]
@rupalichavan9860  it is fixed  from my side, please re-test once and verify
Thanks!

**Comment by rupalichavan9860** [comment]
@nalwa Still user is not receiving delegated support added email when another user delegate their support

**Comment by rupalichavan9860** [comment]
@nalwa User is not receiving removed delegated support email

**Comment by rupalichavan9860** [comment]
@nalwa I found some minor issues in emails : 
1 . Need to remove camp name from delegated support email . Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/149295335-86399306-2022-4dd8-8ad0-94a197288f9f.png)

2. Link to nick names are missing in old emails 

![image](https://user-images.githubusercontent.com/40416610/149295609-776fd28c-53d0-4c76-99a8-92b22696771f.png)

3. Removed  delegated support subject is different for different users

![image](https://user-images.githubusercontent.com/40416610/149295839-d67cdaca-6ee4-4d7f-a7f8-ca7ff8ed4189.png)

![image](https://user-images.githubusercontent.com/40416610/149295916-0cf73bd0-1d68-4608-a373-25267d68b6e9.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Getting 2 different emails for adding delegate support 
![Imgae 1](https://user-images.githubusercontent.com/92429083/149903615-eeccb891-ee59-4bf6-992e-0facf9e354cc.png)
![Image 2](https://user-images.githubusercontent.com/92429083/149903641-63625328-d0a1-4c1e-a8eb-c01c4c7bd845.png)

**Comment by rupalichavan9860** [comment]
Created new ticket for last commented issue so moving this to staging approved

**Comment by rupalichavan9860** [comment]
Verified on production
