### ISSUE TITLE
Change "Unique Number" column heading on Nick Names tab to "Nick Name ID".

### ISSUE THREAD

**Issue by BrentAllsop** [the-canonizer/canonizer.2.0#960]
![image](https://user-images.githubusercontent.com/6559312/144098287-f1269721-1cf2-4618-bcef-392a98d05f8c.png)

**Comment by BrentAllsop** [comment]
We want this to match the column name in the teams accounting sheet and everywhere else:
https://docs.google.com/spreadsheets/d/1VS37AVL8zARpZwW9eubZIGBuFhDrc6GMilp8I7MsnQQ/edit#gid=0

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
