### ISSUE TITLE
Supported camp list is missing on Supported Camps page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#961]
Please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/144176777-4eb2c608-5e88-4052-92e8-a93a2df973c6.png)

Can see on user supports page

![image](https://user-images.githubusercontent.com/40416610/144176891-fc192072-9cbf-4bcc-b1c4-e14ab888e3e7.png)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by saniatg** [comment]
@rupalichavan9860 Working fine on Production. Please confirm

**Comment by rupalichavan9860** [comment]
verified
