### ISSUE TITLE
First and last name is displaying in warning instead of nick name

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#963]
When any user delegated their support to someone else in camp and trying to support that camp directly user can see warning "Warning! You have already delegated your support for this camp to user **Rupali Chavan**. If you continue your delegated support will be removed."

please refer attached screenshot

![image](https://user-images.githubusercontent.com/40416610/144224041-c85f52bf-5a41-47a5-8b88-e88c968b43f2.png)

Issue :  In warning user name is displaying as "firstname lastname"
Expected Result  :  It should be "nick name" as different user can have same first and last name

**Comment by rupalichavan9860** [comment]
This issue is also exists in delegated support added/removed emails, Please refer below screenshot

![image](https://user-images.githubusercontent.com/40416610/144225297-d3fc043e-02ac-402d-80ee-00f7bdae59dd.png)

![image](https://user-images.githubusercontent.com/40416610/144225420-57f0028c-cf2d-4f03-90c5-dda3f0abca3c.png)

**Comment by saniatg** [comment]
@rupalichavan9860 Tested & Verified, please confirm

**Comment by rupalichavan9860** [comment]
@kshitij1326 I can see a change in delegated support removed subject line .Previously it was "Rupali C has removed their delegated support from Rupali cano in Regression 3 dec 2021 / Test camp 2"

Now it is displaying as "Rupali C has removed their support from Regression 3 dec 2021 / Test camp 2"

![image](https://user-images.githubusercontent.com/40416610/144834140-942a1ead-870e-4d8a-8b15-404ef2c7b2cd.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
