### ISSUE TITLE
User is not able to change support order of camp

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#964]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create any new topic
4. Create 2 camps under topic "camp 1" and "camp 2"
5. Support both camps
6. Click on any camp name  "camp 1" or "camp 2"
7. Click on "Directly Join or Manage Support"
8. Try to change support order of camp

Expected Result : 
User should able to drag & drop the camp 

Actual Result  : 
User is unable to drag & drop the camp /change support order of camp

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production.

**Comment by rupalichavan9860** [comment]
Verified
