### ISSUE TITLE
Replace standard pointer by link(hand) pointer for Canonizer Sorted Camp Tree when create a topic as it can expand/collapse

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#965]
1. Create a topic
2. Hover on the branch icon

Currently showing standard pointer instead replace with a link( hand) pointer as the branch is clickable

![Screenshot 2021-12-02 at 5 36 59 PM](https://user-images.githubusercontent.com/91254708/144420831-1439aa97-2bc9-417e-92dc-a20a03e6da8a.png)

**Comment by saniatg** [comment]
Not fixed , still seeing normal pointer

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
