### ISSUE TITLE
Nick Names ---> Visibility Status column  is cutting off from user's view

### ISSUE THREAD

**Issue by Wajeeha1995** [the-canonizer/canonizer.2.0#966]
![Screenshot_1](https://user-images.githubusercontent.com/92429083/144429174-0bbb64ce-ed56-44a4-9ac7-61cc18b60733.png)
Issue produced on **Galaxy Fold**

**Comment by Wajeeha1995** [comment]
@rupalichavan9860  Tested and verified on staging.You can move this to " Staging Approved "

**Comment by rupalichavan9860** [comment]
Verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested on production, its looking fine now.
