### ISSUE TITLE
Page crash while updating camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#967]
Steps to reproduce : 
1. Go to https://staging.canonizer.com/
2. Login with valid email and password
3. Create new topic
4. Create 2 camps "camp 1" and "Camp 2" under topic
5. Support both camps
6. Update Camp 1 : Change parent camp as "Camp 2" from "Agreement"
7. Click on "Camp 2" and apply filter as of date as yesterday's date
8. Click on Topic creation timestamp link
9. Click on Camp creation timestamp link
10. Click on Manage/Edit Camp
11. Click on Submit Camp update based on this
12. Update Camp 2 : Change parent camp as "Camp 1" from "Agreement"
13. Select filter as Default and observe

Actual Result : 
Getting Below page crash

![image](https://user-images.githubusercontent.com/40416610/144557861-8a601f53-e07a-4896-afe8-216652580659.png)

**Comment by bazeer** [comment]
Verified and completed

**Comment by sunitamary** [comment]
Tested and working fine @rupalichavan9860

**Comment by rupalichavan9860** [comment]
@kshitij1326 This is working fine for first level child camp but still getting page crash for scenario like below screenshot 

![image](https://user-images.githubusercontent.com/40416610/145431045-45652918-f2f5-4795-acc8-11148cfc5014.png)

When trying to make "Test camp 3" as a parent of "test camp 1"
![image](https://user-images.githubusercontent.com/40416610/145431109-299bfd2f-cabd-4849-ae07-d4bb7459200d.png)

**Comment by rupalichavan9860** [comment]
@kshitij1326 As per discussed in call we need to fix this for above scenario so moving this "To Do"

**Comment by rupalichavan9860** [comment]
Tested with all possible scenarios and as of now it is working fine

**Comment by rupalichavan9860** [comment]
Verified on production
