### ISSUE TITLE
After applying 'as of date' user can see child camp as a parent camp

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#968]
Steps

1. Create a new topic
2. Now create a camp 'camp1'  and support it
3. Create another camp 'camp2' and support it too
4. Edit camp1 and make 'camp2' parent of 'camp1'
5. Click on camp2 and apply 'As of date' filter and select yesterday's date to change parent of camp2
6. Now click on topic time stamp link
7. Not click on camp time stamp link
![Screenshot 2021-12-03 at 12 24 32 PM](https://user-images.githubusercontent.com/91254708/144558520-4bf8c538-f878-481b-8748-32ed212efb12.png)
8.Now edit camp 2
9.You can see 'camp1' in the drop down as a parent camp

Question  : Should it allow to update 'camp2'  when apply 'as of date' because if I Update parent camp to 'camp1' it gives crash refer ticket #967

**Comment by saniatg** [comment]
Tested & verified

**Comment by rupalichavan9860** [comment]
@kshitij1326 As per discussed scenario on call we need to fix this

**Comment by rupalichavan9860** [comment]
Tested with all possible scenarios and as of now it is working fine

**Comment by saniatg** [comment]
Tested on production and is working fine @rupalichavan9860 please confirm

**Comment by rupalichavan9860** [comment]
Verified on production
