### ISSUE TITLE
Camps are not displaying(apply filter as Default) and score count is displaying 0(when filter applied is as of date) when "camp 1 " selected as parent camp of "camp 2" even if "camp 2" is already parent camp of "camp 1"(Note after applying as of date filter)

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#969]
Steps

1. Create a new topic
2. Now create a camp 'camp1' and support it
3. Create another camp 'camp2' and support it too
4. Edit camp1 and make 'camp2' parent of 'camp1'
5. Click on camp2 and apply 'As of date' filter and select yesterday's date to change parent of camp2
6. Now click on topic time stamp link
7. Not click on camp time stamp link
8.Now edit camp 2
9.You can see 'camp1' in the drop down as a parent camp
10. select 'camp1' as parent and update 'camp2'

Issue 1- score count is displaying 0(when filter applied is as of date) when "camp 1 " selected as parent camp of "camp 2" even if "camp 2" is already parent camp of "camp 1"(Note after applying as of date filter)

![Screenshot 2021-12-03 at 1 23 22 PM](https://user-images.githubusercontent.com/91254708/144565753-9b8fc5b8-fbca-440e-a89a-ae8c93cb7a80.png)

Issue 2-Camps are not displaying(apply filter as Default) 
![Screenshot 2021-12-03 at 1 24 04 PM](https://user-images.githubusercontent.com/91254708/144565897-c7529571-288a-4eb3-aef1-b4c066a71fa2.png)

NOTE-> Related issues to take into consideration when looking at this issue
#967 #968

**Comment by rupalichavan9860** [comment]
@kshitij1326 As per discussed scenario on call we need to fix this

**Comment by rupalichavan9860** [comment]
Tested with all possible scenarios and as of now it is working fine

**Comment by rupalichavan9860** [comment]
Verified on production
