### ISSUE TITLE
"Forgot Password" Link name is incorrect on Login page

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#97]
Expected Result:
Link  name should be "Forgot Password".
Actual Result:
Link   name is displaying as "Forget Password".
![image](https://user-images.githubusercontent.com/40416610/42024297-7336c29a-7adf-11e8-9f61-d932134e0ea4.png)

**Comment by gautamv16** [comment]
@rupalichavan9860 done

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested..Verified
