### ISSUE TITLE
News Feeds block layout is not displaying properly when Edit News and Delete News links are not available

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#971]
Please refer below screenshot : 

Screenshot 1: When News Feeds section having Edit News and Delete News links 
![image](https://user-images.githubusercontent.com/40416610/144596823-c45eef02-b99d-4584-a596-a063d2515aba.png)

Screenshot 1: When News Feeds section not having Edit News and Delete News links 
![image](https://user-images.githubusercontent.com/40416610/144596875-74b5898c-3f74-467b-96eb-46f9f67eb329.png)

**Comment by saniatg** [comment]
@rupalichavan9860 tested and working fine. Please confirm

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested & working fine on Production.

**Comment by rupalichavan9860** [comment]
Verified
