### ISSUE TITLE
User is both delegated and direct support of camps on one topic

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#974]
Steps to reproduce : 
1. Login with User A and Create new topic 
2. Create 2 camps : Test camp 1 and Test camp 2
3. Support "Test camp 1"
4. Login with another user "User B" and delegate support to "User A" in "Test camp 1"
5. Direct support to "Test camp 2" (It will remove delegated support from "User A" in "Test camp 1")
6. Again go to "Test camp 1" and click on delegate your support for User A
7. Click on Submit
Actual Result : 
User B is now direct supporter of  "Test camp 2" and delegated supporter of "User A" in "Test camp 1"

![image](https://user-images.githubusercontent.com/40416610/144836448-fe6c3009-2b8f-4842-ac5a-16c9ab53dcd3.png)

It looks like issue to me . As per functionality, there can be no way to do both delegated and direct support of camps, on one topic.
@BrentAllsop Please confirm

**Comment by BrentAllsop** [comment]
Yes, definitely an issue.  If you direct support a camp, it should put a termination time on delegated support.  (If you set as-of to just before that time, you should see that.)  Same for delegating support, should put a termination time on all directly supported camps in that topic.

**Comment by rupalichavan9860** [comment]
@BrentAllsop Thank you for the confirmation

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
