### ISSUE TITLE
Login page should have "Register" button for new users.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#98]

**Comment by gautamv16** [comment]
@rupalichavan9860 pls test and close

**Comment by rupalichavan9860** [comment]
@gautamv16  Retested and verified.
But it should be "Don't have an account? Sign up Now" instead of "Don't have account Signup Now"

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested .
It should be "Don't have **an** account? Sign up Now" instead of "Don't have account? Signup Now"

**Comment by gautamv16** [comment]
@rupalichavan9860 retest

**Comment by rupalichavan9860** [comment]
@gautamv16 Retested.Verified
