### ISSUE TITLE
User is receiving different emails for different camps (when supporter of all camps) when delegated supporter removes their support

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#980]
Steps to reproduce : 
1. Login with "user 1" and Create new topic
2. Create 5 camps : "Camp 1", "Camp 2",  "Camp 3", "Camp 4", "Camp 5" and support all 5 camps

![image](https://user-images.githubusercontent.com/40416610/145393127-0f31411e-4cad-46d2-8b94-cbc9b6b34bb8.png)

3. Login with another user and delegate support to "user 1" in any camp say "Camp 1"

![image](https://user-images.githubusercontent.com/40416610/145393425-5c4602b2-92da-4d41-9784-1039c5622772.png)

Delegate support will get added to all camps

![image](https://user-images.githubusercontent.com/40416610/145393573-aedcac4e-9416-44ea-a8c6-c7bcc876e051.png)

But User 1 is getting only one mail(Note : Camp 5 is displaying in email), below is the screenshot

![image](https://user-images.githubusercontent.com/40416610/145393745-f0fee266-43bd-4435-bd19-5b74a3577b27.png)

**Question : User is delegating support to another user. Do we need to specify all camps in one email? as of now it is displaying last camp only**

4. Remove delegated support from below 
![image](https://user-images.githubusercontent.com/40416610/145394217-6caccfe6-237a-49a2-b2a4-9ea34af456f0.png)

Issue  : User 1 is receiving 5 different emails for each camp when user 2 removes delegated support from User 1

![image](https://user-images.githubusercontent.com/40416610/145394506-156797ce-0e18-4581-93a6-39569b7d282e.png)

Expected Result : User should receive only 1 email when delegated supporter removes their support
@BrentAllsop Please confirm

**Comment by BrentAllsop** [comment]
Yes, this is an issue, Reena Nalwa also pointed out that we have a similare issue with subscribers getting too many e-mails in the same way.  This is an issue.  There should only be one e-mail go out in these cases.

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have tested this ticket and the previous issue is fixed in which the user receives 5 different emails for each camp when user 2 removes delegated support from User 1

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 I have 1 doubt in this 

**Steps to reproduce :**

1. Login with **User 1** and Create new topic
2. Create 5 camps : "Camp 1", "Camp 2", "Camp 3", "Camp 4", "Camp 5" and support all 5 camps
![Image 1](https://user-images.githubusercontent.com/92429083/146892190-7a4c6b4b-dd82-4bbb-b9fb-b7e327def5fb.png)
3. Login with another user  **user 2** and delegate support to "user 1" in any camp say "Camp 1"
4. **User 1** is getting email mail(Note: Only Camp 1 is displaying ), below is the screenshot
![2](https://user-images.githubusercontent.com/92429083/146894232-1dbf1ad1-be75-4eb7-adde-4275b3fa11f8.png)

5. When **User 2** remove their delegate support 
6. **.User 1** receive an email (Note: All  5 Camps are  displaying ), below is the screenshot)
![3](https://user-images.githubusercontent.com/92429083/146894053-8f24a04f-b93d-4a0e-b04b-2397dc13b3fa.png)

**Comment by rupalichavan9860** [comment]
Not able to check removed delegated email as user is not receiving it, Will check after fix #954

**Comment by rupalichavan9860** [comment]
We have created related tickets separately and assigned "28th release" labels on it so moving this ticket to "Staging approved"

**Comment by rupalichavan9860** [comment]
Verified on production
