### ISSUE TITLE
Invalid link should not be accepted when add /edit news

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#981]
Steps:

1. Go to any topic/camp
2. click on'Add news' or Edit News button
3. add invalid  'Link'  any special char or random text before the https e.g.-> ct..@@https://staging.canonizer.com/ , now on click 'Create  News' 

Actual result- News created successfully with an invalid link
Expected result- Invalid link must not be acceptable must give an error when click on button 'Create News'
![Screenshot 2021-12-09 at 3 40 04 PM](https://user-images.githubusercontent.com/91254708/145400441-03fd636e-c128-412a-b096-b1556506f287.png)

**Comment by saniatg** [comment]
Tested & Verified

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested & is working fine on Production. Please confirm

**Comment by rupalichavan9860** [comment]
Verified
