### ISSUE TITLE
Text is irrelevant on "List of All Camp Threads" when click button 'Top 10' for the mentioned scenario

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#982]
Steps"
Go to any Topic which has 1 or more threads but NO posts under it.
When click button 'Top 10' it shows text as 'No threads available for this topic. Start New Thread' BUT there are threads already created for the topic .
So the message is irrelevant in this case
![Screenshot 2021-12-10 at 11 27 26 AM](https://user-images.githubusercontent.com/91254708/145527048-1410d4ed-2de5-4c6f-ae98-aebd1d15566e.png)

![Screenshot 2021-12-10 at 11 51 51 AM](https://user-images.githubusercontent.com/91254708/145527182-73df3bf1-3d73-4d5a-83a9-fbb51593071b.png)

**Comment by sunilspr7** [comment]
@saniatg  and @rupalichavan9860  I have changed this message "No threads available for this topic " to  "No top 10 threads available for this topic"
because in top 10 thread show based on condition, if  thread have any replies then show in top 10 list.

**Comment by anilPodi** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested and is working fine on Production
