### ISSUE TITLE
Old "Click Here To Reset Password" link is working for second time

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#984]
Once user reset passwords using reset password link, it should be expired
It should show message like "The Password Reset Link Has Expired And The Request another"

As of now user is able to reset password using old links also

**Comment by rupalichavan9860** [comment]
Not able to test this as getting page crash on forgot password page .Please refer #1009

**Comment by kshitij1326** [comment]
@rupalichavan9860  this was due to migration on staging server. Please check again.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
