### ISSUE TITLE
Incorrect arrows for the left side navigation menu

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#987]
Go to : https://staging.canonizer.com/

 On the left side navigation menu  for ( Canonizer Algorithm & As of ) Section the arrows are sidewards when the are expandable, which is incorrect , it should be downwards by default.
 
![Screenshot 2021-12-13 at 5 10 47 PM](https://user-images.githubusercontent.com/91254708/145806850-a144a339-6e21-4b44-bc21-6bf2ad720de3.png)

**Comment by saniatg** [comment]
Tested and is working fine.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by saniatg** [comment]
@rupalichavan9860 
Tested and working fine on Production

**Comment by rupalichavan9860** [comment]
Verified
