### ISSUE TITLE
#error message position and asterisk symbol issue

### ISSUE THREAD

**Issue by bhargavkc** [the-canonizer/canonizer.2.0#988]
if confirm password doesn't match "The password confirmation does not match." this error mesage should be below confirm password input box below and captch is also required field so it should also have asterisk symbol.
![error](https://user-images.githubusercontent.com/95272342/145807144-a99d4f4e-7c92-496f-8e83-02d10ff92872.png)

**Comment by rupalichavan9860** [comment]
@sunilspr7 "The password confirmation does not match." error message should be below confirm password field , As of now error message is displaying at 2 places .Please refer below screenshot

![image](https://user-images.githubusercontent.com/40416610/146722002-e6d4330d-deb4-42f0-86ad-dfc7c428adc0.png)

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on staging . You can move this to " Staging Approved "

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by Wajeeha1995** [comment]
@rupalichavan9860 Tested and verified on production.

**Comment by rupalichavan9860** [comment]
Verified
