### ISSUE TITLE
"atleast" is not a correct word. The correct version is “at least"

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#992]
On every password guidelines and error messages I found word "atleast" which is not a correct word. It should be “at least"

Need to change this on below pages : 
1. Sign up 

![image](https://user-images.githubusercontent.com/40416610/146152489-9bfecbff-0d08-419b-b118-f8ed74e3ed6d.png)

![image](https://user-images.githubusercontent.com/40416610/146152686-eae1f41f-d97f-474d-8050-b06932b28ce5.png)

2. Reset Password

![image](https://user-images.githubusercontent.com/40416610/146152562-845d935d-c02a-484f-aa77-d7a173622695.png)

![image](https://user-images.githubusercontent.com/40416610/146152751-de074e65-3703-4078-b896-00a931a2a880.png)

3. Change Password

![image](https://user-images.githubusercontent.com/40416610/146152902-e4d33754-ac12-4b15-bfd8-1fc5ab7281ff.png)

**Comment by anilPodi** [comment]
@rupalichavan9860 Not fixed in error messages except in tooltips.
![Screenshot from 2022-01-14 13-24-56](https://user-images.githubusercontent.com/96222726/149473838-f844e1b9-4612-4632-a685-bf6af214e48f.png)
![Screenshot from 2022-01-14 13-25-40](https://user-images.githubusercontent.com/96222726/149473841-a2fc5a93-9e35-4012-a898-4dfc96aff716.png)
![Screenshot from 2022-01-14 13-28-05](https://user-images.githubusercontent.com/96222726/149473849-8f36e2ad-6185-47ff-a379-291576929bf2.png)

**Comment by anilPodi** [comment]
![Screenshot from 2022-01-14 13-44-07](https://user-images.githubusercontent.com/96222726/149474029-042d09bb-6db3-4b04-b753-0721bd029a62.png)

**Comment by anilPodi** [comment]
@rupalichavan9860 working fine in all 3 scenarios. The word "at least" works fine in all error messages and tooltips. 
![Screenshot from 2022-01-17 09-43-56](https://user-images.githubusercontent.com/96222726/149709076-a0a30892-69d0-4ddc-9ec9-55399e02ecea.png)
![Screenshot from 2022-01-17 09-47-45](https://user-images.githubusercontent.com/96222726/149709082-c11ae4d3-0e22-4f60-921f-e90f59738b6f.png)

![Screenshot from 2022-01-17 09-39-52](https://user-images.githubusercontent.com/96222726/149709069-3d2c80e5-d439-479b-885c-75513cf78bd0.png)

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Not able to test this on reset password page as I am getting page crash on forgot password page

**Comment by rupalichavan9860** [comment]
Verified on production
