### ISSUE TITLE
Thread name is accepting special characters while updating thread name 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#993]
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/146160019-734d8d91-9a76-492e-afa3-aafc39ee9133.png)

and on create thread it is displaying below error message when trying to create thread with special characters

![image](https://user-images.githubusercontent.com/40416610/146160228-73a064a7-92da-45e3-9964-2dc448e7ea8d.png)

**Comment by anilPodi** [comment]
Tested and Verified. Working fine. Accepting only Alphabets and Numbers, taking no special characters.

**Comment by rupalichavan9860** [comment]
Tested and verified

**Comment by rupalichavan9860** [comment]
Verified on production
