### ISSUE TITLE
Incorrect error message is displaying when user is trying update the thread name without any changes

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/canonizer.2.0#995]
Steps to reproduce : 
1. https://staging.canonizer.com/
2. Go to Browse and click on any topic (Should have own threads)
3. Go to Camp Forum and click on My Threads
4. Click on Edit icon
5. Directly click on "Submit" button without any changes

Expected Result : 
It should save and redirect to list of all camps thread

Actual Result : 
It is displaying error message "Thread title must be unique" 
Please refer attached screenshot 

![image](https://user-images.githubusercontent.com/40416610/146165506-7553c0fb-76f7-4d08-81f4-8d53a6d1e60a.png)

**Comment by saniatg** [comment]
@sunilspr7 Now error message is not showing BUT on click  'Submit' button it is not redirecting to the  list of all camps thread

**Comment by sunilspr7** [comment]
@saniatg please confirm with @rupalichavan9860 . Because when we update title of thread then show title updated success message.

**Comment by saniatg** [comment]
@sunilspr7 It is approved as discussed  with @rupalichavan9860 .

**Comment by rupalichavan9860** [comment]
Verified on production

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and is working fine on Production
