### ISSUE TITLE
Edit thread name, when update and click 'Submit' user should redirect to List of All Camp Threads page. Currently user remains on the edit page only

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#996]
![Screenshot 2021-12-15 at 3 18 34 PM](https://user-images.githubusercontent.com/91254708/146166461-c07be6a6-95de-49e0-a4fc-c8cafecd874e.png)

**Comment by anilPodi** [comment]
tested and verified

**Comment by anilPodi** [comment]
tested with different scenarios( with edit and without edit on different threads and its redirecting to LIst of All Camp Threads.

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on production
