### ISSUE TITLE
Edit thread page layout must be uniform 

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#997]
Page height and width should be uniform . As of now page height and width is displaying smaller than other pages. Please refer attached screenshot
![Screenshot 2021-12-15 at 3 38 32 PM](https://user-images.githubusercontent.com/91254708/146167038-3735872b-7ed0-4139-8e51-de479627d609.png)

**Comment by rupalichavan9860** [comment]
This issue is fixed, but found another layout issue in smaller devices so added new new for this #1036

**Comment by saniatg** [comment]
@rupalichavan9860 Tested and working dine on Production.

**Comment by rupalichavan9860** [comment]
Verified
