### ISSUE TITLE
Responsive issues on edit thread title page

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/canonizer.2.0#999]
1-> Asterisk sign is not aligned with the input field
2-> Submit button must be aligned w.r.t. the title field
3-> Text "List of All Camp Threads" must be wrapped if screen is small and left aligned for proper alignment
4-> White background must be uniform, currently shows half grey on right

![Screenshot 2021-12-15 at 3 51 26 PM](https://user-images.githubusercontent.com/91254708/146169638-52c494f4-0956-430e-b11c-217dc2d30d6c.png)

**Comment by sonalizibtek** [comment]
Tested and verified. @rupalichavan9860  confirm once

**Comment by rupalichavan9860** [comment]
Verified

**Comment by sonalizibtek** [comment]
Tested and Verified in Production @rupalichavan9860  Please confirm once

**Comment by rupalichavan9860** [comment]
Verified
